// Application-related translations - submitting, managing, accepting, rejecting applications
export const applications = {
  // Application Dialog
  'application.title': 'Откликнуться на задачу',
  'application.proposedPrice': 'Ваша цена',
  'application.pricePlaceholder': 'Введите вашу цену в левах',
  'application.timeline': 'Когда можете начать?',
  'application.timelineToday': 'Сегодня',
  'application.timeline3days': 'В течение 3 дней',
  'application.timelineWeek': 'В течение недели',
  'application.timelineFlexible': 'Гибкий',
  'application.hoursShort': 'ч',
  'application.message': 'Почему вы лучше всего подходите?',
  'application.messagePlaceholder': 'Поделитесь своим опытом и почему вы идеально подходите для этой задачи...',
  'application.messageInfo': 'Сосредоточьтесь на навыках и опыте. Контактной информацией можно обменяться после принятия заявки.',
  'application.characterCount': '{{current}}/{{max}} символов',
  'application.submit': 'Отправить заявку',
  'application.submitting': 'Отправка...',
  'application.cancel': 'Отмена',
  'application.success': 'Заявка отправлена!',
  'application.successMessage': 'Владелец задачи рассмотрит вашу заявку и скоро ответит.',
  'application.viewApplication': 'Посмотреть мою заявку',
  'application.browseOther': 'Просмотреть другие задачи',
  'application.errors.priceRequired': 'Цена обязательна',
  'application.errors.priceMin': 'Цена должна быть больше 0',
  'application.errors.timelineRequired': 'Сроки обязательны',
  'application.errors.messageRequired': 'Сообщение обязательно',
  'application.errors.messageMin': 'Сообщение должно содержать не менее 30 символов',
  'application.errors.messageMax': 'Сообщение не может превышать 500 символов',
  'application.errors.noPhoneNumbers': 'Номера телефонов не разрешены в заявках. Вы можете обменяться контактной информацией после принятия заявки.',
  'application.errors.noUrls': 'URL-адреса и ссылки не разрешены в заявках. Вы можете поделиться портфолио после принятия заявки.',
  'application.errors.noEmails': 'Адреса электронной почты не разрешены в заявках. Вы можете обменяться контактной информацией после принятия заявки.',
  'application.alreadyApplied': 'Вы уже откликнулись на эту задачу',
  'application.cannotApplyOwnTask': 'Вы не можете откликнуться на свою собственную задачу',
  'application.budget': 'Бюджет',
  'application.tipClientBudget': 'Подсказка: Бюджет клиента {{min}} - {{max}} лв',
  'application.tipShareExperience': 'Подсказка: Поделитесь своим опытом, чтобы выделиться',
  'application.successSteps.quickReview': 'Быстрая проверка',
  'application.successSteps.getResponse': 'Получить ответ',
  'application.successSteps.startWork': 'Начать работу',

  // Applications Management
  'applications.title': 'Заявки',
  'applications.count': 'заявок',
  'applications.sortBy': 'Сортировать по',
  'applications.sortNewest': 'Сначала новые',
  'applications.sortPriceLow': 'Цена: От низкой к высокой',
  'applications.sortPriceHigh': 'Цена: От высокой к низкой',
  'applications.sortRating': 'С лучшим рейтингом',
  'applications.sortExperience': 'Самые опытные',
  'applications.filterAll': 'Все',
  'applications.filterPending': 'В ожидании',
  'applications.filterAccepted': 'Принятые',
  'applications.filterRejected': 'Отклоненные',
  'applications.emptyState.title': 'Пока нет заявок',
  'applications.emptyState.message': 'Ваша задача опубликована! Специалисты скоро начнут откликаться.',
  'applications.proposedPrice': 'Предложенная цена',
  'applications.timeline': 'Сроки',
  'applications.message': 'Сообщение',
  'applications.portfolio': 'Портфолио',
  'applications.portfolioImages': 'примеров из портфолио',
  'applications.tasksCompleted': 'задач',
  'applications.yearsExperience': 'лет опыта',
  'applications.viewDetails': 'Посмотреть детали',
  'applications.acceptApplication': 'Принять',
  'applications.rejectApplication': 'Отклонить',
  'applications.status': 'Статус',
  'applications.statusPending': 'В ожидании',
  'applications.statusAccepted': 'Принята',
  'applications.statusRejected': 'Отклонена',

  // Application Detail Modal
  'applicationDetail.title': 'Детали заявки',
  'applicationDetail.professionalProfile': 'Профессиональный профиль',
  'applicationDetail.applicationMessage': 'Сообщение заявки',
  'applicationDetail.portfolioGallery': 'Портфолио',
  'applicationDetail.recentReviews': 'Последние отзывы',
  'applicationDetail.close': 'Закрыть',

  // Accept Application Dialog
  'acceptApplication.title': 'Принять заявку',
  'acceptApplication.description': 'Вы собираетесь принять заявку от {{name}}. Пожалуйста, проверьте детали и подтвердите ваше согласие.',
  'acceptApplication.agreedPrice': 'Согласованная цена',
  'acceptApplication.timeline': 'Сроки',
  'acceptApplication.messageLabel': 'Сообщение специалисту (необязательно)',
  'acceptApplication.messagePlaceholder': 'Поприветствуйте, сообщите о доступности для звонка или добавьте дополнительные детали...',
  'acceptApplication.messageHelp': 'Это сообщение будет отправлено {{name}} вместе с вашей контактной информацией.',
  'acceptApplication.pleaseConfirm': 'Пожалуйста, подтвердите:',
  'acceptApplication.agreement.priceTimeline': 'Я согласен с предложенной ценой ({{price}} {{currency}}) и сроками ({{timeline}})',
  'acceptApplication.agreement.contactSharing': 'Я понимаю, что моя контактная информация будет передана {{name}}',
  'acceptApplication.agreement.otherApplications': 'Я понимаю, что все остальные ожидающие заявки будут автоматически отклонены',
  'acceptApplication.warning': 'После принятия этой заявки вы обязуетесь работать с {{name}}. Все остальные заявки будут отклонены автоматически.',
  'acceptApplication.confirm': 'Принять заявку',
  'acceptApplication.cancel': 'Отмена',

  // Reject Application Dialog
  'rejectApplication.title': 'Отклонить заявку',
  'rejectApplication.description': 'Вы собираетесь отклонить заявку от {{name}}. Это действие уведомит специалиста, что вы не будете продолжать с его заявкой.',
  'rejectApplication.reasonTitle': 'Причина отклонения (по желанию)',
  'rejectApplication.reasonHelp': 'Указание причины помогает специалистам улучшить будущие заявки.',
  'rejectApplication.reasons.betterFit': 'Нашел более подходящего кандидата для этой задачи',
  'rejectApplication.reasons.priceHigh': 'Цена слишком высокая',
  'rejectApplication.reasons.timelineIssue': 'График мне не подходит',
  'rejectApplication.reasons.changedMind': 'Передумал насчет задачи',
  'rejectApplication.reasons.other': 'Другая причина',
  'rejectApplication.note': '{{name}} будет уведомлен, что его заявка не выбрана. Вы все еще можете просматривать другие заявки и принять другого специалиста.',
  'rejectApplication.confirm': 'Отклонить заявку',
  'rejectApplication.cancel': 'Отмена',

  // Professional Applications Dashboard
  'myApplications.title': 'Мои заявки',
  'myApplications.count': '{{count}} заявок',
  'myApplications.sortBy': 'Сортировать по',
  'myApplications.sortNewest': 'Сначала новые',
  'myApplications.sortOldest': 'Сначала старые',
  'myApplications.sortStatus': 'По статусу',
  'myApplications.sortTaskDate': 'Дата задачи',
  'myApplications.sortPriceHigh': 'Цена: От высокой к низкой',
  'myApplications.sortPriceLow': 'Цена: От низкой к высокой',
  'myApplications.filterAll': 'Все',
  'myApplications.filterPending': 'В ожидании',
  'myApplications.filterAccepted': 'Принятые',
  'myApplications.filterRejected': 'Отклоненные',
  'myApplications.filterWithdrawn': 'Отозванные',
  'myApplications.status.pending': 'В ожидании',
  'myApplications.status.accepted': 'Принята',
  'myApplications.status.rejected': 'Отклонена',
  'myApplications.status.withdrawn': 'Отозвана',
  'myApplications.appliedAgo': 'Подана {{time}}',
  'myApplications.acceptedAgo': 'Принята {{time}}',
  'myApplications.rejectedAgo': 'Отклонена {{time}}',
  'myApplications.yourQuote': 'Ваша цена',
  'myApplications.taskBudget': 'Бюджет задачи',
  'myApplications.timeline': 'Сроки',
  'myApplications.agreedPrice': 'Согласованная цена',
  'myApplications.startDate': 'Начало',
  'myApplications.viewDetails': 'Посмотреть детали',
  'myApplications.viewTask': 'Посмотреть задачу',
  'myApplications.withdraw': 'Отозвать',
  'myApplications.messageCustomer': 'Написать клиенту',
  'myApplications.markStarted': 'Отметить как начатую',
  'myApplications.markCompleted': 'Отметить как завершенную',
  'myApplications.reportIssue': 'Сообщить о проблеме',
  'myApplications.findSimilar': 'Найти похожие',
  'myApplications.delete': 'Удалить',
  'myApplications.emptyState.title': 'Вы еще не подавали заявки на задачи',
  'myApplications.emptyState.message': 'Начните просматривать доступные задачи и подавайте заявки на те, которые соответствуют вашим навыкам.',
  'myApplications.emptyState.browse': 'Просмотреть задачи',
  'myApplications.emptyStatePending.title': 'Вы прочитали всё!',
  'myApplications.emptyStatePending.message': 'У вас нет ожидающих заявок. Все ваши заявки были рассмотрены.',
  'myApplications.emptyStateAccepted.title': 'Пока нет принятых заявок',
  'myApplications.emptyStateAccepted.message': 'Продолжайте подавать заявки! Ваша следующая возможность не за горами.',
  'myApplications.emptyStateRejected.title': 'Нет отклонённых заявок',
  'myApplications.emptyStateRejected.message': 'Отличная новость! Ни одна из ваших заявок не была отклонена.',
  'myApplications.emptyStateWithdrawn.title': 'Нет отозванных заявок',
  'myApplications.emptyStateWithdrawn.message': 'Вы ещё не отзывали ни одной заявки.',
  'myApplications.withdrawDialog.title': 'Отозвать заявку?',
  'myApplications.withdrawDialog.reason': 'Причина (необязательно)',
  'myApplications.withdrawDialog.reasonUnavailable': 'Больше недоступен',
  'myApplications.withdrawDialog.reasonFoundWork': 'Нашел другую работу',
  'myApplications.withdrawDialog.reasonChanged': 'Требования задачи изменились',
  'myApplications.withdrawDialog.reasonPrice': 'Цена слишком низкая',
  'myApplications.withdrawDialog.reasonOther': 'Другое',
  'myApplications.withdrawDialog.confirm': 'Подтвердить отзыв',
  'myApplications.withdrawDialog.cancel': 'Отмена',
  'myApplications.detail.taskDetails': 'Детали задачи',
  'myApplications.detail.yourProposal': 'Ваше предложение',
  'myApplications.detail.agreedTerms': 'Согласованные условия',
  'myApplications.detail.rejectionReason': 'Причина отказа',
  'myApplications.detail.waitingResponse': 'Ожидание ответа клиента',
  'myApplications.detail.usuallyResponds': 'Обычно отвечает в течение 24 часов',
  'myApplications.detail.otherApplicants': 'Еще {{count}} профессионалов подали заявки',
  'myApplications.detail.nextSteps': 'Следующие шаги',
  'myApplications.detail.customerApproved': 'Клиент одобрил вашу заявку',
  'myApplications.detail.contactCustomer': 'Свяжитесь с клиентом для подтверждения деталей',
  'myApplications.detail.completeBy': 'Завершить задачу до {{date}}',
  'myApplications.detail.feedback': 'Не принимайте это на свой счет! Продолжайте подавать заявки на похожие задачи.',

  // My Applications Page (Professional View)
  'myApplications.subtitle': 'Заявки, которые вы подали на задачи',
  'myApplications.browseButton': 'Просмотр задач',
  'myApplications.filter.all': 'Все',
  'myApplications.filter.pending': 'В ожидании',
  'myApplications.filter.accepted': 'Принятые',
  'myApplications.filter.rejected': 'Отклоненные',
  'myApplications.filter.withdrawn': 'Отозванные',
  'myApplications.yourProposal': 'Ваше предложение',
  'myApplications.proposedPrice': '{{price}} лв',
  'myApplications.submitted': 'Подана',
  'myApplications.empty.title': 'Пока нет заявок',
  'myApplications.empty.message': 'Вы еще не подавали заявки на задачи. Просматривайте доступные задачи!',
  'myApplications.empty.browseButton': 'Просмотр задач',

  // Mock Timeline Examples (for development)
  'myApplications.mockTimeline.thisWeekend': 'В эти выходные (21-22 окт)',
  'myApplications.mockTimeline.nextWeek': 'Следующая неделя, гибкий график',
  'myApplications.mockTimeline.startMonday': 'Начну в следующий понедельник, Пн-Пт 7-8 утра',

  // My Work Page (Professional View - Accepted Applications Only)
  'myWork.title': 'Моя работа',
  'myWork.subtitle': 'Управляйте активными и завершенными задачами',
  'myWork.filter.inProgress': 'В процессе',
  'myWork.filter.pendingCompletion': 'Ожидает завершения',
  'myWork.filter.completed': 'Завершенные',
  'myWork.empty.inProgress.title': 'Нет активных задач',
  'myWork.empty.inProgress.message': 'У вас нет задач в процессе. Просмотрите доступные задачи чтобы начать!',
  'myWork.empty.inProgress.browseButton': 'Просмотр задач',
  'myWork.empty.pendingCompletion.title': 'Нет ожидающих подтверждений',
  'myWork.empty.pendingCompletion.message': 'Все ваши задачи актуальны!',
  'myWork.empty.completed.title': 'Пока нет завершенной работы',
  'myWork.empty.completed.message': 'Завершенные задачи появятся здесь.',
  'myWork.customerContact': 'Контакт клиента',
  'myWork.taskDeadline': 'Крайний срок',
  'myWork.startedDaysAgo': 'Начата {{days}} дней назад',
  'myWork.completedOn': 'Завершена {{date}}',
  'myWork.confirmCompletion': 'Подтвердить завершение',
  'myWork.viewReview': 'Посмотреть отзыв',
};
