// Authentication and authorization translations
export const auth = {
  'auth.applyForTask': 'Откликнуться на задачу',
  'auth.askQuestion': 'Задать вопрос',
  'auth.createTask': 'Создать задачу',
  'auth.loginToContinue': 'Для продолжения войдите в аккаунт',
  'auth.applyDescription':
    'Отправьте заявку клиенту и получите возможность работать над этой задачей.',
  'auth.questionDescription':
    'Задайте вопрос клиенту перед тем как откликнуться на задачу.',
  'auth.createTaskDescription':
    'Создайте новую задачу и найдите проверенных специалистов для выполнения вашей работы.',
  'auth.joinAsProfessional': 'Стать специалистом',
  'auth.joinAsProfessionalDescription':
    'Начните зарабатывать, предлагая свои навыки и услуги клиентам в вашем регионе.',
  'auth.loginDescription':
    'Войдите в аккаунт для управления задачами и связи со специалистами.',
  'auth.emailLabel': 'Email адрес',
  'auth.password': 'Пароль',
  'auth.rememberMe': 'Запомнить меня',
  'auth.forgotPasswordLink': 'Забыли пароль?',
  'auth.loginOrRegister': 'Войти / Регистрация',
  'auth.loginOrRegisterToContinue': 'Для продолжения войдите или зарегистрируйтесь',
  'auth.loginOrRegisterDescription': 'Введите свои данные для доступа к аккаунту или создайте новый.',
  'auth.continue': 'Продолжить',
  'auth.login': 'Войти',
  'auth.or': 'или',
  'auth.noAccount': 'Нет аккаунта?',
  'auth.createAccount': 'Создать аккаунт',
  'auth.whyRegister': 'Зачем регистрироваться?',
  'auth.benefit1': '• Откликайтесь на задачи',
  'auth.benefit2': '• Общайтесь напрямую с клиентами',
  'auth.benefit3': '• Отслеживайте свою историю',
  'auth.benefit4': '• Получайте уведомления о новых задачах',
  'auth.continueWith': 'Продолжить с',
  'auth.telegramHint': 'Откроет приложение Telegram или десктоп клиент',

  // Unified auth form
  'auth.fullName': 'Ваше имя',
  'auth.nameRequired': 'Пожалуйста, укажите ваше имя для создания аккаунта',
  'auth.nameRequiredHint': 'Имя обязательно для создания аккаунта',
  'auth.nameHint': 'Только при создании нового аккаунта',
  'auth.unexpectedError': 'Произошла неожиданная ошибка. Пожалуйста, попробуйте снова.',

  // WebView detection (Telegram, Facebook, etc. in-app browsers)
  'auth.webViewWarningTitle': 'Вход через Google недоступен',
  'auth.webViewWarningMessage': 'Вход через Google не работает в браузере этого приложения. Используйте email/пароль выше или откройте в Safari/Chrome.',
  'auth.openInBrowser': 'Открыть в браузере',
  'auth.popupBlocked': 'Пожалуйста, разрешите всплывающие окна для этого сайта',

  // Email verification
  'auth.email.subject': 'Trudify - Подтвердите ваш email адрес',
  'auth.email.heading': 'Добро пожаловать в Trudify!',
  'auth.email.greeting': 'Здравствуйте',
  'auth.email.message':
    'Спасибо за регистрацию! Пожалуйста, подтвердите ваш email адрес, чтобы включить уведомления по электронной почте.',
  'auth.email.buttonText': 'Подтвердить email адрес',
  'auth.email.linkInstruction': 'Или скопируйте и вставьте эту ссылку в ваш браузер:',
  'auth.email.expiresIn': '24 часа',
  'auth.email.footerText': 'Если вы не создавали аккаунт, можете спокойно игнорировать это письмо.',
  'auth.email.footerRights': 'Все права защищены.',

  // Forgot password
  'auth.forgotPassword.title': 'Забыли пароль',
  'auth.forgotPassword.description': 'Введите ваш email, и мы отправим вам ссылку для сброса пароля.',
  'auth.forgotPassword.emailLabel': 'Email адрес',
  'auth.forgotPassword.sendResetLink': 'Отправить ссылку для сброса',
  'auth.forgotPassword.backToLogin': 'Вернуться ко входу',
  'auth.forgotPassword.checkEmail': 'Проверьте вашу почту',
  'auth.forgotPassword.emailSent': 'Мы отправили ссылку для сброса пароля на',
  'auth.forgotPassword.emailSentInstructions': 'Пожалуйста, проверьте ваш почтовый ящик и нажмите на ссылку, чтобы сбросить пароль.',
  'auth.forgotPassword.didNotReceive': 'Не получили письмо?',
  'auth.forgotPassword.resendLink': 'Отправить повторно',
  'auth.forgotPassword.error': 'Не удалось отправить письмо для сброса пароля. Пожалуйста, попробуйте снова.',

  // Reset password
  'auth.resetPassword.title': 'Сброс пароля',
  'auth.resetPassword.description': 'Введите ваш новый пароль ниже.',
  'auth.resetPassword.newPassword': 'Новый пароль',
  'auth.resetPassword.confirmPassword': 'Подтвердите новый пароль',
  'auth.resetPassword.resetButton': 'Сбросить пароль',
  'auth.resetPassword.success': 'Пароль успешно сброшен!',
  'auth.resetPassword.successDescription': 'Теперь вы можете войти с вашим новым паролем.',
  'auth.resetPassword.goToLogin': 'Перейти ко входу',
  'auth.resetPassword.invalidToken': 'Недействительная или истекшая ссылка для сброса',
  'auth.resetPassword.invalidTokenDescription': 'Эта ссылка для сброса пароля недействительна или истекла. Пожалуйста, запросите новую.',
  'auth.resetPassword.passwordMismatch': 'Пароли не совпадают',
  'auth.resetPassword.passwordTooShort': 'Пароль должен содержать не менее 6 символов',
  'auth.resetPassword.error': 'Не удалось сбросить пароль. Пожалуйста, попробуйте снова.',

  // Email verification
  'auth.emailVerification.title': 'Подтвердите ваш email',
  'auth.emailVerification.notVerified': 'Ваш email не подтвержден',
  'auth.emailVerification.description': 'Пожалуйста, подтвердите ваш email для получения уведомлений и доступа ко всем функциям.',
  'auth.emailVerification.resendButton': 'Отправить письмо для подтверждения',
  'auth.emailVerification.resending': 'Отправка...',
  'auth.emailVerification.success': 'Письмо для подтверждения отправлено! Проверьте ваш почтовый ящик.',
  'auth.emailVerification.alreadyVerified': 'Ваш email уже подтвержден!',
  'auth.emailVerification.error': 'Не удалось отправить письмо для подтверждения. Пожалуйста, попробуйте снова.',
  'auth.emailVerification.rateLimited': 'Слишком много запросов. Пожалуйста, попробуйте позже.',
  'auth.emailVerification.checkSpam': 'Не забудьте проверить папку Спам.',

  // Email verification after signup (auth slide-over)
  'auth.emailVerification.checkInbox': 'Проверьте вашу почту!',
  'auth.emailVerification.sentMessage': 'Мы отправили письмо для подтверждения на',
  'auth.emailVerification.instructions': 'Нажмите на ссылку в письме, чтобы подтвердить ваш аккаунт.',
  'auth.emailVerification.resend': 'Отправить письмо для подтверждения повторно',
  'auth.emailVerification.continue': 'Продолжить в приложение',

  // Email verified success page
  'auth.emailVerified.title': 'Email подтвержден!',
  'auth.emailVerified.description': 'Ваш email успешно подтвержден. Теперь у вас есть полный доступ ко всем функциям.',
  'auth.emailVerified.whatNext': 'Что вы хотите сделать дальше?',
  'auth.emailVerified.browseTasks': 'Найти работу',
  'auth.emailVerified.createTask': 'Создать задачу',
  'auth.emailVerified.completeProfile': 'Заполнить профиль',
  'auth.emailVerified.goHome': 'На главную страницу',

  // Account Deletion
  'accountDeletion.title': 'Удаление аккаунта',
  'accountDeletion.loginRequired': 'Чтобы удалить свой аккаунт, вам нужно войти в систему.',
  'accountDeletion.whatHappens': 'Что происходит при удалении аккаунта:',
  'accountDeletion.profileRemoved': 'Ваш профиль удаляется навсегда',
  'accountDeletion.tasksCancelled': 'Открытые задачи отменяются',
  'accountDeletion.reviewsAnonymized': 'Ваши отзывы становятся анонимными (рейтинги сохраняются)',
  'accountDeletion.cannotUndo': 'Это действие нельзя отменить',
  'accountDeletion.loginWithGoogle': 'Войти через Google',
  'accountDeletion.loginWithFacebook': 'Войти через Facebook',
  'accountDeletion.backToHome': 'Вернуться на главную',
  'accountDeletion.checkingStatus': 'Проверка статуса аккаунта...',
  'accountDeletion.errorTitle': 'Что-то пошло не так',
  'accountDeletion.tryAgain': 'Попробовать снова',
  'accountDeletion.cannotDeleteYet': 'Пока нельзя удалить аккаунт',
  'accountDeletion.completeTasksFirst': 'У вас есть активная работа, которую нужно завершить сначала.',
  'accountDeletion.activeWork': 'Активные задачи, блокирующие удаление:',
  'accountDeletion.asCustomer': 'как заказчик',
  'accountDeletion.asProfessional': 'как специалист',
  'accountDeletion.viewMyTasks': 'Посмотреть мои задачи',
  'accountDeletion.backToProfile': 'Вернуться в профиль',
  'accountDeletion.confirmTitle': 'Удаление аккаунта',
  'accountDeletion.confirmDescription': 'Это навсегда удалит ваш аккаунт и все связанные данные.',
  'accountDeletion.readyToDelete': 'Проверка пройдена - готово к удалению',
  'accountDeletion.willBeDeleted': 'Будет удалено навсегда:',
  'accountDeletion.openTasksCount': '{count} открытых задач будут отменены',
  'accountDeletion.applicationsCount': '{count} ожидающих заявок будут отозваны',
  'accountDeletion.messagesCount': '{count} сообщений',
  'accountDeletion.notificationsCount': '{count} уведомлений',
  'accountDeletion.willBeAnonymized': 'Будет анонимизировано:',
  'accountDeletion.reviewsWrittenCount': '{count} отзывов, которые вы написали (рейтинги сохраняются)',
  'accountDeletion.irreversibleWarning': 'Это действие необратимо. Все ваши данные будут удалены навсегда.',
  'accountDeletion.confirmPassword': 'Подтвердите паролем',
  'accountDeletion.enterPassword': 'Введите пароль',
  'accountDeletion.passwordDescription': 'Введите пароль для подтверждения удаления аккаунта',
  'accountDeletion.passwordOptionalNote': 'Требуется только если вы зарегистрировались с email и паролем. Оставьте пустым, если вы вошли через Google или Facebook.',
  'accountDeletion.noPasswordLink': 'Не устанавливали пароль? Установите его здесь',
  'accountDeletion.deleteButton': 'Удалить мой аккаунт',
  'accountDeletion.cancel': 'Отмена',
  'accountDeletion.invalidPassword': 'Неверный пароль. Пожалуйста, попробуйте снова.',
  'accountDeletion.hasActiveTasksError': 'Нельзя удалить аккаунт с активными задачами. Пожалуйста, сначала завершите или отмените их.',
  'accountDeletion.deleteError': 'Не удалось удалить аккаунт. Пожалуйста, попробуйте снова.',
  'accountDeletion.preflightError': 'Не удалось проверить статус. Пожалуйста, попробуйте снова.',
  'accountDeletion.unknownError': 'Произошла непредвиденная ошибка. Пожалуйста, попробуйте снова.',

  // Professional Onboarding Dialog
  'auth.professionalOnboarding.title': 'Остался один шаг',
  'auth.professionalOnboarding.description': 'Заполните профиль, чтобы стать видимым для клиентов, которые ищут таких специалистов как вы.',
  'auth.professionalOnboarding.benefits': 'Займёт всего 2 минуты. Вы появитесь в поиске и будете получать уведомления о задачах.',
  'auth.professionalOnboarding.confirm': 'Заполнить профиль',
  'auth.professionalOnboarding.later': 'Позже',

  // Register Page (Ad Campaign Landing)
  'auth.register.pageTitle': 'Присоединяйтесь к Trudify',
  'auth.register.pageSubtitle': '#1 платформа в Болгарии, соединяющая клиентов с проверенными специалистами',
  'auth.register.selectIntent': 'Что привело вас в Trudify?',
  'auth.register.intentProfessional': 'Ищу работу',
  'auth.register.intentProfessionalDesc': 'Находите заказы и получайте клиентов',
  'auth.register.intentCustomer': 'Ищу исполнителя',
  'auth.register.intentCustomerDesc': 'Находите специалистов для ваших задач',
  'auth.register.tabRegister': 'Создать аккаунт',
  'auth.register.tabSignIn': 'Войти',
  'auth.register.submitRegister': 'Создать аккаунт',
  'auth.register.submitSignIn': 'Войти',
  'auth.register.benefitVerified': 'Все специалисты проверены',
  'auth.register.benefitFree': 'Бесплатно',
  'auth.register.benefitFast': 'Быстрые ответы',
  'auth.register.continueToSignup': 'Продолжить',
  'auth.register.backToIntent': 'Назад',
  'auth.register.step': 'Шаг',
  'auth.register.of': 'из',
  'auth.register.oneClickSignup': 'Регистрация в один клик',
  'auth.register.useQuickSignup': 'Используйте кнопки выше для быстрой регистрации',
  'auth.register.freeForever': '100% Бесплатно — Без скрытых комиссий',

  // Professional info step (registration)
  'auth.register.professionalInfoTitle': 'Расскажите о себе',
  'auth.register.professionalInfoSubtitle': 'Всего пара деталей, чтобы клиенты могли вас найти',
  'auth.register.professionalTitleLabel': 'Ваша профессиональная должность',
  'auth.register.professionalTitlePlaceholder': 'напр. Сантехник, Электрик, Уборщик',
  'auth.register.professionalTitleError': 'Название должно быть не менее 3 символов',
  'auth.register.serviceCategories': 'Какие услуги вы предлагаете?',
  'auth.register.categoriesRequired': 'Выберите хотя бы одну категорию',
  'auth.register.selectCity': 'Ваш город',
  'auth.register.cityRequired': 'Пожалуйста, выберите ваш город',
  'auth.register.continueToAuth': 'Продолжить',
  'auth.register.backToProfessionalInfo': 'Назад',
  'auth.register.matchingCategories': 'Подбираем подходящие категории...',
  'auth.register.suggestedCategories': 'Подобрано для вас',
  'auth.register.browseAllCategories': 'Все категории',
  'auth.register.searchOrBrowse': 'Не нашли свою категорию? Поиск или обзор',
  'auth.register.applyingProfile': 'Настраиваем ваш профиль...',
  'auth.register.profileCreated': 'Профиль создан!',

  // Already logged in state
  'auth.register.alreadyLoggedInTitle': 'Эй, вы уже внутри!',
  'auth.register.alreadyLoggedInHello': 'С возвращением,',
  'auth.register.alreadyLoggedInMessage': 'Похоже, у вас уже есть аккаунт. Куда хотите пойти?',
  'auth.register.browseTasks': 'Найти работу',
  'auth.register.createTask': 'Создать задачу',
  'auth.register.setupProfessional': 'Настроить про профиль',
  'auth.register.browseProfessionals': 'Найти специалистов',
};
