// Common UI terms and global actions
export const common = {
  welcome: 'Добро пожаловать',
  login: 'Войти',
  logout: 'Выйти',
  signup: 'Регистрация',
  search: 'Поиск',
  browse: 'Обзор',
  create: 'Создать',
  edit: 'Редактировать',
  delete: 'Удалить',
  cancel: 'Отмена',
  dismiss: 'Может быть позже',
  ignore: 'Игнорировать',
  important: 'Важно',
  save: 'Сохранить',
  submit: 'Отправить',
  loading: 'Загрузка...',
  error: 'Ошибка',
  success: 'Успех',
  back: 'Назад',
  next: 'Далее',
  previous: 'Предыдущая',
  reviews: 'отзывов',
  close: 'Закрыть',
  today: 'Сегодня',
  yesterday: 'Вчера',
  application: 'заявка',
  applications: 'заявки',

  'common.optional': 'необязательно',
  'common.close': 'Закрыть',
  'common.ok': 'ОК',
  'common.days': 'дней',
  'common.cancel': 'Отмена',
  'common.edit': 'Редактировать',
  'common.save': 'Сохранить',
  'common.anonymous': 'Анонимный пользователь',
  'common.today': 'Сегодня',
  'common.yesterday': 'Вчера',

  // Countries
  'common.country.bulgaria': 'Болгария',

  'language.en': 'English',
  'language.bg': 'Български',
  'language.ru': 'Русский',

  // Locations
  'locations.sofiaCenter': 'София, Центр',
  'locations.sofiaLyulin': 'София, Люлин',
  'locations.sofiaStudentski': 'София, Студенческий городок',
  'locations.sofiaVitosha': 'София, Витоша',
  'locations.plovdiv': 'Пловдив',
  'locations.varna': 'Варна',
  'locations.burgas': 'Бургас',
  'locations.ruse': 'Русе',
  'locations.staraZagora': 'Стара Загора',

  // Cities (top 8 supported - MVP)
  'cities.sofia': 'София',
  'cities.plovdiv': 'Пловдив',
  'cities.varna': 'Варна',
  'cities.burgas': 'Бургас',
  'cities.ruse': 'Русе',
  'cities.staraZagora': 'Стара Загора',
  'cities.pleven': 'Плевен',
  'cities.sliven': 'Сливен',

  // Common messages
  'message.taskCreated': 'Задача успешно создана!',
  'message.profileUpdated': 'Профиль успешно обновлен!',
  'message.applicationSubmitted': 'Заявка успешно отправлена!',
  'error.generic': 'Что-то пошло не так. Пожалуйста, попробуйте еще раз.',
  'error.network': 'Ошибка сети. Пожалуйста, проверьте ваше соединение.',
  'error.unauthorized':
    'Вам нужно войти в систему, чтобы получить доступ к этой странице.',

  // Empty states
  'common.noResults': 'Задачи не найдены',
  'common.noResultsFilter': 'Попробуйте выбрать другой фильтр статуса',
  'common.clearFilters': 'Показать все задачи',
  'common.errorGeneric': 'Что-то пошло не так. Пожалуйста, попробуйте еще раз.',

  // Safety & Trust Indicators
  'safety.phoneVerified': 'Телефон подтвержден',
  'safety.emailVerified': 'Email подтвержден',
  'safety.cleanRecord': 'Чистая репутация по безопасности',
  'safety.hasNegativeReviews': 'Есть негативные отзывы',
  'safety.multipleReports': 'Множественные жалобы',
  'safety.negativeReviewsTooltip': 'Этот специалист получил множественные негативные отзывы. Пожалуйста, будьте осторожны.',
  'safety.multipleReportsTooltip': 'Этот специалист получил множественные жалобы по безопасности от разных пользователей.',
  'safety.negativeReviewsWarning': 'Этот специалист получил множественные негативные отзывы',
  'safety.negativeReviewsWarningMessage': 'Множественные клиенты сообщили о проблемах с качеством услуг. Пожалуйста, внимательно изучите отзывы и будьте осторожны при найме.',
  'safety.multipleReportsWarning': 'Предупреждение о безопасности: Множественные жалобы',
  'safety.multipleReportsWarningMessage': 'Этот специалист получил множественные жалобы по безопасности от разных клиентов. Мы рекомендуем проявить дополнительную осторожность или выбрать другого специалиста.',

  // Review Visibility
  'reviews.hiddenReviewsNotice': 'Некоторые отзывы скрыты до проверки',
  'reviews.hiddenReviewsTooltip': 'Низко оцененные отзывы скрываются до обнаружения шаблона, чтобы защититься от несправедливых единичных отзывов.',
  'reviews.hiddenCountSingular': '1 скрытый отзыв',
  'reviews.hiddenCountPlural': '{{count}} скрытых отзыва',
  'reviews.patternDetected': 'Обнаружен шаблон негативных отзывов',
  'reviews.allNegativeVisible': 'Все негативные отзывы теперь видимы из-за шаблона проблем.',

  // Scam Reporting
  'report.button': 'Сообщить о проблеме',
  'report.dialogTitle': 'Сообщение о нарушении безопасности',
  'report.dialogDescription': 'Помогите нам поддерживать безопасное сообщество, сообщая о подозрительном поведении или нарушениях.',
  'report.typeLabel': 'Тип проблемы',
  'report.descriptionLabel': 'Описание',
  'report.descriptionPlaceholder': 'Пожалуйста, предоставьте конкретные детали о проблеме...',
  'report.evidenceLabel': 'Доказательства (Необязательно)',
  'report.evidenceHint': 'Загрузите скриншоты или фотографии в поддержку вашего сообщения',
  'report.evidenceComingSoon': '(Скоро появится)',
  'report.submitButton': 'Отправить сообщение',
  'report.cancelButton': 'Отмена',
  'report.successMessage': 'Сообщение успешно отправлено. Наша команда рассмотрит его в ближайшее время.',
  'report.errorMessage': 'Не удалось отправить сообщение. Пожалуйста, попробуйте еще раз.',
  'report.falseReportWarning': 'Ложные сообщения могут привести к действиям против вашего аккаунта. Пожалуйста, сообщайте только о реальных проблемах безопасности.',

  // Report Types
  'report.type.fraud_scam': 'Мошенничество или попытка обмана',
  'report.type.threatening_behavior': 'Угрожающее или агрессивное поведение',
  'report.type.harassment': 'Преследование или травля',
  'report.type.identity_theft': 'Поддельный профиль или кража личных данных',
  'report.type.poor_quality': 'Постоянно низкое качество работы',
  'report.type.no_show': 'Повторяющиеся неявки',
  'report.type.other': 'Другая проблема безопасности',

  // Suspension
  'suspension.accountSuspended': 'Аккаунт заблокирован',
  'suspension.message': 'Этот аккаунт временно заблокирован из-за множественных жалоб по безопасности.',
  'suspension.appeal': 'Если вы считаете, что это ошибка, вы можете подать апелляцию по электронной почте.',
  'suspension.contactEmail': 'Контакт: support@taskbridge.com',

  // Notification Warning (Compact Chip)
  'notificationWarning.title': 'Важно: Настройте уведомления',
  'notificationWarning.message': 'Вы не будете получать обновления о заявках, сообщениях или изменениях в задаче без канала уведомлений.',
  'notificationWarning.recommendation': 'Мы рекомендуем подключить Telegram для мгновенных уведомлений или подтвердить вашу электронную почту в качестве альтернативы.',
  'notificationWarning.compact': 'Настройте уведомления для получения обновлений о ваших задачах',
  'notificationWarning.setup': 'Настроить',
  'notificationWarning.connectTelegram': 'Подключить Telegram',
  'notificationWarning.verifyEmail': 'Подтвердить email',
  'notificationWarning.dismiss': 'Понятно',

  // Profanity Validation
  'validation.profanityDetected': 'Ваш текст содержит неприемлемую лексику. Пожалуйста, измените его.',
  'validation.profanityTitle': 'Название задачи содержит неприемлемую лексику',
  'validation.profanityDescription': 'Описание задачи содержит неприемлемую лексику',
  'validation.profanityWarning': 'Некоторые слова могут быть отмечены. Проверьте перед отправкой.',
  'validation.profanitySeverity.mild': 'Пожалуйста, избегайте использования неприемлемой лексики',
  'validation.profanitySeverity.moderate': 'Ваш текст содержит оскорбительные выражения, которые не разрешены',
  'validation.profanitySeverity.severe': 'Ваш текст содержит крайне оскорбительные выражения, которые нарушают правила нашего сообщества',
};
