export const contentPages = {
  // About Page
  'about.hero.title': 'Соединяем Болгарию с проверенными специалистами',
  'about.hero.subtitle': 'Мы верим, что каждый заслуживает доступ к надежным, проверенным специалистам для повседневных нужд.',

  'about.problem.title': 'Проблема, которую мы решаем',
  'about.problem.description': 'Найти надежную помощь в Болгарии всегда было непросто. Рекомендации от знакомых ограничены, и нет простого способа проверить качество специалиста перед наймом. Мы это меняем.',

  'about.solution.title': 'Наше решение',
  'about.solution.description': 'Trudify - это платформа, которая соединяет клиентов с проверенными местными специалистами. Каждый специалист на нашей платформе проверен, оценен и имеет отзывы от реальных клиентов.',

  'about.mission.title': 'Наша миссия',
  'about.mission.description': 'Сделать поиск надежных специалистов простым, как несколько кликов, помогая при этом квалифицированным работникам строить устойчивый бизнес.',

  'about.values.title': 'Наши ценности',
  'about.values.trust': 'Доверие',
  'about.values.trustDesc': 'Каждый специалист проверен. Каждый отзыв от реального клиента.',
  'about.values.transparency': 'Прозрачность',
  'about.values.transparencyDesc': 'Понятные цены, честные отзывы, никаких скрытых комиссий.',
  'about.values.fairness': 'Справедливость',
  'about.values.fairnessDesc': 'Справедливые возможности для специалистов, справедливые цены для клиентов.',
  'about.values.quality': 'Качество',
  'about.values.qualityDesc': 'Мы устанавливаем высокие стандарты и помогаем специалистам их достигать.',

  'about.stats.professionals': 'Проверенных специалистов',
  'about.stats.tasks': 'Выполненных задач',
  'about.stats.cities': 'Городов',
  'about.stats.satisfaction': 'Удовлетворенность клиентов',

  'about.cta.title': 'Готовы начать?',
  'about.cta.subtitle': 'Присоединяйтесь к тысячам клиентов и специалистов, использующих Trudify сегодня.',
  'about.cta.customer': 'Разместить задачу',
  'about.cta.professional': 'Стать специалистом',

  // How It Works Page
  'howItWorks.hero.title': 'Как работает Trudify',
  'howItWorks.hero.subtitle': 'Просто, безопасно и понятно. Вот как это работает.',

  'howItWorks.customers.title': 'Для клиентов',
  'howItWorks.customers.subtitle': 'Получите помощь за 4 простых шага',
  'howItWorks.customers.step1.title': 'Разместите задачу',
  'howItWorks.customers.step1.description': 'Опишите, что вам нужно, установите бюджет и разместите бесплатно. Это займет меньше 2 минут.',
  'howItWorks.customers.step2.title': 'Получите предложения',
  'howItWorks.customers.step2.description': 'Проверенные специалисты в вашем районе пришлют вам предложения. Сравните их профили, отзывы и цены.',
  'howItWorks.customers.step3.title': 'Выберите и обсудите',
  'howItWorks.customers.step3.description': 'Выберите специалиста, который лучше всего подходит. Обсудите детали в чате перед подтверждением.',
  'howItWorks.customers.step4.title': 'Получите результат',
  'howItWorks.customers.step4.description': 'Специалист выполняет работу. Платите только когда довольны результатом и оставьте отзыв.',
  'howItWorks.customers.learnMore': 'Узнать больше и смотреть видео гайды',

  'howItWorks.professionals.title': 'Для специалистов',
  'howItWorks.professionals.subtitle': 'Развивайте бизнес с Trudify',
  'howItWorks.professionals.step1.title': 'Создайте профиль',
  'howItWorks.professionals.step1.description': 'Зарегистрируйтесь, подтвердите личность и покажите свои навыки и работы.',
  'howItWorks.professionals.step2.title': 'Просматривайте задачи',
  'howItWorks.professionals.step2.description': 'Находите задачи в вашем районе, соответствующие навыкам. Фильтруйте по категории, месту и бюджету.',
  'howItWorks.professionals.step3.title': 'Отправляйте предложения',
  'howItWorks.professionals.step3.description': 'Отправляйте конкурентные предложения клиентам. Выделяйтесь профилем и отзывами.',
  'howItWorks.professionals.step4.title': 'Создавайте репутацию',
  'howItWorks.professionals.step4.description': 'Выполняйте задачи, собирайте отзывы и развивайте бизнес. Лучшие специалисты получают больше работы.',
  'howItWorks.professionals.learnMore': 'Узнать больше и смотреть видео гайды',

  'howItWorks.cta.title': 'Готовы начать?',
  'howItWorks.cta.subtitle': 'Нужна помощь или хотите предложить услуги - мы поможем.',

  // FAQ Page
  'faq.hero.title': 'Часто задаваемые вопросы',
  'faq.hero.subtitle': 'Ответы на частые вопросы об использовании Trudify.',

  'faq.customers.title': 'Для клиентов',
  'faq.customers.q1': 'Сколько стоит разместить задачу?',
  'faq.customers.a1': 'Размещение задачи на Trudify полностью бесплатно. Вы платите специалисту только после завершения работы.',
  'faq.customers.q2': 'Как узнать, что специалисты надежные?',
  'faq.customers.a2': 'Специалисты на Trudify строят репутацию через реальные отзывы клиентов и историю выполненных работ. Вы видите их рейтинги, отзывы и опыт перед тем, как нанять.',
  'faq.customers.q3': 'Что если я не доволен работой?',
  'faq.customers.a3': 'Trudify соединяет клиентов со специалистами - все договоренности между вами и специалистом. Если недовольны, можете оставить честный отзыв, чтобы предупредить других, или пожаловаться на специалиста. Множество жалоб ведут к ограничению аккаунта.',
  'faq.customers.q4': 'Можно ли отменить задачу?',
  'faq.customers.a4': 'Да, можно отменить задачу в любое время, даже после того как специалист начал работу. Для предотвращения злоупотреблений есть месячный лимит на отмены.',
  'faq.customers.q5': 'Как работает оплата?',
  'faq.customers.a5': 'Оплата договаривается напрямую между вами и специалистом. Указанный бюджет ориентировочный - итоговая цена согласовывается со специалистом после того, как он полностью поймёт объём работы.',

  'faq.professionals.title': 'Для специалистов',
  'faq.professionals.q1': 'Как зарегистрироваться как специалист?',
  'faq.professionals.a1': 'Создайте аккаунт, заполните профиль с навыками и опытом и начните откликаться на задачи. Стройте репутацию через качественную работу и собирайте отзывы от довольных клиентов.',
  'faq.professionals.q2': 'Какие комиссии берет Trudify?',
  'faq.professionals.a2': 'Сейчас Trudify бесплатен для специалистов в период запуска. В будущем возможна небольшая комиссия за выполненные задачи.',
  'faq.professionals.q3': 'Как получить больше заказов?',
  'faq.professionals.a3': 'Заполните профиль, добавьте фото работ, быстро отвечайте на задачи, делайте качественно и собирайте отзывы. Лучшие специалисты показываются выше в поиске.',
  'faq.professionals.q4': 'Можно работать в нескольких городах?',
  'faq.professionals.a4': 'Да, можете указать несколько городов и районов в зоне обслуживания.',
  'faq.professionals.q5': 'Как работают отзывы?',
  'faq.professionals.a5': 'После выполнения задачи клиенты могут оставить отзыв и оценку. Они отображаются в профиле и помогают строить репутацию.',

  'faq.general.title': 'Общие вопросы',
  'faq.general.q1': 'Trudify работает в моем городе?',
  'faq.general.a1': 'Trudify сейчас работает в крупных городах Болгарии: София, Пловдив, Варна, Бургас, Русе, Стара Загора, Плевен и Сливен. Скоро добавим больше городов.',
  'faq.general.q2': 'Какие услуги доступны?',
  'faq.general.a2': 'Широкий спектр услуг: ремонт, уборка, переезд, IT-поддержка, репетиторство, косметические услуги и многое другое. Смотрите все категории на сайте.',
  'faq.general.q3': 'Как связаться с поддержкой?',
  'faq.general.a3': 'Напишите на support@trudify.com или свяжитесь через соцсети (ссылки в футере). Обычно отвечаем в течение 24 часов.',
  'faq.general.q4': 'Как получать уведомления о новых задачах или откликах?',
  'faq.general.a4': 'Подключите Telegram в настройках профиля для бесплатных мгновенных уведомлений. Специалисты получают уведомления о приглашениях на задачи, а клиенты — когда специалисты откликаются на их задачи.',

  'faq.resources.title': 'Полезные ресурсы',
  'faq.resources.customerGuide': 'Гайд для клиентов',
  'faq.resources.customerGuideDesc': 'Смотрите видео уроки о том, как публиковать задачи и нанимать специалистов.',
  'faq.resources.professionalGuide': 'Гайд для специалистов',
  'faq.resources.professionalGuideDesc': 'Узнайте, как находить работу и развивать бизнес на Trudify.',
  'faq.resources.blogPost': 'Ищете работу?',
  'faq.resources.blogPostDesc': 'Читайте наш гайд по поиску фриланс работы в Болгарии.',
  'faq.resources.watchVideos': 'Смотреть видео',
  'faq.resources.readArticle': 'Читать статью',

  'faq.cta.title': 'Остались вопросы?',
  'faq.cta.subtitle': 'Наша поддержка готова помочь.',
  'faq.cta.contact': 'Связаться с поддержкой',

  // For Professionals Page
  'forProfessionals.hero.title': 'Развивайте бизнес с Trudify',
  'forProfessionals.hero.subtitle': 'Присоединяйтесь к тысячам специалистов, находящих новых клиентов и строящих репутацию.',
  'forProfessionals.hero.cta': 'Начать получать клиентов',

  'forProfessionals.benefits.title': 'Почему Trudify?',
  'forProfessionals.benefits.noFees': 'Без начальных платежей',
  'forProfessionals.benefits.noFeesDesc': 'Регистрация бесплатна. Без подписки, без скрытых расходов. Вы платите только когда получаете работу.',
  'forProfessionals.benefits.customers': 'Постоянный поток клиентов',
  'forProfessionals.benefits.customersDesc': 'Доступ к постоянному потоку местных клиентов, ищущих ваши услуги. Больше не нужно ждать рекомендаций.',
  'forProfessionals.benefits.reputation': 'Создавайте репутацию',
  'forProfessionals.benefits.reputationDesc': 'Собирайте отзывы, показывайте работы и создавайте профессиональное присутствие в сети, работающее на вас 24/7.',
  'forProfessionals.benefits.mobile': 'Работайте на своих условиях',
  'forProfessionals.benefits.mobileDesc': 'Выбирайте заказы, устанавливайте свои цены и управляйте всем с телефона.',

  'forProfessionals.howItWorks.title': 'Как это работает',
  'forProfessionals.howItWorks.subtitle': 'Начните зарабатывать за 4 простых шага',
  'forProfessionals.howItWorks.step1.title': 'Создайте профиль',
  'forProfessionals.howItWorks.step1.description': 'Зарегистрируйтесь бесплатно и заполните профиль своими навыками и опытом.',
  'forProfessionals.howItWorks.step2.title': 'Получайте уведомления',
  'forProfessionals.howItWorks.step2.description': 'Получайте уведомления в Telegram или на почту о новых задачах в вашем городе. Клиенты могут приглашать вас напрямую.',
  'forProfessionals.howItWorks.step2.badge': 'Работа находит вас',
  'forProfessionals.howItWorks.step3.title': 'Откликайтесь',
  'forProfessionals.howItWorks.step3.description': 'Просматривайте активные задачи, отправляйте предложения со своей ценой и опытом.',
  'forProfessionals.howItWorks.step3.badge': 'Вы выбираете',
  'forProfessionals.howItWorks.step4.title': 'Получите оплату',
  'forProfessionals.howItWorks.step4.description': 'Выполните задачу и получите оплату напрямую от клиента.',
  'forProfessionals.howItWorks.step4.badge': 'Без комиссий',

  'forProfessionals.howEarnings.title': 'Как работает заработок',
  'forProfessionals.howEarnings.description': 'Вы устанавливаете свои цены и договариваетесь напрямую с клиентами. Первые 1000 специалистов получают бесплатный доступ минимум на 1 год.',
  'forProfessionals.howEarnings.free': '100% Бесплатно для специалистов',
  'forProfessionals.howEarnings.freeDesc': 'Без комиссий, без абонплаты, без скрытых расходов. Вы получаете всё, что заработаете.',

  'forProfessionals.faq.title': 'Частые вопросы',
  'forProfessionals.faq.q1': 'Это действительно бесплатно?',
  'forProfessionals.faq.a1': 'Да! Первые 1000 специалистов получают бесплатный доступ минимум на 1 год. Без платы за регистрацию, без ежемесячных подписок, без скрытых расходов.',
  'forProfessionals.faq.q2': 'Как получить больше заказов?',
  'forProfessionals.faq.a2': 'Полностью заполните профиль, добавьте фото своих работ, быстро откликайтесь на задачи и собирайте положительные отзывы. Специалисты с высоким рейтингом показываются выше.',
  'forProfessionals.faq.q3': 'Могу ли я работать в нескольких городах?',
  'forProfessionals.faq.a3': 'Да, вы можете указать несколько городов в зонах обслуживания. Вы будете получать уведомления о задачах во всех выбранных локациях.',
  'forProfessionals.faq.q4': 'Как получать уведомления о новых задачах?',
  'forProfessionals.faq.a4': 'Подключите Telegram в настройках профиля и получайте бесплатные мгновенные уведомления о новых задачах в ваших категориях и локациях.',

  'forProfessionals.stats.activeTasks': 'Активных задач',
  'forProfessionals.stats.completedTasks': 'Выполненных задач',
  'forProfessionals.stats.growing': 'Новые задачи каждый день',

  'forProfessionals.videoGuides.title': 'Видео гайды',
  'forProfessionals.videoGuides.subtitle': 'Смотрите короткие уроки и начните за минуты',
  'forProfessionals.videoGuides.video1.title': 'Начало работы',
  'forProfessionals.videoGuides.video1.description': 'Как зарегистрироваться и заполнить профиль специалиста',
  'forProfessionals.videoGuides.video2.title': 'Поиск работы',
  'forProfessionals.videoGuides.video2.description': 'Как искать задачи, откликаться и получать уведомления',

  'forProfessionals.stats.title': 'Мы растём каждый день',

  'forProfessionals.cta.title': 'Готовы начать зарабатывать?',
  'forProfessionals.cta.subtitle': 'Создайте профиль сегодня и начните находить клиентов в вашем районе.',
  'forProfessionals.cta.button': 'Создать профиль специалиста',

  // For Customers Page
  'forCustomers.hero.title': 'Решайте задачи с Trudify',
  'forCustomers.hero.subtitle': 'Найдите проверенных специалистов для любой задачи. Разместите заказ и получите предложения за минуты.',
  'forCustomers.hero.cta': 'Разместить первую задачу',

  'forCustomers.benefits.title': 'Почему клиенты выбирают Trudify',
  'forCustomers.benefits.fast': 'Быстрый результат',
  'forCustomers.benefits.fastDesc': 'Разместите задачу и получите предложения за часы. Больше никакого бесконечного поиска и ожидания.',
  'forCustomers.benefits.verified': 'Проверенные специалисты',
  'forCustomers.benefits.verifiedDesc': 'Каждый специалист проверен. Смотрите их рейтинги, отзывы и историю выполненных работ.',
  'forCustomers.benefits.communicate': 'Простое общение',
  'forCustomers.benefits.communicateDesc': 'Общайтесь напрямую со специалистами, обсуждайте детали, договаривайтесь о ценах и согласовывайте график.',
  'forCustomers.benefits.reviews': 'Достоверные отзывы',
  'forCustomers.benefits.reviewsDesc': 'Реальные отзывы от реальных клиентов помогут выбрать лучшего специалиста для вашей задачи.',

  'forCustomers.howItWorks.title': 'Как это работает',
  'forCustomers.howItWorks.subtitle': 'Получите помощь за 3 простых шага',
  'forCustomers.howItWorks.step1.title': 'Разместите задачу',
  'forCustomers.howItWorks.step1.description': 'Опишите, что вам нужно. Занимает 2 минуты, полностью бесплатно.',
  'forCustomers.howItWorks.step1.badge': 'Бесплатно и просто',
  'forCustomers.howItWorks.step2.title': 'Получите отклики',
  'forCustomers.howItWorks.step2.description': 'Специалисты откликаются с ценой и опытом. Вы выбираете.',
  'forCustomers.howItWorks.step2.badge': 'Сравните предложения',
  'forCustomers.howItWorks.step3.title': 'Получите результат',
  'forCustomers.howItWorks.step3.description': 'Выберите лучшего, договоритесь о деталях и платите только когда довольны.',
  'forCustomers.howItWorks.step3.badge': 'Вы решаете',

  'forCustomers.valueProposition.title': 'Хватит искать. Пусть они найдут вас.',
  'forCustomers.valueProposition.description': 'В отличие от досок объявлений, где вы звоните по 10 номерам надеясь, что кто-то ответит, на Trudify специалисты конкурируют за вашу задачу. Вы размещаете, они откликаются, вы выбираете.',
  'forCustomers.valueProposition.free': '100% Бесплатно для клиентов',
  'forCustomers.valueProposition.freeDesc': 'Никаких комиссий, никаких скрытых платежей. Вы платите только специалисту за выполненную работу.',

  'forCustomers.privacy.title': 'Ваша конфиденциальность защищена',
  'forCustomers.privacy.description': 'Ваш телефон и email скрыты, пока ВЫ не выберете специалиста. Только после принятия заявки они получают ваши контакты. Вы контролируете, кто может с вами связаться.',

  'forCustomers.faq.title': 'Частые вопросы',
  'forCustomers.faq.q1': 'Это действительно бесплатно?',
  'forCustomers.faq.a1': 'Да, 100% бесплатно. Никаких комиссий. Вы платите только специалисту за его работу.',
  'forCustomers.faq.q2': 'Как узнать, что специалисты надежные?',
  'forCustomers.faq.a2': 'У каждого специалиста есть проверенные отзывы от реальных клиентов, рейтинг и история выполненных задач. Вы видите, кого нанимаете.',
  'forCustomers.faq.q3': 'Как быстро можно найти помощь?',
  'forCustomers.faq.a3': 'Большинство задач получают отклики в течение часов. На срочные задачи часто отвечают в тот же день.',
  'forCustomers.faq.q4': 'Можно увидеть цены до выбора?',
  'forCustomers.faq.a4': 'Да! Каждый специалист указывает цену при отклике. Сравните предложения и выберите лучшее сочетание цены, опыта и отзывов.',

  'forCustomers.videoGuides.title': 'Видео гайды',
  'forCustomers.videoGuides.subtitle': 'Узнайте, как пользоваться Trudify за несколько минут',
  'forCustomers.videoGuides.video1.title': 'Начало работы',
  'forCustomers.videoGuides.video1.description': 'Как зарегистрироваться и разместить первую задачу',
  'forCustomers.videoGuides.video2.title': 'Пригласить специалиста',
  'forCustomers.videoGuides.video2.description': 'Как пригласить конкретного специалиста к вашей задаче',
  'forCustomers.videoGuides.video3.title': 'Просмотр заявок',
  'forCustomers.videoGuides.video3.description': 'Как просмотреть и принять заявки',
  'forCustomers.videoGuides.video4.title': 'Оставить отзыв',
  'forCustomers.videoGuides.video4.description': 'Как оставить отзыв после завершения задачи',

  'forCustomers.stats.title': 'Присоединяйтесь к тысячам довольных клиентов',

  'forCustomers.cta.title': 'Готовы начать?',
  'forCustomers.cta.subtitle': 'Разместите первую задачу бесплатно и найдите идеального специалиста сегодня.',
  'forCustomers.cta.button': 'Разместить задачу',

  // Pricing Page
  'pricing.hero.title': 'Простое и прозрачное ценообразование',
  'pricing.hero.subtitle': 'Никаких скрытых комиссий и сюрпризов. Вот как работают цены на Trudify.',

  'pricing.customers.title': 'Для клиентов',
  'pricing.customers.free': 'Бесплатно',
  'pricing.customers.description': 'Размещение задач всегда бесплатно',
  'pricing.customers.feature1': 'Размещайте неограниченно задач',
  'pricing.customers.feature2': 'Получайте предложения от специалистов',
  'pricing.customers.feature3': 'Общайтесь со специалистами',
  'pricing.customers.feature4': 'Без оплаты до завершения работы',
  'pricing.customers.feature5': 'Оставляйте отзывы после завершения',

  'pricing.professionals.title': 'Для специалистов',
  'pricing.professionals.free': 'Бесплатно (Период запуска)',
  'pricing.professionals.description': 'Регистрируйтесь и зарабатывайте без комиссий',
  'pricing.professionals.feature1': 'Создайте профиль специалиста',
  'pricing.professionals.feature2': 'Просматривайте и откликайтесь на задачи',
  'pricing.professionals.feature3': 'Неограниченные предложения',
  'pricing.professionals.feature4': 'Создавайте репутацию с отзывами',
  'pricing.professionals.feature5': 'Без комиссии в период запуска',
  'pricing.professionals.note': 'После периода запуска возможна небольшая комиссия за выполненные задачи. Текущие пользователи получат льготные условия.',

  'pricing.cta.title': 'Начните сегодня',
  'pricing.cta.subtitle': 'Присоединяйтесь к Trudify - самый простой способ найти помощь или развить бизнес.',

  // Testimonials Page
  'testimonials.hero.title': 'Что говорят пользователи',
  'testimonials.hero.subtitle': 'Реальные истории клиентов и специалистов Trudify.',

  'testimonials.customers.title': 'Довольные клиенты',
  'testimonials.professionals.title': 'Успешные специалисты',

  'testimonials.cta.title': 'Присоединяйтесь к сообществу',
  'testimonials.cta.subtitle': 'Станьте частью тысяч довольных пользователей.',

  // Giveaway Page
  'giveaway.hero.badge': 'Каждые 2 месяца',
  'giveaway.hero.title': 'Зарабатывайте и выигрывайте!',
  'giveaway.hero.subtitle': 'Находите работу быстро, получайте оплату за свои навыки и выигрывайте ценные подарочные карты каждые два месяца.',
  'giveaway.hero.subtitleExtra': 'Присоединяйтесь к тысячам специалистов и клиентов, которые уже зарабатывают и выигрывают на Trudify!',
  'giveaway.hero.totalPrizes': 'Общий призовой фонд',
  'giveaway.hero.prizeCount': '10 Подарочных карт',
  'giveaway.hero.ctaProfessional': 'Найти работу сейчас',
  'giveaway.hero.ctaCustomer': 'Разместить задачу',

  'giveaway.whyTrudify.title': 'Почему Trudify?',
  'giveaway.whyTrudify.subtitle': 'Хотите быстро найти работу, заработать дополнительные деньги или получить помощь с задачами? Trudify — платформа для вас. Плюс выигрывайте призы просто за активность!',

  'giveaway.benefits.professionals.title': 'Для специалистов — Находите работу и зарабатывайте',
  'giveaway.benefits.professionals.findWork.title': 'Находите работу быстро',
  'giveaway.benefits.professionals.findWork.description': 'Получите доступ к сотням местных заказов. Больше не нужно ждать звонков — работа приходит к вам!',
  'giveaway.benefits.professionals.earnMoney.title': 'Зарабатывайте больше',
  'giveaway.benefits.professionals.earnMoney.description': 'Устанавливайте свои цены и получайте то, что заслуживаете. Оплата напрямую от клиентов.',
  'giveaway.benefits.professionals.growBusiness.title': 'Развивайте бизнес',
  'giveaway.benefits.professionals.growBusiness.description': 'Создавайте репутацию с отзывами. Лучшие специалисты получают больше возможностей.',
  'giveaway.benefits.professionals.bonusRewards.title': 'Выигрывайте бонусы',
  'giveaway.benefits.professionals.bonusRewards.description': 'Каждая выполненная задача — участие в нашем розыгрыше. Больше работы = больше шансов!',

  'giveaway.benefits.customers.title': 'Для клиентов — Получайте помощь быстро',
  'giveaway.benefits.customers.fastHelp.title': 'Быстрые решения',
  'giveaway.benefits.customers.fastHelp.description': 'Разместите задачу и получите предложения за часы. Найдите нужного специалиста быстро.',
  'giveaway.benefits.customers.verified.title': 'Проверенные специалисты',
  'giveaway.benefits.customers.verified.description': 'Все специалисты проверены. Читайте отзывы и выбирайте с уверенностью.',
  'giveaway.benefits.customers.fairPrices.title': 'Честные цены',
  'giveaway.benefits.customers.fairPrices.description': 'Сравнивайте предложения и выбирайте лучшее. Никаких скрытых комиссий.',
  'giveaway.benefits.customers.winPrizes.title': 'Выигрывайте подарки',
  'giveaway.benefits.customers.winPrizes.description': 'Размещайте задачи и выигрывайте призы! Клиенты тоже участвуют в нашем розыгрыше.',

  'giveaway.nextDraw.label': 'Следующий розыгрыш',
  'giveaway.nextDraw.date': 'Февраль 2026',
  'giveaway.nextDraw.frequency': 'Частота розыгрышей',
  'giveaway.nextDraw.frequencyValue': 'Каждые 2 месяца',

  'giveaway.prizes.title': 'Призовой фонд',
  'giveaway.prizes.subtitle': '10 счастливчиков получат подарочные карты от топ брендов. Будьте активны на Trudify, и вы можете стать следующим!',
  'giveaway.prizes.grand': '1-е место',
  'giveaway.prizes.second': '2-е место',
  'giveaway.prizes.third': '3-е место',
  'giveaway.prizes.remaining': 'Места 4-10',
  'giveaway.prizes.remainingValue': '7 x 20 EUR Подарочных карт',
  'giveaway.prizes.sponsorNote': 'Бренды подарочных карт будут объявлены ближе к дате розыгрыша. Мы работаем с премиум партнерами!',

  'giveaway.howItWorks.title': 'Как участвовать',
  'giveaway.howItWorks.subtitle': 'Три простых шага, чтобы начать зарабатывать и выигрывать',
  'giveaway.howItWorks.step1.title': 'Создайте бесплатный профиль',
  'giveaway.howItWorks.step1.description': 'Регистрация за минуты. Создайте профиль специалиста для поиска работы или разместите первую задачу как клиент.',
  'giveaway.howItWorks.step2.title': 'Выполняйте задачи и зарабатывайте',
  'giveaway.howItWorks.step2.description': 'Специалисты: находите и выполняйте заказы. Клиенты: размещайте задачи и завершайте их. Обе группы получают участия!',
  'giveaway.howItWorks.step3.title': 'Выигрывайте автоматически',
  'giveaway.howItWorks.step3.description': 'Каждая завершенная задача — автоматическое участие. Никаких дополнительных шагов — просто работайте и выигрывайте!',

  'giveaway.seo.title': 'Начните зарабатывать сегодня в Болгарии',
  'giveaway.seo.paragraph1': 'Ищете работу в Болгарии? Trudify соединяет квалифицированных специалистов с местными клиентами, которым нужна помощь. Сантехник, электрик, уборщик, водитель, IT-специалист или другая профессия — находите работу быстро и получайте достойную оплату.',
  'giveaway.seo.paragraph2': 'Нужна помощь с задачей? Разместите заказ бесплатно и получите предложения от проверенных специалистов в вашем районе. От домашнего ремонта и уборки до IT-поддержки и услуг по переезду — найдите надежную помощь в Софии, Пловдиве, Варне, Бургасе и других городах Болгарии.',
  'giveaway.seo.paragraph3': 'Присоединяйтесь к Trudify сегодня и станьте частью растущего сообщества. Зарабатывайте, занимаясь любимым делом, помогайте людям в вашем районе и выигрывайте призы. Чем активнее вы, тем больше можете заработать и выиграть!',

  'giveaway.rules.title': 'Правила розыгрыша',
  'giveaway.rules.rule1': 'Одна завершенная задача = одно участие в розыгрыше',
  'giveaway.rules.rule2': 'Участвовать и выигрывать могут как специалисты, так и клиенты',
  'giveaway.rules.rule3': 'Победители выбираются случайным образом из всех участий',
  'giveaway.rules.rule4': 'Подарочные карты доставляются в цифровом виде по email или Telegram',

  'giveaway.cta.title': 'Готовы зарабатывать и выигрывать?',
  'giveaway.cta.subtitle': 'Присоединяйтесь к тысячам специалистов и клиентов на Trudify. Находите работу, получайте помощь и выигрывайте призы — всё в одном месте!',
  'giveaway.cta.joinProfessional': 'Начать зарабатывать',
  'giveaway.cta.postTask': 'Разместить первую задачу',
}
