// Navigation, header, and footer translations
export const navigation = {
  'nav.home': 'Главная',
  'nav.browseTasks': 'найди задачи',
  'nav.createTask': 'создать задачу',
  'nav.profile': 'профиль',
  'nav.profileCustomer': 'Профиль клиента',
  'nav.profileProfessional': 'Профиль профессионала',
  'nav.howItWorks': 'как работает',
  'nav.categories': 'категории',
  'nav.forProfessionals': 'Для специалистов',
  'nav.browseProfessionals': 'найди исполнителя',
  'nav.forCustomers': 'Для клиентов',
  'nav.forClient': 'Для клиентов',
  'nav.myTasks': 'Мои задачи',
  'nav.myPostedTasks': 'Мои задачи',
  'nav.myApplications': 'Мои заявки',
  'nav.myWork': 'Моя работа',
  'nav.tasksIPosted': 'мои задачи',
  'nav.tasksIAmDoing': 'мои работы',
  'nav.findProfessional': 'найти профессионала',
  'nav.findAnotherTask': 'найти другую задачу',
  'nav.language': 'Язык',
  'nav.changeLanguage': 'Сменить язык',
  'nav.general': 'Общее',
  'nav.discover': 'Открыть',
  'nav.closeMenu': 'Закрыть меню',

  // Footer
  'footer.company.description':
    'Связываем людей с квалифицированными специалистами для всех видов услуг в Болгарии.',
  'footer.quickLinks.title': 'Быстрые ссылки',
  'footer.quickLinks.howItWorks': 'Как работает',
  'footer.quickLinks.categories': 'Категории',
  'footer.quickLinks.forProfessionals': 'Для специалистов',
  'footer.quickLinks.forCustomers': 'Для клиентов',
  'footer.quickLinks.browseTasks': 'Смотреть задачи',
  'footer.quickLinks.createTask': 'Создать задачу',
  'footer.quickLinks.about': 'О нас',
  'footer.quickLinks.faq': 'Частые вопросы',
  'footer.quickLinks.testimonials': 'Отзывы',
  'footer.quickLinks.blog': 'Блог',
  'footer.legal.title': 'Правовые',
  'footer.legal.terms': 'Условия обслуживания',
  'footer.legal.privacy': 'Конфиденциальность',
  'footer.contact.title': 'Контакты',
  'footer.contact.subtitle': 'Свяжитесь с нами',
  'footer.language.label': 'Язык',
  'footer.copyright': '© 2025 Trudify. Все права защищены.',

  // Social
  'footer.social.followUs': 'Подписывайтесь на нас',
  'footer.social.title': 'Мы в соцсетях',
};
