// Navigation, header, and footer translations
export const navigation = {
  'nav.home': 'Главная',
  'nav.browseTasks': 'Задачи',
  'nav.createTask': 'Создать',
  'nav.profile': 'Профиль',
  'nav.profileCustomer': 'Профиль клиента',
  'nav.profileProfessional': 'Профиль профессионала',
  'nav.howItWorks': 'Как работает',
  'nav.categories': 'Категории',
  'nav.forProfessionals': 'Профессионалы',
  'nav.forCustomers': 'Для клиентов',
  'nav.myTasks': 'Мои задачи',
  'nav.myPostedTasks': 'Мои задачи',
  'nav.myApplications': 'Мои заявки',
  'nav.myWork': 'Моя работа',
  'nav.help': 'Помощь',
  'nav.language': 'Язык',
  'nav.general': 'Общее',
  'nav.discover': 'Открыть',
  'nav.closeMenu': 'Закрыть меню',

  // Footer
  'footer.company.description':
    'Связываем людей с квалифицированными специалистами для всех видов услуг в Болгарии.',
  'footer.quickLinks.title': 'Быстрые ссылки',
  'footer.quickLinks.howItWorks': 'Как работает',
  'footer.quickLinks.categories': 'Категории',
  'footer.quickLinks.forProfessionals': 'Для специалистов',
  'footer.quickLinks.browseTasks': 'Смотреть задачи',
  'footer.quickLinks.createTask': 'Создать задачу',
  'footer.legal.title': 'Правовые',
  'footer.legal.terms': 'Условия обслуживания',
  'footer.legal.privacy': 'Политика конфиденциальности',
  'footer.contact.title': 'Контакты',
  'footer.contact.subtitle': 'Свяжитесь с нами',
  'footer.language.label': 'Язык',
  'footer.copyright': '© 2025 Obod Soft LTD. Все права защищены.',
};
