// Notifications, task detail, and posted tasks translations
export const notifications = {
  // Notifications
  'notifications.title': 'Уведомления',
  'notifications.cleanup': 'Очистить',
  'notifications.markAsRead': 'Прочитано',
  'notifications.cleanupConfirm.title': 'Удалить все уведомления?',
  'notifications.cleanupConfirm.message': 'Все уведомления будут удалены навсегда.',
  'notifications.cleanupConfirm.cancel': 'Отмена',
  'notifications.cleanupConfirm.confirm': 'Удалить',
  'notifications.tabAll': 'Все',
  'notifications.tabApplications': 'Заявки',
  'notifications.tabTasks': 'Задачи',
  'notifications.tabMessages': 'Сообщения',
  'notifications.empty.title': 'Уведомлений пока нет',
  'notifications.empty.message': 'Вы получите уведомление, когда кто-то откликнется на ваши задачи или ответит на ваши заявки.',
  'notifications.empty.filterMessage': 'Нет уведомлений в этой категории.',
  'notifications.emptyUnread.title': 'Вы прочитали всё!',
  'notifications.emptyUnread.message': 'Все уведомления прочитаны.',
  'notifications.viewApplication': 'Посмотреть заявку',
  'notifications.viewMyWork': 'Посмотреть мою работу',
  'notifications.viewTask': 'Посмотреть задачу',
  'notifications.getStarted': 'Начать',
  'notifications.customerContact': 'Контактная информация клиента',
  'notifications.customerMessage': 'Сообщение от клиента',

  // Notification Content (titles and messages)
  'notifications.content.welcome.title': 'Добро пожаловать в Trudify!',
  'notifications.content.welcome.message': 'Ваш аккаунт успешно создан. Начните с публикации задачи или просмотра рабочих предложений!',
  'notifications.content.applicationReceived.title': 'Новая заявка',
  'notifications.content.applicationReceived.message': '{{professionalName}} откликнулся на вашу задачу "{{taskTitle}}"',
  'notifications.content.applicationAccepted.title': 'Заявка принята! 🎉',
  'notifications.content.applicationAccepted.message': 'Ваша заявка на "{{taskTitle}}" была принята {{customerName}}',
  'notifications.content.applicationRejected.title': 'Обновление заявки',
  'notifications.content.applicationRejected.message': 'Ваша заявка на "{{taskTitle}}" не была выбрана на этот раз. Продолжайте откликаться!',
  'notifications.content.taskCompleted.title': 'Задание завершено - Нужен отзыв ⭐',
  'notifications.content.taskCompleted.message': '"{{taskTitle}}" завершено! Пожалуйста, уделите минуту и оцените работу {{professionalName}}.',
  'notifications.content.professionalWithdrew.title': 'Профессионал отказался',
  'notifications.content.professionalWithdrew.message': '{{professionalName}} отказался от вашей задачи "{{taskTitle}}". Задача снова открыта для новых заявок.',
  'notifications.content.removedByCustomer.title': 'Клиент удалил вас из задачи',
  'notifications.content.removedByCustomer.message': 'Вы были удалены из задачи "{{taskTitle}}" клиентом.',
  'notifications.content.taskCancelled.title': 'Задача отменена',
  'notifications.content.taskCancelled.message': 'Задача "{{taskTitle}}" была отменена клиентом',

  // Telegram notification templates
  'notifications.telegram.viewHere': 'Посмотреть здесь',
  'notifications.telegram.welcome': '👋 <b>Добро пожаловать в Trudify, {{userName}}!</b>\n\n🎉 Поздравляем! Ваш аккаунт успешно создан.\n\n✅ Вы будете получать мгновенные уведомления здесь о:\n• Новых заявках на ваши задачи\n• Сообщениях от специалистов\n• Обновлениях и завершениях задач\n\nНачните прямо сейчас:\n📝 Опубликуйте задачу или\n💼 Просмотрите рабочие предложения!',
  'notifications.telegram.applicationReceived': '✅ <b>Новая заявка!</b>\n\n<b>{{professionalName}}</b> откликнулся на вашу задачу:\n"{{taskTitle}}"\n\n{{link}}',
  'notifications.telegram.applicationAccepted': '🎉 <b>Заявка принята!</b>\n\nВаша заявка на "{{taskTitle}}" была принята {{customerName}}!{{customerMessageSection}}\n\n<b>Контактная информация:</b>\n{{customerContact}}\n\n{{link}}',
  'notifications.telegram.taskCompleted': '✅ <b>Задание завершено - Нужен отзыв!</b>\n\nВаше задание "<b>{{taskTitle}}</b>" было завершено специалистом {{professionalName}}.\n\n⭐ <b>Пожалуйста, оставьте отзыв</b>, чтобы помочь другим найти хороших профессионалов.\n\n{{link}}',
  'notifications.telegram.professionalWithdrew': '⚠️ <b>Профессионал отказался</b>\n\n<b>{{professionalName}}</b> отказался от вашей задачи:\n"{{taskTitle}}"\n\n📋 Ваша задача снова <b>открыта</b> для новых заявок.\n\n👉 <b>Следующие шаги:</b>\n• Проверьте детали задачи\n• Убедитесь, что бюджет конкурентный\n• Быстро отвечайте на новые заявки\n\n🔗 Просмотреть задачу: {{link}}',
  'notifications.telegram.removedByCustomer': '⚠️ <b>Клиент удалил вас из задачи</b>\n\nВы были удалены из задачи:\n"<b>{{taskTitle}}</b>"\n\n📋 Задача была <b>открыта снова</b> для новых заявок.\n\n👉 <b>Следующие шаги:</b>\n• Просмотрите другие доступные задачи\n• Откликайтесь на задачи, соответствующие вашим навыкам\n• Сфокусируйтесь на построении позитивных отношений с клиентами\n\n🔗 Просмотреть задачи: {{link}}',
  'notifications.telegram.taskCancelled': '❌ <b>Задача отменена</b>\n\nЗадача "{{taskTitle}}" была отменена клиентом.\n\nВаша заявка и все обсуждения, связанные с этой задачей, были удалены.\n\n👉 <b>Следующие шаги:</b>\n• Просмотрите другие доступные задачи\n• Откликайтесь на задачи, соответствующие вашим навыкам\n\n🔗 Просмотреть задачи: {{link}}',
  'notifications.telegram.taskInvitation': '🎯 <b>Новое приглашение на задачу!</b>\n\n<b>{{customerName}}</b> пригласил вас откликнуться на свою задачу:\n\n📋 <b>{{taskTitle}}</b>\n🏷️ Категория: {{taskCategory}}\n\n👉 Посмотреть и откликнуться:\n{{link}}',

  // Task Detail
  'taskDetail.backToTasks': 'Обратно к задачам',
  'taskDetail.requirements': 'Требования:',
  'taskDetail.keyInformation': 'Ключевая информация',
  'taskDetail.client': 'Автор задачи',
  'taskDetail.loginForMore': 'Войдите для большего',
  'taskDetail.loginMessage':
    'Войдите в аккаунт чтобы увидеть полную информацию',
  'taskDetail.completedTasks': 'выполненных задач',
  'taskDetail.memberSince': 'Участник с',
  'taskDetail.similarTasks': 'Похожие задачи',
  'taskDetail.apply': 'Откликнуться на задачу',
  'taskDetail.askQuestion': 'Задать вопрос',
  'taskDetail.applicationsCount': 'человек',
  'taskDetail.timeAgo': 'назад',
  'taskDetail.today': 'Сегодня',
  'taskDetail.tomorrow': 'Завтра',
  'taskDetail.days': 'дней',
  'taskDetail.flexible': 'Гибкий',
  'taskDetail.asap': 'Как можно скорее',
  'taskDetail.negotiable': 'По договоренности',
  'taskDetail.urgency.same_day': 'Срочно - сегодня',
  'taskDetail.urgency.within_week': 'На этой неделе',
  'taskDetail.urgency.flexible': 'Гибкий срок',
  'taskDetail.urgency.default': 'Не указано',
  'taskDetail.status': 'Статус',
  'taskDetail.statusTypes.vacant': 'Свободная',
  'taskDetail.statusTypes.applied': 'Откликнулись',
  'taskDetail.statusTypes.inProgress': 'В работе',
  'taskDetail.statusTypes.done': 'Выполнена',
  'taskDetail.statusTypes.archived': 'Архивирована',
  'taskDetail.appliedTooltip': 'Вы откликнулись на эту задачу. Клиент может принять или отклонить вашу заявку.',
  'taskDetail.inProgressBanner.title': 'Задача больше недоступна',
  'taskDetail.inProgressBanner.message': 'Эта задача в настоящее время выполняется специалистом и больше не принимает заявки.',
  'taskDetail.published.today': 'опубликовано сегодня',
  'taskDetail.published.thisWeek': 'опубликовано на этой неделе',
  'taskDetail.published.thisMonth': 'опубликовано в этом месяце',
  'taskDetail.published.someTimeAgo': 'опубликовано давно',

  'taskDetail.share': 'Поделиться',
  'taskDetail.shareText': 'Посмотрите эту задачу на Trudify',
  'taskDetail.shareSuccess': 'Успешно поделились!',
  'taskDetail.linkCopied': 'Ссылка скопирована!',
  'taskDetail.copyError': 'Не удалось скопировать ссылку',
  'taskDetail.editTask': 'Редактировать задачу',
  'taskDetail.cancelTask': 'Отменить задачу',
  'taskDetail.confirmCancel': 'Вы уверены, что хотите отменить эту задачу?',
  'taskDetail.cancelSuccess': 'Задача успешно отменена',
  'taskDetail.cancelError': 'Ошибка при отмене задачи',
  'taskDetail.cancelDialog.title': 'Отменить эту задачу?',
  'taskDetail.cancelDialog.warning': 'Это действие необратимо и:',
  'taskDetail.cancelDialog.consequence1': 'Удалит все заявки',
  'taskDetail.cancelDialog.consequence1NoApps': 'Удалит задачу (заявок пока нет)',
  'taskDetail.cancelDialog.consequence2': 'Уберет задачу из результатов поиска',
  'taskDetail.cancelDialog.consequence3': 'Удалит все данные задачи навсегда',
  'taskDetail.cancelDialog.confirm': 'Вы уверены, что хотите отменить эту задачу?',
  'taskDetail.cancelDialog.btnCancel': 'Отмена',
  'taskDetail.cancelDialog.btnConfirm': 'Да, отменить задачу',
  'taskDetail.cancelDialog.processing': 'Отменяется...',
  'taskDetail.activity': 'Активность по задаче',
  'taskDetail.applications': 'Заявки',
  'taskDetail.questions': 'Вопросы',
  'taskDetail.accept': 'Принять',
  'taskDetail.reject': 'Отклонить',
  'taskDetail.message': 'Сообщение',
  'taskDetail.reply': 'Ответить',
  'taskDetail.yourReply': 'Ваш ответ:',
  'taskDetail.price': 'Цена',
  'taskDetail.timeline': 'Срок',
  'taskDetail.tasks': 'задач',
  'taskDetail.cancel': 'Отмена',
  'taskDetail.writeReply': 'Напишите ваш ответ...',
  'taskDetail.sendReply': 'Отправить ответ',

  // Ask Question Dialog
  'taskDetail.askQuestionDialog.title': 'Задать вопрос',
  'taskDetail.askQuestionDialog.placeholder': 'Что бы вы хотели узнать об этой задаче?',
  'taskDetail.askQuestionDialog.submit': 'Опубликовать вопрос',
  'taskDetail.askQuestionDialog.characterCount': '{{current}}/{{max}} символов',
  'taskDetail.askQuestionDialog.minLength': 'Вопрос должен содержать не менее {{min}} символов',
  'taskDetail.askQuestionDialog.maxLength': 'Вопрос должен содержать не более {{max}} символов',

  // Questions Section
  'taskDetail.questions.empty.title': 'Вопросов пока нет',
  'taskDetail.questions.empty.message': 'Станьте первым, кто задаст вопрос об этой задаче!',
  'taskDetail.questions.unanswered': 'Без ответа',
  'taskDetail.questions.answered': 'Отвечено',
  'taskDetail.questions.loading': 'Загрузка вопросов...',

  // Answer Dialog
  'taskDetail.answerDialog.title': 'Ответить на вопрос',
  'taskDetail.answerDialog.placeholder': 'Напишите ваш ответ...',

  // Success/Error Messages
  'taskDetail.questionPosted': 'Ваш вопрос успешно опубликован!',
  'taskDetail.questionError': 'Не удалось опубликовать вопрос. Пожалуйста, попробуйте снова.',
  'taskDetail.answerPosted': 'Ваш ответ успешно опубликован!',
  'taskDetail.answerError': 'Не удалось опубликовать ответ. Пожалуйста, попробуйте снова.',

  // Not Found Page
  'taskDetail.notFound.title': 'Задача не найдена',
  'taskDetail.notFound.description': 'Задача, которую вы ищете, не существует или была удалена.',
  'taskDetail.notFound.browseTasks': 'Просмотреть задачи',

  // Error Page
  'taskDetail.error.title': 'Что-то пошло не так!',
  'taskDetail.error.description': 'Не удалось загрузить эту задачу. Возможно, это временная проблема.',
  'taskDetail.error.retry': 'Попробовать снова',
  'taskDetail.error.goHome': 'На главную',

  // Posted Tasks Page (Customer View)
  'postedTasks.title': 'Мои опубликованные задачи',
  'postedTasks.subtitle': 'Управляйте созданными вами задачами',
  'postedTasks.loading': 'Загрузка ваших задач...',
  'postedTasks.createTask': 'Создать задачу',
  'postedTasks.filter.all': 'Все',
  'postedTasks.filter.open': 'Открытые',
  'postedTasks.filter.inProgress': 'В процессе',
  'postedTasks.filter.awaitingConfirmation': 'Ожидает подтверждения',
  'postedTasks.filter.completed': 'Завершенные',
  'postedTasks.filter.cancelled': 'Отмененные',
  'postedTasks.applicationsCount': '{{count}} заявок',
  'postedTasks.viewApplications': 'Заявки',
  'postedTasks.viewDetails': 'Посмотреть детали',
  'postedTasks.editTask': 'Редактировать задачу',
  'postedTasks.acceptedProfessional': 'Принятый специалист',
  'postedTasks.completedBy': 'Выполнена специалистом',
  'postedTasks.awaitingYourConfirmation': 'Ожидает вашего подтверждения',
  'postedTasks.markedComplete': 'отметил эту задачу как завершённую',
  'postedTasks.markComplete': 'Завершить',
  'postedTasks.reportIssue': 'Пожаловаться',
  'postedTasks.cancelTask': 'Отменить задачу',
  'postedTasks.cancelTaskConfirm': 'Вы уверены, что хотите отменить эту задачу? Специалист будет уведомлён.',
  'postedTasks.reopenTask': 'Открыть снова',
  'postedTasks.reopenTaskConfirm': 'Открыть эту задачу снова? Вы сможете просмотреть и отредактировать детали перед повторной публикацией.',
  'postedTasks.empty.title': 'Есть идея? Давайте воплотим её! 💡',
  'postedTasks.empty.description': 'Ваша доска задач пуста и готова к действию. От домашних ремонтов до творческих проектов, специалисты ждут, чтобы помочь.',
  'postedTasks.empty.subtext': 'Опубликуйте свою первую задачу менее чем за 2 минуты. Это бесплатно, просто, и вы сразу начнёте получать отклики!',
  'postedTasks.empty.createButton': 'Создать задачу',
  'postedTasks.empty.hint': '✨ Совет: Чем больше деталей вы укажете, тем лучше отклики получите',
  'postedTasks.firstApplication.title': 'Отличные новости! У вас первая заявка',
  'postedTasks.firstApplication.message': 'Проверьте детали заявки и ответьте специалисту',

  // Cancel Task Dialog
  'cancelTask.title': 'Отменить задачу',
  'cancelTask.professional': 'Специалист',
  'cancelTask.professionalNotification': 'Специалист будет уведомлён об отмене',
  'cancelTask.reasonLabel': 'Почему вы отменяете задачу?',
  'cancelTask.reasons.noShow': 'Специалист не появился',
  'cancelTask.reasons.abandoned': 'Специалист бросил работу',
  'cancelTask.reasons.unresponsive': 'Специалист не отвечает',
  'cancelTask.reasons.changedRequirements': 'Мои требования изменились',
  'cancelTask.reasons.foundAlternative': 'Нашёл другое решение',
  'cancelTask.reasons.other': 'Другая причина',
  'cancelTask.descriptionLabel': 'Дополнительные детали (необязательно)',
  'cancelTask.descriptionPlaceholder': 'Пожалуйста, опишите что произошло...',
  'cancelTask.descriptionHint': 'Помогите нам понять ситуацию',
  'cancelTask.confirmButton': 'Отменить задачу',
  'cancelTask.rateLimit.title': 'Вы можете отменить еще {{remaining}} задач(у) в этом месяце',
  'cancelTask.rateLimit.message': 'Для предотвращения злоупотреблений пользователи могут отменять до {{max}} задач в месяц',
  'cancelTask.rateLimit.lastWarning': 'Это ваша последняя бесплатная отмена в этом месяце. Используйте её с умом!',
  'cancelTask.limitExceeded.title': 'Достигнут месячный лимит отмен',
  'cancelTask.limitExceeded.message': 'Вы достигли лимита отмен на этот месяц. Частые отмены могут повлиять на репутацию вашего аккаунта. Пожалуйста, свяжитесь с поддержкой, если нужна помощь.',

  // Customer Remove Professional Dialog
  'customerRemove.title': 'Удалить специалиста из задачи',
  'customerRemove.subtitle': 'Удаление из: {{taskTitle}}',
  'customerRemove.professional': 'Специалист',
  'customerRemove.acceptedOn': 'Принят',
  'customerRemove.workingFor': 'Работает',
  'customerRemove.professionalNotification': 'Специалист получит уведомление, и ваша задача будет снова открыта для новых заявок',
  'customerRemove.taskWillReopen': 'Ваша задача будет снова открыта для новых заявок',
  'customerRemove.limitWarning.title': 'Вы можете удалить еще {{remaining}} специалист(ов) в этом месяце',
  'customerRemove.limitWarning.message': 'Клиенты могут удалять до {{max}} специалиста в месяц. Частые удаления могут указывать на плохой выбор при найме.',
  'customerRemove.limitExceeded.title': 'Достигнут месячный лимит удалений',
  'customerRemove.limitExceeded.message': 'Вы достигли лимита удалений на этот месяц. Пожалуйста, свяжитесь с поддержкой, если у вас серьезная проблема.',
  'customerRemove.reasonLabel': 'Почему вы удаляете этого специалиста?',
  'customerRemove.reasons.professional_unresponsive': 'Специалист не отвечает на сообщения',
  'customerRemove.reasons.professional_no_show': 'Специалист пропустил запланированные встречи',
  'customerRemove.reasons.quality_concerns': 'Качество работы не соответствует стандартам',
  'customerRemove.reasons.safety_issues': 'Проблемы с безопасностью работы',
  'customerRemove.reasons.timeline_issue': 'Не может уложиться в мой срок',
  'customerRemove.reasons.scope_disagreement': 'Разногласия по объему или цене',
  'customerRemove.reasons.my_circumstances_changed': 'Мои обстоятельства изменились',
  'customerRemove.reasons.mutual_agreement': 'Взаимное согласие на прекращение',
  'customerRemove.reasons.other': 'Другая причина',
  'customerRemove.descriptionLabel': 'Дополнительные детали (необязательно)',
  'customerRemove.descriptionPlaceholder': 'Пожалуйста, объясните ситуацию...',
  'customerRemove.descriptionHint': 'Это помогает нам улучшить платформу',
  'customerRemove.confirmButton': 'Удалить специалиста',
  'postedTasks.removeProfessional': 'Убрать специалиста',
  'postedTasks.removeProfessionalSuccess': 'Специалист удален. Задача снова открыта для новых заявок.',
  'postedTasks.cannotRemove': 'Нельзя удалить',
  'postedTasks.markCompleteSuccess': 'Задача успешно отмечена как выполненная!',
  'postedTasks.markCompleteSuccessDescription': 'Специалист уведомлен.',
  'postedTasks.markCompleteError': 'Не удалось отметить задачу как выполненную',

  // Edit Task Page
  'editTask.title': 'Редактировать задачу',
  'editTask.subtitle': 'Обновите детали задачи, чтобы привлечь больше специалистов',
  'editTask.editingBanner': 'Редактирование: {{title}}',
  'editTask.editingSubtext': 'Внесите изменения, чтобы улучшить свою задачу',
  'editTask.help': 'Нужна помощь? Свяжитесь с нашей службой поддержки',
  'editTask.freeToEdit': 'Бесплатное редактирование',
  'editTask.noPayment': 'Без оплаты до начала работы',
  'editTask.instantSave': 'Изменения сохраняются мгновенно',
  'editTask.prosWillSee': 'Специалисты увидят обновления',
  'editTask.savingChanges': 'Сохранение изменений...',
  'editTask.saveChanges': 'Сохранить изменения',
  'editTask.cancelEdit': 'Отмена',
  'editTask.successMessage': 'Задача успешно обновлена!',
  'editTask.errorMessage': 'Ошибка при обновлении задачи. Пожалуйста, попробуйте снова.',
  'editTask.cachingNotice': 'Примечание: Изменения могут занять до 1 часа, чтобы появиться на публичной странице задачи из-за оптимизации производительности.',
  'editTask.imageUpload.error': 'Не удалось загрузить изображение',

  // Task Hints System
  'taskHints.noApplications.title': 'Пока нет заявок? Ваша задача открыта уже {{days}} дней',
  'taskHints.improveTask': 'Улучшить задачу',
  'taskHints.dismiss': 'Закрыть',
  'taskHints.suggestions.increasePrice': 'Попробуйте увеличить бюджет, чтобы привлечь больше специалистов',
  'taskHints.suggestions.addPhotos': 'Добавьте или обновите фотографии, чтобы лучше показать, что нужно сделать',
  'taskHints.suggestions.improveDescription': 'Добавьте больше деталей в описание, чтобы сделать его понятнее',
  'taskHints.suggestions.adjustDeadline': 'Рассмотрите более гибкий срок выполнения',
  'taskHints.suggestions.updateTask': 'Просмотрите и обновите детали задачи, чтобы сделать её более привлекательной',

  // Email-уведомления
  // 1. Получена заявка
  'notifications.email.applicationReceived.subject': '{{customer_name}}, у вас новая заявка!',
  'notifications.email.applicationReceived.heading': 'Получена новая заявка!',
  'notifications.email.applicationReceived.message': '{{professional_name}} откликнулся на вашу задачу "{{task_title}}". Проверьте профиль, отзывы и предложение.',
  'notifications.email.applicationReceived.buttonText': 'Посмотреть заявку',
  'notifications.email.applicationReceived.secondaryButtonText': 'Посмотреть профиль',
  'notifications.email.applicationReceived.infoTitle': 'Детали заявки:',
  'notifications.email.applicationReceived.footerText': 'Вы получили это письмо, потому что опубликовали задачу в Trudify.',

  // 2. Заявка принята
  'notifications.email.applicationAccepted.subject': 'Ваша заявка принята!',
  'notifications.email.applicationAccepted.heading': 'Поздравляем! Заявка принята',
  'notifications.email.applicationAccepted.message': 'Ваша заявка на "{{task_title}}" была принята {{customer_name}}!',
  'notifications.email.applicationAccepted.buttonText': 'Посмотреть задачу',
  'notifications.email.applicationAccepted.infoTitle': 'Контактная информация заказчика:',
  'notifications.email.applicationAccepted.secondaryMessage': 'Приступайте к выполнению задачи и поддерживайте хорошую коммуникацию с заказчиком.',
  'notifications.email.applicationAccepted.footerText': 'Вы получили это письмо, потому что откликнулись на задачу в Trudify.',
  'notifications.email.applicationAccepted.customerMessageLabel': 'Сообщение',

  // 3. Заявка отклонена
  'notifications.email.applicationRejected.subject': 'Обновление заявки на "{{task_title}}"',
  'notifications.email.applicationRejected.heading': 'Заявка не принята',
  'notifications.email.applicationRejected.message': 'Ваша заявка на "{{task_title}}" не была принята в этот раз. Не расстраивайтесь! Продолжайте откликаться на другие возможности.',
  'notifications.email.applicationRejected.buttonText': 'Посмотреть другие задачи',
  'notifications.email.applicationRejected.secondaryMessage': 'Помните: Каждая заявка - это опыт обучения. Изучайте обратную связь и продолжайте совершенствоваться!',
  'notifications.email.applicationRejected.footerText': 'Вы получили это письмо, потому что откликнулись на задачу в Trudify.',

  // 4. Получено сообщение
  'notifications.email.messageReceived.subject': 'Новое сообщение от {{sender_name}}',
  'notifications.email.messageReceived.heading': 'У вас новое сообщение',
  'notifications.email.messageReceived.message': '{{sender_name}} отправил вам сообщение о "{{task_title}}"',
  'notifications.email.messageReceived.buttonText': 'Посмотреть сообщение',
  'notifications.email.messageReceived.infoTitle': 'Предпросмотр сообщения:',
  'notifications.email.messageReceived.secondaryMessage': 'Отвечайте быстро, чтобы поддерживать хорошую коммуникацию и доверие.',
  'notifications.email.messageReceived.footerText': 'Вы получили это письмо, потому что участвуете в задаче в Trudify.',

  // 5. Задача завершена
  'notifications.email.taskCompleted.subject': 'Задача завершена: "{{task_title}}"',
  'notifications.email.taskCompleted.heading': 'Задача успешно завершена!',
  'notifications.email.taskCompleted.message': 'Задача "{{task_title}}" была отмечена как завершённая. Пожалуйста, оцените свой опыт и помогите построить доверие в сообществе.',
  'notifications.email.taskCompleted.buttonText': 'Оставить отзыв',
  'notifications.email.taskCompleted.secondaryMessage': 'Ваш отзыв помогает другим пользователям найти отличных специалистов (или заказчиков) и улучшает сообщество Trudify.',
  'notifications.email.taskCompleted.footerText': 'Вы получили это письмо, потому что участвовали в задаче в Trudify.',

  // 6. Получен платёж
  'notifications.email.paymentReceived.subject': 'Платёж получен за "{{task_title}}"',
  'notifications.email.paymentReceived.heading': 'Платёж получен!',
  'notifications.email.paymentReceived.message': 'Вы получили {{amount}} лев за выполнение "{{task_title}}". Продолжайте отличную работу!',
  'notifications.email.paymentReceived.buttonText': 'Посмотреть баланс',
  'notifications.email.paymentReceived.infoTitle': 'Детали платежа:',
  'notifications.email.paymentReceived.secondaryMessage': 'Заработанные средства доступны в вашем профиле. Продолжайте предоставлять отличные услуги, чтобы зарабатывать больше!',
  'notifications.email.paymentReceived.footerText': 'Вы получили это письмо, потому что выполнили задачу в Trudify.',

  // 7. Приветственное письмо
  'notifications.email.welcome.subject': 'Добро пожаловать в Trudify, {{user_name}}!',
  'notifications.email.welcome.heading': 'Добро пожаловать в Trudify!',
  'notifications.email.welcome.message': 'Поздравляем! Ваш аккаунт успешно создан.',
  'notifications.email.welcome.buttonText': 'Начать',
  'notifications.email.welcome.infoTitle': 'Что вы можете делать в Trudify:',
  'notifications.email.welcome.secondaryMessage': 'Нужна помощь? Посмотрите наши руководства или свяжитесь с поддержкой.',
  'notifications.email.welcome.footerText': 'Вы получили это письмо, потому что создали аккаунт в Trudify.',

  // 8. Удалён из задачи
  'notifications.email.removedFromTask.subject': 'Обновление задачи: "{{task_title}}"',
  'notifications.email.removedFromTask.heading': 'Вас удалили из задачи',
  'notifications.email.removedFromTask.message': 'Вас удалили из задачи "{{task_title}}" заказчиком. Задача теперь открыта для других специалистов.',
  'notifications.email.removedFromTask.buttonText': 'Посмотреть другие задачи',
  'notifications.email.removedFromTask.secondaryMessage': 'Это не влияет на ваш рейтинг, если нет проблем с качеством или безопасностью. Если у вас есть вопросы, пожалуйста, свяжитесь с поддержкой.',
  'notifications.email.removedFromTask.footerText': 'Вы получили это письмо, потому что работали над задачей в Trudify.',

  // 9. Приглашение на задачу
  'notifications.email.taskInvitation.subject': '{{customer_name}} пригласил вас на задачу!',
  'notifications.email.taskInvitation.heading': 'Вас пригласили на задачу!',
  'notifications.email.taskInvitation.message': '{{customer_name}} пригласил вас откликнуться на их задачу в {{task_category}}.',
  'notifications.email.taskInvitation.buttonText': 'Посмотреть задачу',
  'notifications.email.taskInvitation.infoTitle': 'Детали задачи:',
  'notifications.email.taskInvitation.secondaryMessage': 'Вы были выбраны на основе ваших навыков и отзывов. Откликайтесь сейчас, пока задача не заполнена!',
  'notifications.email.taskInvitation.footerText': 'Вы получили это письмо, потому что вас пригласили откликнуться на задачу в Trudify.',

  // Общие элементы для писем
  'notifications.email.common.greeting': 'Здравствуйте',
  'notifications.email.common.footerRights': 'Все права защищены.',
};
