// Notifications, task detail, and posted tasks translations
export const notifications = {
  // Notifications
  'notifications.title': 'Уведомления',
  'notifications.markAllRead': 'Отметить все как прочитанное',
  'notifications.tabAll': 'Все',
  'notifications.tabApplications': 'Заявки',
  'notifications.tabTasks': 'Задачи',
  'notifications.tabMessages': 'Сообщения',
  'notifications.empty.title': 'Уведомлений пока нет',
  'notifications.empty.message': 'Вы получите уведомление, когда кто-то откликнется на ваши задачи или ответит на ваши заявки.',
  'notifications.empty.filterMessage': 'Нет уведомлений в этой категории.',
  'notifications.emptyUnread.title': 'Вы прочитали всё!',
  'notifications.emptyUnread.message': 'Все уведомления прочитаны.',
  'notifications.viewApplication': 'Посмотреть заявку',
  'notifications.viewTask': 'Посмотреть задачу',

  // Task Detail
  'taskDetail.backToTasks': 'Обратно к задачам',
  'taskDetail.requirements': 'Требования:',
  'taskDetail.keyInformation': 'Ключевая информация',
  'taskDetail.client': 'Автор задачи',
  'taskDetail.loginForMore': 'Войдите для большего',
  'taskDetail.loginMessage':
    'Войдите в аккаунт чтобы увидеть полную информацию',
  'taskDetail.completedTasks': 'выполненных задач',
  'taskDetail.memberSince': 'Участник с',
  'taskDetail.similarTasks': 'Похожие задачи',
  'taskDetail.apply': 'Откликнуться на задачу',
  'taskDetail.askQuestion': 'Задать вопрос',
  'taskDetail.applicationsCount': 'человек',
  'taskDetail.timeAgo': 'назад',
  'taskDetail.today': 'Сегодня',
  'taskDetail.tomorrow': 'Завтра',
  'taskDetail.days': 'дней',
  'taskDetail.flexible': 'Гибкий',
  'taskDetail.asap': 'Как можно скорее',
  'taskDetail.negotiable': 'По договоренности',
  'taskDetail.urgency.same_day': 'Срочно - сегодня',
  'taskDetail.urgency.within_week': 'В течение недели',
  'taskDetail.urgency.flexible': 'Гибкий срок',
  'taskDetail.urgency.default': 'Не указано',
  'taskDetail.status': 'Статус',
  'taskDetail.statusTypes.vacant': 'Свободная',
  'taskDetail.statusTypes.applied': 'Откликнулись',
  'taskDetail.statusTypes.done': 'Выполнена',
  'taskDetail.statusTypes.archived': 'Архивирована',
  'taskDetail.appliedTooltip': 'Вы откликнулись на эту задачу. Клиент может принять или отклонить вашу заявку.',

  'taskDetail.share': 'Поделиться',
  'taskDetail.editTask': 'Редактировать задачу',
  'taskDetail.cancelTask': 'Отменить задачу',
  'taskDetail.confirmCancel': 'Вы уверены, что хотите отменить эту задачу?',
  'taskDetail.cancelSuccess': 'Функция отмены задачи скоро появится!',
  'taskDetail.activity': 'Активность по задаче',
  'taskDetail.applications': 'Заявки',
  'taskDetail.questions': 'Вопросы',
  'taskDetail.accept': 'Принять',
  'taskDetail.reject': 'Отклонить',
  'taskDetail.message': 'Сообщение',
  'taskDetail.reply': 'Ответить',
  'taskDetail.yourReply': 'Ваш ответ:',
  'taskDetail.price': 'Цена',
  'taskDetail.timeline': 'Срок',
  'taskDetail.tasks': 'задач',
  'taskDetail.cancel': 'Отмена',
  'taskDetail.writeReply': 'Напишите ваш ответ...',
  'taskDetail.sendReply': 'Отправить ответ',

  // Ask Question Dialog
  'taskDetail.askQuestionDialog.title': 'Задать вопрос',
  'taskDetail.askQuestionDialog.placeholder': 'Что бы вы хотели узнать об этой задаче?',
  'taskDetail.askQuestionDialog.submit': 'Опубликовать вопрос',
  'taskDetail.askQuestionDialog.characterCount': '{{current}}/{{max}} символов',
  'taskDetail.askQuestionDialog.minLength': 'Вопрос должен содержать не менее {{min}} символов',
  'taskDetail.askQuestionDialog.maxLength': 'Вопрос должен содержать не более {{max}} символов',

  // Questions Section
  'taskDetail.questions.empty.title': 'Вопросов пока нет',
  'taskDetail.questions.empty.message': 'Станьте первым, кто задаст вопрос об этой задаче!',
  'taskDetail.questions.unanswered': 'Без ответа',
  'taskDetail.questions.answered': 'Отвечено',
  'taskDetail.questions.loading': 'Загрузка вопросов...',

  // Answer Dialog
  'taskDetail.answerDialog.title': 'Ответить на вопрос',
  'taskDetail.answerDialog.placeholder': 'Напишите ваш ответ...',

  // Success/Error Messages
  'taskDetail.questionPosted': 'Ваш вопрос успешно опубликован!',
  'taskDetail.questionError': 'Не удалось опубликовать вопрос. Пожалуйста, попробуйте снова.',
  'taskDetail.answerPosted': 'Ваш ответ успешно опубликован!',
  'taskDetail.answerError': 'Не удалось опубликовать ответ. Пожалуйста, попробуйте снова.',

  // Not Found Page
  'taskDetail.notFound.title': 'Задача не найдена',
  'taskDetail.notFound.description': 'Задача, которую вы ищете, не существует или была удалена.',
  'taskDetail.notFound.browseTasks': 'Просмотреть задачи',

  // Error Page
  'taskDetail.error.title': 'Что-то пошло не так!',
  'taskDetail.error.description': 'Не удалось загрузить эту задачу. Возможно, это временная проблема.',
  'taskDetail.error.retry': 'Попробовать снова',
  'taskDetail.error.goHome': 'Перейти к просмотру',

  // Posted Tasks Page (Customer View)
  'postedTasks.title': 'Мои опубликованные задачи',
  'postedTasks.subtitle': 'Управляйте созданными вами задачами',
  'postedTasks.createTask': 'Создать задачу',
  'postedTasks.filter.all': 'Все',
  'postedTasks.filter.open': 'Открытые',
  'postedTasks.filter.inProgress': 'В процессе',
  'postedTasks.filter.awaitingConfirmation': 'Ожидает подтверждения',
  'postedTasks.filter.completed': 'Завершенные',
  'postedTasks.filter.cancelled': 'Отмененные',
  'postedTasks.applicationsCount': '{{count}} заявок',
  'postedTasks.viewApplications': 'Заявки',
  'postedTasks.viewDetails': 'Посмотреть детали',
  'postedTasks.editTask': 'Редактировать задачу',
  'postedTasks.acceptedProfessional': 'Принятый специалист',
  'postedTasks.awaitingYourConfirmation': 'Ожидает вашего подтверждения',
  'postedTasks.markedComplete': 'отметил эту задачу как завершённую',
  'postedTasks.reportIssue': 'Сообщить о проблеме',
  'postedTasks.cancelTask': 'Отменить задачу',
  'postedTasks.cancelTaskConfirm': 'Вы уверены, что хотите отменить эту задачу? Специалист будет уведомлён.',
  'postedTasks.reopenTask': 'Открыть снова',
  'postedTasks.reopenTaskConfirm': 'Открыть эту задачу снова, чтобы найти нового специалиста? Это удалит текущее назначение.',
  'postedTasks.empty.title': 'Есть идея? Давайте воплотим её! 💡',
  'postedTasks.empty.description': 'Ваша доска задач пуста и готова к действию. От домашних ремонтов до творческих проектов, специалисты ждут, чтобы помочь.',
  'postedTasks.empty.subtext': 'Опубликуйте свою первую задачу менее чем за 2 минуты. Это бесплатно, просто, и вы сразу начнёте получать отклики!',
  'postedTasks.empty.createButton': 'Создайте свою первую задачу',
  'postedTasks.empty.hint': '✨ Совет: Чем больше деталей вы укажете, тем лучше отклики получите',
  'postedTasks.firstApplication.title': 'Отличные новости! У вас первая заявка',
  'postedTasks.firstApplication.message': 'Проверьте детали заявки и ответьте специалисту',

  // Cancel Task Dialog
  'cancelTask.title': 'Отменить задачу',
  'cancelTask.professional': 'Специалист',
  'cancelTask.professionalNotification': 'Специалист будет уведомлён об отмене',
  'cancelTask.reasonLabel': 'Почему вы отменяете задачу?',
  'cancelTask.reasons.noShow': 'Специалист не появился',
  'cancelTask.reasons.abandoned': 'Специалист бросил работу',
  'cancelTask.reasons.unresponsive': 'Специалист не отвечает',
  'cancelTask.reasons.changedRequirements': 'Мои требования изменились',
  'cancelTask.reasons.foundAlternative': 'Нашёл другое решение',
  'cancelTask.reasons.other': 'Другая причина',
  'cancelTask.descriptionLabel': 'Дополнительные детали (необязательно)',
  'cancelTask.descriptionPlaceholder': 'Пожалуйста, опишите что произошло...',
  'cancelTask.descriptionHint': 'Помогите нам понять ситуацию',
  'cancelTask.confirmButton': 'Отменить задачу',
  'cancelTask.rateLimit.title': 'Вы можете отменить еще {{remaining}} задач(у) в этом месяце',
  'cancelTask.rateLimit.message': 'Для предотвращения злоупотреблений пользователи могут отменять до {{max}} задач в месяц',
  'cancelTask.rateLimit.lastWarning': 'Это ваша последняя бесплатная отмена в этом месяце. Используйте её с умом!',
  'cancelTask.limitExceeded.title': 'Достигнут месячный лимит отмен',
  'cancelTask.limitExceeded.message': 'Вы достигли лимита отмен на этот месяц. Частые отмены могут повлиять на репутацию вашего аккаунта. Пожалуйста, свяжитесь с поддержкой, если нужна помощь.',

  // Edit Task Page
  'editTask.title': 'Редактировать задачу',
  'editTask.subtitle': 'Обновите детали задачи, чтобы привлечь больше специалистов',
  'editTask.editingBanner': 'Редактирование: {{title}}',
  'editTask.editingSubtext': 'Внесите изменения, чтобы улучшить свою задачу',
  'editTask.help': 'Нужна помощь? Свяжитесь с нашей службой поддержки',
  'editTask.savingChanges': 'Сохранение изменений...',
  'editTask.saveChanges': 'Сохранить изменения',
  'editTask.cancelEdit': 'Отмена',
  'editTask.successMessage': 'Задача успешно обновлена!',
  'editTask.errorMessage': 'Ошибка при обновлении задачи. Пожалуйста, попробуйте снова.',
  'editTask.cachingNotice': 'Примечание: Изменения могут занять до 1 часа, чтобы появиться на публичной странице задачи из-за оптимизации производительности.',
  'editTask.imageUpload.error': 'Не удалось загрузить изображение',

  // Task Hints System
  'taskHints.noApplications.title': 'Пока нет заявок? Ваша задача открыта уже {{days}} дней',
  'taskHints.improveTask': 'Улучшить задачу',
  'taskHints.dismiss': 'Закрыть',
  'taskHints.suggestions.increasePrice': 'Попробуйте увеличить бюджет, чтобы привлечь больше специалистов',
  'taskHints.suggestions.addPhotos': 'Добавьте или обновите фотографии, чтобы лучше показать, что нужно сделать',
  'taskHints.suggestions.improveDescription': 'Добавьте больше деталей в описание, чтобы сделать его понятнее',
  'taskHints.suggestions.adjustDeadline': 'Рассмотрите более гибкий срок выполнения',
  'taskHints.suggestions.updateTask': 'Просмотрите и обновите детали задачи, чтобы сделать её более привлекательной',
};
