// Notifications, task detail, and posted tasks translations
export const notifications = {
  // Notifications
  'notifications.title': 'Уведомления',
  'notifications.markAllRead': 'Отметить все как прочитанное',
  'notifications.tabAll': 'Все',
  'notifications.tabApplications': 'Заявки',
  'notifications.tabTasks': 'Задачи',
  'notifications.tabMessages': 'Сообщения',
  'notifications.empty.title': 'Уведомлений пока нет',
  'notifications.empty.message': 'Вы получите уведомление, когда кто-то откликнется на ваши задачи или ответит на ваши заявки.',
  'notifications.empty.filterMessage': 'Нет уведомлений в этой категории.',
  'notifications.emptyUnread.title': 'Вы прочитали всё!',
  'notifications.emptyUnread.message': 'Все уведомления прочитаны.',
  'notifications.viewApplication': 'Посмотреть заявку',
  'notifications.viewTask': 'Посмотреть задачу',

  // Task Detail
  'taskDetail.backToTasks': 'Обратно к задачам',
  'taskDetail.requirements': 'Требования:',
  'taskDetail.keyInformation': 'Ключевая информация',
  'taskDetail.client': 'Автор задачи',
  'taskDetail.loginForMore': 'Войдите для большего',
  'taskDetail.loginMessage':
    'Войдите в аккаунт чтобы увидеть полную информацию',
  'taskDetail.completedTasks': 'выполненных задач',
  'taskDetail.memberSince': 'Участник с',
  'taskDetail.similarTasks': 'Похожие задачи',
  'taskDetail.apply': 'Откликнуться на задачу',
  'taskDetail.askQuestion': 'Задать вопрос',
  'taskDetail.applicationsCount': 'человек',
  'taskDetail.timeAgo': 'назад',
  'taskDetail.today': 'Сегодня',
  'taskDetail.tomorrow': 'Завтра',
  'taskDetail.days': 'дней',
  'taskDetail.flexible': 'Гибкий',
  'taskDetail.negotiable': 'По договоренности',
  'taskDetail.urgency.same_day': 'Срочно - сегодня',
  'taskDetail.urgency.within_week': 'В течение недели',
  'taskDetail.urgency.flexible': 'Гибкий срок',
  'taskDetail.urgency.default': 'Не указано',
  'taskDetail.status': 'Статус',
  'taskDetail.statusTypes.vacant': 'Свободная',
  'taskDetail.statusTypes.applied': 'Откликнулись',
  'taskDetail.statusTypes.done': 'Выполнена',
  'taskDetail.statusTypes.archived': 'Архивирована',
  'taskDetail.appliedTooltip': 'Вы откликнулись на эту задачу. Клиент может принять или отклонить вашу заявку.',

  'taskDetail.share': 'Поделиться',
  'taskDetail.activity': 'Активность по задаче',
  'taskDetail.applications': 'Заявки',
  'taskDetail.questions': 'Вопросы',
  'taskDetail.accept': 'Принять',
  'taskDetail.reject': 'Отклонить',
  'taskDetail.message': 'Сообщение',
  'taskDetail.reply': 'Ответить',
  'taskDetail.yourReply': 'Ваш ответ:',
  'taskDetail.price': 'Цена:',
  'taskDetail.tasks': 'задач',

  // Posted Tasks Page (Customer View)
  'postedTasks.title': 'Мои опубликованные задачи',
  'postedTasks.subtitle': 'Управляйте созданными вами задачами',
  'postedTasks.createTask': 'Создать задачу',
  'postedTasks.filter.all': 'Все',
  'postedTasks.filter.open': 'Открытые',
  'postedTasks.filter.inProgress': 'В процессе',
  'postedTasks.filter.awaitingConfirmation': 'Ожидает подтверждения',
  'postedTasks.filter.completed': 'Завершенные',
  'postedTasks.filter.cancelled': 'Отмененные',
  'postedTasks.applicationsCount': '{{count}} заявок',
  'postedTasks.viewApplications': 'Посмотреть заявки',
  'postedTasks.viewDetails': 'Посмотреть детали',
  'postedTasks.acceptedProfessional': 'Принятый специалист',
  'postedTasks.awaitingYourConfirmation': 'Ожидает вашего подтверждения',
  'postedTasks.markedComplete': 'отметил эту задачу как завершённую',
  'postedTasks.empty.title': 'Пока нет опубликованных задач',
  'postedTasks.empty.message': 'Вы ещё не опубликовали задачи. Создайте первую задачу!',
  'postedTasks.empty.createButton': 'Создать задачу',
};
