// Profile page translations - personal info, professional info, statistics, settings
export const profile = {
  'profile.title': 'Мой профиль',
  'profile.personalInfo': 'Личная информация',
  'profile.professionalInfo': 'Профессиональная информация',
  'profile.verification': 'Верификация',
  'profile.reviews': 'Отзывы',
  'profile.stats': 'Статистика',

  'profile.form.firstName': 'Имя',
  'profile.form.lastName': 'Фамилия',
  'profile.form.email': 'Email',
  'profile.form.phone': 'Телефон',
  'profile.form.location': 'Местоположение',
  'profile.form.bio': 'Биография',
  'profile.form.skills': 'Навыки',
  'profile.form.experience': 'Лет опыта',
  'profile.form.hourlyRate': 'Почасовая ставка (лв.)',
  'profile.form.vatNumber': 'НДС номер',
  'profile.form.businessName': 'Название компании',
  'profile.form.website': 'Веб-сайт',

  'profile.verification.identity': 'Личность верифицирована',
  'profile.verification.business': 'Бизнес верифицирован',
  'profile.verification.phone': 'Телефон верифицирован',
  'profile.verification.email': 'Email верифицирован',

  'language.en': 'English',
  'language.bg': 'Български',
  'language.ru': 'Русский',

  'landing.trustStats.securityUptime': 'Безопасность',
  'landing.trustStats.avgRating': 'Средний рейтинг',
  'landing.trustStats.encryption': 'Шифрование данных',
  'landing.trustStats.compliance': 'Правовое соответствие',

  'landing.trustIndicators.freeToUse': 'Бесплатно в использовании',
  'landing.trustIndicators.communityReviews': 'Отзывы сообщества',
  'landing.trustIndicators.verifiedDescription':
    'Все специалисты тщательно проверены',
  'landing.trustIndicators.ratingSystem': '5-звездная система рейтинга',
  'landing.trustIndicators.ratingSystemDescription':
    'Качество гарантировано через отзывы сообщества',
  'landing.trustIndicators.dataProtection': 'Защита данных',
  'landing.trustIndicators.dataProtectionDescription':
    'Ваша личная информация в безопасности',
  'landing.trustIndicators.contracts': 'Правовая защита',
  'landing.trustIndicators.contractsDescription':
    'Вся работа защищена четкими соглашениями',

  'landing.featured.subtitle':
    'Последние задачи, опубликованные нашим сообществом',
  'landing.featured.professionalDesc': 'Найдите свою следующую возможность',
  'landing.featured.customerDesc': 'Посмотрите, что публикуют другие',

  'landing.howItWorks.customers.step1.title': 'Создайте вашу задачу',
  'landing.howItWorks.customers.step1.description':
    'Опишите, что нужно сделать, и установите ваш бюджет',
  'landing.howItWorks.customers.step2.title': 'Получите предложения',
  'landing.howItWorks.customers.step2.description':
    'Получайте заявки от верифицированных специалистов',
  'landing.howItWorks.customers.step3.title': 'Выберите и завершите',
  'landing.howItWorks.customers.step3.description':
    'Выберите лучшего специалиста и выполните вашу задачу',

  'landing.howItWorks.professionals.step1.title': 'Просматривайте задачи',
  'landing.howItWorks.professionals.step1.description':
    'Найдите задачи, соответствующие вашим навыкам и доступности',
  'landing.howItWorks.professionals.step2.title': 'Отправьте предложение',
  'landing.howItWorks.professionals.step2.description':
    'Отправьте лучшее предложение и покажите свою экспертизу',
  'landing.howItWorks.professionals.step3.title': 'Выполните работу',
  'landing.howItWorks.professionals.step3.description':
    'Предоставьте качественную услугу и создайте репутацию',

  'landing.testimonials.title': 'Что говорят наши пользователи',
  'landing.testimonials.subtitle': 'Реальные отзывы нашего сообщества',
  'landing.testimonials.customers.title': 'От клиентов',
  'landing.testimonials.customers.customer1.name': 'Мария Иванова',
  'landing.testimonials.customers.customer1.location': 'София, Болгария',
  'landing.testimonials.customers.customer1.quote':
    'Нашла отличного сантехника за минуты. Профессиональная услуга и справедливые цены!',
  'landing.testimonials.customers.customer2.name': 'Георги Петров',
  'landing.testimonials.customers.customer2.location': 'Пловдив, Болгария',
  'landing.testimonials.customers.customer2.quote':
    'Услуга уборки была исключительной. Определенно буду использовать Trudify снова.',
  'landing.testimonials.customers.customer3.name': 'Елена Димитрова',
  'landing.testimonials.customers.customer3.location': 'Варна, Болгария',
  'landing.testimonials.customers.customer3.quote':
    'Быстро, надежно и доступно. Именно то, что я искала.',

  'landing.testimonials.professionals.title': 'От специалистов',
  'landing.testimonials.professionals.pro1.name': 'Иван Стоев',
  'landing.testimonials.professionals.pro1.profession': 'Электрик',
  'landing.testimonials.professionals.pro1.quote':
    'Trudify помог мне развить бизнес с постоянным потоком качественных клиентов.',
  'landing.testimonials.professionals.pro2.name': 'Анна Николова',
  'landing.testimonials.professionals.pro2.profession': 'Уборщица',
  'landing.testimonials.professionals.pro2.quote':
    'Простая в использовании платформа. Нравится, как я могу управлять расписанием и платежами.',
  'landing.testimonials.professionals.pro3.name': 'Димитар Георгиев',
  'landing.testimonials.professionals.pro3.profession': 'Мастер на все руки',
  'landing.testimonials.professionals.pro3.quote':
    'Профессиональная платформа, которая связывает меня с клиентами, ценящими качественную работу.',

  'landing.trustSection.title': 'Основана на доверии',
  'landing.trustSection.subtitle':
    'Ваша безопасность и удовлетворенность - наши главные приоритеты',

  'landing.cta.title': 'Готовы начать?',
  'landing.cta.subtitle':
    'Присоединяйтесь к тысячам довольных пользователей сегодня',
  'landing.cta.postTask': 'Создать задачу',
  'landing.cta.joinProfessionals': 'Присоединиться как специалист',
  'landing.cta.freeToJoin': 'Бесплатное присоединение, без скрытых комиссий',
  'landing.cta.stats.completedTasks': 'Выполненных задач',
  'landing.cta.stats.activeSpecialists': 'Активных специалистов',
  'landing.cta.stats.averageRating': 'Средний рейтинг',
  'landing.cta.stats.contractTemplates': 'Правовых шаблонов',

  'taskCard.apply': 'Откликнуться',
  'taskCard.anonymous': 'Анонимный',
  'taskCard.budget.from': 'от',
  'taskCard.budget.to': 'до',
  'taskCard.budget.negotiable': 'Договорная',
  'taskCard.deadline.flexible': 'Гибкий',
  'taskCard.deadline.today': 'Сегодня',
  'taskCard.deadline.tomorrow': 'Завтра',
  'taskCard.deadline.days': 'дней',
  'taskCard.category.home_repair': 'Домашние ремонты',
  'taskCard.category.delivery_transport': 'Доставка и транспорт',
  'taskCard.category.personal_care': 'Личный уход',
  'taskCard.category.personal_assistant': 'Личный помощник',
  'taskCard.category.learning_fitness': 'Обучение и фитнес',
  'taskCard.category.other': 'Другое',

  // Category Groups
  'categoryGroups.homeRepair': 'Дом и ремонт',
  'categoryGroups.cleaning': 'Уборка',
  'categoryGroups.deliveryTransport': 'Доставка и транспорт',
  'categoryGroups.personalCare': 'Личный уход',
  'categoryGroups.professional': 'Профессиональные услуги',
  'categoryGroups.creative': 'Творческие услуги',
  'categoryGroups.events': 'Мероприятия',
  'categoryGroups.beauty': 'Красота',
  'categoryGroups.other': 'Другое',

  // Categories - Comprehensive list (legacy keys - kept for backward compatibility)
  'categories.plumbing': 'Сантехника',
  'categories.electrical': 'Электричество',
  'categories.hvac': 'Кондиционеры и отопление',
  'categories.carpentry': 'Столярные работы',
  'categories.painting': 'Покраска',
  'categories.flooring': 'Напольные покрытия',
  'categories.roofing': 'Кровельные работы',
  'categories.homeRenovation': 'Ремонт дома',
  'categories.applianceRepair': 'Ремонт бытовой техники',
  'categories.handyman': 'Мастер на все руки',
  'categories.houseCleaning': 'Уборка дома',
  'categories.deepCleaning': 'Генеральная уборка',
  'categories.carpetCleaning': 'Чистка ковров',
  'categories.windowCleaning': 'Мытье окон',
  'categories.gardenMaintenance': 'Уход за садом',
  'categories.landscaping': 'Ландшафтный дизайн',
  'categories.delivery': 'Доставка',
  'categories.moving': 'Переезд',
  'categories.taxiDriver': 'Такси',
  'categories.courier': 'Курьер',
  'categories.babysitting': 'Няня',
  'categories.elderlyCare': 'Уход за пожилыми',
  'categories.petSitting': 'Присмотр за животными',
  'categories.personalTrainer': 'Персональный тренер',
  'categories.massageTherapy': 'Массаж',
  'categories.tutoring': 'Репетиторство',
  'categories.translation': 'Переводы',
  'categories.accounting': 'Бухгалтерия',
  'categories.legalServices': 'Юридические услуги',
  'categories.consulting': 'Консалтинг',
  'categories.graphicDesign': 'Графический дизайн',
  'categories.webDevelopment': 'Веб-разработка',
  'categories.photography': 'Фотография',
  'categories.videography': 'Видеосъемка',
  'categories.writing': 'Копирайтинг',
  'categories.musicLessons': 'Музыкальные уроки',
  'categories.eventPlanning': 'Организация мероприятий',
  'categories.catering': 'Кейтеринг',
  'categories.djServices': 'DJ услуги',
  'categories.hairdressing': 'Парикмахерские услуги',
  'categories.makeupArtist': 'Визаж',
  'categories.nailServices': 'Маникюр и педикюр',
  'categories.other': 'Другое',

  // Categories Page
  'categories.pageTitle': 'Обзор всех категорий',
  'categories.pageSubtitle': 'Найдите идеального профессионала для любой задачи',
  'categories.searchPlaceholder': 'Поиск услуг... (напр. сантехник, уборка, уроки)',
  'categories.ctaTitle': 'Не нашли то, что ищете?',
  'categories.ctaSubtitle': 'Опубликуйте вашу задачу и позвольте профессионалам найти вас',

  // Main Categories (centralized categories feature)
  'categories.main.homeServices.title': 'Домашние услуги',
  'categories.main.homeServices.description': 'Сантехника, электричество, мастер на все руки',
  'categories.main.renovation.title': 'Ремонт и строительство',
  'categories.main.renovation.description': 'Ремонты, покраска, облицовка',
  'categories.main.moving.title': 'Переезд и транспорт',
  'categories.main.moving.description': 'Переезд, грузоперевозки, грузчики',
  'categories.main.cleaning.title': 'Услуги по уборке',
  'categories.main.cleaning.description': 'Уборка дома, генеральная уборка, уборка офиса',
  'categories.main.personal.title': 'Личные услуги',
  'categories.main.personal.description': 'Няня, репетиторство, присмотр за животными',
  'categories.main.tech.title': 'Технологии и цифровые',
  'categories.main.tech.description': 'Ремонт компьютеров, IT поддержка, веб-разработка',

  // Main Categories - NEW (26 total)
  'categories.main.applianceRepair.title': 'Ремонт техники',
  'categories.main.applianceRepair.description': 'Ремонт бытовой техники, компьютеров и электроники',
  'categories.main.courierServices.title': 'Курьерские услуги',
  'categories.main.courierServices.description': 'Доставка еды, лекарств и посылок',
  'categories.main.onlineWork.title': 'Работа в интернете',
  'categories.main.onlineWork.description': 'Ввод данных, исследования, транскрипция',
  'categories.main.handyman.title': 'Домашний мастер',
  'categories.main.handyman.description': 'Сантехник, электрик, замочник',
  'categories.main.finishingWork.title': 'Отделочные работы',
  'categories.main.finishingWork.description': 'Ремонт квартир, плитка, штукатурка',
  'categories.main.constructionWork.title': 'Строительные работы',
  'categories.main.constructionWork.description': 'Кладка, сварка, столярные работы',
  'categories.main.furnitureWork.title': 'Мебельные работы',
  'categories.main.furnitureWork.description': 'Производство, ремонт и реставрация мебели',
  'categories.main.cleaningServices.title': 'Клининговые услуги',
  'categories.main.cleaningServices.description': 'Уборка дома, офиса и после ремонта',
  'categories.main.logistics.title': 'Логистика',
  'categories.main.logistics.description': 'Грузоперевозки, переезд, грузчики',
  'categories.main.householdServices.title': 'Бытовые услуги',
  'categories.main.householdServices.description': 'Няни, садовники, домработницы',
  'categories.main.petServices.title': 'Услуги для животных',
  'categories.main.petServices.description': 'Уход за собаками, кошками и другими питомцами',
  'categories.main.beautyHealth.title': 'Красота и здоровье',
  'categories.main.beautyHealth.description': 'Массаж, маникюр, косметология',
  'categories.main.autoRepair.title': 'Ремонт авто',
  'categories.main.autoRepair.description': 'Диагностика, обслуживание и ремонт автомобилей',
  'categories.main.digitalMarketing.title': 'Цифровой маркетинг',
  'categories.main.digitalMarketing.description': 'SEO, контекстная реклама, SMM',
  'categories.main.aiServices.title': 'AI услуги',
  'categories.main.aiServices.description': 'AI разработка, консультации и анализ данных',
  'categories.main.onlineAdvertising.title': 'Интернет-реклама',
  'categories.main.onlineAdvertising.description': 'Размещение рекламы в интернете',
  'categories.main.advertisingDistribution.title': 'Распространение рекламы',
  'categories.main.advertisingDistribution.description': 'Раздача листовок, расклейка объявлений',
  'categories.main.webDevelopment.title': 'Веб-разработка',
  'categories.main.webDevelopment.description': 'Создание сайтов и приложений',
  'categories.main.design.title': 'Дизайн',
  'categories.main.design.description': 'Дизайн логотипов, интерьеров, печатной продукции',
  'categories.main.photoVideo.title': 'Фото и видео услуги',
  'categories.main.photoVideo.description': 'Фотография, видеосъемка, монтаж',
  'categories.main.tutoring.title': 'Услуги репетиторов',
  'categories.main.tutoring.description': 'Уроки по предметам, языкам и музыке',
  'categories.main.businessServices.title': 'Деловые услуги',
  'categories.main.businessServices.description': 'Бухгалтерия, юридические услуги, недвижимость',
  'categories.main.translationServices.title': 'Бюро переводов',
  'categories.main.translationServices.description': 'Письменный и устный перевод',
  'categories.main.trainerServices.title': 'Услуги тренеров',
  'categories.main.trainerServices.description': 'Йога, фитнес, спортивные тренировки',
  'categories.main.eventPlanning.title': 'Организация праздников',
  'categories.main.eventPlanning.description': 'Ведущие, аниматоры, кейтеринг',
  'categories.main.volunteerHelp.title': 'Волонтерская помощь',
  'categories.main.volunteerHelp.description': 'Помощь пожилым людям и транспорт',

  // Subcategories - NEW (135 total)
  // Handyman
  'categories.sub.plumber': 'Сантехник',
  'categories.sub.electrician': 'Электрик',
  'categories.sub.handymanService': 'Мастер на все руки',
  'categories.sub.carpenter': 'Плотник',
  'categories.sub.locksmith': 'Замочник',

  // Appliance Repair
  'categories.sub.largeApplianceRepair': 'Ремонт крупной техники',
  'categories.sub.smallApplianceRepair': 'Ремонт мелкой техники',
  'categories.sub.computerHelp': 'Компьютерная помощь',
  'categories.sub.digitalTechRepair': 'Ремонт цифровой техники',
  'categories.sub.phoneRepair': 'Ремонт телефонов',

  // Finishing Work
  'categories.sub.apartmentRenovation': 'Ремонт квартиры',
  'categories.sub.tileInstallation': 'Укладка плитки',
  'categories.sub.plastering': 'Штукатурка',
  'categories.sub.insulation': 'Утепление',
  'categories.sub.heatingInstallation': 'Монтаж отопления',

  // Construction Work
  'categories.sub.generalLabor': 'Общестроительные работы',
  'categories.sub.welding': 'Сварочные работы',
  'categories.sub.turning': 'Токарные работы',
  'categories.sub.carpentry': 'Столярные работы',
  'categories.sub.bricklaying': 'Кладка кирпича',

  // Furniture Work
  'categories.sub.furnitureManufacturing': 'Производство мебели',
  'categories.sub.furnitureRepair': 'Ремонт мебели',
  'categories.sub.furnitureAssembly': 'Сборка мебели',
  'categories.sub.furnitureRestoration': 'Реставрация мебели',
  'categories.sub.furnitureUpholstery': 'Обивка мебели',

  // Cleaning Services
  'categories.sub.apartmentCleaning': 'Уборка квартиры',
  'categories.sub.deepCleaning': 'Генеральная уборка',
  'categories.sub.postRenovationCleaning': 'Уборка после ремонта',
  'categories.sub.dryCleaning': 'Химчистка',
  'categories.sub.houseCleaning': 'Уборка дома',

  // Logistics
  'categories.sub.cargoTransport': 'Грузоперевозки',
  'categories.sub.loaders': 'Грузчики',
  'categories.sub.constructionWasteRemoval': 'Вывоз строительного мусора',
  'categories.sub.furnitureApplianceMoving': 'Перевозка мебели и техники',
  'categories.sub.officeRelocation': 'Переезд офиса',

  // Household Services
  'categories.sub.gardening': 'Садоводство',
  'categories.sub.babysitting': 'Няня',
  'categories.sub.caregiver': 'Сиделка',
  'categories.sub.housekeeper': 'Домработница',
  'categories.sub.sewing': 'Швейные услуги',

  // Auto Repair
  'categories.sub.roadsideAssistance': 'Помощь на дороге',
  'categories.sub.maintenanceDiagnostics': 'ТО и диагностика',
  'categories.sub.autoElectrical': 'Автоэлектрика',
  'categories.sub.bodyWork': 'Кузовные работы',
  'categories.sub.engineRepair': 'Ремонт двигателя',

  // Courier Services
  'categories.sub.courierDelivery': 'Курьерская доставка',
  'categories.sub.groceryDelivery': 'Доставка продуктов',
  'categories.sub.foodDelivery': 'Доставка еды',
  'categories.sub.medicineDelivery': 'Доставка лекарств',
  'categories.sub.courierByCar': 'Курьер на авто',

  // Digital Marketing
  'categories.sub.contextualAdvertising': 'Контекстная реклама',
  'categories.sub.seoOptimization': 'SEO оптимизация',
  'categories.sub.copywriting': 'Копирайтинг',
  'categories.sub.socialMediaMarketing': 'SMM',
  'categories.sub.emailMarketing': 'Email-маркетинг',

  // AI Services
  'categories.sub.aiContentCreation': 'AI создание контента',
  'categories.sub.aiConsulting': 'AI консультации',
  'categories.sub.aiDevelopment': 'AI разработка',
  'categories.sub.aiDataAnalytics': 'AI анализ данных',

  // Online Advertising
  'categories.sub.onlineAdPlacement': 'Размещение интернет-рекламы',

  // Advertising Distribution
  'categories.sub.flyerDistribution': 'Раздача листовок',
  'categories.sub.posterHanging': 'Расклейка объявлений',
  'categories.sub.mailboxAdvertising': 'Реклама по почтовым ящикам',
  'categories.sub.sandwichBoardAdvertising': 'Реклама на сэндвич-панелях',

  // Design
  'categories.sub.logoDesign': 'Дизайн логотипа',
  'categories.sub.interiorDesign': 'Дизайн интерьера',
  'categories.sub.webAppDesign': 'Дизайн веб и приложений',
  'categories.sub.printDesign': 'Дизайн для печати',
  'categories.sub.printingServices': 'Полиграфические услуги',

  // Tutoring
  'categories.sub.subjectTutors': 'Репетиторы по предметам',
  'categories.sub.languageTutors': 'Преподаватели языков',
  'categories.sub.academicWriting': 'Академическое письмо',
  'categories.sub.musicTeachers': 'Учителя музыки',
  'categories.sub.drivingInstructors': 'Инструкторы по вождению',

  // Web Development
  'categories.sub.websiteCreation': 'Создание сайта',
  'categories.sub.websiteImprovements': 'Доработка сайта',
  'categories.sub.landingPage': 'Лендинг',
  'categories.sub.websiteLayout': 'Верстка сайта',
  'categories.sub.qaTesting': 'QA тестирование',

  // Online Work
  'categories.sub.dataResearch': 'Поиск данных',
  'categories.sub.contentFilling': 'Наполнение контентом',
  'categories.sub.typing': 'Набор текста',
  'categories.sub.dataEntry': 'Ввод данных',
  'categories.sub.transcription': 'Транскрибация',

  // Photo/Video Services
  'categories.sub.photographer': 'Фотограф',
  'categories.sub.videographer': 'Видеограф',
  'categories.sub.photoEditing': 'Обработка фото',
  'categories.sub.videoEditing': 'Видеомонтаж',
  'categories.sub.videoDigitization': 'Оцифровка видео',

  // Business Services
  'categories.sub.accounting': 'Бухгалтерия',
  'categories.sub.legalServices': 'Юридические услуги',
  'categories.sub.realEstate': 'Недвижимость',
  'categories.sub.callCenter': 'Колл-центр',
  'categories.sub.financialServices': 'Финансовые услуги',

  // Pet Services
  'categories.sub.catCare': 'Уход за кошками',
  'categories.sub.dogCare': 'Уход за собаками',
  'categories.sub.petHotel': 'Зоогостиница',
  'categories.sub.petTransportation': 'Транспортировка животных',
  'categories.sub.fishCare': 'Уход за рыбами',

  // Beauty & Health
  'categories.sub.massage': 'Массаж',
  'categories.sub.nailCare': 'Уход за ногтями',
  'categories.sub.cosmetology': 'Косметология',
  'categories.sub.lashCare': 'Уход за ресницами',
  'categories.sub.browCare': 'Уход за бровями',

  // Event Planning
  'categories.sub.eventHost': 'Ведущий мероприятий',
  'categories.sub.musicEntertainment': 'Музыкальное сопровождение',
  'categories.sub.animators': 'Аниматоры',
  'categories.sub.catering': 'Кейтеринг',
  'categories.sub.bakingDesserts': 'Выпечка и десерты',

  // Translation Services
  'categories.sub.writtenTranslation': 'Письменный перевод',
  'categories.sub.translationEditing': 'Редактура перевода',
  'categories.sub.documentTranslation': 'Перевод документов',
  'categories.sub.oralTranslation': 'Устный перевод',
  'categories.sub.technicalTranslation': 'Технический перевод',

  // Trainer Services
  'categories.sub.yoga': 'Йога',
  'categories.sub.groupFitness': 'Групповой фитнес',
  'categories.sub.teamSports': 'Командные виды спорта',
  'categories.sub.waterSports': 'Водные виды спорта',
  'categories.sub.martialArts': 'Боевые искусства',

  // Volunteer Help
  'categories.sub.elderlyAssistance': 'Помощь пожилым людям',
  'categories.sub.volunteerTransportation': 'Волонтерская перевозка',
  'categories.sub.fuelDelivery': 'Доставка топлива',
  'categories.sub.housingAssistance': 'Помощь с жильем',
  'categories.sub.volunteerFoodDelivery': 'Волонтерская доставка еды',

  'professionalDetail.about': 'О специалисте',
  'professionalDetail.reviews': 'отзывов',
  'professionalDetail.online': 'Онлайн',
  'professionalDetail.offline': 'Недавно был в сети',
  'professionalDetail.verified.phone': 'Телефон',
  'professionalDetail.verified.id': 'Документ',
  'professionalDetail.stats.completedTasks': 'Задач',
  'professionalDetail.stats.yearsExperience': 'Лет',
  'professionalDetail.stats.responseTime': 'Ответ',
  'professionalDetail.actions.proposeTask': 'Предложить задачу',
  'professionalDetail.actions.contact': 'Связаться',
  'professionalDetail.actions.askQuestion': 'Задать вопрос',
  'professionalDetail.actions.saveToFavorites': 'В избранное',
  'professionalDetail.contactHours': 'Доступен',
  'professionalDetail.services.title': 'Услуги и цены',
  'professionalDetail.services.pricingNote.title': 'Информация о ценах',
  'professionalDetail.services.pricingNote.description':
    'Окончательные цены согласовываются индивидуально в зависимости от сложности и требований задачи.',
  'professionalDetail.portfolio.title': 'Мои примеры',
  'professionalDetail.portfolio.noWork': 'Пока нет примеров',
  'professionalDetail.portfolio.before': 'До',
  'professionalDetail.portfolio.after': 'После',
  'professionalDetail.portfolio.viewMore': 'Посмотреть все примеры',
  'professionalDetail.portfolio.showcase': 'Профессиональные примеры работ',
  'professionalDetail.completedTasks.title': 'Выполненные задачи',
  'professionalDetail.completedTasks.noTasks': 'Пока нет выполненных задач',
  'professionalDetail.completedTasks.viewTask': 'Посмотреть задачу',
  'professionalDetail.completedTasks.completedOn': 'Выполнено',
  'professionalDetail.reviews.title': 'Отзывы и рейтинги',
  'professionalDetail.reviews.count': 'отзывов',
  'professionalDetail.reviews.recentRating': 'Недавний рейтинг',
  'professionalDetail.reviews.excellent': 'Отлично',
  'professionalDetail.reviews.noReviews': 'Пока нет отзывов',
  'professionalDetail.reviews.beFirst': 'Станьте первым, кто оставит отзыв',
  'professionalDetail.reviews.showMore': 'Показать все отзывы',
  'professionalDetail.reviews.allReviews': 'Все отзывы',
  'professionalDetail.reviews.avgRating': 'Средний рейтинг',
  'professionalDetail.reviews.more': 'ещё',
  'professionalDetail.completedTasks.stats.tasksCompleted': 'Выполненных задач',
  'professionalDetail.completedTasks.stats.avgRating': 'Средний рейтинг',
  'professionalDetail.completedTasks.stats.fiveStarTasks':
    '5-звёздочные задачи',
  'professionalDetail.verified': 'Подтверждён',
  'common.anonymous': 'Анонимный пользователь',

  'footer.company.description':
    'Связываем людей с квалифицированными специалистами для всех видов услуг в Болгарии.',
  'footer.quickLinks.title': 'Быстрые ссылки',
  'footer.quickLinks.howItWorks': 'Как работает',
  'footer.quickLinks.categories': 'Категории',
  'footer.quickLinks.forProfessionals': 'Для специалистов',
  'footer.quickLinks.security': 'Безопасность',
  'footer.quickLinks.help': 'Помощь',
  'footer.legal.title': 'Правовые',
  'footer.legal.terms': 'Условия обслуживания',
  'footer.legal.privacy': 'Политика конфиденциальности',
  'footer.legal.gdpr': 'GDPR',
  'footer.legal.cookies': 'Cookies',
  'footer.legal.complaints': 'Жалобы',
  'footer.contact.title': 'Контакты',
  'footer.contact.subtitle': 'Свяжитесь с нами по вопросам и поддержке',
  'footer.language.label': 'Язык',
  'footer.copyright': '© 2025 Obod Soft LTD. Все права защищены.',

  'taskDetail.backToTasks': 'Обратно к задачам',
  'taskDetail.requirements': 'Требования:',
  'taskDetail.keyInformation': 'Ключевая информация',
  'taskDetail.client': 'Клиент',
  'taskDetail.loginForMore': 'Войдите для большего',
  'taskDetail.loginMessage':
    'Войдите в аккаунт чтобы увидеть полную информацию',
  'taskDetail.completedTasks': 'выполненных задач',
  'taskDetail.memberSince': 'Участник с',
  'taskDetail.similarTasks': 'Похожие задачи',
  'taskDetail.apply': 'Откликнуться на задачу',
  'taskDetail.askQuestion': 'Задать вопрос',
  'taskDetail.applicationsCount': 'человек',
  'taskDetail.timeAgo': 'назад',
  'taskDetail.today': 'Сегодня',
  'taskDetail.tomorrow': 'Завтра',
  'taskDetail.days': 'дней',
  'taskDetail.flexible': 'Гибкий',
  'taskDetail.negotiable': 'По договоренности',
  'taskDetail.urgency.same_day': 'Срочно - сегодня',
  'taskDetail.urgency.within_week': 'В течение недели',
  'taskDetail.urgency.flexible': 'Гибкий срок',
  'taskDetail.urgency.default': 'Не указано',
  'taskDetail.status': 'Статус',
  'taskDetail.statusTypes.vacant': 'Свободная',
  'taskDetail.statusTypes.applied': 'Откликнулись',
  'taskDetail.statusTypes.done': 'Выполнена',
  'taskDetail.statusTypes.archived': 'Архивирована',
  'taskDetail.appliedTooltip': 'Вы откликнулись на эту задачу. Клиент может принять или отклонить вашу заявку.',

  'taskDetail.share': 'Поделиться',
  'taskDetail.activity': 'Активность по задаче',
  'taskDetail.applications': 'Заявки',
  'taskDetail.questions': 'Вопросы',
  'taskDetail.accept': 'Принять',
  'taskDetail.reject': 'Отклонить',
  'taskDetail.message': 'Сообщение',
  'taskDetail.reply': 'Ответить',
  'taskDetail.yourReply': 'Ваш ответ:',
  'taskDetail.price': 'Цена:',
  'taskDetail.tasks': 'задач',

  'auth.applyForTask': 'Откликнуться на задачу',
  'auth.askQuestion': 'Задать вопрос',
  'auth.createTask': 'Создать задачу',
  'auth.loginToContinue': 'Для продолжения войдите в аккаунт',
  'auth.applyDescription':
    'Отправьте заявку клиенту и получите возможность работать над этой задачей.',
  'auth.questionDescription':
    'Задайте вопрос клиенту перед тем как откликнуться на задачу.',
  'auth.createTaskDescription':
    'Создайте новую задачу и найдите проверенных специалистов для выполнения вашей работы.',
  'auth.loginDescription':
    'Войдите в аккаунт для управления задачами и связи со специалистами.',
  'auth.email': 'Email адрес',
  'auth.password': 'Пароль',
  'auth.rememberMe': 'Запомнить меня',
  'auth.forgotPassword': 'Забыли пароль?',
  'auth.loginOrRegister': 'Войти / Регистрация',
  'auth.loginOrRegisterToContinue': 'Для продолжения войдите или зарегистрируйтесь',
  'auth.loginOrRegisterDescription': 'Введите свои данные для доступа к аккаунту или создайте новый.',
  'auth.continue': 'Продолжить',
  'auth.login': 'Войти',
  'auth.or': 'или',
  'auth.noAccount': 'Нет аккаунта?',
  'auth.createAccount': 'Создать аккаунт',
  'auth.whyRegister': 'Зачем регистрироваться?',
  'auth.benefit1': '• Откликайтесь на задачи',
  'auth.benefit2': '• Общайтесь напрямую с клиентами',
  'auth.benefit3': '• Отслеживайте свою историю',
  'auth.benefit4': '• Получайте уведомления о новых задачах',
  'auth.continueWith': 'Продолжить с',

  // Application Dialog
  'application.title': 'Откликнуться на задачу',
  'application.proposedPrice': 'Ваша цена',
  'application.pricePlaceholder': 'Введите вашу цену в левах',
  'application.timeline': 'Когда можете начать?',
  'application.timelineToday': 'Сегодня',
  'application.timeline3days': 'В течение 3 дней',
  'application.timelineWeek': 'В течение недели',
  'application.timelineFlexible': 'Гибкий',
  'application.message': 'Почему вы лучше всего подходите?',
  'application.messagePlaceholder': 'Поделитесь своим опытом и почему вы идеально подходите для этой задачи...',
  'application.messageInfo': 'Сосредоточьтесь на навыках и опыте. Контактной информацией можно обменяться после принятия заявки.',
  'application.characterCount': '{{current}}/{{max}} символов',
  'application.submit': 'Отправить заявку',
  'application.submitting': 'Отправка...',
  'application.cancel': 'Отмена',
  'application.success': 'Заявка отправлена!',
  'application.successMessage': 'Владелец задачи рассмотрит вашу заявку и скоро ответит.',
  'application.viewApplication': 'Посмотреть мою заявку',
  'application.browseOther': 'Просмотреть другие задачи',
  'application.errors.priceRequired': 'Цена обязательна',
  'application.errors.priceMin': 'Цена должна быть больше 0',
  'application.errors.timelineRequired': 'Сроки обязательны',
  'application.errors.messageRequired': 'Сообщение обязательно',
  'application.errors.messageMin': 'Сообщение должно содержать не менее 30 символов',
  'application.errors.messageMax': 'Сообщение не может превышать 500 символов',
  'application.errors.noPhoneNumbers': 'Номера телефонов не разрешены в заявках. Вы можете обменяться контактной информацией после принятия заявки.',
  'application.errors.noUrls': 'URL-адреса и ссылки не разрешены в заявках. Вы можете поделиться портфолио после принятия заявки.',
  'application.errors.noEmails': 'Адреса электронной почты не разрешены в заявках. Вы можете обменяться контактной информацией после принятия заявки.',
  'application.alreadyApplied': 'Вы уже откликнулись на эту задачу',
  'application.cannotApplyOwnTask': 'Вы не можете откликнуться на свою собственную задачу',

  'message.taskCreated': 'Задача успешно создана!',
  'message.profileUpdated': 'Профиль успешно обновлен!',
  'message.applicationSubmitted': 'Заявка успешно отправлена!',
  'error.generic': 'Что-то пошло не так. Пожалуйста, попробуйте еще раз.',
  'error.network': 'Ошибка сети. Пожалуйста, проверьте ваше соединение.',
  'error.unauthorized':
    'Вам нужно войти в систему, чтобы получить доступ к этой странице.',

  // Profile Page
  'profile.completion': 'Заполнение профиля',
  'profile.settings': 'Настройки',
  'profile.tabs.customer': 'Клиент',
  'profile.tabs.professional': 'Специалист',
  'profile.email': 'Email',
  'profile.phone': 'Телефон',
  'profile.location': 'Местоположение',
  'profile.memberSince': 'Участник с',
  'profile.editPersonalInfo': 'Редактировать личную информацию',
  'profile.statistics': 'Статистика',
  'profile.verified': 'Верифицирован',
  'profile.completed': 'Завершено',
  'profile.active': 'Активно',

  // Avatar Upload
  'profile.avatar.changeAvatar': 'Изменить аватар',
  'profile.avatar.selectImage': 'Выбрать изображение',
  'profile.avatar.remove': 'Удалить',
  'profile.avatar.supportedFormats': 'Поддерживаемые форматы: JPG, PNG, WebP (макс 5MB)',
  'profile.avatar.invalidFileType': 'Недопустимый тип файла. Пожалуйста, выберите JPG, PNG или WebP изображение.',
  'profile.avatar.fileTooLarge': 'Файл слишком большой. Пожалуйста, выберите изображение меньше 5MB.',
  'profile.avatar.uploadError': 'Не удалось загрузить изображение. Пожалуйста, попробуйте еще раз.',

  // Statistics Modal
  'profile.statistics.title': 'Статистика аккаунта',
  'profile.statistics.description': 'Просмотр ваших метрик производительности и обзор активности',
  'profile.statistics.memberSince': 'Участник с',

  // Customer Statistics
  'profile.statistics.customer.overview': 'Обзор клиента',
  'profile.statistics.customer.performance': 'Метрики производительности',
  'profile.statistics.customer.successRate': 'Процент успеха',
  'profile.statistics.customer.responseRate': 'Процент ответов',

  // Professional Statistics
  'profile.statistics.professional.business': 'Обзор бизнеса',
  'profile.statistics.professional.performance': 'Метрики производительности',
  'profile.statistics.professional.repeatClients': 'Постоянные клиенты',
  'profile.statistics.professional.monthlyEarnings': 'Месячный доход',

  // Customer Profile
  'profile.customer.personalInfo': 'Личная информация',
  'profile.customer.statistics': 'Статистика',
  'profile.customer.tasksPosted': 'Размещено задач',
  'profile.customer.tasksCompleted': 'Завершено задач',
  'profile.customer.averageRating': 'Средняя оценка',
  'profile.customer.totalSpent': 'Всего потрачено',
  'profile.customer.recentActivity': 'Недавняя активность',
  'profile.customer.taskCompleted': 'Задача завершена',
  'profile.customer.taskPosted': 'Задача размещена',
  'profile.customer.viewAllTasks': 'Показать все задачи',
  'profile.customer.notificationPreferences': 'Настройки уведомлений',
  'profile.customer.smsNotifications': 'SMS уведомления',
  'profile.customer.smsNotificationsDesc': 'Получать важные обновления через текстовые сообщения',

  // Professional Profile
  'profile.professional.info': 'Профессиональная информация',
  'profile.professional.title': 'Профессиональная должность',
  'profile.professional.description': 'Описание',
  'profile.professional.hourlyRate': 'Почасовая ставка',
  'profile.professional.availability': 'Доступность',
  'profile.professional.skills': 'Навыки',
  'profile.professional.statistics': 'Статистика работы',
  'profile.professional.completedJobs': 'Выполненные работы',
  'profile.professional.totalEarnings': 'Общий доход',
  'profile.professional.responseTime': 'Время ответа',
  'profile.professional.performance': 'Показатели работы',
  'profile.professional.profileViews': 'Просмотры профиля',
  'profile.professional.completionRate': 'Процент завершения',
  'profile.professional.monthlyGrowth': 'Месячный рост',
  'profile.professional.recentWork': 'Недавние работы',
  'profile.professional.viewPortfolio': 'Смотреть портфолио',
  'profile.professional.setupTitle': 'Настройте ваш профессиональный профиль',
  'profile.professional.setupDescription': 'Заполните ваш профессиональный профиль, чтобы начать получать предложения работы и связаться с клиентами.',
  'profile.professional.setupProfile': 'Настроить профессиональный профиль',
  'profile.professional.businessSettings': 'Настройки бизнеса',
  'profile.professional.paymentMethod': 'Способ оплаты',
  'profile.professional.vatNumber': 'НДС номер',
  'profile.professional.serviceArea': 'Область обслуживания',
  'profile.professional.setupFormDescription': 'Заполните свою профессиональную информацию, чтобы продемонстрировать свои навыки и опыт.',
  'profile.professional.selectCategories': 'Выбрать категории',
  'profile.professional.serviceCategories': 'Категории услуг',
  'profile.professional.verificationTrust': 'Верификация и доверие',
  'profile.professional.phoneVerification': 'Верификация телефона',
  'profile.professional.phoneVerificationRequired': 'Обязательно для всех профессионалов',
  'profile.professional.verified': 'Верифицирован',
  'profile.professional.verifyPhone': 'Верифицировать телефон',
  'profile.professional.acceptedPaymentMethods': 'Принимаемые способы оплаты',
  'profile.professional.businessHours': 'Часы работы',
  'profile.professional.businessHoursPlaceholder': 'например: Пн-Пт 8:00-18:00, Сб 9:00-14:00',
  'profile.professional.weekdaysLabel': 'Будние дни (Пн-Пт)',
  'profile.professional.weekendLabel': 'Выходные (Сб-Вс)',
  'profile.professional.startTime': 'Время начала',
  'profile.professional.endTime': 'Время окончания',
  'profile.professional.noPaymentMethods': 'Не выбраны способы оплаты',
  'profile.professional.portfolioGallery': 'Галерея портфолио',
  'profile.professional.portfolioDescription': 'Покажите свою лучшую работу с фотографиями до/после',
  'profile.professional.addServiceCategories': 'Добавьте категории услуг',
  'profile.professional.categoriesHelp': 'Помогите клиентам найти вас! Выберите услуги, которые вы предлагаете, чтобы начать получать заявки.',

  // Professional Setup Form
  'profile.professional.form.titlePlaceholder': 'например: Full Stack Developer, UX Designer, Маркетинговый консультант',
  'profile.professional.form.descriptionPlaceholder': 'Опишите свой профессиональный опыт, экспертизу и то, что делает вас уникальным...',
  'profile.professional.form.experience': 'Уровень опыта',
  'profile.professional.form.portfolio': 'URL портфолио (по желанию)',
  'profile.professional.form.portfolioDescription': 'Ссылка на ваш сайт, GitHub или онлайн портфолио',
  'profile.professional.form.selectedSkills': 'Выбранные навыки',
  'profile.professional.form.searchSkills': 'Поиск навыков...',
  'profile.professional.form.suggestedSkills': 'Популярные навыки',
  'profile.professional.form.addCustomSkill': 'Добавить пользовательский навык',
  'profile.professional.form.customSkillPlaceholder': 'Введите название навыка',
  'profile.professional.form.moreSkillsAvailable': 'и еще {{count}}...',
  'profile.professional.form.skillsLimitNotice': 'Мы рекомендуем выбрать топ 10 навыков для лучших результатов.',
  'profile.professional.form.submitting': 'Создание профиля...',
  'profile.professional.form.createProfile': 'Создать профессиональный профиль',

  // Experience Options
  'profile.professional.form.experienceOptions.beginner': '0-1 года',
  'profile.professional.form.experienceOptions.intermediate': '2-5 лет',
  'profile.professional.form.experienceOptions.experienced': '5-10 лет',
  'profile.professional.form.experienceOptions.expert': '10+ лет',

  // Availability Options
  'profile.professional.form.availabilityOptions.available': 'Доступен',
  'profile.professional.form.availabilityOptions.busy': 'Занят',
  'profile.professional.form.availabilityOptions.unavailable': 'Недоступен',

  // Form Validation
  'profile.professional.form.validation.titleRequired': 'Профессиональная должность обязательна (минимум 3 символа)',
  'profile.professional.form.validation.descriptionRequired': 'Описание обязательно (минимум 20 символов)',
  'profile.professional.form.validation.rateRequired': 'Почасовая ставка должна быть больше 0',
  'profile.professional.form.validation.skillsRequired': 'Пожалуйста, выберите хотя бы один навык',

  // Settings Modal
  'profile.settings.description': 'Управляйте предпочтениями аккаунта и настройками конфиденциальности',

  // Telegram Connection
  'profile.telegramNotifications': 'Telegram Уведомления',
  'profile.telegramDescription': 'Подключите ваш Telegram аккаунт для получения мгновенных, бесплатных уведомлений',
  'profile.telegram.promptTitle': 'Получайте мгновенные уведомления!',
  'profile.telegram.promptDescription': 'Подключите ваш Telegram аккаунт, чтобы получать обновления в реальном времени о ваших задачах, заявках и сообщениях.',
  'profile.telegram.connectNow': 'Подключить Telegram',
  'profile.telegram.openTelegram': 'Открыть Telegram для подключения',
  'profile.connected': 'Подключен',
  'profile.notConnected': 'Не подключен',
  'profile.connectedAs': 'Подключен как',
  'profile.benefits': 'Преимущества',
  'profile.instantNotifications': 'Мгновенные уведомления (без задержек)',
  'profile.freeForever': 'Бесплатно навсегда (без SMS расходов)',
  'profile.noEmailSpam': 'Без email спама',
  'profile.richMessages': 'Богатые сообщения с кнопками и ссылками',
  'profile.connectTelegram': 'Подключить Telegram',
  'profile.disconnectTelegram': 'Отключить Telegram',
  'profile.telegramInstructions': 'Telegram откроется в новом окне. Нажмите кнопку в сообщении бота для завершения подключения.',
  'profile.telegramConnectError': 'Не удалось подключить Telegram. Пожалуйста, попробуйте снова.',
  'profile.telegramDisconnectConfirm': 'Вы уверены, что хотите отключить Telegram? Вы больше не будете получать мгновенные уведомления.',
  'profile.telegramDisconnectError': 'Не удалось отключить Telegram. Пожалуйста, попробуйте снова.',
  'profile.telegram.steps': 'Следуйте этим шагам',
  'profile.telegram.step1': 'Нажмите кнопку ниже, чтобы открыть Telegram бота',
  'profile.telegram.step2': 'Нажмите "Start" и скопируйте ваш Telegram ID',
  'profile.telegram.step3': 'Вставьте ваш Telegram ID ниже',
  'profile.telegram.enterId': 'Введите ваш Telegram ID',
  'profile.telegram.connect': 'Подключить',
  'profile.telegram.invalidIdFormat': 'Пожалуйста, введите действительный Telegram ID (только цифры)',
  'profile.telegram.openBot': 'Открыть Telegram бот',

  'profile.settings.notifications': 'Уведомления',
  'profile.settings.emailNotifications': 'Email уведомления',
  'profile.settings.emailNotificationsDesc': 'Получать обновления о ваших задачах и аккаунте',
  'profile.settings.taskUpdates': 'Обновления задач',
  'profile.settings.taskUpdatesDesc': 'Получать уведомления при обновлении задач',
  'profile.settings.marketingEmails': 'Маркетинговые письма',
  'profile.settings.marketingEmailsDesc': 'Получать советы и промо контент',
  'profile.settings.pushNotifications': 'Push уведомления',
  'profile.settings.pushNotificationsDesc': 'Получать мгновенные уведомления на ваше устройство',
  'profile.settings.weeklyDigest': 'Еженедельная сводка',
  'profile.settings.weeklyDigestDesc': 'Получать еженедельное резюме вашей активности и возможностей',
  'profile.settings.privacy': 'Конфиденциальность',
  'profile.settings.profileVisibility': 'Видимость профиля',
  'profile.settings.profileVisibilityDesc': 'Сделать ваш профиль видимым для потенциальных клиентов',
  'profile.settings.showContactInfo': 'Показывать контактную информацию',
  'profile.settings.showContactInfoDesc': 'Отображать вашу контактную информацию публично',
  'profile.settings.interface': 'Интерфейс',
  'profile.settings.darkMode': 'Темная тема',
  'profile.settings.darkModeDesc': 'Переключиться на темную тему интерфейса',
  'profile.settings.dangerZone': 'Опасная зона',
  'profile.settings.deleteAccount': 'Удалить аккаунт',
  'profile.settings.deleteAccountDesc': 'Навсегда удалить ваш аккаунт и все данные',
  'profile.settings.deleteAccountConfirm': 'Удаление аккаунта скоро будет реализовано',

  // Customer Profile Form
  'profile.form.name': 'Полное имя',
  'profile.form.saving': 'Сохранение...',
  'profile.form.validation.nameRequired': 'Имя обязательно (минимум 2 символа)',
  'profile.form.validation.emailRequired': 'Email обязателен',
  'profile.form.validation.emailInvalid': 'Пожалуйста, введите действительный email адрес',
  'profile.form.validation.phoneRequired': 'Номер телефона обязателен',
  'profile.form.validation.phoneInvalid': 'Пожалуйста, введите действительный номер телефона',
  'profile.form.validation.locationRequired': 'Местоположение обязательно (минимум 3 символа)',

  // Locations
  'locations.sofiaCenter': 'София, Центр',
  'locations.sofiaLyulin': 'София, Люлин',
  'locations.sofiaStudentski': 'София, Студенческий городок',
  'locations.sofiaVitosha': 'София, Витоша',
  'locations.plovdiv': 'Пловдив',
  'locations.varna': 'Варна',
  'locations.burgas': 'Бургас',
  'locations.ruse': 'Русе',
  'locations.staraZagora': 'Стара Загора',

  // Notifications
  'notifications.title': 'Уведомления',
  'notifications.markAllRead': 'Отметить все как прочитанное',
  'notifications.tabAll': 'Все',
  'notifications.tabApplications': 'Заявки',
  'notifications.tabTasks': 'Задачи',
  'notifications.tabMessages': 'Сообщения',
  'notifications.empty.title': 'Уведомлений пока нет',
  'notifications.empty.message': 'Вы получите уведомление, когда кто-то откликнется на ваши задачи или ответит на ваши заявки.',
  'notifications.empty.filterMessage': 'Нет уведомлений в этой категории.',
  'notifications.emptyUnread.title': 'Вы прочитали всё!',
  'notifications.emptyUnread.message': 'Все уведомления прочитаны.',
  'notifications.viewApplication': 'Посмотреть заявку',
  'notifications.viewTask': 'Посмотреть задачу',

  // Applications Management
  'applications.title': 'Заявки',
  'applications.count': 'заявок',
  'applications.sortBy': 'Сортировать по',
  'applications.sortNewest': 'Сначала новые',
  'applications.sortPriceLow': 'Цена: От низкой к высокой',
  'applications.sortPriceHigh': 'Цена: От высокой к низкой',
  'applications.sortRating': 'С лучшим рейтингом',
  'applications.sortExperience': 'Самые опытные',
  'applications.filterAll': 'Все',
  'applications.filterPending': 'В ожидании',
  'applications.filterAccepted': 'Принятые',
  'applications.filterRejected': 'Отклоненные',
  'applications.emptyState.title': 'Пока нет заявок',
  'applications.emptyState.message': 'Ваша задача опубликована! Специалисты скоро начнут откликаться.',
  'applications.proposedPrice': 'Предложенная цена',
  'applications.timeline': 'Сроки',
  'applications.message': 'Сообщение',
  'applications.portfolio': 'Портфолио',
  'applications.portfolioImages': 'примеров из портфолио',
  'applications.tasksCompleted': 'выполненных задач',
  'applications.yearsExperience': 'лет опыта',
  'applications.viewDetails': 'Посмотреть детали',
  'applications.acceptApplication': 'Принять',
  'applications.rejectApplication': 'Отклонить',
  'applications.status': 'Статус',
  'applications.statusPending': 'В ожидании',
  'applications.statusAccepted': 'Принята',
  'applications.statusRejected': 'Отклонена',

  // Application Detail Modal
  'applicationDetail.title': 'Детали заявки',
  'applicationDetail.professionalProfile': 'Профессиональный профиль',
  'applicationDetail.applicationMessage': 'Сообщение заявки',
  'applicationDetail.portfolioGallery': 'Портфолио',
  'applicationDetail.recentReviews': 'Последние отзывы',
  'applicationDetail.close': 'Закрыть',

  // Accept Application Dialog
  'acceptApplication.title': 'Принять заявку',
  'acceptApplication.description': 'Вы собираетесь принять заявку от {{name}}. Пожалуйста, проверьте детали и подтвердите ваше согласие.',
  'acceptApplication.agreedPrice': 'Согласованная цена',
  'acceptApplication.timeline': 'Сроки',
  'acceptApplication.pleaseConfirm': 'Пожалуйста, подтвердите:',
  'acceptApplication.agreement.priceTimeline': 'Я согласен с предложенной ценой ({{price}} {{currency}}) и сроками ({{timeline}})',
  'acceptApplication.agreement.contactSharing': 'Я понимаю, что моя контактная информация будет передана {{name}}',
  'acceptApplication.agreement.otherApplications': 'Я понимаю, что все остальные ожидающие заявки будут автоматически отклонены',
  'acceptApplication.warning': 'После принятия этой заявки вы обязуетесь работать с {{name}}. Все остальные заявки будут отклонены автоматически.',
  'acceptApplication.confirm': 'Принять заявку',
  'acceptApplication.cancel': 'Отмена',

  // Reject Application Dialog
  'rejectApplication.title': 'Отклонить заявку',
  'rejectApplication.description': 'Вы собираетесь отклонить заявку от {{name}}. Это действие уведомит специалиста, что вы не будете продолжать с его заявкой.',
  'rejectApplication.reasonTitle': 'Причина отклонения (по желанию)',
  'rejectApplication.reasonHelp': 'Указание причины помогает специалистам улучшить будущие заявки.',
  'rejectApplication.reasons.betterFit': 'Нашел более подходящего кандидата для этой задачи',
  'rejectApplication.reasons.priceHigh': 'Цена слишком высокая',
  'rejectApplication.reasons.timelineIssue': 'График мне не подходит',
  'rejectApplication.reasons.changedMind': 'Передумал насчет задачи',
  'rejectApplication.reasons.other': 'Другая причина',
  'rejectApplication.note': '{{name}} будет уведомлен, что его заявка не выбрана. Вы все еще можете просматривать другие заявки и принять другого специалиста.',
  'rejectApplication.confirm': 'Отклонить заявку',
  'rejectApplication.cancel': 'Отмена',

  // My Applications (Professional Applications Dashboard)
  'myApplications.title': 'Мои заявки',
  'myApplications.count': '{{count}} заявок',
  'myApplications.sortBy': 'Сортировать по',
  'myApplications.sortNewest': 'Сначала новые',
  'myApplications.sortOldest': 'Сначала старые',
  'myApplications.sortPriceHigh': 'Цена: От высокой к низкой',
  'myApplications.sortPriceLow': 'Цена: От низкой к высокой',
  'myApplications.filterAll': 'Все',
  'myApplications.filterPending': 'В ожидании',
  'myApplications.filterAccepted': 'Принятые',
  'myApplications.filterRejected': 'Отклоненные',
  'myApplications.filterWithdrawn': 'Отозванные',
  'myApplications.status.pending': 'В ожидании',
  'myApplications.status.accepted': 'Принята',
  'myApplications.status.rejected': 'Отклонена',
  'myApplications.status.withdrawn': 'Отозвана',
  'myApplications.yourQuote': 'Ваша цена',
  'myApplications.taskBudget': 'Бюджет задачи',

  'myApplications.viewDetails': 'Посмотреть детали',
  'myApplications.withdraw': 'Отозвать',
  'myApplications.messageCustomer': 'Написать клиенту',
  'myApplications.viewTask': 'Посмотреть задачу',
  'myApplications.markStarted': 'Отметить как начатую',
  'myApplications.markCompleted': 'Отметить как завершенную',
  'myApplications.reportIssue': 'Сообщить о проблеме',
  'myApplications.findSimilar': 'Найти похожие',

  'myApplications.emptyState.title': 'Вы еще не подавали заявки на задачи',
  'myApplications.emptyState.message': 'Начните просматривать доступные задачи и подавайте заявки на те, которые соответствуют вашим навыкам.',

  // Application Detail Modal

  'myApplications.detail.taskDetails': 'Детали задачи',

  'myApplications.detail.yourProposal': 'Ваше предложение',

  'myApplications.detail.waitingResponse': 'Ожидание ответа клиента',
  'myApplications.detail.usuallyResponds': 'Обычно клиенты отвечают в течение 24-48 часов.',
  'myApplications.detail.otherApplicants': 'Также подали заявки еще {{count}} человек.',
  'myApplications.detail.customerApproved': 'Клиент одобрил вашу заявку',
  'myApplications.detail.nextSteps': 'Следующие шаги:',
  'myApplications.detail.contactCustomer': 'Свяжитесь с клиентом для уточнения деталей',

  'myApplications.detail.feedback': 'Не принимайте это на свой счет! Продолжайте подавать заявки на похожие задачи.',
  'myApplications.detail.rejectionReason': 'Причина отказа',

  // Withdraw Dialog
  'myApplications.withdrawDialog.title': 'Отозвать заявку?',

  'myApplications.withdrawDialog.reason': 'Причина отзыва (необязательно)',

  'myApplications.withdrawDialog.reasonUnavailable': 'Больше недоступен',
  'myApplications.withdrawDialog.reasonFoundWork': 'Нашел другую работу',
  'myApplications.withdrawDialog.reasonChanged': 'Передумал',
  'myApplications.withdrawDialog.reasonPrice': 'Цена слишком низкая',
  'myApplications.withdrawDialog.reasonOther': 'Другая причина',
  'myApplications.withdrawDialog.cancel': 'Отмена',
  'myApplications.withdrawDialog.confirm': 'Отозвать заявку',

  // Task Status
  'taskStatus.open': 'Открыта',
  'taskStatus.inProgress': 'В процессе',

  'taskStatus.completed': 'Завершена',
  'taskStatus.cancelled': 'Отменена',

  'taskStatus.openTooltip': 'Задача открыта для заявок специалистов',
  'taskStatus.inProgressTooltip': 'Специалист работает над этой задачей',

  'taskStatus.completedTooltip': 'Обе стороны подтвердили завершение задачи',
  'taskStatus.cancelledTooltip': 'Задача была отменена',
  'taskStatus.disputedTooltip': 'Возникли разногласия, требуется разрешение',

  // Task Completion
  'taskCompletion.markCompleted': 'Отметить как завершённую',
  'taskCompletion.confirmCompletion': 'Подтвердить завершение',
  'taskCompletion.alreadyMarkedByYou': 'Вы уже отметили как завершённую',
  'taskCompletion.alreadyConfirmedByYou': 'Вы уже подтвердили завершение',
  'taskCompletion.rejectCompletion': 'Отклонить завершение',

  // Mark Completed Dialog (Professional)
  'taskCompletion.markDialog.title': 'Отметить задачу как завершённую',

  'taskCompletion.markDialog.notesPlaceholder': 'Добавьте любые дополнительные детали о выполненной работе...',

  // Confirm Completion Dialog (Customer)
  'taskCompletion.confirmDialog.title': 'Подтвердить завершение задачи',

  'taskCompletion.confirmDialog.question': 'Вы удовлетворены выполненной работой?',
  'taskCompletion.confirmDialog.yes': 'Да, я удовлетворён',
  'taskCompletion.confirmDialog.no': 'Нет, у меня есть замечания',

  // Reject Completion
  'taskCompletion.reject.title': 'Укажите свои замечания',

  'taskCompletion.reject.notCompleted': 'Работа не завершена',
  'taskCompletion.reject.poorQuality': 'Качество не соответствует ожиданиям',
  'taskCompletion.reject.differentScope': 'Работа отличается от согласованной',
  'taskCompletion.reject.other': 'Другая причина',

  'taskCompletion.reject.disclaimer': 'Эта задача вернётся к статусу "В процессе" и может снова стать видимой для других специалистов, если работа не может быть завершена с текущим специалистом.',
  'taskCompletion.reject.button': 'Отклонить',

  // Pending Confirmation Banners
  'taskCompletion.pending.waitingCustomer': 'Ожидание подтверждения клиента',
  'taskCompletion.pending.waitingProfessional': 'Ожидание подтверждения специалиста',
  'taskCompletion.pending.youMarked': 'Вы отметили эту задачу как завершённую.',
  'taskCompletion.pending.waitingFor': 'Ожидание подтверждения от',
  'taskCompletion.pending.toConfirm': 'для завершения задачи.',
  'taskCompletion.pending.professionalMarkedComplete': 'Специалист отметил задачу как завершённую',
  'taskCompletion.pending.customerMarkedComplete': 'Клиент отметил задачу как завершённую',
  'taskCompletion.pending.markedComplete': 'отметил эту задачу как завершённую. Пожалуйста, проверьте работу.',

  // Success View
  'taskCompletion.success.title': 'Задача завершена!',
  'taskCompletion.success.message': 'Обе стороны подтвердили завершение этой задачи',
  'taskCompletion.success.nextSteps': 'Следующие шаги',
  'taskCompletion.success.step1': 'Оставить отзыв',
  'taskCompletion.success.step1Description': 'Помогите другим, поделившись своим опытом работы с {{name}}',
  'taskCompletion.success.step2': 'Просмотреть детали',
  'taskCompletion.success.step2Description': 'Получите доступ к полному резюме задачи и фотографиям завершения',
  'taskCompletion.success.leaveReview': 'Оставить отзыв',
  'taskCompletion.success.viewDetails': 'Просмотреть детали',

  // Timeline
  'taskCompletion.timeline.title': 'Прогресс завершения',
  'taskCompletion.timeline.started': 'Задача начата',
  'taskCompletion.timeline.proMarked': 'Специалист отметил как завершённую',
  'taskCompletion.timeline.customerConfirmed': 'Клиент подтвердил',
  'taskCompletion.timeline.completed': 'Задача завершена',
  'taskCompletion.timeline.pending': 'В ожидании',
  'taskCompletion.timeline.totalDuration': 'Общая продолжительность',

  // Common
  'common.optional': 'необязательно',
  'common.days': 'дней',
  'common.cancel': 'Отмена',

  close: 'Закрыть',
};
