// Professionals page and professional detail translations
export const professionals = {
  'professionals.hero.title': 'Найдите проверенных специалистов',
  'professionals.hero.subtitle':
    'Просматривайте верифицированных специалистов по категориям и найдите идеальное соответствие для ваших потребностей',
  'professionals.hero.badge': 'Сеть профессионалов',
  'professionals.searchPlaceholder':
    'Поиск категорий... (например, ремонт, уборка, уроки)',
  'professionals.allCategories': 'Все категории',
  'professionals.featuredTitle': 'Рекомендуемые специалисты',
  'professionals.viewProfile': 'Посмотреть профиль',
  'professionals.rating': 'Рейтинг',
  'professionals.completedJobs': 'Выполненные задания',
  'professionals.startingFrom': 'Начиная от',
  'professionals.noResults': 'Нет категорий, соответствующих вашему поиску',
  'professionals.categoryResults': 'категории найдены',
  'professionals.filterBy': 'Фильтровать по',
  'professionals.location': 'Местоположение',
  'professionals.experience': 'Опыт',
  'professionals.priceRange': 'Ценовой диапазон',
  'professionals.availability': 'Доступность',
  'professionals.findPerfect': 'Найдите идеального профессионала',
  'professionals.discoverTrusted':
    'Откройте для себя надежных профессионалов с проверенной репутацией и отличными отзывами',
  'professionals.popularCategories': 'Популярные категории',
  'professionals.refineSearch': 'Уточните результаты поиска',
  'professionals.professionalsAvailable': 'доступных профессионалов',
  'professionals.noMatchingResults':
    'Нет профессионалов, соответствующих вашим критериям. Попробуйте расширить поиск.',
  'professionals.mostActive': 'Наиболее активные',
  'professionals.specialists': 'Специалисты',
  'professionals.stars': 'звезд',
  'professionals.gender.male': 'Мужчина',
  'professionals.gender.female': 'Женщина',
  'professionals.filters.category': 'Категория',
  'professionals.filters.location': 'Местоположение',
  'professionals.filters.minimumRating': 'Минимальный рейтинг',
  'professionals.filters.genderPreference': 'Предпочтение по полу',
  'professionals.filters.activityLevel': 'Уровень активности',
  'professionals.filters.all': 'Все',
  'professionals.filters.topPerformersOnly': 'Только топ исполнители',
  'professionals.filters.locationPlaceholder': 'София, Пловдив, Варна...',
  'professionals.filters.any': 'Любой',
  'professionals.filters.anyShort': 'Любой',
  'professionals.typing.plumber': 'сантехник в Софии',
  'professionals.typing.cleaner': 'специалист по уборке',
  'professionals.typing.electrician': 'сертифицированный электрик',
  'professionals.typing.tutor': 'учитель английского',
  'professionals.typing.photographer': 'свадебный фотограф',
  'professionals.typing.handyman': 'мастер на все руки',
  'professionals.recommendedTitle': 'РЕКОМЕНДУЕМЫЕ ПРОФЕССИОНАЛЫ',
  'professionals.filters.clear': 'Очистить',
  'professionals.filters.clearAll': 'Очистить все фильтры',
  'professionals.filters.fourPlusStars': '4+ звезд',
  'professionals.filters.fiveStarsOnly': 'Только 5 звезд',
  'professionals.filters.anyRating': 'По рейтингу',
  'professionals.filters.showProfessionalsWithAnyRating':
    'Показать профессионалов с любым рейтингом',
  'professionals.filters.locationPlaceholderDesktop': '📍 Местоположение',
  'professionals.sorting.featuredFirst': 'Топ выбор',
  'professionals.sorting.featuredFirstDesc': 'Лучшие профессионалы',
  'professionals.sorting.highestRating': 'По рейтингу',
  'professionals.sorting.highestRatingDesc': 'С лучшими отзывами',
  'professionals.sorting.mostExperience': 'По опыту',
  'professionals.sorting.mostExperienceDesc': 'Много заказов',
  'professionals.filters.sortResultsBy': 'Сортировка по',
  'professionals.filters.sortResultsTitle': 'Сортировка',
  'professionals.filters.sortResultsDescription':
    'Выберите, как упорядочить профессионалов',
  'professionals.filters.selectMinimumRating': 'Выберите минимальный рейтинг',
  'professionals.filters.showingVerifiedFirst':
    'Показать проверенных топ профессионалов первыми',
  'professionals.filters.proTip': 'Совет',
  'professionals.filters.proTipMessage':
    'Попробуйте "{{sortOption}}" для качественных профессионалов с подтвержденными квалификациями',
  'professionals.filters.sortingBy': 'Сортировка по {{option}}',
  'professionals.filters.sortingDescFeatured':
    'Показать проверенных топ профессионалов первыми',
  'professionals.filters.sortingDescRating':
    'Профессионалы с высшим рейтингом показываются первыми',
  'professionals.filters.sortingDescJobs':
    'Самые опытные профессионалы показываются первыми',
  'professionals.filters.activeFilters': 'Активные фильтры',
  'professionals.filters.filterApplied': '{{count}} фильтр применен',
  'professionals.filters.filtersApplied': '{{count}} фильтров применено',
  'professionals.filters.showProfessionalsWithRating':
    'Показать профессионалов с {{rating}}+ звездным рейтингом',
  'professionals.filters.showPerfectRating':
    'Показать только профессионалов с совершенным 5-звездным рейтингом',

  'professionalDetail.about': 'О специалисте',
  'professionalDetail.reviews': 'отзывов',
  'professionalDetail.online': 'Онлайн',
  'professionalDetail.offline': 'Недавно был в сети',
  'professionalDetail.verified.phone': 'Телефон',
  'professionalDetail.verified.id': 'Документ',
  'professionalDetail.stats.completedTasks': 'Задач',
  'professionalDetail.stats.yearsExperience': 'Лет',
  'professionalDetail.stats.responseTime': 'Ответ',
  'professionalDetail.actions.proposeTask': 'Предложить задачу',
  'professionalDetail.actions.contact': 'Связаться',
  'professionalDetail.actions.askQuestion': 'Задать вопрос',
  'professionalDetail.actions.saveToFavorites': 'В избранное',
  'professionalDetail.contactHours': 'Доступен',
  'professionalDetail.services.title': 'Услуги и цены',
  'professionalDetail.services.pricingNote.title': 'Информация о ценах',
  'professionalDetail.services.pricingNote.description':
    'Окончательные цены согласовываются индивидуально в зависимости от сложности и требований задачи.',
  'professionalDetail.portfolio.title': 'Мои примеры',
  'professionalDetail.portfolio.noWork': 'Пока нет примеров',
  'professionalDetail.portfolio.before': 'До',
  'professionalDetail.portfolio.after': 'После',
  'professionalDetail.portfolio.viewMore': 'Посмотреть все примеры',
  'professionalDetail.portfolio.showcase': 'Профессиональные примеры работ',
  'professionalDetail.completedTasks.title': 'Выполненные задачи',
  'professionalDetail.completedTasks.noTasks': 'Пока нет выполненных задач',
  'professionalDetail.completedTasks.hugePotential': 'У этого специалиста огромный потенциал!',
  'professionalDetail.completedTasks.comingSoon': 'Отличная работа скоро появится...',
  'professionalDetail.completedTasks.watchThisSpace': 'Следите за этим местом для удивительных завершенных проектов!',
  'professionalDetail.completedTasks.viewTask': 'Посмотреть задачу',
  'professionalDetail.completedTasks.completedOn': 'Выполнено',
  'professionalDetail.reviews.title': 'Отзывы и рейтинги',
  'professionalDetail.reviews.count': 'отзывов',
  'professionalDetail.reviews.recentRating': 'Недавний рейтинг',
  'professionalDetail.reviews.excellent': 'Отлично',
  'professionalDetail.reviews.noReviews': 'Пока нет отзывов',
  'professionalDetail.reviews.beFirst': 'Станьте первым, кто оставит отзыв',
  'professionalDetail.reviews.showMore': 'Показать все отзывы',
  'professionalDetail.reviews.allReviews': 'Все отзывы',
  'professionalDetail.reviews.avgRating': 'Средний рейтинг',
  'professionalDetail.reviews.more': 'ещё',
  'professionalDetail.completedTasks.stats.tasksCompleted': 'Выполненных задач',
  'professionalDetail.completedTasks.stats.avgRating': 'Средний рейтинг',
  'professionalDetail.completedTasks.stats.fiveStarTasks':
    '5-звёздочные задачи',
  'professionalDetail.verified': 'Подтверждён',
};
