// Professionals page and professional detail translations
export const professionals = {
  'professionals.hero.title': 'Найдите проверенных специалистов',
  'professionals.hero.subtitle':
    'Просматривайте верифицированных специалистов по категориям и найдите идеальное соответствие для ваших потребностей',
  'professionals.hero.badge': 'Сеть профессионалов',
  'professionals.hero.stats.verified.value': 'Надежные специалисты',
  'professionals.hero.stats.verified.label': 'Становится больше каждый день',
  'professionals.hero.stats.ratings.value': 'Проверенное качество',
  'professionals.hero.stats.ratings.label': 'На основе реальных рейтингов и отзывов',
  'professionals.hero.stats.jobs.value': 'Активная сеть',
  'professionals.hero.stats.jobs.label': 'Много заданий каждый день',
  'professionals.searchPlaceholder':
    'Поиск категорий... (например, ремонт, уборка, уроки)',
  'professionals.search.popular': 'Популярные',
  'professionals.search.categories': 'Категории услуг',
  'professionals.allCategories': 'Все категории',
  'professionals.featuredTitle': 'Рекомендуемые специалисты',
  'professionals.viewProfile': 'Посмотреть профиль',
  'professionals.suggestTask': 'Предложить задачу',
  'professionals.viewProfessionals': 'Посмотреть специалистов',
  'professionals.rating': 'Рейтинг',
  'professionals.completedJobs': 'Выполненные задания',
  'professionals.card.completedJobs': 'выполненных заданий',
  'professionals.card.completedJobsShort': 'заданий',
  'professionals.card.lookingForFirstTask': 'Готов к первому заданию',
  'professionals.card.waitingForReviews': 'Ожидает первых отзывов',
  'professionals.startingFrom': 'Начиная от',
  'professionals.noResults': 'Нет категорий, соответствующих вашему поиску',
  'professionals.categoryResults': 'категории найдены',
  'professionals.filterBy': 'Фильтровать по',
  'professionals.location': 'Местоположение',
  'professionals.experience': 'Опыт',
  'professionals.priceRange': 'Ценовой диапазон',
  'professionals.availability': 'Доступность',
  'professionals.findPerfect': 'Найдите идеального профессионала',
  'professionals.discoverTrusted':
    'Откройте для себя надежных профессионалов с проверенной репутацией и отличными отзывами',
  'professionals.popularCategories': 'Популярные категории',
  'professionals.refineSearch': 'Уточните результаты поиска',
  'professionals.professionalsAvailable': 'доступных профессионалов',
  'professionals.noProfessionalsFound': 'Профессионалы не найдены',
  'professionals.tryAdjustingFilters': 'Попробуйте изменить фильтры или условия поиска, чтобы найти больше профессионалов.',
  'professionals.noMatchingResults':
    'Нет профессионалов, соответствующих вашим критериям. Попробуйте расширить поиск.',
  'professionals.mostActive': 'Наиболее активные',
  'professionals.specialists': 'Специалисты',
  'professionals.stars': 'звезд',
  'professionals.gender.male': 'Мужчина',
  'professionals.gender.female': 'Женщина',
  'professionals.filters.category': 'Категория',
  'professionals.filters.city': 'Город',
  'professionals.filters.location': 'Местоположение',
  'professionals.filters.minimumRating': 'Минимальный рейтинг',
  'professionals.filters.minRating': 'Мин. рейтинг',
  'professionals.filters.minJobs': 'Мин. работ',
  'professionals.filters.jobs': 'работ',
  'professionals.filters.sortBy': 'Сортировать по',
  'professionals.filters.genderPreference': 'Предпочтение по полу',
  'professionals.filters.activityLevel': 'Уровень активности',
  'professionals.filters.all': 'Все',
  'professionals.filters.topPerformersOnly': 'Только топ исполнители',
  'professionals.filters.locationPlaceholder': 'София, Пловдив, Варна...',
  'professionals.filters.any': 'Любой',
  'professionals.filters.anyShort': 'Любой',
  'professionals.typing.plumber': 'сантехник в Софии',
  'professionals.typing.cleaner': 'специалист по уборке',
  'professionals.typing.electrician': 'сертифицированный электрик',
  'professionals.typing.tutor': 'учитель английского',
  'professionals.typing.photographer': 'свадебный фотограф',
  'professionals.typing.handyman': 'мастер на все руки',
  'professionals.recommendedTitle': 'РЕКОМЕНДУЕМЫЕ ПРОФЕССИОНАЛЫ',
  'professionals.filters.clear': 'Очистить',
  'professionals.filters.clearAll': 'Очистить все фильтры',
  'professionals.filters.fourPlusStars': '4+ звезд',
  'professionals.filters.fiveStarsOnly': 'Только 5 звезд',
  'professionals.filters.anyRating': 'По рейтингу',
  'professionals.filters.showProfessionalsWithAnyRating':
    'Показать профессионалов с любым рейтингом',
  'professionals.filters.locationPlaceholderDesktop': '📍 Местоположение',
  'professionals.sorting.featuredFirst': 'Топ выбор',
  'professionals.sorting.featuredFirstDesc': 'Лучшие профессионалы',
  'professionals.sorting.highestRating': 'По рейтингу',
  'professionals.sorting.highestRatingDesc': 'С лучшими отзывами',
  'professionals.sorting.mostExperience': 'По опыту',
  'professionals.sorting.mostExperienceDesc': 'Много заказов',
  'professionals.filters.sortResultsBy': 'Сортировка по',
  'professionals.filters.sortResultsTitle': 'Сортировка',
  'professionals.filters.sortResultsDescription':
    'Выберите, как упорядочить профессионалов',
  'professionals.filters.selectMinimumRating': 'Выберите минимальный рейтинг',
  'professionals.filters.showingVerifiedFirst':
    'Показать проверенных топ профессионалов первыми',
  'professionals.filters.sortingBy': 'Сортировка по {option}',
  'professionals.filters.sortingDescFeatured':
    'Показать проверенных топ профессионалов первыми',
  'professionals.filters.sortingDescRating':
    'Профессионалы с высшим рейтингом показываются первыми',
  'professionals.filters.sortingDescJobs':
    'Самые опытные профессионалы показываются первыми',
  'professionals.filters.activeFilters': 'Активные фильтры',
  'professionals.filters.filterApplied': '{count} фильтр применен',
  'professionals.filters.filtersApplied': '{count} фильтров применено',
  'professionals.filters.showProfessionalsWithRating':
    'Показать профессионалов с {rating}+ звездным рейтингом',
  'professionals.filters.showPerfectRating':
    'Показать только профессионалов с совершенным 5-звездным рейтингом',

  // Results section
  'professionals.results.showing': 'Показано {count} специалистов',
  'professionals.results.loading': 'Загрузка специалистов...',
  'professionals.results.noResults.title': 'Специалисты не найдены',
  'professionals.results.noResults.description':
    'Попробуйте изменить фильтры или поискать в другом районе',
  'professionals.results.noResults.clearFilters': 'Очистить фильтры',
  'professionals.results.error.title': 'Упс! Что-то пошло не так',
  'professionals.results.error.description': 'Нашим серверам нужен кофе-брейк',
  'professionals.results.error.subtext': 'Не волнуйтесь, мы уже работаем над этим!',
  'professionals.results.error.retry': 'Попробовать снова',
  'professionals.results.mockTitle': 'Примерные специалисты (Справка)',
  'professionals.results.mockDescription':
    'Образцы данных, демонстрирующие будущие функции: портфолио, сертификаты, особые случаи',
  'professionals.results.mockBadge1': 'Для разработки',
  'professionals.results.mockBadge2': 'Не реальные пользователи',
  'professionals.results.featured.title': 'Рекомендуемые специалисты',
  'professionals.results.featured.description':
    'Ознакомьтесь с этими высококлассными специалистами из нашей сети',
  'professionals.results.allLoaded': 'Вы достигли конца списка',
  'professionals.results.loadingMore': 'Загрузка ещё специалистов...',

  // Pagination
  'professionals.pagination.previous': 'Предыдущая',
  'professionals.pagination.next': 'Следующая',
  'professionals.pagination.pageOf': 'Страница {current} из {total}',

  'professionalDetail.about': 'О специалисте',
  'professionalDetail.reviews': 'отзывов',
  'professionalDetail.online': 'Онлайн',
  'professionalDetail.offline': 'Недавно был в сети',
  'professionalDetail.verified.phone': 'Телефон',
  'professionalDetail.verified.id': 'Документ',
  'professionalDetail.stats.completedTasks': 'Задач(и)',
  'professionalDetail.stats.yearsExperience': 'Лет',
  'professionalDetail.stats.yearsExperienceLabel': 'лет',
  'professionalDetail.stats.experience': 'Опыт',
  'professionalDetail.stats.responseTime': 'Ответ',
  'professionalDetail.defaultBio': 'Профессиональный специалист с опытом работы в сфере.',
  'professionalDetail.actions.suggestMyTask': 'Предложить мою задачу',
  'professionalDetail.actions.inviteToApply': 'Предложить задачу',
  'professionalDetail.actions.contact': 'Связаться',
  'professionalDetail.actions.share': 'Поделиться',
  'professionalDetail.contactHours': 'Доступен',
  'professionalDetail.services.title': 'Услуги и цены',
  'professionalDetail.services.pricingNote.title': 'Информация о ценах',
  'professionalDetail.services.pricingNote.description':
    'Окончательные цены согласовываются индивидуально в зависимости от сложности и требований задачи.',
  'professionalDetail.portfolio.title': 'Мои примеры',
  'professionalDetail.portfolio.noWork': 'Пока нет примеров',
  'professionalDetail.portfolio.emptyState': 'Этот специалист ещё не обновил свои примеры работ. Мы постоянно просим его добавить их - может быть, нам повезёт завтра!',
  'professionalDetail.portfolio.emptyStateCTA': 'Загляните сюда позже, чтобы увидеть его потрясающие работы',
  'professionalDetail.portfolio.before': 'До',
  'professionalDetail.portfolio.after': 'После',
  'professionalDetail.portfolio.viewMore': 'Посмотреть все примеры',
  'professionalDetail.portfolio.showcase': 'Профессиональные примеры работ',

  // Gallery (Premium Feature)
  'professionalDetail.gallery.title': 'Галерея работ',
  'professionalDetail.gallery.subtitle': 'Примеры выполненных работ',
  'professionalDetail.gallery.imageView': 'Просмотр изображения',

  'professionalDetail.completedTasks.title': 'Выполненные задачи',
  'professionalDetail.completedTasks.noTasks': 'Пока нет выполненных задач',
  'professionalDetail.completedTasks.hugePotential':
    'У этого специалиста огромный потенциал!',
  'professionalDetail.completedTasks.comingSoon':
    'Отличная работа скоро появится...',
  'professionalDetail.completedTasks.watchThisSpace':
    'Следите за этим местом для удивительных завершенных проектов!',
  'professionalDetail.completedTasks.emptyState': 'Этот специалист выполнил множество задач, но пока не с нами. Пожалуйста, помогите нам обогатить эту страницу вашей задачей!',
  'professionalDetail.completedTasks.emptyStateCTA': 'Предложите ему задачу и станьте его первым клиентом на нашей платформе',
  'professionalDetail.completedTasks.viewTask': 'Посмотреть задачу',
  'professionalDetail.completedTasks.completedOn': 'Выполнено',
  'professionalDetail.reviews.title': 'Отзывы и рейтинги',
  'professionalDetail.reviews.count': 'отзывов',
  'professionalDetail.reviews.recentRating': 'Недавний рейтинг',
  'professionalDetail.reviews.excellent': 'Отлично',
  'professionalDetail.reviews.noReviews': 'Пока нет отзывов',
  'professionalDetail.reviews.beFirst': 'Станьте первым, кто оставит отзыв',
  'professionalDetail.reviews.emptyState': 'Отзывы для этого специалиста появятся в ближайшее время. Предложите ему задачу, чтобы оценить его тоже!',
  'professionalDetail.reviews.emptyStateCTA': 'Станьте первым, кто поработает с этим специалистом и оставит отзыв',
  'professionalDetail.reviews.showMore': 'Показать все отзывы',
  'professionalDetail.reviews.allReviews': 'Все отзывы',
  'professionalDetail.reviews.avgRating': 'Средний рейтинг',
  'professionalDetail.reviews.more': 'ещё',
  'professionalDetail.completedTasks.stats.tasksCompleted': 'Выполненных задач',
  'professionalDetail.completedTasks.stats.avgRating': 'Средний рейтинг',
  'professionalDetail.completedTasks.stats.fiveStarTasks':
    '5-звёздочные задачи',
  'professionalDetail.completedTasks.pendingReview': 'Ожидает отзыв',
  'professionalDetail.completedTasks.viewAll': 'Посмотреть все {count} задач',
  'professionalDetail.completedTasks.totalTasks': 'Всего задач',
  'professionalDetail.completedTasks.averageRatingStars': 'Средний рейтинг: {rating} звёзд',
  'professionalDetail.verified': 'Подтверждён',
  'professionalDetail.shareText': 'Посмотрите на этого специалиста в Trudify',
  'professionalDetail.shareSuccess': 'Успешно поделились!',
  'professionalDetail.linkCopied': 'Ссылка скопирована!',
  'professionalDetail.copyError': 'Не удалось скопировать ссылку',
  'professionals.filters.filtersButton': 'Фильтры',
  'professionals.filters.active': 'активных',
  'professionals.filters.showResults': 'Показать результаты',
  'professionals.filters.reset': 'Сбросить',
  'professionals.filters.filters': 'Фильтры',

  // Professional Badges
  'professionals.badge.topProfessionalLabel': 'Топ Про',
  'professionals.badge.topProfessional.tooltip': 'Выполнил {count} задач за последние 30 дней',
  'professionals.badge.earlyAdopterLabel': 'Ранний последователь',
  'professionals.badge.earlyAdopter.tooltip': 'Один из первых специалистов на нашей платформе. Спасибо, что поверили в нас с самого начала!',
  'professionals.badge.featuredProfessionalLabel': 'Избранный специалист',
  'professionals.badge.featuredProfessional.tooltip': 'Лично отобран нашей командой за исключительное качество и надёжность. Этот специалист прошёл проверку и рекомендован нами.',

  // Invite Modal
  'inviteModal.title': 'Пригласить специалиста на задачу',
  'inviteModal.subtitle': 'Выберите, на какую задачу пригласить {name}',
  'inviteModal.selectLabel': 'Выберите задачу',
  'inviteModal.selectPlaceholder': 'Выберите вашу задачу',
  'inviteModal.noTasks': 'У вас пока нет открытых задач.',
  'inviteModal.createTaskHint': 'Сначала создайте задачу, чтобы пригласить этого специалиста.',
  'inviteModal.confirmText': 'получит уведомление об этом приглашении на задачу.',
  'inviteModal.sendInvitation': 'Отправить приглашение',
  'inviteModal.success': 'Приглашение отправлено!',
  'inviteModal.successDescription': '{name} будет уведомлен о вашей задаче.',
  'inviteModal.error': 'Не удалось отправить приглашение',
  'inviteModal.errorFetchingTasks': 'Не удалось загрузить ваши задачи',
  'inviteModal.alreadyInvited': 'Уже приглашён',
  'inviteModal.alreadyInvitedDescription': 'Вы уже пригласили {name} на эту задачу.',
  'inviteModal.alreadyInvitedProfessional': 'Уже приглашён',
  'inviteModal.alreadyInvitedProfessionalDescription': 'Вы уже пригласили {name} на вашу задачу. Они могут откликнуться в течение 24 часов, если доступны.',
  'inviteModal.selfInviteTitle': '🤔 Хорошая попытка!',
  'inviteModal.selfInviteDescription': 'Нельзя предложить задачу самому себе. Но мы ценим креативность!',
  'inviteModal.createNewTask': 'Создать новую задачу',
  'inviteModal.loadingTasks': 'Загрузка ваших задач...',
  'inviteModal.continue': 'Продолжить',
};
