// Task-related translations - browsing, creating, task cards, task detail
export const tasks = {
  'tasks.title': 'Обзор задач',
  'tasks.subtitle':
    'Найдите идеальную задачу, которая соответствует вашим навыкам и интересам',
  'tasks.searchPlaceholder':
    'Поиск задач по ключевым словам, категориям или местоположению...',
  'tasks.filters.title': 'Фильтры',
  'tasks.filters.category': 'Категория',
  'tasks.filters.allCategories': 'Все категории',
  'tasks.filters.location': 'Местоположение',
  'tasks.filters.budget': 'Бюджет',
  'tasks.filters.budgetMin': 'Мин. бюджет',
  'tasks.filters.budgetMax': 'Макс. бюджет',
  'tasks.filters.deadline': 'Срок',
  'tasks.filters.status': 'Статус',
  'tasks.filters.all': 'Все',
  'tasks.filters.open': 'Открытые',
  'tasks.filters.inProgress': 'В процессе',
  'tasks.filters.completed': 'Завершенные',
  'tasks.filters.activeFilters': 'Активные фильтры',
  'tasks.filters.clearAll': 'Очистить все',
  'tasks.results': 'результатов',
  'tasks.sort.newest': 'Сначала новые',
  'tasks.sort.oldest': 'Сначала старые',
  'tasks.sort.budgetHigh': 'Высокий бюджет',
  'tasks.sort.budgetLow': 'Низкий бюджет',
  'tasks.sort.deadline': 'По сроку',

  'browseTasks.hero.badge': 'Зарабатывайте сейчас',
  'browseTasks.hero.title1': 'Найдите следующую',
  'browseTasks.hero.title2': 'возможность',
  'browseTasks.hero.subtitle':
    'Просматривайте проверенные задачи от реальных клиентов. Создавайте доход по своему графику.',
  'browseTasks.search.placeholder':
    'Поиск задач по ключевым словам, категории или городу...',
  'browseTasks.search.popular': 'Популярные',
  'browseTasks.search.searchingCategories': 'Поиск категорий...',
  'browseTasks.search.suggestedCategories': 'Предлагаемые категории',
  'browseTasks.search.categories': 'Категории',
  'browseTasks.search.cities': 'Города',
  'browseTasks.filters.title': 'Фильтрация и сортировка',
  'browseTasks.filters.advanced': 'Расширенные фильтры',
  'browseTasks.filters.quick': 'Быстрый фильтр',
  'browseTasks.filters.searchPlaceholder':
    'Поиск задач... (например, уборка, ремонт, доставка)',
  'browseTasks.filters.category': 'Категория',
  'browseTasks.filters.allCategories': 'Все категории',
  'browseTasks.filters.city': 'Город',
  'browseTasks.filters.allCities': 'Все города',
  'browseTasks.filters.cities.sofia': 'София',
  'browseTasks.filters.cities.plovdiv': 'Пловдив',
  'browseTasks.filters.cities.varna': 'Варна',
  'browseTasks.filters.cities.burgas': 'Бургас',
  'browseTasks.filters.budget': 'Бюджет',
  'browseTasks.filters.budgetMin': 'Мин',
  'browseTasks.filters.budgetMax': 'Макс',
  'browseTasks.filters.budgetUpTo': 'До 500 лв',
  'browseTasks.filters.sortBy': 'Сортировка',
  'browseTasks.filters.sort.newest': 'Новые',
  'browseTasks.filters.sort.oldest': 'Старые',
  'browseTasks.filters.sort.highBudget': 'Высокий бюджет',
  'browseTasks.filters.sort.lowBudget': 'Низкий бюджет',
  'browseTasks.filters.filters': 'Фильтры',
  'browseTasks.filters.active': 'активных',
  'browseTasks.filters.reset': 'Сбросить',
  'browseTasks.filters.showResults': 'Показать результаты',
  'browseTasks.filters.clear': 'Очистить',
  'browseTasks.filters.customRange': 'Пользовательский диапазон',
  'browseTasks.filters.min': 'Мин',
  'browseTasks.filters.max': 'Макс',
  'browseTasks.filters.apply': 'Применить',
  'browseTasks.filters.urgency': 'Срочность',
  'browseTasks.filters.urgentSameDay': 'Срочно (Сегодня)',
  'browseTasks.filters.thisWeek': 'На этой неделе',
  'browseTasks.filters.flexible': 'Гибко',
  'browseTasks.filters.searchCity': 'Поиск города...',
  'browseTasks.filters.noCitiesFound': 'Города не найдены',
  'browseTasks.filters.searchCategory': 'Поиск категорий...',
  'browseTasks.filters.noCategoriesFound': 'Категории не найдены',
  'browseTasks.filters.activeFilters': 'Активные фильтры',
  'browseTasks.filters.clearAll': 'Очистить все',
  'browseTasks.sort.newest': 'Сначала новые',
  'browseTasks.sort.urgent': 'Сначала срочные',
  'browseTasks.sort.budgetHigh': 'Самый высокий бюджет',
  'browseTasks.sort.budgetLow': 'Самый низкий бюджет',
  'browseTasks.sort.deadline': 'Скоро заканчиваются',
  'browseTasks.results.shown': 'Показано {{count}} результатов',
  'browseTasks.results.featured': 'Показано {{count}} популярных задач',
  'browseTasks.results.loading': 'Загрузка...',
  'browseTasks.results.noTasks.title': 'Задачи не найдены',
  'browseTasks.results.noTasks.description':
    'Попробуйте изменить фильтры или искать по другим критериям.',
  'browseTasks.results.noTasks.clearFilters': 'Очистить фильтры',
  'browseTasks.results.suggestedTasks':
    'Популярные задачи, которые могут вам понравиться',
  'browseTasks.results.suggestedDescription':
    'Вот некоторые популярные задачи из нашего сообщества',
  'browseTasks.results.featuredTasks': 'Рекомендуемые задачи',
  'browseTasks.results.featuredDescription':
    'Посмотрите эти популярные задачи из нашего сообщества',
  'browseTasks.results.error.title': 'Упс! Наши серверы ушли на кофе-брейк ☕',
  'browseTasks.results.error.description':
    'Похоже, хомяки перестали бегать в колесе. Не волнуйтесь, мы угощаем их эспрессо!',
  'browseTasks.results.error.subtext':
    'Обычно это исправляется быстрее, чем вы скажете "капучино"',
  'browseTasks.results.error.retry': 'Попробовать снова',
  'browseTasks.pagination.previous': 'Предыдущая',
  'browseTasks.pagination.next': 'Следующая',
  'browseTasks.search.tags.programming': 'Программирование',
  'browseTasks.search.tags.design': 'Дизайн',
  'browseTasks.search.tags.marketing': 'Маркетинг',
  'browseTasks.search.tags.translation': 'Переводы',
  'browseTasks.search.tags.photography': 'Фотография',
  'browseTasks.typing.plumber': 'сантехник в Софии',
  'browseTasks.typing.cleaner': 'уборка дома',
  'browseTasks.typing.electrician': 'ремонт электрики',
  'browseTasks.typing.tutor': 'учитель английского',
  'browseTasks.typing.moving': 'перевозка мебели',
  'browseTasks.typing.gardener': 'уход за садом',

  'task.budget': 'Бюджет',
  'task.location': 'Местоположение',
  'task.category': 'Категория',
  'task.applications': 'Заявки',
  'task.viewDetails': 'Посмотреть детали',
  'task.apply': 'Подать заявку',
  'task.created': 'Создана',
  'task.deadline': 'Срок',

  // Create Task Form
  'createTask.title': 'Создать новую задачу',
  'createTask.hero.subtitle': 'Опишите что вам нужно и позвольте профессионалам прийти к вам',
  'createTask.hero.freeToPost': 'Бесплатная публикация',
  'createTask.hero.noPayment': 'Без оплаты до начала работы',
  'createTask.hero.avgResponse': 'Среднее время ответа: 2 часа',
  'createTask.hero.verifiedPros': 'Проверенные специалисты',
  'createTask.hero.help': 'Нужна помощь? Свяжитесь с нашей командой поддержки',

  // Category Section
  'createTask.category.title': 'Какая услуга вам нужна?',
  'createTask.category.subtitle': 'Выберите категорию, которая лучше всего описывает вашу задачу',
  'createTask.category.selectSubcategory': 'Выберите конкретную услугу',
  'createTask.category.backToMain': 'Назад к основным категориям',
  'createTask.category.selected': 'Выбранная услуга',
  'createTask.category.categorySelected': 'Выбранная категория. Нажмите X, чтобы изменить.',
  'createTask.category.tryDifferent': 'Попробуйте другой поисковый запрос',

  // Details Section
  'createTask.details.title': 'Опишите вашу задачу',
  'createTask.details.subtitle': 'Чем больше деталей, тем лучше предложения вы получите',
  'createTask.details.titleLabel': 'Название задачи',
  'createTask.details.titlePlaceholder': 'напр. Нужен сантехник для устранения течи на кухне',
  'createTask.details.titleHelp': 'Будьте конкретны и ясны (например, "Профессиональная уборка дома для квартиры с 2 спальнями")',
  'createTask.details.descriptionLabel': 'Описание',
  'createTask.details.descriptionPlaceholder': 'Опишите что нужно сделать, когда и какие особые требования у вас есть...',
  'createTask.details.descriptionHelp': 'Включите все важные детали: что нужно сделать, особые требования, необходимые инструменты/материалы и т.д.',
  'createTask.details.requirementsLabel': 'Особые требования (по желанию)',
  'createTask.details.requirementsPlaceholder': '• Требование 1\n• Требование 2\n• Требование 3',
  'createTask.details.requirementsHelp': 'Перечислите особые навыки, сертификаты или оборудование (по одному в строке)',

  // Location Section
  'createTask.location.title': 'Где находится задача?',
  'createTask.location.subtitle': 'Это помогает найти профессионалов в вашем районе',
  'createTask.location.cityLabel': 'Город',
  'createTask.location.cityPlaceholder': 'Выберите город',
  'createTask.location.neighborhoodLabel': 'Район/Квартал',
  'createTask.location.neighborhoodPlaceholder': 'напр. Центр, Люлин, Студенческий городок',
  'createTask.location.neighborhoodHelp': 'Помогает специалистам определить, смогут ли они до вас добраться',
  'createTask.location.addressLabel': 'Точный адрес (по желанию)',
  'createTask.location.addressPlaceholder': 'Улица, номер дома, подъезд, этаж, квартира',
  'createTask.location.addressSecurity': 'Адрес будет показан только профессионалу, которого вы наймете',

  // Budget Section
  'createTask.budget.title': 'Какой ваш бюджет?',
  'createTask.budget.help': 'Честные бюджеты получают в 3 раза больше откликов',
  'createTask.budget.typeFixed': 'Фиксированная цена',
  'createTask.budget.typeRange': 'Диапазон цен',
  'createTask.budget.typeUnclear': 'Не уверен в бюджете',
  'createTask.budget.fixedLabel': 'Ваш бюджет',
  'createTask.budget.minLabel': 'Минимум',
  'createTask.budget.maxLabel': 'Максимум',
  'createTask.budget.notSure': 'Не уверен в бюджете',

  // Timeline Section
  'createTask.timeline.title': 'Когда вам это нужно?',
  'createTask.timeline.subtitle': 'Сообщите профессионалам о вашем графике',
  'createTask.timeline.urgentTitle': 'Срочно - В тот же день',
  'createTask.timeline.urgentDesc': 'Мне нужно сегодня',
  'createTask.timeline.soonTitle': 'Скоро - В течение недели',
  'createTask.timeline.soonDesc': 'Мне нужно в течение ближайших 7 дней',
  'createTask.timeline.flexibleTitle': 'Гибкий',
  'createTask.timeline.flexibleDesc': 'У меня гибкий график',
  'createTask.timeline.deadlineLabel': 'Конкретный срок (по желанию)',
  'createTask.timeline.deadlineHelp': 'Оставьте пустым, если у вас нет конкретного срока',
  'createTask.timeline.pastDateWarning': 'Этот срок в прошлом. Пожалуйста, выберите будущую дату или очистите поле.',

  // Photos Section
  'createTask.photos.title': 'Добавьте фотографию (по желанию)',
  'createTask.photos.help': 'Фотография помогает профессионалам лучше понять вашу задачу',
  'createTask.photos.dragDrop': 'Перетащите изображение сюда',
  'createTask.photos.orBrowse': 'или кликните для обзора',
  'createTask.photos.takePhoto': 'Сделать фото',
  'createTask.photos.maxSize': 'Максимум 5MB',
  'createTask.photos.formats': 'JPG, PNG, WebP',
  'createTask.photos.uploading': 'Загрузка фотографии...',
  'createTask.photos.fileTooLarge': 'Файл слишком большой. Максимальный размер 5MB',
  'createTask.photos.invalidType': 'Файл не является поддерживаемым форматом изображения',
  'createTask.photos.uploadError': 'Не удалось загрузить фотографии. Пожалуйста, попробуйте еще раз.',
  'createTask.photos.optimizing': 'Оптимизация изображения для более быстрой загрузки...',
  'createTask.photos.optimized': 'Изображение успешно оптимизировано',
  'createTask.photos.smaller': 'меньше',

  // Review Section
  'createTask.review.title': 'Проверьте вашу задачу',
  'createTask.review.subtitle': 'Убедитесь, что всё выглядит правильно перед публикацией',
  'createTask.review.submit': 'Опубликовать задачу',
  'createTask.review.location': 'Местоположение',
  'createTask.review.budget': 'Бюджет',
  'createTask.review.timeline': 'График',
  'createTask.review.requirements': 'Требования',
  'createTask.review.photos': 'Фотографии',
  'createTask.review.noTitle': 'Нет названия пока',
  'createTask.review.noDescription': 'Нет описания пока',
  'createTask.review.noCity': 'Город не выбран',
  'createTask.review.fillRequired': 'Пожалуйста, заполните все обязательные поля для публикации',

  // Errors
  'createTask.errors.categoryRequired': 'Пожалуйста, выберите категорию',
  'createTask.errors.titleTooShort': 'Название должно быть не менее 10 символов',
  'createTask.errors.titleTooLong': 'Название не может быть более 200 символов',
  'createTask.errors.descriptionTooShort': 'Описание должно быть не менее 15 символов',
  'createTask.errors.descriptionTooLong': 'Описание не может быть более 2000 символов',
  'createTask.errors.cityRequired': 'Пожалуйста, выберите город',
  'createTask.errors.budgetInvalid': 'Максимальный бюджет должен быть больше минимального',
  'createTask.errors.deadlineInPast': 'Срок должен быть сегодня или в будущем',

  // Validation Dialog
  'createTask.validationDialog.title': 'Пожалуйста, исправьте следующие проблемы',
  'createTask.validationDialog.subtitle': 'Некоторые поля требуют вашего внимания',
  'createTask.validationDialog.fixButton': 'Исправить эти проблемы',
  'createTask.validationDialog.fieldName.category': 'Категория',
  'createTask.validationDialog.fieldName.subcategory': 'Подкатегория',
  'createTask.validationDialog.fieldName.title': 'Название задачи',
  'createTask.validationDialog.fieldName.description': 'Описание',
  'createTask.validationDialog.fieldName.requirements': 'Требования',
  'createTask.validationDialog.fieldName.city': 'Город',
  'createTask.validationDialog.fieldName.neighborhood': 'Район',
  'createTask.validationDialog.fieldName.exactAddress': 'Точный адрес',
  'createTask.validationDialog.fieldName.budgetMin': 'Минимальный бюджет',
  'createTask.validationDialog.fieldName.budgetMax': 'Максимальный бюджет',
  'createTask.validationDialog.fieldName.urgency': 'Срочность',
  'createTask.validationDialog.fieldName.deadline': 'Крайний срок',

  'createTask.imageUpload.error': 'Не удалось загрузить изображение',

  // Success messages
  'createTask.success': 'Задача успешно создана!',
  'createTask.successMessage': 'Ваша задача опубликована и теперь видна профессионалам.',
  'createTask.successWithoutImage': 'Ваша задача опубликована без изображения. Вы можете добавить или изменить изображение, отредактировав задачу.',
  'createTask.error': 'Ошибка при создании задачи',
  'createTask.errorMessage': 'Пожалуйста, попробуйте позже.',

  'taskCard.apply': 'Откликнуться',
  'taskCard.seeDetails': 'Подробнее',
  'taskCard.anonymous': 'Анонимный',
  'taskCard.budget.from': 'от',
  'taskCard.budget.to': 'до',
  'taskCard.budget.negotiable': 'Договорная',
  'taskCard.budget.unclear': 'Бюджет не ясен',
  'taskCard.deadline.flexible': 'Гибкий',
  'taskCard.deadline.today': 'Сегодня',
  'taskCard.deadline.tomorrow': 'Завтра',
  'taskCard.deadline.days': 'дней',
  'taskCard.category.home_repair': 'Домашние ремонты',
  'taskCard.category.delivery_transport': 'Доставка и транспорт',
  'taskCard.category.personal_care': 'Личный уход',
  'taskCard.category.personal_assistant': 'Личный помощник',
  'taskCard.category.learning_fitness': 'Обучение и фитнес',
  'taskCard.category.other': 'Другое',
  // Subcategories
  'taskCard.category.courier-services': 'Курьерские услуги',
  'taskCard.category.logistics': 'Логистика',
  'taskCard.category.handyman': 'Мастер',
  'taskCard.category.plumbing': 'Водопровод',
  'taskCard.category.electrical': 'Электрика',
  'taskCard.category.cleaning-services': 'Уборка',
  'taskCard.category.house-cleaning': 'Уборка дома',
};
