// Application-related translations - submitting, managing, accepting, rejecting applications
export const applications = {
  // Application Status Labels (for badges/chips)
  'applicationStatus.pending': 'В очакване',
  'applicationStatus.accepted': 'Приета',
  'applicationStatus.rejected': 'Отхвърлена',
  'applicationStatus.withdrawn': 'Оттеглена',
  'applicationStatus.removedByCustomer': 'Премахната',

  // Application Dialog
  'application.title': 'Кандидатствайте за тази задача',
  'application.proposedPrice': 'Вашата цена',
  'application.pricePlaceholder': 'Въведете вашата цена в лева',
  'application.timeline': 'Кога можете да започнете?',
  'application.timelineToday': 'Днес',
  'application.timelineWeek': 'В рамките на седмица',
  'application.timelineFlexible': 'Гъвкав',
  'application.hoursShort': 'ч',
  'application.message': 'Защо сте най-подходящ?',
  'application.messagePlaceholder': 'Споделете вашия релевантен опит и защо сте перфектни за тази задача...',
  'application.messageInfo': 'Фокусирайте се върху уменията и опита си. Контактни данни можете да споделите след приемане на кандидатурата.',
  'application.characterCount': '{current}/{max} символа',
  'application.submit': 'Изпрати кандидатура',
  'application.submitting': 'Изпращане...',
  'application.cancel': 'Отказ',
  'application.success': 'Кандидатурата е изпратена!',
  'application.successMessage': 'Собственикът на задачата ще прегледа вашата кандидатура и скоро ще отговори.',
  'application.viewApplication': 'Моята кандидатура',
  'application.browseOther': 'Други задачи',
  'application.errors.priceRequired': 'Цената е задължителна',
  'application.errors.priceMin': 'Цената трябва да бъде по-голяма от 0',
  'application.errors.timelineRequired': 'Графикът е задължителен',
  'application.errors.messageRequired': 'Съобщението е задължително',
  'application.errors.messageMin': 'Съобщението трябва да бъде поне 30 символа',
  'application.errors.messageMax': 'Съобщението не може да надвишава 500 символа',
  'application.errors.noPhoneNumbers': 'Телефонни номера не са разрешени в кандидатури. Можете да обменяте контактна информация след приемане на кандидатурата.',
  'application.errors.noUrls': 'URL адреси и връзки не са разрешени в кандидатури. Можете да споделите портфолиото си след приемане на кандидатурата.',
  'application.errors.noEmails': 'Имейл адреси не са разрешени в кандидатури. Можете да обменяте контактна информация след приемане на кандидатурата.',
  'application.alreadyApplied': 'Вече сте кандидатствали за тази задача',
  'application.cannotApplyOwnTask': 'Не можете да кандидатствате за собствената си задача',
  'application.budget': 'Бюджет',
  'application.tipClientBudget': 'Подсказка: Бюджетът на клиента е {min} - {max} €',
  'application.tipShareExperience': 'Подсказка: Споделете вашия релевантен опит, за да се откроите',
  'application.successSteps.quickReview': 'Бърз преглед',
  'application.successSteps.getResponse': 'Получаване на отговор',
  'application.successSteps.startWork': 'Започнете работа',

  // Wizard Steps
  'application.wizard.step1Title': 'Вашата оферта',
  'application.wizard.step1Subtitle': 'Задайте цена',
  'application.wizard.step2Title': 'Наличност',
  'application.wizard.step2Subtitle': 'Кога можете?',
  'application.wizard.step3Title': 'Мотивационно писмо',
  'application.wizard.step3Subtitle': 'Представете се',
  'application.wizard.step4Title': 'Преглед',
  'application.wizard.step4Subtitle': 'Потвърдете кандидатурата',
  'application.wizard.budgetHint': 'Бюджет на клиента',
  'application.wizard.priceHelp': 'Въведете вашата предложена цена за изпълнение на задачата. Бъдете конкурентни, но справедливи.',
  'application.wizard.timelineHelp': 'Кога можете да започнете задачата? Изберете опцията, която най-добре отговаря на вашата наличност.',
  'application.wizard.timelineDescToday': 'Мога да започна веднага',
  'application.wizard.timelineDescWeek': 'Някъде тази седмица',
  'application.wizard.timelineDescFlexible': 'Можем да обсъдим времето',
  'application.wizard.messageTitle': 'Защо да напишете съобщение?',
  'application.wizard.reviewHelp': 'Моля, прегледайте кандидатурата си преди изпращане.',
  'application.wizard.applyingTo': 'Кандидатстване за',
  'application.wizard.noMessage': 'Няма добавено съобщение',
  'application.wizard.readyToSubmit': 'Готово за изпращане!',
  'application.wizard.submitNote': 'Щракнете Изпрати, за да изпратите кандидатурата. Клиентът ще бъде уведомен.',

  // Wizard Navigation
  'wizard.back': 'Назад',
  'wizard.next': 'Напред',
  'wizard.submit': 'Изпрати',

  // Applications Management
  'applications.title': 'Кандидатури',
  'applications.apply.title': 'Кандидатствай за задача',
  'applications.count': 'кандидатури',
  'applications.sortBy': 'Сортирай по',
  'applications.sortNewest': 'Най-нови първо',
  'applications.sortPriceLow': 'Цена: Ниска към висока',
  'applications.sortPriceHigh': 'Цена: Висока към ниска',
  'applications.sortRating': 'Най-високо оценени',
  'applications.sortExperience': 'Най-опитни',
  'applications.filterAll': 'Всички',
  'applications.filterPending': 'В очакване',
  'applications.filterAccepted': 'Приети',
  'applications.filterRejected': 'Отхвърлени',
  'applications.emptyState.title': 'Все още няма кандидатури',
  'applications.emptyState.message': 'Вашата задача е публикувана! Специалистите скоро ще започнат да кандидатстват.',
  'applications.proposedPrice': 'Предложена цена',
  'applications.timeline': 'Срокове',
  'applications.readyToStart': 'Готов да започне',
  'applications.message': 'Съобщение',
  'applications.portfolio': 'Портфолио',
  'applications.portfolioImages': 'примера от портфолио',
  'applications.tasksCompleted': 'завършени задачи',
  'applications.yearsExperience': 'години опит',
  'applications.viewDetails': 'Детайли',
  'applications.viewProfile': 'Виж профил',
  'applications.freshProfessional': 'Нов в платформата - помогнете му да изгради репутация!',
  'applications.new': 'Нов',
  'applications.acceptApplication': 'Приеми',
  'applications.rejectApplication': 'Отхвърли',
  'applications.status': 'Статус',
  'applications.statusPending': 'В очакване',
  'applications.statusAccepted': 'Приета',
  'applications.statusRejected': 'Отхвърлена',
  'applications.statusWithdrawn': 'Оттеглена',

  // Application Detail Modal
  'applicationDetail.title': 'Детайли за кандидатурата',
  'applicationDetail.professionalProfile': 'Професионален профил',
  'applicationDetail.applicationMessage': 'Съобщение за кандидатурата',
  'applicationDetail.portfolioGallery': 'Портфолио',
  'applicationDetail.recentReviews': 'Последни отзиви',
  'applicationDetail.close': 'Затвори',

  // Accept Application Dialog
  'acceptApplication.title': 'Приемане на кандидатурата',
  'acceptApplication.description': 'На път сте да приемете кандидатурата от {name}. Моля, прегледайте детайлите и потвърдете съгласието си.',
  'acceptApplication.agreedPrice': 'Договорена цена',
  'acceptApplication.timeline': 'Срокове',
  'acceptApplication.messageLabel': 'Съобщение до специалиста (по избор)',
  'acceptApplication.messagePlaceholder': 'Поздравете, споделете наличност за обаждане или добавете допълнителни детайли...',
  'acceptApplication.messageHelp': 'Това съобщение ще бъде изпратено до {name} заедно с вашата контактна информация.',
  'acceptApplication.contactInfo': 'Как да се свърже с вас специалистът?',
  'acceptApplication.noInAppChat': 'Нямаме чат в приложението. Моля, изберете начин за контакт, за да може специалистът да се свърже с вас.',
  'acceptApplication.sharePhone': 'Сподели телефонния ми номер',
  'acceptApplication.shareEmail': 'Сподели имейл адреса ми',
  'acceptApplication.customContact': 'Предостави друга информация за контакт',
  'acceptApplication.customContactLabel': 'Информация за контакт',
  'acceptApplication.customContactPlaceholder': 'Въведете телефон, Telegram (@потребител), Viber линк, WhatsApp или друг начин за връзка...',
  'acceptApplication.customContactHelp': 'Предоставете начин за връзка, по който специалистът може да се свърже с вас',
  'acceptApplication.customContactRequired': 'Моля, предоставете информация за контакт',
  'acceptApplication.noSavedContacts': 'Моля, предоставете начин за връзка, по който специалистът може да се свърже с вас.',
  'acceptApplication.phoneWarning': 'Този телефонен номер ще бъде споделен със специалиста.',
  'acceptApplication.emailWarning': 'Имейлът е по-бавен за координация. Помислете дали да предоставите телефон/Telegram за по-бърза комуникация.',
  'acceptApplication.privacyPolicy': 'Политика за поверителност',
  'acceptApplication.pleaseConfirm': 'Моля, потвърдете:',
  'acceptApplication.agreement.priceTimeline': 'Съгласен съм с предложената цена ({price} {currency}) и срокове ({timeline})',
  'acceptApplication.agreement.contactSharing': 'Разбирам, че моята контактна информация ще бъде споделена с {name}',
  'acceptApplication.agreement.otherApplications': 'Разбирам, че всички други чакащи кандидатури ще бъдат автоматично отхвърлени',
  'acceptApplication.warning': 'След като приемете тази кандидатура, ще се ангажирате да работите с {name}. Всички други кандидатури ще бъдат отхвърлени автоматично.',
  'acceptApplication.confirm': 'Приеми кандидатурата',
  'acceptApplication.cancel': 'Отказ',
  'acceptApplication.accepting': 'Приемане...',

  // Accept Application Wizard Steps
  'acceptApplication.wizard.reviewTitle': 'Преглед на офертата',
  'acceptApplication.wizard.reviewSubtitle': 'Предложение на специалиста',
  'acceptApplication.wizard.reviewHelp': 'Прегледайте офертата на специалиста преди да продължите.',
  'acceptApplication.wizard.professional': 'Специалист',
  'acceptApplication.wizard.proposedPrice': 'Предложена цена',
  'acceptApplication.wizard.timeline': 'Срокове',
  'acceptApplication.wizard.professionalMessage': 'Съобщение от специалиста',

  'acceptApplication.wizard.contactTitle': 'Споделяне на контакт',
  'acceptApplication.wizard.contactSubtitle': 'Как да се свържат с вас',
  'acceptApplication.wizard.contactHelp': 'Изберете как специалистът може да се свърже с вас.',

  'acceptApplication.wizard.messageTitle': 'Добавяне на съобщение',
  'acceptApplication.wizard.messageSubtitle': 'По избор',
  'acceptApplication.wizard.messageHelp': 'Добавете лично съобщение за {name} (по избор).',
  'acceptApplication.wizard.messageTipTitle': 'Бързи съвети',
  'acceptApplication.wizard.messageTip1': '• Споменете кога сте свободни',
  'acceptApplication.wizard.messageTip2': '• Задайте последни въпроси',
  'acceptApplication.wizard.messageTip3': '• Споделете важни детайли за задачата',

  'acceptApplication.wizard.confirmTitle': 'Потвърждение',
  'acceptApplication.wizard.confirmSubtitle': 'Финален преглед',
  'acceptApplication.wizard.confirmHelp': 'Прегледайте детайлите за приемане преди да потвърдите.',
  'acceptApplication.wizard.sharingContact': 'Споделяне със специалиста',
  'acceptApplication.wizard.yourMessage': 'Вашето съобщение',
  'acceptApplication.wizard.noMessage': 'Няма добавено съобщение',
  'acceptApplication.wizard.readyToAccept': 'Готово за приемане!',
  'acceptApplication.wizard.acceptNote': 'Натиснете Приеми за потвърждение. {name} ще бъде уведомен.',
  'acceptApplication.wizard.agreementRequired': 'Изисква се съгласие',
  'acceptApplication.wizard.pleaseAgree': 'Моля, поставете отметка по-горе за да продължите.',

  // Reject Application Dialog
  'rejectApplication.title': 'Отхвърляне на заявка',
  'rejectApplication.description': 'Отхвърляте заявката от {name}?',
  'rejectApplication.reasonTitle': 'Причина (по избор)',
  'rejectApplication.reasonHelp': 'Посочването на причина помага на специалистите да подобрят бъдещите си кандидатури.',
  'rejectApplication.reasons.betterFit': 'Избрах друг кандидат',
  'rejectApplication.reasons.priceHigh': 'Цената е висока',
  'rejectApplication.reasons.timelineIssue': 'Графикът не ми подхожда',
  'rejectApplication.reasons.changedMind': 'Промених решението си',
  'rejectApplication.reasons.other': 'Друга причина',
  'rejectApplication.note': 'Можете да приемете друга заявка.',
  'rejectApplication.confirm': 'Отхвърли',
  'rejectApplication.cancel': 'Отказ',

  // Professional Applications Dashboard
  'myApplications.title': 'Моите кандидатури',
  'myApplications.count': '{count} кандидатури',
  'myApplications.sortBy': 'Сортирай по',
  'myApplications.sortNewest': 'Най-нови първо',
  'myApplications.sortOldest': 'Най-стари първо',
  'myApplications.sortStatus': 'По статус',
  'myApplications.sortTaskDate': 'Дата на задачата',
  'myApplications.sortPriceHigh': 'Цена: Висока към ниска',
  'myApplications.sortPriceLow': 'Цена: Ниска към висока',
  'myApplications.filterAll': 'Всички',
  'myApplications.filterPending': 'В очакване',
  'myApplications.filterAccepted': 'Приети',
  'myApplications.filterRejected': 'Отхвърлени',
  'myApplications.filterWithdrawn': 'Оттеглени',
  'myApplications.status.pending': 'В очакване',
  'myApplications.status.accepted': 'Приета',
  'myApplications.status.rejected': 'Отхвърлена',
  'myApplications.status.withdrawn': 'Оттеглена',
  'myApplications.appliedAgo': 'Кандидатствал {time}',
  'myApplications.acceptedAgo': 'Приета {time}',
  'myApplications.rejectedAgo': 'Отхвърлена {time}',
  'myApplications.yourQuote': 'Вашата оферта',
  'myApplications.taskBudget': 'Бюджет на задачата',
  'myApplications.timeline': 'Срокове',
  'myApplications.agreedPrice': 'Договорена цена',
  'myApplications.startDate': 'Започва',
  'myApplications.viewDetails': 'Детайли',
  'myApplications.viewTask': 'Към задачата',
  'myApplications.withdraw': 'Оттегли',
  'myApplications.withdrawConfirm': 'Сигурни ли сте, че искате да оттеглите тази кандидатура?',
  'myApplications.withdrawError': 'Неуспешно оттегляне на кандидатурата',
  'myApplications.messageCustomer': 'Съобщение до клиента',
  'myApplications.markStarted': 'Маркирай като започнато',
  'myApplications.markCompleted': 'Завърши',
  'myApplications.reportIssue': 'Докладвай проблем',
  'myApplications.findSimilar': 'Намери подобни',
  'myApplications.delete': 'Изтрий',
  'myApplications.emptyState.title': 'Все още не сте кандидатствали за задачи',
  'myApplications.emptyState.message': 'Започнете да разглеждате налични задачи и кандидатствайте за тези, които отговарят на вашите умения.',
  'myApplications.emptyState.browse': 'Разглеждане на задачи',
  'myApplications.emptyStatePending.title': 'Всички задачи са разгледани!',
  'myApplications.emptyStatePending.message': 'Нямате чакащи кандидатури. Всички ваши кандидатури са прегледани.',
  'myApplications.emptyStateAccepted.title': 'Все още нямате приети кандидатури',
  'myApplications.emptyStateAccepted.message': 'Продължавайте да кандидатствате! Следващата ви възможност е зад ъгъла.',
  'myApplications.emptyStateRejected.title': 'Няма отхвърлени кандидатури',
  'myApplications.emptyStateRejected.message': 'Страхотна новина! Нито една от вашите кандидатури не е била отхвърлена.',
  'myApplications.emptyStateWithdrawn.title': 'Няма оттеглени кандидатури',
  'myApplications.emptyStateWithdrawn.message': 'Все още не сте оттегляли нито една кандидатура.',
  'myApplications.withdrawDialog.title': 'Оттегляне на кандидатурата?',
  'myApplications.withdrawDialog.description': 'Сигурни ли сте, че искате да оттеглите кандидатурата си за "{taskTitle}"?',
  'myApplications.withdrawDialog.reason': 'Причина (по избор)',
  'myApplications.withdrawDialog.selectReason': 'Изберете причина (по избор)',
  'myApplications.withdrawDialog.reasonUnavailable': 'Вече не съм наличен',
  'myApplications.withdrawDialog.reasonFoundWork': 'Намерих друга работа',
  'myApplications.withdrawDialog.reasonChanged': 'Изискванията на задачата се промениха',
  'myApplications.withdrawDialog.reasonPrice': 'Цената е твърде ниска',
  'myApplications.withdrawDialog.reasonOther': 'Друго',
  'myApplications.withdrawDialog.warning': 'След оттегляне не можете отново да кандидатствате за тази задача.',
  'myApplications.withdrawDialog.confirm': 'Потвърди оттеглянето',
  'myApplications.withdrawDialog.cancel': 'Отказ',
  'myApplications.detail.taskDetails': 'Детайли на задачата',
  'myApplications.detail.yourProposal': 'Вашето предложение',
  'myApplications.detail.agreedTerms': 'Договорени условия',
  'myApplications.detail.rejectionReason': 'Причина за отхвърляне',
  'myApplications.detail.waitingResponse': 'Изчакване на отговор от клиента',
  'myApplications.detail.usuallyResponds': 'Обикновено отговаря в рамките на 24 часа',
  'myApplications.detail.otherApplicants': '{count} други специалисти кандидатстваха',
  'myApplications.detail.nextSteps': 'Следващи стъпки',
  'myApplications.detail.customerApproved': 'Клиентът одобри вашата кандидатура',
  'myApplications.detail.contactCustomer': 'Свържете се с клиента за потвърждаване на детайлите',
  'myApplications.detail.completeBy': 'Завършете задачата до {date}',
  'myApplications.detail.feedback': 'Не го приемайте лично! Продължавайте да кандидатствате за подобни задачи.',

  // My Applications Page (Professional View)
  'myApplications.subtitle': 'Кандидатури, които сте подали за задачи',
  'myApplications.browseButton': 'Разгледай задачи',
  'myApplications.filter.all': 'Всички',
  'myApplications.filter.pending': 'Чакащи',
  'myApplications.filter.accepted': 'Приети',
  'myApplications.filter.rejected': 'Отхвърлени',
  'myApplications.filter.withdrawn': 'Оттеглени',
  'myApplications.yourProposal': 'Вашето предложение',
  'myApplications.proposedPrice': '{price} €',
  'myApplications.submitted': 'Подадена',
  'myApplications.empty.title': 'Все още няма кандидатури',
  'myApplications.empty.message': 'Все още не сте кандидатствали за задачи. Разгледайте наличните задачи!',
  'myApplications.empty.browseButton': 'Разгледай задачи',

  // My Work Page (Professional View - Accepted Applications Only)
  'myWork.title': 'Моята работа',
  'myWork.subtitle': 'Управлявайте активните и завършени задачи',
  'myWork.loading': 'Зареждане на вашата работа...',
  'myWork.filter.inProgress': 'В процес',
  'myWork.filter.pendingCompletion': 'Чака завършване',
  'myWork.filter.completed': 'Завършени',
  'myWork.empty.inProgress.title': 'Няма активни задачи',
  'myWork.empty.inProgress.message': 'Нямате задачи в процес. Разгледайте налични задачи за да започнете!',
  'myWork.empty.inProgress.browseButton': 'Разгледай задачи',
  'myWork.empty.pendingCompletion.title': 'Няма чакащи потвърждения',
  'myWork.empty.pendingCompletion.message': 'Всички ваши задачи са актуални!',
  'myWork.empty.completed.title': 'Все още няма завършена работа',
  'myWork.empty.completed.message': 'Завършените задачи ще се появят тук.',
  'myWork.customerContact': 'Контакт с клиента',
  'myWork.customerMessage': 'Съобщение от клиента',
  'myWork.taskDeadline': 'Краен срок',
  'myWork.startedDaysAgo': 'Започната преди {days} дни',
  'myWork.completedOn': 'Завършена на {date}',
  'myWork.confirmCompletion': 'Потвърди завършване',
  'myWork.viewReview': 'Виж ревюто',
  'myWork.withdrawFromTask': 'Оттегли се',
  'myWork.leaveReview': 'Остави ревю',
  'myWork.auth.title': 'Влезте, за да видите работата си',
  'myWork.auth.description': 'Тази страница показва активните ви задачи и завършената работа като професионалист. Влезте, за да управлявате задачите си и да следите напредъка.',
  'myWork.auth.hint': 'Вие сте професионалист? Влезте, за да видите задачите, за които сте наети.',

  // Professional Withdrawal from Accepted Task
  'professionalWithdraw.title': 'Оттегляне от задача',
  'professionalWithdraw.subtitle': 'Оттегляте се от: {taskTitle}',
  'professionalWithdraw.customer': 'Клиент',
  'professionalWithdraw.customerNotification': 'Клиентът ще бъде уведомен незабавно и задачата ще бъде отворена отново',

  // Rate limiting
  'professionalWithdraw.rateLimit.title': 'Можете да се оттеглите още {remaining} път(и) този месец',
  'professionalWithdraw.rateLimit.message': 'Професионалистите могат да се оттеглят от до 2 задачи месечно',
  'professionalWithdraw.rateLimit.warning': 'Честите оттегляния могат да повлияят на вашия професионален рейтинг и статус на акаунта',
  'professionalWithdraw.limitExceeded.title': 'Достигнат месечен лимит за оттегляния',
  'professionalWithdraw.limitExceeded.message': 'Достигнали сте лимита си за оттегляния за този месец. Моля, свържете се с поддръжката, ако имате спешна ситуация.',

  // Timing warnings
  'professionalWithdraw.earlyWithdrawal.title': 'Ранно оттегляне - без санкция',
  'professionalWithdraw.earlyWithdrawal.message': 'Тъй като приехте преди по-малко от 2 часа, това няма да се брои към месечния ви лимит',
  'professionalWithdraw.lateWithdrawal.title': 'Забавено оттегляне',
  'professionalWithdraw.lateWithdrawal.message': 'Оттеглянето повече от 24 часа след приемане значително засяга клиента и ще повлияе на вашия професионален рейтинг',

  // Reasons
  'professionalWithdraw.reasonLabel': 'Защо се оттегляте?',
  'professionalWithdraw.reasons.health_emergency': 'Здравословен проблем или спешност',
  'professionalWithdraw.reasons.capacity_issue': 'Претоварен съм или подценил времето',
  'professionalWithdraw.reasons.scope_mismatch': 'Задачата е различна от очакваното',
  'professionalWithdraw.reasons.customer_unresponsive': 'Клиентът не отговаря на съобщенията',
  'professionalWithdraw.reasons.location_issue': 'Не мога да достигна локацията или има опасност',
  'professionalWithdraw.reasons.budget_dispute': 'Клиентът иска да преговаря договорената цена',
  'professionalWithdraw.reasons.equipment_issue': 'Нямам необходимите инструменти или материали',
  'professionalWithdraw.reasons.other': 'Друга причина',

  // Form
  'professionalWithdraw.descriptionLabel': 'Допълнителни детайли',
  'professionalWithdraw.descriptionPlaceholder': 'Моля, обяснете ситуацията...',
  'professionalWithdraw.descriptionHint': 'Това ни помага да подобрим платформата',
  'professionalWithdraw.confirmButton': 'Оттегли се от задачата',
  'professionalWithdraw.reputationWarning': 'Това оттегляне ще бъде записано и може да повлияе на вашия професионален рейтинг',

  // Success/error
  'professionalWithdraw.successTitle': 'Успешно оттегляне',
  'professionalWithdraw.success': 'Оттеглихте се от задачата. Клиентът е уведомен.',
  'professionalWithdraw.errorTitle': 'Грешка при оттегляне',
  'professionalWithdraw.error': 'Не може да се оттеглите. Моля, опитайте отново или се свържете с поддръжката.',

  // Task Detail Page - Professional View
  'taskDetail.professional.withdraw': 'Оттегли се от задачата',
  'taskDetail.professional.markCompleted': 'Маркирай като завършена',

  // Accept Application Success Toast
  'acceptApplication.successTitle': '🎉 Заявката е приета!',
  'acceptApplication.successDescription': 'Вече работите с {name}. Всички останали заявки са автоматично отхвърлени.',

  // Task In Progress State
  'taskInProgress.title': 'Задачата е в ход!',
  'taskInProgress.description': 'Приехте заявка. Задачата ви вече се изпълнява от професионалист.',
  'taskInProgress.workingWith': 'Работите с',
  'taskInProgress.specialization': 'Специализация',
  'taskInProgress.location': 'Местоположение',
  'taskInProgress.agreedPrice': 'Договорена цена',
  'taskInProgress.infoMessage': 'Всички останали заявки са автоматично отхвърлени. Можете да следите напредъка на задачата си и да комуникирате с професионалиста през страницата за управление на задачи.',
  'taskInProgress.viewMyTasks': 'Виж моите задачи',
  'taskInProgress.viewNotifications': 'Виж известия',
};
