// Application-related translations - submitting, managing, accepting, rejecting applications
export const applications = {
  // Application Dialog
  'application.title': 'Кандидатствайте за тази задача',
  'application.proposedPrice': 'Вашата цена',
  'application.pricePlaceholder': 'Въведете вашата цена в лева',
  'application.timeline': 'Кога можете да започнете?',
  'application.timelineToday': 'Днес',
  'application.timeline3days': 'В рамките на 3 дни',
  'application.timelineWeek': 'В рамките на седмица',
  'application.timelineFlexible': 'Гъвкав',
  'application.message': 'Защо сте най-подходящ?',
  'application.messagePlaceholder': 'Споделете вашия релевантен опит и защо сте перфектни за тази задача...',
  'application.messageInfo': 'Фокусирайте се върху уменията и опита си. Контактни данни можете да споделите след приемане на кандидатурата.',
  'application.characterCount': '{{current}}/{{max}} символа',
  'application.submit': 'Изпрати кандидатура',
  'application.submitting': 'Изпращане...',
  'application.cancel': 'Отказ',
  'application.success': 'Кандидатурата е изпратена!',
  'application.successMessage': 'Собственикът на задачата ще прегледа вашата кандидатура и скоро ще отговори.',
  'application.viewApplication': 'Вижте моята кандидатура',
  'application.browseOther': 'Разгледайте други задачи',
  'application.errors.priceRequired': 'Цената е задължителна',
  'application.errors.priceMin': 'Цената трябва да бъде по-голяма от 0',
  'application.errors.timelineRequired': 'Графикът е задължителен',
  'application.errors.messageRequired': 'Съобщението е задължително',
  'application.errors.messageMin': 'Съобщението трябва да бъде поне 30 символа',
  'application.errors.messageMax': 'Съобщението не може да надвишава 500 символа',
  'application.errors.noPhoneNumbers': 'Телефонни номера не са разрешени в кандидатури. Можете да обменяте контактна информация след приемане на кандидатурата.',
  'application.errors.noUrls': 'URL адреси и връзки не са разрешени в кандидатури. Можете да споделите портфолиото си след приемане на кандидатурата.',
  'application.errors.noEmails': 'Имейл адреси не са разрешени в кандидатури. Можете да обменяте контактна информация след приемане на кандидатурата.',
  'application.alreadyApplied': 'Вече сте кандидатствали за тази задача',
  'application.cannotApplyOwnTask': 'Не можете да кандидатствате за собствената си задача',
  'application.budget': 'Бюджет',
  'application.tipClientBudget': 'Подсказка: Бюджетът на клиента е {{min}} - {{max}} лв',
  'application.tipShareExperience': 'Подсказка: Споделете вашия релевантен опит, за да се откроите',
  'application.successSteps.quickReview': 'Бърз преглед',
  'application.successSteps.getResponse': 'Получаване на отговор',
  'application.successSteps.startWork': 'Започнете работа',

  // Applications Management
  'applications.title': 'Кандидатури',
  'applications.count': 'кандидатури',
  'applications.sortBy': 'Сортирай по',
  'applications.sortNewest': 'Най-нови първо',
  'applications.sortPriceLow': 'Цена: Ниска към висока',
  'applications.sortPriceHigh': 'Цена: Висока към ниска',
  'applications.sortRating': 'Най-високо оценени',
  'applications.sortExperience': 'Най-опитни',
  'applications.filterAll': 'Всички',
  'applications.filterPending': 'В очакване',
  'applications.filterAccepted': 'Приети',
  'applications.filterRejected': 'Отхвърлени',
  'applications.emptyState.title': 'Все още няма кандидатури',
  'applications.emptyState.message': 'Вашата задача е публикувана! Специалистите скоро ще започнат да кандидатстват.',
  'applications.proposedPrice': 'Предложена цена',
  'applications.timeline': 'Срокове',
  'applications.message': 'Съобщение',
  'applications.portfolio': 'Портфолио',
  'applications.portfolioImages': 'примера от портфолио',
  'applications.tasksCompleted': 'завършени задачи',
  'applications.yearsExperience': 'години опит',
  'applications.viewDetails': 'Виж детайли',
  'applications.acceptApplication': 'Приеми',
  'applications.rejectApplication': 'Отхвърли',
  'applications.status': 'Статус',
  'applications.statusPending': 'В очакване',
  'applications.statusAccepted': 'Приета',
  'applications.statusRejected': 'Отхвърлена',

  // Application Detail Modal
  'applicationDetail.title': 'Детайли за кандидатурата',
  'applicationDetail.professionalProfile': 'Професионален профил',
  'applicationDetail.applicationMessage': 'Съобщение за кандидатурата',
  'applicationDetail.portfolioGallery': 'Портфолио',
  'applicationDetail.recentReviews': 'Последни отзиви',
  'applicationDetail.close': 'Затвори',

  // Accept Application Dialog
  'acceptApplication.title': 'Приемане на кандидатурата',
  'acceptApplication.description': 'На път сте да приемете кандидатурата от {{name}}. Моля, прегледайте детайлите и потвърдете съгласието си.',
  'acceptApplication.agreedPrice': 'Договорена цена',
  'acceptApplication.timeline': 'Срокове',
  'acceptApplication.messageLabel': 'Съобщение до специалиста (по избор)',
  'acceptApplication.messagePlaceholder': 'Поздравете, споделете наличност за обаждане или добавете допълнителни детайли...',
  'acceptApplication.messageHelp': 'Това съобщение ще бъде изпратено до {{name}} заедно с вашата контактна информация.',
  'acceptApplication.pleaseConfirm': 'Моля, потвърдете:',
  'acceptApplication.agreement.priceTimeline': 'Съгласен съм с предложената цена ({{price}} {{currency}}) и срокове ({{timeline}})',
  'acceptApplication.agreement.contactSharing': 'Разбирам, че моята контактна информация ще бъде споделена с {{name}}',
  'acceptApplication.agreement.otherApplications': 'Разбирам, че всички други чакащи кандидатури ще бъдат автоматично отхвърлени',
  'acceptApplication.warning': 'След като приемете тази кандидатура, ще се ангажирате да работите с {{name}}. Всички други кандидатури ще бъдат отхвърлени автоматично.',
  'acceptApplication.confirm': 'Приеми кандидатурата',
  'acceptApplication.cancel': 'Отказ',

  // Reject Application Dialog
  'rejectApplication.title': 'Отхвърляне на кандидатурата',
  'rejectApplication.description': 'На път сте да отхвърлите кандидатурата от {{name}}. Това действие ще уведоми специалиста, че няма да продължите с неговата кандидатура.',
  'rejectApplication.reasonTitle': 'Причина за отхвърляне (по избор)',
  'rejectApplication.reasonHelp': 'Посочването на причина помага на специалистите да подобрят бъдещите си кандидатури.',
  'rejectApplication.reasons.betterFit': 'Намерих по-подходящ кандидат за тази задача',
  'rejectApplication.reasons.priceHigh': 'Цената е твърде висока',
  'rejectApplication.reasons.timelineIssue': 'Графикът не ми подхожда',
  'rejectApplication.reasons.changedMind': 'Промених решението си относно задачата',
  'rejectApplication.reasons.other': 'Друга причина',
  'rejectApplication.note': '{{name}} ще бъде уведомен, че неговата кандидатура не е избрана. Все още можете да разглеждате други кандидатури и да приемете друг специалист.',
  'rejectApplication.confirm': 'Отхвърли кандидатурата',
  'rejectApplication.cancel': 'Отказ',

  // Professional Applications Dashboard
  'myApplications.title': 'Моите кандидатури',
  'myApplications.count': '{{count}} кандидатури',
  'myApplications.sortBy': 'Сортирай по',
  'myApplications.sortNewest': 'Най-нови първо',
  'myApplications.sortOldest': 'Най-стари първо',
  'myApplications.sortStatus': 'По статус',
  'myApplications.sortTaskDate': 'Дата на задачата',
  'myApplications.sortPriceHigh': 'Цена: Висока към ниска',
  'myApplications.sortPriceLow': 'Цена: Ниска към висока',
  'myApplications.filterAll': 'Всички',
  'myApplications.filterPending': 'В очакване',
  'myApplications.filterAccepted': 'Приети',
  'myApplications.filterRejected': 'Отхвърлени',
  'myApplications.filterWithdrawn': 'Оттеглени',
  'myApplications.status.pending': 'В очакване',
  'myApplications.status.accepted': 'Приета',
  'myApplications.status.rejected': 'Отхвърлена',
  'myApplications.status.withdrawn': 'Оттеглена',
  'myApplications.appliedAgo': 'Кандидатствал {{time}}',
  'myApplications.acceptedAgo': 'Приета {{time}}',
  'myApplications.rejectedAgo': 'Отхвърлена {{time}}',
  'myApplications.yourQuote': 'Вашата оферта',
  'myApplications.taskBudget': 'Бюджет на задачата',
  'myApplications.timeline': 'Срокове',
  'myApplications.agreedPrice': 'Договорена цена',
  'myApplications.startDate': 'Започва',
  'myApplications.viewDetails': 'Виж детайли',
  'myApplications.viewTask': 'Виж задачата',
  'myApplications.withdraw': 'Оттегли',
  'myApplications.messageCustomer': 'Съобщение до клиента',
  'myApplications.markStarted': 'Маркирай като започнато',
  'myApplications.markCompleted': 'Маркирай като завършено',
  'myApplications.reportIssue': 'Докладвай проблем',
  'myApplications.findSimilar': 'Намери подобни',
  'myApplications.delete': 'Изтрий',
  'myApplications.emptyState.title': 'Все още не сте кандидатствали за задачи',
  'myApplications.emptyState.message': 'Започнете да разглеждате налични задачи и кандидатствайте за тези, които отговарят на вашите умения.',
  'myApplications.emptyState.browse': 'Разглеждане на задачи',
  'myApplications.emptyStatePending.title': 'Всички задачи са разгледани!',
  'myApplications.emptyStatePending.message': 'Нямате чакащи кандидатури. Всички ваши кандидатури са прегледани.',
  'myApplications.emptyStateAccepted.title': 'Все още нямате приети кандидатури',
  'myApplications.emptyStateAccepted.message': 'Продължавайте да кандидатствате! Следващата ви възможност е зад ъгъла.',
  'myApplications.emptyStateRejected.title': 'Няма отхвърлени кандидатури',
  'myApplications.emptyStateRejected.message': 'Страхотна новина! Нито една от вашите кандидатури не е била отхвърлена.',
  'myApplications.emptyStateWithdrawn.title': 'Няма оттеглени кандидатури',
  'myApplications.emptyStateWithdrawn.message': 'Все още не сте оттегляли нито една кандидатура.',
  'myApplications.withdrawDialog.title': 'Оттегляне на кандидатурата?',
  'myApplications.withdrawDialog.reason': 'Причина (по избор)',
  'myApplications.withdrawDialog.reasonUnavailable': 'Вече не съм наличен',
  'myApplications.withdrawDialog.reasonFoundWork': 'Намерих друга работа',
  'myApplications.withdrawDialog.reasonChanged': 'Изискванията на задачата се промениха',
  'myApplications.withdrawDialog.reasonPrice': 'Цената е твърде ниска',
  'myApplications.withdrawDialog.reasonOther': 'Друго',
  'myApplications.withdrawDialog.confirm': 'Потвърди оттеглянето',
  'myApplications.withdrawDialog.cancel': 'Отказ',
  'myApplications.detail.taskDetails': 'Детайли на задачата',
  'myApplications.detail.yourProposal': 'Вашето предложение',
  'myApplications.detail.agreedTerms': 'Договорени условия',
  'myApplications.detail.rejectionReason': 'Причина за отхвърляне',
  'myApplications.detail.waitingResponse': 'Изчакване на отговор от клиента',
  'myApplications.detail.usuallyResponds': 'Обикновено отговаря в рамките на 24 часа',
  'myApplications.detail.otherApplicants': '{{count}} други специалисти кандидатстваха',
  'myApplications.detail.nextSteps': 'Следващи стъпки',
  'myApplications.detail.customerApproved': 'Клиентът одобри вашата кандидатура',
  'myApplications.detail.contactCustomer': 'Свържете се с клиента за потвърждаване на детайлите',
  'myApplications.detail.completeBy': 'Завършете задачата до {{date}}',
  'myApplications.detail.feedback': 'Не го приемайте лично! Продължавайте да кандидатствате за подобни задачи.',

  // My Applications Page (Professional View)
  'myApplications.subtitle': 'Кандидатури, които сте подали за задачи',
  'myApplications.browseButton': 'Разгледай задачи',
  'myApplications.filter.all': 'Всички',
  'myApplications.filter.pending': 'Чакащи',
  'myApplications.filter.accepted': 'Приети',
  'myApplications.filter.rejected': 'Отхвърлени',
  'myApplications.filter.withdrawn': 'Оттеглени',
  'myApplications.yourProposal': 'Вашето предложение',
  'myApplications.proposedPrice': '{{price}} лв',
  'myApplications.submitted': 'Подадена',
  'myApplications.empty.title': 'Все още няма кандидатури',
  'myApplications.empty.message': 'Все още не сте кандидатствали за задачи. Разгледайте наличните задачи!',
  'myApplications.empty.browseButton': 'Разгледай задачи',

  // Mock Timeline Examples (for development)
  'myApplications.mockTimeline.thisWeekend': 'Този уикенд (21-22 окт)',
  'myApplications.mockTimeline.nextWeek': 'Следваща седмица, гъвкав график',
  'myApplications.mockTimeline.startMonday': 'Започвам следващия понеделник, Пон-Пет 7-8ч',

  // My Work Page (Professional View - Accepted Applications Only)
  'myWork.title': 'Моята работа',
  'myWork.subtitle': 'Управлявайте активните и завършени задачи',
  'myWork.filter.inProgress': 'В процес',
  'myWork.filter.pendingCompletion': 'Чака завършване',
  'myWork.filter.completed': 'Завършени',
  'myWork.empty.inProgress.title': 'Няма активни задачи',
  'myWork.empty.inProgress.message': 'Нямате задачи в процес. Разгледайте налични задачи за да започнете!',
  'myWork.empty.inProgress.browseButton': 'Разгледай задачи',
  'myWork.empty.pendingCompletion.title': 'Няма чакащи потвърждения',
  'myWork.empty.pendingCompletion.message': 'Всички ваши задачи са актуални!',
  'myWork.empty.completed.title': 'Все още няма завършена работа',
  'myWork.empty.completed.message': 'Завършените задачи ще се появят тук.',
  'myWork.customerContact': 'Контакт с клиента',
  'myWork.taskDeadline': 'Краен срок',
  'myWork.startedDaysAgo': 'Започната преди {{days}} дни',
  'myWork.completedOn': 'Завършена на {{date}}',
  'myWork.confirmCompletion': 'Потвърди завършване',
  'myWork.viewReview': 'Виж ревюто',
};
