// Authentication and authorization translations
export const auth = {
  'auth.applyForTask': 'Кандидатствай за задачата',
  'auth.askQuestion': 'Задай въпрос',
  'auth.createTask': 'Създай задача',
  'auth.loginToContinue': 'За да продължите, моля влезте в акаунта си',
  'auth.applyDescription':
    'Изпратете заявка на клиента и получете възможност да работите по тази задача.',
  'auth.questionDescription':
    'Задайте въпрос на клиента преди да кандидатствате за задачата.',
  'auth.createTaskDescription':
    'Създайте нова задача и намерете доверени професионалисти да завършат работата ви.',
  'auth.joinAsProfessional': 'Стани професионалист',
  'auth.joinAsProfessionalDescription':
    'Започнете да печелите, като предлагате уменията и услугите си на клиенти във вашия район.',
  'auth.loginDescription':
    'Влезте в акаунта си за да управлявате задачи и да се свързвате с професионалисти.',
  'auth.email': 'Имейл адрес',
  'auth.password': 'Парола',
  'auth.rememberMe': 'Запомни ме',
  'auth.forgotPassword': 'Забравена парола?',
  'auth.loginOrRegister': 'Влизане / Регистрация',
  'auth.loginOrRegisterToContinue': 'За да продължите, моля влезте или се регистрирайте',
  'auth.loginOrRegisterDescription': 'Въведете данните си за достъп до акаунта или създайте нов.',
  'auth.continue': 'Продължи',
  'auth.login': 'Влизане',
  'auth.or': 'или',
  'auth.noAccount': 'Нямате акаунт?',
  'auth.createAccount': 'Създайте акаунт',
  'auth.whyRegister': 'Защо да се регистрирате?',
  'auth.benefit1': '• Кандидатствайте за задачи',
  'auth.benefit2': '• Общувайте директно с клиентите',
  'auth.benefit3': '• Проследявайте историята си',
  'auth.benefit4': '• Получавайте известия за нови задачи',
  'auth.continueWith': 'Продължи с',
  'auth.telegramHint': 'Отваря Telegram приложението или десктоп клиента',

  // Unified auth form
  'auth.fullName': 'Вашето име',
  'auth.nameRequired': 'Моля, въведете името си за да създадете акаунт',
  'auth.nameRequiredHint': 'Името е задължително за създаване на акаунт',
  'auth.nameHint': 'Само при създаване на нов акаунт',
  'auth.unexpectedError': 'Възникна неочаквана грешка. Моля, опитайте отново.',

  // Email verification
  'auth.email.subject': 'Trudify - Потвърдете имейл адреса си',
  'auth.email.heading': 'Добре дошли в Trudify!',
  'auth.email.greeting': 'Здравейте',
  'auth.email.message':
    'Благодарим ви, че се регистрирахте! Моля, потвърдете имейл адреса си, за да активирате известията по имейл.',
  'auth.email.buttonText': 'Потвърди имейл адрес',
  'auth.email.linkInstruction': 'Или копирайте и поставете този линк в браузъра си:',
  'auth.email.expiresIn': '24 часа',
  'auth.email.footerText': 'Ако не сте създали акаунт, можете спокойно да игнорирате този имейл.',
  'auth.email.footerRights': 'Всички права запазени.',

  // Forgot password
  'auth.forgotPassword.title': 'Забравена парола',
  'auth.forgotPassword.description': 'Въведете имейла си и ще ви изпратим линк за възстановяване на паролата.',
  'auth.forgotPassword.emailLabel': 'Имейл адрес',
  'auth.forgotPassword.sendResetLink': 'Изпрати линк за възстановяване',
  'auth.forgotPassword.backToLogin': 'Обратно към влизане',
  'auth.forgotPassword.checkEmail': 'Проверете имейла си',
  'auth.forgotPassword.emailSent': 'Изпратихме линк за възстановяване на паролата до',
  'auth.forgotPassword.emailSentInstructions': 'Моля, проверете входящата си поща и кликнете върху линка, за да възстановите паролата си.',
  'auth.forgotPassword.didNotReceive': 'Не получихте имейла?',
  'auth.forgotPassword.resendLink': 'Изпрати отново',
  'auth.forgotPassword.error': 'Неуспешно изпращане на имейл за възстановяване. Моля, опитайте отново.',

  // Reset password
  'auth.resetPassword.title': 'Възстановяване на парола',
  'auth.resetPassword.description': 'Въведете новата си парола по-долу.',
  'auth.resetPassword.newPassword': 'Нова парола',
  'auth.resetPassword.confirmPassword': 'Потвърди новата парола',
  'auth.resetPassword.resetButton': 'Възстанови паролата',
  'auth.resetPassword.success': 'Паролата е успешно възстановена!',
  'auth.resetPassword.successDescription': 'Вече можете да влезете с новата си парола.',
  'auth.resetPassword.goToLogin': 'Към влизане',
  'auth.resetPassword.invalidToken': 'Невалиден или изтекъл линк за възстановяване',
  'auth.resetPassword.invalidTokenDescription': 'Този линк за възстановяване на паролата е невалиден или е изтекъл. Моля, заявете нов.',
  'auth.resetPassword.passwordMismatch': 'Паролите не съвпадат',
  'auth.resetPassword.passwordTooShort': 'Паролата трябва да е поне 6 символа',
  'auth.resetPassword.error': 'Неуспешно възстановяване на паролата. Моля, опитайте отново.',

  // Email verification
  'auth.emailVerification.title': 'Потвърдете имейла си',
  'auth.emailVerification.notVerified': 'Имейлът ви не е потвърден',
  'auth.emailVerification.description': 'Моля, потвърдете имейла си, за да получавате известия и достъп до всички функции.',
  'auth.emailVerification.resendButton': 'Изпрати имейл за потвърждение',
  'auth.emailVerification.resending': 'Изпращане...',
  'auth.emailVerification.success': 'Имейлът за потвърждение е изпратен! Проверете входящата си поща.',
  'auth.emailVerification.alreadyVerified': 'Имейлът ви вече е потвърден!',
  'auth.emailVerification.error': 'Неуспешно изпращане на имейл за потвърждение. Моля, опитайте отново.',
  'auth.emailVerification.rateLimited': 'Твърде много заявки. Моля, опитайте отново по-късно.',
  'auth.emailVerification.checkSpam': 'Не забравяйте да проверите папката си за спам.',

  // Email verification after signup (auth slide-over)
  'auth.emailVerification.checkInbox': 'Проверете входящата си поща!',
  'auth.emailVerification.sentMessage': 'Изпратихме имейл за потвърждение на',
  'auth.emailVerification.instructions': 'Кликнете върху връзката в имейла, за да потвърдите акаунта си.',
  'auth.emailVerification.resend': 'Изпрати отново имейл за потвърждение',
  'auth.emailVerification.continue': 'Продължи към приложението',

  // Email verified success page
  'auth.emailVerified.title': 'Имейлът е потвърден!',
  'auth.emailVerified.description': 'Вашият имейл е успешно потвърден. Вече имате пълен достъп до всички функции.',
  'auth.emailVerified.whatNext': 'Какво искате да направите сега?',
  'auth.emailVerified.browseTasks': 'Намери работа',
  'auth.emailVerified.createTask': 'Публикувай задача',
  'auth.emailVerified.completeProfile': 'Попълни профила си',
  'auth.emailVerified.goHome': 'Към началната страница',

  // Account Deletion
  'accountDeletion.title': 'Изтриване на акаунт',
  'accountDeletion.loginRequired': 'За да изтриете акаунта си, трябва да сте влезли в системата.',
  'accountDeletion.whatHappens': 'Какво се случва при изтриване на акаунта:',
  'accountDeletion.profileRemoved': 'Профилът ви се премахва завинаги',
  'accountDeletion.tasksCancelled': 'Отворените задачи се отменят',
  'accountDeletion.reviewsAnonymized': 'Отзивите ви стават анонимни (оценките се запазват)',
  'accountDeletion.cannotUndo': 'Това действие не може да бъде отменено',
  'accountDeletion.loginWithGoogle': 'Вход с Google',
  'accountDeletion.loginWithFacebook': 'Вход с Facebook',
  'accountDeletion.backToHome': 'Обратно към началото',
  'accountDeletion.checkingStatus': 'Проверка на статуса на акаунта...',
  'accountDeletion.errorTitle': 'Нещо се обърка',
  'accountDeletion.tryAgain': 'Опитай отново',
  'accountDeletion.cannotDeleteYet': 'Все още не можете да изтриете акаунта',
  'accountDeletion.completeTasksFirst': 'Имате активна работа, която трябва да бъде завършена първо.',
  'accountDeletion.activeWork': 'Активни задачи, блокиращи изтриването:',
  'accountDeletion.asCustomer': 'като клиент',
  'accountDeletion.asProfessional': 'като професионалист',
  'accountDeletion.viewMyTasks': 'Виж моите задачи',
  'accountDeletion.backToProfile': 'Обратно към профила',
  'accountDeletion.confirmTitle': 'Изтриване на акаунт',
  'accountDeletion.confirmDescription': 'Това ще изтрие завинаги акаунта ви и всички свързани данни.',
  'accountDeletion.readyToDelete': 'Проверката премина - готови за изтриване',
  'accountDeletion.willBeDeleted': 'Ще бъде изтрито завинаги:',
  'accountDeletion.openTasksCount': '{{count}} отворени задачи ще бъдат отменени',
  'accountDeletion.applicationsCount': '{{count}} чакащи кандидатури ще бъдат оттеглени',
  'accountDeletion.messagesCount': '{{count}} съобщения',
  'accountDeletion.notificationsCount': '{{count}} известия',
  'accountDeletion.willBeAnonymized': 'Ще бъде анонимизирано:',
  'accountDeletion.reviewsWrittenCount': '{{count}} отзива, които сте написали (оценките се запазват)',
  'accountDeletion.irreversibleWarning': 'Това действие е постоянно и не може да бъде отменено. Всички ваши данни ще бъдат изтрити завинаги.',
  'accountDeletion.confirmPassword': 'Потвърдете с вашата парола',
  'accountDeletion.enterPassword': 'Въведете паролата си',
  'accountDeletion.passwordDescription': 'Въведете паролата си, за да потвърдите изтриването на акаунта',
  'accountDeletion.passwordOptionalNote': 'Изисква се само ако сте се регистрирали с имейл и парола. Оставете празно, ако сте се регистрирали с Google или Facebook.',
  'accountDeletion.noPasswordLink': 'Никога не сте задавали парола? Задайте една тук',
  'accountDeletion.deleteButton': 'Изтрий акаунта ми',
  'accountDeletion.cancel': 'Отказ',
  'accountDeletion.invalidPassword': 'Невалидна парола. Моля, опитайте отново.',
  'accountDeletion.hasActiveTasksError': 'Не можете да изтриете акаунт с активни задачи. Моля, първо ги завършете или отменете.',
  'accountDeletion.deleteError': 'Неуспешно изтриване на акаунта. Моля, опитайте отново.',
  'accountDeletion.preflightError': 'Неуспешна проверка на статуса. Моля, опитайте отново.',
  'accountDeletion.unknownError': 'Възникна неочаквана грешка. Моля, опитайте отново.',
};
