// Common UI terms and global actions
export const common = {
  welcome: 'Добре дошли',
  login: 'Вход',
  logout: 'Изход',
  signup: 'Регистрация',
  search: 'Търсене',
  browse: 'Разглеждане',
  create: 'Създаване',
  edit: 'Редактиране',
  delete: 'Изтриване',
  cancel: 'Отказ',
  dismiss: 'Може би по-късно',
  ignore: 'Игнорирай',
  important: 'Важно',
  save: 'Запазване',
  submit: 'Изпращане',
  loading: 'Зареждане...',
  error: 'Грешка',
  success: 'Успех',
  back: 'Назад',
  next: 'Напред',
  previous: 'Предишна',
  reviews: 'отзива',
  close: 'Затвори',
  today: 'Днес',
  yesterday: 'Вчера',
  application: 'кандидатура',
  applications: 'кандидатури',

  'common.optional': 'По избор',
  'common.close': 'Затвори',
  'common.ok': 'ОК',
  'common.days': 'дни',
  'common.cancel': 'Отказ',
  'common.edit': 'Редактирай',
  'common.save': 'Запази',
  'common.anonymous': 'Анонимен потребител',
  'common.goBack': 'Назад',
  'common.today': 'Днес',
  'common.yesterday': 'Вчера',
  'common.reviews': 'отзива',
  'common.tasksCompleted': 'изпълнени задачи',
  'common.newProfessional': 'Нов в Trudify',

  // Countries
  'common.country.bulgaria': 'България',

  'language.en': 'English',
  'language.bg': 'Български',
  'language.ru': 'Русский',
  'language.ua': 'Українська',

  // Locations
  'locations.sofiaCenter': 'София, Център',
  'locations.sofiaLyulin': 'София, Люлин',
  'locations.sofiaStudentski': 'София, Студентски град',
  'locations.sofiaVitosha': 'София, Витоша',
  'locations.plovdiv': 'Пловдив',
  'locations.varna': 'Варна',
  'locations.burgas': 'Бургас',
  'locations.ruse': 'Русе',
  'locations.staraZagora': 'Стара Загора',

  // Cities (top 8 supported - MVP)
  'cities.sofia': 'София',
  'cities.plovdiv': 'Пловдив',
  'cities.varna': 'Варна',
  'cities.burgas': 'Бургас',
  'cities.ruse': 'Русе',
  'cities.staraZagora': 'Стара Загора',
  'cities.pleven': 'Плевен',
  'cities.sliven': 'Сливен',

  // Common messages
  'message.taskCreated': 'Задачата е създадена успешно!',
  'message.profileUpdated': 'Профилът е актуализиран успешно!',
  'message.applicationSubmitted': 'Кандидатурата е изпратена успешно!',
  'error.generic': 'Нещо се обърка. Моля, опитайте отново.',
  'error.network': 'Грешка в мрежата. Моля, проверете връзката си.',
  'error.unauthorized': 'Трябва да влезете, за да достъпите тази страница.',

  // Empty states
  'common.noResults': 'Не са намерени задачи',
  'common.noResultsFilter': 'Опитайте да изберете различен филтър за статус',
  'common.clearFilters': 'Виж всички задачи',
  'common.errorGeneric': 'Нещо се обърка. Моля, опитайте отново.',

  // Safety & Trust Indicators
  'safety.phoneVerified': 'Потвърден телефон',
  'safety.emailVerified': 'Потвърден имейл',
  'safety.cleanRecord': 'Чист профил за безопасност',
  'safety.hasNegativeReviews': 'Има негативни отзиви',
  'safety.multipleReports': 'Множество сигнали',
  'safety.negativeReviewsTooltip': 'Този специалист е получил множество негативни отзиви. Моля, бъдете внимателни.',
  'safety.multipleReportsTooltip': 'Този специалист е получил множество сигнали за безопасност от различни потребители.',
  'safety.negativeReviewsWarning': 'Този специалист е получил множество негативни отзиви',
  'safety.negativeReviewsWarningMessage': 'Множество клиенти са докладвали проблеми с качеството на услугата. Моля, прегледайте отзивите внимателно и бъдете предпазливи при наемане.',
  'safety.multipleReportsWarning': 'Предупреждение за безопасност: Множество сигнали',
  'safety.multipleReportsWarningMessage': 'Този специалист е получил множество сигнали за безопасност от различни клиенти. Препоръчваме да продължите с допълнително внимание или да изберете друг специалист.',

  // Review Visibility
  'reviews.hiddenReviewsNotice': 'Някои отзиви са скрити до потвърждение',
  'reviews.hiddenReviewsTooltip': 'Ниско оценени отзиви се скриват докато не се открие модел, за да се защитят от несправедливи единични отзиви.',
  'reviews.hiddenCountSingular': '1 скрит отзив',
  'reviews.hiddenCountPlural': '{{count}} скрити отзива',
  'reviews.patternDetected': 'Открит е модел на негативни отзиви',
  'reviews.allNegativeVisible': 'Всички негативни отзиви сега са видими поради модел на проблеми.',

  // Scam Reporting
  'report.button': 'Докладвай проблем',
  'report.dialogTitle': 'Докладване на опасност',
  'report.dialogDescription': 'Помогнете ни да поддържаме безопасна общност, като докладвате подозрително поведение или нарушения.',
  'report.typeLabel': 'Тип проблем',
  'report.descriptionLabel': 'Описание',
  'report.descriptionPlaceholder': 'Моля, предоставете конкретни детайли за проблема...',
  'report.evidenceLabel': 'Доказателства (По избор)',
  'report.evidenceHint': 'Качете екранни снимки или снимки в подкрепа на доклада',
  'report.evidenceComingSoon': '(Очаквайте скоро)',
  'report.submitButton': 'Изпращане на доклад',
  'report.cancelButton': 'Отказ',
  'report.successMessage': 'Докладът е изпратен успешно. Екипът ни ще го прегледа незабавно.',
  'report.errorMessage': 'Неуспешно изпращане на доклада. Моля, опитайте отново.',
  'report.falseReportWarning': 'Неверни доклади могат да доведат до действия срещу вашия акаунт. Моля, докладвайте само истински проблеми с безопасността.',

  // Report Types
  'report.type.fraud_scam': 'Измама или опит за измама',
  'report.type.threatening_behavior': 'Заплашително или агресивно поведение',
  'report.type.harassment': 'Тормоз или тормозене',
  'report.type.identity_theft': 'Фалшив профил или кражба на самоличност',
  'report.type.poor_quality': 'Постоянно лошо качество на работата',
  'report.type.no_show': 'Повтарящи се неявявания',
  'report.type.other': 'Друга опасност',

  // Suspension
  'suspension.accountSuspended': 'Акаунт спрян',
  'suspension.message': 'Този акаунт е временно спрян поради множество сигнали за безопасност.',
  'suspension.appeal': 'Ако смятате, че това е грешка, можете да подадете жалба по имейл.',
  'suspension.contactEmail': 'Контакт: support@taskbridge.com',

  // Notification Warning (Compact Chip)
  'notificationWarning.title': 'Важно: Настройте нотификации',
  'notificationWarning.message': 'Няма да получавате актуализации за кандидатури, съобщения или промени в задачата без канал за нотификации.',
  'notificationWarning.recommendation': 'Препоръчваме да свържете Telegram за моментални нотификации или да потвърдите вашия имейл като алтернатива.',
  'notificationWarning.compact': 'Настройте нотификации, за да получавате актуализации за задачите си',
  'notificationWarning.setup': 'Настройка',
  'notificationWarning.connectTelegram': 'Свържете Telegram',
  'notificationWarning.verifyEmail': 'Потвърдете имейл',
  'notificationWarning.dismiss': 'Разбрах',

  // Profanity Validation
  'validation.profanityDetected': 'Вашият текст съдържа неподходящ език. Моля, преработете го.',
  'validation.profanityTitle': 'Заглавието на задачата съдържа неподходящ език',
  'validation.profanityDescription': 'Описанието на задачата съдържа неподходящ език',
  'validation.profanityWarning': 'Някои думи може да бъдат маркирани. Прегледайте преди изпращане.',
  'validation.profanitySeverity.mild': 'Моля, избягвайте използването на неподходящ език',
  'validation.profanitySeverity.moderate': 'Вашият текст съдържа обидни изрази, които не са разрешени',
  'validation.profanitySeverity.severe': 'Вашият текст съдържа силно обидни изрази, които нарушават нашите правила на общността',
};
