export const contentPages = {
  // About Page
  'about.hero.title': 'Свързваме България с проверени професионалисти',
  'about.hero.subtitle': 'Вярваме, че всеки заслужава достъп до надеждни, проверени специалисти за ежедневните си нужди.',

  'about.problem.title': 'Проблемът, който решаваме',
  'about.problem.description': 'Намирането на надеждна помощ в България винаги е било предизвикателство. Препоръките от уста на уста са ограничени и няма лесен начин да проверите качеството на специалист, преди да го наемете. Ние променяме това.',

  'about.solution.title': 'Нашето решение',
  'about.solution.description': 'Trudify е платформа, която свързва клиенти с проверени местни професионалисти. Всеки специалист в нашата платформа е проверен, оценен и има отзиви от реални клиенти.',

  'about.mission.title': 'Нашата мисия',
  'about.mission.description': 'Да направим намирането на надеждни професионалисти лесно като няколко клика, като същевременно помагаме на квалифицирани работници да изградят устойчив бизнес.',

  'about.values.title': 'Нашите ценности',
  'about.values.trust': 'Доверие',
  'about.values.trustDesc': 'Всеки професионалист е проверен. Всеки отзив е от реален клиент.',
  'about.values.transparency': 'Прозрачност',
  'about.values.transparencyDesc': 'Ясни цени, честни отзиви, без скрити такси.',
  'about.values.fairness': 'Справедливост',
  'about.values.fairnessDesc': 'Справедливи възможности за професионалисти, справедливи цени за клиенти.',
  'about.values.quality': 'Качество',
  'about.values.qualityDesc': 'Поставяме високи стандарти и помагаме на професионалистите да ги постигнат.',

  'about.stats.professionals': 'Проверени професионалисти',
  'about.stats.tasks': 'Изпълнени задачи',
  'about.stats.cities': 'Покрити градове',
  'about.stats.satisfaction': 'Удовлетвореност на клиентите',

  'about.cta.title': 'Готови ли сте да започнете?',
  'about.cta.subtitle': 'Присъединете се към хилядите клиенти и професионалисти, използващи Trudify днес.',
  'about.cta.customer': 'Публикувайте задача',
  'about.cta.professional': 'Станете професионалист',

  // How It Works Page
  'howItWorks.hero.title': 'Как работи Trudify',
  'howItWorks.hero.subtitle': 'Просто, сигурно и ясно. Ето как да свършите нещата.',

  'howItWorks.customers.title': 'За клиенти',
  'howItWorks.customers.subtitle': 'Получете помощ в 4 лесни стъпки',
  'howItWorks.customers.step1.title': 'Публикувайте задачата си',
  'howItWorks.customers.step1.description': 'Опишете какво ви трябва, задайте бюджет и публикувайте безплатно. Отнема по-малко от 2 минути.',
  'howItWorks.customers.step2.title': 'Получете оферти',
  'howItWorks.customers.step2.description': 'Проверени професионалисти във вашия район ще ви изпратят оферти. Сравнете профилите, отзивите и цените им.',
  'howItWorks.customers.step3.title': 'Изберете и разговаряйте',
  'howItWorks.customers.step3.description': 'Изберете професионалиста, който най-добре отговаря на нуждите ви. Разговаряйте с него, за да обсъдите детайлите преди потвърждение.',
  'howItWorks.customers.step4.title': 'Свършете работата',
  'howItWorks.customers.step4.description': 'Професионалистът завършва работата. Платете само когато сте доволни и оставете отзив.',
  'howItWorks.customers.learnMore': 'Научете повече и гледайте видео гайдове',

  'howItWorks.professionals.title': 'За професионалисти',
  'howItWorks.professionals.subtitle': 'Развийте бизнеса си с Trudify',
  'howItWorks.professionals.step1.title': 'Създайте профил',
  'howItWorks.professionals.step1.description': 'Регистрирайте се, потвърдете самоличността си и покажете уменията и предишната си работа.',
  'howItWorks.professionals.step2.title': 'Разгледайте задачи',
  'howItWorks.professionals.step2.description': 'Намерете задачи във вашия район, които съответстват на уменията ви. Филтрирайте по категория, местоположение и бюджет.',
  'howItWorks.professionals.step3.title': 'Изпратете оферти',
  'howItWorks.professionals.step3.description': 'Изпращайте конкурентни оферти на клиентите. Откройте се с профила и отзивите си.',
  'howItWorks.professionals.step4.title': 'Изградете репутацията си',
  'howItWorks.professionals.step4.description': 'Изпълнявайте задачи, събирайте отзиви и развивайте бизнеса си. Най-добре оценените професионалисти получават повече работа.',
  'howItWorks.professionals.learnMore': 'Научете повече и гледайте видео гайдове',

  'howItWorks.cta.title': 'Готови да започнете?',
  'howItWorks.cta.subtitle': 'Независимо дали имате нужда от помощ или искате да предложите услугите си, ние сме тук за вас.',

  // FAQ Page
  'faq.hero.title': 'Често задавани въпроси',
  'faq.hero.subtitle': 'Намерете отговори на често задавани въпроси за използването на Trudify.',

  'faq.customers.title': 'За клиенти',
  'faq.customers.q1': 'Колко струва да публикувам задача?',
  'faq.customers.a1': 'Публикуването на задача в Trudify е напълно безплатно. Плащате на професионалиста само когато работата е завършена и сте доволни.',
  'faq.customers.q2': 'Как да разбера дали професионалистите са надеждни?',
  'faq.customers.a2': 'Професионалистите в Trudify изграждат репутацията си чрез реални отзиви от клиенти и история на завършени задачи. Можете да видите техните оценки, отзиви и опит преди да ги наемете.',
  'faq.customers.q3': 'Какво ако не съм доволен от работата?',
  'faq.customers.a3': 'Trudify свързва клиенти с професионалисти - всички договорености са между вас и професионалиста. Ако не сте доволни, можете да оставите честен отзив, за да предупредите другите, или да докладвате професионалиста. Множество сигнали водят до ограничаване на акаунта.',
  'faq.customers.q4': 'Мога ли да отменя задача?',
  'faq.customers.a4': 'Да, можете да отмените задача по всяко време, дори след като професионалист е започнал работа по нея. За да предотвратим злоупотреби, има месечен лимит на отмените.',
  'faq.customers.q5': 'Как работят плащанията?',
  'faq.customers.a5': 'Плащането се уговаря директно между вас и професионалиста. Бюджетът, който задавате, е ориентировъчен - крайната цена трябва да се договори с професионалиста, след като разбере напълно обхвата на работата.',

  'faq.professionals.title': 'За професионалисти',
  'faq.professionals.q1': 'Как да се регистрирам като професионалист?',
  'faq.professionals.a1': 'Създайте акаунт, попълнете профила си с вашите умения и опит и започнете да кандидатствате за задачи. Изградете репутацията си чрез качествена работа и събирайте отзиви от доволни клиенти.',
  'faq.professionals.q2': 'Какви такси начислява Trudify?',
  'faq.professionals.a2': 'В момента Trudify е безплатен за професионалисти по време на стартовия период. Възможно е в бъдеще да въведем малка комисионна за завършени задачи.',
  'faq.professionals.q3': 'Как да получа повече работа?',
  'faq.professionals.a3': 'Попълнете профила си, добавете снимки на работата си, отговаряйте бързо на задачи, доставяйте качествена работа и събирайте положителни отзиви. Най-добре оценените професионалисти се показват по-високо в резултатите от търсенето.',
  'faq.professionals.q4': 'Мога ли да работя в няколко града?',
  'faq.professionals.a4': 'Да, можете да зададете зоните си на обслужване да включват няколко града и квартала.',
  'faq.professionals.q5': 'Как работят отзивите?',
  'faq.professionals.a5': 'След завършване на задача клиентите могат да оставят отзив и оценка. Те се показват в профила ви и помагат за изграждането на репутацията ви.',

  'faq.general.title': 'Общи въпроси',
  'faq.general.q1': 'Trudify достъпен ли е в моя град?',
  'faq.general.a1': 'Trudify в момента е достъпен в основните български градове, включително София, Пловдив, Варна, Бургас, Русе, Стара Загора, Плевен и Сливен. Скоро се разширяваме към още градове.',
  'faq.general.q2': 'Какви услуги са налични?',
  'faq.general.a2': 'Предлагаме широка гама от услуги, включително домашни ремонти, почистване, преместване, ИТ поддръжка, уроци, козметични услуги и много други. Разгледайте категориите ни, за да видите всички налични услуги.',
  'faq.general.q3': 'Как да се свържа с поддръжката?',
  'faq.general.a3': 'Пишете ни на support@trudify.com или ни потърсете в социалните мрежи (линкове във футъра). Обикновено отговаряме в рамките на 24 часа.',
  'faq.general.q4': 'Как да получавам известия за нови задачи или кандидатури?',
  'faq.general.a4': 'Свържете Telegram акаунта си в настройките на профила, за да получавате безплатни мигновени известия. Професионалистите получават известия за покани за задачи, а клиентите - когато професионалисти кандидатстват за техните задачи.',

  'faq.resources.title': 'Полезни ресурси',
  'faq.resources.customerGuide': 'Гайд за клиенти',
  'faq.resources.customerGuideDesc': 'Гледайте видео уроци как да публикувате задачи и да наемете професионалисти.',
  'faq.resources.professionalGuide': 'Гайд за професионалисти',
  'faq.resources.professionalGuideDesc': 'Научете как да намирате работа и да развивате бизнеса си в Trudify.',
  'faq.resources.blogPost': 'Търсите работа?',
  'faq.resources.blogPostDesc': 'Прочетете нашия гайд за намиране на работа на свободна практика в България.',
  'faq.resources.watchVideos': 'Гледайте видео',
  'faq.resources.readArticle': 'Прочетете статията',

  'faq.cta.title': 'Все още имате въпроси?',
  'faq.cta.subtitle': 'Нашият екип за поддръжка е тук, за да помогне.',
  'faq.cta.contact': 'Свържете се с поддръжката',

  // For Professionals Page
  'forProfessionals.hero.title': 'Развийте бизнеса си с Trudify',
  'forProfessionals.hero.subtitle': 'Присъединете се към хиляди професионалисти, които намират нови клиенти и изграждат репутацията си.',
  'forProfessionals.hero.cta': 'Започнете да печелите клиенти',

  'forProfessionals.benefits.title': 'Защо да се присъедините към Trudify?',
  'forProfessionals.benefits.noFees': 'Без предварителни такси',
  'forProfessionals.benefits.noFeesDesc': 'Присъединете се безплатно. Без абонамент, без скрити разходи. Успявате само когато печелите работа.',
  'forProfessionals.benefits.customers': 'Постоянен поток от клиенти',
  'forProfessionals.benefits.customersDesc': 'Достъп до постоянен поток от местни клиенти, търсещи вашите услуги. Без повече чакане на препоръки от уста на уста.',
  'forProfessionals.benefits.reputation': 'Изградете репутацията си',
  'forProfessionals.benefits.reputationDesc': 'Събирайте отзиви, покажете работата си и изградете професионално онлайн присъствие, което работи за вас 24/7.',
  'forProfessionals.benefits.mobile': 'Работете на собствени условия',
  'forProfessionals.benefits.mobileDesc': 'Избирайте работата, която искате, задавайте собствени цени и управлявайте всичко от телефона си.',

  'forProfessionals.howEarnings.title': 'Как работят приходите',
  'forProfessionals.howEarnings.description': 'Вие задавате собствените си цени и преговаряте директно с клиентите. Trudify в момента е безплатен за професионалисти по време на стартовия период.',

  'forProfessionals.videoGuides.title': 'Видео гайдове',
  'forProfessionals.videoGuides.subtitle': 'Гледайте кратки уроци и започнете за минути',
  'forProfessionals.videoGuides.video1.title': 'Първи стъпки',
  'forProfessionals.videoGuides.video1.description': 'Как да се регистрирате и попълните професионалния си профил',
  'forProfessionals.videoGuides.video2.title': 'Намиране на работа',
  'forProfessionals.videoGuides.video2.description': 'Как да търсите задачи, да кандидатствате и да получавате известия',

  'forProfessionals.stats.title': 'Присъединете се към растяща общност',

  'forProfessionals.cta.title': 'Готови да започнете да печелите?',
  'forProfessionals.cta.subtitle': 'Създайте профила си днес и започнете да се свързвате с клиенти във вашия район.',
  'forProfessionals.cta.button': 'Създайте професионален профил',

  // For Customers Page
  'forCustomers.hero.title': 'Свършете нещата с Trudify',
  'forCustomers.hero.subtitle': 'Намерете проверени професионалисти за всяка задача. Публикувайте и получете оферти за минути.',
  'forCustomers.hero.cta': 'Публикувайте първата задача',

  'forCustomers.benefits.title': 'Защо клиентите обичат Trudify',
  'forCustomers.benefits.fast': 'Бързи резултати',
  'forCustomers.benefits.fastDesc': 'Публикувайте задача и получете оферти в рамките на часове. Без повече безкрайно търсене и чакане.',
  'forCustomers.benefits.verified': 'Проверени професионалисти',
  'forCustomers.benefits.verifiedDesc': 'Всеки професионалист е проверен. Вижте техните оценки, отзиви и история на завършените задачи.',
  'forCustomers.benefits.communicate': 'Лесна комуникация',
  'forCustomers.benefits.communicateDesc': 'Разговаряйте директно с професионалисти, за да обсъдите детайли, да договорите цени и да потвърдите графици.',
  'forCustomers.benefits.reviews': 'Достоверни отзиви',
  'forCustomers.benefits.reviewsDesc': 'Реални отзиви от реални клиенти ви помагат да изберете най-добрия професионалист за вашата задача.',

  'forCustomers.howItWorks.title': 'Как работи',
  'forCustomers.howItWorks.subtitle': 'Получете помощ в 3 лесни стъпки',
  'forCustomers.howItWorks.step1.title': 'Публикувайте задача',
  'forCustomers.howItWorks.step1.description': 'Опишете какво ви трябва. Отнема 2 минути, напълно безплатно.',
  'forCustomers.howItWorks.step2.title': 'Получете кандидатури',
  'forCustomers.howItWorks.step2.description': 'Професионалисти кандидатстват с цена и опит. Вие избирате.',
  'forCustomers.howItWorks.step3.title': 'Свършете работата',
  'forCustomers.howItWorks.step3.description': 'Изберете най-подходящия, договорете детайлите и платете само когато сте доволни.',

  'forCustomers.valueProposition.title': 'Спрете да търсите. Нека те да ви намерят.',
  'forCustomers.valueProposition.description': 'За разлика от сайтовете за обяви, където звъните на 10 номера и се надявате някой да отговори, в Trudify професионалистите се конкурират за вашата задача. Публикувате веднъж, те кандидатстват, вие избирате.',
  'forCustomers.valueProposition.free': '100% Безплатно за клиенти',
  'forCustomers.valueProposition.freeDesc': 'Без такси, без комисионни, без скрити разходи. Плащате само на професионалиста за свършената работа.',

  'forCustomers.privacy.title': 'Вашата поверителност е защитена',
  'forCustomers.privacy.description': 'Телефонът и имейлът ви остават скрити докато ВИЕ не изберете професионалист. Едва когато приемете кандидатурата, те получават контактите ви. Вие контролирате кой може да ви пише.',

  'forCustomers.faq.title': 'Чести въпроси',
  'forCustomers.faq.q1': 'Наистина ли е безплатно?',
  'forCustomers.faq.a1': 'Да, 100% безплатно. Без такси, без комисионни. Плащате само на професионалиста за работата му.',
  'forCustomers.faq.q2': 'Как да разбера дали професионалистите са надеждни?',
  'forCustomers.faq.a2': 'Всеки професионалист има верифицирани отзиви от реални клиенти, рейтинг и история на изпълнените задачи. Виждате точно кого наемате.',
  'forCustomers.faq.q3': 'Колко бързо мога да намеря помощ?',
  'forCustomers.faq.a3': 'Повечето задачи получават кандидатури в рамките на часове. За спешни задачи често има отговор още същия ден.',
  'forCustomers.faq.q4': 'Мога ли да видя цените преди да избера?',
  'forCustomers.faq.a4': 'Да! Всеки професионалист посочва цената си при кандидатстване. Сравнете офертите и изберете най-добрата комбинация от цена, опит и отзиви.',

  'forCustomers.videoGuides.title': 'Видео гайдове',
  'forCustomers.videoGuides.subtitle': 'Научете как да използвате Trudify за няколко минути',
  'forCustomers.videoGuides.video1.title': 'Първи стъпки',
  'forCustomers.videoGuides.video1.description': 'Как да се регистрирате и публикувате първата си задача',
  'forCustomers.videoGuides.video2.title': 'Поканете професионалист',
  'forCustomers.videoGuides.video2.description': 'Как да поканите конкретен професионалист към вашата задача',
  'forCustomers.videoGuides.video3.title': 'Прегледайте кандидатурите',
  'forCustomers.videoGuides.video3.description': 'Как да прегледате и приемете кандидатури',
  'forCustomers.videoGuides.video4.title': 'Оставете отзив',
  'forCustomers.videoGuides.video4.description': 'Как да оставите отзив след завършване на задачата',

  'forCustomers.stats.title': 'Присъединете се към хилядите доволни клиенти',

  'forCustomers.cta.title': 'Готови да започнете?',
  'forCustomers.cta.subtitle': 'Публикувайте първата си задача безплатно и намерете перфектния професионалист днес.',
  'forCustomers.cta.button': 'Публикувайте задача сега',

  // Pricing Page
  'pricing.hero.title': 'Просто и прозрачно ценообразуване',
  'pricing.hero.subtitle': 'Без скрити такси, без изненади. Ето как работи ценообразуването в Trudify.',

  'pricing.customers.title': 'За клиенти',
  'pricing.customers.free': 'Безплатно',
  'pricing.customers.description': 'Публикуването на задачи е винаги безплатно',
  'pricing.customers.feature1': 'Публикувайте неограничени задачи',
  'pricing.customers.feature2': 'Получавайте оферти от професионалисти',
  'pricing.customers.feature3': 'Разговаряйте с професионалисти',
  'pricing.customers.feature4': 'Без плащане докато работата не е готова',
  'pricing.customers.feature5': 'Оставяйте отзиви след завършване',

  'pricing.professionals.title': 'За професионалисти',
  'pricing.professionals.free': 'Безплатно (Стартов период)',
  'pricing.professionals.description': 'Присъединете се и започнете да печелите без такси',
  'pricing.professionals.feature1': 'Създайте професионален профил',
  'pricing.professionals.feature2': 'Разглеждайте и кандидатствайте за задачи',
  'pricing.professionals.feature3': 'Неограничени оферти',
  'pricing.professionals.feature4': 'Изграждайте репутация с отзиви',
  'pricing.professionals.feature5': 'Без комисионна по време на старта',
  'pricing.professionals.note': 'След стартовия период е възможно да въведем малка комисионна за завършени задачи. Настоящите потребители ще получат преференциални условия.',

  'pricing.cta.title': 'Започнете днес',
  'pricing.cta.subtitle': 'Присъединете се към Trudify и открийте най-лесния начин да намерите помощ или да развиете бизнеса си.',

  // Testimonials Page
  'testimonials.hero.title': 'Какво казват нашите потребители',
  'testimonials.hero.subtitle': 'Истински истории от клиенти и професионалисти, използващи Trudify.',

  'testimonials.customers.title': 'Доволни клиенти',
  'testimonials.professionals.title': 'Успешни професионалисти',

  'testimonials.cta.title': 'Присъединете се към нашата общност',
  'testimonials.cta.subtitle': 'Станете част от хилядите доволни потребители.',

  // Giveaway Page
  'giveaway.hero.badge': 'На всеки 2 месеца',
  'giveaway.hero.title': 'Печелете пари и награди!',
  'giveaway.hero.subtitle': 'Намерете работа бързо, получете заплащане за уменията си и спечелете ценни подаръчни карти на всеки два месеца.',
  'giveaway.hero.subtitleExtra': 'Присъединете се към хилядите професионалисти и клиенти, които вече печелят и получават награди в Trudify!',
  'giveaway.hero.totalPrizes': 'Общ награден фонд',
  'giveaway.hero.prizeCount': '10 Подаръчни карти',
  'giveaway.hero.ctaProfessional': 'Намерете работа сега',
  'giveaway.hero.ctaCustomer': 'Публикувайте задача',

  'giveaway.whyTrudify.title': 'Защо да изберете Trudify?',
  'giveaway.whyTrudify.subtitle': 'Независимо дали искате да намерите работа бързо, да спечелите допълнителни пари или да получите помощ с задачи - Trudify е платформата за вас. Плюс това, печелете награди просто като сте активни!',

  'giveaway.benefits.professionals.title': 'За професионалисти - Намерете работа и печелете',
  'giveaway.benefits.professionals.findWork.title': 'Намерете работа бързо',
  'giveaway.benefits.professionals.findWork.description': 'Получете достъп до стотици местни поръчки. Без повече чакане на обаждания - работата идва при вас!',
  'giveaway.benefits.professionals.earnMoney.title': 'Печелете повече пари',
  'giveaway.benefits.professionals.earnMoney.description': 'Определете собствените си цени и получете това, което заслужавате. Плащане директно от клиентите.',
  'giveaway.benefits.professionals.growBusiness.title': 'Развийте бизнеса си',
  'giveaway.benefits.professionals.growBusiness.description': 'Изградете репутацията си с отзиви. Топ професионалистите получават повече възможности за работа.',
  'giveaway.benefits.professionals.bonusRewards.title': 'Печелете бонус награди',
  'giveaway.benefits.professionals.bonusRewards.description': 'Всяка завършена задача ви включва в нашия двумесечен розигриш. Повече работа = повече шансове!',

  'giveaway.benefits.customers.title': 'За клиенти - Получете помощ бързо',
  'giveaway.benefits.customers.fastHelp.title': 'Бързи решения',
  'giveaway.benefits.customers.fastHelp.description': 'Публикувайте задача и получете оферти в рамките на часове. Намерете подходящия професионалист бързо.',
  'giveaway.benefits.customers.verified.title': 'Проверени професионалисти',
  'giveaway.benefits.customers.verified.description': 'Всички професионалисти са проверени. Прочетете отзивите и изберете с увереност.',
  'giveaway.benefits.customers.fairPrices.title': 'Честни цени',
  'giveaway.benefits.customers.fairPrices.description': 'Сравнете офертите и изберете най-добрата. Без скрити такси, без изненади.',
  'giveaway.benefits.customers.winPrizes.title': 'Спечелете подаръчни карти',
  'giveaway.benefits.customers.winPrizes.description': 'Публикувайте задачи и печелете награди! Клиентите също участват в двумесечния ни розигриш.',

  'giveaway.nextDraw.label': 'Следващо теглене',
  'giveaway.nextDraw.date': 'Февруари 2026',
  'giveaway.nextDraw.frequency': 'Честота на теглене',
  'giveaway.nextDraw.frequencyValue': 'На всеки 2 месеца',

  'giveaway.prizes.title': 'Награден фонд',
  'giveaway.prizes.subtitle': '10 щастливи победители ще получат подаръчни карти от топ марки. Бъдете активни в Trudify и вие можете да сте следващият!',
  'giveaway.prizes.grand': '1-во място',
  'giveaway.prizes.second': '2-ро място',
  'giveaway.prizes.third': '3-то място',
  'giveaway.prizes.remaining': 'Места 4-10',
  'giveaway.prizes.remainingValue': '7 x 20 EUR Подаръчни карти',
  'giveaway.prizes.sponsorNote': 'Марките на подаръчните карти ще бъдат обявени преди тегленето. Работим с премиум партньори!',

  'giveaway.howItWorks.title': 'Как да участвате',
  'giveaway.howItWorks.subtitle': 'Три лесни стъпки за да започнете да печелите и да получавате награди',
  'giveaway.howItWorks.step1.title': 'Създайте безплатен профил',
  'giveaway.howItWorks.step1.description': 'Регистрирайте се за минути. Създайте професионален профил за да намерите работа, или публикувайте първата си задача като клиент.',
  'giveaway.howItWorks.step2.title': 'Изпълнявайте задачи и печелете',
  'giveaway.howItWorks.step2.description': 'Професионалисти: намирайте и изпълнявайте поръчки. Клиенти: публикувайте задачи и ги завършвайте. И двете групи печелят участия!',
  'giveaway.howItWorks.step3.title': 'Печелете награди автоматично',
  'giveaway.howItWorks.step3.description': 'Всяка завършена задача е автоматично участие. Без допълнителни стъпки - просто работете и печелете!',

  'giveaway.seo.title': 'Започнете да печелите днес в България',
  'giveaway.seo.paragraph1': 'Търсите работа в България? Trudify свързва квалифицирани професионалисти с местни клиенти, които се нуждаят от помощ. Независимо дали сте водопроводчик, електротехник, чистач, шофьор, ИТ специалист или предлагате друга услуга - намерете работа бързо и получете заплащането, което заслужавате.',
  'giveaway.seo.paragraph2': 'Нуждаете се от помощ с някаква задача? Публикувайте поръчката си безплатно и получете оферти от проверени професионалисти във вашия район. От домашни ремонти и почистване до ИТ поддръжка и услуги за преместване - намерете надеждна помощ в София, Пловдив, Варна, Бургас и други български градове.',
  'giveaway.seo.paragraph3': 'Присъединете се към Trudify днес и станете част от растяща общност. Печелете пари, като правите това, което обичате, помагайте на хората във вашия квартал и печелете награди по пътя. Колкото по-активни сте, толкова повече можете да спечелите!',

  'giveaway.rules.title': 'Правила на розигриша',
  'giveaway.rules.rule1': 'Една завършена задача = едно участие в розигриша',
  'giveaway.rules.rule2': 'Както професионалисти, така и клиенти могат да спечелят',
  'giveaway.rules.rule3': 'Победителите се избират на случаен принцип от всички участия',
  'giveaway.rules.rule4': 'Подаръчните карти се доставят дигитално по имейл или Telegram',

  'giveaway.cta.title': 'Готови ли сте да печелите?',
  'giveaway.cta.subtitle': 'Присъединете се към хилядите професионалисти и клиенти в Trudify. Намерете работа, получете помощ и печелете награди - всичко на едно място!',
  'giveaway.cta.joinProfessional': 'Започнете да печелите сега',
  'giveaway.cta.postTask': 'Публикувайте първата си задача',
}
