// Navigation, header, and footer translations
export const navigation = {
  'nav.home': 'Начало',
  'nav.browseTasks': 'търси задачи',
  'nav.createTask': 'създай задача',
  'nav.profile': 'профил',
  'nav.profileCustomer': 'Профил на клиент',
  'nav.profileProfessional': 'Профил на професионалист',
  'nav.howItWorks': 'как работи',
  'nav.categories': 'категории',
  'nav.forProfessionals': 'За професионалисти',
  'nav.browseProfessionals': 'намери изпълнител',
  'nav.forCustomers': 'За клиенти',
  'nav.forClient': 'За клиенти',
  'nav.myTasks': 'Моите задачи',
  'nav.myPostedTasks': 'Моите задачи',
  'nav.myApplications': 'Моите кандидатури',
  'nav.myWork': 'Моята работа',
  'nav.tasksIPosted': 'моите задачи',
  'nav.tasksIAmDoing': 'моите работи',
  'nav.findProfessional': 'намери професионалист',
  'nav.findAnotherTask': 'намери друга задача',
  'nav.language': 'Език',
  'nav.general': 'Общи',
  'nav.discover': 'Открий',
  'nav.closeMenu': 'Затвори менюто',

  // Footer
  'footer.company.description':
    'Свързваме хора с квалифицирани специалисти за всякакви услуги в България.',
  'footer.quickLinks.title': 'Бързи връзки',
  'footer.quickLinks.howItWorks': 'Как работи',
  'footer.quickLinks.categories': 'Категории',
  'footer.quickLinks.forProfessionals': 'За професионалисти',
  'footer.quickLinks.forCustomers': 'За клиенти',
  'footer.quickLinks.browseTasks': 'Разгледай задачи',
  'footer.quickLinks.createTask': 'Създай задача',
  'footer.quickLinks.about': 'За нас',
  'footer.quickLinks.faq': 'Често задавани въпроси',
  'footer.quickLinks.testimonials': 'Отзиви',
  'footer.quickLinks.blog': 'Блог',
  'footer.legal.title': 'Правни',
  'footer.legal.terms': 'Условия за ползване',
  'footer.legal.privacy': 'Поверителност',
  'footer.contact.title': 'Контакти',
  'footer.contact.subtitle': 'Свържете се с нас',
  'footer.language.label': 'Език',
  'footer.copyright': '© 2025 Trudify. Всички права запазени.',

  // Social
  'footer.social.followUs': 'Последвайте ни',
  'footer.social.title': 'Ние сме социални',
};
