// Navigation, header, and footer translations
export const navigation = {
  'nav.home': 'Начало',
  'nav.browseTasks': 'Задачи',
  'nav.createTask': 'Създай',
  'nav.profile': 'Профил',
  'nav.profileCustomer': 'Профил на клиент',
  'nav.profileProfessional': 'Профил на професионалист',
  'nav.howItWorks': 'Как работи',
  'nav.categories': 'Категории',
  'nav.forProfessionals': 'Професионалисти',
  'nav.forCustomers': 'За клиенти',
  'nav.myTasks': 'Моите задачи',
  'nav.myPostedTasks': 'Моите задачи',
  'nav.myApplications': 'Моите кандидатури',
  'nav.myWork': 'Моята работа',
  'nav.help': 'Помощ',
  'nav.language': 'Език',
  'nav.general': 'Общи',
  'nav.discover': 'Открий',
  'nav.closeMenu': 'Затвори менюто',

  // Footer
  'footer.company.description':
    'Свързваме хора с квалифицирани специалисти за всякакви услуги в България.',
  'footer.quickLinks.title': 'Бързи връзки',
  'footer.quickLinks.howItWorks': 'Как работи',
  'footer.quickLinks.categories': 'Категории',
  'footer.quickLinks.forProfessionals': 'За професионалисти',
  'footer.quickLinks.browseTasks': 'Разгледай задачи',
  'footer.quickLinks.createTask': 'Създай задача',
  'footer.legal.title': 'Правни',
  'footer.legal.terms': 'Условия за ползване',
  'footer.legal.privacy': 'Политика за поверителност',
  'footer.contact.title': 'Контакти',
  'footer.contact.subtitle': 'Свържете се с нас',
  'footer.language.label': 'Език',
  'footer.copyright': '© 2025 Obod Soft LTD. Всички права запазени.',
};
