// Notifications, task detail, and posted tasks translations
export const notifications = {
  // Notifications
  'notifications.title': 'Известия',
  'notifications.markAllRead': 'Маркирай всички като прочетени',
  'notifications.tabAll': 'Всички',
  'notifications.tabApplications': 'Кандидатури',
  'notifications.tabTasks': 'Задачи',
  'notifications.tabMessages': 'Съобщения',
  'notifications.empty.title': 'Все още няма известия',
  'notifications.empty.message': 'Ще получите известие когато някой кандидатства за вашите задачи или отговори на вашите кандидатури.',
  'notifications.empty.filterMessage': 'Няма известия в тази категория.',
  'notifications.emptyUnread.title': 'Вече сте наваксали!',
  'notifications.emptyUnread.message': 'Всички известия са прочетени.',
  'notifications.viewApplication': 'Виж кандидатурата',
  'notifications.viewTask': 'Виж задачата',

  // Task Detail
  'taskDetail.backToTasks': 'Обратно към задачите',
  'taskDetail.requirements': 'Изисквания:',
  'taskDetail.keyInformation': 'Ключова информация',
  'taskDetail.client': 'Автор на задачата',
  'taskDetail.loginForMore': 'Влезте за повече',
  'taskDetail.loginMessage':
    'Влезте в акаунта си за да видите пълната информация',
  'taskDetail.completedTasks': 'завършени задачи',
  'taskDetail.memberSince': 'Член от',
  'taskDetail.similarTasks': 'Подобни задачи',
  'taskDetail.apply': 'Кандидатствай за задачата',
  'taskDetail.askQuestion': 'Задай въпрос',
  'taskDetail.applicationsCount': 'души',
  'taskDetail.timeAgo': 'преди',
  'taskDetail.today': 'Днес',
  'taskDetail.tomorrow': 'Утре',
  'taskDetail.days': 'дни',
  'taskDetail.flexible': 'Гъвкав',
  'taskDetail.negotiable': 'По договаряне',
  'taskDetail.urgency.same_day': 'Спешно - днес',
  'taskDetail.urgency.within_week': 'В рамките на седмица',
  'taskDetail.urgency.flexible': 'Гъвкав срок',
  'taskDetail.urgency.default': 'Неуточнен',
  'taskDetail.status': 'Статус',
  'taskDetail.statusTypes.vacant': 'Свободна',
  'taskDetail.statusTypes.applied': 'Кандидатствал',
  'taskDetail.statusTypes.done': 'Завършена',
  'taskDetail.statusTypes.archived': 'Архивирана',
  'taskDetail.appliedTooltip': 'Вие сте кандидатствали за тази задача. Клиентът може да приеме или отхвърли вашата кандидатура.',

  'taskDetail.share': 'Сподели',
  'taskDetail.activity': 'Активност по задачата',
  'taskDetail.applications': 'Кандидатури',
  'taskDetail.questions': 'Въпроси',
  'taskDetail.accept': 'Приеми',
  'taskDetail.reject': 'Отхвърли',
  'taskDetail.message': 'Съобщение',
  'taskDetail.reply': 'Отговори',
  'taskDetail.yourReply': 'Вашия отговор:',
  'taskDetail.price': 'Цена:',
  'taskDetail.tasks': 'задачи',
  'taskDetail.cancel': 'Отмени',
  'taskDetail.writeReply': 'Напишете вашия отговор...',
  'taskDetail.sendReply': 'Изпрати отговор',

  // Ask Question Dialog
  'taskDetail.askQuestionDialog.title': 'Задайте въпрос',
  'taskDetail.askQuestionDialog.placeholder': 'Какво бихте искали да знаете за тази задача?',
  'taskDetail.askQuestionDialog.submit': 'Публикувай въпрос',
  'taskDetail.askQuestionDialog.characterCount': '{{current}}/{{max}} знака',
  'taskDetail.askQuestionDialog.minLength': 'Въпросът трябва да бъде поне {{min}} знака',
  'taskDetail.askQuestionDialog.maxLength': 'Въпросът трябва да бъде най-много {{max}} знака',

  // Questions Section
  'taskDetail.questions.empty.title': 'Все още няма въпроси',
  'taskDetail.questions.empty.message': 'Бъдете първият, който ще зададе въпрос относно тази задача!',
  'taskDetail.questions.unanswered': 'Без отговор',
  'taskDetail.questions.answered': 'Отговорено',
  'taskDetail.questions.loading': 'Зареждане на въпроси...',

  // Answer Dialog
  'taskDetail.answerDialog.title': 'Отговори на въпрос',
  'taskDetail.answerDialog.placeholder': 'Напишете вашия отговор...',

  // Success/Error Messages
  'taskDetail.questionPosted': 'Вашият въпрос беше публикуван успешно!',
  'taskDetail.questionError': 'Неуспешно публикуване на въпрос. Моля, опитайте отново.',
  'taskDetail.answerPosted': 'Вашият отговор беше публикуван успешно!',
  'taskDetail.answerError': 'Неуспешно публикуване на отговор. Моля, опитайте отново.',

  // Posted Tasks Page (Customer View)
  'postedTasks.title': 'Моите публикувани задачи',
  'postedTasks.subtitle': 'Управлявайте задачите, които сте създали',
  'postedTasks.createTask': 'Създай задача',
  'postedTasks.filter.all': 'Всички',
  'postedTasks.filter.open': 'Отворени',
  'postedTasks.filter.inProgress': 'В процес',
  'postedTasks.filter.awaitingConfirmation': 'Очаква потвърждение',
  'postedTasks.filter.completed': 'Завършени',
  'postedTasks.filter.cancelled': 'Отменени',
  'postedTasks.applicationsCount': '{{count}} кандидатури',
  'postedTasks.viewApplications': 'Виж кандидатурите',
  'postedTasks.viewDetails': 'Виж детайлите',
  'postedTasks.editTask': 'Редактирай задача',
  'postedTasks.acceptedProfessional': 'Приет специалист',
  'postedTasks.awaitingYourConfirmation': 'Очаква вашето потвърждение',
  'postedTasks.markedComplete': 'маркира тази задача като завършена',
  'postedTasks.reportIssue': 'Докладвай проблем',
  'postedTasks.cancelTask': 'Откажи задача',
  'postedTasks.cancelTaskConfirm': 'Сигурни ли сте, че искате да откажете тази задача? Специалистът ще бъде уведомен.',
  'postedTasks.reopenTask': 'Отвори отново',
  'postedTasks.reopenTaskConfirm': 'Да се отвори отново тази задача, за да намерите нов специалист? Това ще премахне текущото назначение.',
  'postedTasks.empty.title': 'Все още няма публикувани задачи',
  'postedTasks.empty.message': 'Все още не сте публикували задачи. Създайте първата си задача!',
  'postedTasks.empty.createButton': 'Създай задача',

  // Cancel Task Dialog
  'cancelTask.title': 'Откажи задача',
  'cancelTask.professional': 'Специалист',
  'cancelTask.professionalNotification': 'Специалистът ще бъде уведомен за отказа',
  'cancelTask.reasonLabel': 'Защо отказвате тази задача?',
  'cancelTask.reasons.noShow': 'Специалистът не сеяви',
  'cancelTask.reasons.abandoned': 'Специалистът изостави работата',
  'cancelTask.reasons.unresponsive': 'Специалистът не отговаря',
  'cancelTask.reasons.changedRequirements': 'Изискванията ми се промениха',
  'cancelTask.reasons.foundAlternative': 'Намерих друго решение',
  'cancelTask.reasons.other': 'Друга причина',
  'cancelTask.descriptionLabel': 'Допълнителни детайли (по избор)',
  'cancelTask.descriptionPlaceholder': 'Моля, опишете какво се случи...',
  'cancelTask.descriptionHint': 'Помогнете ни да разберем ситуацията',
  'cancelTask.confirmButton': 'Откажи задача',
  'cancelTask.rateLimit.title': 'Можете да откажете още {{remaining}} задача/и този месец',
  'cancelTask.rateLimit.message': 'За предотвратяване на злоупотреби потребителите могат да отказват до {{max}} задачи месечно',
  'cancelTask.rateLimit.lastWarning': 'Това е последният ви безплатен отказ този месец. Използвайте го мъдро!',
  'cancelTask.limitExceeded.title': 'Достигнат месечен лимит на отказвания',
  'cancelTask.limitExceeded.message': 'Достигнахте лимита на отказвания за този месец. Честите отказвания могат да повлияят на репутацията на вашия акаунт. Моля, свържете се с поддръжката ако имате нужда от помощ.',

  // Edit Task Page
  'editTask.title': 'Редактиране на задача',
  'editTask.subtitle': 'Актуализирайте детайлите на задачата, за да привлечете повече специалисти',
  'editTask.editingBanner': 'Редактиране: {{title}}',
  'editTask.editingSubtext': 'Направете промени, за да подобрите задачата си',
  'editTask.help': 'Нуждаете се от помощ? Свържете се с нашия екип за поддръжка',
  'editTask.savingChanges': 'Запазване на промените...',
  'editTask.saveChanges': 'Запази промените',
  'editTask.cancelEdit': 'Отказ',
  'editTask.successMessage': 'Задачата е актуализирана успешно!',
  'editTask.errorMessage': 'Грешка при актуализиране на задачата. Моля, опитайте отново.',

  // Task Hints System
  'taskHints.noApplications.title': 'Все още няма кандидатури? Вашата задача е отворена от {{days}} дни',
  'taskHints.improveTask': 'Подобри задачата',
  'taskHints.dismiss': 'Затвори',
  'taskHints.suggestions.budgetLow': 'Бюджетът може да е твърде нисък (средно за тази категория: {{average}} лв)',
  'taskHints.suggestions.budgetVeryLow': 'Бюджетът е значително под средния ({{current}} лв срещу {{average}} лв средно)',
  'taskHints.suggestions.descriptionShort': 'Добавете повече детайли към описанието, за да привлечете специалисти',
  'taskHints.suggestions.locationMissing': 'Посочете точното си местоположение (град и квартал), за да помогнете на специалистите да ви намерят',
  'taskHints.suggestions.urgencyUnrealistic': 'Помислете за по-гъвкав краен срок, за да получите повече кандидатури',
};
