// Notifications, task detail, and posted tasks translations
export const notifications = {
  // Notifications
  'notifications.title': 'Известия',
  'notifications.refresh': 'Обнови',
  'notifications.cleanup': 'Изчисти',
  'notifications.markAsRead': 'Прочетено',
  'notifications.cleanupConfirm.title': 'Изтриване на всички известия?',
  'notifications.cleanupConfirm.message': 'Всички известия ще бъдат изтрити завинаги.',
  'notifications.cleanupConfirm.cancel': 'Отказ',
  'notifications.cleanupConfirm.confirm': 'Изтрий',
  'notifications.tabAll': 'Всички',
  'notifications.tabApplications': 'Кандидатури',
  'notifications.tabTasks': 'Задачи',
  'notifications.tabMessages': 'Съобщения',
  'notifications.empty.title': 'Все още няма известия',
  'notifications.empty.message': 'Ще получите известие когато някой кандидатства за вашите задачи или отговори на вашите кандидатури.',
  'notifications.empty.filterMessage': 'Няма известия в тази категория.',
  'notifications.emptyUnread.title': 'Вече сте наваксали!',
  'notifications.emptyUnread.message': 'Всички известия са прочетени.',
  'notifications.viewApplication': 'Към заявката',
  'notifications.viewMyWork': 'Моята работа',
  'notifications.viewTask': 'Към задачата',
  'notifications.justNow': 'Току-що',
  'notifications.getStarted': 'Започнете',
  'notifications.becomeProfessional': 'Стани професионалист',
  'notifications.createTask': 'Създай задача',
  'notifications.customerContact': 'Контактна информация на клиента',
  'notifications.customerMessage': 'Съобщение от клиента',

  // Notification Content (titles and messages)
  'notifications.content.welcome.title': 'Добре дошли в Trudify!',
  'notifications.content.welcome.message': 'Вашият акаунт беше създаден успешно. Започнете като публикувате задача или разгледате работни възможности!',
  'notifications.content.applicationReceived.title': 'Нова кандидатура',
  'notifications.content.applicationReceived.message': '{professionalName} кандидатства за вашата задача "{taskTitle}"',
  'notifications.content.applicationAccepted.title': 'Кандидатурата е приета! 🎉',
  'notifications.content.applicationAccepted.message': 'Вашата кандидатура за "{taskTitle}" беше приета от {customerName}',
  'notifications.content.applicationRejected.title': 'Актуализация на кандидатурата',
  'notifications.content.applicationRejected.message': 'Вашата кандидатура за "{taskTitle}" не беше избрана този път. Продължавайте да кандидатствате!',
  'notifications.content.taskCompleted.title': 'Задача завършена - Необходима е оценка ⭐',
  'notifications.content.taskCompleted.message': '"{taskTitle}" е завършена! Моля, отделете момент да оцените работата на {professionalName}.',
  'notifications.content.professionalWithdrew.title': 'Професионалистът се оттегли',
  'notifications.content.professionalWithdrew.message': '{professionalName} се оттегли от вашата задача "{taskTitle}". Задачата отново е отворена за нови кандидатури.',
  'notifications.content.removedByCustomer.title': 'Клиентът ви премахна от задачата',
  'notifications.content.removedByCustomer.message': 'Бяхте премахнат от задачата "{taskTitle}" от клиента.{customerFeedback}',
  'notifications.content.taskCancelled.title': 'Задачата е отменена',
  'notifications.content.taskCancelled.message': 'Задачата "{taskTitle}" беше отменена от клиента',
  'notifications.content.taskInvitation.title': 'Ново покана за задача',
  'notifications.content.taskInvitation.message': '{customerName} ви покани да кандидатствате за задачата "{taskTitle}"',

  // Telegram notification templates
  'notifications.telegram.viewHere': 'Вижте тук',
  'notifications.telegram.messageFrom': 'Съобщение от',
  'notifications.telegram.welcome': '👋 <b>Добре дошли в Trudify, {userName}!</b>\n\n🎉 Поздравления! Вашият акаунт беше създаден успешно.\n\n✅ Ще получавате моментални известия тук за:\n• Нови кандидатури за вашите задачи\n• Съобщения от професионалисти\n• Актуализации и завършвания на задачи\n\nЗапочнете сега:\n📝 Публикувайте задача или\n💼 Разгледайте работни възможности!',
  'notifications.telegram.applicationReceived': '✅ <b>Нова кандидатура!</b>\n\n<b>{professionalName}</b> кандидатства за вашата задача:\n"{taskTitle}"\n\n{link}',
  'notifications.telegram.applicationAccepted': '🎉 <b>Кандидатурата е приета!</b>\n\nВашата кандидатура за "{taskTitle}" беше приета от {customerName}!{customerMessageSection}\n\n<b>Информация за контакт:</b>\n{customerContact}\n\n{link}',
  'notifications.telegram.taskCompleted': '✅ <b>Задача завършена - Необходима е оценка!</b>\n\nВашата задача "<b>{taskTitle}</b>" беше завършена от {professionalName}.\n\n⭐ <b>Моля, оставете оценка</b>, за да помогнете на други да намерят добри професионалисти.\n\n{link}',
  'notifications.telegram.professionalWithdrew': '⚠️ <b>Професионалистът се оттегли</b>\n\n<b>{professionalName}</b> се оттегли от вашата задача:\n"{taskTitle}"\n\n📋 Задачата отново е <b>отворена</b> за нови кандидатури.\n\n👉 <b>Следващи стъпки:</b>\n• Прегледайте детайлите на задачата\n• Проверете дали бюджетът е конкурентен\n• Отговаряйте бързо на нови кандидатури\n\n🔗 Виж задачата: {link}',
  'notifications.telegram.removedByCustomer': '⚠️ <b>Клиентът ви премахна от задачата</b>\n\nБяхте премахнат от задачата:\n"<b>{taskTitle}</b>"{customerFeedback}\n\n📋 Задачата беше <b>отворена отново</b> за нови кандидатури.\n\n👉 <b>Следващи стъпки:</b>\n• Разгледайте други налични задачи\n• Кандидатствайте за задачи, които отговарят на вашите умения\n• Фокусирайте се върху изграждането на положителни клиентски отношения\n\n🔗 Разгледай задачи: {link}',
  'notifications.telegram.taskCancelled': '❌ <b>Задачата е отменена</b>\n\nЗадачата "{taskTitle}" беше отменена от клиента.\n\nВашата кандидатура и всички дискусии, свързани с тази задача, бяха премахнати.\n\n👉 <b>Следващи стъпки:</b>\n• Разгледайте други налични задачи\n• Кандидатствайте за задачи, които отговарят на вашите умения\n\n🔗 Разгледай задачи: {link}',
  'notifications.telegram.taskInvitation': '🎯 <b>Ново покана за задача!</b>\n\n<b>{customerName}</b> ви покани да кандидатствате за тяхната задача:\n\n📋 <b>{taskTitle}</b>\n🏷️ Категория: {taskCategory}\n\n👉 Вижте и кандидатствайте тук:\n{link}',

  // Task Detail
  'taskDetail.backToTasks': 'Обратно към задачите',
  'taskDetail.requirements': 'Изисквания:',
  'taskDetail.keyInformation': 'Ключова информация',
  'taskDetail.client': 'Автор на задачата',
  'taskDetail.loginForMore': 'Влезте за повече',
  'taskDetail.loginMessage':
    'Влезте в акаунта си за да видите пълната информация',
  'taskDetail.completedTasks': 'завършени задачи',
  'taskDetail.memberSince': 'Член от',
  'taskDetail.similarTasks': 'Подобни задачи',
  'taskDetail.apply': 'Кандидатствай за задачата',
  'taskDetail.askQuestion': 'Задай въпрос',
  'taskDetail.applicationsCount': 'души',
  'taskDetail.timeAgo': 'преди',
  'taskDetail.today': 'Днес',
  'taskDetail.tomorrow': 'Утре',
  'taskDetail.days': 'дни',
  'taskDetail.flexible': 'Гъвкав',
  'taskDetail.asap': 'Възможно най-скоро',
  'taskDetail.negotiable': 'По договаряне',
  'taskDetail.urgency.same_day': 'Спешно',
  'taskDetail.urgency.within_week': 'В рамките на седмица',
  'taskDetail.urgency.flexible': 'Гъвкав срок',
  'taskDetail.urgency.default': 'Неуточнен',
  'taskDetail.status': 'Статус',
  'taskDetail.statusTypes.vacant': 'Свободна',
  'taskDetail.statusTypes.applied': 'Кандидатствал',
  'taskDetail.statusTypes.inProgress': 'В изпълнение',
  'taskDetail.statusTypes.done': 'Завършена',
  'taskDetail.statusTypes.archived': 'Архивирана',
  'taskDetail.statusTypes.cancelled': 'Отменена',
  'taskDetail.appliedTooltip': 'Вие сте кандидатствали за тази задача. Клиентът може да приеме или отхвърли вашата кандидатура.',
  'taskDetail.inProgressBanner.title': 'Задачата вече не е налична',
  'taskDetail.inProgressBanner.message': 'Тази задача в момента се управлява от специалист и повече не приема кандидатури.',
  'taskDetail.published.today': 'публикувана днес',
  'taskDetail.published.thisWeek': 'публикувана тази седмица',
  'taskDetail.published.thisMonth': 'публикувана този месец',
  'taskDetail.published.someTimeAgo': 'публикувана отдавна',

  // Translation indicator
  'taskDetail.originallyWrittenIn': 'Първоначално написано на',

  'taskDetail.share': 'Сподели',
  'taskDetail.shareText': 'Вижте тази задача в Trudify',
  'taskDetail.shareSuccess': 'Споделено успешно!',
  'taskDetail.linkCopied': 'Връзката е копирана!',
  'taskDetail.copyError': 'Неуспешно копиране на връзката',
  'taskDetail.editTask': 'Редактирай задачата',
  'taskDetail.cancelTask': 'Отмени задачата',
  'taskDetail.confirmCancel': 'Сигурни ли сте, че искате да отмените тази задача?',
  'taskDetail.cancelSuccess': 'Задачата беше отменена успешно',
  'taskDetail.cancelError': 'Грешка при отмяна на задачата',
  'taskDetail.cancelDialog.title': 'Отменяте ли тази задача?',
  'taskDetail.cancelDialog.warning': 'Това действие е необратимо и ще:',
  'taskDetail.cancelDialog.consequence1': 'Изтрие всички кандидатури',
  'taskDetail.cancelDialog.consequence1NoApps': 'Премахне задачата (все още няма кандидатури)',
  'taskDetail.cancelDialog.consequence2': 'Премахне задачата от резултатите при търсене',
  'taskDetail.cancelDialog.consequence3': 'Изтрие всички данни за задачата завинаги',
  'taskDetail.cancelDialog.confirm': 'Сигурни ли сте, че искате да отмените тази задача?',
  'taskDetail.cancelDialog.btnCancel': 'Отказ',
  'taskDetail.cancelDialog.btnConfirm': 'Да, отмени задачата',
  'taskDetail.cancelDialog.processing': 'Отменя се...',
  'taskDetail.activity': 'Активност по задачата',
  'taskDetail.applications': 'Кандидатури',
  'taskDetail.questions': 'Въпроси',
  'taskDetail.accept': 'Приеми',
  'taskDetail.reject': 'Отхвърли',
  'taskDetail.message': 'Съобщение',
  'taskDetail.reply': 'Отговори',
  'taskDetail.yourReply': 'Вашия отговор:',
  'taskDetail.price': 'Цена',
  'taskDetail.timeline': 'Срок',
  'taskDetail.tasks': 'задачи',
  'taskDetail.cancel': 'Отмени',
  'taskDetail.writeReply': 'Напишете вашия отговор...',
  'taskDetail.sendReply': 'Изпрати отговор',

  // Language Info Banner (inline)
  'taskDetail.languageInfo': 'Авторът може да предпочита {language}',

  // Language Barrier Warning (deprecated - kept for reference)
  'taskDetail.languageWarning.title': 'Езикова бележка',
  'taskDetail.languageWarning.message': 'Тази задача е публикувана от някой, който може да предпочита комуникация на {language}. Моля, уверете се, че се чувствате комфортно с потенциални езикови различия преди да кандидатствате.',
  'taskDetail.languageWarning.confirm': 'Разбирам, продължи',
  'taskDetail.languageWarning.cancel': 'Отказ',

  // Ask Question Dialog
  'taskDetail.askQuestionDialog.title': 'Задайте въпрос',
  'taskDetail.askQuestionDialog.placeholder': 'Какво бихте искали да знаете за тази задача?',
  'taskDetail.askQuestionDialog.submit': 'Публикувай въпрос',
  'taskDetail.askQuestionDialog.characterCount': '{current}/{max} знака',
  'taskDetail.askQuestionDialog.minLength': 'Въпросът трябва да бъде поне {min} знака',
  'taskDetail.askQuestionDialog.maxLength': 'Въпросът трябва да бъде най-много {max} знака',

  // Questions Section
  'taskDetail.questions.empty.title': 'Все още няма въпроси',
  'taskDetail.questions.empty.message': 'Бъдете първият, който ще зададе въпрос относно тази задача!',
  'taskDetail.questions.unanswered': 'Без отговор',
  'taskDetail.questions.answered': 'Отговорено',
  'taskDetail.questions.loading': 'Зареждане на въпроси...',

  // Answer Dialog
  'taskDetail.answerDialog.title': 'Отговори на въпрос',
  'taskDetail.answerDialog.placeholder': 'Напишете вашия отговор...',

  // Success/Error Messages
  'taskDetail.questionPosted': 'Вашият въпрос беше публикуван успешно!',
  'taskDetail.questionError': 'Неуспешно публикуване на въпрос. Моля, опитайте отново.',
  'taskDetail.answerPosted': 'Вашият отговор беше публикуван успешно!',
  'taskDetail.answerError': 'Неуспешно публикуване на отговор. Моля, опитайте отново.',

  // Not Found Page
  'taskDetail.notFound.title': 'Задачата не е намерена',
  'taskDetail.notFound.description': 'Задачата, която търсите, не съществува или е премахната.',
  'taskDetail.notFound.browseTasks': 'Разгледай задачи',

  // Error Page
  'taskDetail.error.title': 'Нещо се обърка!',
  'taskDetail.error.description': 'Не успяхме да заредим тази задача. Това може да е временен проблем.',
  'taskDetail.error.retry': 'Опитай отново',
  'taskDetail.error.goHome': 'Към началото',
  'taskDetail.readMore': 'Прочетете още',
  'taskDetail.showLess': 'Покажи по-малко',

  // Posted Tasks Page (Customer View)
  'postedTasks.title': 'Моите публикувани задачи',
  'postedTasks.subtitle': 'Управлявайте задачите, които сте създали',
  'postedTasks.loading': 'Зареждане на вашите задачи...',
  'postedTasks.createTask': 'Създай задача',
  'postedTasks.filter.all': 'Всички',
  'postedTasks.filter.open': 'Отворени',
  'postedTasks.filter.inProgress': 'В процес',
  'postedTasks.filter.awaitingConfirmation': 'Очаква потвърждение',
  'postedTasks.filter.completed': 'Завършени',
  'postedTasks.filter.cancelled': 'Отменени',
  'postedTasks.applicationsCount': '{count} кандидатури',
  'postedTasks.viewApplications': 'Кандидатурите',
  'postedTasks.viewDetails': 'Детайли',
  'postedTasks.editTask': 'Редактирай',
  'postedTasks.acceptedProfessional': 'Приет специалист',
  'postedTasks.completedBy': 'Завършена от специалист',
  'postedTasks.awaitingYourConfirmation': 'Очаква вашето потвърждение',
  'postedTasks.markedComplete': 'маркира тази задача като завършена',
  'postedTasks.markComplete': 'Завърши',
  'postedTasks.reportIssue': 'Докладвай',
  'postedTasks.cancelTask': 'Откажи',
  'postedTasks.cancelTaskConfirm': 'Сигурни ли сте, че искате да откажете тази задача? Специалистът ще бъде уведомен.',
  'postedTasks.reopenTask': 'Отвори отново',
  'postedTasks.reopenTaskConfirm': 'Да се отвори отново тази задача? Ще можете да прегледате и редактирате детайлите преди повторно публикуване.',
  'postedTasks.empty.title': 'Имате идея? Нека я осъществим! 💡',
  'postedTasks.empty.description': 'Вашата табла със задачи е празна и готова за действие. От ремонти у дома до творчески проекти, специалистите чакат да помогнат.',
  'postedTasks.empty.subtext': 'Публикувайте първата си задача за по-малко от 2 минути. Безплатно е, лесно е и веднага ще започнете да получавате кандидатури!',
  'postedTasks.empty.createButton': 'Създай задача',
  'postedTasks.empty.hint': '✨ Съвет: Колкото повече детайли предоставите, толкова по-добри кандидатури ще получите',
  'postedTasks.firstApplication.title': 'Страхотни новини! Имате първа кандидатура',
  'postedTasks.firstApplication.message': 'Прегледайте детайлите на кандидатурата и отговорете на специалиста',

  // Cancel Task Dialog
  'cancelTask.title': 'Откажи задача',
  'cancelTask.professional': 'Специалист',
  'cancelTask.professionalNotification': 'Специалистът ще бъде уведомен за отказа',
  'cancelTask.reasonLabel': 'Защо отказвате тази задача?',
  'cancelTask.reasons.noShow': 'Специалистът не сеяви',
  'cancelTask.reasons.abandoned': 'Специалистът изостави работата',
  'cancelTask.reasons.unresponsive': 'Специалистът не отговаря',
  'cancelTask.reasons.changedRequirements': 'Изискванията ми се промениха',
  'cancelTask.reasons.foundAlternative': 'Намерих друго решение',
  'cancelTask.reasons.other': 'Друга причина',
  'cancelTask.descriptionLabel': 'Допълнителни детайли (по избор)',
  'cancelTask.descriptionPlaceholder': 'Моля, опишете какво се случи...',
  'cancelTask.descriptionHint': 'Помогнете ни да разберем ситуацията',
  'cancelTask.confirmButton': 'Откажи задача',
  'cancelTask.rateLimit.title': 'Можете да откажете още {remaining} задача/и този месец',
  'cancelTask.rateLimit.message': 'За предотвратяване на злоупотреби потребителите могат да отказват до {max} задачи месечно',
  'cancelTask.rateLimit.lastWarning': 'Това е последният ви безплатен отказ този месец. Използвайте го мъдро!',
  'cancelTask.limitExceeded.title': 'Достигнат месечен лимит на отказвания',
  'cancelTask.limitExceeded.message': 'Достигнахте лимита на отказвания за този месец. Честите отказвания могат да повлияят на репутацията на вашия акаунт. Моля, свържете се с поддръжката ако имате нужда от помощ.',

  // Customer Remove Professional Dialog
  'customerRemove.title': 'Премахване на специалист от задача',
  'customerRemove.subtitle': 'Премахване от: {taskTitle}',
  'customerRemove.professional': 'Специалист',
  'customerRemove.acceptedOn': 'Приет на',
  'customerRemove.workingFor': 'Работи от',
  'customerRemove.professionalNotification': 'Специалистът ще бъде уведомен и задачата ви ще бъде отворена отново за нови кандидатури',
  'customerRemove.taskWillReopen': 'Задачата ви ще бъде отворена отново за нови кандидатури',
  'customerRemove.limitWarning.title': 'Можете да премахнете още {remaining} специалист/и този месец',
  'customerRemove.limitWarning.message': 'Клиентите могат да премахват до 2 специалиста месечно.',
  'customerRemove.limitExceeded.title': 'Достигнат месечен лимит на премахвания',
  'customerRemove.limitExceeded.message': 'Достигнахте лимита на премахвания за този месец. Моля, свържете се с поддръжката ако имате сериозен проблем.',
  'customerRemove.feedbackLabel': 'Обратна връзка за специалиста (по избор)',
  'customerRemove.feedbackPlaceholder': 'Кажете му защо го премахвате от тази задача...',
  'customerRemove.feedbackHint': 'Това съобщение ще бъде включено в уведомлението до специалиста.',
  'customerRemove.confirmButton': 'Премахни специалист',
  'postedTasks.removeProfessional': 'Премахни',
  'postedTasks.removeProfessionalSuccess': 'Специалистът е премахнат. Задачата е отворена отново за нови кандидатури.',
  'postedTasks.cannotRemove': 'Не може да се премахне',
  'postedTasks.markCompleteSuccess': 'Задачата е маркирана като завършена успешно!',
  'postedTasks.markCompleteSuccessDescription': 'Специалистът е уведомен.',
  'postedTasks.markCompleteError': 'Грешка при маркиране на задачата като завършена',

  // Edit Task Page
  'editTask.title': 'Редактиране на задача',
  'editTask.subtitle': 'Актуализирайте детайлите на задачата, за да привлечете повече специалисти',
  'editTask.editingBanner': 'Редактиране: {title}',
  'editTask.editingSubtext': 'Направете промени, за да подобрите задачата си',
  'editTask.help': 'Нуждаете се от помощ? Свържете се с нашия екип за поддръжка',
  'editTask.freeToEdit': 'Безплатно редактиране',
  'editTask.noPayment': 'Без плащане докато работата не започне',
  'editTask.instantSave': 'Промените се запазват веднага',
  'editTask.prosWillSee': 'Специалистите ще видят актуализациите',
  'editTask.savingChanges': 'Запазване на промените...',
  'editTask.saveChanges': 'Запази промените',
  'editTask.cancelEdit': 'Отказ',
  'editTask.successMessage': 'Задачата е актуализирана успешно!',
  'editTask.errorMessage': 'Грешка при актуализиране на задачата. Моля, опитайте отново.',
  'editTask.cachingNotice': 'Забележка: Промените могат да отнемат до 1 час, за да се появят на публичната страница на задачата поради оптимизация на производителността.',
  'editTask.imageUpload.error': 'Качването на изображението е неуспешно',

  // Task Hints System
  'taskHints.noApplications.title': 'Все още няма кандидатури? Вашата задача е отворена от {days} дни',
  'taskHints.improveTask': 'Подобри задачата',
  'taskHints.dismiss': 'Затвори',
  'taskHints.suggestions.increasePrice': 'Опитайте да увеличите бюджета, за да привлечете повече специалисти',
  'taskHints.suggestions.addPhotos': 'Добавете или актуализирайте снимки, за да покажете по-добре какво трябва да се направи',
  'taskHints.suggestions.improveDescription': 'Добавете повече детайли към описанието, за да го направите по-ясно',
  'taskHints.suggestions.adjustDeadline': 'Помислете за по-гъвкав краен срок',
  'taskHints.suggestions.updateTask': 'Прегледайте и актуализирайте детайлите на задачата, за да я направите по-привлекателна',

  // Имейл нотификации
  // 1. Получена кандидатура
  'notifications.email.applicationReceived.subject': '{customer_name}, имате нова кандидатура!',
  'notifications.email.applicationReceived.heading': 'Получена нова кандидатура!',
  'notifications.email.applicationReceived.message': '{professional_name} кандидатства за вашата задача "{task_title}". Прегледайте профила, отзивите и предложението.',
  'notifications.email.applicationReceived.buttonText': 'Преглед на кандидатурата',
  'notifications.email.applicationReceived.secondaryButtonText': 'Преглед на профила',
  'notifications.email.applicationReceived.infoTitle': 'Детайли за кандидатурата:',
  'notifications.email.applicationReceived.footerText': 'Получавате този имейл, защото публикувахте задача в Trudify.',

  // 2. Приета кандидатура
  'notifications.email.applicationAccepted.subject': 'Вашата кандидатура беше приета!',
  'notifications.email.applicationAccepted.heading': 'Поздравления! Кандидатурата е приета',
  'notifications.email.applicationAccepted.message': 'Вашата кандидатура за "{task_title}" беше приета от {customer_name}!',
  'notifications.email.applicationAccepted.buttonText': 'Виж моята работа',
  'notifications.email.applicationAccepted.infoTitle': 'Информация за клиента:',
  'notifications.email.applicationAccepted.secondaryMessage': 'Започнете работа по задачата и поддържайте добра комуникация с клиента.',
  'notifications.email.applicationAccepted.footerText': 'Получавате този имейл, защото кандидатствахте за задача в Trudify.',
  'notifications.email.applicationAccepted.customerMessageLabel': 'Съобщение',
  'notifications.email.applicationAccepted.contactLabel': 'Контакт',

  // 3. Отхвърлена кандидатура
  'notifications.email.applicationRejected.subject': 'Актуализация на кандидатурата за «{task_title}»',
  'notifications.email.applicationRejected.heading': 'Кандидатурата не беше приета',
  'notifications.email.applicationRejected.message': 'Вашата кандидатура за "{task_title}" не беше приета този път. Не се притеснявайте! Продължете да кандидатствате за други възможности.',
  'notifications.email.applicationRejected.buttonText': 'Разгледай други задачи',
  'notifications.email.applicationRejected.secondaryMessage': 'Не забравяйте: Всяка кандидатура е учебен опит. Прегледайте обратната връзка и продължете да се подобрявате!',
  'notifications.email.applicationRejected.footerText': 'Получавате този имейл, защото кандидатствахте за задача в Trudify.',

  // 4. Получено съобщение
  'notifications.email.messageReceived.subject': 'Ново съобщение от {sender_name}',
  'notifications.email.messageReceived.heading': 'Имате ново съобщение',
  'notifications.email.messageReceived.message': '{sender_name} ви изпрати съобщение относно "{task_title}"',
  'notifications.email.messageReceived.buttonText': 'Преглед на съобщението',
  'notifications.email.messageReceived.infoTitle': 'Преглед на съобщението:',
  'notifications.email.messageReceived.secondaryMessage': 'Отговорете бързо, за да поддържате добра комуникация и доверие.',
  'notifications.email.messageReceived.footerText': 'Получавате този имейл, защото участвате в задача в Trudify.',

  // 5. Завършена задача
  'notifications.email.taskCompleted.subject': 'Завършена задача: «{task_title}»',
  'notifications.email.taskCompleted.heading': 'Задачата е завършена успешно!',
  'notifications.email.taskCompleted.message': 'Задачата "{task_title}" беше маркирана като завършена. Моля, оценете опита си и помогнете за изграждането на доверие в общността.',
  'notifications.email.taskCompleted.buttonText': 'Оставете отзив',
  'notifications.email.taskCompleted.secondaryMessage': 'Вашият отзив помага на другите потребители да намерят страхотни специалисти (или клиенти) и подобрява общността на Trudify.',
  'notifications.email.taskCompleted.footerText': 'Получавате този имейл, защото участвахте в задача в Trudify.',

  // 6. Приветствен имейл
  'notifications.email.welcome.subject': 'Добре дошли в Trudify, {user_name}!',
  'notifications.email.welcome.heading': 'Добре дошли в Trudify!',
  'notifications.email.welcome.message': 'Поздравления! Вашият акаунт беше създаден успешно.',
  'notifications.email.welcome.buttonText': 'Започнете',
  'notifications.email.welcome.infoTitle': 'Какво можете да правите в Trudify:',
  'notifications.email.welcome.secondaryMessage': 'Нуждаете се от помощ? Разгледайте нашите ръководства или се свържете с поддръжката.',
  'notifications.email.welcome.footerText': 'Получавате този имейл, защото създадохте акаунт в Trudify.',

  // 8. Премахнат от задача
  'notifications.email.removedFromTask.subject': 'Актуализация на задачата: «{task_title}»',
  'notifications.email.removedFromTask.heading': 'Бяхте премахнат от задача',
  'notifications.email.removedFromTask.message': 'Бяхте премахнат от задачата "{task_title}" от клиента.{customerFeedback} Задачата сега е отворена за други специалисти да кандидатстват.',
  'notifications.email.removedFromTask.buttonText': 'Разгледай други задачи',
  'notifications.email.removedFromTask.secondaryMessage': 'Това не засяга вашия рейтинг, освен ако няма проблеми с качеството или безопасността. Ако имате въпроси, моля свържете се с поддръжката.',
  'notifications.email.removedFromTask.footerText': 'Получавате този имейл, защото работихте по задача в Trudify.',
  'notifications.email.removedFromTask.feedbackLabel': 'Обратна връзка',

  // 9. Покана за задача
  'notifications.email.taskInvitation.subject': '{customer_name} ви покани за задача!',
  'notifications.email.taskInvitation.heading': 'Поканени сте за задача!',
  'notifications.email.taskInvitation.message': '{customer_name} ви покани да кандидатствате за тяхната задача в {task_category}.',
  'notifications.email.taskInvitation.buttonText': 'Преглед на задачата',
  'notifications.email.taskInvitation.infoTitle': 'Детайли за задачата:',
  'notifications.email.taskInvitation.secondaryMessage': 'Избрани сте въз основа на вашите умения и отзиви. Кандидатствайте сега, преди задачата да бъде попълнена!',
  'notifications.email.taskInvitation.footerText': 'Получавате този имейл, защото бяхте поканени да кандидатствате за задача в Trudify.',

  // Общи елементи за имейли
  'notifications.email.common.greeting': 'Здравейте',
  'notifications.email.common.footerRights': 'Всички права запазени.',
};
