// Professionals page and professional detail translations
export const professionals = {
  'professionals.hero.title': 'Намерете доверени професионалисти',
  'professionals.hero.subtitle':
    'Прегледайте верифицирани специалисти по категория и намерете перфектното съвпадение за вашите нужди',
  'professionals.hero.badge': 'Мрежа от професионалисти',
  'professionals.hero.stats.verified.value': 'Верифицирани професионалисти',
  'professionals.hero.stats.verified.label': 'Все повече всеки ден',
  'professionals.hero.stats.ratings.value': 'Доверено качество',
  'professionals.hero.stats.ratings.label': 'Базирано на истински рейтинги и отзиви',
  'professionals.hero.stats.jobs.value': 'Активна мрежа',
  'professionals.hero.stats.jobs.label': 'Много задачи всеки ден',
  'professionals.searchPlaceholder':
    'Търсете категории... (напр. ремонт, почистване, уроци)',
  'professionals.search.popular': 'Популярни',
  'professionals.allCategories': 'Всички категории',
  'professionals.featuredTitle': 'Препоръчани професионалисти',
  'professionals.viewProfile': 'Вижте профила',
  'professionals.viewProfessionals': 'Вижте професионалистите',
  'professionals.rating': 'Рейтинг',
  'professionals.completedJobs': 'Завършени задачи',
  'professionals.card.completedJobs': 'завършени задачи',
  'professionals.card.completedJobsShort': 'задачи',
  'professionals.card.lookingForFirstTask': 'Готов за първа задача',
  'professionals.card.waitingForReviews': 'Очаква първи отзиви',
  'professionals.startingFrom': 'Започва от',
  'professionals.noResults':
    'Няма категории, които да съвпадат с вашето търсене',
  'professionals.categoryResults': 'категории намерени',
  'professionals.filterBy': 'Филтрирай по',
  'professionals.location': 'Местоположение',
  'professionals.experience': 'Опит',
  'professionals.priceRange': 'Ценови диапазон',
  'professionals.availability': 'Наличност',
  'professionals.findPerfect': 'Намерете перфектния професионалист',
  'professionals.discoverTrusted':
    'Открийте доверени професионалисти с доказани резултати и отлични отзиви',
  'professionals.popularCategories': 'Популярни категории',
  'professionals.refineSearch': 'Прецизирайте резултатите от търсенето',
  'professionals.professionalsAvailable': 'достъпни професионалисти',
  'professionals.noProfessionalsFound': 'Не са намерени професионалисти',
  'professionals.tryAdjustingFilters': 'Опитайте да промените филтрите или термините за търсене, за да намерите повече професионалисти.',
  'professionals.noMatchingResults':
    'Няма професионалисти, които да отговарят на вашите критерии. Опитайте да разширите търсенето.',
  'professionals.mostActive': 'Най-активни',
  'professionals.specialists': 'Специалисти',
  'professionals.stars': 'звезди',
  'professionals.gender.male': 'Мъж',
  'professionals.gender.female': 'Жена',
  'professionals.filters.category': 'Категория',
  'professionals.filters.city': 'Град',
  'professionals.filters.location': 'Местоположение',
  'professionals.filters.minimumRating': 'Минимален рейтинг',
  'professionals.filters.minRating': 'Мин. рейтинг',
  'professionals.filters.minJobs': 'Мин. работи',
  'professionals.filters.jobs': 'работи',
  'professionals.filters.sortBy': 'Подреди по',
  'professionals.filters.genderPreference': 'Предпочитание по пол',
  'professionals.filters.activityLevel': 'Ниво на активност',
  'professionals.filters.all': 'Всички',
  'professionals.filters.topPerformersOnly': 'Само най-добрите',
  'professionals.filters.locationPlaceholder': 'София, Пловдив, Варна...',
  'professionals.filters.any': 'Всички',
  'professionals.filters.anyShort': 'Всички',
  'professionals.typing.plumber': 'водопроводчик в София',
  'professionals.typing.cleaner': 'специалист за почистване',
  'professionals.typing.electrician': 'сертифициран електрик',
  'professionals.typing.tutor': 'учител по английски',
  'professionals.typing.photographer': 'сватбен фотограф',
  'professionals.typing.handyman': 'майсторски услуги',
  'professionals.recommendedTitle': 'ПРЕПОРЪЧАНИ ПРОФЕСИОНАЛИСТИ',
  'professionals.filters.clear': 'Изчисти',
  'professionals.filters.clearAll': 'Изчисти всички филтри',
  'professionals.filters.fourPlusStars': '4+ звезди',
  'professionals.filters.fiveStarsOnly': 'Само 5 звезди',
  'professionals.filters.anyRating': 'По рейтинг',
  'professionals.filters.showProfessionalsWithAnyRating':
    'Покажи професионалисти с всякакъв рейтинг',
  'professionals.filters.locationPlaceholderDesktop': '📍 Местоположение',
  'professionals.sorting.featuredFirst': 'Топ избор',
  'professionals.sorting.featuredFirstDesc': 'Най-добрите профи',
  'professionals.sorting.highestRating': 'По рейтинг',
  'professionals.sorting.highestRatingDesc': 'С най-добри оценки',
  'professionals.sorting.mostExperience': 'По опит',
  'professionals.sorting.mostExperienceDesc': 'Много закази',
  'professionals.filters.sortResultsBy': 'Сортиране по',
  'professionals.filters.sortResultsTitle': 'Сортиране',
  'professionals.filters.sortResultsDescription':
    'Изберете как да подредите професионалистите',
  'professionals.filters.selectMinimumRating': 'Изберете минимален рейтинг',
  'professionals.filters.showingVerifiedFirst':
    'Показване на проверени топ професионалисти първо',
  'professionals.filters.proTip': 'Съвет',
  'professionals.filters.proTipMessage':
    'Опитайте "{{sortOption}}" за качествени професионалисти с проверени квалификации',
  'professionals.filters.sortingBy': 'Сортиране по {{option}}',
  'professionals.filters.sortingDescFeatured':
    'Показване на проверени топ професионалисти първо',
  'professionals.filters.sortingDescRating':
    'Професионалисти с най-висок рейтинг се показват първо',
  'professionals.filters.sortingDescJobs':
    'Най-опитните професионалисти се показват първо',
  'professionals.filters.activeFilters': 'Активни филтри',
  'professionals.filters.filterApplied': '{{count}} филтър приложен',
  'professionals.filters.filtersApplied': '{{count}} филтъра приложени',
  'professionals.filters.showProfessionalsWithRating':
    'Покажи професионалисти с {{rating}}+ звездни оценки',
  'professionals.filters.showPerfectRating':
    'Покажи само професионалисти с пърфектни 5-звездни оценки',

  // Results section
  'professionals.results.showing': 'Показване на {{count}} професионалисти',
  'professionals.results.loading': 'Зареждане на професионалисти...',
  'professionals.results.noResults.title': 'Не са намерени професионалисти',
  'professionals.results.noResults.description':
    'Опитайте да промените филтрите или да търсите в друг район',
  'professionals.results.noResults.clearFilters': 'Изчисти филтрите',
  'professionals.results.error.title': 'Опа! Нещо се обърка',
  'professionals.results.error.description': 'Сървърите ни имат нужда от почивка с кафе',
  'professionals.results.error.subtext': 'Не се притеснявайте, работим по проблема!',
  'professionals.results.error.retry': 'Опитай отново',
  'professionals.results.mockTitle': 'Примерни професионалисти (Референция)',
  'professionals.results.mockDescription':
    'Примерни данни, показващи бъдещи функции: портфолиа, сертификати, специални случаи',
  'professionals.results.mockBadge1': 'За разработка',
  'professionals.results.mockBadge2': 'Не са истински потребители',
  'professionals.results.featured.title': 'Препоръчани професионалисти',
  'professionals.results.featured.description':
    'Разгледайте тези най-високо оценени професионалисти от нашата мрежа',
  'professionals.results.allLoaded': 'Достигнахте края на списъка',
  'professionals.results.loadingMore': 'Зареждане на повече професионалисти...',

  // Pagination
  'professionals.pagination.previous': 'Предишна',
  'professionals.pagination.next': 'Следваща',
  'professionals.pagination.pageOf': 'Страница {{current}} от {{total}}',

  'professionalDetail.about': 'За професионалиста',
  'professionalDetail.reviews': 'отзива',
  'professionalDetail.online': 'Онлайн',
  'professionalDetail.offline': 'Видян наскоро',
  'professionalDetail.verified.phone': 'Телефон',
  'professionalDetail.verified.id': 'Документ',
  'professionalDetail.stats.completedTasks': 'Задачи',
  'professionalDetail.stats.yearsExperience': 'Години',
  'professionalDetail.stats.yearsExperienceLabel': 'години',
  'professionalDetail.stats.experience': 'Опит',
  'professionalDetail.stats.responseTime': 'Отговор',
  'professionalDetail.defaultBio': 'Професионален специалист с опит в сферата.',
  'professionalDetail.actions.inviteToApply': 'Покани да кандидатства',
  'professionalDetail.actions.contact': 'Контакт',
  'professionalDetail.actions.share': 'Сподели',
  'professionalDetail.contactHours': 'Достъпен',
  'professionalDetail.services.title': 'Услуги и цени',
  'professionalDetail.services.pricingNote.title': 'Информация за цените',
  'professionalDetail.services.pricingNote.description':
    'Окончателните цени се договарят индивидуално въз основа на сложността и изискванията на задачата.',
  'professionalDetail.portfolio.title': 'Моите примери',
  'professionalDetail.portfolio.noWork': 'Все още няма примери',
  'professionalDetail.portfolio.emptyState': 'Този професионалист все още не е качил своите примери. Питаме го редовно да ги добави - може би утре ще имаме късмет!',
  'professionalDetail.portfolio.emptyStateCTA': 'Проверете отново скоро за неговите удивителни работи',
  'professionalDetail.portfolio.before': 'Преди',
  'professionalDetail.portfolio.after': 'След',
  'professionalDetail.portfolio.viewMore': 'Виж всички примери',
  'professionalDetail.portfolio.showcase': 'Професионални примери от работата',
  'professionalDetail.completedTasks.title': 'Завършени задачи',
  'professionalDetail.completedTasks.noTasks': 'Все още няма завършени задачи',
  'professionalDetail.completedTasks.hugePotential': 'Този професионалист има огромен потенциал!',
  'professionalDetail.completedTasks.comingSoon': 'Страхотна работа предстои...',
  'professionalDetail.completedTasks.watchThisSpace': 'Следете това място за невероятни завършени проекти!',
  'professionalDetail.completedTasks.emptyState': 'Този професионалист е изпълнил много задачи, но все още не с нас. Моля, помогнете ни да обогатим тази страница с вашата задача!',
  'professionalDetail.completedTasks.emptyStateCTA': 'Предложете му задача и бъдете първият му клиент на нашата платформа',
  'professionalDetail.completedTasks.viewTask': 'Виж задачата',
  'professionalDetail.completedTasks.completedOn': 'Завършена на',
  'professionalDetail.reviews.title': 'Отзиви и оценки',
  'professionalDetail.reviews.count': 'отзива',
  'professionalDetail.reviews.recentRating': 'Скорошна оценка',
  'professionalDetail.reviews.excellent': 'Отлично',
  'professionalDetail.reviews.noReviews': 'Все още няма отзиви',
  'professionalDetail.reviews.beFirst':
    'Бъди първият, който ще даде отзив',
  'professionalDetail.reviews.emptyState': 'Отзивите за този професионалист предстоят. Предложете му задача, за да го оцените също!',
  'professionalDetail.reviews.emptyStateCTA': 'Бъдете първият, който ще работи с този професионалист и ще остави отзив',
  'professionalDetail.reviews.showMore': 'Покажи всички отзиви',
  'professionalDetail.reviews.allReviews': 'Всички отзиви',
  'professionalDetail.reviews.avgRating': 'Средна оценка',
  'professionalDetail.reviews.more': 'още',
  'professionalDetail.completedTasks.stats.tasksCompleted': 'Завършени задачи',
  'professionalDetail.completedTasks.stats.avgRating': 'Средна оценка',
  'professionalDetail.completedTasks.stats.fiveStarTasks': '5-звездни задачи',
  'professionalDetail.completedTasks.pendingReview': 'Чака ревю',
  'professionalDetail.completedTasks.viewAll': 'Виж всички {{count}} задачи',
  'professionalDetail.completedTasks.totalTasks': 'Общо задачи',
  'professionalDetail.completedTasks.averageRatingStars': 'Средна оценка: {{rating}} звезди',
  'professionalDetail.verified': 'Потвърден',
  'professionalDetail.shareText': 'Разгледайте този професионалист в Trudify',
  'professionalDetail.shareSuccess': 'Споделено успешно!',
  'professionalDetail.linkCopied': 'Връзката е копирана!',
  'professionalDetail.copyError': 'Неуспешно копиране на връзката',
  'professionals.filters.filtersButton': 'Филтри',
  'professionals.filters.active': 'активни',
  'professionals.filters.proTipText': 'Използвайте множество филтри, за да намерите перфектния професионалист. Винаги можете да ги нулирате!',
  'professionals.filters.showResults': 'Покажи резултати',
  'professionals.filters.reset': 'Нулирай',
  'professionals.filters.filters': 'Филтри',
};
