// Profile page translations - personal info, professional info, statistics, settings
export const profile = {
  'profile.title': 'Моят профил',
  'profile.customerProfileTitle': 'Информация за клиентски профил',
  'profile.professionalProfileTitle': 'Информация за професионален профил',
  'profile.personalInfo': 'Лична информация',
  'profile.professionalInfo': 'Професионална информация',
  'profile.verification': 'Верификация',
  'profile.reviews': 'Отзиви',
  'profile.stats': 'Статистика',

  'profile.form.firstName': 'Име',
  'profile.form.lastName': 'Фамилия',
  'profile.form.email': 'Имейл',
  'profile.form.phone': 'Телефон',
  'profile.form.location': 'Местоположение',
  'profile.form.bio': 'Биография',
  'profile.form.skills': 'Умения',
  'profile.form.experience': 'Години опит',
  'profile.form.hourlyRate': 'Часова ставка (лв.)',
  'profile.form.vatNumber': 'ДДС номер',
  'profile.form.businessName': 'Име на фирмата',
  'profile.form.website': 'Уебсайт',

  'profile.verification.identity': 'Верифицирана самоличност',
  'profile.verification.business': 'Верифициран бизнес',
  'profile.verification.phone': 'Верифициран телефон',
  'profile.verification.email': 'Верифициран имейл',

  // Email Verification
  'profile.verifyEmailPrompt': 'Потвърдете имейл адреса си',
  'profile.verifyEmailMessage': 'Получавайте важни актуализации за задачите и кандидатурите си. Имейл за потвърждение беше изпратен при регистрацията ви.',
  'profile.sendVerificationEmail': 'Изпрати имейл за потвърждение',
  'profile.sending': 'Изпращане...',

  // Profile Page
  'profile.completion': 'Довършване на профил',
  'profile.settings': 'Настройки',
  'profile.tabs.customer': 'Клиент',
  'profile.tabs.professional': 'Професионалист',
  'profile.switchToCustomer': 'Превключи към Клиентски профил',
  'profile.switchToProfessional': 'Превключи към Професионален профил',
  'profile.email': 'Имейл',
  'profile.phone': 'Телефон',
  'profile.location': 'Местоположение',
  'profile.selectCity': 'Изберете вашия град',
  'profile.memberSince': 'Член от',
  'profile.editPersonalInfo': 'Редактирай',
  'profile.statistics': 'Статистики',
  'profile.verified': 'Потвърден',
  'profile.completed': 'Завършено',
  'profile.active': 'Активно',

  // Avatar Upload
  'profile.avatar.changeAvatar': 'Промяна на аватар',
  'profile.avatar.selectImage': 'Избери изображение',
  'profile.avatar.remove': 'Премахни',
  'profile.avatar.supportedFormats': 'Поддържани формати: JPG, PNG, WebP (макс 2MB)',
  'profile.avatar.supportedFormatsExtended': 'Поддържани формати: JPG, PNG, WebP (авто-оптимизация)',
  'profile.avatar.invalidFileType': 'Невалиден тип файл. Моля изберете JPG, PNG или WebP изображение.',
  'profile.avatar.fileTooLarge': 'Файлът е твърде голям. Моля изберете изображение под 2MB.',
  'profile.avatar.fileTooLargeForCompression': 'Файлът е твърде голям. Максимум 20MB.',
  'profile.avatar.uploadError': 'Неуспешно качване на изображението. Моля опитайте отново.',
  'profile.avatar.deleteError': 'Неуспешно изтриване на аватара. Моля опитайте отново.',
  'profile.avatar.compressing': 'Оптимизиране...',
  'profile.avatar.optimizing': 'Оптимизиране на изображението',
  'profile.avatar.compressionError': 'Неуспешна оптимизация. Моля опитайте отново.',
  'profile.avatar.saved': 'спестени',

  // Statistics Modal
  'profile.statistics.title': 'Статистики на акаунта',
  'profile.statistics.description': 'Преглед на вашите метрики за производителност и обзор на активността',
  'profile.statistics.memberSince': 'Член от',

  // Customer Statistics
  'profile.statistics.customer.overview': 'Преглед на клиента',
  'profile.statistics.customer.performance': 'Метрики за производителност',
  'profile.statistics.customer.successRate': 'Процент на успех',
  'profile.statistics.customer.responseRate': 'Процент на отговор',
  'profile.statistics.customer.noStatsYet': 'Статистиката за задачите ще се появи тук, докато използвате платформата.',
  'profile.statistics.customer.tasksPosted': 'Публикувани задачи',
  'profile.statistics.customer.applicationsReceived': 'Получени заявки',
  'profile.statistics.customer.reviewsGiven': 'Дадени отзиви',

  // Professional Statistics
  'profile.statistics.professional.business': 'Бизнес преглед',
  'profile.statistics.professional.performance': 'Метрики за производителност',
  'profile.statistics.professional.repeatClients': 'Повторни клиенти',
  'profile.statistics.professional.monthlyEarnings': 'Месечни доходи',
  'profile.statistics.professional.activeJobs': 'Активни задачи',
  'profile.statistics.avgResponseTime': 'Сред. време за отговор',
  'profile.statistics.responseTime.minutes': '{{minutes}} мин',
  'profile.statistics.responseTime.hour': '1 час',
  'profile.statistics.responseTime.hours': '{{hours}} часа',
  'profile.professional.acceptanceRate': 'Приемане на задачи',

  // Quick Actions
  'profile.quickActions.createTask': 'Създай задача',

  // Customer Profile
  'profile.customer.personalInfo': 'Лична информация',
  'profile.customer.language': 'Език',
  'profile.customer.preferredContact': 'Предпочитан контакт',
  'profile.customer.preferredLanguage': 'Предпочитан език',
  'profile.customer.preferredContactMethod': 'Предпочитан начин на контакт',
  'profile.customer.statistics': 'Статистики',
  'profile.customer.tasksPosted': 'Публикувани задачи',
  'profile.customer.tasksCompleted': 'Завършени задачи',
  'profile.customer.averageRating': 'Средна оценка',
  'profile.customer.totalSpent': 'Общо похарчено',
  'profile.customer.recentActivity': 'Последна активност',
  'profile.customer.taskCompleted': 'Завършена задача',
  'profile.customer.taskPosted': 'Публикувана задача',
  'profile.customer.viewAllTasks': 'Виж всички задачи',
  'profile.customer.notificationPreferences': 'Настройки за известия',
  'profile.customer.smsNotifications': 'SMS известия',
  'profile.customer.smsNotificationsDesc': 'Получавайте важни актуализации чрез текстови съобщения',

  // Professional Profile
  'profile.professional.info': 'Професионална информация',
  'profile.professional.identitySection': 'Професионална идентичност',
  'profile.professional.title': 'Професионална титла',
  'profile.professional.bio': 'Биография',
  'profile.professional.yearsOfExperience': 'Години опит',
  'profile.professional.description': 'Описание',
  'profile.professional.hourlyRate': 'Часова ставка',
  'profile.professional.availability': 'Наличност',
  'profile.professional.availabilityPreferences': 'Наличност и предпочитания',
  'profile.professional.status': 'Статус',
  'profile.professional.languagesSpoken': 'Говорими езици',
  'profile.professional.noLanguagesSelected': 'Няма избрани езици',
  'profile.professional.skills': 'Умения',
  'profile.professional.statistics': 'Статистики за работа',
  'profile.professional.completedJobs': 'Завършени работи',
  'profile.professional.totalEarnings': 'Общи приходи',
  'profile.professional.responseTime': 'Време за отговор',
  'profile.professional.performance': 'Показатели за работа',
  'profile.professional.profileViews': 'Прегледи на профил',
  'profile.professional.completionRate': 'Процент на завършване',
  'profile.professional.monthlyGrowth': 'Месечен растеж',
  'profile.professional.recentWork': 'Последни работи',
  'profile.professional.viewPortfolio': 'Виж портфолио',
  'profile.professional.setupTitle': 'Настройте професионалния си профил',
  'profile.professional.setupDescription': 'Попълнете професионалния си профил, за да започнете да получавате възможности за работа и да се свързвате с клиенти.',
  'profile.professional.setupProfile': 'Настройте професионален профил',
  'profile.professional.businessSettings': 'Бизнес настройки',
  'profile.professional.paymentMethod': 'Метод на плащане',
  'profile.professional.vatNumber': 'ДДС номер',
  'profile.professional.serviceLocation': 'Местоположение на услугата',
  'profile.professional.setInPersonalInfo': 'Задава се в секция Лична информация',
  'profile.professional.editInPersonalInfo': 'Редактирай в секция Лична информация',
  'profile.professional.notSet': 'Не е зададено',
  'profile.professional.notVerified': 'Не е потвърдено',
  'profile.professional.titlePlaceholder': 'например: Професионално почистване и домашни услуги',
  'profile.professional.bioPlaceholder': 'Разкажете на клиентите за вашия опит, специализации и подход...',
  'profile.professional.setupFormDescription': 'Попълнете професионалната си информация, за да покажете уменията и опита си.',
  'profile.professional.selectCategories': 'Избери категории',
  'profile.professional.serviceCategories': 'Категории услуги',
  'profile.serviceCategories.saveCategories': 'Запази категориите',
  'profile.serviceCategories.searchPlaceholder': 'Търси категории...',
  'profile.serviceCategories.popularCategories': 'Популярни категории',
  'profile.serviceCategories.selected': 'Избрани',
  'profile.serviceCategories.clearAll': 'Изчисти всички',
  'profile.professional.verificationTrust': 'Верификация и доверие',
  'profile.professional.phoneVerification': 'Верификация на телефон',
  'profile.professional.phoneVerificationRequired': 'Задължително за всички професионалисти',
  'profile.professional.verified': 'Верифициран',
  'profile.professional.verifyPhone': 'Верифицирай телефон',
  'profile.professional.acceptedPaymentMethods': 'Приемани методи на плащане',
  'profile.professional.businessHours': 'Работно време',
  'profile.professional.businessHoursPlaceholder': 'например: Пон-Пет 8:00-18:00, Съб 9:00-14:00',
  'profile.professional.weekdaysLabel': 'Делнични дни (Пон-Пет)',
  'profile.professional.weekendLabel': 'Уикенд (Съб-Нед)',
  'profile.professional.startTime': 'Начален час',
  'profile.professional.endTime': 'Краен час',
  'profile.professional.noPaymentMethods': 'Няма избрани методи на плащане',
  'profile.professional.portfolioGallery': 'Портфолио галерия',
  'profile.professional.portfolioDescription': 'Покажете най-добрата си работа с преди/след снимки',
  'profile.professional.addServiceCategories': 'Добавете категории услуги',
  'profile.professional.categoriesHelp': 'Помогнете на клиентите да ви намерят! Изберете услугите, които предлагате, за да започнете да получавате заявки.',

  // Professional Profile Completion
  'profile.professional.incompleteTitle': 'Завършете професионалния си профил',
  'profile.professional.minimumRequired': 'Минимум изисквано',
  'profile.professional.titleField': 'Професионално заглавие',
  'profile.professional.recommended': 'Препоръчително',
  'profile.professional.recommendedFields': 'Категории (Услуги), Местоположение и Биография',

  // Professional Listing Banner
  'profile.listing.notListed': 'Профилът ви все още не е публикуван',
  'profile.listing.notListedMessage': 'Добавете професионално заглавие, за да се появите в нашето търсене и да получавате възможности за работа от клиенти.',
  'profile.listing.incomplete': 'Довършете профила си',
  'profile.listing.incompleteMessage': 'Попълнете липсващата информация, за да подобрите видимостта си и да привлечете повече клиенти.',
  'profile.listing.requirement.title': 'Професионално заглавие',
  'profile.listing.requirement.bio': 'Описание/Биография',
  'profile.listing.requirement.rate': 'Часова ставка',
  'profile.listing.requirement.skills': 'Категории услуги',
  'profile.listing.clickToFix': 'Натиснете за корекция',

  // Telegram Connection
  'profile.telegram.clickToConnect': 'Кликнете за свързване',

  // Professional Setup Form
  'profile.professional.form.titlePlaceholder': 'например: Full Stack Developer, UX Designer, Маркетинг консултант',
  'profile.professional.form.descriptionPlaceholder': 'Опишете професионалния си опит, експертиза и това, което ви прави уникални...',
  'profile.professional.form.experience': 'Ниво на опит',
  'profile.professional.form.portfolio': 'URL на портфолио (по избор)',
  'profile.professional.form.portfolioDescription': 'Линк към вашия уебсайт, GitHub или онлайн портфолио',
  'profile.professional.form.selectedSkills': 'Избрани умения',
  'profile.professional.form.searchSkills': 'Търсене на умения...',
  'profile.professional.form.suggestedSkills': 'Популярни умения',
  'profile.professional.form.addCustomSkill': 'Добавете персонализирано умение',
  'profile.professional.form.customSkillPlaceholder': 'Въведете име на умение',
  'profile.professional.form.moreSkillsAvailable': 'и още {{count}}...',
  'profile.professional.form.skillsLimitNotice': 'Препоръчваме да изберете топ 10 умения за най-добри резултати.',
  'profile.professional.form.submitting': 'Създаване на профил...',
  'profile.professional.form.createProfile': 'Създайте професионален профил',

  // Experience Options
  'profile.professional.form.experienceOptions.beginner': '0-1 години',
  'profile.professional.form.experienceOptions.intermediate': '2-5 години',
  'profile.professional.form.experienceOptions.experienced': '5-10 години',
  'profile.professional.form.experienceOptions.expert': '10+ години',

  // Availability Options
  'profile.professional.form.availabilityOptions.available': 'Наличен',
  'profile.professional.form.availabilityOptions.busy': 'Зает',
  'profile.professional.form.availabilityOptions.unavailable': 'Недостъпен',

  // Response Time Options
  'profile.professional.responseTime.1h': 'В рамките на 1 час',
  'profile.professional.responseTime.2h': 'В рамките на 2 часа',
  'profile.professional.responseTime.4h': 'В рамките на 4 часа',
  'profile.professional.responseTime.24h': 'В рамките на 24 часа',

  // Language Options
  'profile.professional.languages.bg': '🇧🇬 Български',
  'profile.professional.languages.ru': '🇷🇺 Руски',
  'profile.professional.languages.en': '🇬🇧 Английски',
  'profile.professional.languages.ua': '🇺🇦 Украински',

  // Payment Method Options
  'profile.professional.paymentMethods.cash': 'Кеш',
  'profile.professional.paymentMethods.card': 'Карта',
  'profile.professional.paymentMethods.bank_transfer': 'Банков превод',
  'profile.professional.paymentMethods.mobile_payment': 'Мобилно плащане',

  // Business Hours Labels
  'profile.professional.businessHours.weekdays': 'Пон-Пет',
  'profile.professional.businessHours.weekend': 'Съб-Нед',

  // Form Validation
  'profile.professional.form.validation.titleRequired': 'Професионалната титла е задължителна (минимум 3 символа)',
  'profile.professional.form.validation.descriptionRequired': 'Описанието е задължително (минимум 20 символа)',
  'profile.professional.form.validation.rateRequired': 'Часовата ставка трябва да е по-голяма от 0',
  'profile.professional.form.validation.skillsRequired': 'Моля, изберете поне едно умение',

  // Settings Modal
  'profile.settings.description': 'Управлявайте предпочитанията и настройките за поверителност на акаунта си',

  // Email Verification Banner
  'profile.email.promptTitle': 'Потвърдете вашия имейл!',
  'profile.email.promptDescription': 'Потвърдете вашия имейл адрес, за да получавате важни известия за вашите задачи, кандидатури и съобщения.',
  'profile.email.promptDescriptionSecurity': 'Потвърдете вашия имейл адрес за сигурност на акаунта и за да получавате важни актуализации за вашите задачи и кандидатури.',
  'profile.email.sendVerification': 'Изпрати имейл',
  'profile.email.verificationSent': 'Имейлът за потвърждение е изпратен! Проверете входящата си кутия.',
  'profile.email.verificationFailed': 'Неуспешно изпращане на имейл за потвърждение',
  'profile.email.checkInboxTitle': 'Проверете входящата си кутия!',
  'profile.email.checkInboxMessage': 'Изпратихме имейл за потвърждение във вашата входяща кутия. Моля, кликнете върху връзката в имейла, за да потвърдите адреса си.',
  'profile.email.checkSpam': 'Не сте го получили? Проверете папката си за спам или кликнете бутона по-долу, за да го изпратите отново.',

  // Telegram Connection
  'profile.telegramNotifications': 'Telegram Известия',
  'profile.telegramDescription': 'Свържете вашия Telegram акаунт за получаване на мигновени, безплатни известия',
  'profile.telegram.promptTitle': 'Получавайте мигновени известия!',
  'profile.telegram.promptDescription': 'Свържете вашия Telegram акаунт, за да получавате актуализации в реално време за вашите задачи, кандидатури и съобщения.',
  'profile.telegram.connectNow': 'Свържи Telegram',
  'profile.telegram.openTelegram': 'Отвори Telegram за свързване',
  'profile.connected': 'Свързан',
  'profile.notConnected': 'Не е свързан',
  'profile.connectedAs': 'Свързан като',
  'profile.benefits': 'Предимства',
  'profile.instantNotifications': 'Мигновени известия (без забавяне)',
  'profile.freeForever': 'Безплатно завинаги (без SMS разходи)',
  'profile.noEmailSpam': 'Без имейл спам',
  'profile.richMessages': 'Богати съобщения с бутони и връзки',
  'profile.connectTelegram': 'Свържи Telegram',
  'profile.disconnectTelegram': 'Прекъсни Telegram',
  'profile.telegramInstructions': 'Telegram ще се отвори в нов прозорец. Натиснете бутона в бот съобщението за завършване на свързването.',
  'profile.telegramConnectError': 'Неуспешно свързване с Telegram. Моля, опитайте отново.',
  'profile.telegramDisconnectConfirm': 'Сигурни ли сте, че искате да прекъснете Telegram? Няма да получавате повече мигновени известия.',
  'profile.telegramDisconnectError': 'Неуспешно прекъсване на Telegram. Моля, опитайте отново.',
  'profile.telegram.disconnectConfirmTitle': 'Прекъсване на Telegram?',
  'profile.telegram.disconnectConfirmMessage': 'Сигурни ли сте, че искате да спрете получаването на мигновени безплатни Telegram известия?',
  'profile.telegram.disconnectWarning': 'Ще загубите достъп до:',
  'profile.telegram.keepTelegram': 'Запази Telegram',
  'profile.telegram.disconnect': 'Прекъсни',
  'profile.telegram.steps': 'Следвайте тези стъпки',
  'profile.telegram.step1': 'Натиснете бутона по-долу, за да отворите Telegram бота',
  'profile.telegram.step2': 'Натиснете "Start" и копирайте вашия Telegram ID',
  'profile.telegram.step3': 'Поставете вашия Telegram ID по-долу',
  'profile.telegram.enterId': 'Въведете вашия Telegram ID',
  'profile.telegram.connect': 'Свържи',
  'profile.telegram.invalidIdFormat': 'Моля, въведете валиден Telegram ID (само цифри)',
  'profile.telegram.alreadyConnected': 'Този Telegram акаунт вече е свързан с друг Trudify профил. Моля, първо го прекъснете или използвайте друг Telegram акаунт.',
  'profile.telegram.openBot': 'Отвори Telegram бот',
  'profile.telegram.pasteAndConnect': 'Постави ID и свържи',
  'profile.telegram.connecting': 'Свързване...',
  'profile.telegram.autoSaveHint': 'Поставете ID тук - ще се свърже автоматично',
  'profile.telegram.clipboardError': 'Достъпът до клипборда е отказан. Моля, поставете ID ръчно.',
  'profile.telegram.toast.title': 'Свържете Telegram за мигновени известия',
  'profile.telegram.toast.description': 'Получавайте актуализации в реално време за вашите задачи, кандидатури и съобщения. Безплатно и винаги навреме!',
  'profile.telegram.toast.action': 'Свържи сега',

  'profile.settings.notifications': 'Известия',
  'profile.settings.emailNotifications': 'Имейл известия',
  'profile.settings.emailNotificationsDesc': 'Получавайте актуализации за задачите и акаунта си',
  'profile.settings.taskUpdates': 'Актуализации на задачи',
  'profile.settings.taskUpdatesDesc': 'Получавайте известия при актуализации на задачи',
  'profile.settings.marketingEmails': 'Маркетингови имейли',
  'profile.settings.marketingEmailsDesc': 'Получавайте съвети и промоционално съдържание',
  'profile.settings.pushNotifications': 'Push известия',
  'profile.settings.pushNotificationsDesc': 'Получавайте незабавни известия на устройството си',
  'profile.settings.weeklyDigest': 'Седмично обобщение',
  'profile.settings.weeklyDigestDesc': 'Получавайте седмично резюме на активността и възможностите си',
  'profile.settings.privacy': 'Поверителност',
  'profile.settings.profileVisibility': 'Видимост на профил',
  'profile.settings.profileVisibilityDesc': 'Направете профила си видим за потенциални клиенти',
  'profile.settings.showContactInfo': 'Показване на контактна информация',
  'profile.settings.showContactInfoDesc': 'Покажете контактната си информация публично',
  'profile.settings.interface': 'Интерфейс',
  'profile.settings.darkMode': 'Тъмен режим',
  'profile.settings.darkModeDesc': 'Превключете към интерфейс с тъмна тема',
  'profile.settings.dangerZone': 'Опасна зона',
  'profile.settings.deleteAccount': 'Изтриване на акаунт',
  'profile.settings.deleteAccountDesc': 'Окончателно изтриване на акаунта и всички данни',
  'profile.settings.deleteAccountConfirm': 'Изтриването на акаунт скоро ще бъде внедрено',

  // Customer Profile Form
  'profile.form.name': 'Пълно име',
  'profile.form.saving': 'Запазване...',
  'profile.form.validation.nameRequired': 'Името е задължително (минимум 2 символа)',
  'profile.form.validation.emailRequired': 'Имейлът е задължителен',
  'profile.form.validation.emailInvalid': 'Моля, въведете валиден имейл адрес',
  'profile.form.validation.phoneRequired': 'Телефонният номер е задължителен',
  'profile.form.validation.phoneInvalid': 'Въведете 8-9 цифри (напр. 88 123 4567)',
  'profile.form.phoneBulgarianOnly': 'Само български телефонни номера',
  'profile.form.validation.locationRequired': 'Местоположението е задължително (минимум 3 символа)',

  // Gallery (Premium Feature)
  'profile.gallery.title': 'Галерия с работи',
  'profile.gallery.description': 'Покажете най-добрите си работи (макс. 5 снимки)',
  'profile.gallery.addImage': 'Добави',
  'profile.gallery.captionPlaceholder': 'Описание (по избор)',
  'profile.gallery.helperText': 'Кликнете върху празните полета за качване на снимки. JPG, PNG или WEBP (макс. 5MB)',
  'profile.gallery.invalidType': 'Невалиден тип файл',
  'profile.gallery.useJpgPngWebp': 'Моля, използвайте JPG, PNG или WEBP',
  'profile.gallery.fileTooLarge': 'Файлът е твърде голям',
  'profile.gallery.maxSize': 'Максимум 5MB позволени',
  'profile.gallery.uploadSuccess': 'Снимката е качена',
  'profile.gallery.uploadError': 'Качването неуспешно',
  'profile.gallery.deleteSuccess': 'Снимката е изтрита',
  'profile.gallery.deleteError': 'Изтриването неуспешно',
  'profile.gallery.compressing': 'Оптимизиране...',
  'profile.gallery.uploading': 'Качване...',
  'profile.gallery.smaller': 'по-малък',

  // Services & Pricing
  'profile.services.title': 'Услуги и цени',
  'profile.services.description': 'Добавете услугите си с цени',
  'profile.services.empty': 'Все още няма добавени услуги',
  'profile.services.emptyHint': 'Добавете услугите си, за да знаят клиентите какво предлагате',
  'profile.services.addService': 'Добави услуга',
  'profile.services.serviceName': 'Име на услугата',
  'profile.services.serviceNamePlaceholder': 'напр. Водопроводен ремонт',
  'profile.services.price': 'Цена',
  'profile.services.pricePlaceholder': 'напр. 50 лв/час',
  'profile.services.descriptionLabel': 'Описание (по избор)',
  'profile.services.descriptionPlaceholder': 'Кратко описание на услугата',
  'profile.services.helperText': 'Добавете до {{max}} услуги. Промените се запазват автоматично.',

  // Achievement Banner
  'profile.achievement.title': 'Страхотна работа!',
  'profile.achievement.subtitle': 'Благодарим ви, че сте отличен член на нашата общност. Вашата упорита работа и отдаденост правят истинска разлика!',
  'profile.achievement.tasksCompleted': 'задачи',
};
