// Professionals page and professional detail translations
export const professionals = {
  'professionals.hero.title': 'Намерете доверени професионалисти',
  'professionals.hero.subtitle':
    'Прегледайте верифицирани специалисти по категория и намерете перфектното съвпадение за вашите нужди',
  'professionals.hero.badge': 'Мрежа от професионалисти',
  'professionals.searchPlaceholder':
    'Търсете категории... (напр. ремонт, почистване, уроци)',
  'professionals.allCategories': 'Всички категории',
  'professionals.featuredTitle': 'Препоръчани професионалисти',
  'professionals.viewProfile': 'Вижте профила',
  'professionals.rating': 'Рейтинг',
  'professionals.completedJobs': 'Завършени задачи',
  'professionals.startingFrom': 'Започва от',
  'professionals.noResults':
    'Няма категории, които да съвпадат с вашето търсене',
  'professionals.categoryResults': 'категории намерени',
  'professionals.filterBy': 'Филтрирай по',
  'professionals.location': 'Местоположение',
  'professionals.experience': 'Опит',
  'professionals.priceRange': 'Ценови диапазон',
  'professionals.availability': 'Наличност',
  'professionals.findPerfect': 'Намерете перфектния професионалист',
  'professionals.discoverTrusted':
    'Открийте доверени професионалисти с доказани резултати и отлични отзиви',
  'professionals.popularCategories': 'Популярни категории',
  'professionals.refineSearch': 'Прецизирайте резултатите от търсенето',
  'professionals.professionalsAvailable': 'достъпни професионалисти',
  'professionals.noProfessionalsFound': 'Не са намерени професионалисти',
  'professionals.tryAdjustingFilters': 'Опитайте да промените филтрите или термините за търсене, за да намерите повече професионалисти.',
  'professionals.noMatchingResults':
    'Няма професионалисти, които да отговарят на вашите критерии. Опитайте да разширите търсенето.',
  'professionals.mostActive': 'Най-активни',
  'professionals.specialists': 'Специалисти',
  'professionals.stars': 'звезди',
  'professionals.gender.male': 'Мъж',
  'professionals.gender.female': 'Жена',
  'professionals.filters.category': 'Категория',
  'professionals.filters.location': 'Местоположение',
  'professionals.filters.minimumRating': 'Минимален рейтинг',
  'professionals.filters.genderPreference': 'Предпочитание по пол',
  'professionals.filters.activityLevel': 'Ниво на активност',
  'professionals.filters.all': 'Всички',
  'professionals.filters.topPerformersOnly': 'Само най-добрите',
  'professionals.filters.locationPlaceholder': 'София, Пловдив, Варна...',
  'professionals.filters.any': 'Всички',
  'professionals.filters.anyShort': 'Всички',
  'professionals.typing.plumber': 'водопроводчик в София',
  'professionals.typing.cleaner': 'специалист за почистване',
  'professionals.typing.electrician': 'сертифициран електрик',
  'professionals.typing.tutor': 'учител по английски',
  'professionals.typing.photographer': 'сватбен фотограф',
  'professionals.typing.handyman': 'майсторски услуги',
  'professionals.recommendedTitle': 'ПРЕПОРЪЧАНИ ПРОФЕСИОНАЛИСТИ',
  'professionals.filters.clear': 'Изчисти',
  'professionals.filters.clearAll': 'Изчисти всички филтри',
  'professionals.filters.fourPlusStars': '4+ звезди',
  'professionals.filters.fiveStarsOnly': 'Само 5 звезди',
  'professionals.filters.anyRating': 'По рейтинг',
  'professionals.filters.showProfessionalsWithAnyRating':
    'Покажи професионалисти с всякакъв рейтинг',
  'professionals.filters.locationPlaceholderDesktop': '📍 Местоположение',
  'professionals.sorting.featuredFirst': 'Топ избор',
  'professionals.sorting.featuredFirstDesc': 'Най-добрите профи',
  'professionals.sorting.highestRating': 'По рейтинг',
  'professionals.sorting.highestRatingDesc': 'С най-добри оценки',
  'professionals.sorting.mostExperience': 'По опит',
  'professionals.sorting.mostExperienceDesc': 'Много закази',
  'professionals.filters.sortResultsBy': 'Сортиране по',
  'professionals.filters.sortResultsTitle': 'Сортиране',
  'professionals.filters.sortResultsDescription':
    'Изберете как да подредите професионалистите',
  'professionals.filters.selectMinimumRating': 'Изберете минимален рейтинг',
  'professionals.filters.showingVerifiedFirst':
    'Показване на проверени топ професионалисти първо',
  'professionals.filters.proTip': 'Съвет',
  'professionals.filters.proTipMessage':
    'Опитайте "{{sortOption}}" за качествени професионалисти с проверени квалификации',
  'professionals.filters.sortingBy': 'Сортиране по {{option}}',
  'professionals.filters.sortingDescFeatured':
    'Показване на проверени топ професионалисти първо',
  'professionals.filters.sortingDescRating':
    'Професионалисти с най-висок рейтинг се показват първо',
  'professionals.filters.sortingDescJobs':
    'Най-опитните професионалисти се показват първо',
  'professionals.filters.activeFilters': 'Активни филтри',
  'professionals.filters.filterApplied': '{{count}} филтър приложен',
  'professionals.filters.filtersApplied': '{{count}} филтъра приложени',
  'professionals.filters.showProfessionalsWithRating':
    'Покажи професионалисти с {{rating}}+ звездни оценки',
  'professionals.filters.showPerfectRating':
    'Покажи само професионалисти с пърфектни 5-звездни оценки',

  'professionalDetail.about': 'За професионалиста',
  'professionalDetail.reviews': 'отзива',
  'professionalDetail.online': 'Онлайн',
  'professionalDetail.offline': 'Видян наскоро',
  'professionalDetail.verified.phone': 'Телефон',
  'professionalDetail.verified.id': 'Документ',
  'professionalDetail.stats.completedTasks': 'Задачи',
  'professionalDetail.stats.yearsExperience': 'Години',
  'professionalDetail.stats.responseTime': 'Отговор',
  'professionalDetail.actions.inviteToApply': 'Покани да кандидатства',
  'professionalDetail.actions.contact': 'Контакт',
  'professionalDetail.actions.share': 'Сподели',
  'professionalDetail.contactHours': 'Достъпен',
  'professionalDetail.services.title': 'Услуги и цени',
  'professionalDetail.services.pricingNote.title': 'Информация за цените',
  'professionalDetail.services.pricingNote.description':
    'Окончателните цени се договарят индивидуално въз основа на сложността и изискванията на задачата.',
  'professionalDetail.portfolio.title': 'Моите примери',
  'professionalDetail.portfolio.noWork': 'Все още няма примери',
  'professionalDetail.portfolio.before': 'Преди',
  'professionalDetail.portfolio.after': 'След',
  'professionalDetail.portfolio.viewMore': 'Виж всички примери',
  'professionalDetail.portfolio.showcase': 'Професионални примери от работата',
  'professionalDetail.completedTasks.title': 'Завършени задачи',
  'professionalDetail.completedTasks.noTasks': 'Все още няма завършени задачи',
  'professionalDetail.completedTasks.hugePotential': 'Този професионалист има огромен потенциал!',
  'professionalDetail.completedTasks.comingSoon': 'Страхотна работа предстои...',
  'professionalDetail.completedTasks.watchThisSpace': 'Следете това място за невероятни завършени проекти!',
  'professionalDetail.completedTasks.viewTask': 'Виж задачата',
  'professionalDetail.completedTasks.completedOn': 'Завършена на',
  'professionalDetail.reviews.title': 'Отзиви и оценки',
  'professionalDetail.reviews.count': 'отзива',
  'professionalDetail.reviews.recentRating': 'Скорошна оценка',
  'professionalDetail.reviews.excellent': 'Отлично',
  'professionalDetail.reviews.noReviews': 'Все още няма отзиви',
  'professionalDetail.reviews.beFirst':
    'Бъди първият, който ще даде отзив',
  'professionalDetail.reviews.showMore': 'Покажи всички отзиви',
  'professionalDetail.reviews.allReviews': 'Всички отзиви',
  'professionalDetail.reviews.avgRating': 'Средна оценка',
  'professionalDetail.reviews.more': 'още',
  'professionalDetail.completedTasks.stats.tasksCompleted': 'Завършени задачи',
  'professionalDetail.completedTasks.stats.avgRating': 'Средна оценка',
  'professionalDetail.completedTasks.stats.fiveStarTasks': '5-звездни задачи',
  'professionalDetail.verified': 'Потвърден',
};
