// Profile page translations - personal info, professional info, statistics, settings
export const profile = {
  'profile.title': 'Моят профил',
  'profile.personalInfo': 'Лична информация',
  'profile.professionalInfo': 'Професионална информация',
  'profile.verification': 'Верификация',
  'profile.reviews': 'Отзиви',
  'profile.stats': 'Статистика',

  'profile.form.firstName': 'Име',
  'profile.form.lastName': 'Фамилия',
  'profile.form.email': 'Имейл',
  'profile.form.phone': 'Телефон',
  'profile.form.location': 'Местоположение',
  'profile.form.bio': 'Биография',
  'profile.form.skills': 'Умения',
  'profile.form.experience': 'Години опит',
  'profile.form.hourlyRate': 'Часова ставка (лв.)',
  'profile.form.vatNumber': 'ДДС номер',
  'profile.form.businessName': 'Име на фирмата',
  'profile.form.website': 'Уебсайт',

  'profile.verification.identity': 'Верифицирана самоличност',
  'profile.verification.business': 'Верифициран бизнес',
  'profile.verification.phone': 'Верифициран телефон',
  'profile.verification.email': 'Верифициран имейл',

  // Profile Page
  'profile.completion': 'Довършване на профил',
  'profile.settings': 'Настройки',
  'profile.tabs.customer': 'Клиент',
  'profile.tabs.professional': 'Професионалист',
  'profile.email': 'Имейл',
  'profile.phone': 'Телефон',
  'profile.location': 'Местоположение',
  'profile.memberSince': 'Член от',
  'profile.editPersonalInfo': 'Редактиране на лични данни',
  'profile.statistics': 'Статистики',
  'profile.verified': 'Потвърден',
  'profile.completed': 'Завършено',
  'profile.active': 'Активно',

  // Avatar Upload
  'profile.avatar.changeAvatar': 'Промяна на аватар',
  'profile.avatar.selectImage': 'Избери изображение',
  'profile.avatar.remove': 'Премахни',
  'profile.avatar.supportedFormats': 'Поддържани формати: JPG, PNG, WebP (макс 5MB)',
  'profile.avatar.invalidFileType': 'Невалиден тип файл. Моля изберете JPG, PNG или WebP изображение.',
  'profile.avatar.fileTooLarge': 'Файлът е твърде голям. Моля изберете изображение под 5MB.',
  'profile.avatar.uploadError': 'Неуспешно качване на изображението. Моля опитайте отново.',

  // Statistics Modal
  'profile.statistics.title': 'Статистики на акаунта',
  'profile.statistics.description': 'Преглед на вашите метрики за производителност и обзор на активността',
  'profile.statistics.memberSince': 'Член от',

  // Customer Statistics
  'profile.statistics.customer.overview': 'Преглед на клиента',
  'profile.statistics.customer.performance': 'Метрики за производителност',
  'profile.statistics.customer.successRate': 'Процент на успех',
  'profile.statistics.customer.responseRate': 'Процент на отговор',

  // Professional Statistics
  'profile.statistics.professional.business': 'Бизнес преглед',
  'profile.statistics.professional.performance': 'Метрики за производителност',
  'profile.statistics.professional.repeatClients': 'Повторни клиенти',
  'profile.statistics.professional.monthlyEarnings': 'Месечни доходи',

  // Customer Profile
  'profile.customer.personalInfo': 'Лична информация',
  'profile.customer.statistics': 'Статистики',
  'profile.customer.tasksPosted': 'Публикувани задачи',
  'profile.customer.tasksCompleted': 'Завършени задачи',
  'profile.customer.averageRating': 'Средна оценка',
  'profile.customer.totalSpent': 'Общо похарчено',
  'profile.customer.recentActivity': 'Последна активност',
  'profile.customer.taskCompleted': 'Завършена задача',
  'profile.customer.taskPosted': 'Публикувана задача',
  'profile.customer.viewAllTasks': 'Виж всички задачи',
  'profile.customer.notificationPreferences': 'Настройки за известия',
  'profile.customer.smsNotifications': 'SMS известия',
  'profile.customer.smsNotificationsDesc': 'Получавайте важни актуализации чрез текстови съобщения',

  // Professional Profile
  'profile.professional.info': 'Професионална информация',
  'profile.professional.title': 'Професионална титла',
  'profile.professional.description': 'Описание',
  'profile.professional.hourlyRate': 'Часова ставка',
  'profile.professional.availability': 'Наличност',
  'profile.professional.skills': 'Умения',
  'profile.professional.statistics': 'Статистики за работа',
  'profile.professional.completedJobs': 'Завършени работи',
  'profile.professional.totalEarnings': 'Общи приходи',
  'profile.professional.responseTime': 'Време за отговор',
  'profile.professional.performance': 'Показатели за работа',
  'profile.professional.profileViews': 'Прегледи на профил',
  'profile.professional.completionRate': 'Процент на завършване',
  'profile.professional.monthlyGrowth': 'Месечен растеж',
  'profile.professional.recentWork': 'Последни работи',
  'profile.professional.viewPortfolio': 'Виж портфолио',
  'profile.professional.setupTitle': 'Настройте професионалния си профил',
  'profile.professional.setupDescription': 'Попълнете професионалния си профил, за да започнете да получавате възможности за работа и да се свързвате с клиенти.',
  'profile.professional.setupProfile': 'Настройте професионален профил',
  'profile.professional.businessSettings': 'Бизнес настройки',
  'profile.professional.paymentMethod': 'Метод на плащане',
  'profile.professional.vatNumber': 'ДДС номер',
  'profile.professional.serviceArea': 'Обслужвана област',
  'profile.professional.setupFormDescription': 'Попълнете професионалната си информация, за да покажете уменията и опита си.',
  'profile.professional.selectCategories': 'Избери категории',
  'profile.professional.serviceCategories': 'Категории услуги',
  'profile.professional.verificationTrust': 'Верификация и доверие',
  'profile.professional.phoneVerification': 'Верификация на телефон',
  'profile.professional.phoneVerificationRequired': 'Задължително за всички професионалисти',
  'profile.professional.verified': 'Верифициран',
  'profile.professional.verifyPhone': 'Верифицирай телефон',
  'profile.professional.acceptedPaymentMethods': 'Приемани методи на плащане',
  'profile.professional.businessHours': 'Работно време',
  'profile.professional.businessHoursPlaceholder': 'например: Пон-Пет 8:00-18:00, Съб 9:00-14:00',
  'profile.professional.weekdaysLabel': 'Делнични дни (Пон-Пет)',
  'profile.professional.weekendLabel': 'Уикенд (Съб-Нед)',
  'profile.professional.startTime': 'Начален час',
  'profile.professional.endTime': 'Краен час',
  'profile.professional.noPaymentMethods': 'Няма избрани методи на плащане',
  'profile.professional.portfolioGallery': 'Портфолио галерия',
  'profile.professional.portfolioDescription': 'Покажете най-добрата си работа с преди/след снимки',
  'profile.professional.addServiceCategories': 'Добавете категории услуги',
  'profile.professional.categoriesHelp': 'Помогнете на клиентите да ви намерят! Изберете услугите, които предлагате, за да започнете да получавате заявки.',

  // Professional Setup Form
  'profile.professional.form.titlePlaceholder': 'например: Full Stack Developer, UX Designer, Маркетинг консултант',
  'profile.professional.form.descriptionPlaceholder': 'Опишете професионалния си опит, експертиза и това, което ви прави уникални...',
  'profile.professional.form.experience': 'Ниво на опит',
  'profile.professional.form.portfolio': 'URL на портфолио (по избор)',
  'profile.professional.form.portfolioDescription': 'Линк към вашия уебсайт, GitHub или онлайн портфолио',
  'profile.professional.form.selectedSkills': 'Избрани умения',
  'profile.professional.form.searchSkills': 'Търсене на умения...',
  'profile.professional.form.suggestedSkills': 'Популярни умения',
  'profile.professional.form.addCustomSkill': 'Добавете персонализирано умение',
  'profile.professional.form.customSkillPlaceholder': 'Въведете име на умение',
  'profile.professional.form.moreSkillsAvailable': 'и още {{count}}...',
  'profile.professional.form.skillsLimitNotice': 'Препоръчваме да изберете топ 10 умения за най-добри резултати.',
  'profile.professional.form.submitting': 'Създаване на профил...',
  'profile.professional.form.createProfile': 'Създайте професионален профил',

  // Experience Options
  'profile.professional.form.experienceOptions.beginner': '0-1 години',
  'profile.professional.form.experienceOptions.intermediate': '2-5 години',
  'profile.professional.form.experienceOptions.experienced': '5-10 години',
  'profile.professional.form.experienceOptions.expert': '10+ години',

  // Availability Options
  'profile.professional.form.availabilityOptions.available': 'Наличен',
  'profile.professional.form.availabilityOptions.busy': 'Зает',
  'profile.professional.form.availabilityOptions.unavailable': 'Недостъпен',

  // Form Validation
  'profile.professional.form.validation.titleRequired': 'Професионалната титла е задължителна (минимум 3 символа)',
  'profile.professional.form.validation.descriptionRequired': 'Описанието е задължително (минимум 20 символа)',
  'profile.professional.form.validation.rateRequired': 'Часовата ставка трябва да е по-голяма от 0',
  'profile.professional.form.validation.skillsRequired': 'Моля, изберете поне едно умение',

  // Settings Modal
  'profile.settings.description': 'Управлявайте предпочитанията и настройките за поверителност на акаунта си',
  'profile.settings.notifications': 'Известия',
  'profile.settings.emailNotifications': 'Имейл известия',
  'profile.settings.emailNotificationsDesc': 'Получавайте актуализации за задачите и акаунта си',
  'profile.settings.taskUpdates': 'Актуализации на задачи',
  'profile.settings.taskUpdatesDesc': 'Получавайте известия при актуализации на задачи',
  'profile.settings.marketingEmails': 'Маркетингови имейли',
  'profile.settings.marketingEmailsDesc': 'Получавайте съвети и промоционално съдържание',
  'profile.settings.pushNotifications': 'Push известия',
  'profile.settings.pushNotificationsDesc': 'Получавайте незабавни известия на устройството си',
  'profile.settings.weeklyDigest': 'Седмично обобщение',
  'profile.settings.weeklyDigestDesc': 'Получавайте седмично резюме на активността и възможностите си',
  'profile.settings.privacy': 'Поверителност',
  'profile.settings.profileVisibility': 'Видимост на профил',
  'profile.settings.profileVisibilityDesc': 'Направете профила си видим за потенциални клиенти',
  'profile.settings.showContactInfo': 'Показване на контактна информация',
  'profile.settings.showContactInfoDesc': 'Покажете контактната си информация публично',
  'profile.settings.interface': 'Интерфейс',
  'profile.settings.darkMode': 'Тъмен режим',
  'profile.settings.darkModeDesc': 'Превключете към интерфейс с тъмна тема',
  'profile.settings.dangerZone': 'Опасна зона',
  'profile.settings.deleteAccount': 'Изтриване на акаунт',
  'profile.settings.deleteAccountDesc': 'Окончателно изтриване на акаунта и всички данни',
  'profile.settings.deleteAccountConfirm': 'Изтриването на акаунт скоро ще бъде внедрено',

  // Customer Profile Form
  'profile.form.name': 'Пълно име',
  'profile.form.saving': 'Запазване...',
  'profile.form.validation.nameRequired': 'Името е задължително (минимум 2 символа)',
  'profile.form.validation.emailRequired': 'Имейлът е задължителен',
  'profile.form.validation.emailInvalid': 'Моля, въведете валиден имейл адрес',
  'profile.form.validation.phoneRequired': 'Телефонният номер е задължителен',
  'profile.form.validation.phoneInvalid': 'Моля, въведете валиден телефонен номер',
  'profile.form.validation.locationRequired': 'Местоположението е задължително (минимум 3 символа)',
};
