// Task-related translations - browsing, creating, task cards, task detail
export const tasks = {
  'tasks.title': 'Разглеждане на задачи',
  'tasks.subtitle':
    'Намерете перфектната задача, която отговаря на вашите умения и интереси',
  'tasks.searchPlaceholder':
    'Търсете задачи по ключови думи, категории или местоположение...',
  'tasks.filters.title': 'Филтри',
  'tasks.filters.category': 'Категория',
  'tasks.filters.allCategories': 'Всички категории',
  'tasks.filters.location': 'Местоположение',
  'tasks.filters.budget': 'Бюджет',
  'tasks.filters.budgetMin': 'Мин. бюджет',
  'tasks.filters.budgetMax': 'Макс. бюджет',
  'tasks.filters.deadline': 'Краен срок',
  'tasks.filters.status': 'Статус',
  'tasks.filters.all': 'Всички',
  'tasks.filters.open': 'Отворени',
  'tasks.filters.inProgress': 'В ход',
  'tasks.filters.completed': 'Завършени',
  'tasks.filters.activeFilters': 'Активни филтри',
  'tasks.filters.clearAll': 'Изчисти всички',
  'tasks.results': 'резултата',
  'tasks.sort.newest': 'Най-нови първо',
  'tasks.sort.oldest': 'Най-стари първо',
  'tasks.sort.budgetHigh': 'Най-висок бюджет',
  'tasks.sort.budgetLow': 'Най-нисък бюджет',
  'tasks.sort.deadline': 'По краен срок',

  'browseTasks.hero.badge': 'Открийте перфектните професионалисти',
  'browseTasks.hero.title1': 'Намерете идеалната',
  'browseTasks.hero.title2': 'задача за вас',
  'browseTasks.hero.subtitle':
    'Разгледайте стотици възможности от проверени клиенти. Започнете работа още днес.',
  'browseTasks.search.placeholder':
    'Търсете задачи по ключови думи, категория или град...',
  'browseTasks.search.popular': 'Популярни',
  'browseTasks.search.searchingCategories': 'Търсене на категории...',
  'browseTasks.search.suggestedCategories': 'Предложени категории',
  'browseTasks.search.categories': 'Категории',
  'browseTasks.search.cities': 'Градове',
  'browseTasks.filters.title': 'Филтриране и сортиране',
  'browseTasks.filters.advanced': 'Разширени филтри',
  'browseTasks.filters.quick': 'Бърз филтър',
  'browseTasks.filters.searchPlaceholder':
    'Търсете задачи... (напр. почистване, ремонт, доставка)',
  'browseTasks.filters.category': 'Категория',
  'browseTasks.filters.allCategories': 'Всички категории',
  'browseTasks.filters.city': 'Град',
  'browseTasks.filters.allCities': 'Всички градове',
  'browseTasks.filters.cities.sofia': 'София',
  'browseTasks.filters.cities.plovdiv': 'Пловдив',
  'browseTasks.filters.cities.varna': 'Варна',
  'browseTasks.filters.cities.burgas': 'Бургас',
  'browseTasks.filters.budget': 'Бюджет',
  'browseTasks.filters.budgetMin': 'Мин',
  'browseTasks.filters.budgetMax': 'Макс',
  'browseTasks.filters.budgetUpTo': 'До 500 лв',
  'browseTasks.filters.sortBy': 'Сортиране',
  'browseTasks.filters.sort.newest': 'Най-нови',
  'browseTasks.filters.sort.oldest': 'Най-стари',
  'browseTasks.filters.sort.highBudget': 'Висок бюджет',
  'browseTasks.filters.sort.lowBudget': 'Нисък бюджет',
  'browseTasks.filters.filters': 'Филтри',
  'browseTasks.filters.active': 'активни',
  'browseTasks.filters.reset': 'Нулиране',
  'browseTasks.filters.showResults': 'Покажи резултати',
  'browseTasks.filters.clear': 'Изчисти',
  'browseTasks.filters.customRange': 'Персонализиран диапазон',
  'browseTasks.filters.min': 'Мин',
  'browseTasks.filters.max': 'Макс',
  'browseTasks.filters.apply': 'Приложи',
  'browseTasks.filters.urgency': 'Спешност',
  'browseTasks.filters.urgentSameDay': 'Спешно (Същия ден)',
  'browseTasks.filters.thisWeek': 'Тази седмица',
  'browseTasks.filters.flexible': 'Гъвкаво',
  'browseTasks.filters.searchCity': 'Търси град...',
  'browseTasks.filters.noCitiesFound': 'Няма намерени градове',
  'browseTasks.filters.searchCategory': 'Търси категории...',
  'browseTasks.filters.noCategoriesFound': 'Няма намерени категории',
  'browseTasks.filters.activeFilters': 'Активни филтри',
  'browseTasks.filters.clearAll': 'Изчисти всички',
  'browseTasks.sort.newest': 'Най-нови първо',
  'browseTasks.sort.urgent': 'Спешни първо',
  'browseTasks.sort.budgetHigh': 'Най-висок бюджет',
  'browseTasks.sort.budgetLow': 'Най-нисък бюджет',
  'browseTasks.sort.deadline': 'Приключващи скоро',
  'browseTasks.results.shown': 'Показани {{count}} резултата',
  'browseTasks.results.featured': 'Показани {{count}} популярни задачи',
  'browseTasks.results.loading': 'Зареждане...',
  'browseTasks.results.noTasks.title': 'Няма намерени задачи',
  'browseTasks.results.noTasks.description':
    'Опитайте да промените филтрите или да търсите по различни критерии.',
  'browseTasks.results.noTasks.clearFilters': 'Изчисти филтрите',
  'browseTasks.results.suggestedTasks':
    'Популярни задачи, които може да ви харесат',
  'browseTasks.results.suggestedDescription':
    'Ето някои популярни задачи от нашата общност',
  'browseTasks.results.featuredTasks': 'Препоръчани задачи',
  'browseTasks.results.featuredDescription':
    'Разгледайте тези популярни задачи от нашата общност',
  'browseTasks.results.error.title': 'Опа! Нашите сървъри си взеха кафе пауза ☕',
  'browseTasks.results.error.description':
    'Изглежда хомстерите спряха да тичат на колелата си. Не се притеснявайте, даваме им еспресо шотове!',
  'browseTasks.results.error.subtext':
    'Обикновено се оправя по-бързо, отколкото можете да кажете "капучино"',
  'browseTasks.results.error.retry': 'Опитай отново',
  'browseTasks.pagination.previous': 'Предишна',
  'browseTasks.pagination.next': 'Следваща',
  'browseTasks.search.tags.programming': 'Програмиране',
  'browseTasks.search.tags.design': 'Дизайн',
  'browseTasks.search.tags.marketing': 'Маркетинг',
  'browseTasks.search.tags.translation': 'Преводи',
  'browseTasks.search.tags.photography': 'Фотография',
  'browseTasks.typing.plumber': 'водопроводчик в София',
  'browseTasks.typing.cleaner': 'почистване на къща',
  'browseTasks.typing.electrician': 'ремонт електричество',
  'browseTasks.typing.tutor': 'учител по английски',
  'browseTasks.typing.moving': 'преместване мебели',
  'browseTasks.typing.gardener': 'поддръжка на градина',

  'task.budget': 'Бюджет',
  'task.location': 'Местоположение',
  'task.category': 'Категория',
  'task.applications': 'Заявления',
  'task.viewDetails': 'Вижте детайли',
  'task.apply': 'Кандидатствайте сега',
  'task.created': 'Създадена',
  'task.deadline': 'Краен срок',

  // Create Task Form
  'createTask.title': 'Публикувайте нова задача',
  'createTask.hero.subtitle': 'Опишете какво ви трябва и нека професионалистите дойдат при вас',
  'createTask.hero.freeToPost': 'Безплатна публикация',
  'createTask.hero.noPayment': 'Без плащане до започване на работа',
  'createTask.hero.avgResponse': 'Средно време за отговор: 2 часа',
  'createTask.hero.verifiedPros': 'Проверени специалисти',
  'createTask.hero.help': 'Нуждаете се от помощ? Свържете се с нашия екип за поддръжка',

  // Category Section
  'createTask.category.title': 'Каква услуга ви трябва?',
  'createTask.category.subtitle': 'Изберете категория, която най-добре описва вашата задача',
  'createTask.category.selectSubcategory': 'Изберете конкретна услуга',
  'createTask.category.backToMain': 'Обратно към основни категории',
  'createTask.category.selected': 'Избрана услуга',
  'createTask.category.categorySelected': 'Избрана категория. Натиснете X, за да промените.',
  'createTask.category.tryDifferent': 'Опитайте с различна търсачка',

  // Details Section
  'createTask.details.title': 'Опишете вашата задача',
  'createTask.details.subtitle': 'Предоставете ясна информация, за да привлечете правилните професионалисти',
  'createTask.details.titleLabel': 'Заглавие на задачата',
  'createTask.details.titlePlaceholder': 'От какво се нуждаете?',
  'createTask.details.titleHelp': 'Бъдете конкретни и ясни (например "Професионално почистване на 2-стаен апартамент")',
  'createTask.details.descriptionLabel': 'Описание',
  'createTask.details.descriptionPlaceholder': 'Опишете задачата си подробно...',
  'createTask.details.descriptionHelp': 'Включете всички важни детайли: какво трябва да бъде направено, специални изисквания, необходими инструменти/материали и т.н.',
  'createTask.details.requirementsLabel': 'Специфични изисквания (по избор)',
  'createTask.details.requirementsPlaceholder': '• Изискване 1\n• Изискване 2\n• Изискване 3',
  'createTask.details.requirementsHelp': 'Изброете специални умения, сертификати или оборудване (по едно на ред)',

  // Location Section
  'createTask.location.title': 'Къде ще се изпълнява задачата?',
  'createTask.location.subtitle': 'Местоположението помага на професионалистите да разберат дали могат да ви обслужат',
  'createTask.location.cityLabel': 'Град',
  'createTask.location.cityPlaceholder': 'Изберете вашия град',
  'createTask.location.neighborhoodLabel': 'Квартал/Район',
  'createTask.location.neighborhoodPlaceholder': 'напр. Лозенец, Витоша, Център',
  'createTask.location.neighborhoodHelp': 'Помага на професионалистите да определят дали могат да ви достигнат',
  'createTask.location.addressLabel': 'Пълен адрес (по избор)',
  'createTask.location.addressPlaceholder': 'Улица, номер на сградата, вход, етаж, апартамент',
  'createTask.location.addressSecurity': 'Адресът ще бъде показан само на професионалиста, когото наемете',

  // Budget Section
  'createTask.budget.title': 'Какъв е вашият бюджет?',
  'createTask.budget.help': 'Честните бюджети получават 3 пъти повече кандидатури',
  'createTask.budget.typeFixed': 'Фиксирана цена',
  'createTask.budget.typeRange': 'Ценови диапазон',
  'createTask.budget.typeUnclear': 'Не съм сигурен за бюджета',
  'createTask.budget.fixedLabel': 'Вашият бюджет',
  'createTask.budget.minLabel': 'Минимум',
  'createTask.budget.maxLabel': 'Максимум',
  'createTask.budget.notSure': 'Не съм сигурен за бюджета',

  // Timeline Section
  'createTask.timeline.title': 'Кога ви трябва това?',
  'createTask.timeline.subtitle': 'Уведомете професионалистите за вашия график',
  'createTask.timeline.urgentTitle': 'Спешно - Същия ден',
  'createTask.timeline.urgentDesc': 'Трябва ми днес',
  'createTask.timeline.soonTitle': 'Скоро - В рамките на седмица',
  'createTask.timeline.soonDesc': 'Трябва ми в следващите 7 дни',
  'createTask.timeline.flexibleTitle': 'Гъвкав',
  'createTask.timeline.flexibleDesc': 'Гъвкав съм с времето',
  'createTask.timeline.deadlineLabel': 'Конкретен краен срок (по избор)',
  'createTask.timeline.deadlineHelp': 'Оставете празно, ако нямате конкретен краен срок',

  // Photos Section
  'createTask.photos.title': 'Добавете снимка (по избор)',
  'createTask.photos.help': 'Снимката помага на професионалистите да разберат по-добре задачата ви',
  'createTask.photos.dragDrop': 'Плъзнете и пуснете изображение тук',
  'createTask.photos.orBrowse': 'или кликнете за преглед',
  'createTask.photos.takePhoto': 'Направете снимка',
  'createTask.photos.maxSize': 'Максимум 5MB',
  'createTask.photos.formats': 'JPG, PNG, WebP',
  'createTask.photos.uploading': 'Качване на снимка...',
  'createTask.photos.fileTooLarge': 'Файлът е твърде голям. Максималният размер е 5MB',
  'createTask.photos.invalidType': 'Файлът не е поддържан формат на изображение',
  'createTask.photos.uploadError': 'Неуспешно качване на снимки. Моля, опитайте отново.',
  'createTask.photos.optimizing': 'Оптимизиране на изображението за по-бързо качване...',
  'createTask.photos.optimized': 'Изображението е оптимизирано успешно',
  'createTask.photos.smaller': 'по-малко',

  // Review Section
  'createTask.review.title': 'Прегледайте вашата задача',
  'createTask.review.subtitle': 'Уверете се, че всичко изглежда добре преди публикуване',
  'createTask.review.submit': 'Публикувай задачата',
  'createTask.review.location': 'Местоположение',
  'createTask.review.budget': 'Бюджет',
  'createTask.review.timeline': 'График',
  'createTask.review.requirements': 'Изисквания',
  'createTask.review.photos': 'Снимки',
  'createTask.review.noTitle': 'Все още няма заглавие',
  'createTask.review.noDescription': 'Все още няма описание',
  'createTask.review.noCity': 'Няма избран град',
  'createTask.review.fillRequired': 'Моля, попълнете всички задължителни полета за да публикувате',

  // Errors
  'createTask.errors.categoryRequired': 'Моля, изберете категория',
  'createTask.errors.titleTooShort': 'Заглавието трябва да бъде поне 10 символа',
  'createTask.errors.titleTooLong': 'Заглавието не може да бъде повече от 200 символа',
  'createTask.errors.descriptionTooShort': 'Описанието трябва да бъде поне 30 символа',
  'createTask.errors.descriptionTooLong': 'Описанието не може да бъде повече от 2000 символа',
  'createTask.errors.cityRequired': 'Градът е задължителен',
  'createTask.errors.budgetInvalid': 'Максимумът трябва да бъде по-голям от минимума',
  'createTask.errors.deadlineInPast': 'Крайният срок трябва да бъде днес или в бъдеще',

  'createTask.imageUpload.error': 'Неуспешно качване на изображението',

  // Success messages
  'createTask.success': 'Задачата е създадена успешно!',
  'createTask.successMessage': 'Вашата задача е публикувана и вече е видима за професионалистите.',
  'createTask.successWithoutImage': 'Вашата задача е публикувана без изображение. Можете да добавите или промените изображението чрез редактиране на задачата.',
  'createTask.error': 'Грешка при създаване на задача',
  'createTask.errorMessage': 'Моля, опитайте отново по-късно.',

  'taskCard.apply': 'Кандидатствай',
  'taskCard.seeDetails': 'Виж детайли',
  'taskCard.anonymous': 'Анонимен',
  'taskCard.budget.from': 'от',
  'taskCard.budget.to': 'до',
  'taskCard.budget.negotiable': 'За договаряне',
  'taskCard.budget.unclear': 'Неясен бюджет',
  'taskCard.deadline.flexible': 'Гъвкав',
  'taskCard.deadline.today': 'Днес',
  'taskCard.deadline.tomorrow': 'Утре',
  'taskCard.deadline.days': 'дни',
  'taskCard.category.home_repair': 'Домашни ремонти',
  'taskCard.category.delivery_transport': 'Доставки и транспорт',
  'taskCard.category.personal_care': 'Лична грижа',
  'taskCard.category.personal_assistant': 'Личен асистент',
  'taskCard.category.learning_fitness': 'Обучение и фитнес',
  'taskCard.category.other': 'Други',
  // Subcategories
  'taskCard.category.courier-services': 'Куриерски услуги',
  'taskCard.category.logistics': 'Логистика',
  'taskCard.category.handyman': 'Майстор',
  'taskCard.category.plumbing': 'Водопровод',
  'taskCard.category.electrical': 'Електричество',
  'taskCard.category.cleaning-services': 'Почистване',
  'taskCard.category.house-cleaning': 'Почистване на дома',
};
