const bg = {
  // Common
  welcome: 'Добре дошли',
  login: 'Вход',
  logout: 'Изход',
  signup: 'Регистрация',
  search: 'Търсене',
  browse: 'Разглеждане',
  create: 'Създаване',
  edit: 'Редактиране',
  delete: 'Изтриване',
  cancel: 'Отказ',
  save: 'Запазване',
  submit: 'Изпращане',
  loading: 'Зареждане...',
  error: 'Грешка',
  success: 'Успех',
  back: 'Назад',
  next: 'Напред',
  previous: 'Предишна',
  home: 'Начало',
  profile: 'Профил',
  settings: 'Настройки',

  // Navigation
  'nav.home': 'Начало',
  'nav.browseTasks': 'Задачи',
  'nav.createTask': 'Създай',
  'nav.profile': 'Профил',
  'nav.howItWorks': 'Как работи',
  'nav.categories': 'Категории',
  'nav.forProfessionals': 'Професионалисти',
  'nav.myTasks': 'Моите задачи',
  'nav.help': 'Помощ',

  // Landing Page
  'landing.hero.title': 'Намерете доверени местни професионалисти',
  'landing.hero.subtitle':
    'Свържете се с верифицирани доставчици на услуги за всичките ви нужди във вашия район',
  'landing.hero.getStarted': 'Започнете',
  'landing.hero.browseServices': 'Разгледайте услугите',

  'landing.trustIndicators.verified': 'Проверени специалисти',
  'landing.trustIndicators.securePayments': 'Сигурни плащания',
  'landing.trustIndicators.support': '24/7 поддръжка',
  'landing.trustIndicators.freeToUse': 'Безплатно за използване',
  'landing.trustIndicators.communityReviews': 'Отзиви от общността',
  'landing.trustIndicators.verifiedDescription':
    'Всички специалисти са проверени',
  'landing.trustIndicators.ratingSystem': '5-звездна система за оценка',
  'landing.trustIndicators.ratingSystemDescription':
    'Качеството се гарантира чрез отзиви от общността',
  'landing.trustIndicators.dataProtection': 'Защита на данните',
  'landing.trustIndicators.dataProtectionDescription':
    'Вашата лична информация е в безопасност',
  'landing.trustIndicators.contracts': 'Правна защита',
  'landing.trustIndicators.contractsDescription':
    'Всички работи се защитават от ясни споразумения',

  'landing.stats.averageRating': 'средна оценка',
  'landing.stats.completedTasks': 'завършени задачи',
  'landing.categories.activeSpecialists': 'активни специалисти',

  'landing.categories.title': 'Популярни категории',
  'landing.categories.subtitle':
    'Намерете специалисти за всяка задача - от ремонти в дома до лична помощ',
  'landing.categories.viewAll': 'Виж всички категории',
  'landing.categories.home': 'Дом и градина',
  'landing.categories.home.description':
    'Електричество, водопровод, почистване, поддръжка',
  'landing.categories.tech': 'Технологии',
  'landing.categories.tech.description':
    'IT поддръжка, уеб дизайн, софтуерно разработване',
  'landing.categories.business': 'Бизнес услуги',
  'landing.categories.business.description':
    'Административни задачи, събития, консултации',
  'landing.categories.personal': 'Лични услуги',
  'landing.categories.personal.description':
    'Грижа за домашни любимци, деца, възрастни',
  'landing.categories.education': 'Образование и обучение',
  'landing.categories.creative': 'Творчески услуги',

  'landing.featured.title': 'Препоръчани задачи',
  'landing.featured.badge': 'Последни възможности',
  'landing.featured.viewAll': 'Вижте всички задачи',

  'landing.howItWorks.title': 'Как работи платформата',
  'landing.howItWorks.subtitle':
    'Лесен процес за намиране и завършване на задачи с проверени специалисти',
  'landing.howItWorks.forCustomers': 'За клиенти',
  'landing.howItWorks.forProfessionals': 'За специалисти',
  'landing.howItWorks.step1.title': 'Публикувайте задачата си',
  'landing.howItWorks.step1.description':
    'Опишете какво трябва да бъде направено и определете бюджета си',
  'landing.howItWorks.step2.title': 'Получете предложения',
  'landing.howItWorks.step2.description':
    'Получавайте заявления от верифицирани професионалисти',
  'landing.howItWorks.step3.title': 'Изберете и завършете',
  'landing.howItWorks.step3.description':
    'Изберете най-добрия професионалист и приключете задачата си',

  // Tasks
  'tasks.title': 'Разглеждане на задачи',
  'tasks.subtitle':
    'Намерете перфектната задача, която отговаря на вашите умения и интереси',
  'tasks.searchPlaceholder':
    'Търсете задачи по ключови думи, категории или местоположение...',
  'tasks.filters.title': 'Филтри',
  'tasks.filters.category': 'Категория',
  'tasks.filters.allCategories': 'Всички категории',
  'tasks.filters.location': 'Местоположение',
  'tasks.filters.budget': 'Бюджет',
  'tasks.filters.budgetMin': 'Мин. бюджет',
  'tasks.filters.budgetMax': 'Макс. бюджет',
  'tasks.filters.deadline': 'Краен срок',
  'tasks.filters.status': 'Статус',
  'tasks.filters.all': 'Всички',
  'tasks.filters.open': 'Отворени',
  'tasks.filters.inProgress': 'В ход',
  'tasks.filters.completed': 'Завършени',
  'tasks.filters.activeFilters': 'Активни филтри',
  'tasks.filters.clearAll': 'Изчисти всички',
  'tasks.results': 'резултата',
  'tasks.sort.newest': 'Най-нови първо',
  'tasks.sort.oldest': 'Най-стари първо',
  'tasks.sort.budgetHigh': 'Най-висок бюджет',
  'tasks.sort.budgetLow': 'Най-нисък бюджет',
  'tasks.sort.deadline': 'По краен срок',

  // Professionals Page
  'professionals.hero.title': 'Намерете доверени професионалисти',
  'professionals.hero.subtitle':
    'Прегледайте верифицирани специалисти по категория и намерете перфектното съвпадение за вашите нужди',
  'professionals.hero.badge': 'Мрежа от професионалисти',
  'professionals.searchPlaceholder':
    'Търсете категории... (напр. ремонт, почистване, уроци)',
  'professionals.allCategories': 'Всички категории',
  'professionals.featuredTitle': 'Препоръчани професионалисти',
  'professionals.viewProfile': 'Вижте профила',
  'professionals.rating': 'Рейтинг',
  'professionals.completedJobs': 'Завършени задачи',
  'professionals.startingFrom': 'Започва от',
  'professionals.noResults':
    'Няма категории, които да съвпадат с вашето търсене',
  'professionals.categoryResults': 'категории намерени',
  'professionals.filterBy': 'Филтрирай по',
  'professionals.location': 'Местоположение',
  'professionals.experience': 'Опит',
  'professionals.priceRange': 'Ценови диапазон',
  'professionals.availability': 'Наличност',
  'professionals.findPerfect': 'Намерете перфектния професионалист',
  'professionals.discoverTrusted':
    'Открийте доверени професионалисти с доказани резултати и отлични отзиви',
  'professionals.popularCategories': 'Популярни категории',
  'professionals.refineSearch': 'Прецизирайте резултатите от търсенето',
  'professionals.professionalsAvailable': 'достъпни професионалисти',
  'professionals.noMatchingResults':
    'Няма професионалисти, които да отговарят на вашите критерии. Опитайте да разширите търсенето.',
  'professionals.mostActive': 'Най-активни',
  'professionals.gender.male': 'Мъж',
  'professionals.gender.female': 'Жена',
  'professionals.filters.category': 'Категория',
  'professionals.filters.location': 'Местоположение',
  'professionals.filters.minimumRating': 'Минимален рейтинг',
  'professionals.filters.genderPreference': 'Предпочитание по пол',
  'professionals.filters.activityLevel': 'Ниво на активност',
  'professionals.filters.all': 'Всички',
  'professionals.filters.topPerformersOnly': 'Само най-добрите',
  'professionals.filters.locationPlaceholder': 'София, Пловдив, Варна...',
  'professionals.filters.any': 'Всички',
  'professionals.filters.anyShort': 'Всички',
  'professionals.typing.plumber': 'водопроводчик в София',
  'professionals.typing.cleaner': 'специалист за почистване',
  'professionals.typing.electrician': 'сертифициран електрик',
  'professionals.typing.tutor': 'учител по английски',
  'professionals.typing.photographer': 'сватбен фотограф',
  'professionals.typing.handyman': 'майсторски услуги',
  'professionals.recommendedTitle': 'ПРЕПОРЪЧАНИ ПРОФЕСИОНАЛИСТИ',
  'professionals.filters.clear': 'Изчисти',
  'professionals.filters.clearAll': 'Изчисти всички филтри',
  'professionals.filters.fourPlusStars': '4+ звезди',
  'professionals.filters.fiveStarsOnly': 'Само 5 звезди',
  'professionals.filters.anyRating': 'По рейтинг',
  'professionals.filters.showProfessionalsWithAnyRating':
    'Покажи професионалисти с всякакъв рейтинг',
  'professionals.filters.locationPlaceholderDesktop': '📍 Местоположение',
  'professionals.sorting.featuredFirst': 'Топ избор',
  'professionals.sorting.featuredFirstDesc': 'Най-добрите профи',
  'professionals.sorting.highestRating': 'По рейтинг',
  'professionals.sorting.highestRatingDesc': 'С най-добри оценки',
  'professionals.sorting.mostExperience': 'По опит',
  'professionals.sorting.mostExperienceDesc': 'Много закази',
  'professionals.filters.sortResultsBy': 'Сортиране по',
  'professionals.filters.sortResultsTitle': 'Сортиране',
  'professionals.filters.sortResultsDescription':
    'Изберете как да подредите професионалистите',
  'professionals.filters.selectMinimumRating': 'Изберете минимален рейтинг',
  'professionals.filters.showingVerifiedFirst':
    'Показване на проверени топ професионалисти първо',
  'professionals.filters.proTip': 'Съвет',
  'professionals.filters.proTipMessage':
    'Опитайте "{{sortOption}}" за качествени професионалисти с проверени квалификации',
  'professionals.filters.sortingBy': 'Сортиране по {{option}}',
  'professionals.filters.sortingDescFeatured':
    'Показване на проверени топ професионалисти първо',
  'professionals.filters.sortingDescRating':
    'Професионалисти с най-висок рейтинг се показват първо',
  'professionals.filters.sortingDescJobs':
    'Най-опитните професионалисти се показват първо',
  'professionals.filters.activeFilters': 'Активни филтри',
  'professionals.filters.filterApplied': '{{count}} филтър приложен',
  'professionals.filters.filtersApplied': '{{count}} филтъра приложени',
  'professionals.filters.showProfessionalsWithRating':
    'Покажи професионалисти с {{rating}}+ звездни оценки',
  'professionals.filters.showPerfectRating':
    'Покажи само професионалисти с пърфектни 5-звездни оценки',

  // Browse Tasks Hero
  'browseTasks.hero.badge': 'Открийте перфектните професионалисти',
  'browseTasks.hero.title1': 'Намерете идеалната',
  'browseTasks.hero.title2': 'задача за вас',
  'browseTasks.hero.subtitle':
    'Разгледайте стотици възможности от проверени клиенти. Започнете работа още днес.',
  'browseTasks.search.placeholder':
    'Търсете задачи по ключови думи, категория или град...',
  'browseTasks.search.popular': 'Популярни',
  'browseTasks.filters.title': 'Филтриране и сортиране',
  'browseTasks.filters.advanced': 'Разширени филтри',
  'browseTasks.filters.quick': 'Бърз филтър',
  'browseTasks.filters.searchPlaceholder':
    'Търсете задачи... (напр. почистване, ремонт, доставка)',
  'browseTasks.filters.category': 'Категория',
  'browseTasks.filters.allCategories': 'Всички категории',
  'browseTasks.filters.city': 'Град',
  'browseTasks.filters.allCities': 'Всички градове',
  'browseTasks.filters.cities.sofia': 'София',
  'browseTasks.filters.cities.plovdiv': 'Пловдив',
  'browseTasks.filters.cities.varna': 'Варна',
  'browseTasks.filters.cities.burgas': 'Бургас',
  'browseTasks.filters.budget': 'Бюджет',
  'browseTasks.filters.budgetMin': 'Мин',
  'browseTasks.filters.budgetMax': 'Макс',
  'browseTasks.filters.budgetUpTo': 'До 500 лв',
  'browseTasks.filters.sortBy': 'Сортиране',
  'browseTasks.filters.sort.newest': 'Най-нови',
  'browseTasks.filters.sort.oldest': 'Най-стари',
  'browseTasks.filters.sort.highBudget': 'Висок бюджет',
  'browseTasks.filters.sort.lowBudget': 'Нисък бюджет',
  'browseTasks.results.shown': 'Показани {{count}} резултата',
  'browseTasks.results.featured': 'Показани {{count}} популярни задачи',
  'browseTasks.results.loading': 'Зареждане...',
  'browseTasks.results.noTasks.title': 'Няма намерени задачи',
  'browseTasks.results.noTasks.description':
    'Опитайте да промените филтрите или да търсите по различни критерии.',
  'browseTasks.results.noTasks.clearFilters': 'Изчисти филтрите',
  'browseTasks.results.suggestedTasks':
    'Популярни задачи, които може да ви харесат',
  'browseTasks.results.suggestedDescription':
    'Ето някои популярни задачи от нашата общност',
  'browseTasks.results.error.title': 'Грешка при зареждане',
  'browseTasks.results.error.description':
    'Моля, опитайте отново или свържете се с поддръжката.',
  'browseTasks.pagination.previous': 'Предишна',
  'browseTasks.pagination.next': 'Следваща',
  'browseTasks.search.tags.programming': 'Програмиране',
  'browseTasks.search.tags.design': 'Дизайн',
  'browseTasks.search.tags.marketing': 'Маркетинг',
  'browseTasks.search.tags.translation': 'Преводи',
  'browseTasks.search.tags.photography': 'Фотография',
  'browseTasks.typing.plumber': 'водопроводчик в София',
  'browseTasks.typing.cleaner': 'почистване на къща',
  'browseTasks.typing.electrician': 'ремонт електричество',
  'browseTasks.typing.tutor': 'учител по английски',
  'browseTasks.typing.moving': 'преместване мебели',
  'browseTasks.typing.gardener': 'поддръжка на градина',

  'task.budget': 'Бюджет',
  'task.location': 'Местоположение',
  'task.category': 'Категория',
  'task.applications': 'Заявления',
  'task.viewDetails': 'Вижте детайли',
  'task.apply': 'Кандидатствайте сега',
  'task.created': 'Създадена',
  'task.deadline': 'Краен срок',

  // Create Task
  'createTask.title': 'Публикувайте нова задача',
  'createTask.form.title': 'Заглавие на задачата',
  'createTask.form.titlePlaceholder': 'Какво трябва да бъде направено?',
  'createTask.form.description': 'Описание',
  'createTask.form.descriptionPlaceholder': 'Опишете задачата си подробно...',
  'createTask.form.category': 'Категория',
  'createTask.form.selectCategory': 'Изберете категория',
  'createTask.form.budget': 'Бюджет (лв.)',
  'createTask.form.budgetPlaceholder': 'Въведете вашия бюджет',
  'createTask.form.location': 'Местоположение',
  'createTask.form.locationPlaceholder': 'Въведете местоположение',
  'createTask.form.deadline': 'Краен срок',
  'createTask.form.selectDeadline': 'Изберете краен срок',
  'createTask.form.images': 'Изображения (по желание)',
  'createTask.form.imagesDescription':
    'Качете изображения, за да помогнете при описанието на задачата',
  'createTask.form.postTask': 'Публикувайте задача',

  // Profile
  'profile.title': 'Моят профил',
  'profile.personalInfo': 'Лична информация',
  'profile.professionalInfo': 'Професионална информация',
  'profile.verification': 'Верификация',
  'profile.reviews': 'Отзиви',
  'profile.stats': 'Статистика',

  'profile.form.firstName': 'Име',
  'profile.form.lastName': 'Фамилия',
  'profile.form.email': 'Имейл',
  'profile.form.phone': 'Телефон',
  'profile.form.location': 'Местоположение',
  'profile.form.bio': 'Биография',
  'profile.form.skills': 'Умения',
  'profile.form.experience': 'Години опит',
  'profile.form.hourlyRate': 'Часова ставка (лв.)',
  'profile.form.vatNumber': 'ДДС номер',
  'profile.form.businessName': 'Име на фирмата',
  'profile.form.website': 'Уебсайт',

  'profile.verification.identity': 'Верифицирана самоличност',
  'profile.verification.business': 'Верифициран бизнес',
  'profile.verification.phone': 'Верифициран телефон',
  'profile.verification.email': 'Верифициран имейл',

  // Languages
  'language.en': 'English',
  'language.bg': 'Български',
  'language.ru': 'Русский',

  // Messages and feedback
  // Missing trust stats and additional sections
  'landing.trustStats.securityUptime': 'Сигурност',
  'landing.trustStats.avgRating': 'Средна оценка',
  'landing.trustStats.encryption': 'Криптиране на данни',
  'landing.trustStats.compliance': 'Правно съответствие',

  'landing.featured.subtitle': 'Последни задачи публикувани от общността',
  'landing.featured.professionalDesc': 'Намерете следващата си възможност',
  'landing.featured.customerDesc': 'Вижте какво публикуват други',

  'landing.howItWorks.customers.step1.title': 'Публикувайте задачата си',
  'landing.howItWorks.customers.step1.description':
    'Опишете какво трябва да бъде направено и определете бюджета си',
  'landing.howItWorks.customers.step2.title': 'Получете предложения',
  'landing.howItWorks.customers.step2.description':
    'Получавайте заявления от верифицирани професионалисти',
  'landing.howItWorks.customers.step3.title': 'Изберете и завършете',
  'landing.howItWorks.customers.step3.description':
    'Изберете най-добрия професионалист и приключете задачата си',

  'landing.howItWorks.professionals.step1.title': 'Разгледайте задачи',
  'landing.howItWorks.professionals.step1.description':
    'Намерете задачи, които съответстват на вашите умения и наличност',
  'landing.howItWorks.professionals.step2.title': 'Изпратете предложение',
  'landing.howItWorks.professionals.step2.description':
    'Изпратете най-доброто си предложение и покажете експертизата си',
  'landing.howItWorks.professionals.step3.title': 'Завършете работата',
  'landing.howItWorks.professionals.step3.description':
    'Предоставете качествена услуга и изградете репутацията си',

  // Testimonials
  'landing.testimonials.title': 'Какво казват нашите потребители',
  'landing.testimonials.subtitle': 'Истински отзиви от нашата общност',
  'landing.testimonials.customers.title': 'От клиенти',
  'landing.testimonials.customers.customer1.name': 'Мария Иванова',
  'landing.testimonials.customers.customer1.location': 'София, България',
  'landing.testimonials.customers.customer1.quote':
    'Намерих невероятен водопроводчик за минути. Професионална услуга и честни цени!',
  'landing.testimonials.customers.customer2.name': 'Георги Петров',
  'landing.testimonials.customers.customer2.location': 'Пловдив, България',
  'landing.testimonials.customers.customer2.quote':
    'Услугата за почистване беше изключителна. Определено ще използвам Trudify отново.',
  'landing.testimonials.customers.customer3.name': 'Елена Димитрова',
  'landing.testimonials.customers.customer3.location': 'Варна, България',
  'landing.testimonials.customers.customer3.quote':
    'Бързо, надеждно и достъпно. Точно това, което търсех.',

  'landing.testimonials.professionals.title': 'От специалисти',
  'landing.testimonials.professionals.pro1.name': 'Иван Стоев',
  'landing.testimonials.professionals.pro1.profession': 'Електротехник',
  'landing.testimonials.professionals.pro1.quote':
    'Trudify ми помогна да разширя бизнеса си с постоянен поток от качествени клиенти.',
  'landing.testimonials.professionals.pro2.name': 'Анна Николова',
  'landing.testimonials.professionals.pro2.profession': 'Почистваща',
  'landing.testimonials.professionals.pro2.quote':
    'Лесна за използване платформа. Харесвам как мога да управлявам графика и плащанията си.',
  'landing.testimonials.professionals.pro3.name': 'Димитър Георгиев',
  'landing.testimonials.professionals.pro3.profession': 'Майстор',
  'landing.testimonials.professionals.pro3.quote':
    'Професионална платформа, която ме свързва с клиенти, които ценят качествената работа.',

  // Trust Section
  'landing.trustSection.title': 'Изградена върху доверие',
  'landing.trustSection.subtitle':
    'Вашата сигурност и удовлетвореност са нашите най-важни приоритети',

  // Call to Action
  'landing.cta.title': 'Готови ли сте да започнете?',
  'landing.cta.subtitle': 'Присъединете се към хиляди доволни потребители днес',
  'landing.cta.postTask': 'Публикувайте задача',
  'landing.cta.joinProfessionals': 'Стани професионалист',
  'landing.cta.freeToJoin': 'Безплатно присъединяване, без скрити такси',
  'landing.cta.stats.completedTasks': 'Завършени задачи',
  'landing.cta.stats.activeSpecialists': 'Активни специалисти',
  'landing.cta.stats.averageRating': 'Средна оценка',
  'landing.cta.stats.contractTemplates': 'Правни шаблони',

  // Task Card
  'taskCard.apply': 'Кандидатствай',
  'taskCard.anonymous': 'Анонимен',
  'taskCard.budget.from': 'от',
  'taskCard.budget.to': 'до',
  'taskCard.budget.negotiable': 'За договаряне',
  'taskCard.deadline.flexible': 'Гъвкав',
  'taskCard.deadline.today': 'Днес',
  'taskCard.deadline.tomorrow': 'Утре',
  'taskCard.deadline.days': 'дни',
  'taskCard.category.home_repair': 'Домашни ремонти',
  'taskCard.category.delivery_transport': 'Доставки и транспорт',
  'taskCard.category.personal_care': 'Лична грижа',
  'taskCard.category.personal_assistant': 'Личен асистент',
  'taskCard.category.learning_fitness': 'Обучение и фитнес',
  'taskCard.category.other': 'Други',

  // Categories - Comprehensive list
  'categories.plumbing': 'Водопровод',
  'categories.electrical': 'Електричество',
  'categories.hvac': 'Климатици и отопление',
  'categories.carpentry': 'Дърводелство',
  'categories.painting': 'Боядисване',
  'categories.flooring': 'Подови настилки',
  'categories.roofing': 'Покриви',
  'categories.homeRenovation': 'Ремонти на домове',
  'categories.applianceRepair': 'Ремонт на уреди',
  'categories.handyman': 'Майстор',
  'categories.houseCleaning': 'Почистване на дом',
  'categories.deepCleaning': 'Дълбоко почистване',
  'categories.carpetCleaning': 'Почистване на килими',
  'categories.windowCleaning': 'Почистване на прозорци',
  'categories.gardenMaintenance': 'Поддръжка на градини',
  'categories.landscaping': 'Озеленяване',
  'categories.delivery': 'Доставки',
  'categories.moving': 'Преместване',
  'categories.taxiDriver': 'Такси',
  'categories.courier': 'Куриер',
  'categories.babysitting': 'Детегледане',
  'categories.elderlyCare': 'Грижа за възрастни',
  'categories.petSitting': 'Грижа за домашни любимци',
  'categories.personalTrainer': 'Личен треньор',
  'categories.massageTherapy': 'Масаж',
  'categories.tutoring': 'Уроци',
  'categories.translation': 'Превод',
  'categories.accounting': 'Счетоводство',
  'categories.legalServices': 'Юридически услуги',
  'categories.consulting': 'Консултантство',
  'categories.graphicDesign': 'Графичен дизайн',
  'categories.webDevelopment': 'Уеб разработка',
  'categories.photography': 'Фотография',
  'categories.videography': 'Видеография',
  'categories.writing': 'Писане',
  'categories.musicLessons': 'Музикални уроци',
  'categories.eventPlanning': 'Организиране на събития',
  'categories.catering': 'Кетъринг',
  'categories.djServices': 'DJ услуги',
  'categories.hairdressing': 'Фризьорство',
  'categories.makeupArtist': 'Грим',
  'categories.nailServices': 'Маникюр и педикюр',
  'categories.other': 'Други',

  // Professional Detail Page
  'professionalDetail.about': 'За професионалиста',
  'professionalDetail.reviews': 'отзива',
  'professionalDetail.online': 'Онлайн',
  'professionalDetail.offline': 'Видян наскоро',
  'professionalDetail.verified.phone': 'Телефон',
  'professionalDetail.verified.id': 'Документ',
  'professionalDetail.stats.completedTasks': 'Задачи',
  'professionalDetail.stats.yearsExperience': 'Години',
  'professionalDetail.stats.responseTime': 'Отговор',
  'professionalDetail.actions.proposeTask': 'Предложи задача',
  'professionalDetail.actions.contact': 'Контакт',
  'professionalDetail.actions.askQuestion': 'Задай въпрос',
  'professionalDetail.actions.saveToFavorites': 'Запази в любими',
  'professionalDetail.contactHours': 'Достъпен',
  'professionalDetail.services.title': 'Услуги и цени',
  'professionalDetail.services.pricingNote.title': 'Информация за цените',
  'professionalDetail.services.pricingNote.description':
    'Окончателните цени се договарят индивидуално въз основа на сложността и изискванията на задачата.',
  'professionalDetail.portfolio.title': 'Моите примери',
  'professionalDetail.portfolio.noWork': 'Все още няма примери',
  'professionalDetail.portfolio.before': 'Преди',
  'professionalDetail.portfolio.after': 'След',
  'professionalDetail.portfolio.viewMore': 'Виж всички примери',
  'professionalDetail.portfolio.showcase': 'Професионални примери от работата',
  'professionalDetail.completedTasks.title': 'Завършени задачи',
  'professionalDetail.completedTasks.noTasks': 'Все още няма завършени задачи',
  'professionalDetail.completedTasks.viewTask': 'Виж задачата',
  'professionalDetail.completedTasks.completedOn': 'Завършена на',
  'professionalDetail.reviews.title': 'Отзиви и оценки',
  'professionalDetail.reviews.count': 'отзива',
  'professionalDetail.reviews.recentRating': 'Скорошна оценка',
  'professionalDetail.reviews.excellent': 'Отлично',
  'professionalDetail.reviews.noReviews': 'Все още няма отзиви',
  'professionalDetail.reviews.beFirst': 'Бъди първият, който ще даде отзив',
  'professionalDetail.reviews.showMore': 'Покажи всички отзиви',
  'professionalDetail.reviews.allReviews': 'Всички отзиви',
  'professionalDetail.reviews.avgRating': 'Средна оценка',
  'professionalDetail.reviews.more': 'още',
  'professionalDetail.completedTasks.stats.tasksCompleted': 'Завършени задачи',
  'professionalDetail.completedTasks.stats.avgRating': 'Средна оценка',
  'professionalDetail.completedTasks.stats.fiveStarTasks': '5-звездни задачи',
  'professionalDetail.verified': 'Потвърден',
  'common.anonymous': 'Анонимен потребител',

  // Footer
  'footer.company.description':
    'Свързваме хората с квалифицирани професионалисти за всякакъв вид услуги в България.',
  'footer.quickLinks.title': 'Бързи връзки',
  'footer.quickLinks.howItWorks': 'Как работи',
  'footer.quickLinks.categories': 'Категории',
  'footer.quickLinks.forProfessionals': 'За професионалисти',
  'footer.quickLinks.security': 'Сигурност',
  'footer.quickLinks.help': 'Помощ',
  'footer.legal.title': 'Правни',
  'footer.legal.terms': 'Общи условия',
  'footer.legal.privacy': 'Поверителност',
  'footer.legal.gdpr': 'GDPR',
  'footer.legal.cookies': 'Cookies',
  'footer.legal.complaints': 'Жалби',
  'footer.contact.title': 'Контакти',
  'footer.contact.subtitle': 'Свържете се с нас за въпроси и поддръжка',
  'footer.language.label': 'Език',
  'footer.copyright': '© 2025 Obod Soft LTD. Всички права запазени.',

  // Task Details
  'taskDetail.backToTasks': 'Обратно към задачите',
  'taskDetail.requirements': 'Изисквания:',
  'taskDetail.keyInformation': 'Ключова информация',
  'taskDetail.client': 'Клиент',
  'taskDetail.loginForMore': 'Влезте за повече',
  'taskDetail.loginMessage':
    'Влезте в акаунта си за да видите пълната информация',
  'taskDetail.completedTasks': 'завършени задачи',
  'taskDetail.memberSince': 'Член от',
  'taskDetail.similarTasks': 'Подобни задачи',
  'taskDetail.apply': 'Кандидатствай за задачата',
  'taskDetail.askQuestion': 'Задай въпрос',
  'taskDetail.applicationsCount': 'души',
  'taskDetail.timeAgo': 'преди',
  'taskDetail.today': 'Днес',
  'taskDetail.tomorrow': 'Утре',
  'taskDetail.days': 'дни',
  'taskDetail.flexible': 'Гъвкав',
  'taskDetail.negotiable': 'По договаряне',
  'taskDetail.urgency.same_day': 'Спешно - днес',
  'taskDetail.urgency.within_week': 'В рамките на седмица',
  'taskDetail.urgency.flexible': 'Гъвкав срок',
  'taskDetail.urgency.default': 'Неуточнен',

  'taskDetail.share': 'Сподели',
  'taskDetail.activity': 'Активност по задачата',
  'taskDetail.applications': 'Кандидатури',
  'taskDetail.questions': 'Въпроси',
  'taskDetail.accept': 'Приеми',
  'taskDetail.reject': 'Отхвърли',
  'taskDetail.message': 'Съобщение',
  'taskDetail.reply': 'Отговори',
  'taskDetail.yourReply': 'Вашия отговор:',
  'taskDetail.price': 'Цена:',
  'taskDetail.tasks': 'задачи',

  // Auth Slide-over
  'auth.applyForTask': 'Кандидатствай за задачата',
  'auth.askQuestion': 'Задай въпрос',
  'auth.createTask': 'Създай задача',
  'auth.loginToContinue': 'За да продължите, моля влезте в акаунта си',
  'auth.applyDescription':
    'Изпратете заявка на клиента и получете възможност да работите по тази задача.',
  'auth.questionDescription':
    'Задайте въпрос на клиента преди да кандидатствате за задачата.',
  'auth.createTaskDescription':
    'Създайте нова задача и намерете доверени професионалисти да завършат работата ви.',
  'auth.loginDescription':
    'Влезте в акаунта си за да управлявате задачи и да се свързвате с професионалисти.',
  'auth.email': 'Имейл адрес',
  'auth.password': 'Парола',
  'auth.rememberMe': 'Запомни ме',
  'auth.forgotPassword': 'Забравена парола?',
  'auth.loginOrRegister': 'Влизане / Регистрация',
  'auth.loginOrRegisterToContinue': 'За да продължите, моля влезте или се регистрирайте',
  'auth.loginOrRegisterDescription': 'Въведете данните си за достъп до акаунта или създайте нов.',
  'auth.continue': 'Продължи',
  'auth.login': 'Влизане',
  'auth.or': 'или',
  'auth.noAccount': 'Нямате акаунт?',
  'auth.createAccount': 'Създайте акаунт',
  'auth.whyRegister': 'Защо да се регистрирате?',
  'auth.benefit1': '• Кандидатствайте за задачи',
  'auth.benefit2': '• Общувайте директно с клиентите',
  'auth.benefit3': '• Проследявайте историята си',
  'auth.benefit4': '• Получавайте известия за нови задачи',
  'auth.continueWith': 'Продължи с',

  'message.taskCreated': 'Задачата е създадена успешно!',
  'message.profileUpdated': 'Профилът е актуализиран успешно!',
  'message.applicationSubmitted': 'Заявлението е подадено успешно!',
  'error.generic': 'Нещо се обърка. Моля, опитайте отново.',
  'error.network': 'Грешка в мрежата. Моля, проверете връзката си.',
  'error.unauthorized':
    'Трябва да влезете в профила си, за да достъпите тази страница.',
};

export default bg;
