const bg = {
  // Common
  welcome: 'Добре дошли',
  login: 'Вход',
  logout: 'Изход',
  signup: 'Регистрация',
  search: 'Търсене',
  browse: 'Разглеждане',
  create: 'Създаване',
  edit: 'Редактиране',
  delete: 'Изтриване',
  cancel: 'Отказ',
  save: 'Запазване',
  submit: 'Изпращане',
  loading: 'Зареждане...',
  error: 'Грешка',
  success: 'Успех',
  back: 'Назад',
  next: 'Напред',
  previous: 'Предишна',
  home: 'Начало',
  profile: 'Профил',
  settings: 'Настройки',

  // Navigation
  'nav.home': 'Начало',
  'nav.browseTasks': 'Задачи',
  'nav.createTask': 'Създай',
  'nav.profile': 'Профил',
  'nav.howItWorks': 'Как работи',
  'nav.categories': 'Категории',
  'nav.forProfessionals': 'Професионалисти',
  'nav.myTasks': 'Моите задачи',
  'nav.help': 'Помощ',

  // Landing Page
  'landing.hero.title': 'Вашата местна платформа за услуги и възможности',
  'landing.hero.subtitle':
    'Trudify свързва хора, които се нуждаят от помощ, с квалифицирани специалисти, готови да печелят. Публикувайте задача или намерете работа - доверено, проверено и лесно.',
  'landing.hero.getStarted': 'Публикувай задача',
  'landing.hero.browseServices': 'Намери работа',

  'landing.trustIndicators.verified': 'Проверени специалисти',
  'landing.trustIndicators.securePayments': 'Сигурни плащания',
  'landing.trustIndicators.support': '24/7 поддръжка',
  'landing.trustIndicators.freeToUse': 'Безплатно за използване',
  'landing.trustIndicators.communityReviews': 'Отзиви от общността',
  'landing.trustIndicators.verifiedDescription':
    'Всички специалисти са проверени',
  'landing.trustIndicators.ratingSystem': '5-звездна система за оценка',
  'landing.trustIndicators.ratingSystemDescription':
    'Качеството се гарантира чрез отзиви от общността',
  'landing.trustIndicators.dataProtection': 'Защита на данните',
  'landing.trustIndicators.dataProtectionDescription':
    'Вашата лична информация е в безопасност',
  'landing.trustIndicators.contracts': 'Правна защита',
  'landing.trustIndicators.contractsDescription':
    'Всички работи се защитават от ясни споразумения',

  'landing.stats.averageRating': 'средна оценка',
  'landing.stats.completedTasks': 'завършени задачи',
  'landing.categories.activeSpecialists': 'активни специалисти',

  'landing.categories.title': 'Популярни категории',
  'landing.categories.subtitle':
    'Намерете специалисти за всяка задача - от ремонти в дома до лична помощ',
  'landing.categories.viewAll': 'Виж всички категории',
  'landing.categories.home': 'Дом и градина',
  'landing.categories.home.description':
    'Електричество, водопровод, почистване, поддръжка',
  'landing.categories.tech': 'Технологии',
  'landing.categories.tech.description':
    'IT поддръжка, уеб дизайн, софтуерно разработване',
  'landing.categories.business': 'Бизнес услуги',
  'landing.categories.business.description':
    'Административни задачи, събития, консултации',
  'landing.categories.personal': 'Лични услуги',
  'landing.categories.personal.description':
    'Грижа за домашни любимци, деца, възрастни',
  'landing.categories.education': 'Образование и обучение',
  'landing.categories.creative': 'Творчески услуги',

  'landing.featured.title': 'Препоръчани задачи',
  'landing.featured.badge': 'Последни възможности',
  'landing.featured.viewAll': 'Вижте всички задачи',

  'landing.howItWorks.title': 'Как работи платформата',
  'landing.howItWorks.subtitle':
    'Лесен процес за намиране и завършване на задачи с проверени специалисти',
  'landing.howItWorks.forCustomers': 'За клиенти',
  'landing.howItWorks.forProfessionals': 'За специалисти',
  'landing.howItWorks.step1.title': 'Публикувайте задачата си',
  'landing.howItWorks.step1.description':
    'Опишете какво трябва да бъде направено и определете бюджета си',
  'landing.howItWorks.step2.title': 'Получете предложения',
  'landing.howItWorks.step2.description':
    'Получавайте заявления от верифицирани професионалисти',
  'landing.howItWorks.step3.title': 'Изберете и завършете',
  'landing.howItWorks.step3.description':
    'Изберете най-добрия професионалист и приключете задачата си',

  // Tasks
  'tasks.title': 'Разглеждане на задачи',
  'tasks.subtitle':
    'Намерете перфектната задача, която отговаря на вашите умения и интереси',
  'tasks.searchPlaceholder':
    'Търсете задачи по ключови думи, категории или местоположение...',
  'tasks.filters.title': 'Филтри',
  'tasks.filters.category': 'Категория',
  'tasks.filters.allCategories': 'Всички категории',
  'tasks.filters.location': 'Местоположение',
  'tasks.filters.budget': 'Бюджет',
  'tasks.filters.budgetMin': 'Мин. бюджет',
  'tasks.filters.budgetMax': 'Макс. бюджет',
  'tasks.filters.deadline': 'Краен срок',
  'tasks.filters.status': 'Статус',
  'tasks.filters.all': 'Всички',
  'tasks.filters.open': 'Отворени',
  'tasks.filters.inProgress': 'В ход',
  'tasks.filters.completed': 'Завършени',
  'tasks.filters.activeFilters': 'Активни филтри',
  'tasks.filters.clearAll': 'Изчисти всички',
  'tasks.results': 'резултата',
  'tasks.sort.newest': 'Най-нови първо',
  'tasks.sort.oldest': 'Най-стари първо',
  'tasks.sort.budgetHigh': 'Най-висок бюджет',
  'tasks.sort.budgetLow': 'Най-нисък бюджет',
  'tasks.sort.deadline': 'По краен срок',

  // Professionals Page
  'professionals.hero.title': 'Намерете доверени професионалисти',
  'professionals.hero.subtitle':
    'Прегледайте верифицирани специалисти по категория и намерете перфектното съвпадение за вашите нужди',
  'professionals.hero.badge': 'Мрежа от професионалисти',
  'professionals.searchPlaceholder':
    'Търсете категории... (напр. ремонт, почистване, уроци)',
  'professionals.allCategories': 'Всички категории',
  'professionals.featuredTitle': 'Препоръчани професионалисти',
  'professionals.viewProfile': 'Вижте профила',
  'professionals.rating': 'Рейтинг',
  'professionals.completedJobs': 'Завършени задачи',
  'professionals.startingFrom': 'Започва от',
  'professionals.noResults':
    'Няма категории, които да съвпадат с вашето търсене',
  'professionals.categoryResults': 'категории намерени',
  'professionals.filterBy': 'Филтрирай по',
  'professionals.location': 'Местоположение',
  'professionals.experience': 'Опит',
  'professionals.priceRange': 'Ценови диапазон',
  'professionals.availability': 'Наличност',
  'professionals.findPerfect': 'Намерете перфектния професионалист',
  'professionals.discoverTrusted':
    'Открийте доверени професионалисти с доказани резултати и отлични отзиви',
  'professionals.popularCategories': 'Популярни категории',
  'professionals.refineSearch': 'Прецизирайте резултатите от търсенето',
  'professionals.professionalsAvailable': 'достъпни професионалисти',
  'professionals.noMatchingResults':
    'Няма професионалисти, които да отговарят на вашите критерии. Опитайте да разширите търсенето.',
  'professionals.mostActive': 'Най-активни',
  'professionals.gender.male': 'Мъж',
  'professionals.gender.female': 'Жена',
  'professionals.filters.category': 'Категория',
  'professionals.filters.location': 'Местоположение',
  'professionals.filters.minimumRating': 'Минимален рейтинг',
  'professionals.filters.genderPreference': 'Предпочитание по пол',
  'professionals.filters.activityLevel': 'Ниво на активност',
  'professionals.filters.all': 'Всички',
  'professionals.filters.topPerformersOnly': 'Само най-добрите',
  'professionals.filters.locationPlaceholder': 'София, Пловдив, Варна...',
  'professionals.filters.any': 'Всички',
  'professionals.filters.anyShort': 'Всички',
  'professionals.typing.plumber': 'водопроводчик в София',
  'professionals.typing.cleaner': 'специалист за почистване',
  'professionals.typing.electrician': 'сертифициран електрик',
  'professionals.typing.tutor': 'учител по английски',
  'professionals.typing.photographer': 'сватбен фотограф',
  'professionals.typing.handyman': 'майсторски услуги',
  'professionals.recommendedTitle': 'ПРЕПОРЪЧАНИ ПРОФЕСИОНАЛИСТИ',
  'professionals.filters.clear': 'Изчисти',
  'professionals.filters.clearAll': 'Изчисти всички филтри',
  'professionals.filters.fourPlusStars': '4+ звезди',
  'professionals.filters.fiveStarsOnly': 'Само 5 звезди',
  'professionals.filters.anyRating': 'По рейтинг',
  'professionals.filters.showProfessionalsWithAnyRating':
    'Покажи професионалисти с всякакъв рейтинг',
  'professionals.filters.locationPlaceholderDesktop': '📍 Местоположение',
  'professionals.sorting.featuredFirst': 'Топ избор',
  'professionals.sorting.featuredFirstDesc': 'Най-добрите профи',
  'professionals.sorting.highestRating': 'По рейтинг',
  'professionals.sorting.highestRatingDesc': 'С най-добри оценки',
  'professionals.sorting.mostExperience': 'По опит',
  'professionals.sorting.mostExperienceDesc': 'Много закази',
  'professionals.filters.sortResultsBy': 'Сортиране по',
  'professionals.filters.sortResultsTitle': 'Сортиране',
  'professionals.filters.sortResultsDescription':
    'Изберете как да подредите професионалистите',
  'professionals.filters.selectMinimumRating': 'Изберете минимален рейтинг',
  'professionals.filters.showingVerifiedFirst':
    'Показване на проверени топ професионалисти първо',
  'professionals.filters.proTip': 'Съвет',
  'professionals.filters.proTipMessage':
    'Опитайте "{{sortOption}}" за качествени професионалисти с проверени квалификации',
  'professionals.filters.sortingBy': 'Сортиране по {{option}}',
  'professionals.filters.sortingDescFeatured':
    'Показване на проверени топ професионалисти първо',
  'professionals.filters.sortingDescRating':
    'Професионалисти с най-висок рейтинг се показват първо',
  'professionals.filters.sortingDescJobs':
    'Най-опитните професионалисти се показват първо',
  'professionals.filters.activeFilters': 'Активни филтри',
  'professionals.filters.filterApplied': '{{count}} филтър приложен',
  'professionals.filters.filtersApplied': '{{count}} филтъра приложени',
  'professionals.filters.showProfessionalsWithRating':
    'Покажи професионалисти с {{rating}}+ звездни оценки',
  'professionals.filters.showPerfectRating':
    'Покажи само професионалисти с пърфектни 5-звездни оценки',

  // Browse Tasks Hero
  'browseTasks.hero.badge': 'Открийте перфектните професионалисти',
  'browseTasks.hero.title1': 'Намерете идеалната',
  'browseTasks.hero.title2': 'задача за вас',
  'browseTasks.hero.subtitle':
    'Разгледайте стотици възможности от проверени клиенти. Започнете работа още днес.',
  'browseTasks.search.placeholder':
    'Търсете задачи по ключови думи, категория или град...',
  'browseTasks.search.popular': 'Популярни',
  'browseTasks.filters.title': 'Филтриране и сортиране',
  'browseTasks.filters.advanced': 'Разширени филтри',
  'browseTasks.filters.quick': 'Бърз филтър',
  'browseTasks.filters.searchPlaceholder':
    'Търсете задачи... (напр. почистване, ремонт, доставка)',
  'browseTasks.filters.category': 'Категория',
  'browseTasks.filters.allCategories': 'Всички категории',
  'browseTasks.filters.city': 'Град',
  'browseTasks.filters.allCities': 'Всички градове',
  'browseTasks.filters.cities.sofia': 'София',
  'browseTasks.filters.cities.plovdiv': 'Пловдив',
  'browseTasks.filters.cities.varna': 'Варна',
  'browseTasks.filters.cities.burgas': 'Бургас',
  'browseTasks.filters.budget': 'Бюджет',
  'browseTasks.filters.budgetMin': 'Мин',
  'browseTasks.filters.budgetMax': 'Макс',
  'browseTasks.filters.budgetUpTo': 'До 500 лв',
  'browseTasks.filters.sortBy': 'Сортиране',
  'browseTasks.filters.sort.newest': 'Най-нови',
  'browseTasks.filters.sort.oldest': 'Най-стари',
  'browseTasks.filters.sort.highBudget': 'Висок бюджет',
  'browseTasks.filters.sort.lowBudget': 'Нисък бюджет',
  'browseTasks.results.shown': 'Показани {{count}} резултата',
  'browseTasks.results.featured': 'Показани {{count}} популярни задачи',
  'browseTasks.results.loading': 'Зареждане...',
  'browseTasks.results.noTasks.title': 'Няма намерени задачи',
  'browseTasks.results.noTasks.description':
    'Опитайте да промените филтрите или да търсите по различни критерии.',
  'browseTasks.results.noTasks.clearFilters': 'Изчисти филтрите',
  'browseTasks.results.suggestedTasks':
    'Популярни задачи, които може да ви харесат',
  'browseTasks.results.suggestedDescription':
    'Ето някои популярни задачи от нашата общност',
  'browseTasks.results.error.title': 'Грешка при зареждане',
  'browseTasks.results.error.description':
    'Моля, опитайте отново или свържете се с поддръжката.',
  'browseTasks.pagination.previous': 'Предишна',
  'browseTasks.pagination.next': 'Следваща',
  'browseTasks.search.tags.programming': 'Програмиране',
  'browseTasks.search.tags.design': 'Дизайн',
  'browseTasks.search.tags.marketing': 'Маркетинг',
  'browseTasks.search.tags.translation': 'Преводи',
  'browseTasks.search.tags.photography': 'Фотография',
  'browseTasks.typing.plumber': 'водопроводчик в София',
  'browseTasks.typing.cleaner': 'почистване на къща',
  'browseTasks.typing.electrician': 'ремонт електричество',
  'browseTasks.typing.tutor': 'учител по английски',
  'browseTasks.typing.moving': 'преместване мебели',
  'browseTasks.typing.gardener': 'поддръжка на градина',

  'task.budget': 'Бюджет',
  'task.location': 'Местоположение',
  'task.category': 'Категория',
  'task.applications': 'Заявления',
  'task.viewDetails': 'Вижте детайли',
  'task.apply': 'Кандидатствайте сега',
  'task.created': 'Създадена',
  'task.deadline': 'Краен срок',

  // Create Task Form
  'createTask.title': 'Публикувайте нова задача',
  'createTask.hero.subtitle': 'Опишете какво ви трябва и нека професионалистите дойдат при вас',
  'createTask.hero.freeToPost': 'Безплатна публикация',
  'createTask.hero.noPayment': 'Без плащане до започване на работа',
  'createTask.hero.avgResponse': 'Средно време за отговор: 2 часа',
  'createTask.hero.verifiedPros': '1,500+ верифицирани професионалисти',
  'createTask.hero.help': 'Нуждаете се от помощ? Свържете се с нашия екип за поддръжка',

  // Category Section
  'createTask.category.title': 'Каква услуга ви трябва?',
  'createTask.category.subtitle': 'Изберете категория, която най-добре описва вашата задача',
  'createTask.category.selectSubcategory': 'Изберете конкретна услуга',
  'createTask.category.backToMain': 'Обратно към основни категории',
  'createTask.category.selected': 'Избрана услуга',
  'createTask.category.tryDifferent': 'Опитайте с различна търсачка',

  // Details Section
  'createTask.details.title': 'Опишете вашата задача',
  'createTask.details.subtitle': 'Колкото повече подробности, толкова по-добри предложения ще получите',
  'createTask.details.titleLabel': 'Заглавие на задачата',
  'createTask.details.titlePlaceholder': 'напр. Нуждая се от водопроводчик за теч в кухнята',
  'createTask.details.descriptionLabel': 'Описание',
  'createTask.details.descriptionPlaceholder': 'Опишете какво трябва да бъде направено, кога и какви специални изисквания имате...',
  'createTask.details.requirementsLabel': 'Специални изисквания (по избор)',
  'createTask.details.requirementsPlaceholder': 'Списък на инструменти, умения или опит, които са необходими...',

  // Location Section
  'createTask.location.title': 'Къде е задачата?',
  'createTask.location.subtitle': 'Това помага да намерим професионалисти в района ви',
  'createTask.location.cityLabel': 'Град',
  'createTask.location.cityPlaceholder': 'Изберете град',
  'createTask.location.neighborhoodLabel': 'Квартал (по избор)',
  'createTask.location.neighborhoodPlaceholder': 'напр. Център, Люлин, Студентски град',
  'createTask.location.addressLabel': 'Точен адрес (по избор)',
  'createTask.location.addressPlaceholder': 'Ще бъде споделен с избрания професионалист',
  'createTask.location.addressSecurity': 'Пълният адрес се крие, докато не наемете професионалист',

  // Budget Section
  'createTask.budget.title': 'Какъв е вашият бюджет?',
  'createTask.budget.help': 'Честните бюджети получават 3 пъти повече кандидатури',
  'createTask.budget.typeFixed': 'Фиксирана цена',
  'createTask.budget.typeRange': 'Ценови диапазон',
  'createTask.budget.fixedLabel': 'Вашият бюджет',
  'createTask.budget.minLabel': 'Минимум',
  'createTask.budget.maxLabel': 'Максимум',
  'createTask.budget.notSure': 'Не съм сигурен за бюджета',

  // Timeline Section
  'createTask.timeline.title': 'Кога ви трябва това?',
  'createTask.timeline.subtitle': 'Уведомете професионалистите за вашия график',
  'createTask.timeline.urgentTitle': 'Спешно - Същия ден',
  'createTask.timeline.urgentDesc': 'Трябва ми днес',
  'createTask.timeline.soonTitle': 'Скоро - В рамките на седмица',
  'createTask.timeline.soonDesc': 'Трябва ми в следващите 7 дни',
  'createTask.timeline.flexibleTitle': 'Гъвкав',
  'createTask.timeline.flexibleDesc': 'Гъвкав съм с времето',
  'createTask.timeline.deadlineLabel': 'Конкретен краен срок (по избор)',
  'createTask.timeline.deadlineHelp': 'Оставете празно, ако нямате конкретен краен срок',

  // Photos Section
  'createTask.photos.title': 'Добавете снимки (по избор)',
  'createTask.photos.help': 'Снимките помагат на професионалистите да разберат по-добре задачата ви',
  'createTask.photos.dragDrop': 'Плъзнете и пуснете изображения тук',
  'createTask.photos.orBrowse': 'или кликнете за преглед',
  'createTask.photos.maxFiles': 'Максимум 5 изображения',
  'createTask.photos.maxSize': '5MB на изображение',
  'createTask.photos.formats': 'JPG, PNG, WebP',
  'createTask.photos.addMore': 'Добавете още',
  'createTask.photos.uploading': 'Качване на снимки...',
  'createTask.photos.fileTooLarge': 'Файлът {{fileName}} е твърде голям. Максималният размер е 5MB',
  'createTask.photos.invalidType': 'Файлът {{fileName}} не е поддържан формат на изображение',
  'createTask.photos.uploadError': 'Неуспешно качване на снимки. Моля, опитайте отново.',

  // Review Section
  'createTask.review.title': 'Прегледайте вашата задача',
  'createTask.review.subtitle': 'Уверете се, че всичко изглежда добре преди публикуване',
  'createTask.review.noTitle': 'Все още няма заглавие',
  'createTask.review.noDescription': 'Все още няма описание',
  'createTask.review.location': 'Местоположение',
  'createTask.review.noCity': 'Няма избран град',
  'createTask.review.budget': 'Бюджет',
  'createTask.review.timeline': 'График',
  'createTask.review.requirements': 'Изисквания',
  'createTask.review.photos': 'Снимки',
  'createTask.review.submit': 'Публикувай задачата',
  'createTask.review.fillRequired': 'Моля, попълнете всички задължителни полета за да публикувате',

  // Form Validation Errors
  'createTask.errors.categoryRequired': 'Моля, изберете категория',
  'createTask.errors.titleTooShort': 'Заглавието трябва да бъде поне 10 символа',
  'createTask.errors.titleTooLong': 'Заглавието не може да бъде повече от 200 символа',
  'createTask.errors.descriptionTooShort': 'Описанието трябва да бъде поне 50 символа',
  'createTask.errors.descriptionTooLong': 'Описанието не може да бъде повече от 2000 символа',
  'createTask.errors.cityRequired': 'Моля, изберете град',
  'createTask.errors.budgetInvalid': 'Максималният бюджет трябва да бъде по-голям от минималния',
  'createTask.errors.tooManyPhotos': 'Максимум 5 снимки са разрешени',

  // Profile
  'profile.title': 'Моят профил',
  'profile.personalInfo': 'Лична информация',
  'profile.professionalInfo': 'Професионална информация',
  'profile.verification': 'Верификация',
  'profile.reviews': 'Отзиви',
  'profile.stats': 'Статистика',

  'profile.form.firstName': 'Име',
  'profile.form.lastName': 'Фамилия',
  'profile.form.email': 'Имейл',
  'profile.form.phone': 'Телефон',
  'profile.form.location': 'Местоположение',
  'profile.form.bio': 'Биография',
  'profile.form.skills': 'Умения',
  'profile.form.experience': 'Години опит',
  'profile.form.hourlyRate': 'Часова ставка (лв.)',
  'profile.form.vatNumber': 'ДДС номер',
  'profile.form.businessName': 'Име на фирмата',
  'profile.form.website': 'Уебсайт',

  'profile.verification.identity': 'Верифицирана самоличност',
  'profile.verification.business': 'Верифициран бизнес',
  'profile.verification.phone': 'Верифициран телефон',
  'profile.verification.email': 'Верифициран имейл',

  // Languages
  'language.en': 'English',
  'language.bg': 'Български',
  'language.ru': 'Русский',

  // Messages and feedback
  // Missing trust stats and additional sections
  'landing.trustStats.securityUptime': 'Сигурност',
  'landing.trustStats.avgRating': 'Средна оценка',
  'landing.trustStats.encryption': 'Криптиране на данни',
  'landing.trustStats.compliance': 'Правно съответствие',

  'landing.featured.subtitle': 'Последни задачи публикувани от общността',
  'landing.featured.professionalDesc': 'Намерете следващата си възможност',
  'landing.featured.customerDesc': 'Вижте какво публикуват други',

  'landing.howItWorks.customers.step1.title': 'Публикувайте задачата си',
  'landing.howItWorks.customers.step1.description':
    'Опишете какво трябва да бъде направено и определете бюджета си',
  'landing.howItWorks.customers.step2.title': 'Получете предложения',
  'landing.howItWorks.customers.step2.description':
    'Получавайте заявления от верифицирани професионалисти',
  'landing.howItWorks.customers.step3.title': 'Изберете и завършете',
  'landing.howItWorks.customers.step3.description':
    'Изберете най-добрия професионалист и приключете задачата си',

  'landing.howItWorks.professionals.step1.title': 'Разгледайте задачи',
  'landing.howItWorks.professionals.step1.description':
    'Намерете задачи, които съответстват на вашите умения и наличност',
  'landing.howItWorks.professionals.step2.title': 'Изпратете предложение',
  'landing.howItWorks.professionals.step2.description':
    'Изпратете най-доброто си предложение и покажете експертизата си',
  'landing.howItWorks.professionals.step3.title': 'Завършете работата',
  'landing.howItWorks.professionals.step3.description':
    'Предоставете качествена услуга и изградете репутацията си',

  // Testimonials
  'landing.testimonials.title': 'Какво казват нашите потребители',
  'landing.testimonials.subtitle': 'Истински отзиви от нашата общност',
  'landing.testimonials.customers.title': 'От клиенти',
  'landing.testimonials.customers.customer1.name': 'Мария Иванова',
  'landing.testimonials.customers.customer1.location': 'София, България',
  'landing.testimonials.customers.customer1.quote':
    'Намерих невероятен водопроводчик за минути. Професионална услуга и честни цени!',
  'landing.testimonials.customers.customer2.name': 'Георги Петров',
  'landing.testimonials.customers.customer2.location': 'Пловдив, България',
  'landing.testimonials.customers.customer2.quote':
    'Услугата за почистване беше изключителна. Определено ще използвам Trudify отново.',
  'landing.testimonials.customers.customer3.name': 'Елена Димитрова',
  'landing.testimonials.customers.customer3.location': 'Варна, България',
  'landing.testimonials.customers.customer3.quote':
    'Бързо, надеждно и достъпно. Точно това, което търсех.',

  'landing.testimonials.professionals.title': 'От специалисти',
  'landing.testimonials.professionals.pro1.name': 'Иван Стоев',
  'landing.testimonials.professionals.pro1.profession': 'Електротехник',
  'landing.testimonials.professionals.pro1.quote':
    'Trudify ми помогна да разширя бизнеса си с постоянен поток от качествени клиенти.',
  'landing.testimonials.professionals.pro2.name': 'Анна Николова',
  'landing.testimonials.professionals.pro2.profession': 'Почистваща',
  'landing.testimonials.professionals.pro2.quote':
    'Лесна за използване платформа. Харесвам как мога да управлявам графика и плащанията си.',
  'landing.testimonials.professionals.pro3.name': 'Димитър Георгиев',
  'landing.testimonials.professionals.pro3.profession': 'Майстор',
  'landing.testimonials.professionals.pro3.quote':
    'Професионална платформа, която ме свързва с клиенти, които ценят качествената работа.',

  // Trust Section
  'landing.trustSection.title': 'Изградена върху доверие',
  'landing.trustSection.subtitle':
    'Вашата сигурност и удовлетвореност са нашите най-важни приоритети',

  // Call to Action
  'landing.cta.title': 'Готови ли сте да започнете?',
  'landing.cta.subtitle': 'Присъединете се към хиляди доволни потребители днес',
  'landing.cta.postTask': 'Публикувайте задача',
  'landing.cta.joinProfessionals': 'Стани професионалист',
  'landing.cta.freeToJoin': 'Безплатно присъединяване, без скрити такси',
  'landing.cta.stats.completedTasks': 'Завършени задачи',
  'landing.cta.stats.activeSpecialists': 'Активни специалисти',
  'landing.cta.stats.averageRating': 'Средна оценка',
  'landing.cta.stats.contractTemplates': 'Правни шаблони',

  // Task Card
  'taskCard.apply': 'Кандидатствай',
  'taskCard.anonymous': 'Анонимен',
  'taskCard.budget.from': 'от',
  'taskCard.budget.to': 'до',
  'taskCard.budget.negotiable': 'За договаряне',
  'taskCard.deadline.flexible': 'Гъвкав',
  'taskCard.deadline.today': 'Днес',
  'taskCard.deadline.tomorrow': 'Утре',
  'taskCard.deadline.days': 'дни',
  'taskCard.category.home_repair': 'Домашни ремонти',
  'taskCard.category.delivery_transport': 'Доставки и транспорт',
  'taskCard.category.personal_care': 'Лична грижа',
  'taskCard.category.personal_assistant': 'Личен асистент',
  'taskCard.category.learning_fitness': 'Обучение и фитнес',
  'taskCard.category.other': 'Други',

  // Category Groups
  'categoryGroups.homeRepair': 'Дом и ремонти',
  'categoryGroups.cleaning': 'Почистване',
  'categoryGroups.deliveryTransport': 'Доставки и транспорт',
  'categoryGroups.personalCare': 'Лична грижа',
  'categoryGroups.professional': 'Професионални услуги',
  'categoryGroups.creative': 'Творчески услуги',
  'categoryGroups.events': 'Събития',
  'categoryGroups.beauty': 'Красота',
  'categoryGroups.other': 'Други',

  // Categories - Comprehensive list (legacy keys - kept for backward compatibility)
  'categories.plumbing': 'Водопровод',
  'categories.electrical': 'Електричество',
  'categories.hvac': 'Климатици и отопление',
  'categories.carpentry': 'Дърводелство',
  'categories.painting': 'Боядисване',
  'categories.flooring': 'Подови настилки',
  'categories.roofing': 'Покриви',
  'categories.homeRenovation': 'Ремонти на домове',
  'categories.applianceRepair': 'Ремонт на уреди',
  'categories.handyman': 'Майстор',
  'categories.houseCleaning': 'Почистване на дом',
  'categories.deepCleaning': 'Дълбоко почистване',
  'categories.carpetCleaning': 'Почистване на килими',
  'categories.windowCleaning': 'Почистване на прозорци',
  'categories.gardenMaintenance': 'Поддръжка на градини',
  'categories.landscaping': 'Озеленяване',
  'categories.delivery': 'Доставки',
  'categories.moving': 'Преместване',
  'categories.taxiDriver': 'Такси',
  'categories.courier': 'Куриер',
  'categories.babysitting': 'Детегледане',
  'categories.elderlyCare': 'Грижа за възрастни',
  'categories.petSitting': 'Грижа за домашни любимци',
  'categories.personalTrainer': 'Личен треньор',
  'categories.massageTherapy': 'Масаж',
  'categories.tutoring': 'Уроци',
  'categories.translation': 'Превод',
  'categories.accounting': 'Счетоводство',
  'categories.legalServices': 'Юридически услуги',
  'categories.consulting': 'Консултантство',
  'categories.graphicDesign': 'Графичен дизайн',
  'categories.webDevelopment': 'Уеб разработка',
  'categories.photography': 'Фотография',
  'categories.videography': 'Видеография',
  'categories.writing': 'Писане',
  'categories.musicLessons': 'Музикални уроци',
  'categories.eventPlanning': 'Организиране на събития',
  'categories.catering': 'Кетъринг',
  'categories.djServices': 'DJ услуги',
  'categories.hairdressing': 'Фризьорство',
  'categories.makeupArtist': 'Грим',
  'categories.nailServices': 'Маникюр и педикюр',
  'categories.other': 'Други',

  // Categories Page
  'categories.pageTitle': 'Разглеждане на всички категории',
  'categories.pageSubtitle': 'Намерете перфектния професионалист за всяка задача',
  'categories.searchPlaceholder': 'Търсене на услуги... (напр. водопроводчик, почистване, уроци)',
  'categories.ctaTitle': 'Не намирате това, което търсите?',
  'categories.ctaSubtitle': 'Публикувайте задачата си и нека професионалистите дойдат при вас',

  // Main Categories (centralized categories feature)
  'categories.main.homeServices.title': 'Домашни услуги',
  'categories.main.homeServices.description': 'Водопровод, електричество, майсторски услуги',
  'categories.main.renovation.title': 'Ремонт и строителство',
  'categories.main.renovation.description': 'Ремонти, боядисване, облицовка',
  'categories.main.moving.title': 'Преместване и транспорт',
  'categories.main.moving.description': 'Преместване, товарен транспорт, товарачи',
  'categories.main.cleaning.title': 'Услуги за почистване',
  'categories.main.cleaning.description': 'Почистване на дом, дълбоко почистване, почистване на офис',
  'categories.main.personal.title': 'Лични услуги',
  'categories.main.personal.description': 'Детегледане, уроци, грижа за домашни любимци',
  'categories.main.tech.title': 'Технологии и дигитални',
  'categories.main.tech.description': 'Ремонт на компютри, IT поддръжка, уеб разработка',

  // Main Categories - NEW (26 total)
  'categories.main.applianceRepair.title': 'Ремонт на техника',
  'categories.main.applianceRepair.description': 'Ремонт на уреди, компютри и електроника',
  'categories.main.courierServices.title': 'Куриерски услуги',
  'categories.main.courierServices.description': 'Доставка на храна, лекарства и пратки',
  'categories.main.onlineWork.title': 'Работа в интернет',
  'categories.main.onlineWork.description': 'Въвеждане на данни, изследвания, транскрипция',
  'categories.main.handyman.title': 'Домашен майстор',
  'categories.main.handyman.description': 'Водопроводчик, електротехник, ключар',
  'categories.main.finishingWork.title': 'Довършителни работи',
  'categories.main.finishingWork.description': 'Ремонт на апартамент, плочки, мазилка',
  'categories.main.constructionWork.title': 'Строителни работи',
  'categories.main.constructionWork.description': 'Зидария, заваръчни работи, дърводелство',
  'categories.main.furnitureWork.title': 'Мебелни работи',
  'categories.main.furnitureWork.description': 'Производство, ремонт и реставрация на мебели',
  'categories.main.cleaningServices.title': 'Почистващи услуги',
  'categories.main.cleaningServices.description': 'Почистване на дом, офис и след ремонт',
  'categories.main.logistics.title': 'Логистика',
  'categories.main.logistics.description': 'Товарен транспорт, преместване, товарачи',
  'categories.main.householdServices.title': 'Домакински услуги',
  'categories.main.householdServices.description': 'Детегледачи, градинарство, домакини',
  'categories.main.petServices.title': 'Услуги за животни',
  'categories.main.petServices.description': 'Грижа за кучета, котки и други домашни любимци',
  'categories.main.beautyHealth.title': 'Красота и здраве',
  'categories.main.beautyHealth.description': 'Масажи, маникюр, козметология',
  'categories.main.autoRepair.title': 'Ремонт на автомобили',
  'categories.main.autoRepair.description': 'Диагностика, поддръжка и ремонт на автомобили',
  'categories.main.digitalMarketing.title': 'Дигитален маркетинг',
  'categories.main.digitalMarketing.description': 'SEO, контекстна реклама, маркетинг в социалните мрежи',
  'categories.main.aiServices.title': 'AI услуги',
  'categories.main.aiServices.description': 'AI разработка, консултации и анализ на данни',
  'categories.main.onlineAdvertising.title': 'Онлайн реклама',
  'categories.main.onlineAdvertising.description': 'Поставяне на реклами в интернет',
  'categories.main.advertisingDistribution.title': 'Разпространение на реклама',
  'categories.main.advertisingDistribution.description': 'Раздаване на листовки, лепене на плакати',
  'categories.main.webDevelopment.title': 'Уеб разработка',
  'categories.main.webDevelopment.description': 'Създаване на уебсайтове и приложения',
  'categories.main.design.title': 'Дизайн',
  'categories.main.design.description': 'Лого дизайн, интериорен дизайн, печатен дизайн',
  'categories.main.photoVideo.title': 'Фото и видео услуги',
  'categories.main.photoVideo.description': 'Фотография, видеозаснемане, монтаж',
  'categories.main.tutoring.title': 'Услуги на репетитори',
  'categories.main.tutoring.description': 'Уроци по предмети, езици и музика',
  'categories.main.businessServices.title': 'Бизнес услуги',
  'categories.main.businessServices.description': 'Счетоводство, юридически услуги, недвижими имоти',
  'categories.main.translationServices.title': 'Преводачески услуги',
  'categories.main.translationServices.description': 'Писмен и устен превод',
  'categories.main.trainerServices.title': 'Услуги на треньори',
  'categories.main.trainerServices.description': 'Йога, фитнес, спортни тренировки',
  'categories.main.eventPlanning.title': 'Организация на събития',
  'categories.main.eventPlanning.description': 'Водещи, аниматори, кетъринг',
  'categories.main.volunteerHelp.title': 'Доброволческа помощ',
  'categories.main.volunteerHelp.description': 'Помощ за възрастни хора и транспорт',

  // Subcategories - NEW (135 total)
  // Handyman
  'categories.sub.plumber': 'Водопроводчик',
  'categories.sub.electrician': 'Електротехник',
  'categories.sub.handymanService': 'Майстор',
  'categories.sub.carpenter': 'Дърводелец',
  'categories.sub.locksmith': 'Ключар',

  // Appliance Repair
  'categories.sub.largeApplianceRepair': 'Ремонт на едра техника',
  'categories.sub.smallApplianceRepair': 'Ремонт на дребна техника',
  'categories.sub.computerHelp': 'Компютърна помощ',
  'categories.sub.digitalTechRepair': 'Ремонт на дигитална техника',
  'categories.sub.phoneRepair': 'Ремонт на телефони',

  // Finishing Work
  'categories.sub.apartmentRenovation': 'Ремонт на апартамент',
  'categories.sub.tileInstallation': 'Полагане на плочки',
  'categories.sub.plastering': 'Мазилка',
  'categories.sub.insulation': 'Изолация',
  'categories.sub.heatingInstallation': 'Монтаж на отопление',

  // Construction Work
  'categories.sub.generalLabor': 'Общо строителство',
  'categories.sub.welding': 'Заваръчни работи',
  'categories.sub.turning': 'Стругарски работи',
  'categories.sub.carpentry': 'Дърводелски работи',
  'categories.sub.bricklaying': 'Зидария',

  // Furniture Work
  'categories.sub.furnitureManufacturing': 'Производство на мебели',
  'categories.sub.furnitureRepair': 'Ремонт на мебели',
  'categories.sub.furnitureAssembly': 'Сглобяване на мебели',
  'categories.sub.furnitureRestoration': 'Реставрация на мебели',
  'categories.sub.furnitureUpholstery': 'Тапициране на мебели',

  // Cleaning Services
  'categories.sub.apartmentCleaning': 'Почистване на апартамент',
  'categories.sub.deepCleaning': 'Дълбоко почистване',
  'categories.sub.postRenovationCleaning': 'Почистване след ремонт',
  'categories.sub.dryCleaning': 'Химическо чистене',
  'categories.sub.houseCleaning': 'Почистване на къща',

  // Logistics
  'categories.sub.cargoTransport': 'Товарен транспорт',
  'categories.sub.loaders': 'Товарачи',
  'categories.sub.constructionWasteRemoval': 'Извозване на строителни отпадъци',
  'categories.sub.furnitureApplianceMoving': 'Преместване на мебели и техника',
  'categories.sub.officeRelocation': 'Преместване на офис',

  // Household Services
  'categories.sub.gardening': 'Градинарство',
  'categories.sub.babysitting': 'Детегледач',
  'categories.sub.caregiver': 'Болногледач',
  'categories.sub.housekeeper': 'Домакин',
  'categories.sub.sewing': 'Шиене',

  // Auto Repair
  'categories.sub.roadsideAssistance': 'Пътна помощ',
  'categories.sub.maintenanceDiagnostics': 'Поддръжка и диагностика',
  'categories.sub.autoElectrical': 'Авто електрика',
  'categories.sub.bodyWork': 'Авто тенекеджийство',
  'categories.sub.engineRepair': 'Ремонт на двигатели',

  // Courier Services
  'categories.sub.courierDelivery': 'Куриерска доставка',
  'categories.sub.groceryDelivery': 'Доставка на хранителни стоки',
  'categories.sub.foodDelivery': 'Доставка на храна',
  'categories.sub.medicineDelivery': 'Доставка на лекарства',
  'categories.sub.courierByCar': 'Куриер с автомобил',

  // Digital Marketing
  'categories.sub.contextualAdvertising': 'Контекстна реклама',
  'categories.sub.seoOptimization': 'SEO оптимизация',
  'categories.sub.copywriting': 'Копирайтинг',
  'categories.sub.socialMediaMarketing': 'Маркетинг в социалните мрежи',
  'categories.sub.emailMarketing': 'Имейл маркетинг',

  // AI Services
  'categories.sub.aiContentCreation': 'AI създаване на съдържание',
  'categories.sub.aiConsulting': 'AI консултации',
  'categories.sub.aiDevelopment': 'AI разработка',
  'categories.sub.aiDataAnalytics': 'AI анализ на данни',

  // Online Advertising
  'categories.sub.onlineAdPlacement': 'Поставяне на онлайн реклами',

  // Advertising Distribution
  'categories.sub.flyerDistribution': 'Раздаване на листовки',
  'categories.sub.posterHanging': 'Лепене на плакати',
  'categories.sub.mailboxAdvertising': 'Реклама по пощенски кутии',
  'categories.sub.sandwichBoardAdvertising': 'Реклама със сандвич панели',

  // Design
  'categories.sub.logoDesign': 'Дизайн на лого',
  'categories.sub.interiorDesign': 'Интериорен дизайн',
  'categories.sub.webAppDesign': 'Дизайн на уеб и приложения',
  'categories.sub.printDesign': 'Дизайн за печат',
  'categories.sub.printingServices': 'Печатни услуги',

  // Tutoring
  'categories.sub.subjectTutors': 'Репетитори по предмети',
  'categories.sub.languageTutors': 'Езикови преподаватели',
  'categories.sub.academicWriting': 'Академично писане',
  'categories.sub.musicTeachers': 'Учители по музика',
  'categories.sub.drivingInstructors': 'Инструктори по шофиране',

  // Web Development
  'categories.sub.websiteCreation': 'Създаване на уебсайт',
  'categories.sub.websiteImprovements': 'Подобрения на уебсайт',
  'categories.sub.landingPage': 'Лендинг страница',
  'categories.sub.websiteLayout': 'Верстка на уебсайт',
  'categories.sub.qaTesting': 'QA тестване',

  // Online Work
  'categories.sub.dataResearch': 'Изследване на данни',
  'categories.sub.contentFilling': 'Попълване на съдържание',
  'categories.sub.typing': 'Въвеждане на текст',
  'categories.sub.dataEntry': 'Въвеждане на данни',
  'categories.sub.transcription': 'Транскрипция',

  // Photo/Video Services
  'categories.sub.photographer': 'Фотограф',
  'categories.sub.videographer': 'Видеограф',
  'categories.sub.photoEditing': 'Обработка на снимки',
  'categories.sub.videoEditing': 'Видео монтаж',
  'categories.sub.videoDigitization': 'Дигитализация на видео',

  // Business Services
  'categories.sub.accounting': 'Счетоводство',
  'categories.sub.legalServices': 'Юридически услуги',
  'categories.sub.realEstate': 'Недвижими имоти',
  'categories.sub.callCenter': 'Кол център',
  'categories.sub.financialServices': 'Финансови услуги',

  // Pet Services
  'categories.sub.catCare': 'Грижа за котки',
  'categories.sub.dogCare': 'Грижа за кучета',
  'categories.sub.petHotel': 'Хотел за домашни любимци',
  'categories.sub.petTransportation': 'Транспорт на домашни любимци',
  'categories.sub.fishCare': 'Грижа за риби',

  // Beauty & Health
  'categories.sub.massage': 'Масаж',
  'categories.sub.nailCare': 'Грижа за нокти',
  'categories.sub.cosmetology': 'Козметология',
  'categories.sub.lashCare': 'Грижа за мигли',
  'categories.sub.browCare': 'Грижа за вежди',

  // Event Planning
  'categories.sub.eventHost': 'Водещ на събития',
  'categories.sub.musicEntertainment': 'Музикална забава',
  'categories.sub.animators': 'Аниматори',
  'categories.sub.catering': 'Кетъринг',
  'categories.sub.bakingDesserts': 'Печене и десерти',

  // Translation Services
  'categories.sub.writtenTranslation': 'Писмен превод',
  'categories.sub.translationEditing': 'Редакция на превод',
  'categories.sub.documentTranslation': 'Превод на документи',
  'categories.sub.oralTranslation': 'Устен превод',
  'categories.sub.technicalTranslation': 'Технически превод',

  // Trainer Services
  'categories.sub.yoga': 'Йога',
  'categories.sub.groupFitness': 'Групови фитнес занимания',
  'categories.sub.teamSports': 'Отборни спортове',
  'categories.sub.waterSports': 'Водни спортове',
  'categories.sub.martialArts': 'Бойни изкуства',

  // Volunteer Help
  'categories.sub.elderlyAssistance': 'Помощ за възрастни хора',
  'categories.sub.volunteerTransportation': 'Доброволчески транспорт',
  'categories.sub.fuelDelivery': 'Доставка на гориво',
  'categories.sub.housingAssistance': 'Помощ с жилище',
  'categories.sub.volunteerFoodDelivery': 'Доброволческа доставка на храна',

  // Professional Detail Page
  'professionalDetail.about': 'За професионалиста',
  'professionalDetail.reviews': 'отзива',
  'professionalDetail.online': 'Онлайн',
  'professionalDetail.offline': 'Видян наскоро',
  'professionalDetail.verified.phone': 'Телефон',
  'professionalDetail.verified.id': 'Документ',
  'professionalDetail.stats.completedTasks': 'Задачи',
  'professionalDetail.stats.yearsExperience': 'Години',
  'professionalDetail.stats.responseTime': 'Отговор',
  'professionalDetail.actions.proposeTask': 'Предложи задача',
  'professionalDetail.actions.contact': 'Контакт',
  'professionalDetail.actions.askQuestion': 'Задай въпрос',
  'professionalDetail.actions.saveToFavorites': 'Запази в любими',
  'professionalDetail.contactHours': 'Достъпен',
  'professionalDetail.services.title': 'Услуги и цени',
  'professionalDetail.services.pricingNote.title': 'Информация за цените',
  'professionalDetail.services.pricingNote.description':
    'Окончателните цени се договарят индивидуално въз основа на сложността и изискванията на задачата.',
  'professionalDetail.portfolio.title': 'Моите примери',
  'professionalDetail.portfolio.noWork': 'Все още няма примери',
  'professionalDetail.portfolio.before': 'Преди',
  'professionalDetail.portfolio.after': 'След',
  'professionalDetail.portfolio.viewMore': 'Виж всички примери',
  'professionalDetail.portfolio.showcase': 'Професионални примери от работата',
  'professionalDetail.completedTasks.title': 'Завършени задачи',
  'professionalDetail.completedTasks.noTasks': 'Все още няма завършени задачи',
  'professionalDetail.completedTasks.viewTask': 'Виж задачата',
  'professionalDetail.completedTasks.completedOn': 'Завършена на',
  'professionalDetail.reviews.title': 'Отзиви и оценки',
  'professionalDetail.reviews.count': 'отзива',
  'professionalDetail.reviews.recentRating': 'Скорошна оценка',
  'professionalDetail.reviews.excellent': 'Отлично',
  'professionalDetail.reviews.noReviews': 'Все още няма отзиви',
  'professionalDetail.reviews.beFirst': 'Бъди първият, който ще даде отзив',
  'professionalDetail.reviews.showMore': 'Покажи всички отзиви',
  'professionalDetail.reviews.allReviews': 'Всички отзиви',
  'professionalDetail.reviews.avgRating': 'Средна оценка',
  'professionalDetail.reviews.more': 'още',
  'professionalDetail.completedTasks.stats.tasksCompleted': 'Завършени задачи',
  'professionalDetail.completedTasks.stats.avgRating': 'Средна оценка',
  'professionalDetail.completedTasks.stats.fiveStarTasks': '5-звездни задачи',
  'professionalDetail.verified': 'Потвърден',
  'common.anonymous': 'Анонимен потребител',

  // Footer
  'footer.company.description':
    'Свързваме хората с квалифицирани професионалисти за всякакъв вид услуги в България.',
  'footer.quickLinks.title': 'Бързи връзки',
  'footer.quickLinks.howItWorks': 'Как работи',
  'footer.quickLinks.categories': 'Категории',
  'footer.quickLinks.forProfessionals': 'За професионалисти',
  'footer.quickLinks.security': 'Сигурност',
  'footer.quickLinks.help': 'Помощ',
  'footer.legal.title': 'Правни',
  'footer.legal.terms': 'Общи условия',
  'footer.legal.privacy': 'Поверителност',
  'footer.legal.gdpr': 'GDPR',
  'footer.legal.cookies': 'Cookies',
  'footer.legal.complaints': 'Жалби',
  'footer.contact.title': 'Контакти',
  'footer.contact.subtitle': 'Свържете се с нас за въпроси и поддръжка',
  'footer.language.label': 'Език',
  'footer.copyright': '© 2025 Obod Soft LTD. Всички права запазени.',

  // Task Details
  'taskDetail.backToTasks': 'Обратно към задачите',
  'taskDetail.requirements': 'Изисквания:',
  'taskDetail.keyInformation': 'Ключова информация',
  'taskDetail.client': 'Клиент',
  'taskDetail.loginForMore': 'Влезте за повече',
  'taskDetail.loginMessage':
    'Влезте в акаунта си за да видите пълната информация',
  'taskDetail.completedTasks': 'завършени задачи',
  'taskDetail.memberSince': 'Член от',
  'taskDetail.similarTasks': 'Подобни задачи',
  'taskDetail.apply': 'Кандидатствай за задачата',
  'taskDetail.askQuestion': 'Задай въпрос',
  'taskDetail.applicationsCount': 'души',
  'taskDetail.timeAgo': 'преди',
  'taskDetail.today': 'Днес',
  'taskDetail.tomorrow': 'Утре',
  'taskDetail.days': 'дни',
  'taskDetail.flexible': 'Гъвкав',
  'taskDetail.negotiable': 'По договаряне',
  'taskDetail.urgency.same_day': 'Спешно - днес',
  'taskDetail.urgency.within_week': 'В рамките на седмица',
  'taskDetail.urgency.flexible': 'Гъвкав срок',
  'taskDetail.urgency.default': 'Неуточнен',
  'taskDetail.status': 'Статус',
  'taskDetail.statusTypes.vacant': 'Свободна',
  'taskDetail.statusTypes.applied': 'Кандидатствал',
  'taskDetail.statusTypes.done': 'Завършена',
  'taskDetail.statusTypes.archived': 'Архивирана',
  'taskDetail.appliedTooltip': 'Вие сте кандидатствали за тази задача. Клиентът може да приеме или отхвърли вашата кандидатура.',

  'taskDetail.share': 'Сподели',
  'taskDetail.activity': 'Активност по задачата',
  'taskDetail.applications': 'Кандидатури',
  'taskDetail.questions': 'Въпроси',
  'taskDetail.accept': 'Приеми',
  'taskDetail.reject': 'Отхвърли',
  'taskDetail.message': 'Съобщение',
  'taskDetail.reply': 'Отговори',
  'taskDetail.yourReply': 'Вашия отговор:',
  'taskDetail.price': 'Цена:',
  'taskDetail.tasks': 'задачи',

  // Auth Slide-over
  'auth.applyForTask': 'Кандидатствай за задачата',
  'auth.askQuestion': 'Задай въпрос',
  'auth.createTask': 'Създай задача',
  'auth.loginToContinue': 'За да продължите, моля влезте в акаунта си',
  'auth.applyDescription':
    'Изпратете заявка на клиента и получете възможност да работите по тази задача.',
  'auth.questionDescription':
    'Задайте въпрос на клиента преди да кандидатствате за задачата.',
  'auth.createTaskDescription':
    'Създайте нова задача и намерете доверени професионалисти да завършат работата ви.',
  'auth.loginDescription':
    'Влезте в акаунта си за да управлявате задачи и да се свързвате с професионалисти.',
  'auth.email': 'Имейл адрес',
  'auth.password': 'Парола',
  'auth.rememberMe': 'Запомни ме',
  'auth.forgotPassword': 'Забравена парола?',
  'auth.loginOrRegister': 'Влизане / Регистрация',
  'auth.loginOrRegisterToContinue': 'За да продължите, моля влезте или се регистрирайте',
  'auth.loginOrRegisterDescription': 'Въведете данните си за достъп до акаунта или създайте нов.',
  'auth.continue': 'Продължи',
  'auth.login': 'Влизане',
  'auth.or': 'или',
  'auth.noAccount': 'Нямате акаунт?',
  'auth.createAccount': 'Създайте акаунт',
  'auth.whyRegister': 'Защо да се регистрирате?',
  'auth.benefit1': '• Кандидатствайте за задачи',
  'auth.benefit2': '• Общувайте директно с клиентите',
  'auth.benefit3': '• Проследявайте историята си',
  'auth.benefit4': '• Получавайте известия за нови задачи',
  'auth.continueWith': 'Продължи с',

  // Application Dialog
  'application.title': 'Кандидатствайте за тази задача',
  'application.proposedPrice': 'Вашата цена',
  'application.pricePlaceholder': 'Въведете вашата цена в лева',
  'application.timeline': 'Кога можете да започнете?',
  'application.timelineToday': 'Днес',
  'application.timeline3days': 'В рамките на 3 дни',
  'application.timelineWeek': 'В рамките на седмица',
  'application.timelineFlexible': 'Гъвкав',
  'application.message': 'Защо сте най-подходящ?',
  'application.messagePlaceholder': 'Споделете вашия релевантен опит и защо сте перфектни за тази задача...',
  'application.messageInfo': 'Фокусирайте се върху уменията и опита си. Контактни данни можете да споделите след приемане на кандидатурата.',
  'application.characterCount': '{{current}}/{{max}} символа',
  'application.submit': 'Изпрати кандидатура',
  'application.submitting': 'Изпращане...',
  'application.cancel': 'Отказ',
  'application.success': 'Кандидатурата е изпратена!',
  'application.successMessage': 'Собственикът на задачата ще прегледа вашата кандидатура и скоро ще отговори.',
  'application.viewApplication': 'Вижте моята кандидатура',
  'application.browseOther': 'Разгледайте други задачи',
  'application.errors.priceRequired': 'Цената е задължителна',
  'application.errors.priceMin': 'Цената трябва да бъде по-голяма от 0',
  'application.errors.timelineRequired': 'Графикът е задължителен',
  'application.errors.messageRequired': 'Съобщението е задължително',
  'application.errors.messageMin': 'Съобщението трябва да бъде поне 30 символа',
  'application.errors.messageMax': 'Съобщението не може да надвишава 500 символа',
  'application.errors.noPhoneNumbers': 'Телефонни номера не са разрешени в кандидатури. Можете да обменяте контактна информация след приемане на кандидатурата.',
  'application.errors.noUrls': 'URL адреси и връзки не са разрешени в кандидатури. Можете да споделите портфолиото си след приемане на кандидатурата.',
  'application.errors.noEmails': 'Имейл адреси не са разрешени в кандидатури. Можете да обменяте контактна информация след приемане на кандидатурата.',
  'application.alreadyApplied': 'Вече сте кандидатствали за тази задача',
  'application.cannotApplyOwnTask': 'Не можете да кандидатствате за собствената си задача',

  'message.taskCreated': 'Задачата е създадена успешно!',
  'message.profileUpdated': 'Профилът е актуализиран успешно!',
  'message.applicationSubmitted': 'Заявлението е подадено успешно!',
  'error.generic': 'Нещо се обърка. Моля, опитайте отново.',
  'error.network': 'Грешка в мрежата. Моля, проверете връзката си.',
  'error.unauthorized':
    'Трябва да влезете в профила си, за да достъпите тази страница.',

  // Profile Page
  'profile.completion': 'Довършване на профил',
  'profile.settings': 'Настройки',
  'profile.tabs.customer': 'Клиент',
  'profile.tabs.professional': 'Професионалист',
  'profile.email': 'Имейл',
  'profile.phone': 'Телефон',
  'profile.location': 'Местоположение',
  'profile.memberSince': 'Член от',
  'profile.editPersonalInfo': 'Редактиране на лични данни',
  'profile.statistics': 'Статистики',
  'profile.verified': 'Потвърден',
  'profile.completed': 'Завършено',
  'profile.active': 'Активно',

  // Avatar Upload
  'profile.avatar.changeAvatar': 'Промяна на аватар',
  'profile.avatar.selectImage': 'Избери изображение',
  'profile.avatar.remove': 'Премахни',
  'profile.avatar.supportedFormats': 'Поддържани формати: JPG, PNG, WebP (макс 5MB)',
  'profile.avatar.invalidFileType': 'Невалиден тип файл. Моля изберете JPG, PNG или WebP изображение.',
  'profile.avatar.fileTooLarge': 'Файлът е твърде голям. Моля изберете изображение под 5MB.',
  'profile.avatar.uploadError': 'Неуспешно качване на изображението. Моля опитайте отново.',

  // Statistics Modal
  'profile.statistics.title': 'Статистики на акаунта',
  'profile.statistics.description': 'Преглед на вашите метрики за производителност и обзор на активността',
  'profile.statistics.memberSince': 'Член от',

  // Customer Statistics
  'profile.statistics.customer.overview': 'Преглед на клиента',
  'profile.statistics.customer.performance': 'Метрики за производителност',
  'profile.statistics.customer.successRate': 'Процент на успех',
  'profile.statistics.customer.responseRate': 'Процент на отговор',

  // Professional Statistics
  'profile.statistics.professional.business': 'Бизнес преглед',
  'profile.statistics.professional.performance': 'Метрики за производителност',
  'profile.statistics.professional.repeatClients': 'Повторни клиенти',
  'profile.statistics.professional.monthlyEarnings': 'Месечни доходи',

  // Customer Profile
  'profile.customer.personalInfo': 'Лична информация',
  'profile.customer.statistics': 'Статистики',
  'profile.customer.tasksPosted': 'Публикувани задачи',
  'profile.customer.tasksCompleted': 'Завършени задачи',
  'profile.customer.averageRating': 'Средна оценка',
  'profile.customer.totalSpent': 'Общо похарчено',
  'profile.customer.recentActivity': 'Последна активност',
  'profile.customer.taskCompleted': 'Завършена задача',
  'profile.customer.taskPosted': 'Публикувана задача',
  'profile.customer.viewAllTasks': 'Виж всички задачи',
  'profile.customer.notificationPreferences': 'Настройки за известия',
  'profile.customer.smsNotifications': 'SMS известия',
  'profile.customer.smsNotificationsDesc': 'Получавайте важни актуализации чрез текстови съобщения',

  // Professional Profile
  'profile.professional.info': 'Професионална информация',
  'profile.professional.title': 'Професионална титла',
  'profile.professional.description': 'Описание',
  'profile.professional.hourlyRate': 'Часова ставка',
  'profile.professional.availability': 'Наличност',
  'profile.professional.skills': 'Умения',
  'profile.professional.statistics': 'Статистики за работа',
  'profile.professional.completedJobs': 'Завършени работи',
  'profile.professional.totalEarnings': 'Общи приходи',
  'profile.professional.responseTime': 'Време за отговор',
  'profile.professional.performance': 'Показатели за работа',
  'profile.professional.profileViews': 'Прегледи на профил',
  'profile.professional.completionRate': 'Процент на завършване',
  'profile.professional.monthlyGrowth': 'Месечен растеж',
  'profile.professional.recentWork': 'Последни работи',
  'profile.professional.viewPortfolio': 'Виж портфолио',
  'profile.professional.setupTitle': 'Настройте професионалния си профил',
  'profile.professional.setupDescription': 'Попълнете професионалния си профил, за да започнете да получавате възможности за работа и да се свързвате с клиенти.',
  'profile.professional.setupProfile': 'Настройте професионален профил',
  'profile.professional.businessSettings': 'Бизнес настройки',
  'profile.professional.paymentMethod': 'Метод на плащане',
  'profile.professional.vatNumber': 'ДДС номер',
  'profile.professional.serviceArea': 'Обслужвана област',
  'profile.professional.setupFormDescription': 'Попълнете професионалната си информация, за да покажете уменията и опита си.',
  'profile.professional.selectCategories': 'Избери категории',
  'profile.professional.serviceCategories': 'Категории услуги',
  'profile.professional.verificationTrust': 'Верификация и доверие',
  'profile.professional.phoneVerification': 'Верификация на телефон',
  'profile.professional.phoneVerificationRequired': 'Задължително за всички професионалисти',
  'profile.professional.verified': 'Верифициран',
  'profile.professional.verifyPhone': 'Верифицирай телефон',
  'profile.professional.acceptedPaymentMethods': 'Приемани методи на плащане',
  'profile.professional.businessHours': 'Работно време',
  'profile.professional.businessHoursPlaceholder': 'например: Пон-Пет 8:00-18:00, Съб 9:00-14:00',
  'profile.professional.weekdaysLabel': 'Делнични дни (Пон-Пет)',
  'profile.professional.weekendLabel': 'Уикенд (Съб-Нед)',
  'profile.professional.startTime': 'Начален час',
  'profile.professional.endTime': 'Краен час',
  'profile.professional.noPaymentMethods': 'Няма избрани методи на плащане',
  'profile.professional.portfolioGallery': 'Портфолио галерия',
  'profile.professional.portfolioDescription': 'Покажете най-добрата си работа с преди/след снимки',
  'profile.professional.addServiceCategories': 'Добавете категории услуги',
  'profile.professional.categoriesHelp': 'Помогнете на клиентите да ви намерят! Изберете услугите, които предлагате, за да започнете да получавате заявки.',

  // Professional Setup Form
  'profile.professional.form.titlePlaceholder': 'например: Full Stack Developer, UX Designer, Маркетинг консултант',
  'profile.professional.form.descriptionPlaceholder': 'Опишете професионалния си опит, експертиза и това, което ви прави уникални...',
  'profile.professional.form.experience': 'Ниво на опит',
  'profile.professional.form.portfolio': 'URL на портфолио (по избор)',
  'profile.professional.form.portfolioDescription': 'Линк към вашия уебсайт, GitHub или онлайн портфолио',
  'profile.professional.form.selectedSkills': 'Избрани умения',
  'profile.professional.form.searchSkills': 'Търсене на умения...',
  'profile.professional.form.suggestedSkills': 'Популярни умения',
  'profile.professional.form.addCustomSkill': 'Добавете персонализирано умение',
  'profile.professional.form.customSkillPlaceholder': 'Въведете име на умение',
  'profile.professional.form.moreSkillsAvailable': 'и още {{count}}...',
  'profile.professional.form.skillsLimitNotice': 'Препоръчваме да изберете топ 10 умения за най-добри резултати.',
  'profile.professional.form.submitting': 'Създаване на профил...',
  'profile.professional.form.createProfile': 'Създайте професионален профил',

  // Experience Options
  'profile.professional.form.experienceOptions.beginner': '0-1 години',
  'profile.professional.form.experienceOptions.intermediate': '2-5 години',
  'profile.professional.form.experienceOptions.experienced': '5-10 години',
  'profile.professional.form.experienceOptions.expert': '10+ години',

  // Availability Options
  'profile.professional.form.availabilityOptions.available': 'Наличен',
  'profile.professional.form.availabilityOptions.busy': 'Зает',
  'profile.professional.form.availabilityOptions.unavailable': 'Недостъпен',

  // Form Validation
  'profile.professional.form.validation.titleRequired': 'Професионалната титла е задължителна (минимум 3 символа)',
  'profile.professional.form.validation.descriptionRequired': 'Описанието е задължително (минимум 20 символа)',
  'profile.professional.form.validation.rateRequired': 'Часовата ставка трябва да е по-голяма от 0',
  'profile.professional.form.validation.skillsRequired': 'Моля, изберете поне едно умение',

  // Settings Modal
  'profile.settings.description': 'Управлявайте предпочитанията и настройките за поверителност на акаунта си',
  'profile.settings.notifications': 'Известия',
  'profile.settings.emailNotifications': 'Имейл известия',
  'profile.settings.emailNotificationsDesc': 'Получавайте актуализации за задачите и акаунта си',
  'profile.settings.taskUpdates': 'Актуализации на задачи',
  'profile.settings.taskUpdatesDesc': 'Получавайте известия при актуализации на задачи',
  'profile.settings.marketingEmails': 'Маркетингови имейли',
  'profile.settings.marketingEmailsDesc': 'Получавайте съвети и промоционално съдържание',
  'profile.settings.pushNotifications': 'Push известия',
  'profile.settings.pushNotificationsDesc': 'Получавайте незабавни известия на устройството си',
  'profile.settings.weeklyDigest': 'Седмично обобщение',
  'profile.settings.weeklyDigestDesc': 'Получавайте седмично резюме на активността и възможностите си',
  'profile.settings.privacy': 'Поверителност',
  'profile.settings.profileVisibility': 'Видимост на профил',
  'profile.settings.profileVisibilityDesc': 'Направете профила си видим за потенциални клиенти',
  'profile.settings.showContactInfo': 'Показване на контактна информация',
  'profile.settings.showContactInfoDesc': 'Покажете контактната си информация публично',
  'profile.settings.interface': 'Интерфейс',
  'profile.settings.darkMode': 'Тъмен режим',
  'profile.settings.darkModeDesc': 'Превключете към интерфейс с тъмна тема',
  'profile.settings.dangerZone': 'Опасна зона',
  'profile.settings.deleteAccount': 'Изтриване на акаунт',
  'profile.settings.deleteAccountDesc': 'Окончателно изтриване на акаунта и всички данни',
  'profile.settings.deleteAccountConfirm': 'Изтриването на акаунт скоро ще бъде внедрено',

  // Customer Profile Form
  'profile.form.name': 'Пълно име',
  'profile.form.saving': 'Запазване...',
  'profile.form.validation.nameRequired': 'Името е задължително (минимум 2 символа)',
  'profile.form.validation.emailRequired': 'Имейлът е задължителен',
  'profile.form.validation.emailInvalid': 'Моля, въведете валиден имейл адрес',
  'profile.form.validation.phoneRequired': 'Телефонният номер е задължителен',
  'profile.form.validation.phoneInvalid': 'Моля, въведете валиден телефонен номер',
  'profile.form.validation.locationRequired': 'Местоположението е задължително (минимум 3 символа)',

  // Locations
  'locations.sofiaCenter': 'София, Център',
  'locations.sofiaLyulin': 'София, Люлин',
  'locations.sofiaStudentski': 'София, Студентски град',
  'locations.sofiaVitosha': 'София, Витоша',
  'locations.plovdiv': 'Пловдив',
  'locations.varna': 'Варна',
  'locations.burgas': 'Бургас',
  'locations.ruse': 'Русе',
  'locations.staraZagora': 'Стара Загора',

  // Notifications
  'notifications.title': 'Известия',
  'notifications.markAllRead': 'Маркирай всички като прочетени',
  'notifications.tabAll': 'Всички',
  'notifications.tabApplications': 'Кандидатури',
  'notifications.tabTasks': 'Задачи',
  'notifications.tabMessages': 'Съобщения',
  'notifications.empty.title': 'Все още няма известия',
  'notifications.empty.message': 'Ще получите известие когато някой кандидатства за вашите задачи или отговори на вашите кандидатури.',
  'notifications.empty.filterMessage': 'Няма известия в тази категория.',
  'notifications.emptyUnread.title': 'Вече сте наваксали!',
  'notifications.emptyUnread.message': 'Всички известия са прочетени.',
  'notifications.viewApplication': 'Виж кандидатурата',
  'notifications.viewTask': 'Виж задачата',
};

export default bg;
