const en = {
  welcome: 'Welcome',
  login: 'Log In',
  logout: 'Log Out',
  signup: 'Sign Up',
  search: 'Search',
  browse: 'Browse',
  create: 'Create',
  edit: 'Edit',
  delete: 'Delete',
  cancel: 'Cancel',
  important: 'Important',
  save: 'Save',
  submit: 'Submit',
  loading: 'Loading...',
  error: 'Error',
  success: 'Success',
  back: 'Back',
  next: 'Next',
  previous: 'Previous',
  reviews: 'reviews',

  'nav.home': 'Home',
  'nav.browseTasks': 'Browse Tasks',
  'nav.createTask': 'Post a Task',
  'nav.profile': 'Profile',
  'nav.howItWorks': 'How It Works',
  'nav.categories': 'Categories',
  'nav.forProfessionals': 'Professionals',
  'nav.forCustomers': 'For Customers',
  'nav.myTasks': 'My Tasks',
  'nav.myPostedTasks': 'My Posted Tasks',
  'nav.myApplications': 'My Applications',
  'nav.myWork': 'My Work',
  'nav.help': 'Help',

  'landing.hero.title': 'Your Local Marketplace for Services & Opportunities',
  'landing.hero.subtitle':
    'Trudify connects people who need help with skilled professionals ready to earn. Post your task or find work - trusted, verified, and simple.',
  'landing.hero.getStarted': 'Post a Task',
  'landing.hero.browseServices': 'Find Work',

  'landing.trustIndicators.verified': 'Verified Professionals',
  'landing.trustIndicators.securePayments': 'Secure Payments',
  'landing.trustIndicators.support': '24/7 Support',
  'landing.trustIndicators.freeToUse': 'Free to Use',
  'landing.trustIndicators.communityReviews': 'Community Reviews',
  'landing.trustIndicators.verifiedDescription':
    'All professionals are thoroughly verified',
  'landing.trustIndicators.ratingSystem': '5-Star Rating System',
  'landing.trustIndicators.ratingSystemDescription':
    'Quality assured through community feedback',
  'landing.trustIndicators.dataProtection': 'Data Protection',
  'landing.trustIndicators.dataProtectionDescription':
    'Your personal information is secure',
  'landing.trustIndicators.contracts': 'Legal Protection',
  'landing.trustIndicators.contractsDescription':
    'All work is protected by clear agreements',

  'landing.stats.averageRating': 'average rating',
  'landing.stats.completedTasks': 'completed tasks',
  'landing.categories.activeSpecialists': 'active specialists',

  'landing.trustStats.securityUptime': 'Security Uptime',
  'landing.trustStats.avgRating': 'Average Rating',
  'landing.trustStats.encryption': 'Data Encryption',
  'landing.trustStats.compliance': 'Legal Compliance',

  'landing.categories.title': 'Popular Categories',
  'landing.categories.subtitle':
    'Find specialists for every task - from home repairs to personal assistance',
  'landing.categories.viewAll': 'View All Categories',
  'landing.categories.home': 'Home & Garden',
  'landing.categories.home.description':
    'Electrical, plumbing, cleaning, maintenance',
  'landing.categories.tech': 'Technology',
  'landing.categories.tech.description':
    'IT support, web design, software development',
  'landing.categories.business': 'Business Services',
  'landing.categories.business.description':
    'Administrative tasks, events, consulting',
  'landing.categories.personal': 'Personal Services',
  'landing.categories.personal.description': 'Pet care, childcare, eldercare',
  'landing.categories.education': 'Education & Training',
  'landing.categories.creative': 'Creative Services',

  'landing.featured.title': 'Featured Tasks',
  'landing.featured.subtitle': 'Recent tasks posted by our community',
  'landing.featured.badge': 'Latest Opportunities',
  'landing.featured.viewAll': 'View All Tasks',
  'landing.featured.professionalDesc': 'Find your next opportunity',
  'landing.featured.customerDesc': 'See what others are posting',

  'landing.howItWorks.title': 'How It Works',
  'landing.howItWorks.subtitle':
    'Easy process for finding and completing tasks with verified specialists',
  'landing.howItWorks.forCustomers': 'For Customers',
  'landing.howItWorks.forProfessionals': 'For Professionals',
  'landing.howItWorks.step1.title': 'Post Your Task',
  'landing.howItWorks.step1.description':
    'Describe what you need done and set your budget',
  'landing.howItWorks.step2.title': 'Get Proposals',
  'landing.howItWorks.step2.description':
    'Receive applications from verified professionals',
  'landing.howItWorks.step3.title': 'Choose & Complete',
  'landing.howItWorks.step3.description':
    'Select the best professional and get your task done',

  'landing.howItWorks.customers.step1.title': 'Post Your Task',
  'landing.howItWorks.customers.step1.description':
    'Describe what you need done and set your budget',
  'landing.howItWorks.customers.step2.title': 'Get Proposals',
  'landing.howItWorks.customers.step2.description':
    'Receive applications from verified professionals',
  'landing.howItWorks.customers.step3.title': 'Choose & Complete',
  'landing.howItWorks.customers.step3.description':
    'Select the best professional and get your task done',

  'landing.howItWorks.professionals.step1.title': 'Browse Tasks',
  'landing.howItWorks.professionals.step1.description':
    'Find tasks that match your skills and availability',
  'landing.howItWorks.professionals.step2.title': 'Submit Proposal',
  'landing.howItWorks.professionals.step2.description':
    'Send your best offer and showcase your expertise',
  'landing.howItWorks.professionals.step3.title': 'Complete Work',
  'landing.howItWorks.professionals.step3.description':
    'Deliver quality service and build your reputation',

  'tasks.title': 'Browse Tasks',
  'tasks.subtitle':
    'Find the perfect task that matches your skills and interests',
  'tasks.searchPlaceholder':
    'Search tasks by keywords, categories, or location...',
  'tasks.filters.title': 'Filters',
  'tasks.filters.category': 'Category',
  'tasks.filters.allCategories': 'All Categories',
  'tasks.filters.location': 'Location',
  'tasks.filters.budget': 'Budget',
  'tasks.filters.budgetMin': 'Min Budget',
  'tasks.filters.budgetMax': 'Max Budget',
  'tasks.filters.deadline': 'Deadline',
  'tasks.filters.status': 'Status',
  'tasks.filters.all': 'All',
  'tasks.filters.open': 'Open',
  'tasks.filters.inProgress': 'In Progress',
  'tasks.filters.completed': 'Completed',
  'tasks.filters.activeFilters': 'Active Filters',
  'tasks.filters.clearAll': 'Clear All',
  'tasks.results': 'results',
  'tasks.sort.newest': 'Newest First',
  'tasks.sort.oldest': 'Oldest First',
  'tasks.sort.budgetHigh': 'Highest Budget',
  'tasks.sort.budgetLow': 'Lowest Budget',
  'tasks.sort.deadline': 'By Deadline',

  'professionals.hero.title': 'Find Trusted Professionals',
  'professionals.hero.subtitle':
    'Browse verified specialists by category and find the perfect match for your needs',
  'professionals.hero.badge': 'Professional Network',
  'professionals.searchPlaceholder':
    'Search categories... (e.g., repair, cleaning, tutoring)',
  'professionals.allCategories': 'All Categories',
  'professionals.featuredTitle': 'Featured Professionals',
  'professionals.viewProfile': 'View Profile',
  'professionals.rating': 'Rating',
  'professionals.completedJobs': 'Completed Jobs',
  'professionals.startingFrom': 'Starting from',
  'professionals.noResults': 'No categories match your search',
  'professionals.categoryResults': 'categories found',
  'professionals.filterBy': 'Filter by',
  'professionals.location': 'Location',
  'professionals.experience': 'Experience',
  'professionals.priceRange': 'Price Range',
  'professionals.availability': 'Availability',
  'professionals.findPerfect': 'Find the Perfect Professional',
  'professionals.discoverTrusted':
    'Discover trusted professionals with proven track records and exceptional reviews',
  'professionals.popularCategories': 'Popular categories',
  'professionals.refineSearch': 'Refine your search results',
  'professionals.professionalsAvailable': 'professionals available',
  'professionals.noMatchingResults':
    'No professionals available matching your criteria. Try broadening your search.',
  'professionals.mostActive': 'Most Active',
  'professionals.gender.male': 'Male',
  'professionals.gender.female': 'Female',
  'professionals.filters.category': 'Category',
  'professionals.filters.location': 'Location',
  'professionals.filters.minimumRating': 'Minimum Rating',
  'professionals.filters.genderPreference': 'Gender Preference',
  'professionals.filters.activityLevel': 'Activity Level',
  'professionals.filters.all': 'All',
  'professionals.filters.topPerformersOnly': 'Top Performers Only',
  'professionals.filters.locationPlaceholder': 'Sofia, Plovdiv, Varna...',
  'professionals.filters.any': 'Any',
  'professionals.filters.anyShort': 'Any',
  'professionals.typing.plumber': 'plumber in Sofia',
  'professionals.typing.cleaner': 'house cleaning specialist',
  'professionals.typing.electrician': 'certified electrician',
  'professionals.typing.tutor': 'English tutor',
  'professionals.typing.photographer': 'wedding photographer',
  'professionals.typing.handyman': 'handyman services',
  'professionals.recommendedTitle': 'RECOMMENDED PROFESSIONALS',
  'professionals.filters.clear': 'Clear',
  'professionals.filters.clearAll': 'Clear all filters',
  'professionals.filters.fourPlusStars': '4+ stars',
  'professionals.filters.fiveStarsOnly': '5 stars only',
  'professionals.filters.anyRating': 'By Rating',
  'professionals.filters.showProfessionalsWithAnyRating':
    'Show professionals with any rating',
  'professionals.filters.locationPlaceholderDesktop': '📍 Location',
  'professionals.sorting.featuredFirst': 'Top Choice',
  'professionals.sorting.featuredFirstDesc': 'Best professionals',
  'professionals.sorting.highestRating': 'By Rating',
  'professionals.sorting.highestRatingDesc': 'Top rated',
  'professionals.sorting.mostExperience': 'By Experience',
  'professionals.sorting.mostExperienceDesc': 'Most orders',
  'professionals.filters.sortResultsBy': 'Sort Results By',
  'professionals.filters.sortResultsTitle': 'Sort Results',
  'professionals.filters.sortResultsDescription':
    'Choose how to order professionals',
  'professionals.filters.selectMinimumRating': 'Select Minimum Rating',
  'professionals.filters.showingVerifiedFirst':
    'Showing verified top performers first',
  'professionals.filters.proTip': 'Pro Tip',
  'professionals.filters.proTipMessage':
    'Try "{{sortOption}}" for quality-assured professionals with verified credentials',
  'professionals.filters.sortingBy': 'Sorting by {{option}}',
  'professionals.filters.sortingDescFeatured':
    'Showing verified top performers first',
  'professionals.filters.sortingDescRating':
    'Professionals with highest ratings appear first',
  'professionals.filters.sortingDescJobs':
    'Most experienced professionals appear first',
  'professionals.filters.activeFilters': 'Active Filters',
  'professionals.filters.filterApplied': '{{count}} filter applied',
  'professionals.filters.filtersApplied': '{{count}} filters applied',
  'professionals.filters.showProfessionalsWithRating':
    'Show professionals with {{rating}}+ star ratings',
  'professionals.filters.showPerfectRating':
    'Show only professionals with perfect 5-star ratings',

  'browseTasks.hero.badge': 'Find perfect professionals',
  'browseTasks.hero.title1': 'Find your ideal',
  'browseTasks.hero.title2': 'task for you',
  'browseTasks.hero.subtitle':
    'Browse hundreds of opportunities from verified clients. Start working today.',
  'browseTasks.search.placeholder':
    'Search tasks by keywords, category or city...',
  'browseTasks.search.popular': 'Popular',
  'browseTasks.filters.title': 'Filtering and sorting',
  'browseTasks.filters.advanced': 'Advanced filters',
  'browseTasks.filters.quick': 'Quick filter',
  'browseTasks.filters.searchPlaceholder':
    'Search for tasks... (e.g., cleaning, repair, delivery)',
  'browseTasks.filters.category': 'Category',
  'browseTasks.filters.allCategories': 'All categories',
  'browseTasks.filters.city': 'City',
  'browseTasks.filters.allCities': 'All cities',
  'browseTasks.filters.cities.sofia': 'Sofia',
  'browseTasks.filters.cities.plovdiv': 'Plovdiv',
  'browseTasks.filters.cities.varna': 'Varna',
  'browseTasks.filters.cities.burgas': 'Burgas',
  'browseTasks.filters.budget': 'Budget',
  'browseTasks.filters.budgetMin': 'Min',
  'browseTasks.filters.budgetMax': 'Max',
  'browseTasks.filters.budgetUpTo': 'Up to 500 BGN',
  'browseTasks.filters.sortBy': 'Sort by',
  'browseTasks.filters.sort.newest': 'Newest',
  'browseTasks.filters.sort.oldest': 'Oldest',
  'browseTasks.filters.sort.highBudget': 'High budget',
  'browseTasks.filters.sort.lowBudget': 'Low budget',
  'browseTasks.results.shown': 'Shown {{count}} results',
  'browseTasks.results.featured': 'Showing {{count}} popular tasks',
  'browseTasks.results.loading': 'Loading...',
  'browseTasks.results.noTasks.title': 'No tasks found',
  'browseTasks.results.noTasks.description':
    'Try changing the filters or searching by different criteria.',
  'browseTasks.results.noTasks.clearFilters': 'Clear filters',
  'browseTasks.results.suggestedTasks': 'Popular Tasks You Might Like',
  'browseTasks.results.suggestedDescription':
    'Here are some popular tasks from our community',
  'browseTasks.results.error.title': 'Error loading',
  'browseTasks.results.error.description':
    'Please try again or contact support.',
  'browseTasks.pagination.previous': 'Previous',
  'browseTasks.pagination.next': 'Next',
  'browseTasks.search.tags.programming': 'Programming',
  'browseTasks.search.tags.design': 'Design',
  'browseTasks.search.tags.marketing': 'Marketing',
  'browseTasks.search.tags.translation': 'Translation',
  'browseTasks.search.tags.photography': 'Photography',
  'browseTasks.typing.plumber': 'plumber in Sofia',
  'browseTasks.typing.cleaner': 'house cleaning',
  'browseTasks.typing.electrician': 'electrician repair',
  'browseTasks.typing.tutor': 'English tutor',
  'browseTasks.typing.moving': 'moving furniture',
  'browseTasks.typing.gardener': 'garden maintenance',

  'task.budget': 'Budget',
  'task.location': 'Location',
  'task.category': 'Category',
  'task.applications': 'Applications',
  'task.viewDetails': 'View Details',
  'task.apply': 'Apply Now',
  'task.created': 'Created',
  'task.deadline': 'Deadline',

  // Create Task Form
  'createTask.title': 'Post a New Task',
  'createTask.hero.subtitle': 'Describe what you need and let professionals come to you',
  'createTask.hero.freeToPost': 'Free to post',
  'createTask.hero.noPayment': 'No payment until work starts',
  'createTask.hero.avgResponse': 'Average response time: 2 hours',
  'createTask.hero.verifiedPros': '1,500+ verified professionals',
  'createTask.hero.help': 'Need help? Contact our support team',

  // Category Section
  'createTask.category.title': 'What type of service do you need?',
  'createTask.category.subtitle': 'Select the category that best matches your task',
  'createTask.category.selectSubcategory': 'Select a specific service',
  'createTask.category.backToMain': 'Back to main categories',
  'createTask.category.selected': 'Selected Service',
  'createTask.category.tryDifferent': 'Try a different search term',

  // Details Section
  'createTask.details.title': 'Tell us about your task',
  'createTask.details.subtitle': 'Provide clear information to attract the right professionals',
  'createTask.details.titleLabel': 'Task Title',
  'createTask.details.titlePlaceholder': 'What do you need done?',
  'createTask.details.titleHelp': 'Be specific and clear (e.g., "Professional house cleaning for 2-bedroom apartment")',
  'createTask.details.descriptionLabel': 'Description',
  'createTask.details.descriptionPlaceholder': 'Describe your task in detail...',
  'createTask.details.descriptionHelp': 'Include all important details: what needs to be done, any special requirements, tools/materials needed, etc.',
  'createTask.details.requirementsLabel': 'Specific Requirements (Optional)',
  'createTask.details.requirementsPlaceholder': '• Requirement 1\n• Requirement 2\n• Requirement 3',
  'createTask.details.requirementsHelp': 'List any special skills, certifications, or equipment needed (one per line)',

  // Location Section
  'createTask.location.title': 'Where will the task be performed?',
  'createTask.location.subtitle': 'Location helps professionals understand if they can reach you',
  'createTask.location.cityLabel': 'City',
  'createTask.location.cityPlaceholder': 'Select your city',
  'createTask.location.neighborhoodLabel': 'Neighborhood/District',
  'createTask.location.neighborhoodPlaceholder': 'e.g., Лозенец, Витоша, Център',
  'createTask.location.neighborhoodHelp': 'Helps professionals determine if they can reach you',
  'createTask.location.addressLabel': 'Full Address (Optional)',
  'createTask.location.addressPlaceholder': 'Street, building number, entrance, floor, apartment',
  'createTask.location.addressSecurity': 'Address will only be shown to the professional you hire',

  // Budget Section
  'createTask.budget.title': 'What is your budget?',
  'createTask.budget.help': 'Fair budgets get 3x more applications',
  'createTask.budget.typeFixed': 'Fixed Price',
  'createTask.budget.typeRange': 'Price Range',
  'createTask.budget.fixedLabel': 'Your Budget',
  'createTask.budget.minLabel': 'Minimum',
  'createTask.budget.maxLabel': 'Maximum',
  'createTask.budget.notSure': "I'm not sure about the budget",

  // Timeline Section
  'createTask.timeline.title': 'When do you need this done?',
  'createTask.timeline.subtitle': 'Let professionals know your timeline',
  'createTask.timeline.urgentTitle': 'Urgent - Same Day',
  'createTask.timeline.urgentDesc': 'I need this done today',
  'createTask.timeline.soonTitle': 'Soon - Within a Week',
  'createTask.timeline.soonDesc': 'I need this done in the next 7 days',
  'createTask.timeline.flexibleTitle': 'Flexible',
  'createTask.timeline.flexibleDesc': "I'm flexible with timing",
  'createTask.timeline.deadlineLabel': 'Specific Deadline (Optional)',
  'createTask.timeline.deadlineHelp': "Leave empty if you don't have a specific deadline",

  // Photos Section
  'createTask.photos.title': 'Add photos (optional)',
  'createTask.photos.help': 'Photos help professionals understand your task better',
  'createTask.photos.dragDrop': 'Drag and drop images here',
  'createTask.photos.orBrowse': 'or click to browse',
  'createTask.photos.maxFiles': 'Maximum 5 images',
  'createTask.photos.maxSize': '5MB per image',
  'createTask.photos.formats': 'JPG, PNG, WebP',
  'createTask.photos.addMore': 'Add more',
  'createTask.photos.uploading': 'Uploading photos...',
  'createTask.photos.fileTooLarge': 'File is too large. Maximum size is 5MB',
  'createTask.photos.invalidType': 'File is not a supported image format',
  'createTask.photos.uploadError': 'Failed to upload photos. Please try again.',

  // Review Section
  'createTask.review.title': 'Review your task',
  'createTask.review.subtitle': 'Make sure everything looks good before posting',
  'createTask.review.submit': 'Post Task',
  'createTask.review.location': 'Location',
  'createTask.review.budget': 'Budget',
  'createTask.review.timeline': 'Timeline',
  'createTask.review.requirements': 'Requirements',
  'createTask.review.photos': 'Photos',
  'createTask.review.noTitle': 'No title yet',
  'createTask.review.noDescription': 'No description yet',
  'createTask.review.noCity': 'No city selected',
  'createTask.review.fillRequired': 'Please fill in all required fields to submit',

  // Errors
  'createTask.errors.categoryRequired': 'Please select a category',
  'createTask.errors.titleTooShort': 'Title must be at least 10 characters',
  'createTask.errors.titleTooLong': 'Title must be less than 200 characters',
  'createTask.errors.descriptionTooShort': 'Description must be at least 50 characters',
  'createTask.errors.descriptionTooLong': 'Description must be less than 2000 characters',
  'createTask.errors.cityRequired': 'City is required',
  'createTask.errors.budgetInvalid': 'Maximum must be greater than minimum',
  'createTask.errors.tooManyPhotos': 'Maximum 5 photos allowed',

  'profile.title': 'My Profile',
  'profile.personalInfo': 'Personal Information',
  'profile.professionalInfo': 'Professional Information',
  'profile.verification': 'Verification',
  'profile.reviews': 'Reviews',
  'profile.stats': 'Statistics',

  'profile.form.firstName': 'First Name',
  'profile.form.lastName': 'Last Name',
  'profile.form.email': 'Email',
  'profile.form.phone': 'Phone',
  'profile.form.location': 'Location',
  'profile.form.bio': 'Bio',
  'profile.form.skills': 'Skills',
  'profile.form.experience': 'Years of Experience',
  'profile.form.hourlyRate': 'Hourly Rate (BGN)',
  'profile.form.vatNumber': 'VAT Number',
  'profile.form.businessName': 'Business Name',
  'profile.form.website': 'Website',

  'profile.verification.identity': 'Identity Verified',
  'profile.verification.business': 'Business Verified',
  'profile.verification.phone': 'Phone Verified',
  'profile.verification.email': 'Email Verified',

  'language.en': 'English',
  'language.bg': 'Български',
  'language.ru': 'Русский',

  'landing.testimonials.title': 'What Our Users Say',
  'landing.testimonials.subtitle': 'Real feedback from our community',
  'landing.testimonials.customers.title': 'From Customers',
  'landing.testimonials.customers.customer1.name': 'Maria Ivanova',
  'landing.testimonials.customers.customer1.location': 'Sofia, Bulgaria',
  'landing.testimonials.customers.customer1.quote':
    'Found an amazing plumber in minutes. Professional service and fair pricing!',
  'landing.testimonials.customers.customer2.name': 'Georgi Petrov',
  'landing.testimonials.customers.customer2.location': 'Plovdiv, Bulgaria',
  'landing.testimonials.customers.customer2.quote':
    'The cleaning service was exceptional. Will definitely use Trudify again.',
  'landing.testimonials.customers.customer3.name': 'Elena Dimitrova',
  'landing.testimonials.customers.customer3.location': 'Varna, Bulgaria',
  'landing.testimonials.customers.customer3.quote':
    'Quick, reliable, and affordable. Exactly what I was looking for.',

  'landing.testimonials.professionals.title': 'From Professionals',
  'landing.testimonials.professionals.pro1.name': 'Ivan Stoev',
  'landing.testimonials.professionals.pro1.profession': 'Electrician',
  'landing.testimonials.professionals.pro1.quote':
    'Trudify helped me grow my business with steady stream of quality clients.',
  'landing.testimonials.professionals.pro2.name': 'Anna Nikolova',
  'landing.testimonials.professionals.pro2.profession': 'Cleaner',
  'landing.testimonials.professionals.pro2.quote':
    'Easy to use platform. I love how I can manage my schedule and payments.',
  'landing.testimonials.professionals.pro3.name': 'Dimitar Georgiev',
  'landing.testimonials.professionals.pro3.profession': 'Handyman',
  'landing.testimonials.professionals.pro3.quote':
    'Professional platform that connects me with customers who value quality work.',

  'landing.trustSection.title': 'Built on Trust',
  'landing.trustSection.subtitle':
    'Your security and satisfaction are our top priorities',

  'landing.cta.title': 'Ready to Get Started?',
  'landing.cta.subtitle': 'Join thousands of satisfied users today',
  'landing.cta.postTask': 'Post a Task',
  'landing.cta.joinProfessionals': 'Join as Professional',
  'landing.cta.freeToJoin': 'Free to join, no hidden fees',
  'landing.cta.stats.completedTasks': 'Tasks Completed',
  'landing.cta.stats.activeSpecialists': 'Active Specialists',
  'landing.cta.stats.averageRating': 'Average Rating',
  'landing.cta.stats.contractTemplates': 'Legal Templates',

  'taskCard.apply': 'Apply',
  'taskCard.anonymous': 'Anonymous',
  'taskCard.budget.from': 'from',
  'taskCard.budget.to': 'up to',
  'taskCard.budget.negotiable': 'Negotiable',
  'taskCard.deadline.flexible': 'Flexible',
  'taskCard.deadline.today': 'Today',
  'taskCard.deadline.tomorrow': 'Tomorrow',
  'taskCard.deadline.days': 'days',
  'taskCard.category.home_repair': 'Home Repairs',
  'taskCard.category.delivery_transport': 'Delivery & Transport',
  'taskCard.category.personal_care': 'Personal Care',
  'taskCard.category.personal_assistant': 'Personal Assistant',
  'taskCard.category.learning_fitness': 'Learning & Fitness',
  'taskCard.category.other': 'Other',

  // Category Groups
  'categoryGroups.homeRepair': 'Home & Repair',
  'categoryGroups.cleaning': 'Cleaning',
  'categoryGroups.deliveryTransport': 'Delivery & Transport',
  'categoryGroups.personalCare': 'Personal Care',
  'categoryGroups.professional': 'Professional Services',
  'categoryGroups.creative': 'Creative Services',
  'categoryGroups.events': 'Events',
  'categoryGroups.beauty': 'Beauty',
  'categoryGroups.other': 'Other',

  // Individual Categories
  'categories.plumbing': 'Plumbing',
  'categories.electrical': 'Electrical',
  'categories.hvac': 'HVAC',
  'categories.carpentry': 'Carpentry',
  'categories.painting': 'Painting',
  'categories.flooring': 'Flooring',
  'categories.roofing': 'Roofing',
  'categories.homeRenovation': 'Home Renovation',
  'categories.applianceRepair': 'Appliance Repair',
  'categories.handyman': 'Handyman',
  'categories.houseCleaning': 'House Cleaning',
  'categories.deepCleaning': 'Deep Cleaning',
  'categories.carpetCleaning': 'Carpet Cleaning',
  'categories.windowCleaning': 'Window Cleaning',
  'categories.gardenMaintenance': 'Garden Maintenance',
  'categories.landscaping': 'Landscaping',
  'categories.delivery': 'Delivery',
  'categories.moving': 'Moving',
  'categories.taxiDriver': 'Taxi Driver',
  'categories.courier': 'Courier',
  'categories.babysitting': 'Babysitting',
  'categories.elderlyCare': 'Elderly Care',
  'categories.petSitting': 'Pet Sitting',
  'categories.personalTrainer': 'Personal Trainer',
  'categories.massageTherapy': 'Massage Therapy',
  'categories.tutoring': 'Tutoring',
  'categories.translation': 'Translation',
  'categories.accounting': 'Accounting',
  'categories.legalServices': 'Legal Services',
  'categories.consulting': 'Consulting',
  'categories.graphicDesign': 'Graphic Design',
  'categories.webDevelopment': 'Web Development',
  'categories.photography': 'Photography',
  'categories.videography': 'Videography',
  'categories.writing': 'Writing',
  'categories.musicLessons': 'Music Lessons',
  'categories.eventPlanning': 'Event Planning',
  'categories.catering': 'Catering',
  'categories.djServices': 'DJ Services',
  'categories.hairdressing': 'Hairdressing',
  'categories.makeupArtist': 'Makeup Artist',
  'categories.nailServices': 'Nail Services',
  'categories.other': 'Other',

  // Categories Page
  'categories.pageTitle': 'Browse All Categories',
  'categories.pageSubtitle': 'Find the perfect professional for any task',
  'categories.searchPlaceholder': 'Search for services... (e.g. plumber, cleaning, tutoring)',
  'categories.ctaTitle': "Can't find what you're looking for?",
  'categories.ctaSubtitle': 'Post your task and let professionals come to you',

  // Main Categories (centralized categories feature)
  'categories.main.homeServices.title': 'Home Services',
  'categories.main.homeServices.description': 'Plumbing, electrical, handyman services',
  'categories.main.renovation.title': 'Renovation & Construction',
  'categories.main.renovation.description': 'Renovations, painting, tiling',
  'categories.main.moving.title': 'Moving & Transport',
  'categories.main.moving.description': 'Moving services, cargo transport, loaders',
  'categories.main.cleaning.title': 'Cleaning Services',
  'categories.main.cleaning.description': 'House cleaning, deep cleaning, office cleaning',
  'categories.main.personal.title': 'Personal Services',
  'categories.main.personal.description': 'Babysitting, tutoring, pet care',
  'categories.main.tech.title': 'Tech & Digital',
  'categories.main.tech.description': 'Computer repair, IT support, web development',

  // Main Categories - NEW (26 total)
  'categories.main.applianceRepair.title': 'Appliance Repair',
  'categories.main.applianceRepair.description': 'Repair of appliances, computers and electronics',
  'categories.main.courierServices.title': 'Courier Services',
  'categories.main.courierServices.description': 'Delivery of food, medicine and packages',
  'categories.main.onlineWork.title': 'Online Work',
  'categories.main.onlineWork.description': 'Data entry, research, transcription',
  'categories.main.handyman.title': 'Handyman',
  'categories.main.handyman.description': 'Plumber, electrician, locksmith',
  'categories.main.finishingWork.title': 'Finishing Work',
  'categories.main.finishingWork.description': 'Apartment renovation, tiling, plastering',
  'categories.main.constructionWork.title': 'Construction Work',
  'categories.main.constructionWork.description': 'Masonry, welding, carpentry',
  'categories.main.furnitureWork.title': 'Furniture Work',
  'categories.main.furnitureWork.description': 'Manufacturing, repair and restoration of furniture',
  'categories.main.cleaningServices.title': 'Cleaning Services',
  'categories.main.cleaningServices.description': 'Home, office and post-renovation cleaning',
  'categories.main.logistics.title': 'Logistics',
  'categories.main.logistics.description': 'Cargo transport, moving, loaders',
  'categories.main.householdServices.title': 'Household Services',
  'categories.main.householdServices.description': 'Babysitters, gardening, housekeepers',
  'categories.main.petServices.title': 'Pet Services',
  'categories.main.petServices.description': 'Care for dogs, cats and other pets',
  'categories.main.beautyHealth.title': 'Beauty & Health',
  'categories.main.beautyHealth.description': 'Massage, manicure, cosmetology',
  'categories.main.autoRepair.title': 'Auto Repair',
  'categories.main.autoRepair.description': 'Diagnostics, maintenance and car repair',
  'categories.main.digitalMarketing.title': 'Digital Marketing',
  'categories.main.digitalMarketing.description': 'SEO, contextual advertising, social media marketing',
  'categories.main.aiServices.title': 'AI Services',
  'categories.main.aiServices.description': 'AI development, consulting and data analytics',
  'categories.main.onlineAdvertising.title': 'Online Advertising',
  'categories.main.onlineAdvertising.description': 'Online ad placement',
  'categories.main.advertisingDistribution.title': 'Advertising Distribution',
  'categories.main.advertisingDistribution.description': 'Flyer distribution, poster hanging',
  'categories.main.webDevelopment.title': 'Web Development',
  'categories.main.webDevelopment.description': 'Website and application development',
  'categories.main.design.title': 'Design',
  'categories.main.design.description': 'Logo design, interior design, print design',
  'categories.main.photoVideo.title': 'Photo & Video Services',
  'categories.main.photoVideo.description': 'Photography, videography, editing',
  'categories.main.tutoring.title': 'Tutoring Services',
  'categories.main.tutoring.description': 'Subject, language and music lessons',
  'categories.main.businessServices.title': 'Business Services',
  'categories.main.businessServices.description': 'Accounting, legal services, real estate',
  'categories.main.translationServices.title': 'Translation Services',
  'categories.main.translationServices.description': 'Written and oral translation',
  'categories.main.trainerServices.title': 'Trainer Services',
  'categories.main.trainerServices.description': 'Yoga, fitness, sports training',
  'categories.main.eventPlanning.title': 'Event Planning',
  'categories.main.eventPlanning.description': 'Hosts, animators, catering',
  'categories.main.volunteerHelp.title': 'Volunteer Help',
  'categories.main.volunteerHelp.description': 'Assistance for elderly and transportation',

  // Subcategories - NEW (135 total)
  // Handyman
  'categories.sub.plumber': 'Plumber',
  'categories.sub.electrician': 'Electrician',
  'categories.sub.handymanService': 'Handyman',
  'categories.sub.carpenter': 'Carpenter',
  'categories.sub.locksmith': 'Locksmith',

  // Appliance Repair
  'categories.sub.largeApplianceRepair': 'Large Appliance Repair',
  'categories.sub.smallApplianceRepair': 'Small Appliance Repair',
  'categories.sub.computerHelp': 'Computer Help',
  'categories.sub.digitalTechRepair': 'Digital Tech Repair',
  'categories.sub.phoneRepair': 'Phone Repair',

  // Finishing Work
  'categories.sub.apartmentRenovation': 'Apartment Renovation',
  'categories.sub.tileInstallation': 'Tile Installation',
  'categories.sub.plastering': 'Plastering',
  'categories.sub.insulation': 'Insulation',
  'categories.sub.heatingInstallation': 'Heating Installation',

  // Construction Work
  'categories.sub.generalLabor': 'General Labor',
  'categories.sub.welding': 'Welding',
  'categories.sub.turning': 'Turning',
  'categories.sub.carpentry': 'Carpentry',
  'categories.sub.bricklaying': 'Bricklaying',

  // Furniture Work
  'categories.sub.furnitureManufacturing': 'Furniture Manufacturing',
  'categories.sub.furnitureRepair': 'Furniture Repair',
  'categories.sub.furnitureAssembly': 'Furniture Assembly',
  'categories.sub.furnitureRestoration': 'Furniture Restoration',
  'categories.sub.furnitureUpholstery': 'Furniture Upholstery',

  // Cleaning Services
  'categories.sub.apartmentCleaning': 'Apartment Cleaning',
  'categories.sub.deepCleaning': 'Deep Cleaning',
  'categories.sub.postRenovationCleaning': 'Post-Renovation Cleaning',
  'categories.sub.dryCleaning': 'Dry Cleaning',
  'categories.sub.houseCleaning': 'House Cleaning',

  // Logistics
  'categories.sub.cargoTransport': 'Cargo Transport',
  'categories.sub.loaders': 'Loaders',
  'categories.sub.constructionWasteRemoval': 'Construction Waste Removal',
  'categories.sub.furnitureApplianceMoving': 'Furniture & Appliance Moving',
  'categories.sub.officeRelocation': 'Office Relocation',

  // Household Services
  'categories.sub.gardening': 'Gardening',
  'categories.sub.babysitting': 'Babysitting',
  'categories.sub.caregiver': 'Caregiver',
  'categories.sub.housekeeper': 'Housekeeper',
  'categories.sub.sewing': 'Sewing',

  // Auto Repair
  'categories.sub.roadsideAssistance': 'Roadside Assistance',
  'categories.sub.maintenanceDiagnostics': 'Maintenance & Diagnostics',
  'categories.sub.autoElectrical': 'Auto Electrical',
  'categories.sub.bodyWork': 'Body Work',
  'categories.sub.engineRepair': 'Engine Repair',

  // Courier Services
  'categories.sub.courierDelivery': 'Courier Delivery',
  'categories.sub.groceryDelivery': 'Grocery Delivery',
  'categories.sub.foodDelivery': 'Food Delivery',
  'categories.sub.medicineDelivery': 'Medicine Delivery',
  'categories.sub.courierByCar': 'Courier by Car',

  // Digital Marketing
  'categories.sub.contextualAdvertising': 'Contextual Advertising',
  'categories.sub.seoOptimization': 'SEO Optimization',
  'categories.sub.copywriting': 'Copywriting',
  'categories.sub.socialMediaMarketing': 'Social Media Marketing',
  'categories.sub.emailMarketing': 'Email Marketing',

  // AI Services
  'categories.sub.aiContentCreation': 'AI Content Creation',
  'categories.sub.aiConsulting': 'AI Consulting',
  'categories.sub.aiDevelopment': 'AI Development',
  'categories.sub.aiDataAnalytics': 'AI Data Analytics',

  // Online Advertising
  'categories.sub.onlineAdPlacement': 'Online Ad Placement',

  // Advertising Distribution
  'categories.sub.flyerDistribution': 'Flyer Distribution',
  'categories.sub.posterHanging': 'Poster Hanging',
  'categories.sub.mailboxAdvertising': 'Mailbox Advertising',
  'categories.sub.sandwichBoardAdvertising': 'Sandwich Board Advertising',

  // Design
  'categories.sub.logoDesign': 'Logo Design',
  'categories.sub.interiorDesign': 'Interior Design',
  'categories.sub.webAppDesign': 'Web & App Design',
  'categories.sub.printDesign': 'Print Design',
  'categories.sub.printingServices': 'Printing Services',

  // Tutoring
  'categories.sub.subjectTutors': 'Subject Tutors',
  'categories.sub.languageTutors': 'Language Tutors',
  'categories.sub.academicWriting': 'Academic Writing',
  'categories.sub.musicTeachers': 'Music Teachers',
  'categories.sub.drivingInstructors': 'Driving Instructors',

  // Web Development
  'categories.sub.websiteCreation': 'Website Creation',
  'categories.sub.websiteImprovements': 'Website Improvements',
  'categories.sub.landingPage': 'Landing Page',
  'categories.sub.websiteLayout': 'Website Layout',
  'categories.sub.qaTesting': 'QA Testing',

  // Online Work
  'categories.sub.dataResearch': 'Data Research',
  'categories.sub.contentFilling': 'Content Filling',
  'categories.sub.typing': 'Typing',
  'categories.sub.dataEntry': 'Data Entry',
  'categories.sub.transcription': 'Transcription',

  // Photo/Video Services
  'categories.sub.photographer': 'Photographer',
  'categories.sub.videographer': 'Videographer',
  'categories.sub.photoEditing': 'Photo Editing',
  'categories.sub.videoEditing': 'Video Editing',
  'categories.sub.videoDigitization': 'Video Digitization',

  // Business Services
  'categories.sub.accounting': 'Accounting',
  'categories.sub.legalServices': 'Legal Services',
  'categories.sub.realEstate': 'Real Estate',
  'categories.sub.callCenter': 'Call Center',
  'categories.sub.financialServices': 'Financial Services',

  // Pet Services
  'categories.sub.catCare': 'Cat Care',
  'categories.sub.dogCare': 'Dog Care',
  'categories.sub.petHotel': 'Pet Hotel',
  'categories.sub.petTransportation': 'Pet Transportation',
  'categories.sub.fishCare': 'Fish Care',

  // Beauty & Health
  'categories.sub.massage': 'Massage',
  'categories.sub.nailCare': 'Nail Care',
  'categories.sub.cosmetology': 'Cosmetology',
  'categories.sub.lashCare': 'Lash Care',
  'categories.sub.browCare': 'Brow Care',

  // Event Planning
  'categories.sub.eventHost': 'Event Host',
  'categories.sub.musicEntertainment': 'Music Entertainment',
  'categories.sub.animators': 'Animators',
  'categories.sub.catering': 'Catering',
  'categories.sub.bakingDesserts': 'Baking & Desserts',

  // Translation Services
  'categories.sub.writtenTranslation': 'Written Translation',
  'categories.sub.translationEditing': 'Translation Editing',
  'categories.sub.documentTranslation': 'Document Translation',
  'categories.sub.oralTranslation': 'Oral Translation',
  'categories.sub.technicalTranslation': 'Technical Translation',

  // Trainer Services
  'categories.sub.yoga': 'Yoga',
  'categories.sub.groupFitness': 'Group Fitness',
  'categories.sub.teamSports': 'Team Sports',
  'categories.sub.waterSports': 'Water Sports',
  'categories.sub.martialArts': 'Martial Arts',

  // Volunteer Help
  'categories.sub.elderlyAssistance': 'Elderly Assistance',
  'categories.sub.volunteerTransportation': 'Volunteer Transportation',
  'categories.sub.fuelDelivery': 'Fuel Delivery',
  'categories.sub.housingAssistance': 'Housing Assistance',
  'categories.sub.volunteerFoodDelivery': 'Volunteer Food Delivery',

  'professionalDetail.about': 'About the Professional',
  'professionalDetail.reviews': 'reviews',
  'professionalDetail.online': 'Online',
  'professionalDetail.offline': 'Last seen recently',
  'professionalDetail.verified.phone': 'Phone',
  'professionalDetail.verified.id': 'ID',
  'professionalDetail.stats.completedTasks': 'Tasks',
  'professionalDetail.stats.yearsExperience': 'Years',
  'professionalDetail.stats.responseTime': 'Response',
  'professionalDetail.actions.proposeTask': 'Propose a Task',
  'professionalDetail.actions.contact': 'Contact',
  'professionalDetail.actions.askQuestion': 'Ask Question',
  'professionalDetail.actions.saveToFavorites': 'Save to Favorites',
  'professionalDetail.contactHours': 'Available',
  'professionalDetail.services.title': 'Services & Pricing',
  'professionalDetail.services.pricingNote.title': 'Pricing Information',
  'professionalDetail.services.pricingNote.description':
    'Final prices are agreed upon individually based on task complexity and requirements.',
  'professionalDetail.portfolio.title': 'My Demos',
  'professionalDetail.portfolio.noWork': 'No demos available yet',
  'professionalDetail.portfolio.before': 'Before',
  'professionalDetail.portfolio.after': 'After',
  'professionalDetail.portfolio.viewMore': 'View all demos',
  'professionalDetail.portfolio.showcase': 'Professional work showcase',
  'professionalDetail.completedTasks.title': 'Completed Tasks',
  'professionalDetail.completedTasks.noTasks': 'No completed tasks yet',
  'professionalDetail.completedTasks.viewTask': 'View Task',
  'professionalDetail.completedTasks.completedOn': 'Completed on',
  'professionalDetail.reviews.title': 'Reviews & Ratings',
  'professionalDetail.reviews.count': 'reviews',
  'professionalDetail.reviews.recentRating': 'Recent rating',
  'professionalDetail.reviews.excellent': 'Excellent',
  'professionalDetail.reviews.noReviews': 'No reviews yet',
  'professionalDetail.reviews.beFirst':
    'Be the first to review this professional',
  'professionalDetail.reviews.showMore': 'Show all reviews',
  'professionalDetail.reviews.allReviews': 'All Reviews',
  'professionalDetail.reviews.avgRating': 'Average Rating',
  'professionalDetail.reviews.more': 'more',
  'professionalDetail.completedTasks.stats.tasksCompleted': 'Tasks Completed',
  'professionalDetail.completedTasks.stats.avgRating': 'Avg Rating',
  'professionalDetail.completedTasks.stats.fiveStarTasks': '5-Star Tasks',
  'professionalDetail.verified': 'Verified',
  'common.anonymous': 'Anonymous User',

  'footer.company.description':
    'Connecting people with qualified professionals for all kinds of services in Bulgaria.',
  'footer.quickLinks.title': 'Quick Links',
  'footer.quickLinks.howItWorks': 'How It Works',
  'footer.quickLinks.categories': 'Categories',
  'footer.quickLinks.forProfessionals': 'For Professionals',
  'footer.quickLinks.security': 'Security',
  'footer.quickLinks.help': 'Help',
  'footer.legal.title': 'Legal',
  'footer.legal.terms': 'Terms of Service',
  'footer.legal.privacy': 'Privacy Policy',
  'footer.legal.gdpr': 'GDPR',
  'footer.legal.cookies': 'Cookies',
  'footer.legal.complaints': 'Complaints',
  'footer.contact.title': 'Contact',
  'footer.contact.subtitle': 'Get in touch for questions and support',
  'footer.language.label': 'Language',
  'footer.copyright': '© 2025 Obod Soft LTD. All rights reserved.',

  'taskDetail.backToTasks': 'Back to tasks',
  'taskDetail.requirements': 'Requirements:',
  'taskDetail.keyInformation': 'Key Information',
  'taskDetail.client': 'Client',
  'taskDetail.loginForMore': 'Login for more',
  'taskDetail.loginMessage': 'Log in to see full information',
  'taskDetail.completedTasks': 'completed tasks',
  'taskDetail.memberSince': 'Member since',
  'taskDetail.similarTasks': 'Similar Tasks',
  'taskDetail.apply': 'Apply for Task',
  'taskDetail.askQuestion': 'Ask Question',
  'taskDetail.applicationsCount': 'applications',
  'taskDetail.timeAgo': 'ago',
  'taskDetail.today': 'Today',
  'taskDetail.tomorrow': 'Tomorrow',
  'taskDetail.days': 'days',
  'taskDetail.flexible': 'Flexible',
  'taskDetail.negotiable': 'Negotiable',
  'taskDetail.urgency.same_day': 'Urgent - today',
  'taskDetail.urgency.within_week': 'Within a week',
  'taskDetail.urgency.flexible': 'Flexible deadline',
  'taskDetail.urgency.default': 'Unspecified',
  'taskDetail.status': 'Status',
  'taskDetail.statusTypes.vacant': 'Vacant',
  'taskDetail.statusTypes.applied': 'Applied',
  'taskDetail.statusTypes.done': 'Done',
  'taskDetail.statusTypes.archived': 'Archived',
  'taskDetail.appliedTooltip': 'You have applied to this task. The client may accept or reject your application.',

  'taskDetail.share': 'Share',
  'taskDetail.activity': 'Task Activity',
  'taskDetail.applications': 'Applications',
  'taskDetail.questions': 'Questions',
  'taskDetail.accept': 'Accept',
  'taskDetail.reject': 'Reject',
  'taskDetail.message': 'Message',
  'taskDetail.reply': 'Reply',
  'taskDetail.yourReply': 'Your reply:',
  'taskDetail.price': 'Price:',
  'taskDetail.tasks': 'tasks',

  'auth.applyForTask': 'Apply for task',
  'auth.askQuestion': 'Ask question',
  'auth.createTask': 'Create a task',
  'auth.loginToContinue': 'Please log in to continue',
  'auth.applyDescription':
    'Submit an application to the client and get the opportunity to work on this task.',
  'auth.questionDescription':
    'Ask the client a question before applying for the task.',
  'auth.createTaskDescription':
    'Create a new task and find trusted professionals to complete your work.',
  'auth.loginDescription':
    'Access your account to manage tasks and connect with professionals.',
  'auth.email': 'Email address',
  'auth.password': 'Password',
  'auth.rememberMe': 'Remember me',
  'auth.forgotPassword': 'Forgot password?',
  'auth.loginOrRegister': 'Login / Register',
  'auth.loginOrRegisterToContinue': 'Please login or register to continue',
  'auth.loginOrRegisterDescription': 'Enter your credentials to access your account or create a new one.',
  'auth.continue': 'Continue',
  'auth.login': 'Log In',
  'auth.or': 'or',
  'auth.noAccount': "Don't have an account?",
  'auth.createAccount': 'Create Account',
  'auth.whyRegister': 'Why register?',
  'auth.benefit1': '• Apply for tasks',
  'auth.benefit2': '• Communicate directly with clients',
  'auth.benefit3': '• Track your history',
  'auth.benefit4': '• Get notifications for new tasks',
  'auth.continueWith': 'Continue with',

  // Application Dialog
  'application.title': 'Apply for this Task',
  'application.proposedPrice': 'Your Price',
  'application.pricePlaceholder': 'Enter your price in BGN',
  'application.timeline': 'When can you start?',
  'application.timelineToday': 'Today',
  'application.timeline3days': 'Within 3 days',
  'application.timelineWeek': 'Within a week',
  'application.timelineFlexible': 'Flexible',
  'application.message': 'Why are you the best fit?',
  'application.messagePlaceholder': 'Share your relevant experience and why you\'re perfect for this task...',
  'application.messageInfo': 'Focus on your skills and experience. Contact details can be shared after your application is accepted.',
  'application.characterCount': '{{current}}/{{max}} characters',
  'application.submit': 'Submit Application',
  'application.submitting': 'Submitting...',
  'application.cancel': 'Cancel',
  'application.success': 'Application Submitted!',
  'application.successMessage': 'The task owner will review your application and respond soon.',
  'application.viewApplication': 'View My Application',
  'application.browseOther': 'Browse Other Tasks',
  'application.errors.priceRequired': 'Price is required',
  'application.errors.priceMin': 'Price must be greater than 0',
  'application.errors.timelineRequired': 'Timeline is required',
  'application.errors.messageRequired': 'Message is required',
  'application.errors.messageMin': 'Message must be at least 30 characters',
  'application.errors.messageMax': 'Message cannot exceed 500 characters',
  'application.errors.noPhoneNumbers': 'Phone numbers are not allowed in applications. You can exchange contact info after your application is accepted.',
  'application.errors.noUrls': 'URLs and links are not allowed in applications. You can share your portfolio after your application is accepted.',
  'application.errors.noEmails': 'Email addresses are not allowed in applications. You can exchange contact info after your application is accepted.',
  'application.alreadyApplied': 'You have already applied to this task',
  'application.cannotApplyOwnTask': 'You cannot apply to your own task',

  'message.taskCreated': 'Task created successfully!',
  'message.profileUpdated': 'Profile updated successfully!',
  'message.applicationSubmitted': 'Application submitted successfully!',
  'error.generic': 'Something went wrong. Please try again.',
  'error.network': 'Network error. Please check your connection.',
  'error.unauthorized': 'You need to log in to access this page.',

  // Profile Page
  'profile.completion': 'Profile completion',
  'profile.settings': 'Settings',
  'profile.tabs.customer': 'Customer',
  'profile.tabs.professional': 'Professional',
  'profile.email': 'Email',
  'profile.phone': 'Phone',
  'profile.location': 'Location',
  'profile.memberSince': 'Member since',
  'profile.editPersonalInfo': 'Edit Personal Info',
  'profile.statistics': 'Statistics',
  'profile.verified': 'Verified',
  'profile.completed': 'Completed',
  'profile.active': 'Active',

  // Avatar Upload
  'profile.avatar.changeAvatar': 'Change Avatar',
  'profile.avatar.selectImage': 'Select Image',
  'profile.avatar.remove': 'Remove',
  'profile.avatar.supportedFormats': 'Supported formats: JPG, PNG, WebP (max 5MB)',
  'profile.avatar.invalidFileType': 'Invalid file type. Please select JPG, PNG, or WebP image.',
  'profile.avatar.fileTooLarge': 'File too large. Please select image smaller than 5MB.',
  'profile.avatar.uploadError': 'Failed to upload image. Please try again.',

  // Statistics Modal
  'profile.statistics.title': 'Account Statistics',
  'profile.statistics.description': 'View your performance metrics and activity overview',
  'profile.statistics.memberSince': 'Member Since',

  // Customer Statistics
  'profile.statistics.customer.overview': 'Customer Overview',
  'profile.statistics.customer.performance': 'Performance Metrics',
  'profile.statistics.customer.successRate': 'Success Rate',
  'profile.statistics.customer.responseRate': 'Response Rate',

  // Professional Statistics
  'profile.statistics.professional.business': 'Business Overview',
  'profile.statistics.professional.performance': 'Performance Metrics',
  'profile.statistics.professional.repeatClients': 'Repeat Clients',
  'profile.statistics.professional.monthlyEarnings': 'Monthly Earnings',

  // Customer Profile
  'profile.customer.personalInfo': 'Personal Information',
  'profile.customer.statistics': 'Statistics',
  'profile.customer.tasksPosted': 'Tasks Posted',
  'profile.customer.tasksCompleted': 'Tasks Completed',
  'profile.customer.averageRating': 'Average Rating',
  'profile.customer.totalSpent': 'Total Spent',
  'profile.customer.recentActivity': 'Recent Activity',
  'profile.customer.taskCompleted': 'Task Completed',
  'profile.customer.taskPosted': 'Task Posted',
  'profile.customer.viewAllTasks': 'View All Tasks',
  'profile.customer.notificationPreferences': 'Notification Preferences',
  'profile.customer.smsNotifications': 'SMS Notifications',
  'profile.customer.smsNotificationsDesc': 'Receive important updates via text message',

  // Professional Profile
  'profile.professional.info': 'Professional Information',
  'profile.professional.title': 'Professional Title',
  'profile.professional.description': 'Description',
  'profile.professional.hourlyRate': 'Hourly Rate',
  'profile.professional.availability': 'Availability',
  'profile.professional.skills': 'Skills',
  'profile.professional.statistics': 'Performance Statistics',
  'profile.professional.completedJobs': 'Completed Jobs',
  'profile.professional.totalEarnings': 'Total Earnings',
  'profile.professional.responseTime': 'Response Time',
  'profile.professional.performance': 'Performance Metrics',
  'profile.professional.profileViews': 'Profile Views',
  'profile.professional.completionRate': 'Completion Rate',
  'profile.professional.monthlyGrowth': 'Monthly Growth',
  'profile.professional.recentWork': 'Recent Work',
  'profile.professional.viewPortfolio': 'View Portfolio',
  'profile.professional.setupTitle': 'Set Up Your Professional Profile',
  'profile.professional.setupDescription': 'Complete your professional profile to start receiving job opportunities and connect with clients.',
  'profile.professional.setupProfile': 'Set Up Professional Profile',
  'profile.professional.businessSettings': 'Business Settings',
  'profile.professional.paymentMethod': 'Payment Method',
  'profile.professional.vatNumber': 'VAT Number',
  'profile.professional.serviceArea': 'Service Area',
  'profile.professional.setupFormDescription': 'Fill out your professional information to showcase your skills and experience.',
  'profile.professional.selectCategories': 'Select Categories',
  'profile.professional.serviceCategories': 'Service Categories',
  'profile.professional.verificationTrust': 'Verification & Trust',
  'profile.professional.phoneVerification': 'Phone Verification',
  'profile.professional.phoneVerificationRequired': 'Required for all professionals',
  'profile.professional.verified': 'Verified',
  'profile.professional.verifyPhone': 'Verify Phone',
  'profile.professional.acceptedPaymentMethods': 'Accepted Payment Methods',
  'profile.professional.businessHours': 'Business Hours',
  'profile.professional.businessHoursPlaceholder': 'e.g., Mon-Fri 8:00-18:00, Sat 9:00-14:00',
  'profile.professional.weekdaysLabel': 'Weekdays (Mon-Fri)',
  'profile.professional.weekendLabel': 'Weekend (Sat-Sun)',
  'profile.professional.startTime': 'Start Time',
  'profile.professional.endTime': 'End Time',
  'profile.professional.noPaymentMethods': 'No payment methods selected',
  'profile.professional.portfolioGallery': 'Portfolio Gallery',
  'profile.professional.portfolioDescription': 'Showcase your best work with before/after images',
  'profile.professional.addServiceCategories': 'Add Your Service Categories',
  'profile.professional.categoriesHelp': 'Help customers find you! Select the services you offer to start receiving task requests.',

  // Professional Setup Form
  'profile.professional.form.titlePlaceholder': 'e.g. Full Stack Developer, UX Designer, Marketing Consultant',
  'profile.professional.form.descriptionPlaceholder': 'Describe your professional background, expertise, and what makes you unique...',
  'profile.professional.form.experience': 'Experience Level',
  'profile.professional.form.portfolio': 'Portfolio URL (Optional)',
  'profile.professional.form.portfolioDescription': 'Link to your website, GitHub, or online portfolio',
  'profile.professional.form.selectedSkills': 'Selected Skills',
  'profile.professional.form.searchSkills': 'Search skills...',
  'profile.professional.form.suggestedSkills': 'Popular Skills',
  'profile.professional.form.addCustomSkill': 'Add Custom Skill',
  'profile.professional.form.customSkillPlaceholder': 'Enter skill name',
  'profile.professional.form.moreSkillsAvailable': 'and {{count}} more...',
  'profile.professional.form.skillsLimitNotice': 'We recommend selecting your top 10 skills for the best results.',
  'profile.professional.form.submitting': 'Creating Profile...',
  'profile.professional.form.createProfile': 'Create Professional Profile',

  // Experience Options
  'profile.professional.form.experienceOptions.beginner': '0-1 years',
  'profile.professional.form.experienceOptions.intermediate': '2-5 years',
  'profile.professional.form.experienceOptions.experienced': '5-10 years',
  'profile.professional.form.experienceOptions.expert': '10+ years',

  // Availability Options
  'profile.professional.form.availabilityOptions.available': 'Available',
  'profile.professional.form.availabilityOptions.busy': 'Busy',
  'profile.professional.form.availabilityOptions.unavailable': 'Unavailable',

  // Form Validation
  'profile.professional.form.validation.titleRequired': 'Professional title is required (minimum 3 characters)',
  'profile.professional.form.validation.descriptionRequired': 'Description is required (minimum 20 characters)',
  'profile.professional.form.validation.rateRequired': 'Hourly rate must be greater than 0',
  'profile.professional.form.validation.skillsRequired': 'Please select at least one skill',

  // Settings Modal
  'profile.settings.description': 'Manage your account preferences and privacy settings',
  'profile.settings.notifications': 'Notifications',
  'profile.settings.emailNotifications': 'Email Notifications',
  'profile.settings.emailNotificationsDesc': 'Receive updates about your tasks and account',
  'profile.settings.taskUpdates': 'Task Updates',
  'profile.settings.taskUpdatesDesc': 'Get notified when tasks have updates',
  'profile.settings.marketingEmails': 'Marketing Emails',
  'profile.settings.marketingEmailsDesc': 'Receive tips and promotional content',
  'profile.settings.pushNotifications': 'Push Notifications',
  'profile.settings.pushNotificationsDesc': 'Receive instant notifications on your device',
  'profile.settings.weeklyDigest': 'Weekly Digest',
  'profile.settings.weeklyDigestDesc': 'Get a weekly summary of your activity and opportunities',
  'profile.settings.privacy': 'Privacy',
  'profile.settings.profileVisibility': 'Profile Visibility',
  'profile.settings.profileVisibilityDesc': 'Make your profile visible to potential clients',
  'profile.settings.showContactInfo': 'Show Contact Info',
  'profile.settings.showContactInfoDesc': 'Display your contact information publicly',
  'profile.settings.interface': 'Interface',
  'profile.settings.darkMode': 'Dark Mode',
  'profile.settings.darkModeDesc': 'Switch to dark theme interface',
  'profile.settings.dangerZone': 'Danger Zone',
  'profile.settings.deleteAccount': 'Delete Account',
  'profile.settings.deleteAccountDesc': 'Permanently delete your account and all data',
  'profile.settings.deleteAccountConfirm': 'Account deletion will be implemented soon',

  // Customer Profile Form
  'profile.form.name': 'Full Name',
  'profile.form.saving': 'Saving...',
  'profile.form.validation.nameRequired': 'Name is required (minimum 2 characters)',
  'profile.form.validation.emailRequired': 'Email is required',
  'profile.form.validation.emailInvalid': 'Please enter a valid email address',
  'profile.form.validation.phoneRequired': 'Phone number is required',
  'profile.form.validation.phoneInvalid': 'Please enter a valid phone number',
  'profile.form.validation.locationRequired': 'Location is required (minimum 3 characters)',

  // Locations
  'locations.sofiaCenter': 'Sofia, Center',
  'locations.sofiaLyulin': 'Sofia, Lyulin',
  'locations.sofiaStudentski': 'Sofia, Studentski Grad',
  'locations.sofiaVitosha': 'Sofia, Vitosha',
  'locations.plovdiv': 'Plovdiv',
  'locations.varna': 'Varna',
  'locations.burgas': 'Burgas',
  'locations.ruse': 'Ruse',
  'locations.staraZagora': 'Stara Zagora',

  // Notifications
  'notifications.title': 'Notifications',
  'notifications.markAllRead': 'Mark all as read',
  'notifications.tabAll': 'All',
  'notifications.tabApplications': 'Applications',
  'notifications.tabTasks': 'Tasks',
  'notifications.tabMessages': 'Messages',
  'notifications.empty.title': 'No notifications yet',
  'notifications.empty.message': "You'll be notified when someone applies to your tasks or responds to your applications.",
  'notifications.empty.filterMessage': 'No notifications in this category.',
  'notifications.emptyUnread.title': "You're all caught up!",
  'notifications.emptyUnread.message': 'All notifications have been read.',
  'notifications.viewApplication': 'View Application',
  'notifications.viewTask': 'View Task',

  // Applications Management
  'applications.title': 'Applications',
  'applications.count': 'applications',
  'applications.sortBy': 'Sort by',
  'applications.sortNewest': 'Newest First',
  'applications.sortPriceLow': 'Price: Low to High',
  'applications.sortPriceHigh': 'Price: High to Low',
  'applications.sortRating': 'Highest Rated',
  'applications.sortExperience': 'Most Experience',
  'applications.filterAll': 'All',
  'applications.filterPending': 'Pending',
  'applications.filterAccepted': 'Accepted',
  'applications.filterRejected': 'Rejected',
  'applications.emptyState.title': 'No applications yet',
  'applications.emptyState.message': 'Your task is live! Professionals will start applying soon.',
  'applications.proposedPrice': 'Proposed Price',
  'applications.timeline': 'Timeline',
  'applications.message': 'Message',
  'applications.portfolio': 'Portfolio',
  'applications.portfolioImages': 'portfolio images',
  'applications.tasksCompleted': 'tasks completed',
  'applications.yearsExperience': 'years experience',
  'applications.viewDetails': 'View Details',
  'applications.acceptApplication': 'Accept',
  'applications.rejectApplication': 'Reject',
  'applications.status': 'Status',
  'applications.statusPending': 'Pending',
  'applications.statusAccepted': 'Accepted',
  'applications.statusRejected': 'Rejected',

  // Application Detail Modal
  'applicationDetail.title': 'Application Details',
  'applicationDetail.professionalProfile': 'Professional Profile',
  'applicationDetail.applicationMessage': 'Application Message',
  'applicationDetail.portfolioGallery': 'Portfolio',
  'applicationDetail.recentReviews': 'Recent Reviews',
  'applicationDetail.close': 'Close',

  // Accept Application Dialog
  'acceptApplication.title': 'Accept Application',
  'acceptApplication.description': 'You are about to accept the application from {{name}}. Please review the details and confirm your agreement.',
  'acceptApplication.agreedPrice': 'Agreed Price',
  'acceptApplication.timeline': 'Timeline',
  'acceptApplication.pleaseConfirm': 'Please confirm:',
  'acceptApplication.agreement.priceTimeline': 'I agree to the proposed price ({{price}} {{currency}}) and timeline ({{timeline}})',
  'acceptApplication.agreement.contactSharing': 'I understand my contact information will be shared with {{name}}',
  'acceptApplication.agreement.otherApplications': 'I understand that all other pending applications will be automatically rejected',
  'acceptApplication.warning': 'Once you accept this application, you\'ll be committed to working with {{name}}. All other applications will be rejected automatically.',
  'acceptApplication.confirm': 'Accept Application',
  'acceptApplication.cancel': 'Cancel',

  // Reject Application Dialog
  'rejectApplication.title': 'Reject Application',
  'rejectApplication.description': 'You are about to reject the application from {{name}}. This action will notify the professional that you won\'t be moving forward with their application.',
  'rejectApplication.reasonTitle': 'Reason for rejection (optional)',
  'rejectApplication.reasonHelp': 'Providing a reason helps professionals improve their future applications.',
  'rejectApplication.reasons.betterFit': 'Found a better fit for this task',
  'rejectApplication.reasons.priceHigh': 'Price is too high',
  'rejectApplication.reasons.timelineIssue': 'Timeline doesn\'t work for me',
  'rejectApplication.reasons.changedMind': 'Changed my mind about the task',
  'rejectApplication.reasons.other': 'Other reason',
  'rejectApplication.note': '{{name}} will be notified that their application was not selected. You can still browse other applications and accept a different professional.',
  'rejectApplication.confirm': 'Reject Application',
  'rejectApplication.cancel': 'Cancel',

  // Professional Applications Dashboard
  'myApplications.title': 'My Applications',
  'myApplications.count': '{{count}} applications',
  'myApplications.sortBy': 'Sort by',
  'myApplications.sortNewest': 'Newest First',
  'myApplications.sortOldest': 'Oldest First',
  'myApplications.sortStatus': 'By Status',
  'myApplications.sortTaskDate': 'Task Date',
  'myApplications.sortPriceHigh': 'Price: High to Low',
  'myApplications.sortPriceLow': 'Price: Low to High',
  'myApplications.filterAll': 'All',
  'myApplications.filterPending': 'Pending',
  'myApplications.filterAccepted': 'Accepted',
  'myApplications.filterRejected': 'Rejected',
  'myApplications.filterWithdrawn': 'Withdrawn',
  'myApplications.status.pending': 'Pending',
  'myApplications.status.accepted': 'Accepted',
  'myApplications.status.rejected': 'Rejected',
  'myApplications.status.withdrawn': 'Withdrawn',
  'myApplications.appliedAgo': 'Applied {{time}}',
  'myApplications.acceptedAgo': 'Accepted {{time}}',
  'myApplications.rejectedAgo': 'Rejected {{time}}',
  'myApplications.yourQuote': 'Your Quote',
  'myApplications.taskBudget': 'Task Budget',
  'myApplications.timeline': 'Timeline',
  'myApplications.agreedPrice': 'Agreed Price',
  'myApplications.startDate': 'Starts',
  'myApplications.viewDetails': 'View Details',
  'myApplications.viewTask': 'View Task',
  'myApplications.withdraw': 'Withdraw',
  'myApplications.messageCustomer': 'Message Customer',
  'myApplications.markStarted': 'Mark as Started',
  'myApplications.markCompleted': 'Mark as Completed',
  'myApplications.reportIssue': 'Report Issue',
  'myApplications.findSimilar': 'Find Similar',
  'myApplications.delete': 'Delete',
  'myApplications.emptyState.title': 'You haven\'t applied to any tasks yet',
  'myApplications.emptyState.message': 'Start browsing available tasks and apply to the ones that match your skills.',
  'myApplications.emptyState.browse': 'Browse Tasks',
  'myApplications.emptyStatePending.title': 'All caught up!',
  'myApplications.emptyStatePending.message': 'You have no pending applications. All your applications have been reviewed.',
  'myApplications.emptyStateAccepted.title': 'No accepted applications yet',
  'myApplications.emptyStateAccepted.message': 'Keep applying! Your next opportunity is just around the corner.',
  'myApplications.withdrawDialog.title': 'Withdraw Application?',
  'myApplications.withdrawDialog.reason': 'Reason (optional)',
  'myApplications.withdrawDialog.reasonUnavailable': 'No longer available',
  'myApplications.withdrawDialog.reasonFoundWork': 'Found other work',
  'myApplications.withdrawDialog.reasonChanged': 'Task requirements changed',
  'myApplications.withdrawDialog.reasonPrice': 'Price too low',
  'myApplications.withdrawDialog.reasonOther': 'Other',
  'myApplications.withdrawDialog.confirm': 'Confirm Withdrawal',
  'myApplications.withdrawDialog.cancel': 'Cancel',
  'myApplications.detail.taskDetails': 'Task Details',
  'myApplications.detail.yourProposal': 'Your Proposal',
  'myApplications.detail.agreedTerms': 'Agreed Terms',
  'myApplications.detail.rejectionReason': 'Rejection Reason',
  'myApplications.detail.waitingResponse': 'Waiting for Customer Response',
  'myApplications.detail.usuallyResponds': 'Usually responds within 24 hours',
  'myApplications.detail.otherApplicants': '{{count}} other professionals applied',
  'myApplications.detail.nextSteps': 'Next Steps',
  'myApplications.detail.customerApproved': 'Customer approved your application',
  'myApplications.detail.contactCustomer': 'Contact customer to confirm details',
  'myApplications.detail.completeBy': 'Complete task by {{date}}',
  'myApplications.detail.feedback': 'Don\'t take it personally! Keep applying to similar tasks.',
  close: 'Close',

  // Posted Tasks Page (Customer View)
  'postedTasks.title': 'My Posted Tasks',
  'postedTasks.subtitle': 'Manage tasks you\'ve created',
  'postedTasks.createTask': 'Create Task',
  'postedTasks.filter.all': 'All',
  'postedTasks.filter.open': 'Open',
  'postedTasks.filter.inProgress': 'In Progress',
  'postedTasks.filter.completed': 'Completed',
  'postedTasks.filter.cancelled': 'Cancelled',
  'postedTasks.applicationsCount': '{{count}} applications',
  'postedTasks.viewApplications': 'View Applications',
  'postedTasks.viewDetails': 'View Details',
  'postedTasks.acceptedProfessional': 'Accepted Professional',
  'postedTasks.empty.title': 'No tasks posted yet',
  'postedTasks.empty.message': 'You haven\'t posted any tasks yet. Create your first task!',
  'postedTasks.empty.createButton': 'Create Task',

  // My Applications Page (Professional View)
  'myApplications.subtitle': 'Applications you\'ve submitted to tasks',
  'myApplications.browseButton': 'Browse Tasks',
  'myApplications.filter.all': 'All',
  'myApplications.filter.pending': 'Pending',
  'myApplications.filter.accepted': 'Accepted',
  'myApplications.filter.rejected': 'Rejected',
  'myApplications.filter.withdrawn': 'Withdrawn',
  'myApplications.yourProposal': 'Your Proposal',
  'myApplications.proposedPrice': '{{price}} BGN',
  'myApplications.taskBudget': 'Task Budget',
  'myApplications.submitted': 'Submitted',
  'myApplications.empty.title': 'No applications yet',
  'myApplications.empty.message': 'You haven\'t applied to any tasks yet. Browse available tasks!',
  'myApplications.empty.browseButton': 'Browse Tasks',

  // Task Completion & Status
  'taskStatus.open': 'Open',
  'taskStatus.inProgress': 'In Progress',
  'taskStatus.awaitingConfirmation': 'Awaiting Confirmation',
  'taskStatus.completed': 'Completed',
  'taskStatus.cancelled': 'Cancelled',
  'taskStatus.underReview': 'Under Review',
  'taskStatus.openTooltip': 'Accepting applications from professionals',
  'taskStatus.inProgressTooltip': 'Work is currently in progress',
  'taskStatus.pendingProfessionalTooltip': 'Waiting for professional to confirm completion',
  'taskStatus.pendingCustomerTooltip': 'Waiting for customer to confirm completion',
  'taskStatus.completedTooltip': 'Task completed successfully',
  'taskStatus.cancelledTooltip': 'Task was cancelled',
  'taskStatus.disputedTooltip': 'Under review by admin',

  // Task Completion Actions
  'taskCompletion.markCompleted': 'Mark as Completed',
  'taskCompletion.confirmCompletion': 'Confirm Completion',
  'taskCompletion.rejectCompletion': 'Reject Completion',
  'taskCompletion.alreadyMarkedByYou': 'You marked as complete',
  'taskCompletion.alreadyConfirmedByYou': 'You already confirmed',

  // Mark Completed Dialog (Professional)
  'taskCompletion.markDialog.title': 'Mark Task as Completed?',
  'taskCompletion.markDialog.task': 'Task',
  'taskCompletion.markDialog.customer': 'Customer',
  'taskCompletion.markDialog.payment': 'Payment',
  'taskCompletion.markDialog.question': 'Have you finished all work?',
  'taskCompletion.markDialog.checkRequirements': 'All requirements completed',
  'taskCompletion.markDialog.checkSatisfied': 'Customer satisfied with result',
  'taskCompletion.markDialog.photos': 'Upload completion photos (optional)',
  'taskCompletion.markDialog.addPhotos': 'Add Photos',
  'taskCompletion.markDialog.notes': 'Additional notes',
  'taskCompletion.markDialog.notesPlaceholder': 'Any final notes about the completed work...',

  // Confirm Completion Dialog (Customer)
  'taskCompletion.confirmDialog.title': 'Confirm Task Completion?',
  'taskCompletion.confirmDialog.professional': 'Professional',
  'taskCompletion.confirmDialog.task': 'Task',
  'taskCompletion.confirmDialog.question': 'Is the work completed to your satisfaction?',
  'taskCompletion.confirmDialog.yes': 'Yes, I\'m satisfied',
  'taskCompletion.confirmDialog.no': 'No, there are issues',
  'taskCompletion.confirmDialog.greatMessage': 'Great! Thank you for confirming.',
  'taskCompletion.confirmDialog.reviewReminder': 'You\'ll be able to leave a review after confirmation.',

  // Rejection Flow
  'taskCompletion.reject.title': 'Please explain the issue',
  'taskCompletion.reject.reason': 'Why are you rejecting?',
  'taskCompletion.reject.notCompleted': 'Work not completed',
  'taskCompletion.reject.poorQuality': 'Poor quality',
  'taskCompletion.reject.differentScope': 'Different from agreed scope',
  'taskCompletion.reject.other': 'Other issues',
  'taskCompletion.reject.explain': 'Describe the issue',
  'taskCompletion.reject.explainPlaceholder': 'Please provide details about what needs to be fixed...',
  'taskCompletion.reject.warning': 'Task will return to "In Progress". You can discuss with the professional and they can rework it.',
  'taskCompletion.reject.disclaimer': 'This task will return to "In Progress" status and may become visible to other professionals again if work cannot be completed with the current professional.',
  'taskCompletion.reject.button': 'Reject',

  // Pending Confirmation Banner
  'taskCompletion.pending.waitingCustomer': 'Waiting for Customer Confirmation',
  'taskCompletion.pending.waitingProfessional': 'Waiting for Professional Confirmation',
  'taskCompletion.pending.professionalMarkedComplete': 'Professional Marked Task Complete',
  'taskCompletion.pending.customerMarkedComplete': 'Customer Marked Task Complete',
  'taskCompletion.pending.markedComplete': 'marked this task as completed.',
  'taskCompletion.pending.youMarked': 'You marked this task as completed.',
  'taskCompletion.pending.waitingFor': 'Waiting for',
  'taskCompletion.pending.toConfirm': 'to confirm.',

  // Success View
  'taskCompletion.success.title': 'Task Completed!',
  'taskCompletion.success.message': 'Great work! Both parties have confirmed task completion.',
  'taskCompletion.success.nextSteps': 'Next Steps',
  'taskCompletion.success.step1': 'Leave a review',
  'taskCompletion.success.step1Description': 'Share your experience working with {{name}}',
  'taskCompletion.success.step2': 'Task archived in 30 days',
  'taskCompletion.success.step2Description': 'Task will be automatically archived',
  'taskCompletion.success.leaveReview': 'Leave Review',
  'taskCompletion.success.viewDetails': 'View Task Details',

  // Timeline
  'taskCompletion.timeline.title': 'Task Progress',
  'taskCompletion.timeline.started': 'Started',
  'taskCompletion.timeline.proMarked': 'Professional Marked Complete',
  'taskCompletion.timeline.customerConfirmed': 'Customer Confirmed',
  'taskCompletion.timeline.completed': 'Completed',
  'taskCompletion.timeline.pending': 'Pending',
  'taskCompletion.timeline.totalDuration': 'Total Duration',

  // Common
  'common.optional': 'Optional',
  'common.days': 'days',
  'common.cancel': 'Cancel',
};

export default en;
