const ru = {
  welcome: 'Добро пожаловать',
  login: 'Войти',
  logout: 'Выйти',
  signup: 'Регистрация',
  search: 'Поиск',
  browse: 'Обзор',
  create: 'Создать',
  edit: 'Редактировать',
  delete: 'Удалить',
  cancel: 'Отмена',
  save: 'Сохранить',
  submit: 'Отправить',
  loading: 'Загрузка...',
  error: 'Ошибка',
  success: 'Успех',
  back: 'Назад',
  next: 'Далее',
  previous: 'Предыдущая',
  home: 'Главная',
  profile: 'Профиль',
  settings: 'Настройки',

  'nav.home': 'Главная',
  'nav.browseTasks': 'Задачи',
  'nav.createTask': 'Создать',
  'nav.profile': 'Профиль',
  'nav.howItWorks': 'Как работает',
  'nav.categories': 'Категории',
  'nav.forProfessionals': 'Профессионалы',

  'landing.hero.title': 'Найдите проверенных местных специалистов',
  'landing.hero.subtitle':
    'Свяжитесь с верифицированными поставщиками услуг для всех ваших потребностей в вашем районе',
  'landing.hero.getStarted': 'Начать',
  'landing.hero.browseServices': 'Обзор услуг',

  'landing.trustIndicators.verified': 'Проверенные специалисты',
  'landing.trustIndicators.securePayments': 'Безопасные платежи',
  'landing.trustIndicators.support': 'Поддержка 24/7',

  'landing.stats.averageRating': 'средний рейтинг',
  'landing.stats.completedTasks': 'выполненных задач',
  'landing.categories.activeSpecialists': 'активных специалистов',

  'landing.categories.title': 'Популярные категории',
  'landing.categories.subtitle':
    'Найдите специалистов для любой задачи - от ремонта дома до персональной помощи',
  'landing.categories.viewAll': 'Посмотреть все категории',
  'landing.categories.home': 'Дом и сад',
  'landing.categories.home.description':
    'Электричество, сантехника, уборка, техобслуживание',
  'landing.categories.tech': 'Технологии',
  'landing.categories.tech.description':
    'IT поддержка, веб-дизайн, разработка ПО',
  'landing.categories.business': 'Бизнес-услуги',
  'landing.categories.business.description':
    'Административные задачи, мероприятия, консультации',
  'landing.categories.personal': 'Личные услуги',
  'landing.categories.personal.description':
    'Уход за питомцами, детьми, пожилыми',
  'landing.categories.education': 'Образование и обучение',
  'landing.categories.creative': 'Творческие услуги',

  'landing.featured.title': 'Рекомендуемые задачи',
  'landing.featured.badge': 'Последние возможности',
  'landing.featured.viewAll': 'Посмотреть все задачи',

  'landing.howItWorks.title': 'Как это работает',
  'landing.howItWorks.subtitle':
    'Простой процесс поиска и выполнения задач с проверенными специалистами',
  'landing.howItWorks.forCustomers': 'Для клиентов',
  'landing.howItWorks.forProfessionals': 'Для специалистов',
  'landing.howItWorks.step1.title': 'Опубликуйте вашу задачу',
  'landing.howItWorks.step1.description':
    'Опишите, что нужно сделать, и установите ваш бюджет',
  'landing.howItWorks.step2.title': 'Получите предложения',
  'landing.howItWorks.step2.description':
    'Получайте заявки от верифицированных специалистов',
  'landing.howItWorks.step3.title': 'Выберите и завершите',
  'landing.howItWorks.step3.description':
    'Выберите лучшего специалиста и выполните вашу задачу',

  'tasks.title': 'Обзор задач',
  'tasks.subtitle':
    'Найдите идеальную задачу, которая соответствует вашим навыкам и интересам',
  'tasks.searchPlaceholder':
    'Поиск задач по ключевым словам, категориям или местоположению...',
  'tasks.filters.title': 'Фильтры',
  'tasks.filters.category': 'Категория',
  'tasks.filters.allCategories': 'Все категории',
  'tasks.filters.location': 'Местоположение',
  'tasks.filters.budget': 'Бюджет',
  'tasks.filters.budgetMin': 'Мин. бюджет',
  'tasks.filters.budgetMax': 'Макс. бюджет',
  'tasks.filters.deadline': 'Срок',
  'tasks.filters.status': 'Статус',
  'tasks.filters.all': 'Все',
  'tasks.filters.open': 'Открытые',
  'tasks.filters.inProgress': 'В процессе',
  'tasks.filters.completed': 'Завершенные',
  'tasks.filters.activeFilters': 'Активные фильтры',
  'tasks.filters.clearAll': 'Очистить все',
  'tasks.results': 'результатов',
  'tasks.sort.newest': 'Сначала новые',
  'tasks.sort.oldest': 'Сначала старые',
  'tasks.sort.budgetHigh': 'Высокий бюджет',
  'tasks.sort.budgetLow': 'Низкий бюджет',
  'tasks.sort.deadline': 'По сроку',

  'professionals.hero.title': 'Найдите проверенных специалистов',
  'professionals.hero.subtitle':
    'Просматривайте верифицированных специалистов по категориям и найдите идеальное соответствие для ваших потребностей',
  'professionals.hero.badge': 'Сеть профессионалов',
  'professionals.searchPlaceholder':
    'Поиск категорий... (например, ремонт, уборка, уроки)',
  'professionals.allCategories': 'Все категории',
  'professionals.featuredTitle': 'Рекомендуемые специалисты',
  'professionals.viewProfile': 'Посмотреть профиль',
  'professionals.rating': 'Рейтинг',
  'professionals.completedJobs': 'Выполненные задания',
  'professionals.startingFrom': 'Начиная от',
  'professionals.noResults': 'Нет категорий, соответствующих вашему поиску',
  'professionals.categoryResults': 'категории найдены',
  'professionals.filterBy': 'Фильтровать по',
  'professionals.location': 'Местоположение',
  'professionals.experience': 'Опыт',
  'professionals.priceRange': 'Ценовой диапазон',
  'professionals.availability': 'Доступность',
  'professionals.findPerfect': 'Найдите идеального профессионала',
  'professionals.discoverTrusted':
    'Откройте для себя надежных профессионалов с проверенной репутацией и отличными отзывами',
  'professionals.popularCategories': 'Популярные категории',
  'professionals.refineSearch': 'Уточните результаты поиска',
  'professionals.professionalsAvailable': 'доступных профессионалов',
  'professionals.noMatchingResults':
    'Нет профессионалов, соответствующих вашим критериям. Попробуйте расширить поиск.',
  'professionals.mostActive': 'Наиболее активные',
  'professionals.gender.male': 'Мужчина',
  'professionals.gender.female': 'Женщина',
  'professionals.filters.category': 'Категория',
  'professionals.filters.location': 'Местоположение',
  'professionals.filters.minimumRating': 'Минимальный рейтинг',
  'professionals.filters.genderPreference': 'Предпочтение по полу',
  'professionals.filters.activityLevel': 'Уровень активности',
  'professionals.filters.all': 'Все',
  'professionals.filters.topPerformersOnly': 'Только топ исполнители',
  'professionals.filters.locationPlaceholder': 'София, Пловдив, Варна...',
  'professionals.filters.any': 'Любой',
  'professionals.filters.anyShort': 'Любой',
  'professionals.typing.plumber': 'сантехник в Софии',
  'professionals.typing.cleaner': 'специалист по уборке',
  'professionals.typing.electrician': 'сертифицированный электрик',
  'professionals.typing.tutor': 'учитель английского',
  'professionals.typing.photographer': 'свадебный фотограф',
  'professionals.typing.handyman': 'мастер на все руки',
  'professionals.recommendedTitle': 'РЕКОМЕНДУЕМЫЕ ПРОФЕССИОНАЛЫ',
  'professionals.filters.clear': 'Очистить',
  'professionals.filters.clearAll': 'Очистить все фильтры',
  'professionals.filters.fourPlusStars': '4+ звезд',
  'professionals.filters.fiveStarsOnly': 'Только 5 звезд',
  'professionals.filters.anyRating': 'По рейтингу',
  'professionals.filters.showProfessionalsWithAnyRating':
    'Показать профессионалов с любым рейтингом',
  'professionals.filters.locationPlaceholderDesktop': '📍 Местоположение',
  'professionals.sorting.featuredFirst': 'Топ выбор',
  'professionals.sorting.featuredFirstDesc': 'Лучшие профессионалы',
  'professionals.sorting.highestRating': 'По рейтингу',
  'professionals.sorting.highestRatingDesc': 'С лучшими отзывами',
  'professionals.sorting.mostExperience': 'По опыту',
  'professionals.sorting.mostExperienceDesc': 'Много заказов',
  'professionals.filters.sortResultsBy': 'Сортировка по',
  'professionals.filters.sortResultsTitle': 'Сортировка',
  'professionals.filters.sortResultsDescription':
    'Выберите, как упорядочить профессионалов',
  'professionals.filters.selectMinimumRating': 'Выберите минимальный рейтинг',
  'professionals.filters.showingVerifiedFirst':
    'Показать проверенных топ профессионалов первыми',
  'professionals.filters.proTip': 'Совет',
  'professionals.filters.proTipMessage':
    'Попробуйте "{{sortOption}}" для качественных профессионалов с подтвержденными квалификациями',
  'professionals.filters.sortingBy': 'Сортировка по {{option}}',
  'professionals.filters.sortingDescFeatured':
    'Показать проверенных топ профессионалов первыми',
  'professionals.filters.sortingDescRating':
    'Профессионалы с высшим рейтингом показываются первыми',
  'professionals.filters.sortingDescJobs':
    'Самые опытные профессионалы показываются первыми',
  'professionals.filters.activeFilters': 'Активные фильтры',
  'professionals.filters.filterApplied': '{{count}} фильтр применен',
  'professionals.filters.filtersApplied': '{{count}} фильтров применено',
  'professionals.filters.showProfessionalsWithRating':
    'Показать профессионалов с {{rating}}+ звездным рейтингом',
  'professionals.filters.showPerfectRating':
    'Показать только профессионалов с совершенным 5-звездным рейтингом',

  'browseTasks.hero.badge': 'Найдите идеальных специалистов',
  'browseTasks.hero.title1': 'Найдите идеальную',
  'browseTasks.hero.title2': 'задачу для вас',
  'browseTasks.hero.subtitle':
    'Просмотрите сотни возможностей от проверенных клиентов. Начните работать сегодня.',
  'browseTasks.search.placeholder':
    'Поиск задач по ключевым словам, категории или городу...',
  'browseTasks.search.popular': 'Популярные',
  'browseTasks.filters.title': 'Фильтрация и сортировка',
  'browseTasks.filters.advanced': 'Расширенные фильтры',
  'browseTasks.filters.quick': 'Быстрый фильтр',
  'browseTasks.filters.searchPlaceholder':
    'Поиск задач... (например, уборка, ремонт, доставка)',
  'browseTasks.filters.category': 'Категория',
  'browseTasks.filters.allCategories': 'Все категории',
  'browseTasks.filters.city': 'Город',
  'browseTasks.filters.allCities': 'Все города',
  'browseTasks.filters.cities.sofia': 'София',
  'browseTasks.filters.cities.plovdiv': 'Пловдив',
  'browseTasks.filters.cities.varna': 'Варна',
  'browseTasks.filters.cities.burgas': 'Бургас',
  'browseTasks.filters.budget': 'Бюджет',
  'browseTasks.filters.budgetMin': 'Мин',
  'browseTasks.filters.budgetMax': 'Макс',
  'browseTasks.filters.budgetUpTo': 'До 500 лв',
  'browseTasks.filters.sortBy': 'Сортировка',
  'browseTasks.filters.sort.newest': 'Новые',
  'browseTasks.filters.sort.oldest': 'Старые',
  'browseTasks.filters.sort.highBudget': 'Высокий бюджет',
  'browseTasks.filters.sort.lowBudget': 'Низкий бюджет',
  'browseTasks.results.shown': 'Показано {{count}} результатов',
  'browseTasks.results.featured': 'Показано {{count}} популярных задач',
  'browseTasks.results.loading': 'Загрузка...',
  'browseTasks.results.noTasks.title': 'Задачи не найдены',
  'browseTasks.results.noTasks.description':
    'Попробуйте изменить фильтры или искать по другим критериям.',
  'browseTasks.results.noTasks.clearFilters': 'Очистить фильтры',
  'browseTasks.results.suggestedTasks':
    'Популярные задачи, которые могут вам понравиться',
  'browseTasks.results.suggestedDescription':
    'Вот некоторые популярные задачи из нашего сообщества',
  'browseTasks.results.error.title': 'Ошибка при загрузке',
  'browseTasks.results.error.description':
    'Пожалуйста, попробуйте снова или обратитесь в службу поддержки.',
  'browseTasks.pagination.previous': 'Предыдущая',
  'browseTasks.pagination.next': 'Следующая',
  'browseTasks.search.tags.programming': 'Программирование',
  'browseTasks.search.tags.design': 'Дизайн',
  'browseTasks.search.tags.marketing': 'Маркетинг',
  'browseTasks.search.tags.translation': 'Переводы',
  'browseTasks.search.tags.photography': 'Фотография',
  'browseTasks.typing.plumber': 'сантехник в Софии',
  'browseTasks.typing.cleaner': 'уборка дома',
  'browseTasks.typing.electrician': 'ремонт электрики',
  'browseTasks.typing.tutor': 'учитель английского',
  'browseTasks.typing.moving': 'перевозка мебели',
  'browseTasks.typing.gardener': 'уход за садом',

  'task.budget': 'Бюджет',
  'task.location': 'Местоположение',
  'task.category': 'Категория',
  'task.applications': 'Заявки',
  'task.viewDetails': 'Посмотреть детали',
  'task.apply': 'Подать заявку',
  'task.created': 'Создана',
  'task.deadline': 'Срок',

  'createTask.title': 'Создать новую задачу',
  'createTask.form.title': 'Название задачи',
  'createTask.form.titlePlaceholder': 'Что нужно сделать?',
  'createTask.form.description': 'Описание',
  'createTask.form.descriptionPlaceholder': 'Опишите вашу задачу подробно...',
  'createTask.form.category': 'Категория',
  'createTask.form.selectCategory': 'Выберите категорию',
  'createTask.form.budget': 'Бюджет (лв.)',
  'createTask.form.budgetPlaceholder': 'Введите ваш бюджет',
  'createTask.form.location': 'Местоположение',
  'createTask.form.locationPlaceholder': 'Введите местоположение',
  'createTask.form.deadline': 'Срок',
  'createTask.form.selectDeadline': 'Выберите срок',
  'createTask.form.images': 'Изображения (необязательно)',
  'createTask.form.imagesDescription':
    'Загрузите изображения, чтобы помочь описать вашу задачу',
  'createTask.form.postTask': 'Опубликовать задачу',

  'profile.title': 'Мой профиль',
  'profile.personalInfo': 'Личная информация',
  'profile.professionalInfo': 'Профессиональная информация',
  'profile.verification': 'Верификация',
  'profile.reviews': 'Отзывы',
  'profile.stats': 'Статистика',

  'profile.form.firstName': 'Имя',
  'profile.form.lastName': 'Фамилия',
  'profile.form.email': 'Email',
  'profile.form.phone': 'Телефон',
  'profile.form.location': 'Местоположение',
  'profile.form.bio': 'Биография',
  'profile.form.skills': 'Навыки',
  'profile.form.experience': 'Лет опыта',
  'profile.form.hourlyRate': 'Почасовая ставка (лв.)',
  'profile.form.vatNumber': 'НДС номер',
  'profile.form.businessName': 'Название компании',
  'profile.form.website': 'Веб-сайт',

  'profile.verification.identity': 'Личность верифицирована',
  'profile.verification.business': 'Бизнес верифицирован',
  'profile.verification.phone': 'Телефон верифицирован',
  'profile.verification.email': 'Email верифицирован',

  'language.en': 'English',
  'language.bg': 'Български',
  'language.ru': 'Русский',

  'landing.trustStats.securityUptime': 'Безопасность',
  'landing.trustStats.avgRating': 'Средний рейтинг',
  'landing.trustStats.encryption': 'Шифрование данных',
  'landing.trustStats.compliance': 'Правовое соответствие',

  'landing.trustIndicators.freeToUse': 'Бесплатно в использовании',
  'landing.trustIndicators.communityReviews': 'Отзывы сообщества',
  'landing.trustIndicators.verifiedDescription':
    'Все специалисты тщательно проверены',
  'landing.trustIndicators.ratingSystem': '5-звездная система рейтинга',
  'landing.trustIndicators.ratingSystemDescription':
    'Качество гарантировано через отзывы сообщества',
  'landing.trustIndicators.dataProtection': 'Защита данных',
  'landing.trustIndicators.dataProtectionDescription':
    'Ваша личная информация в безопасности',
  'landing.trustIndicators.contracts': 'Правовая защита',
  'landing.trustIndicators.contractsDescription':
    'Вся работа защищена четкими соглашениями',

  'landing.featured.subtitle':
    'Последние задачи, опубликованные нашим сообществом',
  'landing.featured.professionalDesc': 'Найдите свою следующую возможность',
  'landing.featured.customerDesc': 'Посмотрите, что публикуют другие',

  'landing.howItWorks.customers.step1.title': 'Создайте вашу задачу',
  'landing.howItWorks.customers.step1.description':
    'Опишите, что нужно сделать, и установите ваш бюджет',
  'landing.howItWorks.customers.step2.title': 'Получите предложения',
  'landing.howItWorks.customers.step2.description':
    'Получайте заявки от верифицированных специалистов',
  'landing.howItWorks.customers.step3.title': 'Выберите и завершите',
  'landing.howItWorks.customers.step3.description':
    'Выберите лучшего специалиста и выполните вашу задачу',

  'landing.howItWorks.professionals.step1.title': 'Просматривайте задачи',
  'landing.howItWorks.professionals.step1.description':
    'Найдите задачи, соответствующие вашим навыкам и доступности',
  'landing.howItWorks.professionals.step2.title': 'Отправьте предложение',
  'landing.howItWorks.professionals.step2.description':
    'Отправьте лучшее предложение и покажите свою экспертизу',
  'landing.howItWorks.professionals.step3.title': 'Выполните работу',
  'landing.howItWorks.professionals.step3.description':
    'Предоставьте качественную услугу и создайте репутацию',

  'landing.testimonials.title': 'Что говорят наши пользователи',
  'landing.testimonials.subtitle': 'Реальные отзывы нашего сообщества',
  'landing.testimonials.customers.title': 'От клиентов',
  'landing.testimonials.customers.customer1.name': 'Мария Иванова',
  'landing.testimonials.customers.customer1.location': 'София, Болгария',
  'landing.testimonials.customers.customer1.quote':
    'Нашла отличного сантехника за минуты. Профессиональная услуга и справедливые цены!',
  'landing.testimonials.customers.customer2.name': 'Георги Петров',
  'landing.testimonials.customers.customer2.location': 'Пловдив, Болгария',
  'landing.testimonials.customers.customer2.quote':
    'Услуга уборки была исключительной. Определенно буду использовать Trudify снова.',
  'landing.testimonials.customers.customer3.name': 'Елена Димитрова',
  'landing.testimonials.customers.customer3.location': 'Варна, Болгария',
  'landing.testimonials.customers.customer3.quote':
    'Быстро, надежно и доступно. Именно то, что я искала.',

  'landing.testimonials.professionals.title': 'От специалистов',
  'landing.testimonials.professionals.pro1.name': 'Иван Стоев',
  'landing.testimonials.professionals.pro1.profession': 'Электрик',
  'landing.testimonials.professionals.pro1.quote':
    'Trudify помог мне развить бизнес с постоянным потоком качественных клиентов.',
  'landing.testimonials.professionals.pro2.name': 'Анна Николова',
  'landing.testimonials.professionals.pro2.profession': 'Уборщица',
  'landing.testimonials.professionals.pro2.quote':
    'Простая в использовании платформа. Нравится, как я могу управлять расписанием и платежами.',
  'landing.testimonials.professionals.pro3.name': 'Димитар Георгиев',
  'landing.testimonials.professionals.pro3.profession': 'Мастер на все руки',
  'landing.testimonials.professionals.pro3.quote':
    'Профессиональная платформа, которая связывает меня с клиентами, ценящими качественную работу.',

  'landing.trustSection.title': 'Основана на доверии',
  'landing.trustSection.subtitle':
    'Ваша безопасность и удовлетворенность - наши главные приоритеты',

  'landing.cta.title': 'Готовы начать?',
  'landing.cta.subtitle':
    'Присоединяйтесь к тысячам довольных пользователей сегодня',
  'landing.cta.postTask': 'Создать задачу',
  'landing.cta.joinProfessionals': 'Присоединиться как специалист',
  'landing.cta.freeToJoin': 'Бесплатное присоединение, без скрытых комиссий',
  'landing.cta.stats.completedTasks': 'Выполненных задач',
  'landing.cta.stats.activeSpecialists': 'Активных специалистов',
  'landing.cta.stats.averageRating': 'Средний рейтинг',
  'landing.cta.stats.contractTemplates': 'Правовых шаблонов',

  'taskCard.apply': 'Откликнуться',
  'taskCard.anonymous': 'Анонимный',
  'taskCard.budget.from': 'от',
  'taskCard.budget.to': 'до',
  'taskCard.budget.negotiable': 'Договорная',
  'taskCard.deadline.flexible': 'Гибкий',
  'taskCard.deadline.today': 'Сегодня',
  'taskCard.deadline.tomorrow': 'Завтра',
  'taskCard.deadline.days': 'дней',
  'taskCard.category.home_repair': 'Домашние ремонты',
  'taskCard.category.delivery_transport': 'Доставка и транспорт',
  'taskCard.category.personal_care': 'Личный уход',
  'taskCard.category.personal_assistant': 'Личный помощник',
  'taskCard.category.learning_fitness': 'Обучение и фитнес',
  'taskCard.category.other': 'Другое',

  'categories.plumbing': 'Сантехника',
  'categories.electrical': 'Электричество',
  'categories.hvac': 'Кондиционеры и отопление',
  'categories.carpentry': 'Столярные работы',
  'categories.painting': 'Покраска',
  'categories.flooring': 'Напольные покрытия',
  'categories.roofing': 'Кровельные работы',
  'categories.homeRenovation': 'Ремонт дома',
  'categories.applianceRepair': 'Ремонт бытовой техники',
  'categories.handyman': 'Мастер на все руки',
  'categories.houseCleaning': 'Уборка дома',
  'categories.deepCleaning': 'Генеральная уборка',
  'categories.carpetCleaning': 'Чистка ковров',
  'categories.windowCleaning': 'Мытье окон',
  'categories.gardenMaintenance': 'Уход за садом',
  'categories.landscaping': 'Ландшафтный дизайн',
  'categories.delivery': 'Доставка',
  'categories.moving': 'Переезд',
  'categories.taxiDriver': 'Такси',
  'categories.courier': 'Курьер',
  'categories.babysitting': 'Няня',
  'categories.elderlyCare': 'Уход за пожилыми',
  'categories.petSitting': 'Присмотр за животными',
  'categories.personalTrainer': 'Персональный тренер',
  'categories.massageTherapy': 'Массаж',
  'categories.tutoring': 'Репетиторство',
  'categories.translation': 'Переводы',
  'categories.accounting': 'Бухгалтерия',
  'categories.legalServices': 'Юридические услуги',
  'categories.consulting': 'Консалтинг',
  'categories.graphicDesign': 'Графический дизайн',
  'categories.webDevelopment': 'Веб-разработка',
  'categories.photography': 'Фотография',
  'categories.videography': 'Видеосъемка',
  'categories.writing': 'Копирайтинг',
  'categories.musicLessons': 'Музыкальные уроки',
  'categories.eventPlanning': 'Организация мероприятий',
  'categories.catering': 'Кейтеринг',
  'categories.djServices': 'DJ услуги',
  'categories.hairdressing': 'Парикмахерские услуги',
  'categories.makeupArtist': 'Визаж',
  'categories.nailServices': 'Маникюр и педикюр',
  'categories.other': 'Другое',

  'professionalDetail.about': 'О специалисте',
  'professionalDetail.reviews': 'отзывов',
  'professionalDetail.online': 'Онлайн',
  'professionalDetail.offline': 'Недавно был в сети',
  'professionalDetail.verified.phone': 'Телефон',
  'professionalDetail.verified.id': 'Документ',
  'professionalDetail.stats.completedTasks': 'Задач',
  'professionalDetail.stats.yearsExperience': 'Лет',
  'professionalDetail.stats.responseTime': 'Ответ',
  'professionalDetail.actions.proposeTask': 'Предложить задачу',
  'professionalDetail.actions.contact': 'Связаться',
  'professionalDetail.actions.askQuestion': 'Задать вопрос',
  'professionalDetail.actions.saveToFavorites': 'В избранное',
  'professionalDetail.contactHours': 'Доступен',
  'professionalDetail.services.title': 'Услуги и цены',
  'professionalDetail.services.pricingNote.title': 'Информация о ценах',
  'professionalDetail.services.pricingNote.description':
    'Окончательные цены согласовываются индивидуально в зависимости от сложности и требований задачи.',
  'professionalDetail.portfolio.title': 'Мои примеры',
  'professionalDetail.portfolio.noWork': 'Пока нет примеров',
  'professionalDetail.portfolio.before': 'До',
  'professionalDetail.portfolio.after': 'После',
  'professionalDetail.portfolio.viewMore': 'Посмотреть все примеры',
  'professionalDetail.portfolio.showcase': 'Профессиональные примеры работ',
  'professionalDetail.completedTasks.title': 'Выполненные задачи',
  'professionalDetail.completedTasks.noTasks': 'Пока нет выполненных задач',
  'professionalDetail.completedTasks.viewTask': 'Посмотреть задачу',
  'professionalDetail.completedTasks.completedOn': 'Выполнено',
  'professionalDetail.reviews.title': 'Отзывы и рейтинги',
  'professionalDetail.reviews.count': 'отзывов',
  'professionalDetail.reviews.recentRating': 'Недавний рейтинг',
  'professionalDetail.reviews.excellent': 'Отлично',
  'professionalDetail.reviews.noReviews': 'Пока нет отзывов',
  'professionalDetail.reviews.beFirst': 'Станьте первым, кто оставит отзыв',
  'professionalDetail.reviews.showMore': 'Показать все отзывы',
  'professionalDetail.reviews.allReviews': 'Все отзывы',
  'professionalDetail.reviews.avgRating': 'Средний рейтинг',
  'professionalDetail.reviews.more': 'ещё',
  'professionalDetail.completedTasks.stats.tasksCompleted': 'Выполненных задач',
  'professionalDetail.completedTasks.stats.avgRating': 'Средний рейтинг',
  'professionalDetail.completedTasks.stats.fiveStarTasks':
    '5-звёздочные задачи',
  'professionalDetail.verified': 'Подтверждён',
  'common.anonymous': 'Анонимный пользователь',

  'footer.company.description':
    'Связываем людей с квалифицированными специалистами для всех видов услуг в Болгарии.',
  'footer.quickLinks.title': 'Быстрые ссылки',
  'footer.quickLinks.howItWorks': 'Как работает',
  'footer.quickLinks.categories': 'Категории',
  'footer.quickLinks.forProfessionals': 'Для специалистов',
  'footer.quickLinks.security': 'Безопасность',
  'footer.quickLinks.help': 'Помощь',
  'footer.legal.title': 'Правовые',
  'footer.legal.terms': 'Условия обслуживания',
  'footer.legal.privacy': 'Политика конфиденциальности',
  'footer.legal.gdpr': 'GDPR',
  'footer.legal.cookies': 'Cookies',
  'footer.legal.complaints': 'Жалобы',
  'footer.contact.title': 'Контакты',
  'footer.contact.subtitle': 'Свяжитесь с нами по вопросам и поддержке',
  'footer.language.label': 'Язык',
  'footer.copyright': '© 2025 Obod Soft LTD. Все права защищены.',

  'taskDetail.backToTasks': 'Обратно к задачам',
  'taskDetail.requirements': 'Требования:',
  'taskDetail.keyInformation': 'Ключевая информация',
  'taskDetail.client': 'Клиент',
  'taskDetail.loginForMore': 'Войдите для большего',
  'taskDetail.loginMessage':
    'Войдите в аккаунт чтобы увидеть полную информацию',
  'taskDetail.completedTasks': 'выполненных задач',
  'taskDetail.memberSince': 'Участник с',
  'taskDetail.similarTasks': 'Похожие задачи',
  'taskDetail.apply': 'Откликнуться на задачу',
  'taskDetail.askQuestion': 'Задать вопрос',
  'taskDetail.applicationsCount': 'человек',
  'taskDetail.timeAgo': 'назад',
  'taskDetail.today': 'Сегодня',
  'taskDetail.tomorrow': 'Завтра',
  'taskDetail.days': 'дней',
  'taskDetail.flexible': 'Гибкий',
  'taskDetail.negotiable': 'По договоренности',
  'taskDetail.urgency.same_day': 'Срочно - сегодня',
  'taskDetail.urgency.within_week': 'В течение недели',
  'taskDetail.urgency.flexible': 'Гибкий срок',
  'taskDetail.urgency.default': 'Не указано',

  'taskDetail.share': 'Поделиться',
  'taskDetail.activity': 'Активность по задаче',
  'taskDetail.applications': 'Заявки',
  'taskDetail.questions': 'Вопросы',
  'taskDetail.accept': 'Принять',
  'taskDetail.reject': 'Отклонить',
  'taskDetail.message': 'Сообщение',
  'taskDetail.reply': 'Ответить',
  'taskDetail.yourReply': 'Ваш ответ:',
  'taskDetail.price': 'Цена:',
  'taskDetail.tasks': 'задач',

  'auth.applyForTask': 'Откликнуться на задачу',
  'auth.askQuestion': 'Задать вопрос',
  'auth.createTask': 'Создать задачу',
  'auth.loginToContinue': 'Для продолжения войдите в аккаунт',
  'auth.applyDescription':
    'Отправьте заявку клиенту и получите возможность работать над этой задачей.',
  'auth.questionDescription':
    'Задайте вопрос клиенту перед тем как откликнуться на задачу.',
  'auth.createTaskDescription':
    'Создайте новую задачу и найдите проверенных специалистов для выполнения вашей работы.',
  'auth.loginDescription':
    'Войдите в аккаунт для управления задачами и связи со специалистами.',
  'auth.email': 'Email адрес',
  'auth.password': 'Пароль',
  'auth.rememberMe': 'Запомнить меня',
  'auth.forgotPassword': 'Забыли пароль?',
  'auth.login': 'Войти',
  'auth.or': 'или',
  'auth.noAccount': 'Нет аккаунта?',
  'auth.createAccount': 'Создать аккаунт',
  'auth.whyRegister': 'Зачем регистрироваться?',
  'auth.benefit1': '• Откликайтесь на задачи',
  'auth.benefit2': '• Общайтесь напрямую с клиентами',
  'auth.benefit3': '• Отслеживайте свою историю',
  'auth.benefit4': '• Получайте уведомления о новых задачах',
  'auth.continueWith': 'Продолжить с',

  'message.taskCreated': 'Задача успешно создана!',
  'message.profileUpdated': 'Профиль успешно обновлен!',
  'message.applicationSubmitted': 'Заявка успешно отправлена!',
  'error.generic': 'Что-то пошло не так. Пожалуйста, попробуйте еще раз.',
  'error.network': 'Ошибка сети. Пожалуйста, проверьте ваше соединение.',
  'error.unauthorized':
    'Вам нужно войти в систему, чтобы получить доступ к этой странице.',
};

export default ru;
