const ru = {
  welcome: 'Добро пожаловать',
  login: 'Войти',
  logout: 'Выйти',
  signup: 'Регистрация',
  search: 'Поиск',
  browse: 'Обзор',
  create: 'Создать',
  edit: 'Редактировать',
  delete: 'Удалить',
  cancel: 'Отмена',
  save: 'Сохранить',
  submit: 'Отправить',
  loading: 'Загрузка...',
  error: 'Ошибка',
  success: 'Успех',
  back: 'Назад',
  next: 'Далее',
  previous: 'Предыдущая',
  home: 'Главная',
  profile: 'Профиль',
  settings: 'Настройки',

  'nav.home': 'Главная',
  'nav.browseTasks': 'Задачи',
  'nav.createTask': 'Создать',
  'nav.profile': 'Профиль',
  'nav.howItWorks': 'Как работает',
  'nav.categories': 'Категории',
  'nav.forProfessionals': 'Профессионалы',
  'nav.myTasks': 'Мои задачи',
  'nav.help': 'Помощь',

  'landing.hero.title': 'Ваша местная платформа для услуг и возможностей',
  'landing.hero.subtitle':
    'Trudify связывает людей, которым нужна помощь, с квалифицированными специалистами, готовыми зарабатывать. Разместите задачу или найдите работу - надежно, проверено и просто.',
  'landing.hero.getStarted': 'Разместить задачу',
  'landing.hero.browseServices': 'Найти работу',

  'landing.trustIndicators.verified': 'Проверенные специалисты',
  'landing.trustIndicators.securePayments': 'Безопасные платежи',
  'landing.trustIndicators.support': 'Поддержка 24/7',

  'landing.stats.averageRating': 'средний рейтинг',
  'landing.stats.completedTasks': 'выполненных задач',
  'landing.categories.activeSpecialists': 'активных специалистов',

  'landing.categories.title': 'Популярные категории',
  'landing.categories.subtitle':
    'Найдите специалистов для любой задачи - от ремонта дома до персональной помощи',
  'landing.categories.viewAll': 'Посмотреть все категории',
  'landing.categories.home': 'Дом и сад',
  'landing.categories.home.description':
    'Электричество, сантехника, уборка, техобслуживание',
  'landing.categories.tech': 'Технологии',
  'landing.categories.tech.description':
    'IT поддержка, веб-дизайн, разработка ПО',
  'landing.categories.business': 'Бизнес-услуги',
  'landing.categories.business.description':
    'Административные задачи, мероприятия, консультации',
  'landing.categories.personal': 'Личные услуги',
  'landing.categories.personal.description':
    'Уход за питомцами, детьми, пожилыми',
  'landing.categories.education': 'Образование и обучение',
  'landing.categories.creative': 'Творческие услуги',

  'landing.featured.title': 'Рекомендуемые задачи',
  'landing.featured.badge': 'Последние возможности',
  'landing.featured.viewAll': 'Посмотреть все задачи',

  'landing.howItWorks.title': 'Как это работает',
  'landing.howItWorks.subtitle':
    'Простой процесс поиска и выполнения задач с проверенными специалистами',
  'landing.howItWorks.forCustomers': 'Для клиентов',
  'landing.howItWorks.forProfessionals': 'Для специалистов',
  'landing.howItWorks.step1.title': 'Опубликуйте вашу задачу',
  'landing.howItWorks.step1.description':
    'Опишите, что нужно сделать, и установите ваш бюджет',
  'landing.howItWorks.step2.title': 'Получите предложения',
  'landing.howItWorks.step2.description':
    'Получайте заявки от верифицированных специалистов',
  'landing.howItWorks.step3.title': 'Выберите и завершите',
  'landing.howItWorks.step3.description':
    'Выберите лучшего специалиста и выполните вашу задачу',

  'tasks.title': 'Обзор задач',
  'tasks.subtitle':
    'Найдите идеальную задачу, которая соответствует вашим навыкам и интересам',
  'tasks.searchPlaceholder':
    'Поиск задач по ключевым словам, категориям или местоположению...',
  'tasks.filters.title': 'Фильтры',
  'tasks.filters.category': 'Категория',
  'tasks.filters.allCategories': 'Все категории',
  'tasks.filters.location': 'Местоположение',
  'tasks.filters.budget': 'Бюджет',
  'tasks.filters.budgetMin': 'Мин. бюджет',
  'tasks.filters.budgetMax': 'Макс. бюджет',
  'tasks.filters.deadline': 'Срок',
  'tasks.filters.status': 'Статус',
  'tasks.filters.all': 'Все',
  'tasks.filters.open': 'Открытые',
  'tasks.filters.inProgress': 'В процессе',
  'tasks.filters.completed': 'Завершенные',
  'tasks.filters.activeFilters': 'Активные фильтры',
  'tasks.filters.clearAll': 'Очистить все',
  'tasks.results': 'результатов',
  'tasks.sort.newest': 'Сначала новые',
  'tasks.sort.oldest': 'Сначала старые',
  'tasks.sort.budgetHigh': 'Высокий бюджет',
  'tasks.sort.budgetLow': 'Низкий бюджет',
  'tasks.sort.deadline': 'По сроку',

  'professionals.hero.title': 'Найдите проверенных специалистов',
  'professionals.hero.subtitle':
    'Просматривайте верифицированных специалистов по категориям и найдите идеальное соответствие для ваших потребностей',
  'professionals.hero.badge': 'Сеть профессионалов',
  'professionals.searchPlaceholder':
    'Поиск категорий... (например, ремонт, уборка, уроки)',
  'professionals.allCategories': 'Все категории',
  'professionals.featuredTitle': 'Рекомендуемые специалисты',
  'professionals.viewProfile': 'Посмотреть профиль',
  'professionals.rating': 'Рейтинг',
  'professionals.completedJobs': 'Выполненные задания',
  'professionals.startingFrom': 'Начиная от',
  'professionals.noResults': 'Нет категорий, соответствующих вашему поиску',
  'professionals.categoryResults': 'категории найдены',
  'professionals.filterBy': 'Фильтровать по',
  'professionals.location': 'Местоположение',
  'professionals.experience': 'Опыт',
  'professionals.priceRange': 'Ценовой диапазон',
  'professionals.availability': 'Доступность',
  'professionals.findPerfect': 'Найдите идеального профессионала',
  'professionals.discoverTrusted':
    'Откройте для себя надежных профессионалов с проверенной репутацией и отличными отзывами',
  'professionals.popularCategories': 'Популярные категории',
  'professionals.refineSearch': 'Уточните результаты поиска',
  'professionals.professionalsAvailable': 'доступных профессионалов',
  'professionals.noMatchingResults':
    'Нет профессионалов, соответствующих вашим критериям. Попробуйте расширить поиск.',
  'professionals.mostActive': 'Наиболее активные',
  'professionals.gender.male': 'Мужчина',
  'professionals.gender.female': 'Женщина',
  'professionals.filters.category': 'Категория',
  'professionals.filters.location': 'Местоположение',
  'professionals.filters.minimumRating': 'Минимальный рейтинг',
  'professionals.filters.genderPreference': 'Предпочтение по полу',
  'professionals.filters.activityLevel': 'Уровень активности',
  'professionals.filters.all': 'Все',
  'professionals.filters.topPerformersOnly': 'Только топ исполнители',
  'professionals.filters.locationPlaceholder': 'София, Пловдив, Варна...',
  'professionals.filters.any': 'Любой',
  'professionals.filters.anyShort': 'Любой',
  'professionals.typing.plumber': 'сантехник в Софии',
  'professionals.typing.cleaner': 'специалист по уборке',
  'professionals.typing.electrician': 'сертифицированный электрик',
  'professionals.typing.tutor': 'учитель английского',
  'professionals.typing.photographer': 'свадебный фотограф',
  'professionals.typing.handyman': 'мастер на все руки',
  'professionals.recommendedTitle': 'РЕКОМЕНДУЕМЫЕ ПРОФЕССИОНАЛЫ',
  'professionals.filters.clear': 'Очистить',
  'professionals.filters.clearAll': 'Очистить все фильтры',
  'professionals.filters.fourPlusStars': '4+ звезд',
  'professionals.filters.fiveStarsOnly': 'Только 5 звезд',
  'professionals.filters.anyRating': 'По рейтингу',
  'professionals.filters.showProfessionalsWithAnyRating':
    'Показать профессионалов с любым рейтингом',
  'professionals.filters.locationPlaceholderDesktop': '📍 Местоположение',
  'professionals.sorting.featuredFirst': 'Топ выбор',
  'professionals.sorting.featuredFirstDesc': 'Лучшие профессионалы',
  'professionals.sorting.highestRating': 'По рейтингу',
  'professionals.sorting.highestRatingDesc': 'С лучшими отзывами',
  'professionals.sorting.mostExperience': 'По опыту',
  'professionals.sorting.mostExperienceDesc': 'Много заказов',
  'professionals.filters.sortResultsBy': 'Сортировка по',
  'professionals.filters.sortResultsTitle': 'Сортировка',
  'professionals.filters.sortResultsDescription':
    'Выберите, как упорядочить профессионалов',
  'professionals.filters.selectMinimumRating': 'Выберите минимальный рейтинг',
  'professionals.filters.showingVerifiedFirst':
    'Показать проверенных топ профессионалов первыми',
  'professionals.filters.proTip': 'Совет',
  'professionals.filters.proTipMessage':
    'Попробуйте "{{sortOption}}" для качественных профессионалов с подтвержденными квалификациями',
  'professionals.filters.sortingBy': 'Сортировка по {{option}}',
  'professionals.filters.sortingDescFeatured':
    'Показать проверенных топ профессионалов первыми',
  'professionals.filters.sortingDescRating':
    'Профессионалы с высшим рейтингом показываются первыми',
  'professionals.filters.sortingDescJobs':
    'Самые опытные профессионалы показываются первыми',
  'professionals.filters.activeFilters': 'Активные фильтры',
  'professionals.filters.filterApplied': '{{count}} фильтр применен',
  'professionals.filters.filtersApplied': '{{count}} фильтров применено',
  'professionals.filters.showProfessionalsWithRating':
    'Показать профессионалов с {{rating}}+ звездным рейтингом',
  'professionals.filters.showPerfectRating':
    'Показать только профессионалов с совершенным 5-звездным рейтингом',

  'browseTasks.hero.badge': 'Найдите идеальных специалистов',
  'browseTasks.hero.title1': 'Найдите идеальную',
  'browseTasks.hero.title2': 'задачу для вас',
  'browseTasks.hero.subtitle':
    'Просмотрите сотни возможностей от проверенных клиентов. Начните работать сегодня.',
  'browseTasks.search.placeholder':
    'Поиск задач по ключевым словам, категории или городу...',
  'browseTasks.search.popular': 'Популярные',
  'browseTasks.filters.title': 'Фильтрация и сортировка',
  'browseTasks.filters.advanced': 'Расширенные фильтры',
  'browseTasks.filters.quick': 'Быстрый фильтр',
  'browseTasks.filters.searchPlaceholder':
    'Поиск задач... (например, уборка, ремонт, доставка)',
  'browseTasks.filters.category': 'Категория',
  'browseTasks.filters.allCategories': 'Все категории',
  'browseTasks.filters.city': 'Город',
  'browseTasks.filters.allCities': 'Все города',
  'browseTasks.filters.cities.sofia': 'София',
  'browseTasks.filters.cities.plovdiv': 'Пловдив',
  'browseTasks.filters.cities.varna': 'Варна',
  'browseTasks.filters.cities.burgas': 'Бургас',
  'browseTasks.filters.budget': 'Бюджет',
  'browseTasks.filters.budgetMin': 'Мин',
  'browseTasks.filters.budgetMax': 'Макс',
  'browseTasks.filters.budgetUpTo': 'До 500 лв',
  'browseTasks.filters.sortBy': 'Сортировка',
  'browseTasks.filters.sort.newest': 'Новые',
  'browseTasks.filters.sort.oldest': 'Старые',
  'browseTasks.filters.sort.highBudget': 'Высокий бюджет',
  'browseTasks.filters.sort.lowBudget': 'Низкий бюджет',
  'browseTasks.results.shown': 'Показано {{count}} результатов',
  'browseTasks.results.featured': 'Показано {{count}} популярных задач',
  'browseTasks.results.loading': 'Загрузка...',
  'browseTasks.results.noTasks.title': 'Задачи не найдены',
  'browseTasks.results.noTasks.description':
    'Попробуйте изменить фильтры или искать по другим критериям.',
  'browseTasks.results.noTasks.clearFilters': 'Очистить фильтры',
  'browseTasks.results.suggestedTasks':
    'Популярные задачи, которые могут вам понравиться',
  'browseTasks.results.suggestedDescription':
    'Вот некоторые популярные задачи из нашего сообщества',
  'browseTasks.results.error.title': 'Ошибка при загрузке',
  'browseTasks.results.error.description':
    'Пожалуйста, попробуйте снова или обратитесь в службу поддержки.',
  'browseTasks.pagination.previous': 'Предыдущая',
  'browseTasks.pagination.next': 'Следующая',
  'browseTasks.search.tags.programming': 'Программирование',
  'browseTasks.search.tags.design': 'Дизайн',
  'browseTasks.search.tags.marketing': 'Маркетинг',
  'browseTasks.search.tags.translation': 'Переводы',
  'browseTasks.search.tags.photography': 'Фотография',
  'browseTasks.typing.plumber': 'сантехник в Софии',
  'browseTasks.typing.cleaner': 'уборка дома',
  'browseTasks.typing.electrician': 'ремонт электрики',
  'browseTasks.typing.tutor': 'учитель английского',
  'browseTasks.typing.moving': 'перевозка мебели',
  'browseTasks.typing.gardener': 'уход за садом',

  'task.budget': 'Бюджет',
  'task.location': 'Местоположение',
  'task.category': 'Категория',
  'task.applications': 'Заявки',
  'task.viewDetails': 'Посмотреть детали',
  'task.apply': 'Подать заявку',
  'task.created': 'Создана',
  'task.deadline': 'Срок',

  // Create Task Form
  'createTask.title': 'Создать новую задачу',
  'createTask.hero.subtitle': 'Опишите что вам нужно и позвольте профессионалам прийти к вам',
  'createTask.hero.freeToPost': 'Бесплатная публикация',
  'createTask.hero.noPayment': 'Без оплаты до начала работы',
  'createTask.hero.avgResponse': 'Среднее время ответа: 2 часа',
  'createTask.hero.verifiedPros': '1,500+ верифицированных профессионалов',
  'createTask.hero.help': 'Нужна помощь? Свяжитесь с нашей командой поддержки',

  // Category Section
  'createTask.category.title': 'Какая услуга вам нужна?',
  'createTask.category.subtitle': 'Выберите категорию, которая лучше всего описывает вашу задачу',
  'createTask.category.selectSubcategory': 'Выберите конкретную услугу',
  'createTask.category.backToMain': 'Назад к основным категориям',
  'createTask.category.selected': 'Выбранная услуга',
  'createTask.category.tryDifferent': 'Попробуйте другой поисковый запрос',

  // Details Section
  'createTask.details.title': 'Опишите вашу задачу',
  'createTask.details.subtitle': 'Чем больше деталей, тем лучше предложения вы получите',
  'createTask.details.titleLabel': 'Название задачи',
  'createTask.details.titlePlaceholder': 'напр. Нужен сантехник для устранения течи на кухне',
  'createTask.details.descriptionLabel': 'Описание',
  'createTask.details.descriptionPlaceholder': 'Опишите что нужно сделать, когда и какие особые требования у вас есть...',
  'createTask.details.requirementsLabel': 'Особые требования (по желанию)',
  'createTask.details.requirementsPlaceholder': 'Перечислите инструменты, навыки или опыт, которые необходимы...',

  // Location Section
  'createTask.location.title': 'Где находится задача?',
  'createTask.location.subtitle': 'Это помогает найти профессионалов в вашем районе',
  'createTask.location.cityLabel': 'Город',
  'createTask.location.cityPlaceholder': 'Выберите город',
  'createTask.location.neighborhoodLabel': 'Район (по желанию)',
  'createTask.location.neighborhoodPlaceholder': 'напр. Центр, Люлин, Студенческий городок',
  'createTask.location.addressLabel': 'Точный адрес (по желанию)',
  'createTask.location.addressPlaceholder': 'Будет передан выбранному профессионалу',
  'createTask.location.addressSecurity': 'Полный адрес скрыт до найма профессионала',

  // Budget Section
  'createTask.budget.title': 'Какой ваш бюджет?',
  'createTask.budget.help': 'Честные бюджеты получают в 3 раза больше откликов',
  'createTask.budget.typeFixed': 'Фиксированная цена',
  'createTask.budget.typeRange': 'Диапазон цен',
  'createTask.budget.fixedLabel': 'Ваш бюджет',
  'createTask.budget.minLabel': 'Минимум',
  'createTask.budget.maxLabel': 'Максимум',
  'createTask.budget.notSure': 'Не уверен в бюджете',

  // Timeline Section
  'createTask.timeline.title': 'Когда вам это нужно?',
  'createTask.timeline.subtitle': 'Сообщите профессионалам о вашем графике',
  'createTask.timeline.urgentTitle': 'Срочно - В тот же день',
  'createTask.timeline.urgentDesc': 'Мне нужно сегодня',
  'createTask.timeline.soonTitle': 'Скоро - В течение недели',
  'createTask.timeline.soonDesc': 'Мне нужно в течение ближайших 7 дней',
  'createTask.timeline.flexibleTitle': 'Гибкий',
  'createTask.timeline.flexibleDesc': 'У меня гибкий график',
  'createTask.timeline.deadlineLabel': 'Конкретный срок (по желанию)',
  'createTask.timeline.deadlineHelp': 'Оставьте пустым, если у вас нет конкретного срока',

  // Photos Section
  'createTask.photos.title': 'Добавьте фотографии (по желанию)',
  'createTask.photos.help': 'Фотографии помогают профессионалам лучше понять вашу задачу',
  'createTask.photos.dragDrop': 'Перетащите изображения сюда',
  'createTask.photos.orBrowse': 'или кликните для обзора',
  'createTask.photos.maxFiles': 'Максимум 5 изображений',
  'createTask.photos.maxSize': '5MB на изображение',
  'createTask.photos.formats': 'JPG, PNG, WebP',
  'createTask.photos.addMore': 'Добавить еще',
  'createTask.photos.uploading': 'Загрузка фотографий...',
  'createTask.photos.fileTooLarge': 'Файл {{fileName}} слишком большой. Максимальный размер 5MB',
  'createTask.photos.invalidType': 'Файл {{fileName}} не является поддерживаемым форматом изображения',
  'createTask.photos.uploadError': 'Не удалось загрузить фотографии. Пожалуйста, попробуйте еще раз.',

  // Review Section
  'createTask.review.title': 'Проверьте вашу задачу',
  'createTask.review.subtitle': 'Убедитесь, что всё выглядит правильно перед публикацией',
  'createTask.review.noTitle': 'Нет названия пока',
  'createTask.review.noDescription': 'Нет описания пока',
  'createTask.review.location': 'Местоположение',
  'createTask.review.noCity': 'Город не выбран',
  'createTask.review.budget': 'Бюджет',
  'createTask.review.timeline': 'График',
  'createTask.review.requirements': 'Требования',
  'createTask.review.photos': 'Фотографии',
  'createTask.review.submit': 'Опубликовать задачу',
  'createTask.review.fillRequired': 'Пожалуйста, заполните все обязательные поля для публикации',

  // Form Validation Errors
  'createTask.errors.categoryRequired': 'Пожалуйста, выберите категорию',
  'createTask.errors.titleTooShort': 'Название должно быть не менее 10 символов',
  'createTask.errors.titleTooLong': 'Название не может быть более 200 символов',
  'createTask.errors.descriptionTooShort': 'Описание должно быть не менее 50 символов',
  'createTask.errors.descriptionTooLong': 'Описание не может быть более 2000 символов',
  'createTask.errors.cityRequired': 'Пожалуйста, выберите город',
  'createTask.errors.budgetInvalid': 'Максимальный бюджет должен быть больше минимального',
  'createTask.errors.tooManyPhotos': 'Разрешено максимум 5 фотографий',

  'profile.title': 'Мой профиль',
  'profile.personalInfo': 'Личная информация',
  'profile.professionalInfo': 'Профессиональная информация',
  'profile.verification': 'Верификация',
  'profile.reviews': 'Отзывы',
  'profile.stats': 'Статистика',

  'profile.form.firstName': 'Имя',
  'profile.form.lastName': 'Фамилия',
  'profile.form.email': 'Email',
  'profile.form.phone': 'Телефон',
  'profile.form.location': 'Местоположение',
  'profile.form.bio': 'Биография',
  'profile.form.skills': 'Навыки',
  'profile.form.experience': 'Лет опыта',
  'profile.form.hourlyRate': 'Почасовая ставка (лв.)',
  'profile.form.vatNumber': 'НДС номер',
  'profile.form.businessName': 'Название компании',
  'profile.form.website': 'Веб-сайт',

  'profile.verification.identity': 'Личность верифицирована',
  'profile.verification.business': 'Бизнес верифицирован',
  'profile.verification.phone': 'Телефон верифицирован',
  'profile.verification.email': 'Email верифицирован',

  'language.en': 'English',
  'language.bg': 'Български',
  'language.ru': 'Русский',

  'landing.trustStats.securityUptime': 'Безопасность',
  'landing.trustStats.avgRating': 'Средний рейтинг',
  'landing.trustStats.encryption': 'Шифрование данных',
  'landing.trustStats.compliance': 'Правовое соответствие',

  'landing.trustIndicators.freeToUse': 'Бесплатно в использовании',
  'landing.trustIndicators.communityReviews': 'Отзывы сообщества',
  'landing.trustIndicators.verifiedDescription':
    'Все специалисты тщательно проверены',
  'landing.trustIndicators.ratingSystem': '5-звездная система рейтинга',
  'landing.trustIndicators.ratingSystemDescription':
    'Качество гарантировано через отзывы сообщества',
  'landing.trustIndicators.dataProtection': 'Защита данных',
  'landing.trustIndicators.dataProtectionDescription':
    'Ваша личная информация в безопасности',
  'landing.trustIndicators.contracts': 'Правовая защита',
  'landing.trustIndicators.contractsDescription':
    'Вся работа защищена четкими соглашениями',

  'landing.featured.subtitle':
    'Последние задачи, опубликованные нашим сообществом',
  'landing.featured.professionalDesc': 'Найдите свою следующую возможность',
  'landing.featured.customerDesc': 'Посмотрите, что публикуют другие',

  'landing.howItWorks.customers.step1.title': 'Создайте вашу задачу',
  'landing.howItWorks.customers.step1.description':
    'Опишите, что нужно сделать, и установите ваш бюджет',
  'landing.howItWorks.customers.step2.title': 'Получите предложения',
  'landing.howItWorks.customers.step2.description':
    'Получайте заявки от верифицированных специалистов',
  'landing.howItWorks.customers.step3.title': 'Выберите и завершите',
  'landing.howItWorks.customers.step3.description':
    'Выберите лучшего специалиста и выполните вашу задачу',

  'landing.howItWorks.professionals.step1.title': 'Просматривайте задачи',
  'landing.howItWorks.professionals.step1.description':
    'Найдите задачи, соответствующие вашим навыкам и доступности',
  'landing.howItWorks.professionals.step2.title': 'Отправьте предложение',
  'landing.howItWorks.professionals.step2.description':
    'Отправьте лучшее предложение и покажите свою экспертизу',
  'landing.howItWorks.professionals.step3.title': 'Выполните работу',
  'landing.howItWorks.professionals.step3.description':
    'Предоставьте качественную услугу и создайте репутацию',

  'landing.testimonials.title': 'Что говорят наши пользователи',
  'landing.testimonials.subtitle': 'Реальные отзывы нашего сообщества',
  'landing.testimonials.customers.title': 'От клиентов',
  'landing.testimonials.customers.customer1.name': 'Мария Иванова',
  'landing.testimonials.customers.customer1.location': 'София, Болгария',
  'landing.testimonials.customers.customer1.quote':
    'Нашла отличного сантехника за минуты. Профессиональная услуга и справедливые цены!',
  'landing.testimonials.customers.customer2.name': 'Георги Петров',
  'landing.testimonials.customers.customer2.location': 'Пловдив, Болгария',
  'landing.testimonials.customers.customer2.quote':
    'Услуга уборки была исключительной. Определенно буду использовать Trudify снова.',
  'landing.testimonials.customers.customer3.name': 'Елена Димитрова',
  'landing.testimonials.customers.customer3.location': 'Варна, Болгария',
  'landing.testimonials.customers.customer3.quote':
    'Быстро, надежно и доступно. Именно то, что я искала.',

  'landing.testimonials.professionals.title': 'От специалистов',
  'landing.testimonials.professionals.pro1.name': 'Иван Стоев',
  'landing.testimonials.professionals.pro1.profession': 'Электрик',
  'landing.testimonials.professionals.pro1.quote':
    'Trudify помог мне развить бизнес с постоянным потоком качественных клиентов.',
  'landing.testimonials.professionals.pro2.name': 'Анна Николова',
  'landing.testimonials.professionals.pro2.profession': 'Уборщица',
  'landing.testimonials.professionals.pro2.quote':
    'Простая в использовании платформа. Нравится, как я могу управлять расписанием и платежами.',
  'landing.testimonials.professionals.pro3.name': 'Димитар Георгиев',
  'landing.testimonials.professionals.pro3.profession': 'Мастер на все руки',
  'landing.testimonials.professionals.pro3.quote':
    'Профессиональная платформа, которая связывает меня с клиентами, ценящими качественную работу.',

  'landing.trustSection.title': 'Основана на доверии',
  'landing.trustSection.subtitle':
    'Ваша безопасность и удовлетворенность - наши главные приоритеты',

  'landing.cta.title': 'Готовы начать?',
  'landing.cta.subtitle':
    'Присоединяйтесь к тысячам довольных пользователей сегодня',
  'landing.cta.postTask': 'Создать задачу',
  'landing.cta.joinProfessionals': 'Присоединиться как специалист',
  'landing.cta.freeToJoin': 'Бесплатное присоединение, без скрытых комиссий',
  'landing.cta.stats.completedTasks': 'Выполненных задач',
  'landing.cta.stats.activeSpecialists': 'Активных специалистов',
  'landing.cta.stats.averageRating': 'Средний рейтинг',
  'landing.cta.stats.contractTemplates': 'Правовых шаблонов',

  'taskCard.apply': 'Откликнуться',
  'taskCard.anonymous': 'Анонимный',
  'taskCard.budget.from': 'от',
  'taskCard.budget.to': 'до',
  'taskCard.budget.negotiable': 'Договорная',
  'taskCard.deadline.flexible': 'Гибкий',
  'taskCard.deadline.today': 'Сегодня',
  'taskCard.deadline.tomorrow': 'Завтра',
  'taskCard.deadline.days': 'дней',
  'taskCard.category.home_repair': 'Домашние ремонты',
  'taskCard.category.delivery_transport': 'Доставка и транспорт',
  'taskCard.category.personal_care': 'Личный уход',
  'taskCard.category.personal_assistant': 'Личный помощник',
  'taskCard.category.learning_fitness': 'Обучение и фитнес',
  'taskCard.category.other': 'Другое',

  // Category Groups
  'categoryGroups.homeRepair': 'Дом и ремонт',
  'categoryGroups.cleaning': 'Уборка',
  'categoryGroups.deliveryTransport': 'Доставка и транспорт',
  'categoryGroups.personalCare': 'Личный уход',
  'categoryGroups.professional': 'Профессиональные услуги',
  'categoryGroups.creative': 'Творческие услуги',
  'categoryGroups.events': 'Мероприятия',
  'categoryGroups.beauty': 'Красота',
  'categoryGroups.other': 'Другое',

  // Categories - Comprehensive list (legacy keys - kept for backward compatibility)
  'categories.plumbing': 'Сантехника',
  'categories.electrical': 'Электричество',
  'categories.hvac': 'Кондиционеры и отопление',
  'categories.carpentry': 'Столярные работы',
  'categories.painting': 'Покраска',
  'categories.flooring': 'Напольные покрытия',
  'categories.roofing': 'Кровельные работы',
  'categories.homeRenovation': 'Ремонт дома',
  'categories.applianceRepair': 'Ремонт бытовой техники',
  'categories.handyman': 'Мастер на все руки',
  'categories.houseCleaning': 'Уборка дома',
  'categories.deepCleaning': 'Генеральная уборка',
  'categories.carpetCleaning': 'Чистка ковров',
  'categories.windowCleaning': 'Мытье окон',
  'categories.gardenMaintenance': 'Уход за садом',
  'categories.landscaping': 'Ландшафтный дизайн',
  'categories.delivery': 'Доставка',
  'categories.moving': 'Переезд',
  'categories.taxiDriver': 'Такси',
  'categories.courier': 'Курьер',
  'categories.babysitting': 'Няня',
  'categories.elderlyCare': 'Уход за пожилыми',
  'categories.petSitting': 'Присмотр за животными',
  'categories.personalTrainer': 'Персональный тренер',
  'categories.massageTherapy': 'Массаж',
  'categories.tutoring': 'Репетиторство',
  'categories.translation': 'Переводы',
  'categories.accounting': 'Бухгалтерия',
  'categories.legalServices': 'Юридические услуги',
  'categories.consulting': 'Консалтинг',
  'categories.graphicDesign': 'Графический дизайн',
  'categories.webDevelopment': 'Веб-разработка',
  'categories.photography': 'Фотография',
  'categories.videography': 'Видеосъемка',
  'categories.writing': 'Копирайтинг',
  'categories.musicLessons': 'Музыкальные уроки',
  'categories.eventPlanning': 'Организация мероприятий',
  'categories.catering': 'Кейтеринг',
  'categories.djServices': 'DJ услуги',
  'categories.hairdressing': 'Парикмахерские услуги',
  'categories.makeupArtist': 'Визаж',
  'categories.nailServices': 'Маникюр и педикюр',
  'categories.other': 'Другое',

  // Categories Page
  'categories.pageTitle': 'Обзор всех категорий',
  'categories.pageSubtitle': 'Найдите идеального профессионала для любой задачи',
  'categories.searchPlaceholder': 'Поиск услуг... (напр. сантехник, уборка, уроки)',
  'categories.ctaTitle': 'Не нашли то, что ищете?',
  'categories.ctaSubtitle': 'Опубликуйте вашу задачу и позвольте профессионалам найти вас',

  // Main Categories (centralized categories feature)
  'categories.main.homeServices.title': 'Домашние услуги',
  'categories.main.homeServices.description': 'Сантехника, электричество, мастер на все руки',
  'categories.main.renovation.title': 'Ремонт и строительство',
  'categories.main.renovation.description': 'Ремонты, покраска, облицовка',
  'categories.main.moving.title': 'Переезд и транспорт',
  'categories.main.moving.description': 'Переезд, грузоперевозки, грузчики',
  'categories.main.cleaning.title': 'Услуги по уборке',
  'categories.main.cleaning.description': 'Уборка дома, генеральная уборка, уборка офиса',
  'categories.main.personal.title': 'Личные услуги',
  'categories.main.personal.description': 'Няня, репетиторство, присмотр за животными',
  'categories.main.tech.title': 'Технологии и цифровые',
  'categories.main.tech.description': 'Ремонт компьютеров, IT поддержка, веб-разработка',

  // Main Categories - NEW (26 total)
  'categories.main.applianceRepair.title': 'Ремонт техники',
  'categories.main.applianceRepair.description': 'Ремонт бытовой техники, компьютеров и электроники',
  'categories.main.courierServices.title': 'Курьерские услуги',
  'categories.main.courierServices.description': 'Доставка еды, лекарств и посылок',
  'categories.main.onlineWork.title': 'Работа в интернете',
  'categories.main.onlineWork.description': 'Ввод данных, исследования, транскрипция',
  'categories.main.handyman.title': 'Домашний мастер',
  'categories.main.handyman.description': 'Сантехник, электрик, замочник',
  'categories.main.finishingWork.title': 'Отделочные работы',
  'categories.main.finishingWork.description': 'Ремонт квартир, плитка, штукатурка',
  'categories.main.constructionWork.title': 'Строительные работы',
  'categories.main.constructionWork.description': 'Кладка, сварка, столярные работы',
  'categories.main.furnitureWork.title': 'Мебельные работы',
  'categories.main.furnitureWork.description': 'Производство, ремонт и реставрация мебели',
  'categories.main.cleaningServices.title': 'Клининговые услуги',
  'categories.main.cleaningServices.description': 'Уборка дома, офиса и после ремонта',
  'categories.main.logistics.title': 'Логистика',
  'categories.main.logistics.description': 'Грузоперевозки, переезд, грузчики',
  'categories.main.householdServices.title': 'Бытовые услуги',
  'categories.main.householdServices.description': 'Няни, садовники, домработницы',
  'categories.main.petServices.title': 'Услуги для животных',
  'categories.main.petServices.description': 'Уход за собаками, кошками и другими питомцами',
  'categories.main.beautyHealth.title': 'Красота и здоровье',
  'categories.main.beautyHealth.description': 'Массаж, маникюр, косметология',
  'categories.main.autoRepair.title': 'Ремонт авто',
  'categories.main.autoRepair.description': 'Диагностика, обслуживание и ремонт автомобилей',
  'categories.main.digitalMarketing.title': 'Цифровой маркетинг',
  'categories.main.digitalMarketing.description': 'SEO, контекстная реклама, SMM',
  'categories.main.aiServices.title': 'AI услуги',
  'categories.main.aiServices.description': 'AI разработка, консультации и анализ данных',
  'categories.main.onlineAdvertising.title': 'Интернет-реклама',
  'categories.main.onlineAdvertising.description': 'Размещение рекламы в интернете',
  'categories.main.advertisingDistribution.title': 'Распространение рекламы',
  'categories.main.advertisingDistribution.description': 'Раздача листовок, расклейка объявлений',
  'categories.main.webDevelopment.title': 'Веб-разработка',
  'categories.main.webDevelopment.description': 'Создание сайтов и приложений',
  'categories.main.design.title': 'Дизайн',
  'categories.main.design.description': 'Дизайн логотипов, интерьеров, печатной продукции',
  'categories.main.photoVideo.title': 'Фото и видео услуги',
  'categories.main.photoVideo.description': 'Фотография, видеосъемка, монтаж',
  'categories.main.tutoring.title': 'Услуги репетиторов',
  'categories.main.tutoring.description': 'Уроки по предметам, языкам и музыке',
  'categories.main.businessServices.title': 'Деловые услуги',
  'categories.main.businessServices.description': 'Бухгалтерия, юридические услуги, недвижимость',
  'categories.main.translationServices.title': 'Бюро переводов',
  'categories.main.translationServices.description': 'Письменный и устный перевод',
  'categories.main.trainerServices.title': 'Услуги тренеров',
  'categories.main.trainerServices.description': 'Йога, фитнес, спортивные тренировки',
  'categories.main.eventPlanning.title': 'Организация праздников',
  'categories.main.eventPlanning.description': 'Ведущие, аниматоры, кейтеринг',
  'categories.main.volunteerHelp.title': 'Волонтерская помощь',
  'categories.main.volunteerHelp.description': 'Помощь пожилым людям и транспорт',

  // Subcategories - NEW (135 total)
  // Handyman
  'categories.sub.plumber': 'Сантехник',
  'categories.sub.electrician': 'Электрик',
  'categories.sub.handymanService': 'Мастер на все руки',
  'categories.sub.carpenter': 'Плотник',
  'categories.sub.locksmith': 'Замочник',

  // Appliance Repair
  'categories.sub.largeApplianceRepair': 'Ремонт крупной техники',
  'categories.sub.smallApplianceRepair': 'Ремонт мелкой техники',
  'categories.sub.computerHelp': 'Компьютерная помощь',
  'categories.sub.digitalTechRepair': 'Ремонт цифровой техники',
  'categories.sub.phoneRepair': 'Ремонт телефонов',

  // Finishing Work
  'categories.sub.apartmentRenovation': 'Ремонт квартиры',
  'categories.sub.tileInstallation': 'Укладка плитки',
  'categories.sub.plastering': 'Штукатурка',
  'categories.sub.insulation': 'Утепление',
  'categories.sub.heatingInstallation': 'Монтаж отопления',

  // Construction Work
  'categories.sub.generalLabor': 'Общестроительные работы',
  'categories.sub.welding': 'Сварочные работы',
  'categories.sub.turning': 'Токарные работы',
  'categories.sub.carpentry': 'Столярные работы',
  'categories.sub.bricklaying': 'Кладка кирпича',

  // Furniture Work
  'categories.sub.furnitureManufacturing': 'Производство мебели',
  'categories.sub.furnitureRepair': 'Ремонт мебели',
  'categories.sub.furnitureAssembly': 'Сборка мебели',
  'categories.sub.furnitureRestoration': 'Реставрация мебели',
  'categories.sub.furnitureUpholstery': 'Обивка мебели',

  // Cleaning Services
  'categories.sub.apartmentCleaning': 'Уборка квартиры',
  'categories.sub.deepCleaning': 'Генеральная уборка',
  'categories.sub.postRenovationCleaning': 'Уборка после ремонта',
  'categories.sub.dryCleaning': 'Химчистка',
  'categories.sub.houseCleaning': 'Уборка дома',

  // Logistics
  'categories.sub.cargoTransport': 'Грузоперевозки',
  'categories.sub.loaders': 'Грузчики',
  'categories.sub.constructionWasteRemoval': 'Вывоз строительного мусора',
  'categories.sub.furnitureApplianceMoving': 'Перевозка мебели и техники',
  'categories.sub.officeRelocation': 'Переезд офиса',

  // Household Services
  'categories.sub.gardening': 'Садоводство',
  'categories.sub.babysitting': 'Няня',
  'categories.sub.caregiver': 'Сиделка',
  'categories.sub.housekeeper': 'Домработница',
  'categories.sub.sewing': 'Швейные услуги',

  // Auto Repair
  'categories.sub.roadsideAssistance': 'Помощь на дороге',
  'categories.sub.maintenanceDiagnostics': 'ТО и диагностика',
  'categories.sub.autoElectrical': 'Автоэлектрика',
  'categories.sub.bodyWork': 'Кузовные работы',
  'categories.sub.engineRepair': 'Ремонт двигателя',

  // Courier Services
  'categories.sub.courierDelivery': 'Курьерская доставка',
  'categories.sub.groceryDelivery': 'Доставка продуктов',
  'categories.sub.foodDelivery': 'Доставка еды',
  'categories.sub.medicineDelivery': 'Доставка лекарств',
  'categories.sub.courierByCar': 'Курьер на авто',

  // Digital Marketing
  'categories.sub.contextualAdvertising': 'Контекстная реклама',
  'categories.sub.seoOptimization': 'SEO оптимизация',
  'categories.sub.copywriting': 'Копирайтинг',
  'categories.sub.socialMediaMarketing': 'SMM',
  'categories.sub.emailMarketing': 'Email-маркетинг',

  // AI Services
  'categories.sub.aiContentCreation': 'AI создание контента',
  'categories.sub.aiConsulting': 'AI консультации',
  'categories.sub.aiDevelopment': 'AI разработка',
  'categories.sub.aiDataAnalytics': 'AI анализ данных',

  // Online Advertising
  'categories.sub.onlineAdPlacement': 'Размещение интернет-рекламы',

  // Advertising Distribution
  'categories.sub.flyerDistribution': 'Раздача листовок',
  'categories.sub.posterHanging': 'Расклейка объявлений',
  'categories.sub.mailboxAdvertising': 'Реклама по почтовым ящикам',
  'categories.sub.sandwichBoardAdvertising': 'Реклама на сэндвич-панелях',

  // Design
  'categories.sub.logoDesign': 'Дизайн логотипа',
  'categories.sub.interiorDesign': 'Дизайн интерьера',
  'categories.sub.webAppDesign': 'Дизайн веб и приложений',
  'categories.sub.printDesign': 'Дизайн для печати',
  'categories.sub.printingServices': 'Полиграфические услуги',

  // Tutoring
  'categories.sub.subjectTutors': 'Репетиторы по предметам',
  'categories.sub.languageTutors': 'Преподаватели языков',
  'categories.sub.academicWriting': 'Академическое письмо',
  'categories.sub.musicTeachers': 'Учителя музыки',
  'categories.sub.drivingInstructors': 'Инструкторы по вождению',

  // Web Development
  'categories.sub.websiteCreation': 'Создание сайта',
  'categories.sub.websiteImprovements': 'Доработка сайта',
  'categories.sub.landingPage': 'Лендинг',
  'categories.sub.websiteLayout': 'Верстка сайта',
  'categories.sub.qaTesting': 'QA тестирование',

  // Online Work
  'categories.sub.dataResearch': 'Поиск данных',
  'categories.sub.contentFilling': 'Наполнение контентом',
  'categories.sub.typing': 'Набор текста',
  'categories.sub.dataEntry': 'Ввод данных',
  'categories.sub.transcription': 'Транскрибация',

  // Photo/Video Services
  'categories.sub.photographer': 'Фотограф',
  'categories.sub.videographer': 'Видеограф',
  'categories.sub.photoEditing': 'Обработка фото',
  'categories.sub.videoEditing': 'Видеомонтаж',
  'categories.sub.videoDigitization': 'Оцифровка видео',

  // Business Services
  'categories.sub.accounting': 'Бухгалтерия',
  'categories.sub.legalServices': 'Юридические услуги',
  'categories.sub.realEstate': 'Недвижимость',
  'categories.sub.callCenter': 'Колл-центр',
  'categories.sub.financialServices': 'Финансовые услуги',

  // Pet Services
  'categories.sub.catCare': 'Уход за кошками',
  'categories.sub.dogCare': 'Уход за собаками',
  'categories.sub.petHotel': 'Зоогостиница',
  'categories.sub.petTransportation': 'Транспортировка животных',
  'categories.sub.fishCare': 'Уход за рыбами',

  // Beauty & Health
  'categories.sub.massage': 'Массаж',
  'categories.sub.nailCare': 'Уход за ногтями',
  'categories.sub.cosmetology': 'Косметология',
  'categories.sub.lashCare': 'Уход за ресницами',
  'categories.sub.browCare': 'Уход за бровями',

  // Event Planning
  'categories.sub.eventHost': 'Ведущий мероприятий',
  'categories.sub.musicEntertainment': 'Музыкальное сопровождение',
  'categories.sub.animators': 'Аниматоры',
  'categories.sub.catering': 'Кейтеринг',
  'categories.sub.bakingDesserts': 'Выпечка и десерты',

  // Translation Services
  'categories.sub.writtenTranslation': 'Письменный перевод',
  'categories.sub.translationEditing': 'Редактура перевода',
  'categories.sub.documentTranslation': 'Перевод документов',
  'categories.sub.oralTranslation': 'Устный перевод',
  'categories.sub.technicalTranslation': 'Технический перевод',

  // Trainer Services
  'categories.sub.yoga': 'Йога',
  'categories.sub.groupFitness': 'Групповой фитнес',
  'categories.sub.teamSports': 'Командные виды спорта',
  'categories.sub.waterSports': 'Водные виды спорта',
  'categories.sub.martialArts': 'Боевые искусства',

  // Volunteer Help
  'categories.sub.elderlyAssistance': 'Помощь пожилым людям',
  'categories.sub.volunteerTransportation': 'Волонтерская перевозка',
  'categories.sub.fuelDelivery': 'Доставка топлива',
  'categories.sub.housingAssistance': 'Помощь с жильем',
  'categories.sub.volunteerFoodDelivery': 'Волонтерская доставка еды',

  'professionalDetail.about': 'О специалисте',
  'professionalDetail.reviews': 'отзывов',
  'professionalDetail.online': 'Онлайн',
  'professionalDetail.offline': 'Недавно был в сети',
  'professionalDetail.verified.phone': 'Телефон',
  'professionalDetail.verified.id': 'Документ',
  'professionalDetail.stats.completedTasks': 'Задач',
  'professionalDetail.stats.yearsExperience': 'Лет',
  'professionalDetail.stats.responseTime': 'Ответ',
  'professionalDetail.actions.proposeTask': 'Предложить задачу',
  'professionalDetail.actions.contact': 'Связаться',
  'professionalDetail.actions.askQuestion': 'Задать вопрос',
  'professionalDetail.actions.saveToFavorites': 'В избранное',
  'professionalDetail.contactHours': 'Доступен',
  'professionalDetail.services.title': 'Услуги и цены',
  'professionalDetail.services.pricingNote.title': 'Информация о ценах',
  'professionalDetail.services.pricingNote.description':
    'Окончательные цены согласовываются индивидуально в зависимости от сложности и требований задачи.',
  'professionalDetail.portfolio.title': 'Мои примеры',
  'professionalDetail.portfolio.noWork': 'Пока нет примеров',
  'professionalDetail.portfolio.before': 'До',
  'professionalDetail.portfolio.after': 'После',
  'professionalDetail.portfolio.viewMore': 'Посмотреть все примеры',
  'professionalDetail.portfolio.showcase': 'Профессиональные примеры работ',
  'professionalDetail.completedTasks.title': 'Выполненные задачи',
  'professionalDetail.completedTasks.noTasks': 'Пока нет выполненных задач',
  'professionalDetail.completedTasks.viewTask': 'Посмотреть задачу',
  'professionalDetail.completedTasks.completedOn': 'Выполнено',
  'professionalDetail.reviews.title': 'Отзывы и рейтинги',
  'professionalDetail.reviews.count': 'отзывов',
  'professionalDetail.reviews.recentRating': 'Недавний рейтинг',
  'professionalDetail.reviews.excellent': 'Отлично',
  'professionalDetail.reviews.noReviews': 'Пока нет отзывов',
  'professionalDetail.reviews.beFirst': 'Станьте первым, кто оставит отзыв',
  'professionalDetail.reviews.showMore': 'Показать все отзывы',
  'professionalDetail.reviews.allReviews': 'Все отзывы',
  'professionalDetail.reviews.avgRating': 'Средний рейтинг',
  'professionalDetail.reviews.more': 'ещё',
  'professionalDetail.completedTasks.stats.tasksCompleted': 'Выполненных задач',
  'professionalDetail.completedTasks.stats.avgRating': 'Средний рейтинг',
  'professionalDetail.completedTasks.stats.fiveStarTasks':
    '5-звёздочные задачи',
  'professionalDetail.verified': 'Подтверждён',
  'common.anonymous': 'Анонимный пользователь',

  'footer.company.description':
    'Связываем людей с квалифицированными специалистами для всех видов услуг в Болгарии.',
  'footer.quickLinks.title': 'Быстрые ссылки',
  'footer.quickLinks.howItWorks': 'Как работает',
  'footer.quickLinks.categories': 'Категории',
  'footer.quickLinks.forProfessionals': 'Для специалистов',
  'footer.quickLinks.security': 'Безопасность',
  'footer.quickLinks.help': 'Помощь',
  'footer.legal.title': 'Правовые',
  'footer.legal.terms': 'Условия обслуживания',
  'footer.legal.privacy': 'Политика конфиденциальности',
  'footer.legal.gdpr': 'GDPR',
  'footer.legal.cookies': 'Cookies',
  'footer.legal.complaints': 'Жалобы',
  'footer.contact.title': 'Контакты',
  'footer.contact.subtitle': 'Свяжитесь с нами по вопросам и поддержке',
  'footer.language.label': 'Язык',
  'footer.copyright': '© 2025 Obod Soft LTD. Все права защищены.',

  'taskDetail.backToTasks': 'Обратно к задачам',
  'taskDetail.requirements': 'Требования:',
  'taskDetail.keyInformation': 'Ключевая информация',
  'taskDetail.client': 'Клиент',
  'taskDetail.loginForMore': 'Войдите для большего',
  'taskDetail.loginMessage':
    'Войдите в аккаунт чтобы увидеть полную информацию',
  'taskDetail.completedTasks': 'выполненных задач',
  'taskDetail.memberSince': 'Участник с',
  'taskDetail.similarTasks': 'Похожие задачи',
  'taskDetail.apply': 'Откликнуться на задачу',
  'taskDetail.askQuestion': 'Задать вопрос',
  'taskDetail.applicationsCount': 'человек',
  'taskDetail.timeAgo': 'назад',
  'taskDetail.today': 'Сегодня',
  'taskDetail.tomorrow': 'Завтра',
  'taskDetail.days': 'дней',
  'taskDetail.flexible': 'Гибкий',
  'taskDetail.negotiable': 'По договоренности',
  'taskDetail.urgency.same_day': 'Срочно - сегодня',
  'taskDetail.urgency.within_week': 'В течение недели',
  'taskDetail.urgency.flexible': 'Гибкий срок',
  'taskDetail.urgency.default': 'Не указано',
  'taskDetail.status': 'Статус',
  'taskDetail.statusTypes.vacant': 'Свободная',
  'taskDetail.statusTypes.applied': 'Откликнулись',
  'taskDetail.statusTypes.done': 'Выполнена',
  'taskDetail.statusTypes.archived': 'Архивирована',
  'taskDetail.appliedTooltip': 'Вы откликнулись на эту задачу. Клиент может принять или отклонить вашу заявку.',

  'taskDetail.share': 'Поделиться',
  'taskDetail.activity': 'Активность по задаче',
  'taskDetail.applications': 'Заявки',
  'taskDetail.questions': 'Вопросы',
  'taskDetail.accept': 'Принять',
  'taskDetail.reject': 'Отклонить',
  'taskDetail.message': 'Сообщение',
  'taskDetail.reply': 'Ответить',
  'taskDetail.yourReply': 'Ваш ответ:',
  'taskDetail.price': 'Цена:',
  'taskDetail.tasks': 'задач',

  'auth.applyForTask': 'Откликнуться на задачу',
  'auth.askQuestion': 'Задать вопрос',
  'auth.createTask': 'Создать задачу',
  'auth.loginToContinue': 'Для продолжения войдите в аккаунт',
  'auth.applyDescription':
    'Отправьте заявку клиенту и получите возможность работать над этой задачей.',
  'auth.questionDescription':
    'Задайте вопрос клиенту перед тем как откликнуться на задачу.',
  'auth.createTaskDescription':
    'Создайте новую задачу и найдите проверенных специалистов для выполнения вашей работы.',
  'auth.loginDescription':
    'Войдите в аккаунт для управления задачами и связи со специалистами.',
  'auth.email': 'Email адрес',
  'auth.password': 'Пароль',
  'auth.rememberMe': 'Запомнить меня',
  'auth.forgotPassword': 'Забыли пароль?',
  'auth.loginOrRegister': 'Войти / Регистрация',
  'auth.loginOrRegisterToContinue': 'Для продолжения войдите или зарегистрируйтесь',
  'auth.loginOrRegisterDescription': 'Введите свои данные для доступа к аккаунту или создайте новый.',
  'auth.continue': 'Продолжить',
  'auth.login': 'Войти',
  'auth.or': 'или',
  'auth.noAccount': 'Нет аккаунта?',
  'auth.createAccount': 'Создать аккаунт',
  'auth.whyRegister': 'Зачем регистрироваться?',
  'auth.benefit1': '• Откликайтесь на задачи',
  'auth.benefit2': '• Общайтесь напрямую с клиентами',
  'auth.benefit3': '• Отслеживайте свою историю',
  'auth.benefit4': '• Получайте уведомления о новых задачах',
  'auth.continueWith': 'Продолжить с',

  // Application Dialog
  'application.title': 'Откликнуться на задачу',
  'application.proposedPrice': 'Ваша цена',
  'application.pricePlaceholder': 'Введите вашу цену в левах',
  'application.timeline': 'Когда можете начать?',
  'application.timelineToday': 'Сегодня',
  'application.timeline3days': 'В течение 3 дней',
  'application.timelineWeek': 'В течение недели',
  'application.timelineFlexible': 'Гибкий',
  'application.message': 'Почему вы лучше всего подходите?',
  'application.messagePlaceholder': 'Поделитесь своим опытом и почему вы идеально подходите для этой задачи...',
  'application.messageInfo': 'Сосредоточьтесь на навыках и опыте. Контактной информацией можно обменяться после принятия заявки.',
  'application.characterCount': '{{current}}/{{max}} символов',
  'application.submit': 'Отправить заявку',
  'application.submitting': 'Отправка...',
  'application.cancel': 'Отмена',
  'application.success': 'Заявка отправлена!',
  'application.successMessage': 'Владелец задачи рассмотрит вашу заявку и скоро ответит.',
  'application.viewApplication': 'Посмотреть мою заявку',
  'application.browseOther': 'Просмотреть другие задачи',
  'application.errors.priceRequired': 'Цена обязательна',
  'application.errors.priceMin': 'Цена должна быть больше 0',
  'application.errors.timelineRequired': 'Сроки обязательны',
  'application.errors.messageRequired': 'Сообщение обязательно',
  'application.errors.messageMin': 'Сообщение должно содержать не менее 30 символов',
  'application.errors.messageMax': 'Сообщение не может превышать 500 символов',
  'application.errors.noPhoneNumbers': 'Номера телефонов не разрешены в заявках. Вы можете обменяться контактной информацией после принятия заявки.',
  'application.errors.noUrls': 'URL-адреса и ссылки не разрешены в заявках. Вы можете поделиться портфолио после принятия заявки.',
  'application.errors.noEmails': 'Адреса электронной почты не разрешены в заявках. Вы можете обменяться контактной информацией после принятия заявки.',
  'application.alreadyApplied': 'Вы уже откликнулись на эту задачу',
  'application.cannotApplyOwnTask': 'Вы не можете откликнуться на свою собственную задачу',

  'message.taskCreated': 'Задача успешно создана!',
  'message.profileUpdated': 'Профиль успешно обновлен!',
  'message.applicationSubmitted': 'Заявка успешно отправлена!',
  'error.generic': 'Что-то пошло не так. Пожалуйста, попробуйте еще раз.',
  'error.network': 'Ошибка сети. Пожалуйста, проверьте ваше соединение.',
  'error.unauthorized':
    'Вам нужно войти в систему, чтобы получить доступ к этой странице.',

  // Profile Page
  'profile.completion': 'Заполнение профиля',
  'profile.settings': 'Настройки',
  'profile.tabs.customer': 'Клиент',
  'profile.tabs.professional': 'Специалист',
  'profile.email': 'Email',
  'profile.phone': 'Телефон',
  'profile.location': 'Местоположение',
  'profile.memberSince': 'Участник с',
  'profile.editPersonalInfo': 'Редактировать личную информацию',
  'profile.statistics': 'Статистика',
  'profile.verified': 'Верифицирован',
  'profile.completed': 'Завершено',
  'profile.active': 'Активно',

  // Avatar Upload
  'profile.avatar.changeAvatar': 'Изменить аватар',
  'profile.avatar.selectImage': 'Выбрать изображение',
  'profile.avatar.remove': 'Удалить',
  'profile.avatar.supportedFormats': 'Поддерживаемые форматы: JPG, PNG, WebP (макс 5MB)',
  'profile.avatar.invalidFileType': 'Недопустимый тип файла. Пожалуйста, выберите JPG, PNG или WebP изображение.',
  'profile.avatar.fileTooLarge': 'Файл слишком большой. Пожалуйста, выберите изображение меньше 5MB.',
  'profile.avatar.uploadError': 'Не удалось загрузить изображение. Пожалуйста, попробуйте еще раз.',

  // Statistics Modal
  'profile.statistics.title': 'Статистика аккаунта',
  'profile.statistics.description': 'Просмотр ваших метрик производительности и обзор активности',
  'profile.statistics.memberSince': 'Участник с',

  // Customer Statistics
  'profile.statistics.customer.overview': 'Обзор клиента',
  'profile.statistics.customer.performance': 'Метрики производительности',
  'profile.statistics.customer.successRate': 'Процент успеха',
  'profile.statistics.customer.responseRate': 'Процент ответов',

  // Professional Statistics
  'profile.statistics.professional.business': 'Обзор бизнеса',
  'profile.statistics.professional.performance': 'Метрики производительности',
  'profile.statistics.professional.repeatClients': 'Постоянные клиенты',
  'profile.statistics.professional.monthlyEarnings': 'Месячный доход',

  // Customer Profile
  'profile.customer.personalInfo': 'Личная информация',
  'profile.customer.statistics': 'Статистика',
  'profile.customer.tasksPosted': 'Размещено задач',
  'profile.customer.tasksCompleted': 'Завершено задач',
  'profile.customer.averageRating': 'Средняя оценка',
  'profile.customer.totalSpent': 'Всего потрачено',
  'profile.customer.recentActivity': 'Недавняя активность',
  'profile.customer.taskCompleted': 'Задача завершена',
  'profile.customer.taskPosted': 'Задача размещена',
  'profile.customer.viewAllTasks': 'Показать все задачи',
  'profile.customer.notificationPreferences': 'Настройки уведомлений',
  'profile.customer.smsNotifications': 'SMS уведомления',
  'profile.customer.smsNotificationsDesc': 'Получать важные обновления через текстовые сообщения',

  // Professional Profile
  'profile.professional.info': 'Профессиональная информация',
  'profile.professional.title': 'Профессиональная должность',
  'profile.professional.description': 'Описание',
  'profile.professional.hourlyRate': 'Почасовая ставка',
  'profile.professional.availability': 'Доступность',
  'profile.professional.skills': 'Навыки',
  'profile.professional.statistics': 'Статистика работы',
  'profile.professional.completedJobs': 'Выполненные работы',
  'profile.professional.totalEarnings': 'Общий доход',
  'profile.professional.responseTime': 'Время ответа',
  'profile.professional.performance': 'Показатели работы',
  'profile.professional.profileViews': 'Просмотры профиля',
  'profile.professional.completionRate': 'Процент завершения',
  'profile.professional.monthlyGrowth': 'Месячный рост',
  'profile.professional.recentWork': 'Недавние работы',
  'profile.professional.viewPortfolio': 'Смотреть портфолио',
  'profile.professional.setupTitle': 'Настройте ваш профессиональный профиль',
  'profile.professional.setupDescription': 'Заполните ваш профессиональный профиль, чтобы начать получать предложения работы и связаться с клиентами.',
  'profile.professional.setupProfile': 'Настроить профессиональный профиль',
  'profile.professional.businessSettings': 'Настройки бизнеса',
  'profile.professional.paymentMethod': 'Способ оплаты',
  'profile.professional.vatNumber': 'НДС номер',
  'profile.professional.serviceArea': 'Область обслуживания',
  'profile.professional.setupFormDescription': 'Заполните свою профессиональную информацию, чтобы продемонстрировать свои навыки и опыт.',
  'profile.professional.selectCategories': 'Выбрать категории',
  'profile.professional.serviceCategories': 'Категории услуг',
  'profile.professional.verificationTrust': 'Верификация и доверие',
  'profile.professional.phoneVerification': 'Верификация телефона',
  'profile.professional.phoneVerificationRequired': 'Обязательно для всех профессионалов',
  'profile.professional.verified': 'Верифицирован',
  'profile.professional.verifyPhone': 'Верифицировать телефон',
  'profile.professional.acceptedPaymentMethods': 'Принимаемые способы оплаты',
  'profile.professional.businessHours': 'Часы работы',
  'profile.professional.businessHoursPlaceholder': 'например: Пн-Пт 8:00-18:00, Сб 9:00-14:00',
  'profile.professional.weekdaysLabel': 'Будние дни (Пн-Пт)',
  'profile.professional.weekendLabel': 'Выходные (Сб-Вс)',
  'profile.professional.startTime': 'Время начала',
  'profile.professional.endTime': 'Время окончания',
  'profile.professional.noPaymentMethods': 'Не выбраны способы оплаты',
  'profile.professional.portfolioGallery': 'Галерея портфолио',
  'profile.professional.portfolioDescription': 'Покажите свою лучшую работу с фотографиями до/после',
  'profile.professional.addServiceCategories': 'Добавьте категории услуг',
  'profile.professional.categoriesHelp': 'Помогите клиентам найти вас! Выберите услуги, которые вы предлагаете, чтобы начать получать заявки.',

  // Professional Setup Form
  'profile.professional.form.titlePlaceholder': 'например: Full Stack Developer, UX Designer, Маркетинговый консультант',
  'profile.professional.form.descriptionPlaceholder': 'Опишите свой профессиональный опыт, экспертизу и то, что делает вас уникальным...',
  'profile.professional.form.experience': 'Уровень опыта',
  'profile.professional.form.portfolio': 'URL портфолио (по желанию)',
  'profile.professional.form.portfolioDescription': 'Ссылка на ваш сайт, GitHub или онлайн портфолио',
  'profile.professional.form.selectedSkills': 'Выбранные навыки',
  'profile.professional.form.searchSkills': 'Поиск навыков...',
  'profile.professional.form.suggestedSkills': 'Популярные навыки',
  'profile.professional.form.addCustomSkill': 'Добавить пользовательский навык',
  'profile.professional.form.customSkillPlaceholder': 'Введите название навыка',
  'profile.professional.form.moreSkillsAvailable': 'и еще {{count}}...',
  'profile.professional.form.skillsLimitNotice': 'Мы рекомендуем выбрать топ 10 навыков для лучших результатов.',
  'profile.professional.form.submitting': 'Создание профиля...',
  'profile.professional.form.createProfile': 'Создать профессиональный профиль',

  // Experience Options
  'profile.professional.form.experienceOptions.beginner': '0-1 года',
  'profile.professional.form.experienceOptions.intermediate': '2-5 лет',
  'profile.professional.form.experienceOptions.experienced': '5-10 лет',
  'profile.professional.form.experienceOptions.expert': '10+ лет',

  // Availability Options
  'profile.professional.form.availabilityOptions.available': 'Доступен',
  'profile.professional.form.availabilityOptions.busy': 'Занят',
  'profile.professional.form.availabilityOptions.unavailable': 'Недоступен',

  // Form Validation
  'profile.professional.form.validation.titleRequired': 'Профессиональная должность обязательна (минимум 3 символа)',
  'profile.professional.form.validation.descriptionRequired': 'Описание обязательно (минимум 20 символов)',
  'profile.professional.form.validation.rateRequired': 'Почасовая ставка должна быть больше 0',
  'profile.professional.form.validation.skillsRequired': 'Пожалуйста, выберите хотя бы один навык',

  // Settings Modal
  'profile.settings.description': 'Управляйте предпочтениями аккаунта и настройками конфиденциальности',
  'profile.settings.notifications': 'Уведомления',
  'profile.settings.emailNotifications': 'Email уведомления',
  'profile.settings.emailNotificationsDesc': 'Получать обновления о ваших задачах и аккаунте',
  'profile.settings.taskUpdates': 'Обновления задач',
  'profile.settings.taskUpdatesDesc': 'Получать уведомления при обновлении задач',
  'profile.settings.marketingEmails': 'Маркетинговые письма',
  'profile.settings.marketingEmailsDesc': 'Получать советы и промо контент',
  'profile.settings.pushNotifications': 'Push уведомления',
  'profile.settings.pushNotificationsDesc': 'Получать мгновенные уведомления на ваше устройство',
  'profile.settings.weeklyDigest': 'Еженедельная сводка',
  'profile.settings.weeklyDigestDesc': 'Получать еженедельное резюме вашей активности и возможностей',
  'profile.settings.privacy': 'Конфиденциальность',
  'profile.settings.profileVisibility': 'Видимость профиля',
  'profile.settings.profileVisibilityDesc': 'Сделать ваш профиль видимым для потенциальных клиентов',
  'profile.settings.showContactInfo': 'Показывать контактную информацию',
  'profile.settings.showContactInfoDesc': 'Отображать вашу контактную информацию публично',
  'profile.settings.interface': 'Интерфейс',
  'profile.settings.darkMode': 'Темная тема',
  'profile.settings.darkModeDesc': 'Переключиться на темную тему интерфейса',
  'profile.settings.dangerZone': 'Опасная зона',
  'profile.settings.deleteAccount': 'Удалить аккаунт',
  'profile.settings.deleteAccountDesc': 'Навсегда удалить ваш аккаунт и все данные',
  'profile.settings.deleteAccountConfirm': 'Удаление аккаунта скоро будет реализовано',

  // Customer Profile Form
  'profile.form.name': 'Полное имя',
  'profile.form.saving': 'Сохранение...',
  'profile.form.validation.nameRequired': 'Имя обязательно (минимум 2 символа)',
  'profile.form.validation.emailRequired': 'Email обязателен',
  'profile.form.validation.emailInvalid': 'Пожалуйста, введите действительный email адрес',
  'profile.form.validation.phoneRequired': 'Номер телефона обязателен',
  'profile.form.validation.phoneInvalid': 'Пожалуйста, введите действительный номер телефона',
  'profile.form.validation.locationRequired': 'Местоположение обязательно (минимум 3 символа)',

  // Locations
  'locations.sofiaCenter': 'София, Центр',
  'locations.sofiaLyulin': 'София, Люлин',
  'locations.sofiaStudentski': 'София, Студенческий городок',
  'locations.sofiaVitosha': 'София, Витоша',
  'locations.plovdiv': 'Пловдив',
  'locations.varna': 'Варна',
  'locations.burgas': 'Бургас',
  'locations.ruse': 'Русе',
  'locations.staraZagora': 'Стара Загора',

  // Notifications
  'notifications.title': 'Уведомления',
  'notifications.markAllRead': 'Отметить все как прочитанное',
  'notifications.tabAll': 'Все',
  'notifications.tabApplications': 'Заявки',
  'notifications.tabTasks': 'Задачи',
  'notifications.tabMessages': 'Сообщения',
  'notifications.empty.title': 'Уведомлений пока нет',
  'notifications.empty.message': 'Вы получите уведомление, когда кто-то откликнется на ваши задачи или ответит на ваши заявки.',
  'notifications.empty.filterMessage': 'Нет уведомлений в этой категории.',
  'notifications.emptyUnread.title': 'Вы прочитали всё!',
  'notifications.emptyUnread.message': 'Все уведомления прочитаны.',
  'notifications.viewApplication': 'Посмотреть заявку',
  'notifications.viewTask': 'Посмотреть задачу',
};

export default ru;
