// Application-related translations - submitting, managing, accepting, rejecting applications
export const applications = {
  // Application Status Labels (for badges/chips)
  'applicationStatus.pending': 'На розгляді',
  'applicationStatus.accepted': 'Прийнята',
  'applicationStatus.rejected': 'Відхилена',
  'applicationStatus.withdrawn': 'Відкликана',
  'applicationStatus.removedByCustomer': 'Видалена',

  // Application Dialog
  'application.title': 'Подати заявку на завдання',
  'application.proposedPrice': 'Ваша ціна',
  'application.pricePlaceholder': 'Введіть ціну в BGN',
  'application.timeline': 'Коли можете почати?',
  'application.timelineToday': 'Сьогодні',
  'application.timelineWeek': 'Протягом тижня',
  'application.timelineFlexible': 'Гнучко',
  'application.hoursShort': 'год',
  'application.message': 'Чому ви найкращий кандидат?',
  'application.messagePlaceholder': 'Розкажіть про свій досвід та чому ви ідеально підходите...',
  'application.messageInfo': 'Зосередьтесь на навичках та досвіді. Контакти можна обмінюватись після прийняття заявки.',
  'application.characterCount': '{{current}}/{{max}} символів',
  'application.submit': 'Надіслати заявку',
  'application.submitting': 'Надсилання...',
  'application.cancel': 'Скасувати',
  'application.success': 'Заявку надіслано!',
  'application.successMessage': 'Власник завдання розгляне вашу заявку та незабаром відповість.',
  'application.viewApplication': 'Моя заявка',
  'application.browseOther': 'Переглянути завдання',
  'application.errors.priceRequired': 'Ціна обов\'язкова',
  'application.errors.priceMin': 'Ціна має бути більше 0',
  'application.errors.timelineRequired': 'Терміни обов\'язкові',
  'application.errors.messageRequired': 'Повідомлення обов\'язкове',
  'application.errors.messageMin': 'Повідомлення має містити мінімум 30 символів',
  'application.errors.messageMax': 'Повідомлення не може перевищувати 500 символів',
  'application.errors.noPhoneNumbers': 'Номери телефонів заборонені у заявках. Контакти можна обмінювати після прийняття.',
  'application.errors.noUrls': 'Посилання заборонені у заявках. Портфоліо можна показати після прийняття.',
  'application.errors.noEmails': 'Email адреси заборонені у заявках. Контакти можна обмінювати після прийняття.',
  'application.alreadyApplied': 'Ви вже подали заявку на це завдання',
  'application.cannotApplyOwnTask': 'Не можна подати заявку на власне завдання',
  'application.budget': 'Бюджет',
  'application.tipClientBudget': 'Порада: Бюджет клієнта {{min}} - {{max}} BGN',
  'application.tipShareExperience': 'Порада: Поділіться досвідом, щоб виділитись',
  'application.successSteps.quickReview': 'Швидкий перегляд',
  'application.successSteps.getResponse': 'Отримати відповідь',
  'application.successSteps.startWork': 'Почати роботу',

  // Applications Management
  'applications.title': 'Заявки',
  'applications.count': 'заявок',
  'applications.sortBy': 'Сортувати',
  'applications.sortNewest': 'Спочатку нові',
  'applications.sortPriceLow': 'Ціна: від низької до високої',
  'applications.sortPriceHigh': 'Ціна: від високої до низької',
  'applications.sortRating': 'Найвищий рейтинг',
  'applications.sortExperience': 'Найбільше досвіду',
  'applications.filterAll': 'Усі',
  'applications.filterPending': 'Очікують',
  'applications.filterAccepted': 'Прийняті',
  'applications.filterRejected': 'Відхилені',
  'applications.emptyState.title': 'Заявок ще немає',
  'applications.emptyState.message': 'Ваше завдання активне! Фахівці незабаром почнуть подавати заявки.',
  'applications.proposedPrice': 'Запропонована ціна',
  'applications.timeline': 'Терміни',
  'applications.message': 'Повідомлення',
  'applications.portfolio': 'Портфоліо',
  'applications.portfolioImages': 'зображень портфоліо',
  'applications.tasksCompleted': 'виконаних завдань',
  'applications.yearsExperience': 'років досвіду',
  'applications.viewDetails': 'Детальніше',
  'applications.freshProfessional': 'Новий на платформі - допоможіть йому побудувати репутацію!',
  'applications.new': 'Новий',
  'applications.acceptApplication': 'Прийняти',
  'applications.rejectApplication': 'Відхилити',
  'applications.status': 'Статус',
  'applications.statusPending': 'Очікує',
  'applications.statusAccepted': 'Прийнято',
  'applications.statusRejected': 'Відхилено',
  'applications.statusWithdrawn': 'Відкликано',

  // Application Detail Modal
  'applicationDetail.title': 'Деталі заявки',
  'applicationDetail.professionalProfile': 'Профіль фахівця',
  'applicationDetail.applicationMessage': 'Повідомлення заявки',
  'applicationDetail.portfolioGallery': 'Портфоліо',
  'applicationDetail.recentReviews': 'Останні відгуки',
  'applicationDetail.close': 'Закрити',

  // Accept Application Dialog
  'acceptApplication.title': 'Прийняти заявку',
  'acceptApplication.description': 'Ви збираєтесь прийняти заявку від {{name}}. Перегляньте деталі та підтвердіть угоду.',
  'acceptApplication.agreedPrice': 'Узгоджена ціна',
  'acceptApplication.timeline': 'Терміни',
  'acceptApplication.messageLabel': 'Повідомлення фахівцю (необов\'язково)',
  'acceptApplication.messagePlaceholder': 'Привітайтесь, поділіться доступністю для дзвінка або додайте деталі...',
  'acceptApplication.messageHelp': 'Це повідомлення буде надіслано {{name}} разом з вашими контактами.',
  'acceptApplication.contactInfo': 'Як фахівець може з вами зв\'язатися?',
  'acceptApplication.noInAppChat': 'У нас немає внутрішнього чату. Оберіть спосіб зв\'язку.',
  'acceptApplication.sharePhone': 'Поділитися номером телефону',
  'acceptApplication.shareEmail': 'Поділитися email адресою',
  'acceptApplication.customContact': 'Вказати інші контакти',
  'acceptApplication.customContactLabel': 'Контактна інформація',
  'acceptApplication.customContactPlaceholder': 'Телефон, Telegram (@username), Viber, WhatsApp або інше...',
  'acceptApplication.customContactHelp': 'Вкажіть будь-який зручний спосіб зв\'язку',
  'acceptApplication.customContactRequired': 'Вкажіть контактну інформацію',
  'acceptApplication.noSavedContacts': 'Вкажіть спосіб зв\'язку, за яким фахівець може з вами зв\'язатися.',
  'acceptApplication.phoneWarning': 'Цей номер буде передано фахівцю.',
  'acceptApplication.emailWarning': 'Email повільніший для координації. Рекомендуємо телефон/Telegram.',
  'acceptApplication.privacyPolicy': 'Політика конфіденційності',
  'acceptApplication.pleaseConfirm': 'Підтвердіть:',
  'acceptApplication.agreement.priceTimeline': 'Я погоджуюсь на запропоновану ціну ({{price}} {{currency}}) та терміни ({{timeline}})',
  'acceptApplication.agreement.contactSharing': 'Я розумію, що мої контакти будуть передані {{name}}',
  'acceptApplication.agreement.otherApplications': 'Я розумію, що всі інші заявки будуть автоматично відхилені',
  'acceptApplication.warning': 'Після прийняття ви зобов\'язуєтесь працювати з {{name}}. Усі інші заявки будуть автоматично відхилені.',
  'acceptApplication.confirm': 'Прийняти заявку',
  'acceptApplication.cancel': 'Скасувати',

  // Reject Application Dialog
  'rejectApplication.title': 'Відхилити заявку',
  'rejectApplication.description': 'Ви збираєтесь відхилити заявку від {{name}}. Фахівця буде повідомлено.',
  'rejectApplication.reasonTitle': 'Причина відхилення (необов\'язково)',
  'rejectApplication.reasonHelp': 'Вказівка причини допомагає фахівцям покращувати заявки.',
  'rejectApplication.reasons.betterFit': 'Знайшов кращий варіант',
  'rejectApplication.reasons.priceHigh': 'Ціна занадто висока',
  'rejectApplication.reasons.timelineIssue': 'Терміни не підходять',
  'rejectApplication.reasons.changedMind': 'Передумав щодо завдання',
  'rejectApplication.reasons.other': 'Інша причина',
  'rejectApplication.note': '{{name}} буде повідомлено, що заявку не обрано. Ви можете переглянути інші заявки та обрати іншого фахівця.',
  'rejectApplication.confirm': 'Відхилити заявку',
  'rejectApplication.cancel': 'Скасувати',

  // Professional Applications Dashboard
  'myApplications.title': 'Мої заявки',
  'myApplications.count': '{{count}} заявок',
  'myApplications.sortBy': 'Сортувати',
  'myApplications.sortNewest': 'Спочатку нові',
  'myApplications.sortOldest': 'Спочатку старі',
  'myApplications.sortStatus': 'За статусом',
  'myApplications.sortTaskDate': 'За датою завдання',
  'myApplications.sortPriceHigh': 'Ціна: від високої до низької',
  'myApplications.sortPriceLow': 'Ціна: від низької до високої',
  'myApplications.filterAll': 'Усі',
  'myApplications.filterPending': 'Очікують',
  'myApplications.filterAccepted': 'Прийняті',
  'myApplications.filterRejected': 'Відхилені',
  'myApplications.filterWithdrawn': 'Відкликані',
  'myApplications.status.pending': 'Очікує',
  'myApplications.status.accepted': 'Прийнято',
  'myApplications.status.rejected': 'Відхилено',
  'myApplications.status.withdrawn': 'Відкликано',
  'myApplications.appliedAgo': 'Подано {{time}}',
  'myApplications.acceptedAgo': 'Прийнято {{time}}',
  'myApplications.rejectedAgo': 'Відхилено {{time}}',
  'myApplications.yourQuote': 'Ваша пропозиція',
  'myApplications.taskBudget': 'Бюджет завдання',
  'myApplications.timeline': 'Терміни',
  'myApplications.agreedPrice': 'Узгоджена ціна',
  'myApplications.startDate': 'Початок',
  'myApplications.viewDetails': 'Детальніше',
  'myApplications.viewTask': 'Переглянути завдання',
  'myApplications.withdraw': 'Відкликати',
  'myApplications.withdrawConfirm': 'Точно хочете відкликати заявку?',
  'myApplications.withdrawError': 'Не вдалося відкликати заявку',
  'myApplications.messageCustomer': 'Написати клієнту',
  'myApplications.markStarted': 'Позначити як розпочато',
  'myApplications.markCompleted': 'Завершити',
  'myApplications.reportIssue': 'Повідомити про проблему',
  'myApplications.findSimilar': 'Знайти схожі',
  'myApplications.delete': 'Видалити',
  'myApplications.emptyState.title': 'Ви ще не подавали заявок',
  'myApplications.emptyState.message': 'Переглядайте доступні завдання та подавайте заявки на ті, що відповідають вашим навичкам.',
  'myApplications.emptyState.browse': 'Переглянути завдання',
  'myApplications.emptyStatePending.title': 'Усе оброблено!',
  'myApplications.emptyStatePending.message': 'Немає очікуваних заявок. Усі ваші заявки розглянуто.',
  'myApplications.emptyStateAccepted.title': 'Прийнятих заявок ще немає',
  'myApplications.emptyStateAccepted.message': 'Продовжуйте подавати заявки! Ваша наступна можливість за рогом.',
  'myApplications.emptyStateRejected.title': 'Відхилених заявок немає',
  'myApplications.emptyStateRejected.message': 'Чудові новини! Жодну з ваших заявок не відхилено.',
  'myApplications.emptyStateWithdrawn.title': 'Відкликаних заявок немає',
  'myApplications.emptyStateWithdrawn.message': 'Ви ще не відкликали жодної заявки.',
  'myApplications.withdrawDialog.title': 'Відкликати заявку?',
  'myApplications.withdrawDialog.description': 'Точно хочете відкликати заявку на "{{taskTitle}}"?',
  'myApplications.withdrawDialog.reason': 'Причина (необов\'язково)',
  'myApplications.withdrawDialog.selectReason': 'Оберіть причину (необов\'язково)',
  'myApplications.withdrawDialog.reasonUnavailable': 'Більше не доступний',
  'myApplications.withdrawDialog.reasonFoundWork': 'Знайшов іншу роботу',
  'myApplications.withdrawDialog.reasonChanged': 'Вимоги завдання змінились',
  'myApplications.withdrawDialog.reasonPrice': 'Ціна занадто низька',
  'myApplications.withdrawDialog.reasonOther': 'Інше',
  'myApplications.withdrawDialog.warning': 'Після відкликання ви не зможете повторно подати заявку.',
  'myApplications.withdrawDialog.confirm': 'Підтвердити відкликання',
  'myApplications.withdrawDialog.cancel': 'Скасувати',
  'myApplications.detail.taskDetails': 'Деталі завдання',
  'myApplications.detail.yourProposal': 'Ваша пропозиція',
  'myApplications.detail.agreedTerms': 'Узгоджені умови',
  'myApplications.detail.rejectionReason': 'Причина відхилення',
  'myApplications.detail.waitingResponse': 'Очікування відповіді замовника',
  'myApplications.detail.usuallyResponds': 'Зазвичай відповідає протягом 24 годин',
  'myApplications.detail.otherApplicants': 'Ще {{count}} фахівців подали заявки',
  'myApplications.detail.nextSteps': 'Наступні кроки',
  'myApplications.detail.customerApproved': 'Замовник схвалив вашу заявку',
  'myApplications.detail.contactCustomer': 'Зв\'яжіться з замовником для уточнення деталей',
  'myApplications.detail.completeBy': 'Завершіть завдання до {{date}}',
  'myApplications.detail.feedback': 'Не сприймайте це особисто! Продовжуйте подавати заявки на схожі завдання.',

  // My Applications Page (Professional View)
  'myApplications.subtitle': 'Заявки, які ви подали на завдання',
  'myApplications.browseButton': 'Переглянути завдання',
  'myApplications.filter.all': 'Усі',
  'myApplications.filter.pending': 'Очікують',
  'myApplications.filter.accepted': 'Прийняті',
  'myApplications.filter.rejected': 'Відхилені',
  'myApplications.filter.withdrawn': 'Відкликані',
  'myApplications.yourProposal': 'Ваша пропозиція',
  'myApplications.proposedPrice': '{{price}} BGN',
  'myApplications.submitted': 'Подано',
  'myApplications.empty.title': 'Заявок ще немає',
  'myApplications.empty.message': 'Ви ще не подавали заявок. Переглядайте доступні завдання!',
  'myApplications.empty.browseButton': 'Переглянути завдання',

  // My Work Page (Professional View - Accepted Applications Only)
  'myWork.title': 'Моя робота',
  'myWork.subtitle': 'Керуйте активними завданнями та виконаними роботами',
  'myWork.loading': 'Завантаження вашої роботи...',
  'myWork.filter.inProgress': 'У роботі',
  'myWork.filter.pendingCompletion': 'Очікують завершення',
  'myWork.filter.completed': 'Завершені',
  'myWork.empty.inProgress.title': 'Активних завдань немає',
  'myWork.empty.inProgress.message': 'У вас немає завдань у роботі. Переглядайте доступні завдання!',
  'myWork.empty.inProgress.browseButton': 'Переглянути завдання',
  'myWork.empty.pendingCompletion.title': 'Немає очікуваних підтверджень',
  'myWork.empty.pendingCompletion.message': 'Усі ваші завдання актуальні!',
  'myWork.empty.completed.title': 'Виконаних робіт ще немає',
  'myWork.empty.completed.message': 'Завершені завдання з\'являться тут.',
  'myWork.customerContact': 'Контакт замовника',
  'myWork.customerMessage': 'Повідомлення від замовника',
  'myWork.taskDeadline': 'Дедлайн',
  'myWork.startedDaysAgo': 'Розпочато {{days}} днів тому',
  'myWork.completedOn': 'Завершено {{date}}',
  'myWork.confirmCompletion': 'Підтвердити завершення',
  'myWork.viewReview': 'Переглянути відгук',
  'myWork.withdrawFromTask': 'Відмовитись',
  'myWork.leaveReview': 'Залишити відгук',

  // Professional Withdrawal from Accepted Task
  'professionalWithdraw.title': 'Відмовитись від завдання',
  'professionalWithdraw.subtitle': 'Відмова від: {{taskTitle}}',
  'professionalWithdraw.customer': 'Замовник',
  'professionalWithdraw.customerNotification': 'Замовника буде негайно повідомлено, і завдання буде відкрито повторно',

  // Rate limiting
  'professionalWithdraw.rateLimit.title': 'Ви можете відмовитись ще {{remaining}} раз(ів) цього місяця',
  'professionalWithdraw.rateLimit.message': 'Фахівці можуть відмовлятись від 2 завдань на місяць',
  'professionalWithdraw.rateLimit.warning': 'Часті відмови можуть вплинути на ваш рейтинг та статус акаунта',
  'professionalWithdraw.limitExceeded.title': 'Досягнуто місячний ліміт відмов',
  'professionalWithdraw.limitExceeded.message': 'Ви досягли ліміту відмов на цей місяць. Зверніться до підтримки в екстрених випадках.',

  // Timing warnings
  'professionalWithdraw.earlyWithdrawal.title': 'Рання відмова - без штрафу',
  'professionalWithdraw.earlyWithdrawal.message': 'Оскільки ви прийняли менше 2 годин тому, це не вплине на ваш місячний ліміт',
  'professionalWithdraw.lateWithdrawal.title': 'Попередження про пізню відмову',
  'professionalWithdraw.lateWithdrawal.message': 'Відмова більш ніж через 24 години після прийняття суттєво впливає на замовника та ваш рейтинг',

  // Reasons
  'professionalWithdraw.reasonLabel': 'Чому ви відмовляєтесь?',
  'professionalWithdraw.reasons.health_emergency': 'Проблеми зі здоров\'ям або екстрений випадок',
  'professionalWithdraw.reasons.capacity_issue': 'Перевантаження або недооцінка часу',
  'professionalWithdraw.reasons.scope_mismatch': 'Завдання інше, ніж очікувалось',
  'professionalWithdraw.reasons.customer_unresponsive': 'Замовник не відповідає',
  'professionalWithdraw.reasons.location_issue': 'Не можу дістатися до місця або проблеми безпеки',
  'professionalWithdraw.reasons.budget_dispute': 'Замовник хоче переглянути узгоджену ціну',
  'professionalWithdraw.reasons.equipment_issue': 'Немає необхідних інструментів або матеріалів',
  'professionalWithdraw.reasons.other': 'Інша причина',

  // Form
  'professionalWithdraw.descriptionLabel': 'Додаткові деталі',
  'professionalWithdraw.descriptionPlaceholder': 'Поясніть ситуацію...',
  'professionalWithdraw.descriptionHint': 'Це допомагає нам покращувати платформу',
  'professionalWithdraw.confirmButton': 'Відмовитись від завдання',
  'professionalWithdraw.reputationWarning': 'Ця відмова буде записана і може вплинути на ваш рейтинг',

  // Success/error
  'professionalWithdraw.successTitle': 'Відмова успішна',
  'professionalWithdraw.success': 'Ви відмовились від завдання. Замовника повідомлено.',
  'professionalWithdraw.errorTitle': 'Помилка відмови',
  'professionalWithdraw.error': 'Не вдалося відмовитись. Спробуйте ще раз або зверніться до підтримки.',

  // Task Detail Page - Professional View
  'taskDetail.professional.withdraw': 'Відмовитись від завдання',

  // Accept Application Success Toast
  'acceptApplication.successTitle': '🎉 Заявку прийнято!',
  'acceptApplication.successDescription': 'Тепер ви працюєте з {{name}}. Усі інші заявки автоматично відхилено.',

  // Task In Progress State
  'taskInProgress.title': 'Завдання в роботі!',
  'taskInProgress.description': 'Ви прийняли заявку. Ваше завдання тепер виконується фахівцем.',
  'taskInProgress.workingWith': 'Працюєте з',
  'taskInProgress.specialization': 'Спеціалізація',
  'taskInProgress.location': 'Місце',
  'taskInProgress.agreedPrice': 'Узгоджена ціна',
  'taskInProgress.infoMessage': 'Усі інші заявки автоматично відхилено. Відстежуйте прогрес та спілкуйтесь з фахівцем через сторінку керування завданнями.',
  'taskInProgress.viewMyTasks': 'Мої завдання',
  'taskInProgress.viewNotifications': 'Сповіщення',
};
