// Authentication and authorization translations
export const auth = {
  'auth.applyForTask': 'Подати заявку',
  'auth.askQuestion': 'Поставити запитання',
  'auth.createTask': 'Створити завдання',
  'auth.loginToContinue': 'Увійдіть, щоб продовжити',
  'auth.applyDescription':
    'Надішліть заявку клієнту та отримайте можливість працювати над цим завданням.',
  'auth.questionDescription':
    'Поставте запитання клієнту перед подачею заявки.',
  'auth.createTaskDescription':
    'Створіть нове завдання та знайдіть перевірених фахівців для виконання роботи.',
  'auth.joinAsProfessional': 'Приєднатися як фахівець',
  'auth.joinAsProfessionalDescription':
    'Почніть заробляти, пропонуючи свої навички та послуги клієнтам у вашому регіоні.',
  'auth.loginDescription':
    'Увійдіть до свого акаунта для керування завданнями та зв\'язку з фахівцями.',
  'auth.emailLabel': 'Електронна пошта',
  'auth.password': 'Пароль',
  'auth.rememberMe': 'Запам\'ятати мене',
  'auth.forgotPasswordLink': 'Забули пароль?',
  'auth.loginOrRegister': 'Увійти / Реєстрація',
  'auth.loginOrRegisterToContinue': 'Увійдіть або зареєструйтесь, щоб продовжити',
  'auth.loginOrRegisterDescription': 'Введіть облікові дані для входу або створіть новий акаунт.',
  'auth.continue': 'Продовжити',
  'auth.login': 'Увійти',
  'auth.or': 'або',
  'auth.noAccount': 'Немає акаунта?',
  'auth.createAccount': 'Створити акаунт',
  'auth.whyRegister': 'Чому варто зареєструватися?',
  'auth.benefit1': '• Подавати заявки на завдання',
  'auth.benefit2': '• Спілкуватися напряму з клієнтами',
  'auth.benefit3': '• Відстежувати історію',
  'auth.benefit4': '• Отримувати сповіщення про нові завдання',
  'auth.continueWith': 'Продовжити з',
  'auth.telegramHint': 'Відкриє Telegram додаток або десктопний клієнт',
  'auth.fullName': 'Ваше ім\'я',
  'auth.nameRequired': 'Будь ласка, вкажіть ім\'я для створення акаунта',
  'auth.nameRequiredHint': 'Ім\'я потрібне для створення акаунта',
  'auth.nameHint': 'Потрібно лише при створенні нового акаунта',
  'auth.unexpectedError': 'Сталася неочікувана помилка. Спробуйте ще раз.',

  // WebView and popup warnings
  'auth.webViewWarningTitle': 'Вхід через Google недоступний',
  'auth.webViewWarningMessage': 'Вхід через Google не працює в браузері цього додатку. Використовуйте email/пароль або відкрийте в Safari/Chrome.',
  'auth.openInBrowser': 'Відкрити в браузері',
  'auth.popupBlocked': 'Будь ласка, дозвольте спливаючі вікна для входу',

  // Email verification
  'auth.email.subject': 'Trudify - Підтвердіть свою електронну адресу',
  'auth.email.heading': 'Ласкаво просимо до Trudify!',
  'auth.email.greeting': 'Привіт',
  'auth.email.message':
    'Дякуємо за реєстрацію! Підтвердіть свою електронну адресу, щоб отримувати сповіщення.',
  'auth.email.buttonText': 'Підтвердити Email',
  'auth.email.linkInstruction': 'Або скопіюйте це посилання у браузер:',
  'auth.email.footerText': 'Якщо ви не створювали акаунт, можете ігнорувати цей лист.',
  'auth.email.footerRights': 'Усі права захищено.',
  'auth.email.expiresIn': '24 години',

  // Forgot password
  'auth.forgotPassword.title': 'Забули пароль',
  'auth.forgotPassword.description': 'Введіть email, і ми надішлемо посилання для скидання пароля.',
  'auth.forgotPassword.emailLabel': 'Електронна адреса',
  'auth.forgotPassword.sendResetLink': 'Надіслати посилання',
  'auth.forgotPassword.backToLogin': 'Повернутися до входу',
  'auth.forgotPassword.checkEmail': 'Перевірте пошту',
  'auth.forgotPassword.emailSent': 'Ми надіслали посилання для скидання на',
  'auth.forgotPassword.emailSentInstructions': 'Перевірте вхідні та натисніть посилання для скидання пароля.',
  'auth.forgotPassword.didNotReceive': 'Не отримали лист?',
  'auth.forgotPassword.resendLink': 'Надіслати повторно',
  'auth.forgotPassword.error': 'Не вдалося надіслати лист. Спробуйте ще раз.',

  // Reset password
  'auth.resetPassword.title': 'Скинути пароль',
  'auth.resetPassword.description': 'Введіть новий пароль нижче.',
  'auth.resetPassword.newPassword': 'Новий пароль',
  'auth.resetPassword.confirmPassword': 'Підтвердіть пароль',
  'auth.resetPassword.resetButton': 'Скинути пароль',
  'auth.resetPassword.success': 'Пароль успішно скинуто!',
  'auth.resetPassword.successDescription': 'Тепер ви можете увійти з новим паролем.',
  'auth.resetPassword.goToLogin': 'Перейти до входу',
  'auth.resetPassword.invalidToken': 'Недійсне або прострочене посилання',
  'auth.resetPassword.invalidTokenDescription': 'Це посилання для скидання пароля недійсне або прострочене. Запросіть нове.',
  'auth.resetPassword.passwordMismatch': 'Паролі не збігаються',
  'auth.resetPassword.passwordTooShort': 'Пароль має містити щонайменше 6 символів',
  'auth.resetPassword.error': 'Не вдалося скинути пароль. Спробуйте ще раз.',

  // Email verification
  'auth.emailVerification.title': 'Підтвердіть Email',
  'auth.emailVerification.notVerified': 'Ваш email не підтверджено',
  'auth.emailVerification.description': 'Підтвердіть email для отримання сповіщень та доступу до всіх функцій.',
  'auth.emailVerification.resendButton': 'Надіслати лист підтвердження',
  'auth.emailVerification.resending': 'Надсилання...',
  'auth.emailVerification.success': 'Лист надіслано! Перевірте вхідні.',
  'auth.emailVerification.alreadyVerified': 'Ваш email вже підтверджено!',
  'auth.emailVerification.error': 'Не вдалося надіслати лист. Спробуйте ще раз.',
  'auth.emailVerification.rateLimited': 'Забагато запитів. Спробуйте пізніше.',
  'auth.emailVerification.checkSpam': 'Не забудьте перевірити папку спам.',

  // Email verification after signup (auth slide-over)
  'auth.emailVerification.checkInbox': 'Перевірте пошту!',
  'auth.emailVerification.sentMessage': 'Ми надіслали лист підтвердження на',
  'auth.emailVerification.instructions': 'Натисніть посилання в листі для підтвердження акаунта.',
  'auth.emailVerification.resend': 'Надіслати повторно',
  'auth.emailVerification.continue': 'Продовжити',

  // Email verified success page
  'auth.emailVerified.title': 'Email підтверджено!',
  'auth.emailVerified.description': 'Вашу електронну адресу успішно підтверджено. Тепер ви маєте повний доступ до всіх функцій.',
  'auth.emailVerified.whatNext': 'Що б ви хотіли зробити далі?',
  'auth.emailVerified.browseTasks': 'Знайти роботу',
  'auth.emailVerified.createTask': 'Створити завдання',
  'auth.emailVerified.completeProfile': 'Заповнити профіль',
  'auth.emailVerified.goHome': 'На головну',

  // Account Deletion
  'accountDeletion.title': 'Видалення акаунта',
  'accountDeletion.loginRequired': 'Щоб видалити акаунт, вам потрібно увійти в систему.',
  'accountDeletion.whatHappens': 'Що станеться при видаленні акаунта:',
  'accountDeletion.profileRemoved': 'Ваш профіль буде видалено назавжди',
  'accountDeletion.tasksCancelled': 'Відкриті завдання будуть скасовані',
  'accountDeletion.reviewsAnonymized': 'Ваші відгуки стануть анонімними (рейтинги збережуться)',
  'accountDeletion.cannotUndo': 'Цю дію неможливо скасувати',
  'accountDeletion.loginWithGoogle': 'Увійти через Google',
  'accountDeletion.loginWithFacebook': 'Увійти через Facebook',
  'accountDeletion.backToHome': 'Повернутися на головну',
  'accountDeletion.checkingStatus': 'Перевірка статусу акаунта...',
  'accountDeletion.errorTitle': 'Щось пішло не так',
  'accountDeletion.tryAgain': 'Спробувати знову',
  'accountDeletion.cannotDeleteYet': 'Поки що не можна видалити акаунт',
  'accountDeletion.completeTasksFirst': 'У вас є активна робота, яку потрібно завершити спочатку.',
  'accountDeletion.activeWork': 'Активні завдання, що блокують видалення:',
  'accountDeletion.asCustomer': 'як замовник',
  'accountDeletion.asProfessional': 'як спеціаліст',
  'accountDeletion.viewMyTasks': 'Переглянути мої завдання',
  'accountDeletion.backToProfile': 'Повернутися до профілю',
  'accountDeletion.confirmTitle': 'Видалення акаунта',
  'accountDeletion.confirmDescription': 'Це назавжди видалить ваш акаунт та всі пов\'язані дані.',
  'accountDeletion.readyToDelete': 'Перевірку пройдено - готово до видалення',
  'accountDeletion.willBeDeleted': 'Буде видалено назавжди:',
  'accountDeletion.openTasksCount': '{count} відкритих завдань буде скасовано',
  'accountDeletion.applicationsCount': '{count} очікуваних заявок буде відкликано',
  'accountDeletion.messagesCount': '{count} повідомлень',
  'accountDeletion.notificationsCount': '{count} сповіщень',
  'accountDeletion.willBeAnonymized': 'Буде анонімізовано:',
  'accountDeletion.reviewsWrittenCount': '{count} відгуків, які ви написали (рейтинги збережуться)',
  'accountDeletion.irreversibleWarning': 'Ця дія незворотна. Всі ваші дані будуть видалені назавжди.',
  'accountDeletion.confirmPassword': 'Підтвердіть паролем',
  'accountDeletion.enterPassword': 'Введіть пароль',
  'accountDeletion.passwordDescription': 'Введіть пароль для підтвердження видалення акаунта',
  'accountDeletion.passwordOptionalNote': 'Потрібно лише якщо ви зареєструвалися з email та паролем. Залиште порожнім, якщо ви увійшли через Google або Facebook.',
  'accountDeletion.noPasswordLink': 'Ніколи не встановлювали пароль? Встановіть його тут',
  'accountDeletion.deleteButton': 'Видалити мій акаунт',
  'accountDeletion.cancel': 'Скасувати',
  'accountDeletion.invalidPassword': 'Невірний пароль. Будь ласка, спробуйте знову.',
  'accountDeletion.hasActiveTasksError': 'Не можна видалити акаунт з активними завданнями. Спочатку завершіть або скасуйте їх.',
  'accountDeletion.deleteError': 'Не вдалося видалити акаунт. Будь ласка, спробуйте знову.',
  'accountDeletion.preflightError': 'Не вдалося перевірити статус. Будь ласка, спробуйте знову.',
  'accountDeletion.unknownError': 'Сталася непередбачена помилка. Будь ласка, спробуйте знову.',

  // Professional Onboarding Dialog
  'auth.professionalOnboarding.title': 'Залишився один крок',
  'auth.professionalOnboarding.description': 'Заповніть профіль, щоб стати видимим для клієнтів, які шукають таких спеціалістів як ви.',
  'auth.professionalOnboarding.benefits': 'Займе лише 2 хвилини. Ви з\'явитесь у пошуку та отримуватимете сповіщення про завдання.',
  'auth.professionalOnboarding.confirm': 'Заповнити профіль',
  'auth.professionalOnboarding.later': 'Пізніше',

  // Register Page (Ad Campaign Landing)
  'auth.register.pageTitle': 'Приєднуйтесь до Trudify',
  'auth.register.pageSubtitle': '#1 платформа в Болгарії, що з\'єднує клієнтів з перевіреними фахівцями',
  'auth.register.selectIntent': 'Що привело вас до Trudify?',
  'auth.register.intentProfessional': 'Шукаю роботу',
  'auth.register.intentProfessionalDesc': 'Знаходьте замовлення та отримуйте клієнтів',
  'auth.register.intentCustomer': 'Шукаю виконавця',
  'auth.register.intentCustomerDesc': 'Знаходьте фахівців для ваших завдань',
  'auth.register.tabRegister': 'Створити акаунт',
  'auth.register.tabSignIn': 'Увійти',
  'auth.register.submitRegister': 'Створити акаунт',
  'auth.register.submitSignIn': 'Увійти',
  'auth.register.benefitVerified': 'Всі фахівці перевірені',
  'auth.register.benefitFree': 'Безкоштовно',
  'auth.register.benefitFast': 'Швидкі відповіді',
  'auth.register.continueToSignup': 'Продовжити',
  'auth.register.backToIntent': 'Назад',
  'auth.register.step': 'Крок',
  'auth.register.of': 'з',
  'auth.register.oneClickSignup': 'Реєстрація в один клік',
  'auth.register.useQuickSignup': 'Використовуйте кнопки вище для швидкої реєстрації',
  'auth.register.freeForever': '100% Безкоштовно — Без прихованих комісій',

  // Professional info step (registration)
  'auth.register.professionalInfoTitle': 'Розкажіть про себе',
  'auth.register.professionalInfoSubtitle': 'Лише кілька деталей, щоб клієнти могли вас знайти',
  'auth.register.professionalTitleLabel': 'Ваша професійна посада',
  'auth.register.professionalTitlePlaceholder': 'напр. Сантехнік, Електрик, Прибиральник',
  'auth.register.professionalTitleError': 'Назва має бути щонайменше 3 символи',
  'auth.register.serviceCategories': 'Які послуги ви пропонуєте?',
  'auth.register.categoriesRequired': 'Оберіть принаймні одну категорію',
  'auth.register.selectCity': 'Ваше місто',
  'auth.register.cityRequired': 'Будь ласка, оберіть ваше місто',
  'auth.register.continueToAuth': 'Продовжити',
  'auth.register.backToProfessionalInfo': 'Назад',
  'auth.register.matchingCategories': 'Підбираємо відповідні категорії...',
  'auth.register.suggestedCategories': 'Підібрано для вас',
  'auth.register.browseAllCategories': 'Усі категорії',
  'auth.register.searchOrBrowse': 'Не знайшли свою категорію? Пошук або перегляд',
  'auth.register.applyingProfile': 'Налаштовуємо ваш профіль...',
  'auth.register.profileCreated': 'Профіль створено!',

  // Already logged in state
  'auth.register.alreadyLoggedInTitle': 'Гей, ви вже всередині!',
  'auth.register.alreadyLoggedInHello': 'З поверненням,',
  'auth.register.alreadyLoggedInMessage': 'Схоже, у вас вже є акаунт. Куди хочете перейти?',
  'auth.register.browseTasks': 'Знайти роботу',
  'auth.register.createTask': 'Створити завдання',
  'auth.register.setupProfessional': 'Налаштувати про профіль',
  'auth.register.browseProfessionals': 'Знайти спеціалістів',
};
