// Common UI terms and global actions
export const common = {
  welcome: 'Ласкаво просимо',
  login: 'Увійти',
  logout: 'Вийти',
  signup: 'Реєстрація',
  search: 'Пошук',
  browse: 'Переглянути',
  create: 'Створити',
  edit: 'Редагувати',
  delete: 'Видалити',
  cancel: 'Скасувати',
  dismiss: 'Можливо пізніше',
  ignore: 'Ігнорувати',
  important: 'Важливо',
  save: 'Зберегти',
  submit: 'Надіслати',
  loading: 'Завантаження...',
  error: 'Помилка',
  success: 'Успіх',
  back: 'Назад',
  next: 'Далі',
  previous: 'Назад',
  reviews: 'відгуків',
  close: 'Закрити',
  today: 'Сьогодні',
  yesterday: 'Вчора',
  application: 'заявка',
  applications: 'заявок',

  'common.optional': 'Необов\'язково',
  'common.close': 'Закрити',
  'common.ok': 'ОК',
  'common.days': 'днів',
  'common.cancel': 'Скасувати',
  'common.edit': 'Редагувати',
  'common.save': 'Зберегти',
  'common.anonymous': 'Анонімний користувач',
  'common.today': 'Сьогодні',
  'common.yesterday': 'Вчора',
  'common.reviews': 'відгуків',
  'common.tasksCompleted': 'виконаних завдань',
  'common.newProfessional': 'Новий в Trudify',

  // Countries
  'common.country.bulgaria': 'Болгарія',

  'language.en': 'English',
  'language.bg': 'Български',
  'language.ru': 'Русский',
  'language.ua': 'Українська',

  // Locations
  'locations.sofiaCenter': 'Софія, Центр',
  'locations.sofiaLyulin': 'Софія, Люлін',
  'locations.sofiaStudentski': 'Софія, Студентське містечко',
  'locations.sofiaVitosha': 'Софія, Вітоша',
  'locations.plovdiv': 'Пловдив',
  'locations.varna': 'Варна',
  'locations.burgas': 'Бургас',
  'locations.ruse': 'Русе',
  'locations.staraZagora': 'Стара Загора',

  // Cities (top 8 supported - MVP)
  'cities.sofia': 'Софія',
  'cities.plovdiv': 'Пловдив',
  'cities.varna': 'Варна',
  'cities.burgas': 'Бургас',
  'cities.ruse': 'Русе',
  'cities.staraZagora': 'Стара Загора',
  'cities.pleven': 'Плевен',
  'cities.sliven': 'Слівен',

  // Common messages
  'message.taskCreated': 'Завдання успішно створено!',
  'message.profileUpdated': 'Профіль успішно оновлено!',
  'message.applicationSubmitted': 'Заявку успішно надіслано!',
  'error.generic': 'Щось пішло не так. Спробуйте ще раз.',
  'error.network': 'Помилка мережі. Перевірте з\'єднання.',
  'error.unauthorized': 'Увійдіть, щоб отримати доступ до цієї сторінки.',

  // Empty states
  'common.noResults': 'Завдань не знайдено',
  'common.noResultsFilter': 'Спробуйте вибрати інший фільтр статусу',
  'common.clearFilters': 'Переглянути всі завдання',
  'common.errorGeneric': 'Щось пішло не так. Спробуйте ще раз.',

  // Safety & Trust Indicators
  'safety.phoneVerified': 'Телефон підтверджено',
  'safety.emailVerified': 'Email підтверджено',
  'safety.cleanRecord': 'Чиста репутація',
  'safety.hasNegativeReviews': 'Має негативні відгуки',
  'safety.multipleReports': 'Декілька скарг',
  'safety.negativeReviewsTooltip': 'Цей фахівець отримав кілька негативних відгуків. Будьте обережні.',
  'safety.multipleReportsTooltip': 'На цього фахівця надійшло кілька скарг від різних користувачів.',
  'safety.negativeReviewsWarning': 'Цей фахівець отримав кілька негативних відгуків',
  'safety.negativeReviewsWarningMessage': 'Декілька клієнтів повідомили про проблеми з якістю послуг. Уважно перегляньте відгуки та будьте обережні при наймі.',
  'safety.multipleReportsWarning': 'Попередження безпеки: Декілька скарг',
  'safety.multipleReportsWarningMessage': 'На цього фахівця надійшло кілька скарг від різних клієнтів. Рекомендуємо бути особливо обережними або обрати іншого фахівця.',

  // Review Visibility
  'reviews.hiddenReviewsNotice': 'Деякі відгуки приховано до перевірки',
  'reviews.hiddenReviewsTooltip': 'Низькі оцінки приховуються до виявлення закономірності для захисту від несправедливих поодиноких відгуків.',
  'reviews.hiddenCountSingular': '1 відгук приховано',
  'reviews.hiddenCountPlural': '{{count}} відгуків приховано',
  'reviews.patternDetected': 'Виявлено закономірність негативних відгуків',
  'reviews.allNegativeVisible': 'Усі негативні відгуки тепер видимі через виявлену закономірність проблем.',

  // Scam Reporting
  'report.button': 'Поскаржитись',
  'report.dialogTitle': 'Повідомити про проблему безпеки',
  'report.dialogDescription': 'Допоможіть нам підтримувати безпечну спільноту, повідомляючи про підозрілу поведінку або порушення правил.',
  'report.typeLabel': 'Тип проблеми',
  'report.descriptionLabel': 'Опис',
  'report.descriptionPlaceholder': 'Надайте конкретні деталі про проблему...',
  'report.evidenceLabel': 'Докази (необов\'язково)',
  'report.evidenceHint': 'Завантажте скріншоти або фото на підтвердження вашої скарги',
  'report.evidenceComingSoon': '(Скоро)',
  'report.submitButton': 'Надіслати скаргу',
  'report.cancelButton': 'Скасувати',
  'report.successMessage': 'Скаргу успішно надіслано. Наша команда розгляне її найближчим часом.',
  'report.errorMessage': 'Не вдалося надіслати скаргу. Спробуйте ще раз.',
  'report.falseReportWarning': 'Неправдиві скарги можуть призвести до дій щодо вашого акаунта. Надсилайте лише справжні скарги.',

  // Report Types
  'report.type.fraud_scam': 'Шахрайство або спроба обману',
  'report.type.threatening_behavior': 'Погрози або агресивна поведінка',
  'report.type.harassment': 'Переслідування або цькування',
  'report.type.identity_theft': 'Фальшивий профіль або крадіжка особистості',
  'report.type.poor_quality': 'Систематично низька якість роботи',
  'report.type.no_show': 'Неодноразова неявка',
  'report.type.other': 'Інша проблема безпеки',

  // Suspension
  'suspension.accountSuspended': 'Акаунт призупинено',
  'suspension.message': 'Цей акаунт тимчасово призупинено через численні скарги.',
  'suspension.appeal': 'Якщо ви вважаєте, що це помилка, можете оскаржити рішення електронною поштою.',
  'suspension.contactEmail': 'Контакт: support@taskbridge.com',

  // Notification Warning (Compact Chip)
  'notificationWarning.title': 'Важливо: Налаштуйте сповіщення',
  'notificationWarning.message': 'Ви не отримуватимете оновлення про заявки, повідомлення або зміни завдань без налаштованого каналу сповіщень.',
  'notificationWarning.recommendation': 'Рекомендуємо підключити Telegram для миттєвих сповіщень або підтвердити email як альтернативу.',
  'notificationWarning.compact': 'Налаштуйте сповіщення для отримання оновлень',
  'notificationWarning.setup': 'Налаштувати',
  'notificationWarning.connectTelegram': 'Підключити Telegram',
  'notificationWarning.verifyEmail': 'Підтвердити Email',
  'notificationWarning.dismiss': 'Зрозуміло',

  // Profanity Validation
  'validation.profanityDetected': 'Ваш текст містить неприпустиму лексику. Будь ласка, виправте.',
  'validation.profanityTitle': 'Назва завдання містить неприпустиму лексику',
  'validation.profanityDescription': 'Опис завдання містить неприпустиму лексику',
  'validation.profanityWarning': 'Деякі слова можуть бути позначені. Перевірте перед надсиланням.',
  'validation.profanitySeverity.mild': 'Будь ласка, уникайте неприпустимої лексики',
  'validation.profanitySeverity.moderate': 'Ваш текст містить образливу лексику, яка заборонена',
  'validation.profanitySeverity.severe': 'Ваш текст містить вкрай образливу лексику, що порушує правила спільноти',
};
