export const contentPages = {
  // About Page
  'about.hero.title': 'З\'єднуємо Болгарію з перевіреними фахівцями',
  'about.hero.subtitle': 'Ми віримо, що кожен заслуговує на доступ до надійних, перевірених спеціалістів для щоденних потреб.',

  'about.problem.title': 'Проблема, яку ми вирішуємо',
  'about.problem.description': 'Знайти надійну допомогу в Болгарії завжди було непросто. Рекомендації від знайомих обмежені, і немає простого способу перевірити якість фахівця перед наймом. Ми це змінюємо.',

  'about.solution.title': 'Наше рішення',
  'about.solution.description': 'Trudify - це платформа, яка з\'єднує клієнтів з перевіреними місцевими фахівцями. Кожен спеціаліст на нашій платформі перевірений, оцінений та має відгуки від реальних клієнтів.',

  'about.mission.title': 'Наша місія',
  'about.mission.description': 'Зробити пошук надійних фахівців простим, як кілька кліків, допомагаючи при цьому кваліфікованим працівникам будувати стійкий бізнес.',

  'about.values.title': 'Наші цінності',
  'about.values.trust': 'Довіра',
  'about.values.trustDesc': 'Кожен фахівець перевірений. Кожен відгук від реального клієнта.',
  'about.values.transparency': 'Прозорість',
  'about.values.transparencyDesc': 'Зрозумілі ціни, чесні відгуки, ніяких прихованих комісій.',
  'about.values.fairness': 'Справедливість',
  'about.values.fairnessDesc': 'Справедливі можливості для фахівців, справедливі ціни для клієнтів.',
  'about.values.quality': 'Якість',
  'about.values.qualityDesc': 'Ми встановлюємо високі стандарти і допомагаємо фахівцям їх досягати.',

  'about.stats.professionals': 'Перевірених фахівців',
  'about.stats.tasks': 'Виконаних завдань',
  'about.stats.cities': 'Міст',
  'about.stats.satisfaction': 'Задоволеність клієнтів',

  'about.cta.title': 'Готові почати?',
  'about.cta.subtitle': 'Приєднуйтесь до тисяч клієнтів та фахівців, які використовують Trudify сьогодні.',
  'about.cta.customer': 'Розмістити завдання',
  'about.cta.professional': 'Стати фахівцем',

  // How It Works Page
  'howItWorks.hero.title': 'Як працює Trudify',
  'howItWorks.hero.subtitle': 'Просто, безпечно і зрозуміло. Ось як це працює.',

  'howItWorks.customers.title': 'Для клієнтів',
  'howItWorks.customers.subtitle': 'Отримайте допомогу за 4 прості кроки',
  'howItWorks.customers.step1.title': 'Розмістіть завдання',
  'howItWorks.customers.step1.description': 'Опишіть, що вам потрібно, встановіть бюджет і розмістіть безкоштовно. Це займе менше 2 хвилин.',
  'howItWorks.customers.step2.title': 'Отримайте пропозиції',
  'howItWorks.customers.step2.description': 'Перевірені фахівці у вашому районі надішлють вам пропозиції. Порівняйте їх профілі, відгуки та ціни.',
  'howItWorks.customers.step3.title': 'Виберіть та обговоріть',
  'howItWorks.customers.step3.description': 'Виберіть фахівця, який найкраще підходить. Обговоріть деталі в чаті перед підтвердженням.',
  'howItWorks.customers.step4.title': 'Отримайте результат',
  'howItWorks.customers.step4.description': 'Фахівець виконує роботу. Платіть тільки коли задоволені результатом та залиште відгук.',

  'howItWorks.professionals.title': 'Для фахівців',
  'howItWorks.professionals.subtitle': 'Розвивайте бізнес з Trudify',
  'howItWorks.professionals.step1.title': 'Створіть профіль',
  'howItWorks.professionals.step1.description': 'Зареєструйтесь, підтвердіть особу та покажіть свої навички і роботи.',
  'howItWorks.professionals.step2.title': 'Переглядайте завдання',
  'howItWorks.professionals.step2.description': 'Знаходьте завдання у вашому районі, що відповідають навичкам. Фільтруйте за категорією, місцем та бюджетом.',
  'howItWorks.professionals.step3.title': 'Надсилайте пропозиції',
  'howItWorks.professionals.step3.description': 'Надсилайте конкурентні пропозиції клієнтам. Виділяйтесь профілем та відгуками.',
  'howItWorks.professionals.step4.title': 'Створюйте репутацію',
  'howItWorks.professionals.step4.description': 'Виконуйте завдання, збирайте відгуки та розвивайте бізнес. Найкращі фахівці отримують більше роботи.',
  'howItWorks.customers.learnMore': 'Дізнатись більше та дивитись відео гайди',
  'howItWorks.professionals.learnMore': 'Дізнатись більше та дивитись відео гайди',

  'howItWorks.cta.title': 'Готові почати?',
  'howItWorks.cta.subtitle': 'Потрібна допомога чи хочете запропонувати послуги - ми допоможемо.',

  // FAQ Page
  'faq.hero.title': 'Часті запитання',
  'faq.hero.subtitle': 'Відповіді на поширені питання про використання Trudify.',

  'faq.customers.title': 'Для клієнтів',
  'faq.customers.q1': 'Скільки коштує розмістити завдання?',
  'faq.customers.a1': 'Розміщення завдання на Trudify повністю безкоштовне. Ви платите фахівцю тільки після завершення роботи.',
  'faq.customers.q2': 'Як дізнатись, що фахівці надійні?',
  'faq.customers.a2': 'Всі фахівці на Trudify проходять верифікацію. Ви також бачите їх рейтинги, відгуки клієнтів та історію виконаних завдань.',
  'faq.customers.q3': 'Що якщо я не задоволений роботою?',
  'faq.customers.a3': 'У нас є процес вирішення спорів. Якщо ви не задоволені, зв\'яжіться з нами, і ми допоможемо вирішити питання.',
  'faq.customers.q4': 'Чи можна скасувати завдання?',
  'faq.customers.a4': 'Так, можна скасувати завдання до прийняття пропозиції. Після початку роботи умови скасування залежать від домовленості з фахівцем.',
  'faq.customers.q5': 'Як працює оплата?',
  'faq.customers.a5': 'Оплата домовляється напряму між вами та фахівцем. Рекомендуємо узгодити умови до початку роботи.',

  'faq.professionals.title': 'Для фахівців',
  'faq.professionals.q1': 'Як зареєструватись як фахівець?',
  'faq.professionals.a1': 'Створіть акаунт, заповніть профіль з навичками та досвідом, пройдіть верифікацію. Після підтвердження можете відгукуватись на завдання.',
  'faq.professionals.q2': 'Які комісії бере Trudify?',
  'faq.professionals.a2': 'Зараз Trudify безкоштовний для фахівців в період запуску. В майбутньому можлива невелика комісія за виконані завдання.',
  'faq.professionals.q3': 'Як отримати більше замовлень?',
  'faq.professionals.a3': 'Заповніть профіль, додайте фото робіт, швидко відповідайте на завдання, робіть якісно та збирайте відгуки. Найкращі фахівці показуються вище в пошуку.',
  'faq.professionals.q4': 'Чи можна працювати в кількох містах?',
  'faq.professionals.a4': 'Так, можете вказати кілька міст та районів в зоні обслуговування.',
  'faq.professionals.q5': 'Як працюють відгуки?',
  'faq.professionals.a5': 'Після виконання завдання клієнти можуть залишити відгук та оцінку. Вони відображаються в профілі та допомагають будувати репутацію.',

  'faq.general.title': 'Загальні питання',
  'faq.general.q1': 'Trudify працює в моєму місті?',
  'faq.general.a1': 'Trudify зараз працює у великих містах Болгарії: Софія, Пловдив, Варна, Бургас, Русе, Стара Загора, Плевен та Слівен. Скоро додамо більше міст.',
  'faq.general.q2': 'Які послуги доступні?',
  'faq.general.a2': 'Широкий спектр послуг: ремонт, прибирання, переїзд, IT-підтримка, репетиторство, косметичні послуги та багато іншого. Дивіться всі категорії на сайті.',
  'faq.general.q3': 'Як зв\'язатись з підтримкою?',
  'faq.general.a3': 'Напишіть на support@trudify.com або зверніться через соцмережі (посилання у футері). Зазвичай відповідаємо протягом 24 годин.',
  'faq.general.q4': 'Як отримувати сповіщення про нові завдання або відгуки?',
  'faq.general.a4': 'Підключіть Telegram у налаштуваннях профілю для безкоштовних миттєвих сповіщень. Спеціалісти отримують сповіщення про запрошення на завдання, а клієнти — коли спеціалісти відгукуються на їхні завдання.',

  'faq.resources.title': 'Корисні ресурси',
  'faq.resources.customerGuide': 'Гайд для клієнтів',
  'faq.resources.customerGuideDesc': 'Дивіться відео уроки про те, як публікувати завдання та наймати спеціалістів.',
  'faq.resources.professionalGuide': 'Гайд для спеціалістів',
  'faq.resources.professionalGuideDesc': 'Дізнайтесь, як знаходити роботу та розвивати бізнес на Trudify.',
  'faq.resources.blogPost': 'Шукаєте роботу?',
  'faq.resources.blogPostDesc': 'Читайте наш гайд з пошуку фріланс роботи в Болгарії.',
  'faq.resources.watchVideos': 'Дивитись відео',
  'faq.resources.readArticle': 'Читати статтю',

  'faq.cta.title': 'Залишились питання?',
  'faq.cta.subtitle': 'Наша підтримка готова допомогти.',
  'faq.cta.contact': 'Зв\'язатись з підтримкою',

  // For Professionals Page
  'forProfessionals.hero.title': 'Розвивайте бізнес з Trudify',
  'forProfessionals.hero.subtitle': 'Приєднуйтесь до тисяч фахівців, які знаходять нових клієнтів та будують репутацію.',
  'forProfessionals.hero.cta': 'Почати отримувати клієнтів',

  'forProfessionals.benefits.title': 'Чому Trudify?',
  'forProfessionals.benefits.noFees': 'Без початкових платежів',
  'forProfessionals.benefits.noFeesDesc': 'Реєстрація безкоштовна. Без підписки, без прихованих витрат. Ви платите тільки коли отримуєте роботу.',
  'forProfessionals.benefits.customers': 'Постійний потік клієнтів',
  'forProfessionals.benefits.customersDesc': 'Доступ до постійного потоку місцевих клієнтів, які шукають ваші послуги. Більше не потрібно чекати рекомендацій.',
  'forProfessionals.benefits.reputation': 'Створюйте репутацію',
  'forProfessionals.benefits.reputationDesc': 'Збирайте відгуки, показуйте роботи та створюйте професійну присутність в мережі, що працює на вас 24/7.',
  'forProfessionals.benefits.mobile': 'Працюйте на своїх умовах',
  'forProfessionals.benefits.mobileDesc': 'Вибирайте замовлення, встановлюйте свої ціни та керуйте всім з телефону.',

  'forProfessionals.howEarnings.title': 'Як працює заробіток',
  'forProfessionals.howEarnings.description': 'Ви встановлюєте свої ціни та домовляєтесь напряму з клієнтами. Trudify зараз безкоштовний для фахівців в період запуску.',

  'forProfessionals.videoGuides.title': 'Відео гайди',
  'forProfessionals.videoGuides.subtitle': 'Дивіться короткі уроки, щоб почати за кілька хвилин',
  'forProfessionals.videoGuides.video1.title': 'Початок роботи',
  'forProfessionals.videoGuides.video1.description': 'Як зареєструватись та налаштувати профіль фахівця',
  'forProfessionals.videoGuides.video2.title': 'Пошук роботи',
  'forProfessionals.videoGuides.video2.description': 'Як шукати завдання, подавати заявки та отримувати сповіщення',

  'forProfessionals.stats.title': 'Приєднуйтесь до зростаючої спільноти',

  'forProfessionals.cta.title': 'Готові почати заробляти?',
  'forProfessionals.cta.subtitle': 'Створіть профіль сьогодні та починайте знаходити клієнтів у вашому районі.',
  'forProfessionals.cta.button': 'Створити профіль фахівця',

  // For Customers Page
  'forCustomers.hero.title': 'Виконуйте справи з Trudify',
  'forCustomers.hero.subtitle': 'Знайдіть перевірених фахівців для будь-якого завдання. Розмістіть запит і отримайте пропозиції за хвилини.',
  'forCustomers.hero.cta': 'Розмістити перше завдання',

  'forCustomers.benefits.title': 'Чому клієнти обирають Trudify',
  'forCustomers.benefits.fast': 'Швидкий результат',
  'forCustomers.benefits.fastDesc': 'Розмістіть завдання та отримайте пропозиції за години. Більше ніякого нескінченного пошуку.',
  'forCustomers.benefits.verified': 'Перевірені фахівці',
  'forCustomers.benefits.verifiedDesc': 'Кожен фахівець перевірений. Дивіться їх рейтинги, відгуки та історію виконаних робіт.',
  'forCustomers.benefits.communicate': 'Легке спілкування',
  'forCustomers.benefits.communicateDesc': 'Спілкуйтесь напряму з фахівцями для обговорення деталей, узгодження ціни та підтвердження часу.',
  'forCustomers.benefits.reviews': 'Надійні відгуки',
  'forCustomers.benefits.reviewsDesc': 'Реальні відгуки від реальних клієнтів допомагають вибрати найкращого фахівця.',

  'forCustomers.howItWorks.title': 'Як це працює',
  'forCustomers.howItWorks.subtitle': 'Отримайте допомогу за 3 прості кроки',
  'forCustomers.howItWorks.step1.title': 'Розмістіть завдання',
  'forCustomers.howItWorks.step1.description': 'Опишіть, що вам потрібно. Займає 2 хвилини, повністю безкоштовно.',
  'forCustomers.howItWorks.step2.title': 'Отримайте відгуки',
  'forCustomers.howItWorks.step2.description': 'Фахівці відгукуються з ціною та досвідом. Ви обираєте.',
  'forCustomers.howItWorks.step3.title': 'Отримайте результат',
  'forCustomers.howItWorks.step3.description': 'Оберіть найкращого, домовтесь про деталі та платіть тільки коли задоволені.',

  'forCustomers.valueProposition.title': 'Досить шукати. Нехай вони знайдуть вас.',
  'forCustomers.valueProposition.description': 'На відміну від дошок оголошень, де ви телефонуєте по 10 номерів сподіваючись, що хтось відповість, на Trudify фахівці конкурують за ваше завдання. Ви розміщуєте, вони відгукуються, ви обираєте.',
  'forCustomers.valueProposition.free': '100% Безкоштовно для клієнтів',
  'forCustomers.valueProposition.freeDesc': 'Ніяких комісій, ніяких прихованих платежів. Ви платите тільки фахівцю за виконану роботу.',

  'forCustomers.privacy.title': 'Ваша конфіденційність захищена',
  'forCustomers.privacy.description': 'Ваш телефон та email приховані, поки ВИ не оберете фахівця. Тільки після прийняття заявки вони отримують ваші контакти. Ви контролюєте, хто може з вами зв\'язатись.',

  'forCustomers.faq.title': 'Часті запитання',
  'forCustomers.faq.q1': 'Це справді безкоштовно?',
  'forCustomers.faq.a1': 'Так, 100% безкоштовно. Ніяких комісій. Ви платите тільки фахівцю за його роботу.',
  'forCustomers.faq.q2': 'Як дізнатись, що фахівці надійні?',
  'forCustomers.faq.a2': 'У кожного фахівця є перевірені відгуки від реальних клієнтів, рейтинг та історія виконаних завдань. Ви бачите, кого наймаєте.',
  'forCustomers.faq.q3': 'Як швидко можна знайти допомогу?',
  'forCustomers.faq.a3': 'Більшість завдань отримують відгуки протягом годин. На термінові завдання часто відповідають того ж дня.',
  'forCustomers.faq.q4': 'Можна побачити ціни до вибору?',
  'forCustomers.faq.a4': 'Так! Кожен фахівець вказує ціну при відгуку. Порівняйте пропозиції та оберіть найкраще поєднання ціни, досвіду та відгуків.',

  'forCustomers.videoGuides.title': 'Відео гайди',
  'forCustomers.videoGuides.subtitle': 'Навчіться користуватись Trudify за кілька хвилин',
  'forCustomers.videoGuides.video1.title': 'Початок роботи',
  'forCustomers.videoGuides.video1.description': 'Як зареєструватись та розмістити перше завдання',
  'forCustomers.videoGuides.video2.title': 'Запросити фахівця',
  'forCustomers.videoGuides.video2.description': 'Як запросити конкретного фахівця до вашого завдання',
  'forCustomers.videoGuides.video3.title': 'Переглянути заявки',
  'forCustomers.videoGuides.video3.description': 'Як переглядати та приймати заявки',
  'forCustomers.videoGuides.video4.title': 'Залишити відгук',
  'forCustomers.videoGuides.video4.description': 'Як залишити відгук після завершення завдання',

  'forCustomers.stats.title': 'Приєднуйтесь до тисяч задоволених клієнтів',

  'forCustomers.cta.title': 'Готові почати?',
  'forCustomers.cta.subtitle': 'Розмістіть перше завдання безкоштовно і знайдіть ідеального фахівця сьогодні.',
  'forCustomers.cta.button': 'Розмістити завдання',

  // Pricing Page
  'pricing.hero.title': 'Просте і прозоре ціноутворення',
  'pricing.hero.subtitle': 'Ніяких прихованих комісій та сюрпризів. Ось як працюють ціни на Trudify.',

  'pricing.customers.title': 'Для клієнтів',
  'pricing.customers.free': 'Безкоштовно',
  'pricing.customers.description': 'Розміщення завдань завжди безкоштовне',
  'pricing.customers.feature1': 'Розміщуйте необмежено завдань',
  'pricing.customers.feature2': 'Отримуйте пропозиції від фахівців',
  'pricing.customers.feature3': 'Спілкуйтесь з фахівцями',
  'pricing.customers.feature4': 'Без оплати до завершення роботи',
  'pricing.customers.feature5': 'Залишайте відгуки після завершення',

  'pricing.professionals.title': 'Для фахівців',
  'pricing.professionals.free': 'Безкоштовно (Період запуску)',
  'pricing.professionals.description': 'Реєструйтесь та заробляйте без комісій',
  'pricing.professionals.feature1': 'Створіть профіль фахівця',
  'pricing.professionals.feature2': 'Переглядайте та відгукуйтесь на завдання',
  'pricing.professionals.feature3': 'Необмежені пропозиції',
  'pricing.professionals.feature4': 'Створюйте репутацію з відгуками',
  'pricing.professionals.feature5': 'Без комісії в період запуску',
  'pricing.professionals.note': 'Після періоду запуску можлива невелика комісія за виконані завдання. Поточні користувачі отримають пільгові умови.',

  'pricing.cta.title': 'Почніть сьогодні',
  'pricing.cta.subtitle': 'Приєднуйтесь до Trudify - найпростіший спосіб знайти допомогу або розвинути бізнес.',

  // Testimonials Page
  'testimonials.hero.title': 'Що кажуть користувачі',
  'testimonials.hero.subtitle': 'Реальні історії клієнтів та фахівців Trudify.',

  'testimonials.customers.title': 'Задоволені клієнти',
  'testimonials.professionals.title': 'Успішні фахівці',

  'testimonials.cta.title': 'Приєднуйтесь до спільноти',
  'testimonials.cta.subtitle': 'Станьте частиною тисяч задоволених користувачів.',

  // Giveaway Page
  'giveaway.hero.badge': 'Кожні 2 місяці',
  'giveaway.hero.title': 'Заробляйте та вигравайте призи!',
  'giveaway.hero.subtitle': 'Швидко знаходьте роботу, отримуйте гроші за свої навички та вигравайте цінні подарункові картки кожні два місяці.',
  'giveaway.hero.subtitleExtra': 'Приєднуйтесь до тисяч фахівців та клієнтів, які вже заробляють та вигрують на Trudify!',
  'giveaway.hero.totalPrizes': 'Загальний призовий фонд',
  'giveaway.hero.prizeCount': '10 подарункових карток',
  'giveaway.hero.ctaProfessional': 'Знайти роботу',
  'giveaway.hero.ctaCustomer': 'Розмістити завдання',

  'giveaway.whyTrudify.title': 'Чому Trudify?',
  'giveaway.whyTrudify.subtitle': 'Хочете швидко знайти роботу, заробити додаткові гроші чи отримати допомогу із завданнями - Trudify для вас. Плюс вигравайте призи просто за активність!',

  'giveaway.benefits.professionals.title': 'Для фахівців - знаходьте роботу та заробляйте',
  'giveaway.benefits.professionals.findWork.title': 'Швидко знаходьте роботу',
  'giveaway.benefits.professionals.findWork.description': 'Доступ до сотень місцевих замовлень. Більше не потрібно чекати дзвінків - робота приходить до вас!',
  'giveaway.benefits.professionals.earnMoney.title': 'Заробляйте більше',
  'giveaway.benefits.professionals.earnMoney.description': 'Встановлюйте свої ціни та заробляйте стільки, скільки заслуговуєте. Отримуйте оплату напряму від клієнтів.',
  'giveaway.benefits.professionals.growBusiness.title': 'Розвивайте бізнес',
  'giveaway.benefits.professionals.growBusiness.description': 'Створюйте репутацію завдяки відгукам. Найкращі фахівці отримують більше замовлень.',
  'giveaway.benefits.professionals.bonusRewards.title': 'Вигравайте бонуси',
  'giveaway.benefits.professionals.bonusRewards.description': 'Кожне виконане завдання - участь у розіграші. Більше роботи = більше шансів!',

  'giveaway.benefits.customers.title': 'Для клієнтів - отримуйте допомогу швидко',
  'giveaway.benefits.customers.fastHelp.title': 'Швидкі рішення',
  'giveaway.benefits.customers.fastHelp.description': 'Розмістіть завдання та отримайте пропозиції за години. Знайдіть потрібного фахівця швидко.',
  'giveaway.benefits.customers.verified.title': 'Перевірені фахівці',
  'giveaway.benefits.customers.verified.description': 'Всі фахівці перевірені. Читайте відгуки та вибирайте впевнено.',
  'giveaway.benefits.customers.fairPrices.title': 'Справедливі ціни',
  'giveaway.benefits.customers.fairPrices.description': 'Порівнюйте пропозиції та вибирайте найкращу. Без прихованих платежів.',
  'giveaway.benefits.customers.winPrizes.title': 'Вигравайте картки',
  'giveaway.benefits.customers.winPrizes.description': 'Розміщуйте завдання та вигравайте призи! Клієнти теж беруть участь у розіграші.',

  'giveaway.nextDraw.label': 'Наступний розіграш',
  'giveaway.nextDraw.date': 'Лютий 2026',
  'giveaway.nextDraw.frequency': 'Частота розіграшів',
  'giveaway.nextDraw.frequencyValue': 'Кожні 2 місяці',

  'giveaway.prizes.title': 'Призовий фонд',
  'giveaway.prizes.subtitle': '10 щасливчиків отримають подарункові картки від топових брендів. Будьте активними на Trudify і ви можете стати наступним!',
  'giveaway.prizes.grand': '1 місце',
  'giveaway.prizes.second': '2 місце',
  'giveaway.prizes.third': '3 місце',
  'giveaway.prizes.remaining': 'Місця 4-10',
  'giveaway.prizes.remainingValue': '7 x 20 EUR подарункових карток',
  'giveaway.prizes.sponsorNote': 'Бренди подарункових карток будуть оголошені ближче до дати розіграшу. Ми працюємо з преміум партнерами!',

  'giveaway.howItWorks.title': 'Як взяти участь',
  'giveaway.howItWorks.subtitle': 'Три прості кроки, щоб почати заробляти та вигравати',
  'giveaway.howItWorks.step1.title': 'Створіть безкоштовний профіль',
  'giveaway.howItWorks.step1.description': 'Зареєструйтесь за хвилини. Створіть профіль фахівця для пошуку роботи або розмістіть перше завдання як клієнт.',
  'giveaway.howItWorks.step2.title': 'Виконуйте завдання та заробляйте',
  'giveaway.howItWorks.step2.description': 'Фахівці: знаходьте та виконуйте роботу. Клієнти: розміщуйте завдання. Обидві сторони отримують шанси на виграш!',
  'giveaway.howItWorks.step3.title': 'Вигравайте автоматично',
  'giveaway.howItWorks.step3.description': 'Кожне виконане завдання - автоматичний шанс на виграш. Ніяких додаткових дій - просто працюйте та вигравайте!',

  'giveaway.seo.title': 'Почніть заробляти сьогодні в Болгарії',
  'giveaway.seo.paragraph1': 'Шукаєте роботу в Болгарії? Trudify з\'єднує кваліфікованих фахівців з місцевими клієнтами. Чи ви сантехнік, електрик, прибиральник, водій, IT-спеціаліст чи пропонуєте інші послуги - знаходьте роботу швидко та отримуйте гідну оплату.',
  'giveaway.seo.paragraph2': 'Потрібна допомога? Розмістіть завдання безкоштовно та отримайте пропозиції від перевірених фахівців у вашому районі. Від ремонту та прибирання до IT-підтримки та переїздів - знайдіть надійну допомогу в Софії, Пловдиві, Варні, Бургасі та інших містах Болгарії.',
  'giveaway.seo.paragraph3': 'Приєднуйтесь до Trudify сьогодні та станьте частиною зростаючої спільноти. Заробляйте, роблячи те, що любите, допомагайте людям у вашому районі та вигравайте призи. Чим активніші ви - тим більше можете заробити та виграти!',

  'giveaway.rules.title': 'Правила розіграшу',
  'giveaway.rules.rule1': 'Одне виконане завдання = один шанс у розіграші',
  'giveaway.rules.rule2': 'І фахівці, і клієнти можуть виграти',
  'giveaway.rules.rule3': 'Переможці вибираються випадково з усіх учасників',
  'giveaway.rules.rule4': 'Подарункові картки надсилаються електронно на email або Telegram',

  'giveaway.cta.title': 'Готові заробляти та вигравати?',
  'giveaway.cta.subtitle': 'Приєднуйтесь до тисяч фахівців та клієнтів на Trudify. Знаходьте роботу, отримуйте допомогу та вигравайте призи - все в одному місці!',
  'giveaway.cta.joinProfessional': 'Почати заробляти',
  'giveaway.cta.postTask': 'Розмістити перше завдання',
}
