// Navigation, header, and footer translations
export const navigation = {
  'nav.home': 'Головна',
  'nav.browseTasks': 'Завдання',
  'nav.createTask': 'Створити',
  'nav.profile': 'Профіль',
  'nav.profileCustomer': 'Профіль замовника',
  'nav.profileProfessional': 'Профіль фахівця',
  'nav.howItWorks': 'Як працює',
  'nav.categories': 'Категорії',
  'nav.forProfessionals': 'Фахівці',
  'nav.browseProfessionals': 'знайти виконавця',
  'nav.forCustomers': 'Для замовників',
  'nav.forClient': 'Для замовників',
  'nav.myTasks': 'Мої завдання',
  'nav.myPostedTasks': 'Мої завдання',
  'nav.myApplications': 'Мої заявки',
  'nav.myWork': 'Моя робота',
  'nav.tasksIPosted': 'завдання, які я опублікував',
  'nav.tasksIAmDoing': 'завдання, які я виконую',
  'nav.findProfessional': 'знайти фахівця',
  'nav.findAnotherTask': 'знайти інше завдання',
  'nav.language': 'Мова',
  'nav.general': 'Загальне',
  'nav.discover': 'Відкрити',
  'nav.closeMenu': 'Закрити меню',

  // Footer
  'footer.company.description':
    'Об\'єднуємо людей з кваліфікованими фахівцями для всіх видів послуг у Болгарії.',
  'footer.quickLinks.title': 'Швидкі посилання',
  'footer.quickLinks.howItWorks': 'Як працює',
  'footer.quickLinks.categories': 'Категорії',
  'footer.quickLinks.forProfessionals': 'Для фахівців',
  'footer.quickLinks.browseTasks': 'Переглянути завдання',
  'footer.quickLinks.createTask': 'Створити завдання',
  'footer.legal.title': 'Правові',
  'footer.legal.terms': 'Умови користування',
  'footer.legal.privacy': 'Політика конфіденційності',
  'footer.contact.title': 'Контакти',
  'footer.contact.subtitle': 'Зв\'яжіться з нами',
  'footer.language.label': 'Мова',
  'footer.copyright': '© 2025 Obod Soft LTD. Усі права захищено.',
};
