// Notifications, task detail, and posted tasks translations
export const notifications = {
  // Notifications
  'notifications.title': 'Сповіщення',
  'notifications.cleanup': 'Очистити',
  'notifications.markAsRead': 'Позначити як прочитане',
  'notifications.cleanupConfirm.title': 'Видалити всі сповіщення?',
  'notifications.cleanupConfirm.message': 'Усі сповіщення будуть видалені назавжди.',
  'notifications.cleanupConfirm.cancel': 'Скасувати',
  'notifications.cleanupConfirm.confirm': 'Видалити',
  'notifications.tabAll': 'Усі',
  'notifications.tabApplications': 'Заявки',
  'notifications.tabTasks': 'Завдання',
  'notifications.tabMessages': 'Повідомлення',
  'notifications.empty.title': 'Сповіщень поки немає',
  'notifications.empty.message': 'Ви отримаєте сповіщення, коли хтось подасть заявку на ваше завдання або відповість на вашу заявку.',
  'notifications.empty.filterMessage': 'Немає сповіщень у цій категорії.',
  'notifications.emptyUnread.title': 'Ви все прочитали!',
  'notifications.emptyUnread.message': 'Усі сповіщення прочитано.',
  'notifications.viewApplication': 'Переглянути заявку',
  'notifications.viewMyWork': 'Переглянути мою роботу',
  'notifications.viewTask': 'Переглянути завдання',
  'notifications.getStarted': 'Почати',
  'notifications.customerContact': 'Контактна інформація замовника',

  // Notification Content
  'notifications.content.welcome.title': 'Ласкаво просимо до Trudify!',
  'notifications.content.welcome.message': 'Ваш обліковий запис успішно створено. Почніть з публікації завдання або перегляду можливостей для роботи!',
  'notifications.content.applicationReceived.title': 'Нова заявка',
  'notifications.content.applicationReceived.message': '{{professionalName}} подав заявку на ваше завдання "{{taskTitle}}"',
  'notifications.content.applicationAccepted.title': 'Заявку прийнято! 🎉',
  'notifications.content.applicationAccepted.message': 'Вашу заявку на "{{taskTitle}}" прийнято {{customerName}}',
  'notifications.content.applicationRejected.title': 'Оновлення заявки',
  'notifications.content.applicationRejected.message': 'Вашу заявку на "{{taskTitle}}" цього разу не обрано. Продовжуйте подавати заявки!',
  'notifications.content.taskCompleted.title': 'Завдання виконано - потрібен відгук ⭐',
  'notifications.content.taskCompleted.message': '"{{taskTitle}}" завершено! Будь ласка, залиште відгук про роботу {{professionalName}}.',
  'notifications.content.professionalWithdrew.title': 'Фахівець відмовився',
  'notifications.content.professionalWithdrew.message': '{{professionalName}} відмовився від вашого завдання "{{taskTitle}}". Ваше завдання тепер відкрите для нових заявок.',
  'notifications.content.removedByCustomer.title': 'Замовник видалив вас із завдання',
  'notifications.content.removedByCustomer.message': 'Вас видалено із завдання "{{taskTitle}}" замовником.',
  'notifications.content.taskCancelled.title': 'Завдання скасовано',
  'notifications.content.taskCancelled.message': 'Завдання "{{taskTitle}}" скасовано клієнтом',

  // Telegram templates
  'notifications.telegram.viewHere': 'Переглянути тут',
  'notifications.telegram.welcome': '👋 <b>Ласкаво просимо до Trudify, {{userName}}!</b>\n\n🎉 Вітаємо! Ваш обліковий запис успішно створено.\n\n✅ Ви отримуватимете миттєві сповіщення тут про:\n• Нові заявки на ваші завдання\n• Повідомлення від фахівців\n• Оновлення та завершення завдань\n\nПочніть зараз:\n📝 Опублікуйте завдання або\n💼 Перегляньте можливості для роботи!',
  'notifications.telegram.applicationReceived': '✅ <b>Нова заявка!</b>\n\n<b>{{professionalName}}</b> подав заявку на ваше завдання:\n"{{taskTitle}}"\n\n{{link}}',
  'notifications.telegram.applicationAccepted': '🎉 <b>Заявку прийнято!</b>\n\nВашу заявку на "{{taskTitle}}" прийнято {{customerName}}!\n\n<b>Контактна інформація:</b>\n{{customerContact}}\n\n{{link}}',
  'notifications.telegram.taskCompleted': '✅ <b>Завдання виконано - потрібен відгук!</b>\n\nВаше завдання "<b>{{taskTitle}}</b>" виконав {{professionalName}}.\n\n⭐ <b>Будь ласка, залиште відгук</b>, щоб допомогти іншим знайти чудових фахівців.\n\n{{link}}',
  'notifications.telegram.professionalWithdrew': '⚠️ <b>Фахівець відмовився</b>\n\n<b>{{professionalName}}</b> відмовився від вашого завдання:\n"{{taskTitle}}"\n\n📋 Ваше завдання тепер <b>знову відкрите</b> для нових заявок.\n\n👉 <b>Наступні кроки:</b>\n• Перегляньте деталі завдання\n• Перевірте конкурентність бюджету\n• Швидко відповідайте на нові заявки\n\n🔗 Переглянути завдання: {{link}}',
  'notifications.telegram.removedByCustomer': '⚠️ <b>Замовник видалив вас із завдання</b>\n\nВас видалено із завдання:\n"<b>{{taskTitle}}</b>"\n\n📋 Завдання <b>знову відкрите</b> для нових заявок.\n\n👉 <b>Наступні кроки:</b>\n• Перегляньте інші доступні завдання\n• Подавайте заявки на завдання, що відповідають вашим навичкам\n• Зосередьтеся на побудові позитивних відносин із клієнтами\n\n🔗 Переглянути завдання: {{link}}',
  'notifications.telegram.taskCancelled': '❌ <b>Завдання скасовано</b>\n\nЗавдання "{{taskTitle}}" скасовано клієнтом.\n\nВашу заявку та всі обговорення, пов\'язані з цим завданням, видалено.\n\n👉 <b>Наступні кроки:</b>\n• Перегляньте інші доступні завдання\n• Подавайте заявки на завдання, що відповідають вашим навичкам\n\n🔗 Переглянути завдання: {{link}}',
  'notifications.telegram.taskInvitation': '🎯 <b>Нове запрошення на завдання!</b>\n\n<b>{{customerName}}</b> запрошує вас подати заявку на завдання:\n\n📋 <b>{{taskTitle}}</b>\n🏷️ Категорія: {{taskCategory}}\n\n👉 Переглянути та подати заявку тут:\n{{link}}',

  // Task Detail
  'taskDetail.backToTasks': 'Назад до завдань',
  'taskDetail.requirements': 'Вимоги:',
  'taskDetail.keyInformation': 'Ключова інформація',
  'taskDetail.client': 'Автор завдання',
  'taskDetail.loginForMore': 'Увійдіть для більше',
  'taskDetail.loginMessage': 'Увійдіть, щоб побачити повну інформацію',
  'taskDetail.completedTasks': 'виконаних завдань',
  'taskDetail.memberSince': 'Учасник з',
  'taskDetail.similarTasks': 'Схожі завдання',
  'taskDetail.apply': 'Подати заявку',
  'taskDetail.askQuestion': 'Поставити запитання',
  'taskDetail.applicationsCount': 'заявок',
  'taskDetail.timeAgo': 'тому',
  'taskDetail.today': 'Сьогодні',
  'taskDetail.tomorrow': 'Завтра',
  'taskDetail.days': 'днів',
  'taskDetail.flexible': 'Гнучко',
  'taskDetail.asap': 'Якнайшвидше',
  'taskDetail.negotiable': 'За домовленістю',
  'taskDetail.urgency.same_day': 'Терміново - сьогодні',
  'taskDetail.urgency.within_week': 'Протягом тижня',
  'taskDetail.urgency.flexible': 'Гнучкий термін',
  'taskDetail.urgency.default': 'Не вказано',
  'taskDetail.status': 'Статус',
  'taskDetail.statusTypes.vacant': 'Вакантне',
  'taskDetail.statusTypes.applied': 'Подано заявку',
  'taskDetail.statusTypes.inProgress': 'У роботі',
  'taskDetail.statusTypes.done': 'Виконано',
  'taskDetail.statusTypes.archived': 'В архіві',
  'taskDetail.appliedTooltip': 'Ви подали заявку на це завдання. Клієнт може прийняти або відхилити вашу заявку.',
  'taskDetail.inProgressBanner.title': 'Завдання більше недоступне',
  'taskDetail.inProgressBanner.message': 'Це завдання зараз виконується фахівцем і більше не приймає заявки.',
  'taskDetail.published.today': 'опубліковано сьогодні',
  'taskDetail.published.thisWeek': 'опубліковано цього тижня',
  'taskDetail.published.thisMonth': 'опубліковано цього місяця',
  'taskDetail.published.someTimeAgo': 'опубліковано раніше',

  // Translation indicator
  'taskDetail.originallyWrittenIn': 'Спочатку написано',

  'taskDetail.share': 'Поділитися',
  'taskDetail.shareText': 'Подивіться це завдання на Trudify',
  'taskDetail.shareSuccess': 'Успішно поділилися!',
  'taskDetail.linkCopied': 'Посилання скопійовано!',
  'taskDetail.copyError': 'Не вдалося скопіювати посилання',
  'taskDetail.editTask': 'Редагувати завдання',
  'taskDetail.cancelTask': 'Скасувати завдання',
  'taskDetail.confirmCancel': 'Ви впевнені, що хочете скасувати це завдання?',
  'taskDetail.cancelSuccess': 'Завдання успішно скасовано',
  'taskDetail.cancelError': 'Не вдалося скасувати завдання',
  'taskDetail.cancelDialog.title': 'Скасувати це завдання?',
  'taskDetail.cancelDialog.warning': 'Цю дію не можна скасувати, вона:',
  'taskDetail.cancelDialog.consequence1': 'Видалить усі заявки',
  'taskDetail.cancelDialog.consequence1NoApps': 'Видалить завдання (заявок ще немає)',
  'taskDetail.cancelDialog.consequence2': 'Видалить завдання з результатів пошуку',
  'taskDetail.cancelDialog.consequence3': 'Назавжди видалить усі дані завдання',
  'taskDetail.cancelDialog.confirm': 'Ви впевнені, що хочете скасувати це завдання?',
  'taskDetail.cancelDialog.btnCancel': 'Скасувати',
  'taskDetail.cancelDialog.btnConfirm': 'Так, скасувати завдання',
  'taskDetail.cancelDialog.processing': 'Скасування...',
  'taskDetail.activity': 'Активність завдання',
  'taskDetail.applications': 'Заявки',
  'taskDetail.questions': 'Запитання',
  'taskDetail.accept': 'Прийняти',
  'taskDetail.reject': 'Відхилити',
  'taskDetail.message': 'Повідомлення',
  'taskDetail.reply': 'Відповісти',
  'taskDetail.yourReply': 'Ваша відповідь:',
  'taskDetail.price': 'Ціна',
  'taskDetail.timeline': 'Термін',
  'taskDetail.tasks': 'завдань',
  'taskDetail.cancel': 'Скасувати',
  'taskDetail.writeReply': 'Напишіть відповідь...',
  'taskDetail.sendReply': 'Надіслати відповідь',

  // Language Barrier Warning
  'taskDetail.languageWarning.title': 'Мовна примітка',
  'taskDetail.languageWarning.message': 'Це завдання опубліковане людиною, яка може надавати перевагу спілкуванню {{language}}. Будь ласка, переконайтеся, що вам комфортно з можливими мовними відмінностями перед подачею заявки.',
  'taskDetail.languageWarning.confirm': 'Зрозуміло, продовжити',
  'taskDetail.languageWarning.cancel': 'Скасувати',

  // Ask Question Dialog
  'taskDetail.askQuestionDialog.title': 'Поставити запитання',
  'taskDetail.askQuestionDialog.placeholder': 'Що б ви хотіли дізнатися про це завдання?',
  'taskDetail.askQuestionDialog.submit': 'Опублікувати запитання',
  'taskDetail.askQuestionDialog.characterCount': '{{current}}/{{max}} символів',
  'taskDetail.askQuestionDialog.minLength': 'Запитання має містити щонайменше {{min}} символів',
  'taskDetail.askQuestionDialog.maxLength': 'Запитання має містити не більше {{max}} символів',

  // Questions Section
  'taskDetail.questions.empty.title': 'Запитань поки немає',
  'taskDetail.questions.empty.message': 'Будьте першим, хто поставить запитання про це завдання!',
  'taskDetail.questions.unanswered': 'Без відповіді',
  'taskDetail.questions.answered': 'З відповіддю',
  'taskDetail.questions.loading': 'Завантаження запитань...',

  // Answer Dialog
  'taskDetail.answerDialog.title': 'Відповісти на запитання',
  'taskDetail.answerDialog.placeholder': 'Напишіть свою відповідь...',

  // Success/Error Messages
  'taskDetail.questionPosted': 'Ваше запитання успішно опубліковано!',
  'taskDetail.questionError': 'Не вдалося опублікувати запитання. Спробуйте ще раз.',
  'taskDetail.answerPosted': 'Вашу відповідь успішно опубліковано!',
  'taskDetail.answerError': 'Не вдалося опублікувати відповідь. Спробуйте ще раз.',

  // Not Found Page
  'taskDetail.notFound.title': 'Завдання не знайдено',
  'taskDetail.notFound.description': 'Завдання, яке ви шукаєте, не існує або було видалено.',
  'taskDetail.notFound.browseTasks': 'Переглянути завдання',

  // Error Page
  'taskDetail.error.title': 'Щось пішло не так!',
  'taskDetail.error.description': 'Не вдалося завантажити це завдання. Це може бути тимчасова проблема.',
  'taskDetail.error.retry': 'Спробувати знову',
  'taskDetail.error.goHome': 'На головну',

  // Posted Tasks Page
  'postedTasks.title': 'Мої опубліковані завдання',
  'postedTasks.subtitle': 'Керуйте завданнями, які ви створили',
  'postedTasks.loading': 'Завантаження ваших завдань...',
  'postedTasks.createTask': 'Створити завдання',
  'postedTasks.filter.all': 'Усі',
  'postedTasks.filter.open': 'Відкриті',
  'postedTasks.filter.inProgress': 'У роботі',
  'postedTasks.filter.awaitingConfirmation': 'Очікують підтвердження',
  'postedTasks.filter.completed': 'Завершені',
  'postedTasks.filter.cancelled': 'Скасовані',
  'postedTasks.applicationsCount': '{{count}} заявок',
  'postedTasks.viewApplications': 'Переглянути заявки',
  'postedTasks.viewDetails': 'Деталі',
  'postedTasks.editTask': 'Редагувати',
  'postedTasks.acceptedProfessional': 'Прийнятий фахівець',
  'postedTasks.completedBy': 'Виконано фахівцем',
  'postedTasks.awaitingYourConfirmation': 'Очікує вашого підтвердження',
  'postedTasks.markedComplete': 'позначив це завдання як виконане',
  'postedTasks.markComplete': 'Позначити як виконане',
  'postedTasks.reportIssue': 'Повідомити про проблему',
  'postedTasks.cancelTask': 'Скасувати завдання',
  'postedTasks.cancelTaskConfirm': 'Ви впевнені, що хочете скасувати це завдання? Фахівця буде повідомлено.',
  'postedTasks.reopenTask': 'Відновити завдання',
  'postedTasks.reopenTaskConfirm': 'Відновити це завдання? Ви зможете переглянути та відредагувати деталі перед повторною публікацією.',
  'postedTasks.empty.title': 'Є ідея? Давайте втілимо! 💡',
  'postedTasks.empty.description': 'Ваша дошка завдань порожня та готова до дій. Від ремонту будинку до творчих проєктів - фахівці чекають, щоб допомогти.',
  'postedTasks.empty.subtext': 'Опублікуйте перше завдання менш ніж за 2 хвилини. Це безкоштовно, просто, і ви одразу почнете отримувати заявки!',
  'postedTasks.empty.createButton': 'Створити завдання',
  'postedTasks.empty.hint': '✨ Порада: чим більше деталей ви надасте, тим кращі заявки отримаєте',
  'postedTasks.firstApplication.title': 'Чудові новини! Ви отримали першу заявку',
  'postedTasks.firstApplication.message': 'Перегляньте деталі заявки та дайте відповідь фахівцю',

  // Cancel Task Dialog
  'cancelTask.title': 'Скасувати завдання',
  'cancelTask.professional': 'Фахівець',
  'cancelTask.professionalNotification': 'Фахівця буде повідомлено про скасування',
  'cancelTask.reasonLabel': 'Чому ви скасовуєте це завдання?',
  'cancelTask.reasons.noShow': 'Фахівець не з\'явився',
  'cancelTask.reasons.abandoned': 'Фахівець покинув роботу',
  'cancelTask.reasons.unresponsive': 'Фахівець не відповідає',
  'cancelTask.reasons.changedRequirements': 'Мої вимоги змінилися',
  'cancelTask.reasons.foundAlternative': 'Знайшов інше рішення',
  'cancelTask.reasons.other': 'Інша причина',
  'cancelTask.descriptionLabel': 'Додаткові деталі (необов\'язково)',
  'cancelTask.descriptionPlaceholder': 'Надайте додатковий контекст...',
  'cancelTask.descriptionHint': 'Допоможіть нам зрозуміти, що сталося',
  'cancelTask.confirmButton': 'Скасувати завдання',
  'cancelTask.rateLimit.title': 'Ви можете скасувати ще {{remaining}} завдання цього місяця',
  'cancelTask.rateLimit.message': 'Для запобігання зловживанням користувачі можуть скасовувати до {{max}} завдань на місяць',
  'cancelTask.rateLimit.lastWarning': 'Це ваше останнє безкоштовне скасування цього місяця!',
  'cancelTask.limitExceeded.title': 'Місячний ліміт скасувань вичерпано',
  'cancelTask.limitExceeded.message': 'Ви досягли ліміту скасувань цього місяця. Зверніться до служби підтримки, якщо потрібна допомога.',

  // Customer Remove Professional Dialog
  'customerRemove.title': 'Видалити фахівця із завдання',
  'customerRemove.subtitle': 'Видалення з: {{taskTitle}}',
  'customerRemove.professional': 'Фахівець',
  'customerRemove.acceptedOn': 'Прийнято',
  'customerRemove.workingFor': 'Працює',
  'customerRemove.professionalNotification': 'Фахівця буде повідомлено, а ваше завдання знову відкриється для нових заявок',
  'customerRemove.taskWillReopen': 'Ваше завдання знову відкриється для нових заявок',
  'customerRemove.limitWarning.title': 'Ви можете видалити ще {{remaining}} фахівців цього місяця',
  'customerRemove.limitWarning.message': 'Замовники можуть видаляти до {{max}} фахівців на місяць.',
  'customerRemove.limitExceeded.title': 'Місячний ліміт видалень вичерпано',
  'customerRemove.limitExceeded.message': 'Ви досягли ліміту видалень цього місяця. Зверніться до служби підтримки.',
  'customerRemove.reasonLabel': 'Чому ви видаляєте цього фахівця?',
  'customerRemove.reasons.professional_unresponsive': 'Фахівець не відповідає на повідомлення',
  'customerRemove.reasons.professional_no_show': 'Фахівець пропустив заплановані зустрічі',
  'customerRemove.reasons.quality_concerns': 'Якість роботи не відповідає стандартам',
  'customerRemove.reasons.safety_issues': 'Занепокоєння щодо безпеки робіт',
  'customerRemove.reasons.timeline_issue': 'Не може встигнути до мого терміну',
  'customerRemove.reasons.scope_disagreement': 'Розбіжності щодо обсягу або ціни',
  'customerRemove.reasons.my_circumstances_changed': 'Мої обставини змінилися',
  'customerRemove.reasons.mutual_agreement': 'Взаємна згода припинити співпрацю',
  'customerRemove.reasons.other': 'Інша причина',
  'customerRemove.descriptionLabel': 'Додаткові деталі (необов\'язково)',
  'customerRemove.descriptionPlaceholder': 'Поясніть ситуацію...',
  'customerRemove.descriptionHint': 'Це допоможе нам покращити платформу',
  'customerRemove.confirmButton': 'Видалити фахівця',
  'postedTasks.removeProfessional': 'Видалити фахівця',
  'postedTasks.removeProfessionalSuccess': 'Фахівця видалено. Завдання знову відкрите для нових заявок.',
  'postedTasks.cannotRemove': 'Неможливо видалити',
  'postedTasks.markCompleteSuccess': 'Завдання успішно позначено як виконане!',
  'postedTasks.markCompleteSuccessDescription': 'Фахівця повідомлено.',
  'postedTasks.markCompleteError': 'Не вдалося позначити завдання як виконане',

  // Edit Task Page
  'editTask.title': 'Редагувати завдання',
  'editTask.subtitle': 'Оновіть деталі завдання, щоб залучити більше фахівців',
  'editTask.editingBanner': 'Редагування: {{title}}',
  'editTask.editingSubtext': 'Внесіть зміни для покращення завдання',
  'editTask.help': 'Потрібна допомога? Зверніться до служби підтримки',
  'editTask.freeToEdit': 'Безкоштовне редагування',
  'editTask.noPayment': 'Без оплати до початку роботи',
  'editTask.instantSave': 'Зміни зберігаються миттєво',
  'editTask.prosWillSee': 'Фахівці побачать оновлення',
  'editTask.savingChanges': 'Збереження змін...',
  'editTask.saveChanges': 'Зберегти зміни',
  'editTask.cancelEdit': 'Скасувати',
  'editTask.successMessage': 'Завдання успішно оновлено!',
  'editTask.errorMessage': 'Помилка оновлення завдання. Спробуйте ще раз.',
  'editTask.cachingNotice': 'Примітка: зміни можуть з\'явитися на публічній сторінці завдання протягом 1 години.',
  'editTask.imageUpload.error': 'Помилка завантаження зображення',

  // Task Hints System
  'taskHints.noApplications.title': 'Немає заявок? Ваше завдання відкрите {{days}} днів',
  'taskHints.improveTask': 'Покращити завдання',
  'taskHints.dismiss': 'Закрити',
  'taskHints.suggestions.increasePrice': 'Спробуйте збільшити бюджет, щоб залучити більше фахівців',
  'taskHints.suggestions.addPhotos': 'Додайте або оновіть фото, щоб краще показати, що потрібно зробити',
  'taskHints.suggestions.improveDescription': 'Додайте більше деталей до опису для ясності',
  'taskHints.suggestions.adjustDeadline': 'Розгляньте можливість зробити термін більш гнучким',
  'taskHints.suggestions.updateTask': 'Перегляньте та оновіть деталі завдання для більшої привабливості',

  // Email Notification Templates
  'notifications.email.applicationReceived.subject': '{{customer_name}}, у вас нова заявка!',
  'notifications.email.applicationReceived.heading': 'Отримано нову заявку!',
  'notifications.email.applicationReceived.message': '{{professional_name}} подав заявку на ваше завдання "{{task_title}}". Перегляньте профіль, відгуки та деталі пропозиції.',
  'notifications.email.applicationReceived.buttonText': 'Переглянути заявку',
  'notifications.email.applicationReceived.secondaryButtonText': 'Переглянути профіль',
  'notifications.email.applicationReceived.infoTitle': 'Деталі заявки:',
  'notifications.email.applicationReceived.footerText': 'Ви отримали цей лист, тому що опублікували завдання на Trudify.',

  'notifications.email.applicationAccepted.subject': 'Вашу заявку прийнято!',
  'notifications.email.applicationAccepted.heading': 'Вітаємо! Заявку прийнято',
  'notifications.email.applicationAccepted.message': 'Вашу заявку на "{{task_title}}" прийнято {{customer_name}}!',
  'notifications.email.applicationAccepted.buttonText': 'Переглянути мою роботу',
  'notifications.email.applicationAccepted.infoTitle': 'Контактна інформація замовника:',
  'notifications.email.applicationAccepted.secondaryMessage': 'Почніть роботу над завданням та підтримуйте зв\'язок із замовником.',
  'notifications.email.applicationAccepted.footerText': 'Ви отримали цей лист, тому що подали заявку на завдання на Trudify.',
  'notifications.email.applicationAccepted.customerMessageLabel': 'Повідомлення',
  'notifications.email.applicationAccepted.contactLabel': 'Контакт',

  'notifications.email.applicationRejected.subject': 'Оновлення заявки на "{{task_title}}"',
  'notifications.email.applicationRejected.heading': 'Заявку не прийнято',
  'notifications.email.applicationRejected.message': 'Вашу заявку на "{{task_title}}" цього разу не прийнято. Не засмучуйтеся! Продовжуйте подавати заявки на інші можливості.',
  'notifications.email.applicationRejected.buttonText': 'Переглянути інші завдання',
  'notifications.email.applicationRejected.secondaryMessage': 'Пам\'ятайте: кожна заявка - це досвід. Аналізуйте відгуки та продовжуйте покращуватися!',
  'notifications.email.applicationRejected.footerText': 'Ви отримали цей лист, тому що подали заявку на завдання на Trudify.',

  'notifications.email.messageReceived.subject': 'Нове повідомлення від {{sender_name}}',
  'notifications.email.messageReceived.heading': 'У вас нове повідомлення',
  'notifications.email.messageReceived.message': '{{sender_name}} надіслав вам повідомлення про "{{task_title}}"',
  'notifications.email.messageReceived.buttonText': 'Переглянути повідомлення',
  'notifications.email.messageReceived.infoTitle': 'Попередній перегляд повідомлення:',
  'notifications.email.messageReceived.secondaryMessage': 'Відповідайте швидко для підтримки доброї комунікації та довіри.',
  'notifications.email.messageReceived.footerText': 'Ви отримали цей лист, тому що берете участь у завданні на Trudify.',

  'notifications.email.taskCompleted.subject': 'Завдання виконано: "{{task_title}}"',
  'notifications.email.taskCompleted.heading': 'Завдання успішно виконано!',
  'notifications.email.taskCompleted.message': 'Завдання "{{task_title}}" позначено як виконане. Будь ласка, оцініть свій досвід та допоможіть створити довіру у спільноті.',
  'notifications.email.taskCompleted.buttonText': 'Залишити відгук',
  'notifications.email.taskCompleted.secondaryMessage': 'Ваш відгук допоможе іншим користувачам знайти чудових фахівців та покращить спільноту Trudify.',
  'notifications.email.taskCompleted.footerText': 'Ви отримали цей лист, тому що брали участь у завданні на Trudify.',

  'notifications.email.paymentReceived.subject': 'Отримано оплату за "{{task_title}}"',
  'notifications.email.paymentReceived.heading': 'Оплату отримано!',
  'notifications.email.paymentReceived.message': 'Ви отримали {{amount}} BGN за виконання "{{task_title}}". Продовжуйте чудову роботу!',
  'notifications.email.paymentReceived.buttonText': 'Переглянути баланс',
  'notifications.email.paymentReceived.infoTitle': 'Деталі оплати:',
  'notifications.email.paymentReceived.secondaryMessage': 'Заробіток доступний у вашому профілі. Продовжуйте надавати відмінний сервіс, щоб заробляти більше!',
  'notifications.email.paymentReceived.footerText': 'Ви отримали цей лист, тому що виконали завдання на Trudify.',

  'notifications.email.welcome.subject': 'Ласкаво просимо до Trudify, {{user_name}}!',
  'notifications.email.welcome.heading': 'Ласкаво просимо до Trudify!',
  'notifications.email.welcome.message': 'Вітаємо! Ваш обліковий запис успішно створено.',
  'notifications.email.welcome.buttonText': 'Почати',
  'notifications.email.welcome.infoTitle': 'Що ви можете робити на Trudify:',
  'notifications.email.welcome.secondaryMessage': 'Потрібна допомога? Перегляньте наші посібники або зверніться до підтримки.',
  'notifications.email.welcome.footerText': 'Ви отримали цей лист, тому що створили обліковий запис на Trudify.',

  'notifications.email.removedFromTask.subject': 'Оновлення завдання: "{{task_title}}"',
  'notifications.email.removedFromTask.heading': 'Вас видалено із завдання',
  'notifications.email.removedFromTask.message': 'Вас видалено із завдання "{{task_title}}" замовником. Завдання тепер відкрите для інших фахівців.',
  'notifications.email.removedFromTask.buttonText': 'Переглянути інші завдання',
  'notifications.email.removedFromTask.secondaryMessage': 'Це не впливає на ваш рейтинг, якщо немає занепокоєнь щодо якості чи безпеки. Якщо маєте запитання, зверніться до підтримки.',
  'notifications.email.removedFromTask.footerText': 'Ви отримали цей лист, тому що працювали над завданням на Trudify.',

  'notifications.email.taskInvitation.subject': '{{customer_name}} запрошує вас на завдання!',
  'notifications.email.taskInvitation.heading': 'Вас запросили на завдання!',
  'notifications.email.taskInvitation.message': '{{customer_name}} запрошує вас подати заявку на завдання в категорії {{task_category}}.',
  'notifications.email.taskInvitation.buttonText': 'Переглянути та подати заявку',
  'notifications.email.taskInvitation.infoTitle': 'Деталі завдання:',
  'notifications.email.taskInvitation.secondaryMessage': 'Вас обрали на основі ваших навичок та відгуків. Подайте заявку зараз, поки завдання не зайняте!',
  'notifications.email.taskInvitation.footerText': 'Ви отримали цей лист, тому що вас запросили подати заявку на завдання на Trudify.',

  // Common Email Elements
  'notifications.email.common.greeting': 'Привіт',
  'notifications.email.common.footerRights': 'Усі права захищено.',
};
