// Professionals page and professional detail translations
export const professionals = {
  'professionals.hero.title': 'Знайдіть перевірених фахівців',
  'professionals.hero.subtitle':
    'Переглядайте верифікованих спеціалістів за категорією та знайдіть ідеальний варіант',
  'professionals.hero.badge': 'Мережа фахівців',
  'professionals.hero.stats.verified.value': 'Перевірені фахівці',
  'professionals.hero.stats.verified.label': 'Щодня стає більше',
  'professionals.hero.stats.ratings.value': 'Надійна якість',
  'professionals.hero.stats.ratings.label':
    'На основі реальних оцінок та відгуків',
  'professionals.hero.stats.jobs.value': 'Активна мережа',
  'professionals.hero.stats.jobs.label': 'Щодня виконується багато завдань',
  'professionals.searchPlaceholder':
    'Шукайте категорії... (напр., ремонт, прибирання, репетитор)',
  'professionals.search.popular': 'Популярне',
  'professionals.search.categories': 'Категорії послуг',
  'professionals.allCategories': 'Усі категорії',
  'professionals.featuredTitle': 'Рекомендовані фахівці',
  'professionals.viewProfile': 'Переглянути профіль',
  'professionals.suggestTask': 'Запропонувати завдання',
  'professionals.viewProfessionals': 'Переглянути фахівців',
  'professionals.rating': 'Рейтинг',
  'professionals.completedJobs': 'Виконаних завдань',
  'professionals.card.completedJobs': 'виконаних завдань',
  'professionals.card.completedJobsShort': 'завдань',
  'professionals.card.lookingForFirstTask': 'Готовий до завдання',
  'professionals.card.waitingForReviews': 'Чекає на перші відгуки',
  'professionals.startingFrom': 'Від',
  'professionals.noResults': 'Категорій за вашим запитом не знайдено',
  'professionals.categoryResults': 'знайдено категорій',
  'professionals.filterBy': 'Фільтрувати за',
  'professionals.location': 'Місце',
  'professionals.experience': 'Досвід',
  'professionals.priceRange': 'Діапазон цін',
  'professionals.availability': 'Доступність',
  'professionals.findPerfect': 'Знайдіть ідеального фахівця',
  'professionals.discoverTrusted':
    'Відкрийте перевірених фахівців з доведеним досвідом та чудовими відгуками',
  'professionals.popularCategories': 'Популярні категорії',
  'professionals.refineSearch': 'Уточніть результати пошуку',
  'professionals.professionalsAvailable': 'доступних фахівців',
  'professionals.noProfessionalsFound': 'Фахівців не знайдено',
  'professionals.tryAdjustingFilters':
    'Спробуйте змінити фільтри або пошуковий запит.',
  'professionals.noMatchingResults':
    'Немає фахівців за вашими критеріями. Спробуйте розширити пошук.',
  'professionals.mostActive': 'Найактивніші',
  'professionals.specialists': 'Спеціалістів',
  'professionals.stars': 'зірок',
  'professionals.gender.male': 'Чоловік',
  'professionals.gender.female': 'Жінка',
  'professionals.filters.category': 'Категорія',
  'professionals.filters.city': 'Місто',
  'professionals.filters.location': 'Місце',
  'professionals.filters.minimumRating': 'Мінімальний рейтинг',
  'professionals.filters.minRating': 'Мін. рейтинг',
  'professionals.filters.minJobs': 'Мін. завдань',
  'professionals.filters.jobs': 'завдань',
  'professionals.filters.sortBy': 'Сортувати за',
  'professionals.filters.genderPreference': 'Переваги статі',
  'professionals.filters.activityLevel': 'Рівень активності',
  'professionals.filters.all': 'Усі',
  'professionals.filters.topPerformersOnly': 'Тільки найкращі',
  'professionals.filters.locationPlaceholder': 'Софія, Пловдив, Варна...',
  'professionals.filters.any': 'Будь-який',
  'professionals.filters.anyShort': 'Будь-який',
  'professionals.typing.plumber': 'сантехнік у Софії',
  'professionals.typing.cleaner': 'спеціаліст з прибирання',
  'professionals.typing.electrician': 'сертифікований електрик',
  'professionals.typing.tutor': 'репетитор англійської',
  'professionals.typing.photographer': 'весільний фотограф',
  'professionals.typing.handyman': 'послуги майстра',
  'professionals.recommendedTitle': 'РЕКОМЕНДОВАНІ ФАХІВЦІ',
  'professionals.filters.clear': 'Очистити',
  'professionals.filters.clearAll': 'Очистити всі фільтри',
  'professionals.filters.fourPlusStars': '4+ зірок',
  'professionals.filters.fiveStarsOnly': 'Тільки 5 зірок',
  'professionals.filters.anyRating': 'За рейтингом',
  'professionals.filters.showProfessionalsWithAnyRating':
    'Показати фахівців з будь-яким рейтингом',
  'professionals.filters.locationPlaceholderDesktop': '📍 Місце',
  'professionals.sorting.featuredFirst': 'Найкращий вибір',
  'professionals.sorting.featuredFirstDesc': 'Найкращі фахівці',
  'professionals.sorting.highestRating': 'За рейтингом',
  'professionals.sorting.highestRatingDesc': 'Найвищий рейтинг',
  'professionals.sorting.mostExperience': 'За досвідом',
  'professionals.sorting.mostExperienceDesc': 'Найбільше замовлень',
  'professionals.filters.sortResultsBy': 'Сортувати результати за',
  'professionals.filters.sortResultsTitle': 'Сортувати результати',
  'professionals.filters.sortResultsDescription': 'Виберіть порядок фахівців',
  'professionals.filters.selectMinimumRating': 'Оберіть мінімальний рейтинг',
  'professionals.filters.showingVerifiedFirst':
    'Спочатку показуємо перевірених найкращих фахівців',
  'professionals.filters.sortingBy': 'Сортування за {{option}}',
  'professionals.filters.sortingDescFeatured':
    'Спочатку показуємо перевірених найкращих фахівців',
  'professionals.filters.sortingDescRating':
    'Фахівці з найвищим рейтингом показуються першими',
  'professionals.filters.sortingDescJobs':
    'Найдосвідченіші фахівці показуються першими',
  'professionals.filters.activeFilters': 'Активні фільтри',
  'professionals.filters.filterApplied': '{{count}} фільтр застосовано',
  'professionals.filters.filtersApplied': '{{count}} фільтрів застосовано',
  'professionals.filters.showProfessionalsWithRating':
    'Показати фахівців з рейтингом {{rating}}+ зірок',
  'professionals.filters.showPerfectRating':
    'Показати лише фахівців з ідеальним рейтингом 5 зірок',

  // Results section
  'professionals.results.showing': 'Показано {{count}} фахівців',
  'professionals.results.loading': 'Завантаження фахівців...',
  'professionals.results.noResults.title': 'Фахівців не знайдено',
  'professionals.results.noResults.description':
    'Спробуйте змінити фільтри або шукати в іншому районі',
  'professionals.results.noResults.clearFilters': 'Очистити фільтри',
  'professionals.results.error.title': 'Ой! Щось пішло не так',
  'professionals.results.error.description':
    'Наші сервери потребують перерви на каву',
  'professionals.results.error.subtext': 'Не хвилюйтесь, ми працюємо над цим!',
  'professionals.results.error.retry': 'Спробувати знову',
  'professionals.results.mockTitle': 'Тестові фахівці (довідка)',
  'professionals.results.mockDescription':
    'Зразки даних для демонстрації майбутніх функцій: портфоліо, сертифікати',
  'professionals.results.mockBadge1': 'Для розробки',
  'professionals.results.mockBadge2': 'Не реальні користувачі',
  'professionals.results.featured.title': 'Рекомендовані фахівці',
  'professionals.results.featured.description':
    'Перегляньте найкращих фахівців з нашої мережі',
  'professionals.results.allLoaded': 'Ви досягли кінця списку',
  'professionals.results.loadingMore': 'Завантаження більше фахівців...',

  // Pagination
  'professionals.pagination.previous': 'Попередня',
  'professionals.pagination.next': 'Наступна',
  'professionals.pagination.pageOf': 'Сторінка {{current}} з {{total}}',

  'professionalDetail.about': 'Про фахівця',
  'professionalDetail.reviews': 'відгуків',
  'professionalDetail.online': 'Онлайн',
  'professionalDetail.offline': 'Був нещодавно',
  'professionalDetail.verified.phone': 'Телефон',
  'professionalDetail.verified.id': 'ID',
  'professionalDetail.stats.completedTasks': 'Завдань',
  'professionalDetail.stats.yearsExperience': 'Років',
  'professionalDetail.stats.yearsExperienceLabel': 'років',
  'professionalDetail.stats.experience': 'Досвід',
  'professionalDetail.stats.responseTime': 'Відповідь',
  'professionalDetail.defaultBio':
    'Професійний спеціаліст з досвідом у галузі.',
  'professionalDetail.actions.suggestMyTask': 'Запропонувати завдання',
  'professionalDetail.actions.inviteToApply': 'Запросити подати заявку',
  'professionalDetail.actions.contact': 'Контакт',
  'professionalDetail.actions.share': 'Поділитись',
  'professionalDetail.contactHours': 'Доступний',
  'professionalDetail.services.title': 'Послуги та ціни',
  'professionalDetail.services.pricingNote.title': 'Інформація про ціни',
  'professionalDetail.services.pricingNote.description':
    'Остаточні ціни узгоджуються індивідуально залежно від складності та вимог завдання.',
  'professionalDetail.portfolio.title': 'Мої роботи',
  'professionalDetail.portfolio.noWork': 'Робіт ще немає',
  'professionalDetail.portfolio.emptyState':
    'Цей фахівець ще не оновив свої роботи. Ми постійно просимо їх додати - можливо, пощастить завтра!',
  'professionalDetail.portfolio.emptyStateCTA':
    'Перевірте пізніше, щоб побачити їхні чудові роботи',
  'professionalDetail.portfolio.before': 'До',
  'professionalDetail.portfolio.after': 'Після',
  'professionalDetail.portfolio.viewMore': 'Усі роботи',
  'professionalDetail.portfolio.showcase': 'Демонстрація професійних робіт',
  'professionalDetail.completedTasks.title': 'Виконані завдання',
  'professionalDetail.completedTasks.noTasks': 'Виконаних завдань ще немає',
  'professionalDetail.completedTasks.hugePotential':
    'Цей фахівець має величезний потенціал!',
  'professionalDetail.completedTasks.comingSoon':
    "Чудові роботи скоро з'являться...",
  'professionalDetail.completedTasks.watchThisSpace':
    'Слідкуйте за оновленнями!',
  'professionalDetail.completedTasks.emptyState':
    'Цей фахівець виконав багато завдань, але поки не на нашій платформі. Допоможіть нам збагатити цю сторінку своїм завданням!',
  'professionalDetail.completedTasks.emptyStateCTA':
    'Запропонуйте завдання та станьте їхнім першим клієнтом на платформі',
  'professionalDetail.completedTasks.viewTask': 'Переглянути завдання',
  'professionalDetail.completedTasks.completedOn': 'Завершено',
  'professionalDetail.reviews.title': 'Відгуки та рейтинг',
  'professionalDetail.reviews.count': 'відгуків',
  'professionalDetail.reviews.recentRating': 'Останній рейтинг',
  'professionalDetail.reviews.excellent': 'Відмінно',
  'professionalDetail.reviews.noReviews': 'Відгуків ще немає',
  'professionalDetail.reviews.beFirst': 'Станьте першим, хто залишить відгук',
  'professionalDetail.reviews.emptyState':
    "Відгуки про цього фахівця скоро з'являться. Запропонуйте завдання, щоб також оцінити!",
  'professionalDetail.reviews.emptyStateCTA':
    'Станьте першим, хто попрацює з цим фахівцем та залишить відгук',
  'professionalDetail.reviews.showMore': 'Показати всі відгуки',
  'professionalDetail.reviews.allReviews': 'Усі відгуки',
  'professionalDetail.reviews.avgRating': 'Середній рейтинг',
  'professionalDetail.reviews.more': 'більше',
  'professionalDetail.completedTasks.stats.tasksCompleted': 'Завершено завдань',
  'professionalDetail.completedTasks.stats.avgRating': 'Середній рейтинг',
  'professionalDetail.completedTasks.stats.fiveStarTasks': '5-зіркових завдань',
  'professionalDetail.completedTasks.pendingReview': 'Очікує відгуку',
  'professionalDetail.completedTasks.viewAll':
    'Переглянути всі {{count}} завдань',
  'professionalDetail.completedTasks.totalTasks': 'Усього завдань',
  'professionalDetail.completedTasks.averageRatingStars':
    'Середній рейтинг: {{rating}} зірок',
  'professionalDetail.verified': 'Перевірено',
  'professionalDetail.shareText': 'Перегляньте цього фахівця на Trudify',
  'professionalDetail.shareSuccess': 'Успішно поділились!',
  'professionalDetail.linkCopied': 'Посилання скопійовано!',
  'professionalDetail.copyError': 'Не вдалося скопіювати посилання',
  'professionals.filters.filtersButton': 'Фільтри',
  'professionals.filters.active': 'активних',
  'professionals.filters.showResults': 'Показати результати',
  'professionals.filters.reset': 'Скинути',
  'professionals.filters.filters': 'Фільтри',

  // Professional Badges
  'professionals.badge.topProfessional': 'Топ Про',
  'professionals.badge.topProfessional.tooltip':
    'Виконав {{count}} завдань за останні 30 днів',
  'professionals.badge.earlyAdopter': 'Ранній послідовник',
  'professionals.badge.earlyAdopter.tooltip':
    'Один з перших фахівців на нашій платформі. Дякуємо, що повірили в нас з самого початку!',
  'professionals.badge.featuredProfessional': 'Обраний фахівець',
  'professionals.badge.featuredProfessional.tooltip':
    'Особисто відібраний нашою командою за виняткову якість та надійність. Цей фахівець пройшов перевірку та рекомендований нами.',

  // Invite Modal
  'inviteModal.title': 'Запросити фахівця на завдання',
  'inviteModal.subtitle': 'Оберіть, на яке завдання запросити {{name}}',
  'inviteModal.selectLabel': 'Оберіть завдання',
  'inviteModal.selectPlaceholder': 'Оберіть ваше завдання',
  'inviteModal.noTasks': 'У вас ще немає відкритих завдань.',
  'inviteModal.createTaskHint':
    'Спочатку створіть завдання, щоб запросити цього фахівця.',
  'inviteModal.confirmText': 'отримає сповіщення про це запрошення.',
  'inviteModal.sendInvitation': 'Надіслати запрошення',
  'inviteModal.success': 'Запрошення надіслано!',
  'inviteModal.successDescription':
    '{{name}} отримає сповіщення про ваше завдання.',
  'inviteModal.error': 'Не вдалося надіслати запрошення',
  'inviteModal.errorFetchingTasks': 'Не вдалося завантажити ваші завдання',
  'inviteModal.alreadyInvited': 'Вже запрошено',
  'inviteModal.alreadyInvitedDescription':
    'Ви вже запросили {{name}} на це завдання.',
  'inviteModal.alreadyInvitedProfessional': 'Вже запрошено',
  'inviteModal.alreadyInvitedProfessionalDescription':
    'Ви вже запросили {{name}} на ваше завдання. Вони можуть подати заявку протягом 24 годин.',
  'inviteModal.createNewTask': 'Створити нове завдання',
  'inviteModal.loadingTasks': 'Завантаження ваших завдань...',
  'inviteModal.continue': 'Продовжити',
};
