// Profile page translations - personal info, professional info, statistics, settings
export const profile = {
  // Auto-save
  'profile.autoSave.saved': 'Зміни збережено',
  'profile.autoSave.error': 'Помилка збереження',

  // Loading
  'profile.loading': 'Завантаження профілю...',

  'profile.title': 'Мій профіль',
  'profile.customerProfileTitle': 'Інформація профілю замовника',
  'profile.professionalProfileTitle': 'Інформація профілю фахівця',
  'profile.personalInfo': 'Особиста інформація',
  'profile.professionalInfo': 'Професійна інформація',
  'profile.verification': 'Верифікація',
  'profile.reviews': 'Відгуки',
  'profile.stats': 'Статистика',

  'profile.form.firstName': 'Ім\'я',
  'profile.form.lastName': 'Прізвище',
  'profile.form.email': 'Email',
  'profile.form.phone': 'Телефон',
  'profile.form.location': 'Місце',
  'profile.form.bio': 'Про себе',
  'profile.form.skills': 'Навички',
  'profile.form.experience': 'Років досвіду',
  'profile.form.hourlyRate': 'Погодинна ставка (€)',
  'profile.form.vatNumber': 'ІПН',
  'profile.form.businessName': 'Назва компанії',
  'profile.form.website': 'Веб-сайт',

  'profile.verification.identity': 'Особу підтверджено',
  'profile.verification.business': 'Бізнес підтверджено',
  'profile.verification.phone': 'Телефон підтверджено',
  'profile.verification.email': 'Email підтверджено',

  // Email Verification
  'profile.verifyEmailPrompt': 'Підтвердіть email адресу',
  'profile.verifyEmailMessage': 'Отримуйте важливі оновлення про завдання та заявки. Лист підтвердження надіслано при реєстрації.',
  'profile.sendVerificationEmail': 'Надіслати лист',
  'profile.sending': 'Надсилання...',

  // Profile Page
  'profile.completion': 'Заповнення профілю',
  'profile.settingsTitle': 'Налаштування',
  'profile.tabs.customer': 'Замовник',
  'profile.tabs.professional': 'Фахівець',
  'profile.switchToCustomer': 'Перейти до профілю Замовника',
  'profile.switchToProfessional': 'Перейти до профілю Фахівця',
  'profile.emailLabel': 'Email',
  'profile.phone': 'Телефон',
  'profile.location': 'Місце',
  'profile.selectCity': 'Оберіть ваше місто',
  'profile.memberSince': 'Учасник з',
  'profile.editPersonalInfo': 'Редагувати',
  'profile.statistics': 'Статистика',
  'profile.verified': 'Підтверджено',
  'profile.completed': 'Завершено',
  'profile.active': 'Активних',

  // Avatar Upload
  'profile.avatar.changeAvatar': 'Змінити аватар',
  'profile.avatar.selectImage': 'Обрати зображення',
  'profile.avatar.remove': 'Видалити',
  'profile.avatar.supportedFormats': 'Підтримувані формати: JPG, PNG, WebP (макс. 2 МБ)',
  'profile.avatar.supportedFormatsExtended': 'Підтримувані формати: JPG, PNG, WebP (авто-оптимізація)',
  'profile.avatar.invalidFileType': 'Непідтримуваний тип файлу. Оберіть JPG, PNG або WebP.',
  'profile.avatar.fileTooLarge': 'Файл занадто великий. Оберіть зображення менше 2 МБ.',
  'profile.avatar.fileTooLargeForCompression': 'Файл занадто великий. Максимум 20 МБ.',
  'profile.avatar.uploadError': 'Помилка завантаження. Спробуйте ще раз.',
  'profile.avatar.deleteError': 'Помилка видалення аватара. Спробуйте ще раз.',
  'profile.avatar.compressing': 'Оптимізація...',
  'profile.avatar.optimizing': 'Оптимізація зображення',
  'profile.avatar.compressionError': 'Помилка оптимізації. Спробуйте ще раз.',
  'profile.avatar.saved': 'збережено',

  // Statistics Modal
  'profile.statistics.title': 'Статистика акаунта',
  'profile.statistics.description': 'Перегляньте показники продуктивності та активності',
  'profile.statistics.memberSince': 'Учасник з',

  // Customer Statistics
  'profile.statistics.customer.overview': 'Огляд замовника',
  'profile.statistics.customer.performance': 'Показники продуктивності',
  'profile.statistics.customer.successRate': 'Рівень успіху',
  'profile.statistics.customer.responseRate': 'Рівень відповідей',
  'profile.statistics.customer.noStatsYet': 'Статистика завдань з\'явиться тут під час використання платформи.',
  'profile.statistics.customer.tasksPosted': 'Опубліковано завдань',
  'profile.statistics.customer.applicationsReceived': 'Отримано заявок',
  'profile.statistics.customer.reviewsGiven': 'Залишено відгуків',

  // Professional Statistics
  'profile.statistics.professional.business': 'Огляд бізнесу',
  'profile.statistics.professional.performance': 'Показники продуктивності',
  'profile.statistics.professional.repeatClients': 'Повторні клієнти',
  'profile.statistics.professional.monthlyEarnings': 'Місячний заробіток',
  'profile.statistics.professional.activeJobs': 'Активні завдання',
  'profile.statistics.avgResponseTime': 'Сер. час відповіді',
  'profile.statistics.responseTime.minutes': '{minutes} хв',
  'profile.statistics.responseTime.hour': '1 година',
  'profile.statistics.responseTime.hours': '{hours} годин',
  'profile.professional.acceptanceRate': 'Прийняття завдань',

  // Quick Actions
  'profile.quickActions.createTask': 'Створити завдання',

  // Customer Profile
  'profile.customer.personalInfo': 'Особиста інформація',
  'profile.customer.language': 'Мова',
  'profile.customer.preferredContact': 'Бажаний контакт',
  'profile.customer.preferredLanguage': 'Бажана мова',
  'profile.customer.preferredContactMethod': 'Бажаний спосіб зв\'язку',
  'profile.customer.statistics': 'Статистика',
  'profile.customer.tasksPosted': 'Опубліковано завдань',
  'profile.customer.tasksCompleted': 'Завершено завдань',
  'profile.customer.averageRating': 'Середній рейтинг',
  'profile.customer.totalSpent': 'Загальні витрати',
  'profile.customer.recentActivity': 'Остання активність',
  'profile.customer.taskCompleted': 'Завдання завершено',
  'profile.customer.taskPosted': 'Завдання опубліковано',
  'profile.customer.viewAllTasks': 'Усі завдання',
  'profile.customer.notificationPreferences': 'Налаштування сповіщень',
  'profile.customer.smsNotifications': 'SMS-сповіщення',
  'profile.customer.smsNotificationsDesc': 'Отримуйте важливі оновлення через SMS',

  // Professional Profile
  'profile.professional.info': 'Професійна інформація',
  'profile.professional.identitySection': 'Професійна ідентичність',
  'profile.professional.title': 'Професійна назва',
  'profile.professional.bio': 'Про себе',
  'profile.professional.yearsOfExperience': 'Років досвіду',
  'profile.professional.description': 'Опис',
  'profile.professional.hourlyRate': 'Погодинна ставка',
  'profile.professional.availability': 'Доступність',
  'profile.professional.availabilityPreferences': 'Доступність та налаштування',
  'profile.professional.status': 'Статус',
  'profile.professional.languagesSpoken': 'Мови',
  'profile.professional.noLanguagesSelected': 'Мови не обрано',
  'profile.professional.skills': 'Навички',
  'profile.professional.statistics': 'Статистика продуктивності',
  'profile.professional.completedJobs': 'Виконаних завдань',
  'profile.professional.totalEarnings': 'Загальний заробіток',
  'profile.professional.responseTimeLabel': 'Час відповіді',
  'profile.professional.performance': 'Показники продуктивності',
  'profile.professional.profileViews': 'Переглядів профілю',
  'profile.professional.completionRate': 'Рівень завершення',
  'profile.professional.monthlyGrowth': 'Місячне зростання',
  'profile.professional.recentWork': 'Останні роботи',
  'profile.professional.viewPortfolio': 'Переглянути портфоліо',
  'profile.professional.setupTitle': 'Налаштуйте професійний профіль',
  'profile.professional.setupDescription': 'Заповніть профіль, щоб отримувати пропозиції роботи та зв\'язуватися з клієнтами.',
  'profile.professional.setupProfile': 'Налаштувати профіль',
  'profile.professional.businessSettings': 'Бізнес-налаштування',
  'profile.professional.paymentMethod': 'Спосіб оплати',
  'profile.professional.vatNumber': 'ІПН',
  'profile.professional.serviceLocation': 'Місце надання послуг',
  'profile.professional.setInPersonalInfo': 'Встановіть в особистій інформації',
  'profile.professional.editInPersonalInfo': 'Редагуйте в особистій інформації',
  'profile.professional.notSet': 'Не встановлено',
  'profile.professional.notVerified': 'Не підтверджено',
  'profile.professional.titlePlaceholder': 'напр., Професійне прибирання та домашні послуги',
  'profile.professional.bioPlaceholder': 'Розкажіть клієнтам про свій досвід, спеціалізацію та підхід...',
  'profile.professional.setupFormDescription': 'Заповніть інформацію, щоб продемонструвати навички та досвід.',
  'profile.professional.selectCategories': 'Обрати категорії',
  'profile.professional.serviceCategories': 'Категорії послуг',
  'profile.serviceCategories.saveCategories': 'Зберегти',
  'profile.serviceCategories.searchPlaceholder': 'Шукати категорії...',
  'profile.serviceCategories.popularCategories': 'Популярні категорії',
  'profile.serviceCategories.selected': 'Обрано',
  'profile.serviceCategories.clearAll': 'Очистити все',
  'profile.professional.verificationTrust': 'Верифікація та довіра',
  'profile.professional.phoneVerification': 'Верифікація телефону',
  'profile.professional.phoneVerificationRequired': 'Обов\'язково для всіх фахівців',
  'profile.professional.verified': 'Підтверджено',
  'profile.professional.verifyPhone': 'Підтвердити телефон',
  'profile.professional.acceptedPaymentMethods': 'Прийняті способи оплати',
  'profile.professional.businessHoursLabel': 'Робочі години',
  'profile.professional.businessHoursPlaceholder': 'напр., Пн-Пт 8:00-18:00, Сб 9:00-14:00',
  'profile.professional.weekdaysLabel': 'Будні (Пн-Пт)',
  'profile.professional.weekendLabel': 'Вихідні (Сб-Нд)',
  'profile.professional.startTime': 'Початок',
  'profile.professional.endTime': 'Кінець',
  'profile.professional.noPaymentMethods': 'Способи оплати не обрано',
  'profile.professional.portfolioGallery': 'Галерея портфоліо',
  'profile.professional.portfolioDescription': 'Продемонструйте кращі роботи з фото до/після',
  'profile.professional.addServiceCategories': 'Додайте категорії послуг',
  'profile.professional.categoriesHelp': 'Допоможіть клієнтам вас знайти! Оберіть послуги, які надаєте.',

  // Professional Profile Completion
  'profile.professional.incompleteTitle': 'Заповніть професійний профіль',
  'profile.professional.minimumRequired': 'Мінімально необхідне',
  'profile.professional.titleField': 'Професійна назва',
  'profile.professional.recommended': 'Рекомендовано',
  'profile.professional.recommendedFields': 'Категорії (Послуги), Місце та Про себе',

  // Professional Listing Banner
  'profile.listing.notListed': 'Ваш профіль ще не опубліковано',
  'profile.listing.notListedMessage': 'Додайте професійну назву, щоб з\'явитися в нашому пошуку та отримувати пропозиції роботи від клієнтів.',
  'profile.listing.incomplete': 'Заповніть профіль',
  'profile.listing.incompleteMessage': 'Заповніть відсутню інформацію, щоб покращити видимість та залучити більше клієнтів.',
  'profile.listing.requirement.title': 'Професійна назва',
  'profile.listing.requirement.bio': 'Опис/Про себе',
  'profile.listing.requirement.rate': 'Погодинна ставка',
  'profile.listing.requirement.skills': 'Категорії послуг',
  'profile.listing.clickToFix': 'Натисніть для виправлення',

  // Telegram Connection
  'profile.telegram.clickToConnect': 'Натисніть для підключення',

  // Professional Setup Form
  'profile.professional.form.titlePlaceholder': 'напр., Full Stack розробник, UX дизайнер, Маркетинговий консультант',
  'profile.professional.form.descriptionPlaceholder': 'Опишіть свій професійний досвід, експертизу та унікальність...',
  'profile.professional.form.experience': 'Рівень досвіду',
  'profile.professional.form.portfolio': 'URL портфоліо (необов\'язково)',
  'profile.professional.form.portfolioDescription': 'Посилання на сайт, GitHub або онлайн-портфоліо',
  'profile.professional.form.selectedSkills': 'Обрані навички',
  'profile.professional.form.searchSkills': 'Шукати навички...',
  'profile.professional.form.suggestedSkills': 'Популярні навички',
  'profile.professional.form.addCustomSkill': 'Додати власну навичку',
  'profile.professional.form.customSkillPlaceholder': 'Введіть назву навички',
  'profile.professional.form.moreSkillsAvailable': 'та ще {count}...',
  'profile.professional.form.skillsLimitNotice': 'Рекомендуємо обрати топ-10 навичок для найкращих результатів.',
  'profile.professional.form.submitting': 'Створення профілю...',
  'profile.professional.form.createProfile': 'Створити професійний профіль',

  // Experience Options
  'profile.professional.form.experienceOptions.beginner': '0-1 рік',
  'profile.professional.form.experienceOptions.intermediate': '2-5 років',
  'profile.professional.form.experienceOptions.experienced': '5-10 років',
  'profile.professional.form.experienceOptions.expert': '10+ років',

  // Availability Options
  'profile.professional.form.availabilityOptions.available': 'Доступний',
  'profile.professional.form.availabilityOptions.busy': 'Зайнятий',
  'profile.professional.form.availabilityOptions.unavailable': 'Недоступний',

  // Response Time Options
  'profile.professional.responseTime.1h': 'Протягом 1 години',
  'profile.professional.responseTime.2h': 'Протягом 2 годин',
  'profile.professional.responseTime.4h': 'Протягом 4 годин',
  'profile.professional.responseTime.24h': 'Протягом 24 годин',

  // Language Options
  'profile.professional.languages.bg': '🇧🇬 Болгарська',
  'profile.professional.languages.ru': '🇷🇺 Російська',
  'profile.professional.languages.en': '🇬🇧 Англійська',
  'profile.professional.languages.ua': '🇺🇦 Українська',

  // Payment Method Options
  'profile.professional.paymentMethods.cash': 'Готівка',
  'profile.professional.paymentMethods.card': 'Картка',
  'profile.professional.paymentMethods.bank_transfer': 'Банківський переказ',
  'profile.professional.paymentMethods.mobile_payment': 'Мобільний платіж',

  // Business Hours Labels
  'profile.professional.businessHours.weekdays': 'Пн-Пт',
  'profile.professional.businessHours.weekend': 'Сб-Нд',

  // Form Validation
  'profile.professional.form.validation.titleRequired': 'Професійна назва обов\'язкова (мінімум 3 символи)',
  'profile.professional.form.validation.descriptionRequired': 'Опис обов\'язковий (мінімум 20 символів)',
  'profile.professional.form.validation.rateRequired': 'Погодинна ставка має бути більше 0',
  'profile.professional.form.validation.skillsRequired': 'Оберіть хоча б одну навичку',

  // Settings Modal
  'profile.settings.description': 'Керуйте налаштуваннями акаунта та приватності',

  // Email Verification Banner
  'profile.email.promptTitle': 'Підтвердіть Email!',
  'profile.email.promptDescription': 'Підтвердіть email для отримання важливих сповіщень про завдання, заявки та повідомлення.',
  'profile.email.promptDescriptionSecurity': 'Підтвердіть email для безпеки акаунта та отримання важливих оновлень.',
  'profile.email.sendVerification': 'Надіслати лист',
  'profile.email.verificationSent': 'Лист надіслано! Перевірте вхідні.',
  'profile.email.verificationFailed': 'Не вдалося надіслати лист',
  'profile.email.checkInboxTitle': 'Перевірте пошту!',
  'profile.email.checkInboxMessage': 'Ми надіслали лист підтвердження. Натисніть посилання в листі для підтвердження.',
  'profile.email.checkSpam': 'Не отримали? Перевірте папку спам або натисніть кнопку для повторного надсилання.',

  // Telegram Connection
  'profile.telegramNotifications': 'Сповіщення Telegram',
  'profile.telegramDescription': 'Підключіть Telegram для миттєвих безкоштовних сповіщень',
  'profile.telegram.promptTitle': 'Миттєві сповіщення!',
  'profile.telegram.promptDescription': 'Підключіть Telegram для отримання оновлень про завдання, заявки та повідомлення в реальному часі.',
  'profile.telegram.connectNow': 'Підключити Telegram',
  'profile.telegram.openTelegram': 'Відкрити Telegram для підключення',
  'profile.connected': 'Підключено',
  'profile.notConnected': 'Не підключено',
  'profile.connectedAs': 'Підключено як',
  'profile.benefits': 'Переваги',
  'profile.instantNotifications': 'Миттєві сповіщення (без затримок)',
  'profile.freeForever': 'Безкоштовно назавжди (без SMS-витрат)',
  'profile.noEmailSpam': 'Без спаму в пошті',
  'profile.richMessages': 'Розширені повідомлення з кнопками та посиланнями',
  'profile.connectTelegram': 'Підключити Telegram',
  'profile.disconnectTelegram': 'Відключити Telegram',
  'profile.telegramInstructions': 'Telegram відкриється в новому вікні. Натисніть кнопку в боті для завершення підключення.',
  'profile.telegramConnectError': 'Помилка підключення Telegram. Спробуйте ще раз.',
  'profile.telegramDisconnectConfirm': 'Точно хочете відключити Telegram? Ви більше не отримуватимете миттєвих сповіщень.',
  'profile.telegramDisconnectError': 'Помилка відключення Telegram. Спробуйте ще раз.',
  'profile.telegram.disconnectConfirmTitle': 'Відключити Telegram?',
  'profile.telegram.disconnectConfirmMessage': 'Точно хочете припинити отримувати миттєві безкоштовні сповіщення через Telegram?',
  'profile.telegram.disconnectWarning': 'Ви втратите доступ до:',
  'profile.telegram.keepTelegram': 'Залишити Telegram',
  'profile.telegram.disconnect': 'Відключити',
  'profile.telegram.steps': 'Виконайте ці кроки',
  'profile.telegram.step1': 'Натисніть кнопку нижче для відкриття Telegram-бота',
  'profile.telegram.step2': 'Натисніть "Start" та скопіюйте свій Telegram ID',
  'profile.telegram.step3': 'Вставте Telegram ID нижче',
  'profile.telegram.enterId': 'Введіть Telegram ID',
  'profile.telegram.connect': 'Підключити',
  'profile.telegram.invalidIdFormat': 'Введіть дійсний Telegram ID (тільки цифри)',
  'profile.telegram.alreadyConnected': 'Цей Telegram вже підключено до іншого акаунта Trudify. Спочатку відключіть його або використайте інший Telegram.',
  'profile.telegram.openBot': 'Відкрити Telegram-бота',
  'profile.telegram.pasteAndConnect': 'Вставити ID та підключити',
  'profile.telegram.connecting': 'Підключення...',
  'profile.telegram.autoSaveHint': 'Вставте свій ID сюди - підключення відбудеться автоматично',
  'profile.telegram.clipboardError': 'Немає доступу до буфера обміну. Вставте ID вручну.',
  'profile.telegram.toast.title': 'Підключіть Telegram для миттєвих сповіщень',
  'profile.telegram.toast.description': 'Отримуйте оновлення про завдання, заявки та повідомлення в реальному часі. Безкоштовно та завжди вчасно!',
  'profile.telegram.toast.action': 'Підключити зараз',

  // Work Gallery
  'profile.gallery.title': 'Галерея робіт',
  'profile.gallery.description': 'Покажіть свої найкращі роботи (макс. 5 зображень)',
  'profile.gallery.addImage': 'Додати',
  'profile.gallery.captionPlaceholder': 'Підпис (необов\'язково)',
  'profile.gallery.helperText': 'Натисніть на порожні слоти для завантаження. JPG, PNG або WEBP (макс. 5МБ кожне)',
  'profile.gallery.invalidType': 'Недійсний тип файлу',
  'profile.gallery.useJpgPngWebp': 'Використовуйте JPG, PNG або WEBP',
  'profile.gallery.fileTooLarge': 'Файл занадто великий',
  'profile.gallery.maxSize': 'Максимум 5МБ',
  'profile.gallery.compressing': 'Оптимізація...',
  'profile.gallery.uploading': 'Завантаження...',
  'profile.gallery.smaller': 'менше',
  'profile.gallery.uploadSuccess': 'Зображення завантажено',
  'profile.gallery.uploadError': 'Помилка завантаження',
  'profile.gallery.deleteSuccess': 'Зображення видалено',
  'profile.gallery.deleteError': 'Помилка видалення',

  'profile.settings.notifications': 'Сповіщення',
  'profile.settings.emailNotifications': 'Email-сповіщення',
  'profile.settings.emailNotificationsDesc': 'Отримуйте оновлення про завдання та акаунт',
  'profile.settings.taskUpdates': 'Оновлення завдань',
  'profile.settings.taskUpdatesDesc': 'Сповіщення про оновлення завдань',
  'profile.settings.marketingEmails': 'Маркетингові листи',
  'profile.settings.marketingEmailsDesc': 'Отримуйте поради та рекламний контент',
  'profile.settings.pushNotifications': 'Push-сповіщення',
  'profile.settings.pushNotificationsDesc': 'Миттєві сповіщення на пристрій',
  'profile.settings.weeklyDigest': 'Щотижневий дайджест',
  'profile.settings.weeklyDigestDesc': 'Щотижневий підсумок активності та можливостей',
  'profile.settings.privacy': 'Приватність',
  'profile.settings.profileVisibility': 'Видимість профілю',
  'profile.settings.profileVisibilityDesc': 'Зробити профіль видимим для потенційних клієнтів',
  'profile.settings.showContactInfo': 'Показувати контакти',
  'profile.settings.showContactInfoDesc': 'Публічно відображати контактну інформацію',
  'profile.settings.interface': 'Інтерфейс',
  'profile.settings.darkMode': 'Темна тема',
  'profile.settings.darkModeDesc': 'Перемкнути на темний інтерфейс',
  'profile.settings.dangerZone': 'Небезпечна зона',
  'profile.settings.deleteAccount': 'Видалити акаунт',
  'profile.settings.deleteAccountDesc': 'Остаточно видалити акаунт та всі дані',
  'profile.settings.deleteAccountConfirm': 'Видалення акаунта буде доступне незабаром',

  // Customer Profile Form
  'profile.form.name': 'Повне ім\'я',
  'profile.form.saving': 'Збереження...',
  'profile.form.validation.nameRequired': 'Ім\'я обов\'язкове (мінімум 2 символи)',
  'profile.form.validation.emailRequired': 'Email обов\'язковий',
  'profile.form.validation.emailInvalid': 'Введіть дійсну email адресу',
  'profile.form.validation.phoneRequired': 'Номер телефону обов\'язковий',
  'profile.form.validation.phoneInvalid': 'Введіть 8-9 цифр (напр. 88 123 4567)',
  'profile.form.phoneBulgarianOnly': 'Тільки болгарські номери телефонів',
  'profile.form.validation.locationRequired': 'Місце обов\'язкове (мінімум 3 символи)',

  // Achievement Banner
  'profile.achievement.title': 'Ви чудово працюєте!',
  'profile.achievement.subtitle': 'Дякуємо, що ви видатний член нашої спільноти. Ваша наполеглива праця та відданість справі дійсно мають значення!',
  'profile.achievement.tasksCompleted': 'завдань',

  // Services & Pricing
  'profile.services.title': 'Послуги та ціни',
  'profile.services.description': 'Додайте ваші послуги з цінами',
  'profile.services.empty': 'Послуги ще не додано',
  'profile.services.emptyHint': 'Додайте ваші послуги, щоб клієнти знали, що ви пропонуєте',
  'profile.services.addService': 'Додати послугу',
  'profile.services.serviceName': 'Назва послуги',
  'profile.services.serviceNamePlaceholder': 'напр. Сантехнічний ремонт',
  'profile.services.price': 'Ціна',
  'profile.services.pricePlaceholder': 'напр. 25 €/год',
  'profile.services.descriptionLabel': 'Опис (необов\'язково)',
  'profile.services.descriptionPlaceholder': 'Короткий опис послуги',
  'profile.services.helperText': 'Додайте до {max} послуг. Зміни зберігаються автоматично.',
};
