// Task-related translations - browsing, creating, task cards, task detail
export const tasks = {
  'tasks.title': 'Переглянути завдання',
  'tasks.subtitle':
    'Знайдіть завдання, що відповідає вашим навичкам та інтересам',
  'tasks.searchPlaceholder':
    'Шукайте за ключовими словами, категоріями або місцем...',
  'tasks.filters.title': 'Фільтри',
  'tasks.filters.category': 'Категорія',
  'tasks.filters.allCategories': 'Усі категорії',
  'tasks.filters.location': 'Місце',
  'tasks.filters.budget': 'Бюджет',
  'tasks.filters.budgetMin': 'Мін. бюджет',
  'tasks.filters.budgetMax': 'Макс. бюджет',
  'tasks.filters.deadline': 'Дедлайн',
  'tasks.filters.status': 'Статус',
  'tasks.filters.all': 'Усі',
  'tasks.filters.open': 'Відкриті',
  'tasks.filters.inProgress': 'У роботі',
  'tasks.filters.completed': 'Завершені',
  'tasks.filters.activeFilters': 'Активні фільтри',
  'tasks.filters.clearAll': 'Очистити все',
  'tasks.results': 'результатів',
  'tasks.sort.newest': 'Спочатку нові',
  'tasks.sort.oldest': 'Спочатку старі',
  'tasks.sort.budgetHigh': 'Найвищий бюджет',
  'tasks.sort.budgetLow': 'Найнижчий бюджет',
  'tasks.sort.deadline': 'За дедлайном',

  'browseTasks.hero.badge': 'Заробляйте зараз',
  'browseTasks.hero.title1': 'Знайдіть свою',
  'browseTasks.hero.title2': 'можливість',
  'browseTasks.hero.subtitle':
    'Переглядайте перевірені завдання від реальних клієнтів. Будуйте дохід за власним графіком.',
  'browseTasks.search.placeholder':
    'Шукайте за ключовими словами, категорією або містом...',
  'browseTasks.search.popular': 'Популярне',
  'browseTasks.search.searchingCategories': 'Пошук категорій...',
  'browseTasks.search.suggestedCategories': 'Рекомендовані категорії',
  'browseTasks.search.categories': 'Категорії',
  'browseTasks.search.cities': 'Міста',
  'browseTasks.filters.title': 'Фільтрація та сортування',
  'browseTasks.filters.advanced': 'Розширені фільтри',
  'browseTasks.filters.quick': 'Швидкий фільтр',
  'browseTasks.filters.searchPlaceholder':
    'Шукайте завдання... (напр., прибирання, ремонт, доставка)',
  'browseTasks.filters.category': 'Категорія',
  'browseTasks.filters.allCategories': 'Усі категорії',
  'browseTasks.filters.city': 'Місто',
  'browseTasks.filters.allCities': 'Усі міста',
  'browseTasks.filters.cities.sofia': 'Софія',
  'browseTasks.filters.cities.plovdiv': 'Пловдив',
  'browseTasks.filters.cities.varna': 'Варна',
  'browseTasks.filters.cities.burgas': 'Бургас',
  'browseTasks.filters.budget': 'Бюджет',
  'browseTasks.filters.budgetMin': 'Мін',
  'browseTasks.filters.budgetMax': 'Макс',
  'browseTasks.filters.budgetUpTo': 'До 500 BGN',
  'browseTasks.filters.sortBy': 'Сортувати',
  'browseTasks.filters.sort.newest': 'Найновіші',
  'browseTasks.filters.sort.oldest': 'Найстаріші',
  'browseTasks.filters.sort.highBudget': 'Високий бюджет',
  'browseTasks.filters.sort.lowBudget': 'Низький бюджет',
  'browseTasks.filters.filters': 'Фільтри',
  'browseTasks.filters.active': 'активних',
  'browseTasks.filters.reset': 'Скинути',
  'browseTasks.filters.showResults': 'Показати результати',
  'browseTasks.filters.clear': 'Очистити',
  'browseTasks.filters.customRange': 'Власний діапазон',
  'browseTasks.filters.min': 'Мін',
  'browseTasks.filters.max': 'Макс',
  'browseTasks.filters.apply': 'Застосувати',
  'browseTasks.filters.urgency': 'Терміновість',
  'browseTasks.filters.urgentSameDay': 'Терміново',
  'browseTasks.filters.thisWeek': 'Цього тижня',
  'browseTasks.filters.flexible': 'Гнучко',
  'browseTasks.filters.searchCity': 'Шукати місто...',
  'browseTasks.filters.noCitiesFound': 'Міст не знайдено',
  'browseTasks.filters.searchCategory': 'Шукати категорії...',
  'browseTasks.filters.noCategoriesFound': 'Категорій не знайдено',
  'browseTasks.filters.activeFilters': 'Активні фільтри',
  'browseTasks.filters.clearAll': 'Очистити все',
  'browseTasks.sort.newest': 'Спочатку нові',
  'browseTasks.sort.urgent': 'Спочатку термінові',
  'browseTasks.sort.budgetHigh': 'Найвищий бюджет',
  'browseTasks.sort.budgetLow': 'Найнижчий бюджет',
  'browseTasks.sort.deadline': 'Завершуються скоро',
  'browseTasks.results.shown': 'Показано {{count}} результатів',
  'browseTasks.results.featured': 'Показано {{count}} популярних завдань',
  'browseTasks.results.loading': 'Завантаження...',
  'browseTasks.results.noTasks.title': 'Завдань не знайдено',
  'browseTasks.results.noTasks.description':
    'Спробуйте змінити фільтри або шукати за іншими критеріями.',
  'browseTasks.results.noTasks.clearFilters': 'Очистити фільтри',
  'browseTasks.results.suggestedTasks': 'Популярні завдання, які можуть вас зацікавити',
  'browseTasks.results.suggestedDescription':
    'Ось популярні завдання від нашої спільноти',
  'browseTasks.results.featuredTasks': 'Рекомендовані завдання',
  'browseTasks.results.featuredDescription':
    'Перегляньте популярні завдання від нашої спільноти',
  'browseTasks.results.error.title': 'Ой! Наші сервери взяли перерву на каву ☕',
  'browseTasks.results.error.description':
    'Здається, наші хом\'яки перестали бігати. Не хвилюйтесь, ми даємо їм еспресо!',
  'browseTasks.results.error.subtext':
    'Зазвичай це виправляється швидше, ніж ви скажете "капучіно"',
  'browseTasks.results.error.retry': 'Спробувати знову',
  'browseTasks.results.allTasksLoaded': 'Ви досягли кінця списку',
  'browseTasks.results.loadingMore': 'Завантаження більше завдань...',
  'browseTasks.pagination.previous': 'Попередня',
  'browseTasks.pagination.next': 'Наступна',
  'browseTasks.search.tags.programming': 'Програмування',
  'browseTasks.search.tags.design': 'Дизайн',
  'browseTasks.search.tags.marketing': 'Маркетинг',
  'browseTasks.search.tags.translation': 'Переклад',
  'browseTasks.search.tags.photography': 'Фотографія',
  'browseTasks.typing.plumber': 'сантехнік у Софії',
  'browseTasks.typing.cleaner': 'прибирання будинку',
  'browseTasks.typing.electrician': 'ремонт електрики',
  'browseTasks.typing.tutor': 'репетитор англійської',
  'browseTasks.typing.moving': 'перевезення меблів',
  'browseTasks.typing.gardener': 'догляд за садом',

  'task.budget': 'Бюджет',
  'task.location': 'Місце',
  'task.category': 'Категорія',
  'task.applications': 'Заявок',
  'task.viewDetails': 'Детальніше',
  'task.apply': 'Подати заявку',
  'task.created': 'Створено',
  'task.deadline': 'Дедлайн',

  // Create Task Form
  'createTask.title': 'Опублікувати нове завдання',
  'createTask.hero.subtitle': 'Опишіть, що потрібно, і фахівці прийдуть до вас',
  'createTask.hero.freeToPost': 'Безкоштовно',
  'createTask.hero.noPayment': 'Оплата тільки після початку роботи',
  'createTask.hero.avgResponse': 'Середній час відповіді: 2 години',
  'createTask.hero.verifiedPros': 'Перевірені фахівці',
  'createTask.hero.help': 'Потрібна допомога? Зверніться до підтримки',

  // Category Section
  'createTask.category.title': 'Який тип послуги вам потрібен?',
  'createTask.category.subtitle': 'Оберіть категорію, що найкраще відповідає вашому завданню',
  'createTask.category.selectSubcategory': 'Оберіть конкретну послугу',
  'createTask.category.backToMain': 'Назад до головних категорій',
  'createTask.category.selected': 'Обрана послуга',
  'createTask.category.categorySelected': 'Категорію обрано. Натисніть X, щоб змінити.',
  'createTask.category.tryDifferent': 'Спробуйте інший пошуковий запит',
  'createTask.category.change': 'Змінити',

  // Details Section
  'createTask.details.title': 'Розкажіть про завдання',
  'createTask.details.subtitle': 'Надайте чітку інформацію для залучення потрібних фахівців',
  'createTask.details.titleLabel': 'Назва завдання',
  'createTask.details.titlePlaceholder': 'Що потрібно зробити?',
  'createTask.title.label': 'Що вам потрібно?',
  'createTask.details.titleHelp': 'Будьте конкретними (напр., "Професійне прибирання 2-кімнатної квартири")',
  'createTask.details.titleTooltipTitle': 'Напишіть чітку назву',
  'createTask.details.titleTooltipContent': 'Будьте конкретними. Добрі приклади: "Полагодити кран на кухні", "Професійне прибирання квартири", "Редизайн головної сторінки"',
  'createTask.details.descriptionLabel': 'Опис',
  'createTask.details.descriptionPlaceholder': 'Опишіть завдання детально...',
  'createTask.details.descriptionHelp': 'Включіть усі важливі деталі: що потрібно зробити, особливі вимоги, необхідні інструменти тощо.',
  'createTask.details.requirementsLabel': 'Особливі вимоги (необов\'язково)',
  'createTask.details.requirementsPlaceholder': '• Вимога 1\n• Вимога 2\n• Вимога 3',
  'createTask.details.requirementsHelp': 'Перелічіть особливі навички, сертифікати або обладнання (по одному на рядок)',

  // Location Section
  'createTask.location.title': 'Де буде виконуватись завдання?',
  'createTask.location.subtitle': 'Місце допомагає фахівцям зрозуміти, чи можуть вони до вас дістатися',
  'createTask.location.cityLabel': 'Місто',
  'createTask.location.cityPlaceholder': 'Оберіть місто',
  'createTask.location.neighborhoodLabel': 'Район',
  'createTask.location.neighborhoodPlaceholder': 'напр., Центр, Витоша',
  'createTask.location.neighborhoodHelp': 'Допомагає фахівцям визначити можливість приїзду',
  'createTask.location.addressLabel': 'Повна адреса (необов\'язково)',
  'createTask.location.addressPlaceholder': 'Вулиця, номер будинку, під\'їзд, поверх, квартира',
  'createTask.location.addressSecurity': 'Адреса буде показана лише обраному фахівцю',

  // Budget Section
  'createTask.budget.title': 'Який ваш бюджет?',
  'createTask.budget.help': 'Справедливий бюджет отримує втричі більше заявок',
  'createTask.budget.typeFixed': 'Фіксована ціна',
  'createTask.budget.typeRange': 'Діапазон цін',
  'createTask.budget.typeUnclear': 'Не впевнений щодо бюджету',
  'createTask.budget.fixedLabel': 'Ваш бюджет',
  'createTask.budget.minLabel': 'Мінімум',
  'createTask.budget.maxLabel': 'Максимум',
  'createTask.budget.notSure': 'Не впевнений щодо бюджету',
  'createTask.budget.mustBePositive': 'Бюджет має бути позитивним',

  // Timeline Section
  'createTask.timeline.title': 'Коли це потрібно зробити?',
  'createTask.timeline.subtitle': 'Повідомте фахівцям про терміни',
  'createTask.timeline.urgentTitle': 'Терміново',
  'createTask.timeline.urgentDesc': 'Якнайшвидше',
  'createTask.timeline.soonTitle': 'Скоро - протягом тижня',
  'createTask.timeline.soonDesc': 'Потрібно зробити протягом 7 днів',
  'createTask.timeline.flexibleTitle': 'Гнучко',
  'createTask.timeline.flexibleDesc': 'Гнучкий за термінами',
  'createTask.timeline.deadlineLabel': 'Конкретний дедлайн (необов\'язково)',
  'createTask.timeline.deadlineHelp': 'Залиште порожнім, якщо немає конкретного дедлайну',
  'createTask.timeline.pastDateWarning': 'Цей дедлайн у минулому. Оберіть майбутню дату або очистіть поле.',
  'createTask.timeline.selectDate': 'Обрати дату',

  // Photos Section
  'createTask.photos.title': 'Додайте фото (необов\'язково)',
  'createTask.photos.help': 'Фото допомагає фахівцям краще зрозуміти завдання',
  'createTask.photos.dragDrop': 'Перетягніть зображення сюди',
  'createTask.photos.tapToSelect': 'Торкніться, щоб вибрати фото',
  'createTask.photos.orBrowse': 'або натисніть для вибору',
  'createTask.photos.takePhoto': 'Зробити фото',
  'createTask.photos.maxSize': 'Максимум 5 МБ',
  'createTask.photos.formats': 'JPG, PNG, WebP',
  'createTask.photos.uploading': 'Завантаження фото...',
  'createTask.photos.fileTooLarge': 'Зображення занадто велике після оптимізації (макс. 5 МБ). Це зображення не буде завантажено. Можете змінити його зараз або редагувати завдання пізніше.',
  'createTask.photos.invalidType': 'Файл не є підтримуваним форматом',
  'createTask.photos.uploadError': 'Не вдалося завантажити фото. Спробуйте ще раз.',
  'createTask.photos.optimizing': 'Оптимізація для швидшого завантаження...',
  'createTask.photos.optimized': 'Зображення успішно оптимізовано',
  'createTask.photos.smaller': 'менше',

  // Review Section
  'createTask.review.title': 'Перегляньте завдання',
  'createTask.review.subtitle': 'Переконайтеся, що все виглядає добре перед публікацією',
  'createTask.review.submit': 'Опублікувати',
  'createTask.review.location': 'Місце',
  'createTask.review.budget': 'Бюджет',
  'createTask.review.timeline': 'Терміни',
  'createTask.review.requirements': 'Вимоги',
  'createTask.review.photos': 'Фото',
  'createTask.review.noTitle': 'Назва ще не додана',
  'createTask.review.noDescription': 'Опис ще не додано',
  'createTask.review.noCity': 'Місто не обрано',
  'createTask.review.fillRequired': 'Заповніть усі обов\'язкові поля для надсилання',

  // Errors
  'createTask.errors.categoryRequired': 'Оберіть категорію',
  'createTask.errors.titleTooShort': 'Назва має містити мінімум 10 символів',
  'createTask.errors.titleTooLong': 'Назва має бути менше 200 символів',
  'createTask.errors.descriptionTooShort': 'Опис має містити мінімум 15 символів',
  'createTask.errors.descriptionTooLong': 'Опис має бути менше 2000 символів',
  'createTask.errors.cityRequired': 'Місто є обов\'язковим',
  'createTask.errors.budgetInvalid': 'Максимум має бути більшим за мінімум',
  'createTask.errors.deadlineInPast': 'Дедлайн має бути сьогодні або в майбутньому',
  'createTask.errors.maxPhotos': 'Максимум 5 фотографій',

  // Validation Dialog
  'createTask.validationDialog.title': 'Виправте наступні проблеми',
  'createTask.validationDialog.subtitle': 'Деякі поля потребують вашої уваги',
  'createTask.validationDialog.fixButton': 'Виправити проблеми',
  'createTask.validationDialog.fieldName.category': 'Категорія',
  'createTask.validationDialog.fieldName.subcategory': 'Підкатегорія',
  'createTask.validationDialog.fieldName.title': 'Назва завдання',
  'createTask.validationDialog.fieldName.description': 'Опис',
  'createTask.validationDialog.fieldName.requirements': 'Вимоги',
  'createTask.validationDialog.fieldName.city': 'Місто',
  'createTask.validationDialog.fieldName.neighborhood': 'Район',
  'createTask.validationDialog.fieldName.exactAddress': 'Точна адреса',
  'createTask.validationDialog.fieldName.budgetMin': 'Мінімальний бюджет',
  'createTask.validationDialog.fieldName.budgetMax': 'Максимальний бюджет',
  'createTask.validationDialog.fieldName.urgency': 'Терміновість',
  'createTask.validationDialog.fieldName.deadline': 'Дедлайн',

  'createTask.imageUpload.error': 'Помилка завантаження зображення',

  // Success messages
  'createTask.success': 'Завдання успішно створено!',
  'createTask.successMessage': 'Ваше завдання опубліковано і тепер видиме фахівцям.',
  'createTask.successWithoutImage': 'Завдання опубліковано без зображення. Можете додати або змінити зображення, редагуючи завдання.',
  'createTask.error': 'Помилка створення завдання',
  'createTask.errorMessage': 'Спробуйте пізніше.',

  // Reopen task flow
  'createTask.reopeningBanner.title': 'Повторне відкриття завдання',
  'createTask.reopeningBanner.originalTask': 'Оригінальне завдання:',
  'createTask.reopeningBanner.description': 'Перегляньте та відредагуйте деталі перед публікацією. Це створить нове завдання.',
  'createTask.reopeningBanner.startFresh': 'Почати заново',
  'createTask.reopenSuccess': 'Завдання успішно відкрито повторно!',
  'createTask.reopenSuccessMessage': 'Ваше завдання повторно опубліковано і відкрите для нових заявок.',

  'taskCard.apply': 'Подати заявку',
  'taskCard.seeDetails': 'Детальніше',
  'taskCard.anonymous': 'Анонім',
  'taskCard.budget.from': 'від',
  'taskCard.budget.to': 'до',
  'taskCard.budget.negotiable': 'Договірна',
  'taskCard.budget.unclear': 'За домовленістю',
  'taskCard.deadline.flexible': 'Гнучко',
  'taskCard.deadline.today': 'Сьогодні',
  'taskCard.deadline.tomorrow': 'Завтра',
  'taskCard.deadline.days': 'днів',
  'taskCard.category.home_repair': 'Домашній ремонт',
  'taskCard.category.delivery_transport': 'Доставка та транспорт',
  'taskCard.category.personal_care': 'Особистий догляд',
  'taskCard.category.personal_assistant': 'Особистий помічник',
  'taskCard.category.learning_fitness': 'Навчання та фітнес',
  'taskCard.category.other': 'Інше',
  // Subcategories
  'taskCard.category.courier-services': 'Кур\'єрські послуги',
  'taskCard.category.logistics': 'Логістика',
  'taskCard.category.handyman': 'Майстер',
  'taskCard.category.plumbing': 'Сантехніка',
  'taskCard.category.electrical': 'Електрика',
  'taskCard.category.cleaning-services': 'Прибирання',
  'taskCard.category.house-cleaning': 'Прибирання будинку',
};
