// Task completion and status management translations
export const taskCompletion = {
  // Task Completion & Status
  'taskStatus.open': 'Відкрите',
  'taskStatus.inProgress': 'У роботі',
  'taskStatus.awaitingConfirmation': 'Очікує підтвердження',
  'taskStatus.completed': 'Завершено',
  'taskStatus.cancelled': 'Скасовано',
  'taskStatus.underReview': 'На розгляді',
  'taskStatus.openTooltip': 'Приймаються заявки від фахівців',
  'taskStatus.inProgressTooltip': 'Робота в процесі виконання',
  'taskStatus.pendingProfessionalTooltip': 'Очікування підтвердження від фахівця',
  'taskStatus.pendingCustomerTooltip': 'Очікування підтвердження від замовника',
  'taskStatus.completedTooltip': 'Завдання успішно завершено',
  'taskStatus.cancelledTooltip': 'Завдання скасовано',
  'taskStatus.disputedTooltip': 'На розгляді адміністратором',

  // Task Completion Actions
  'taskCompletion.markCompleted': 'Позначити як завершене',
  'taskCompletion.confirmCompletion': 'Підтвердити завершення',
  'taskCompletion.rejectCompletion': 'Відхилити завершення',
  'taskCompletion.alreadyMarkedByYou': 'Ви позначили як завершене',
  'taskCompletion.alreadyConfirmedByYou': 'Ви вже підтвердили',
  'taskCompletion.success': 'Завдання позначено як завершене. Очікуємо підтвердження від замовника.',
  'taskCompletion.error': 'Не вдалося позначити завдання. Будь ласка, спробуйте ще раз.',
  'taskCompletion.error.alreadyCompleted': 'Це завдання вже було завершено іншою стороною.',
  'taskCompletion.error.invalidStatus': 'Це завдання не може бути позначене як завершене у поточному статусі.',

  // Mark Completed Dialog (Professional)
  'taskCompletion.markDialog.title': 'Позначити завдання як завершене?',
  'taskCompletion.markDialog.task': 'Завдання',
  'taskCompletion.markDialog.customer': 'Замовник',
  'taskCompletion.markDialog.payment': 'Оплата',
  'taskCompletion.markDialog.question': 'Ви завершили всю роботу?',
  'taskCompletion.markDialog.checkRequirements': 'Усі вимоги виконано',
  'taskCompletion.markDialog.checkSatisfied': 'Замовник задоволений результатом',
  'taskCompletion.markDialog.photos': 'Завантажте фото завершення (необов\'язково)',
  'taskCompletion.markDialog.addPhotos': 'Додати фото',
  'taskCompletion.markDialog.notes': 'Додаткові нотатки',
  'taskCompletion.markDialog.notesPlaceholder': 'Будь-які заключні нотатки про виконану роботу...',

  // Confirm Completion Dialog (Customer)
  'taskCompletion.confirmDialog.title': 'Підтвердити завершення завдання?',
  'taskCompletion.confirmDialog.professional': 'Фахівець',
  'taskCompletion.confirmDialog.task': 'Завдання',
  'taskCompletion.confirmDialog.question': 'Роботу виконано на ваше задоволення?',
  'taskCompletion.confirmDialog.yes': 'Так, я задоволений',
  'taskCompletion.confirmDialog.no': 'Ні, є проблеми',
  'taskCompletion.confirmDialog.simpleConfirmTitle': 'Чудово! Завдання буде позначено як завершене.',
  'taskCompletion.confirmDialog.simpleConfirmMessage': 'Ви можете залишити детальний відгук про фахівця на сторінці завершених завдань.',
  'taskCompletion.confirmDialog.reviewReminder': 'Відгук можна додати зараз або пізніше із завершених завдань.',
  'taskCompletion.confirmDialog.reviewSection': 'Відгук (необов\'язково)',
  'taskCompletion.confirmDialog.reviewSectionHelp': 'Поділіться досвідом та допоможіть іншим приймати рішення.',
  'taskCompletion.confirmDialog.actualPricePaid': 'Фактично сплачена сума',
  'taskCompletion.confirmDialog.actualPricePlaceholder': 'Введіть суму...',
  'taskCompletion.confirmDialog.actualPriceHelp': 'Відстежуйте фактичну оплату порівняно з бюджетом',
  'taskCompletion.confirmDialog.ratingLabel': 'Оцініть досвід',
  'taskCompletion.confirmDialog.reviewLabel': 'Напишіть відгук',
  'taskCompletion.confirmDialog.reviewPlaceholder': 'Поділіться досвідом роботи з {{name}}...',
  'taskCompletion.confirmDialog.reviewHelp': 'Відгук буде видимий у профілі фахівця',
  'taskCompletion.confirmDialog.skipAndConfirm': 'Пропустити та підтвердити',
  'taskCompletion.confirmDialog.confirmWithReview': 'Підтвердити завершення',

  // Rejection Flow
  'taskCompletion.reject.title': 'Поясніть проблему',
  'taskCompletion.reject.reason': 'Чому відхиляєте?',
  'taskCompletion.reject.notCompleted': 'Роботу не завершено',
  'taskCompletion.reject.poorQuality': 'Низька якість',
  'taskCompletion.reject.differentScope': 'Не відповідає домовленостям',
  'taskCompletion.reject.other': 'Інші проблеми',
  'taskCompletion.reject.explain': 'Опишіть проблему',
  'taskCompletion.reject.explainPlaceholder': 'Вкажіть деталі, що потрібно виправити...',
  'taskCompletion.reject.warning': 'Завдання повернеться до статусу "У роботі". Ви зможете обговорити з фахівцем доопрацювання.',
  'taskCompletion.reject.disclaimer': 'Завдання повернеться до статусу "У роботі" і може стати видимим для інших фахівців, якщо роботу не можна завершити з поточним фахівцем.',
  'taskCompletion.reject.button': 'Відхилити',
  'taskCompletion.reject.seriousIssue': 'Зіткнулись із шахрайством або проблемами безпеки?',
  'taskCompletion.reject.reportHint': 'Повідомте про серйозні порушення: шахрайство, обман або погрози',

  // Toast Notifications
  'taskCompletion.confirmSuccess': 'Завдання успішно завершено!',
  'taskCompletion.confirmSuccessDescription': 'Фахівця повідомлено. Ви можете залишити відгук будь-коли.',
  'taskCompletion.confirmError': 'Помилка підтвердження завершення',
  'taskCompletion.rejectSuccess': 'Відгук надіслано',
  'taskCompletion.rejectSuccessDescription': 'Фахівця повідомлено, він може доопрацювати завдання.',
  'taskCompletion.rejectError': 'Помилка надсилання відгуку',

  // Pending Confirmation Banner
  'taskCompletion.pending.waitingCustomer': 'Очікування підтвердження замовника',
  'taskCompletion.pending.waitingProfessional': 'Очікування підтвердження фахівця',
  'taskCompletion.pending.professionalMarkedComplete': 'Фахівець позначив завдання як завершене',
  'taskCompletion.pending.customerMarkedComplete': 'Замовник позначив завдання як завершене',
  'taskCompletion.pending.markedComplete': 'позначив це завдання як завершене.',
  'taskCompletion.pending.youMarked': 'Ви позначили це завдання як завершене.',
  'taskCompletion.pending.waitingFor': 'Очікування',
  'taskCompletion.pending.toConfirm': 'для підтвердження.',

  // Success View
  'taskCompletion.success.title': 'Завдання завершено!',
  'taskCompletion.success.message': 'Чудова робота! Обидві сторони підтвердили завершення завдання.',
  'taskCompletion.success.nextSteps': 'Наступні кроки',
  'taskCompletion.success.step1': 'Залишити відгук',
  'taskCompletion.success.step1Description': 'Поділіться досвідом роботи з {{name}}',
  'taskCompletion.success.step2': 'Архівація через 30 днів',
  'taskCompletion.success.step2Description': 'Завдання буде автоматично заархівовано',
  'taskCompletion.success.leaveReview': 'Залишити відгук',
  'taskCompletion.success.viewDetails': 'Переглянути деталі завдання',

  // Timeline
  'taskCompletion.timeline.title': 'Прогрес завдання',
  'taskCompletion.timeline.started': 'Розпочато',
  'taskCompletion.timeline.proMarked': 'Фахівець позначив як завершене',
  'taskCompletion.timeline.customerConfirmed': 'Замовник підтвердив',
  'taskCompletion.timeline.completed': 'Завершено',
  'taskCompletion.timeline.pending': 'Очікує',
  'taskCompletion.timeline.totalDuration': 'Загальна тривалість',
};
