// Application-related translations - submitting, managing, accepting, rejecting applications
export const applications = {
  // Application Dialog
  'application.title': 'Apply for this Task',
  'application.proposedPrice': 'Your Price',
  'application.pricePlaceholder': 'Enter your price in BGN',
  'application.timeline': 'When can you start?',
  'application.timelineToday': 'Today',
  'application.timeline3days': 'Within 3 days',
  'application.timelineWeek': 'Within a week',
  'application.timelineFlexible': 'Flexible',
  'application.hoursShort': 'h',
  'application.message': 'Why are you the best fit?',
  'application.messagePlaceholder': 'Share your relevant experience and why you\'re perfect for this task...',
  'application.messageInfo': 'Focus on your skills and experience. Contact details can be shared after your application is accepted.',
  'application.characterCount': '{{current}}/{{max}} characters',
  'application.submit': 'Submit Application',
  'application.submitting': 'Submitting...',
  'application.cancel': 'Cancel',
  'application.success': 'Application Submitted!',
  'application.successMessage': 'The task owner will review your application and respond soon.',
  'application.viewApplication': 'View My Application',
  'application.browseOther': 'Browse Other Tasks',
  'application.errors.priceRequired': 'Price is required',
  'application.errors.priceMin': 'Price must be greater than 0',
  'application.errors.timelineRequired': 'Timeline is required',
  'application.errors.messageRequired': 'Message is required',
  'application.errors.messageMin': 'Message must be at least 30 characters',
  'application.errors.messageMax': 'Message cannot exceed 500 characters',
  'application.errors.noPhoneNumbers': 'Phone numbers are not allowed in applications. You can exchange contact info after your application is accepted.',
  'application.errors.noUrls': 'URLs and links are not allowed in applications. You can share your portfolio after your application is accepted.',
  'application.errors.noEmails': 'Email addresses are not allowed in applications. You can exchange contact info after your application is accepted.',
  'application.alreadyApplied': 'You have already applied to this task',
  'application.cannotApplyOwnTask': 'You cannot apply to your own task',
  'application.budget': 'Budget',
  'application.tipClientBudget': 'Tip: Client budget is {{min}} - {{max}} BGN',
  'application.tipShareExperience': 'Tip: Share your relevant experience to stand out',
  'application.successSteps.quickReview': 'Quick Review',
  'application.successSteps.getResponse': 'Get Response',
  'application.successSteps.startWork': 'Start Work',

  // Applications Management
  'applications.title': 'Applications',
  'applications.count': 'applications',
  'applications.sortBy': 'Sort by',
  'applications.sortNewest': 'Newest First',
  'applications.sortPriceLow': 'Price: Low to High',
  'applications.sortPriceHigh': 'Price: High to Low',
  'applications.sortRating': 'Highest Rated',
  'applications.sortExperience': 'Most Experience',
  'applications.filterAll': 'All',
  'applications.filterPending': 'Pending',
  'applications.filterAccepted': 'Accepted',
  'applications.filterRejected': 'Rejected',
  'applications.emptyState.title': 'No applications yet',
  'applications.emptyState.message': 'Your task is live! Professionals will start applying soon.',
  'applications.proposedPrice': 'Proposed Price',
  'applications.timeline': 'Timeline',
  'applications.message': 'Message',
  'applications.portfolio': 'Portfolio',
  'applications.portfolioImages': 'portfolio images',
  'applications.tasksCompleted': 'tasks completed',
  'applications.yearsExperience': 'years experience',
  'applications.viewDetails': 'View Details',
  'applications.freshProfessional': 'New to the platform - help them build their reputation!',
  'applications.new': 'New',
  'applications.acceptApplication': 'Accept',
  'applications.rejectApplication': 'Reject',
  'applications.status': 'Status',
  'applications.statusPending': 'Pending',
  'applications.statusAccepted': 'Accepted',
  'applications.statusRejected': 'Rejected',
  'applications.statusWithdrawn': 'Withdrawn',

  // Application Detail Modal
  'applicationDetail.title': 'Application Details',
  'applicationDetail.professionalProfile': 'Professional Profile',
  'applicationDetail.applicationMessage': 'Application Message',
  'applicationDetail.portfolioGallery': 'Portfolio',
  'applicationDetail.recentReviews': 'Recent Reviews',
  'applicationDetail.close': 'Close',

  // Accept Application Dialog
  'acceptApplication.title': 'Accept Application',
  'acceptApplication.description': 'You are about to accept the application from {{name}}. Please review the details and confirm your agreement.',
  'acceptApplication.agreedPrice': 'Agreed Price',
  'acceptApplication.timeline': 'Timeline',
  'acceptApplication.messageLabel': 'Message to Professional (optional)',
  'acceptApplication.messagePlaceholder': 'Say hi, share availability for a call, or add any extra details...',
  'acceptApplication.messageHelp': 'This message will be sent to {{name}} along with your contact information.',
  'acceptApplication.contactInfo': 'How should the professional contact you?',
  'acceptApplication.noInAppChat': 'We don\'t have in-app chat. Please choose a contact method for the professional to reach you.',
  'acceptApplication.sharePhone': 'Share my phone number',
  'acceptApplication.shareEmail': 'Share my email address',
  'acceptApplication.customContact': 'Provide custom contact information',
  'acceptApplication.customContactLabel': 'Contact Information',
  'acceptApplication.customContactPlaceholder': 'Enter phone, Telegram (@username), Viber link, WhatsApp, or other contact method...',
  'acceptApplication.customContactHelp': 'Provide any contact method where the professional can reach you',
  'acceptApplication.customContactRequired': 'Please provide contact information',
  'acceptApplication.phoneWarning': 'This phone number will be shared with the professional.',
  'acceptApplication.emailWarning': 'Email is slower for coordination. Consider providing phone/Telegram for faster communication.',
  'acceptApplication.privacyPolicy': 'Privacy Policy',
  'acceptApplication.pleaseConfirm': 'Please confirm:',
  'acceptApplication.agreement.priceTimeline': 'I agree to the proposed price ({{price}} {{currency}}) and timeline ({{timeline}})',
  'acceptApplication.agreement.contactSharing': 'I understand my contact information will be shared with {{name}}',
  'acceptApplication.agreement.otherApplications': 'I understand that all other pending applications will be automatically rejected',
  'acceptApplication.warning': 'Once you accept this application, you\'ll be committed to working with {{name}}. All other applications will be rejected automatically.',
  'acceptApplication.confirm': 'Accept Application',
  'acceptApplication.cancel': 'Cancel',

  // Reject Application Dialog
  'rejectApplication.title': 'Reject Application',
  'rejectApplication.description': 'You are about to reject the application from {{name}}. This action will notify the professional that you won\'t be moving forward with their application.',
  'rejectApplication.reasonTitle': 'Reason for rejection (optional)',
  'rejectApplication.reasonHelp': 'Providing a reason helps professionals improve their future applications.',
  'rejectApplication.reasons.betterFit': 'Found a better fit for this task',
  'rejectApplication.reasons.priceHigh': 'Price is too high',
  'rejectApplication.reasons.timelineIssue': 'Timeline doesn\'t work for me',
  'rejectApplication.reasons.changedMind': 'Changed my mind about the task',
  'rejectApplication.reasons.other': 'Other reason',
  'rejectApplication.note': '{{name}} will be notified that their application was not selected. You can still browse other applications and accept a different professional.',
  'rejectApplication.confirm': 'Reject Application',
  'rejectApplication.cancel': 'Cancel',

  // Professional Applications Dashboard
  'myApplications.title': 'My Applications',
  'myApplications.count': '{{count}} applications',
  'myApplications.sortBy': 'Sort by',
  'myApplications.sortNewest': 'Newest First',
  'myApplications.sortOldest': 'Oldest First',
  'myApplications.sortStatus': 'By Status',
  'myApplications.sortTaskDate': 'Task Date',
  'myApplications.sortPriceHigh': 'Price: High to Low',
  'myApplications.sortPriceLow': 'Price: Low to High',
  'myApplications.filterAll': 'All',
  'myApplications.filterPending': 'Pending',
  'myApplications.filterAccepted': 'Accepted',
  'myApplications.filterRejected': 'Rejected',
  'myApplications.filterWithdrawn': 'Withdrawn',
  'myApplications.status.pending': 'Pending',
  'myApplications.status.accepted': 'Accepted',
  'myApplications.status.rejected': 'Rejected',
  'myApplications.status.withdrawn': 'Withdrawn',
  'myApplications.appliedAgo': 'Applied {{time}}',
  'myApplications.acceptedAgo': 'Accepted {{time}}',
  'myApplications.rejectedAgo': 'Rejected {{time}}',
  'myApplications.yourQuote': 'Your Quote',
  'myApplications.taskBudget': 'Task Budget',
  'myApplications.timeline': 'Timeline',
  'myApplications.agreedPrice': 'Agreed Price',
  'myApplications.startDate': 'Starts',
  'myApplications.viewDetails': 'View Details',
  'myApplications.viewTask': 'View Task',
  'myApplications.withdraw': 'Withdraw',
  'myApplications.withdrawConfirm': 'Are you sure you want to withdraw this application?',
  'myApplications.withdrawError': 'Failed to withdraw application',
  'myApplications.messageCustomer': 'Message Customer',
  'myApplications.markStarted': 'Mark as Started',
  'myApplications.markCompleted': 'Mark as Completed',
  'myApplications.reportIssue': 'Report Issue',
  'myApplications.findSimilar': 'Find Similar',
  'myApplications.delete': 'Delete',
  'myApplications.emptyState.title': 'You haven\'t applied to any tasks yet',
  'myApplications.emptyState.message': 'Start browsing available tasks and apply to the ones that match your skills.',
  'myApplications.emptyState.browse': 'Browse Tasks',
  'myApplications.emptyStatePending.title': 'All caught up!',
  'myApplications.emptyStatePending.message': 'You have no pending applications. All your applications have been reviewed.',
  'myApplications.emptyStateAccepted.title': 'No accepted applications yet',
  'myApplications.emptyStateAccepted.message': 'Keep applying! Your next opportunity is just around the corner.',
  'myApplications.emptyStateRejected.title': 'No rejected applications',
  'myApplications.emptyStateRejected.message': 'Great news! None of your applications have been rejected.',
  'myApplications.emptyStateWithdrawn.title': 'No withdrawn applications',
  'myApplications.emptyStateWithdrawn.message': 'You haven\'t withdrawn any applications yet.',
  'myApplications.withdrawDialog.title': 'Withdraw Application?',
  'myApplications.withdrawDialog.description': 'Are you sure you want to withdraw your application for "{{taskTitle}}"?',
  'myApplications.withdrawDialog.reason': 'Reason (optional)',
  'myApplications.withdrawDialog.selectReason': 'Select a reason (optional)',
  'myApplications.withdrawDialog.reasonUnavailable': 'No longer available',
  'myApplications.withdrawDialog.reasonFoundWork': 'Found other work',
  'myApplications.withdrawDialog.reasonChanged': 'Task requirements changed',
  'myApplications.withdrawDialog.reasonPrice': 'Price too low',
  'myApplications.withdrawDialog.reasonOther': 'Other',
  'myApplications.withdrawDialog.warning': 'Once withdrawn, you cannot reapply to this task.',
  'myApplications.withdrawDialog.confirm': 'Confirm Withdrawal',
  'myApplications.withdrawDialog.cancel': 'Cancel',
  'myApplications.detail.taskDetails': 'Task Details',
  'myApplications.detail.yourProposal': 'Your Proposal',
  'myApplications.detail.agreedTerms': 'Agreed Terms',
  'myApplications.detail.rejectionReason': 'Rejection Reason',
  'myApplications.detail.waitingResponse': 'Waiting for Customer Response',
  'myApplications.detail.usuallyResponds': 'Usually responds within 24 hours',
  'myApplications.detail.otherApplicants': '{{count}} other professionals applied',
  'myApplications.detail.nextSteps': 'Next Steps',
  'myApplications.detail.customerApproved': 'Customer approved your application',
  'myApplications.detail.contactCustomer': 'Contact customer to confirm details',
  'myApplications.detail.completeBy': 'Complete task by {{date}}',
  'myApplications.detail.feedback': 'Don\'t take it personally! Keep applying to similar tasks.',

  // My Applications Page (Professional View)
  'myApplications.subtitle': 'Applications you\'ve submitted to tasks',
  'myApplications.browseButton': 'Browse Tasks',
  'myApplications.filter.all': 'All',
  'myApplications.filter.pending': 'Pending',
  'myApplications.filter.accepted': 'Accepted',
  'myApplications.filter.rejected': 'Rejected',
  'myApplications.filter.withdrawn': 'Withdrawn',
  'myApplications.yourProposal': 'Your Proposal',
  'myApplications.proposedPrice': '{{price}} BGN',
  'myApplications.submitted': 'Submitted',
  'myApplications.empty.title': 'No applications yet',
  'myApplications.empty.message': 'You haven\'t applied to any tasks yet. Browse available tasks!',
  'myApplications.empty.browseButton': 'Browse Tasks',

  // My Work Page (Professional View - Accepted Applications Only)
  'myWork.title': 'My Work',
  'myWork.subtitle': 'Manage your active tasks and completed work',
  'myWork.filter.inProgress': 'In Progress',
  'myWork.filter.pendingCompletion': 'Pending Completion',
  'myWork.filter.completed': 'Completed',
  'myWork.empty.inProgress.title': 'No active tasks',
  'myWork.empty.inProgress.message': 'You don\'t have any tasks in progress. Browse available tasks to get started!',
  'myWork.empty.inProgress.browseButton': 'Browse Tasks',
  'myWork.empty.pendingCompletion.title': 'No pending confirmations',
  'myWork.empty.pendingCompletion.message': 'All your tasks are up to date!',
  'myWork.empty.completed.title': 'No completed work yet',
  'myWork.empty.completed.message': 'Completed tasks will appear here.',
  'myWork.customerContact': 'Customer Contact',
  'myWork.taskDeadline': 'Deadline',
  'myWork.startedDaysAgo': 'Started {{days}} days ago',
  'myWork.completedOn': 'Completed on {{date}}',
  'myWork.confirmCompletion': 'Confirm Completion',
  'myWork.viewReview': 'View Review',
  'myWork.withdrawFromTask': 'Withdraw from Task',
  'myWork.leaveReview': 'Leave Review',

  // Professional Withdrawal from Accepted Task
  'professionalWithdraw.title': 'Withdraw from Task',
  'professionalWithdraw.subtitle': 'Withdrawing from: {{taskTitle}}',
  'professionalWithdraw.customer': 'Customer',
  'professionalWithdraw.customerNotification': 'The customer will be notified immediately and the task will be reopened',

  // Rate limiting
  'professionalWithdraw.rateLimit.title': 'You can withdraw {{remaining}} more time(s) this month',
  'professionalWithdraw.rateLimit.message': 'Professionals can withdraw from up to 2 tasks per month',
  'professionalWithdraw.rateLimit.warning': 'Frequent withdrawals may affect your professional rating and account standing',
  'professionalWithdraw.limitExceeded.title': 'Monthly withdrawal limit reached',
  'professionalWithdraw.limitExceeded.message': 'You\'ve reached your withdrawal limit for this month. Please contact support if you have an emergency situation.',

  // Timing warnings
  'professionalWithdraw.earlyWithdrawal.title': 'Early withdrawal - no penalty',
  'professionalWithdraw.earlyWithdrawal.message': 'Since you accepted less than 2 hours ago, this won\'t count toward your monthly limit',
  'professionalWithdraw.lateWithdrawal.title': 'Late withdrawal notice',
  'professionalWithdraw.lateWithdrawal.message': 'Withdrawing more than 24 hours after acceptance significantly impacts the customer and will affect your professional rating',

  // Reasons
  'professionalWithdraw.reasonLabel': 'Why are you withdrawing?',
  'professionalWithdraw.reasons.health_emergency': 'Health issue or emergency',
  'professionalWithdraw.reasons.capacity_issue': 'Overbooked or underestimated time required',
  'professionalWithdraw.reasons.scope_mismatch': 'Task different than expected',
  'professionalWithdraw.reasons.customer_unresponsive': 'Customer not responding to messages',
  'professionalWithdraw.reasons.location_issue': 'Cannot reach location or safety concern',
  'professionalWithdraw.reasons.budget_dispute': 'Customer wants to renegotiate agreed price',
  'professionalWithdraw.reasons.equipment_issue': 'Don\'t have necessary tools or materials',
  'professionalWithdraw.reasons.other': 'Other reason',

  // Form
  'professionalWithdraw.descriptionLabel': 'Additional details',
  'professionalWithdraw.descriptionPlaceholder': 'Please explain your situation...',
  'professionalWithdraw.descriptionHint': 'This helps us improve the platform',
  'professionalWithdraw.confirmButton': 'Withdraw from Task',
  'professionalWithdraw.reputationWarning': 'This withdrawal will be recorded and may affect your professional rating',

  // Success/error
  'professionalWithdraw.successTitle': 'Withdrawal Successful',
  'professionalWithdraw.success': 'You\'ve withdrawn from the task. The customer has been notified.',
  'professionalWithdraw.errorTitle': 'Withdrawal Failed',
  'professionalWithdraw.error': 'Unable to withdraw. Please try again or contact support.',

  // Task Detail Page - Professional View
  'taskDetail.professional.withdraw': 'Withdraw from Task',

  // Accept Application Success Toast
  'acceptApplication.successTitle': '🎉 Application Accepted!',
  'acceptApplication.successDescription': 'You are now working with {{name}}. All other applications have been automatically rejected.',

  // Task In Progress State
  'taskInProgress.title': 'Task In Progress!',
  'taskInProgress.description': 'You have accepted an application. Your task is now in progress with a professional.',
  'taskInProgress.workingWith': 'Working with',
  'taskInProgress.specialization': 'Specialization',
  'taskInProgress.location': 'Location',
  'taskInProgress.agreedPrice': 'Agreed Price',
  'taskInProgress.infoMessage': 'All other applications have been automatically rejected. You can track the progress of your task and communicate with the professional through your task management page.',
  'taskInProgress.viewMyTasks': 'View My Tasks',
  'taskInProgress.viewNotifications': 'View Notifications',
};
