// Authentication and authorization translations
export const auth = {
  'auth.applyForTask': 'Apply for task',
  'auth.askQuestion': 'Ask question',
  'auth.createTask': 'Create a task',
  'auth.loginToContinue': 'Please log in to continue',
  'auth.applyDescription':
    'Submit an application to the client and get the opportunity to work on this task.',
  'auth.questionDescription':
    'Ask the client a question before applying for the task.',
  'auth.createTaskDescription':
    'Create a new task and find trusted professionals to complete your work.',
  'auth.joinAsProfessional': 'Join as Professional',
  'auth.joinAsProfessionalDescription':
    'Start earning by offering your skills and services to customers in your area.',
  'auth.loginDescription':
    'Access your account to manage tasks and connect with professionals.',
  'auth.email': 'Email address',
  'auth.password': 'Password',
  'auth.rememberMe': 'Remember me',
  'auth.forgotPassword': 'Forgot password?',
  'auth.loginOrRegister': 'Login / Register',
  'auth.loginOrRegisterToContinue': 'Please login or register to continue',
  'auth.loginOrRegisterDescription': 'Enter your credentials to access your account or create a new one.',
  'auth.continue': 'Continue',
  'auth.login': 'Log In',
  'auth.or': 'or',
  'auth.noAccount': "Don't have an account?",
  'auth.createAccount': 'Create Account',
  'auth.whyRegister': 'Why register?',
  'auth.benefit1': '• Apply for tasks',
  'auth.benefit2': '• Communicate directly with clients',
  'auth.benefit3': '• Track your history',
  'auth.benefit4': '• Get notifications for new tasks',
  'auth.continueWith': 'Continue with',
  'auth.telegramHint': 'Opens Telegram app or desktop client',

  // Unified auth form
  'auth.fullName': 'Your Name',
  'auth.nameRequired': 'Please provide your name to create an account',
  'auth.nameRequiredHint': 'Name is required to create your account',
  'auth.nameHint': 'Only needed when creating a new account',
  'auth.unexpectedError': 'An unexpected error occurred. Please try again.',

  // WebView detection (Telegram, Facebook, etc. in-app browsers)
  'auth.webViewWarningTitle': 'Google login unavailable',
  'auth.webViewWarningMessage': "Google login doesn't work in this app's browser. Use email/password above, or open in Safari/Chrome.",
  'auth.openInBrowser': 'Open in Browser',
  'auth.popupBlocked': 'Please allow popups for this site to sign in',

  // Email verification
  'auth.email.subject': 'Trudify - Confirm Your Email Address',
  'auth.email.heading': 'Welcome to Trudify!',
  'auth.email.greeting': 'Hi',
  'auth.email.message':
    'Thank you for signing up! Please verify your email address to enable email notifications.',
  'auth.email.buttonText': 'Verify Email Address',
  'auth.email.linkInstruction': 'Or copy and paste this link into your browser:',
  'auth.email.expiresIn': '24 hours',
  'auth.email.footerText': "If you didn't create an account, you can safely ignore this email.",
  'auth.email.footerRights': 'All rights reserved.',

  // Forgot password
  'auth.forgotPassword.title': 'Forgot Password',
  'auth.forgotPassword.description': 'Enter your email and we\'ll send you a link to reset your password.',
  'auth.forgotPassword.emailLabel': 'Email address',
  'auth.forgotPassword.sendResetLink': 'Send Reset Link',
  'auth.forgotPassword.backToLogin': 'Back to login',
  'auth.forgotPassword.checkEmail': 'Check your email',
  'auth.forgotPassword.emailSent': 'We\'ve sent a password reset link to',
  'auth.forgotPassword.emailSentInstructions': 'Please check your inbox and click the link to reset your password.',
  'auth.forgotPassword.didNotReceive': 'Didn\'t receive the email?',
  'auth.forgotPassword.resendLink': 'Resend link',
  'auth.forgotPassword.error': 'Failed to send reset email. Please try again.',

  // Reset password
  'auth.resetPassword.title': 'Reset Password',
  'auth.resetPassword.description': 'Enter your new password below.',
  'auth.resetPassword.newPassword': 'New password',
  'auth.resetPassword.confirmPassword': 'Confirm new password',
  'auth.resetPassword.resetButton': 'Reset Password',
  'auth.resetPassword.success': 'Password reset successful!',
  'auth.resetPassword.successDescription': 'You can now log in with your new password.',
  'auth.resetPassword.goToLogin': 'Go to login',
  'auth.resetPassword.invalidToken': 'Invalid or expired reset link',
  'auth.resetPassword.invalidTokenDescription': 'This password reset link is invalid or has expired. Please request a new one.',
  'auth.resetPassword.passwordMismatch': 'Passwords do not match',
  'auth.resetPassword.passwordTooShort': 'Password must be at least 6 characters',
  'auth.resetPassword.error': 'Failed to reset password. Please try again.',

  // Email verification
  'auth.emailVerification.title': 'Verify Your Email',
  'auth.emailVerification.notVerified': 'Your email is not verified',
  'auth.emailVerification.description': 'Please verify your email to receive notifications and access all features.',
  'auth.emailVerification.resendButton': 'Send Verification Email',
  'auth.emailVerification.resending': 'Sending...',
  'auth.emailVerification.success': 'Verification email sent! Check your inbox.',
  'auth.emailVerification.alreadyVerified': 'Your email is already verified!',
  'auth.emailVerification.error': 'Failed to send verification email. Please try again.',
  'auth.emailVerification.rateLimited': 'Too many requests. Please try again later.',
  'auth.emailVerification.checkSpam': 'Don\'t forget to check your spam folder.',

  // Email verification after signup (auth slide-over)
  'auth.emailVerification.checkInbox': 'Check your inbox!',
  'auth.emailVerification.sentMessage': 'We sent a verification email to',
  'auth.emailVerification.instructions': 'Click the link in the email to verify your account.',
  'auth.emailVerification.resend': 'Resend Verification Email',
  'auth.emailVerification.continue': 'Continue to App',

  // Email verified success page
  'auth.emailVerified.title': 'Email Verified!',
  'auth.emailVerified.description': 'Your email has been successfully verified. You now have full access to all features.',
  'auth.emailVerified.whatNext': 'What would you like to do next?',
  'auth.emailVerified.browseTasks': 'Find Work',
  'auth.emailVerified.createTask': 'Post a Task',
  'auth.emailVerified.completeProfile': 'Complete Your Profile',
  'auth.emailVerified.goHome': 'Go to Homepage',

  // Account Deletion
  'accountDeletion.title': 'Delete Your Account',
  'accountDeletion.loginRequired': 'To delete your account, you need to be logged in.',
  'accountDeletion.whatHappens': 'What happens when you delete your account:',
  'accountDeletion.profileRemoved': 'Your profile is permanently removed',
  'accountDeletion.tasksCancelled': 'Open tasks are cancelled',
  'accountDeletion.reviewsAnonymized': 'Your reviews become anonymous (ratings kept)',
  'accountDeletion.cannotUndo': 'This action cannot be undone',
  'accountDeletion.loginWithGoogle': 'Log in with Google',
  'accountDeletion.loginWithFacebook': 'Log in with Facebook',
  'accountDeletion.backToHome': 'Back to Home',
  'accountDeletion.checkingStatus': 'Checking account status...',
  'accountDeletion.errorTitle': 'Something went wrong',
  'accountDeletion.tryAgain': 'Try Again',
  'accountDeletion.cannotDeleteYet': 'Cannot Delete Account Yet',
  'accountDeletion.completeTasksFirst': 'You have active work that must be completed first.',
  'accountDeletion.activeWork': 'Active tasks blocking deletion:',
  'accountDeletion.asCustomer': 'as customer',
  'accountDeletion.asProfessional': 'as professional',
  'accountDeletion.viewMyTasks': 'View My Tasks',
  'accountDeletion.backToProfile': 'Back to Profile',
  'accountDeletion.confirmTitle': 'Delete Your Account',
  'accountDeletion.confirmDescription': 'This will permanently delete your account and all associated data.',
  'accountDeletion.readyToDelete': 'Pre-flight check passed - ready to delete',
  'accountDeletion.willBeDeleted': 'This will permanently delete:',
  'accountDeletion.openTasksCount': '{{count}} open task(s) will be cancelled',
  'accountDeletion.applicationsCount': '{{count}} pending application(s) will be withdrawn',
  'accountDeletion.messagesCount': '{{count}} message(s)',
  'accountDeletion.notificationsCount': '{{count}} notification(s)',
  'accountDeletion.willBeAnonymized': 'This will be anonymized:',
  'accountDeletion.reviewsWrittenCount': '{{count}} review(s) you wrote (ratings kept)',
  'accountDeletion.irreversibleWarning': 'This action is permanent and cannot be undone. All your data will be permanently deleted.',
  'accountDeletion.confirmPassword': 'Confirm with your password',
  'accountDeletion.enterPassword': 'Enter your password',
  'accountDeletion.passwordDescription': 'Enter your password to confirm account deletion',
  'accountDeletion.passwordOptionalNote': 'Only required if you registered with email and password. Leave empty if you signed up with Google or Facebook.',
  'accountDeletion.noPasswordLink': 'Never set a password? Set one here first',
  'accountDeletion.deleteButton': 'Delete My Account',
  'accountDeletion.cancel': 'Cancel',
  'accountDeletion.invalidPassword': 'Invalid password. Please try again.',
  'accountDeletion.hasActiveTasksError': 'Cannot delete account with active tasks. Please complete or cancel them first.',
  'accountDeletion.deleteError': 'Failed to delete account. Please try again.',
  'accountDeletion.preflightError': 'Failed to check deletion status. Please try again.',
  'accountDeletion.unknownError': 'An unexpected error occurred. Please try again.',
};
