// Common UI terms and global actions
export const common = {
  welcome: 'Welcome',
  login: 'Log In',
  logout: 'Log Out',
  signup: 'Sign Up',
  search: 'Search',
  browse: 'Browse',
  create: 'Create',
  edit: 'Edit',
  delete: 'Delete',
  cancel: 'Cancel',
  dismiss: 'Maybe Later',
  ignore: 'Ignore',
  important: 'Important',
  save: 'Save',
  submit: 'Submit',
  submitting: 'Submitting...',
  loading: 'Loading...',
  error: 'Error',
  success: 'Success',
  back: 'Back',
  next: 'Next',
  previous: 'Previous',
  reviews: 'reviews',
  close: 'Close',
  today: 'Today',
  yesterday: 'Yesterday',
  application: 'application',
  applications: 'applications',

  'common.optional': 'Optional',
  'common.close': 'Close',
  'common.ok': 'OK',
  'common.success': 'Success',
  'common.gotIt': 'Got it',
  'common.days': 'days',
  'common.cancel': 'Cancel',
  'common.edit': 'Edit',
  'common.save': 'Save',
  'common.saving': 'Saving...',
  'common.anonymous': 'Anonymous User',
  'common.goBack': 'Go Back',
  'common.today': 'Today',
  'common.yesterday': 'Yesterday',
  'common.reviews': 'reviews',
  'common.tasksCompleted': 'tasks completed',
  'common.newProfessional': 'New on Trudify',
  'common.negotiable': 'Negotiable',
  'common.loading': 'Loading...',
  'common.applicationSingular': 'application',
  'common.applicationPlural': 'applications',

  // Countries
  'common.country.bulgaria': 'Bulgaria',

  'language.en': 'English',
  'language.bg': 'Български',
  'language.ru': 'Русский',
  'language.ua': 'Українська',

  // Locations
  'locations.sofiaCenter': 'Sofia, Center',
  'locations.sofiaLyulin': 'Sofia, Lyulin',
  'locations.sofiaStudentski': 'Sofia, Studentski Grad',
  'locations.sofiaVitosha': 'Sofia, Vitosha',
  'locations.plovdiv': 'Plovdiv',
  'locations.varna': 'Varna',
  'locations.burgas': 'Burgas',
  'locations.ruse': 'Ruse',
  'locations.staraZagora': 'Stara Zagora',

  // Cities (40 Bulgarian cities)
  'cities.sofia': 'Sofia',
  'cities.plovdiv': 'Plovdiv',
  'cities.varna': 'Varna',
  'cities.burgas': 'Burgas',
  'cities.ruse': 'Ruse',
  'cities.staraZagora': 'Stara Zagora',
  'cities.pleven': 'Pleven',
  'cities.sliven': 'Sliven',
  'cities.dobrich': 'Dobrich',
  'cities.shumen': 'Shumen',
  'cities.pernik': 'Pernik',
  'cities.haskovo': 'Haskovo',
  'cities.yambol': 'Yambol',
  'cities.pazardzhik': 'Pazardzhik',
  'cities.blagoevgrad': 'Blagoevgrad',
  'cities.velikoTarnovo': 'Veliko Tarnovo',
  'cities.vratsa': 'Vratsa',
  'cities.gabrovo': 'Gabrovo',
  'cities.asenovgrad': 'Asenovgrad',
  'cities.vidin': 'Vidin',
  'cities.kazanlak': 'Kazanlak',
  'cities.kardzhali': 'Kardzhali',
  'cities.kyustendil': 'Kyustendil',
  'cities.montana': 'Montana',
  'cities.targovishte': 'Targovishte',
  'cities.dimitrovgrad': 'Dimitrovgrad',
  'cities.silistra': 'Silistra',
  'cities.lovech': 'Lovech',
  'cities.razgrad': 'Razgrad',
  'cities.dupnitsa': 'Dupnitsa',
  'cities.gornaOryahovitsa': 'Gorna Oryahovitsa',
  'cities.smolyan': 'Smolyan',
  'cities.petrich': 'Petrich',
  'cities.sandanski': 'Sandanski',
  'cities.samokov': 'Samokov',
  'cities.sevlievo': 'Sevlievo',
  'cities.lom': 'Lom',
  'cities.karlovo': 'Karlovo',
  'cities.troyan': 'Troyan',
  'cities.bansko': 'Bansko',
  'cities.nesebar': 'Nesebar',
  'cities.sunnyBeach': 'Sunny Beach',
  'cities.svetiVlas': 'Sveti Vlas',
  'cities.sozopol': 'Sozopol',
  'cities.pomorie': 'Pomorie',
  'cities.primorsko': 'Primorsko',
  'cities.goldenSands': 'Golden Sands',
  'cities.albena': 'Albena',
  'cities.balchik': 'Balchik',
  'cities.obzor': 'Obzor',
  'cities.borovets': 'Borovets',

  // Common messages
  'message.taskCreated': 'Task created successfully!',
  'message.profileUpdated': 'Profile updated successfully!',
  'message.applicationSubmitted': 'Application submitted successfully!',
  'error.generic': 'Something went wrong. Please try again.',
  'error.network': 'Network error. Please check your connection.',
  'error.unauthorized': 'You need to log in to access this page.',

  // Auth Required Banner (protected pages)
  'authRequired.title': 'Sign in to continue',
  'authRequired.description': 'You need to be signed in to view this page.',
  'authRequired.signIn': 'Sign In',
  'authRequired.hint': 'Sign in with your existing account or create a new one.',

  // Empty states
  'common.noResults': 'No tasks found',
  'common.noResultsFilter': 'Try selecting a different status filter',
  'common.clearFilters': 'View All Tasks',
  'common.error': 'Error',
  'common.errorGeneric': 'Something went wrong. Please try again.',
  'common.internalServerError': 'Something went wrong. Please try again later.',

  // 404 Page
  'error.404.title': 'Oops! This page went on vacation 🏖️',
  'error.404.description': "It packed its bags and forgot to leave a forwarding address. Even our GPS can't find it!",
  'error.404.subtext': "But don't worry, there's plenty more to explore!",
  'error.404.goHome': 'Go Home',
  'error.404.browseTasks': 'Browse Tasks',
  'error.404.createTask': 'Create Task',

  // Safety & Trust Indicators
  'safety.phoneVerified': 'Phone Verified',
  'safety.emailVerified': 'Email Verified',
  'safety.cleanRecord': 'Clean Safety Record',
  'safety.hasNegativeReviews': 'Has Negative Reviews',
  'safety.multipleReports': 'Multiple Reports',
  'safety.negativeReviewsTooltip': 'This professional has received multiple negative reviews. Please exercise caution.',
  'safety.multipleReportsTooltip': 'This professional has received multiple safety reports from different users.',
  'safety.negativeReviewsWarning': 'This professional has received multiple negative reviews',
  'safety.negativeReviewsWarningMessage': 'Multiple customers have reported issues with service quality. Please review feedback carefully and exercise caution when hiring.',
  'safety.multipleReportsWarning': 'Safety Alert: Multiple Reports',
  'safety.multipleReportsWarningMessage': 'This professional has received multiple safety reports from different customers. We recommend proceeding with extra caution or choosing another professional.',

  // Review Visibility
  'reviews.hiddenReviewsNotice': 'Some reviews are hidden pending verification',
  'reviews.hiddenReviewsTooltip': 'Low-rated reviews are hidden until a pattern is detected to protect against unfair single reviews.',
  'reviews.hiddenCountSingular': '1 review hidden',
  'reviews.hiddenCountPlural': '{count} reviews hidden',
  'reviews.patternDetected': 'Pattern of negative reviews detected',
  'reviews.allNegativeVisible': 'All negative reviews are now visible due to a pattern of issues.',

  // Scam Reporting
  'report.button': 'Report Issue',
  'report.dialogTitle': 'Report Safety Concern',
  'report.dialogDescription': 'Help us maintain a safe community by reporting suspicious behavior or policy violations.',
  'report.typeLabel': 'Type of Issue',
  'report.descriptionLabel': 'Description',
  'report.descriptionPlaceholder': 'Please provide specific details about the issue...',
  'report.evidenceLabel': 'Evidence (Optional)',
  'report.evidenceHint': 'Upload screenshots or photos to support your report',
  'report.evidenceComingSoon': '(Coming soon)',
  'report.submitButton': 'Submit Report',
  'report.cancelButton': 'Cancel',
  'report.successMessage': 'Report submitted successfully. Our team will review it promptly.',
  'report.errorMessage': 'Failed to submit report. Please try again.',
  'report.falseReportWarning': 'False reports may result in action against your account. Please only report genuine safety concerns.',

  // Report Types
  'report.type.fraud_scam': 'Fraud or Scam Attempt',
  'report.type.threatening_behavior': 'Threatening or Aggressive Behavior',
  'report.type.harassment': 'Harassment or Bullying',
  'report.type.identity_theft': 'Fake Profile or Identity Theft',
  'report.type.poor_quality': 'Consistently Poor Work Quality',
  'report.type.no_show': 'Repeated No-Shows',
  'report.type.other': 'Other Safety Concern',

  // Suspension
  'suspension.accountSuspended': 'Account Suspended',
  'suspension.message': 'This account has been temporarily suspended due to multiple safety reports.',
  'suspension.appeal': 'If you believe this is a mistake, you can appeal via email.',
  'suspension.contactEmail': 'Contact: support@taskbridge.com',

  // Notification Warning (Compact Chip)
  'notificationWarning.title': 'Important: Set Up Notifications',
  'notificationWarning.message': 'You won\'t receive updates about applications, messages, or task changes without a notification channel.',
  'notificationWarning.recommendation': 'We recommend connecting Telegram for instant notifications, or verify your email as an alternative.',
  'notificationWarning.compact': 'Set up notifications to get updates about your tasks',
  'notificationWarning.setup': 'Setup',
  'notificationWarning.connectTelegram': 'Connect Telegram',
  'notificationWarning.verifyEmail': 'Verify Email',
  'notificationWarning.dismiss': 'I Understand',

  // Profile Completion Warning (Application Wizard)
  'profileCompletion.stepTitle': 'Complete Your Profile',
  'profileCompletion.stepSubtitle': 'Increase your chances of being hired',
  'profileCompletion.warningTitle': 'Your profile is incomplete',
  'profileCompletion.warningDescription': 'Customers are more likely to hire professionals with complete profiles. Take a moment to fill in the missing information.',
  'profileCompletion.missing': 'Missing',
  'profileCompletion.updateProfile': 'Update Profile',
  'profileCompletion.ignoreAndProceed': 'Ignore and Proceed',

  // Profanity Validation
  'validation.profanityDetected': 'Your text contains inappropriate language. Please revise.',
  'validation.profanityTitle': 'Task title contains inappropriate language',
  'validation.profanityDescription': 'Task description contains inappropriate language',
  'validation.profanityWarning': 'Some words may be flagged. Review before submitting.',
  'validation.profanitySeverity.mild': 'Please avoid using inappropriate language',
  'validation.profanitySeverity.moderate': 'Your text contains offensive language that is not allowed',
  'validation.profanitySeverity.severe': 'Your text contains highly offensive language that violates our community guidelines',

  // City Autocomplete
  'cityAutocomplete.placeholder': 'Search for a city...',
  'cityAutocomplete.lastSearched': 'Last searched:',
  'cityAutocomplete.yourCity': 'Your city:',
  'cityAutocomplete.popular': 'Popular',
  'cityAutocomplete.searching': 'Searching...',
  'cityAutocomplete.noResults': 'No cities found',

  // Language Preference Prompt
  'languagePrompt.title': 'Switch to {language}?',
  'languagePrompt.switch': 'Yes, switch',

  // Unsaved Changes Dialog
  'common.unsavedChanges.title': 'Unsaved Changes',
  'common.unsavedChanges.description': 'You have unsaved changes. Are you sure you want to leave? Your changes will be lost.',
  'common.unsavedChanges.stay': 'Stay',
  'common.unsavedChanges.leave': 'Leave',
};
