export const contentPages = {
  // About Page
  'about.hero.title': 'Connecting Bulgaria with Trusted Professionals',
  'about.hero.subtitle': 'We believe everyone deserves access to reliable, verified professionals for their everyday needs.',

  'about.problem.title': 'The Problem We Solve',
  'about.problem.description': 'Finding reliable help in Bulgaria has always been challenging. Word-of-mouth recommendations are limited, and there\'s no easy way to verify a professional\'s quality before hiring them. We\'re changing that.',

  'about.solution.title': 'Our Solution',
  'about.solution.description': 'Trudify is a platform that connects customers with verified local professionals. Every professional on our platform is verified, rated, and reviewed by real customers.',

  'about.mission.title': 'Our Mission',
  'about.mission.description': 'To make finding trustworthy professionals as easy as a few clicks, while helping skilled workers build sustainable businesses.',

  'about.values.title': 'Our Values',
  'about.values.trust': 'Trust',
  'about.values.trustDesc': 'Every professional is verified. Every review is from a real customer.',
  'about.values.transparency': 'Transparency',
  'about.values.transparencyDesc': 'Clear pricing, honest reviews, no hidden fees.',
  'about.values.fairness': 'Fairness',
  'about.values.fairnessDesc': 'Fair opportunities for professionals, fair prices for customers.',
  'about.values.quality': 'Quality',
  'about.values.qualityDesc': 'We set high standards and help professionals meet them.',

  'about.stats.professionals': 'Verified Professionals',
  'about.stats.tasks': 'Tasks Completed',
  'about.stats.cities': 'Cities Covered',
  'about.stats.satisfaction': 'Customer Satisfaction',

  'about.cta.title': 'Ready to Get Started?',
  'about.cta.subtitle': 'Join thousands of customers and professionals using Trudify today.',
  'about.cta.customer': 'Post a Task',
  'about.cta.professional': 'Join as Professional',

  // How It Works Page
  'howItWorks.hero.title': 'How Trudify Works',
  'howItWorks.hero.subtitle': 'Simple, secure, and straightforward. Here\'s how to get things done.',

  'howItWorks.customers.title': 'For Customers',
  'howItWorks.customers.subtitle': 'Get help in 4 simple steps',
  'howItWorks.customers.step1.title': 'Post Your Task',
  'howItWorks.customers.step1.description': 'Describe what you need done, set your budget, and post it for free. It takes less than 2 minutes.',
  'howItWorks.customers.step2.title': 'Receive Quotes',
  'howItWorks.customers.step2.description': 'Verified professionals in your area will send you quotes. Compare their profiles, reviews, and prices.',
  'howItWorks.customers.step3.title': 'Choose & Chat',
  'howItWorks.customers.step3.description': 'Pick the professional that best fits your needs. Chat with them to discuss details before confirming.',
  'howItWorks.customers.step4.title': 'Get It Done',
  'howItWorks.customers.step4.description': 'The professional completes the work. Pay only when you\'re satisfied and leave a review.',
  'howItWorks.customers.learnMore': 'Learn more & watch video guides',

  'howItWorks.professionals.title': 'For Professionals',
  'howItWorks.professionals.subtitle': 'Grow your business with Trudify',
  'howItWorks.professionals.step1.title': 'Create Your Profile',
  'howItWorks.professionals.step1.description': 'Sign up, verify your identity, and showcase your skills and past work.',
  'howItWorks.professionals.step2.title': 'Browse Tasks',
  'howItWorks.professionals.step2.description': 'Find tasks in your area that match your skills. Filter by category, location, and budget.',
  'howItWorks.professionals.step3.title': 'Submit Quotes',
  'howItWorks.professionals.step3.description': 'Send competitive quotes to customers. Stand out with your profile and reviews.',
  'howItWorks.professionals.step4.title': 'Build Your Reputation',
  'howItWorks.professionals.step4.description': 'Complete tasks, collect reviews, and grow your business. Top-rated professionals get more work.',
  'howItWorks.professionals.learnMore': 'Learn more & watch video guides',

  'howItWorks.cta.title': 'Ready to Start?',
  'howItWorks.cta.subtitle': 'Whether you need help or want to offer your services, we\'ve got you covered.',

  // FAQ Page
  'faq.hero.title': 'Frequently Asked Questions',
  'faq.hero.subtitle': 'Find answers to common questions about using Trudify.',

  'faq.customers.title': 'For Customers',
  'faq.customers.q1': 'How much does it cost to post a task?',
  'faq.customers.a1': 'Posting a task on Trudify is completely free. You only pay the professional when the work is completed to your satisfaction.',
  'faq.customers.q2': 'How do I know professionals are trustworthy?',
  'faq.customers.a2': 'Professionals on Trudify build their reputation through real customer reviews and completed work history. You can see their ratings, reviews from other customers, and track record before hiring.',
  'faq.customers.q3': 'What if I\'m not satisfied with the work?',
  'faq.customers.a3': 'Trudify connects customers with professionals - all work arrangements are between you and the professional. If unsatisfied, you can leave an honest review to warn others, or report the professional. Multiple reports lead to account restrictions.',
  'faq.customers.q4': 'Can I cancel a task?',
  'faq.customers.a4': 'Yes, you can cancel a task at any time, even after a professional has started working on it. To prevent abuse, there is a monthly limit on cancellations.',
  'faq.customers.q5': 'How do payments work?',
  'faq.customers.a5': 'Payment is arranged directly between you and the professional. The budget you set is indicative - the final price should be agreed with the professional once they fully understand the scope of work.',

  'faq.professionals.title': 'For Professionals',
  'faq.professionals.q1': 'How do I sign up as a professional?',
  'faq.professionals.a1': 'Create an account, complete your profile with your skills and experience, and start applying to tasks. Build your reputation through quality work and collect reviews from satisfied customers.',
  'faq.professionals.q2': 'What fees does Trudify charge?',
  'faq.professionals.a2': 'Currently, Trudify is free for professionals during our launch period. We may introduce a small commission on completed tasks in the future.',
  'faq.professionals.q3': 'How do I get more jobs?',
  'faq.professionals.a3': 'Complete your profile, add photos of your work, respond quickly to tasks, deliver quality work, and collect positive reviews. Top-rated professionals appear higher in search results.',
  'faq.professionals.q4': 'Can I work in multiple cities?',
  'faq.professionals.a4': 'Yes, you can set your service areas to include multiple cities and neighborhoods.',
  'faq.professionals.q5': 'How do reviews work?',
  'faq.professionals.a5': 'After completing a task, customers can leave a review and rating. These are displayed on your profile and help build your reputation.',

  'faq.general.title': 'General Questions',
  'faq.general.q1': 'Is Trudify available in my city?',
  'faq.general.a1': 'Trudify is currently available in major Bulgarian cities including Sofia, Plovdiv, Varna, Burgas, Ruse, Stara Zagora, Pleven, and Sliven. We\'re expanding to more cities soon.',
  'faq.general.q2': 'What services are available?',
  'faq.general.a2': 'We offer a wide range of services including home repairs, cleaning, moving, IT support, tutoring, beauty services, and many more. Browse our categories to see all available services.',
  'faq.general.q3': 'How do I contact support?',
  'faq.general.a3': 'Email us at support@trudify.com or reach out through our social media channels (links in footer). We typically respond within 24 hours.',
  'faq.general.q4': 'How do I get notified about new tasks or applications?',
  'faq.general.a4': 'Connect your Telegram account in profile settings to receive free instant notifications. Professionals get notified about task invitations, and customers receive alerts when professionals apply to their tasks.',

  'faq.resources.title': 'Helpful Resources',
  'faq.resources.customerGuide': 'Guide for Customers',
  'faq.resources.customerGuideDesc': 'Watch video tutorials on how to post tasks and hire professionals.',
  'faq.resources.professionalGuide': 'Guide for Professionals',
  'faq.resources.professionalGuideDesc': 'Learn how to find work and grow your business on Trudify.',
  'faq.resources.blogPost': 'Looking for Work?',
  'faq.resources.blogPostDesc': 'Read our guide on finding freelance work in Bulgaria.',
  'faq.resources.watchVideos': 'Watch videos',
  'faq.resources.readArticle': 'Read article',

  'faq.cta.title': 'Still have questions?',
  'faq.cta.subtitle': 'Our support team is here to help.',
  'faq.cta.contact': 'Contact Support',

  // For Professionals Page
  'forProfessionals.hero.title': 'Grow Your Business with Trudify',
  'forProfessionals.hero.subtitle': 'Join thousands of professionals finding new customers and building their reputation.',
  'forProfessionals.hero.cta': 'Start Getting Customers',

  'forProfessionals.benefits.title': 'Why Join Trudify?',
  'forProfessionals.benefits.noFees': 'No Upfront Fees',
  'forProfessionals.benefits.noFeesDesc': 'Join for free. No subscription, no hidden costs. You only succeed when you win work.',
  'forProfessionals.benefits.customers': 'Steady Stream of Customers',
  'forProfessionals.benefits.customersDesc': 'Access a constant flow of local customers looking for your services. No more waiting for word-of-mouth referrals.',
  'forProfessionals.benefits.reputation': 'Build Your Reputation',
  'forProfessionals.benefits.reputationDesc': 'Collect reviews, showcase your work, and build a professional online presence that works for you 24/7.',
  'forProfessionals.benefits.mobile': 'Work on Your Terms',
  'forProfessionals.benefits.mobileDesc': 'Choose the jobs you want, set your own prices, and manage everything from your phone.',

  'forProfessionals.howEarnings.title': 'How Earnings Work',
  'forProfessionals.howEarnings.description': 'You set your own prices and negotiate directly with customers. Trudify is currently free for professionals during our launch period.',

  'forProfessionals.videoGuides.title': 'Video Guides',
  'forProfessionals.videoGuides.subtitle': 'Watch quick tutorials to get started in minutes',
  'forProfessionals.videoGuides.video1.title': 'Getting Started',
  'forProfessionals.videoGuides.video1.description': 'How to register and set up your professional profile',
  'forProfessionals.videoGuides.video2.title': 'Finding Work',
  'forProfessionals.videoGuides.video2.description': 'How to search tasks, apply, and get notifications',

  'forProfessionals.stats.title': 'Join a Growing Community',

  'forProfessionals.cta.title': 'Ready to Start Earning?',
  'forProfessionals.cta.subtitle': 'Create your profile today and start connecting with customers in your area.',
  'forProfessionals.cta.button': 'Create Professional Profile',

  // For Customers Page
  'forCustomers.hero.title': 'Get Things Done with Trudify',
  'forCustomers.hero.subtitle': 'Find verified professionals for any task. Post your job and get quotes in minutes.',
  'forCustomers.hero.cta': 'Post Your First Task',

  'forCustomers.benefits.title': 'Why Customers Love Trudify',
  'forCustomers.benefits.fast': 'Quick Results',
  'forCustomers.benefits.fastDesc': 'Post a task and receive quotes within hours. No more endless searching or waiting.',
  'forCustomers.benefits.verified': 'Verified Professionals',
  'forCustomers.benefits.verifiedDesc': 'Every professional is verified. View their ratings, reviews, and completed work history.',
  'forCustomers.benefits.communicate': 'Easy Communication',
  'forCustomers.benefits.communicateDesc': 'Chat directly with professionals to discuss details, negotiate prices, and confirm schedules.',
  'forCustomers.benefits.reviews': 'Trusted Reviews',
  'forCustomers.benefits.reviewsDesc': 'Real reviews from real customers help you choose the best professional for your task.',

  'forCustomers.howItWorks.title': 'Simple and Free',
  'forCustomers.howItWorks.description': 'Posting tasks on Trudify is completely free. You only pay the professional directly after the work is done and you are satisfied.',

  'forCustomers.videoGuides.title': 'Video Guides',
  'forCustomers.videoGuides.subtitle': 'Learn how to use Trudify in just a few minutes',
  'forCustomers.videoGuides.video1.title': 'Getting Started',
  'forCustomers.videoGuides.video1.description': 'How to register and post your first task',
  'forCustomers.videoGuides.video2.title': 'Invite Professional',
  'forCustomers.videoGuides.video2.description': 'How to invite a specific professional to your task',
  'forCustomers.videoGuides.video3.title': 'Review Applications',
  'forCustomers.videoGuides.video3.description': 'How to review and accept applications',
  'forCustomers.videoGuides.video4.title': 'Leave a Review',
  'forCustomers.videoGuides.video4.description': 'How to leave feedback after task completion',

  'forCustomers.stats.title': 'Join Thousands of Happy Customers',

  'forCustomers.cta.title': 'Ready to Get Started?',
  'forCustomers.cta.subtitle': 'Post your first task for free and find the perfect professional today.',
  'forCustomers.cta.button': 'Post a Task Now',

  // Pricing Page
  'pricing.hero.title': 'Simple, Transparent Pricing',
  'pricing.hero.subtitle': 'No hidden fees, no surprises. Here\'s how pricing works on Trudify.',

  'pricing.customers.title': 'For Customers',
  'pricing.customers.free': 'Free',
  'pricing.customers.description': 'Posting tasks is always free',
  'pricing.customers.feature1': 'Post unlimited tasks',
  'pricing.customers.feature2': 'Receive quotes from professionals',
  'pricing.customers.feature3': 'Chat with professionals',
  'pricing.customers.feature4': 'No payment until work is done',
  'pricing.customers.feature5': 'Leave reviews after completion',

  'pricing.professionals.title': 'For Professionals',
  'pricing.professionals.free': 'Free (Launch Period)',
  'pricing.professionals.description': 'Join and start earning with no fees',
  'pricing.professionals.feature1': 'Create your professional profile',
  'pricing.professionals.feature2': 'Browse and apply to tasks',
  'pricing.professionals.feature3': 'Unlimited quote submissions',
  'pricing.professionals.feature4': 'Build your reputation with reviews',
  'pricing.professionals.feature5': 'No commission during launch',
  'pricing.professionals.note': 'After the launch period, we may introduce a small commission on completed tasks. Current users will be grandfathered with preferential rates.',

  'pricing.cta.title': 'Get Started Today',
  'pricing.cta.subtitle': 'Join Trudify and experience the easiest way to find help or grow your business.',

  // Testimonials Page
  'testimonials.hero.title': 'What Our Users Say',
  'testimonials.hero.subtitle': 'Real stories from customers and professionals using Trudify.',

  'testimonials.customers.title': 'Happy Customers',
  'testimonials.professionals.title': 'Successful Professionals',

  'testimonials.cta.title': 'Join Our Community',
  'testimonials.cta.subtitle': 'Become part of thousands of satisfied users.',

  // Giveaway Page
  'giveaway.hero.badge': 'Every 2 Months',
  'giveaway.hero.title': 'Earn Money & Win Prizes!',
  'giveaway.hero.subtitle': 'Find work fast, get paid for your skills, and win valuable gift cards every two months.',
  'giveaway.hero.subtitleExtra': 'Join thousands of professionals and customers who are already earning and winning on Trudify!',
  'giveaway.hero.totalPrizes': 'Total Prize Pool',
  'giveaway.hero.prizeCount': '10 Gift Cards',
  'giveaway.hero.ctaProfessional': 'Find Work Now',
  'giveaway.hero.ctaCustomer': 'Post a Task',

  'giveaway.whyTrudify.title': 'Why Choose Trudify?',
  'giveaway.whyTrudify.subtitle': 'Whether you want to find work quickly, earn extra money, or get help with tasks - Trudify is the platform for you. Plus, win prizes just for being active!',

  'giveaway.benefits.professionals.title': 'For Professionals - Find Work & Earn Money',
  'giveaway.benefits.professionals.findWork.title': 'Find Work Fast',
  'giveaway.benefits.professionals.findWork.description': 'Get access to hundreds of local jobs. No more waiting for calls - work comes to you!',
  'giveaway.benefits.professionals.earnMoney.title': 'Earn More Money',
  'giveaway.benefits.professionals.earnMoney.description': 'Set your own prices and earn what you deserve. Get paid directly by customers.',
  'giveaway.benefits.professionals.growBusiness.title': 'Grow Your Business',
  'giveaway.benefits.professionals.growBusiness.description': 'Build your reputation with reviews. Top professionals get more work opportunities.',
  'giveaway.benefits.professionals.bonusRewards.title': 'Win Bonus Rewards',
  'giveaway.benefits.professionals.bonusRewards.description': 'Every completed task enters you into our bi-monthly giveaway. More work = more chances!',

  'giveaway.benefits.customers.title': 'For Customers - Get Help Fast',
  'giveaway.benefits.customers.fastHelp.title': 'Quick Solutions',
  'giveaway.benefits.customers.fastHelp.description': 'Post a task and get quotes within hours. Find the right professional fast.',
  'giveaway.benefits.customers.verified.title': 'Verified Professionals',
  'giveaway.benefits.customers.verified.description': 'All professionals are verified. Read reviews and choose with confidence.',
  'giveaway.benefits.customers.fairPrices.title': 'Fair Prices',
  'giveaway.benefits.customers.fairPrices.description': 'Compare quotes and choose the best offer. No hidden fees, no surprises.',
  'giveaway.benefits.customers.winPrizes.title': 'Win Gift Cards',
  'giveaway.benefits.customers.winPrizes.description': 'Post tasks and win prizes! Customers are eligible for our bi-monthly giveaway too.',

  'giveaway.nextDraw.label': 'Next Draw',
  'giveaway.nextDraw.date': 'February 2026',
  'giveaway.nextDraw.frequency': 'Draw Frequency',
  'giveaway.nextDraw.frequencyValue': 'Every 2 Months',

  'giveaway.prizes.title': 'Prize Pool',
  'giveaway.prizes.subtitle': '10 lucky winners will receive gift cards from top brands. Be active on Trudify and you could be next!',
  'giveaway.prizes.grand': '1st Place',
  'giveaway.prizes.second': '2nd Place',
  'giveaway.prizes.third': '3rd Place',
  'giveaway.prizes.remaining': 'Places 4-10',
  'giveaway.prizes.remainingValue': '7 x 20 EUR Gift Cards',
  'giveaway.prizes.sponsorNote': 'Gift card brands will be announced closer to the draw date. We are working with premium partners!',

  'giveaway.howItWorks.title': 'How to Participate',
  'giveaway.howItWorks.subtitle': 'Three simple steps to start earning and winning',
  'giveaway.howItWorks.step1.title': 'Create Your Free Profile',
  'giveaway.howItWorks.step1.description': 'Sign up in minutes. Create a professional profile to find work, or post your first task as a customer.',
  'giveaway.howItWorks.step2.title': 'Complete Tasks & Earn',
  'giveaway.howItWorks.step2.description': 'Professionals: find and complete jobs. Customers: post tasks and get them done. Both earn entries!',
  'giveaway.howItWorks.step3.title': 'Win Prizes Automatically',
  'giveaway.howItWorks.step3.description': 'Every completed task is an automatic entry. No extra steps needed - just work and win!',

  'giveaway.seo.title': 'Start Earning Today in Bulgaria',
  'giveaway.seo.paragraph1': 'Looking for work in Bulgaria? Trudify connects skilled professionals with local customers who need help. Whether you are a plumber, electrician, cleaner, driver, IT specialist, or offer any other service - find jobs fast and get paid what you deserve.',
  'giveaway.seo.paragraph2': 'Need help with a task? Post your job for free and receive quotes from verified professionals in your area. From home repairs and cleaning to IT support and moving services - find reliable help in Sofia, Plovdiv, Varna, Burgas, and other Bulgarian cities.',
  'giveaway.seo.paragraph3': 'Join Trudify today and be part of a growing community. Earn money doing what you love, help people in your neighborhood, and win prizes along the way. The more active you are, the more you can earn and win!',

  'giveaway.rules.title': 'Giveaway Rules',
  'giveaway.rules.rule1': 'One completed task = one entry into the giveaway',
  'giveaway.rules.rule2': 'Both professionals and customers are eligible to win',
  'giveaway.rules.rule3': 'Winners are selected randomly from all entries',
  'giveaway.rules.rule4': 'Gift cards are delivered digitally via email or Telegram',

  'giveaway.cta.title': 'Ready to Earn & Win?',
  'giveaway.cta.subtitle': 'Join thousands of professionals and customers on Trudify. Find work, get help, and win prizes - all in one place!',
  'giveaway.cta.joinProfessional': 'Start Earning Now',
  'giveaway.cta.postTask': 'Post Your First Task',
}
