// Navigation, header, and footer translations
export const navigation = {
  'nav.home': 'Home',
  'nav.browseTasks': 'browse tasks',
  'nav.createTask': 'post a task',
  'nav.profile': 'profile',
  'nav.profileCustomer': 'I am Client',
  'nav.profileProfessional': 'I am Professional',
  'nav.howItWorks': 'how it works',
  'nav.categories': 'categories',
  'nav.forProfessionals': 'For Professionals',
  'nav.browseProfessionals': 'browse professionals',
  'nav.forCustomers': 'For Customers',
  'nav.forClient': 'For Client',
  'nav.myTasks': 'My Tasks',
  'nav.myPostedTasks': 'My Tasks',
  'nav.myApplications': 'My Applications',
  'nav.myWork': 'My Work',
  'nav.tasksIPosted': 'tasks I posted',
  'nav.tasksIAmDoing': 'tasks I am doing',
  'nav.findProfessional': 'find a professional',
  'nav.findAnotherTask': 'find another task',
  'nav.help': 'Help',
  'nav.language': 'Language',
  'nav.general': 'General',
  'nav.discover': 'Discover',
  'nav.closeMenu': 'Close Menu',

  // Footer
  'footer.company.description':
    'Connecting people with qualified professionals for all kinds of services in Bulgaria.',
  'footer.quickLinks.title': 'Quick Links',
  'footer.quickLinks.howItWorks': 'How It Works',
  'footer.quickLinks.categories': 'Categories',
  'footer.quickLinks.forProfessionals': 'For Professionals',
  'footer.quickLinks.browseTasks': 'Browse Tasks',
  'footer.quickLinks.createTask': 'Create Task',
  'footer.legal.title': 'Legal',
  'footer.legal.terms': 'Terms of Service',
  'footer.legal.privacy': 'Privacy Policy',
  'footer.contact.title': 'Contact',
  'footer.contact.subtitle': 'Get in touch',
  'footer.language.label': 'Language',
  'footer.copyright': '© 2025 Obod Soft LTD. All rights reserved.',
};
