// Notifications, task detail, and posted tasks translations
export const notifications = {
  // Notifications
  'notifications.title': 'Notifications',
  'notifications.markAllRead': 'Mark all as read',
  'notifications.tabAll': 'All',
  'notifications.tabApplications': 'Applications',
  'notifications.tabTasks': 'Tasks',
  'notifications.tabMessages': 'Messages',
  'notifications.empty.title': 'No notifications yet',
  'notifications.empty.message': "You'll be notified when someone applies to your tasks or responds to your applications.",
  'notifications.empty.filterMessage': 'No notifications in this category.',
  'notifications.emptyUnread.title': "You're all caught up!",
  'notifications.emptyUnread.message': 'All notifications have been read.',
  'notifications.viewApplication': 'View Application',
  'notifications.viewTask': 'View Task',

  // Task Detail
  'taskDetail.backToTasks': 'Back to tasks',
  'taskDetail.requirements': 'Requirements:',
  'taskDetail.keyInformation': 'Key Information',
  'taskDetail.client': 'Task Author',
  'taskDetail.loginForMore': 'Login for more',
  'taskDetail.loginMessage': 'Log in to see full information',
  'taskDetail.completedTasks': 'completed tasks',
  'taskDetail.memberSince': 'Member since',
  'taskDetail.similarTasks': 'Similar Tasks',
  'taskDetail.apply': 'Apply for Task',
  'taskDetail.askQuestion': 'Ask Question',
  'taskDetail.applicationsCount': 'applications',
  'taskDetail.timeAgo': 'ago',
  'taskDetail.today': 'Today',
  'taskDetail.tomorrow': 'Tomorrow',
  'taskDetail.days': 'days',
  'taskDetail.flexible': 'Flexible',
  'taskDetail.negotiable': 'Negotiable',
  'taskDetail.urgency.same_day': 'Urgent - today',
  'taskDetail.urgency.within_week': 'Within a week',
  'taskDetail.urgency.flexible': 'Flexible deadline',
  'taskDetail.urgency.default': 'Unspecified',
  'taskDetail.status': 'Status',
  'taskDetail.statusTypes.vacant': 'Vacant',
  'taskDetail.statusTypes.applied': 'Applied',
  'taskDetail.statusTypes.done': 'Done',
  'taskDetail.statusTypes.archived': 'Archived',
  'taskDetail.appliedTooltip': 'You have applied to this task. The client may accept or reject your application.',

  'taskDetail.share': 'Share',
  'taskDetail.activity': 'Task Activity',
  'taskDetail.applications': 'Applications',
  'taskDetail.questions': 'Questions',
  'taskDetail.accept': 'Accept',
  'taskDetail.reject': 'Reject',
  'taskDetail.message': 'Message',
  'taskDetail.reply': 'Reply',
  'taskDetail.yourReply': 'Your reply:',
  'taskDetail.price': 'Price:',
  'taskDetail.tasks': 'tasks',

  // Posted Tasks Page (Customer View)
  'postedTasks.title': 'My Posted Tasks',
  'postedTasks.subtitle': 'Manage tasks you\'ve created',
  'postedTasks.createTask': 'Create Task',
  'postedTasks.filter.all': 'All',
  'postedTasks.filter.open': 'Open',
  'postedTasks.filter.inProgress': 'In Progress',
  'postedTasks.filter.awaitingConfirmation': 'Awaiting Confirmation',
  'postedTasks.filter.completed': 'Completed',
  'postedTasks.filter.cancelled': 'Cancelled',
  'postedTasks.applicationsCount': '{{count}} applications',
  'postedTasks.viewApplications': 'View Applications',
  'postedTasks.viewDetails': 'View Details',
  'postedTasks.acceptedProfessional': 'Accepted Professional',
  'postedTasks.awaitingYourConfirmation': 'Awaiting Your Confirmation',
  'postedTasks.markedComplete': 'marked this task as complete',
  'postedTasks.reportIssue': 'Report Issue',
  'postedTasks.cancelTask': 'Cancel Task',
  'postedTasks.cancelTaskConfirm': 'Are you sure you want to cancel this task? The professional will be notified.',
  'postedTasks.reopenTask': 'Reopen Task',
  'postedTasks.reopenTaskConfirm': 'Reopen this task to find a new professional? This will remove the current assignment.',
  'postedTasks.empty.title': 'No tasks posted yet',
  'postedTasks.empty.message': 'You haven\'t posted any tasks yet. Create your first task!',
  'postedTasks.empty.createButton': 'Create Task',

  // Cancel Task Dialog
  'cancelTask.title': 'Cancel Task',
  'cancelTask.professional': 'Professional',
  'cancelTask.professionalNotification': 'The professional will be notified about the cancellation',
  'cancelTask.reasonLabel': 'Why are you canceling this task?',
  'cancelTask.reasons.noShow': 'Professional never showed up',
  'cancelTask.reasons.abandoned': 'Professional abandoned the work',
  'cancelTask.reasons.unresponsive': 'Professional is unresponsive',
  'cancelTask.reasons.changedRequirements': 'My requirements changed',
  'cancelTask.reasons.foundAlternative': 'Found another solution',
  'cancelTask.reasons.other': 'Other reason',
  'cancelTask.descriptionLabel': 'Additional details (optional)',
  'cancelTask.descriptionPlaceholder': 'Please provide any additional context...',
  'cancelTask.descriptionHint': 'Help us understand what happened',
  'cancelTask.confirmButton': 'Cancel Task',
  'cancelTask.rateLimit.title': 'You can cancel {{remaining}} more task(s) this month',
  'cancelTask.rateLimit.message': 'To prevent abuse, users can cancel up to {{max}} tasks per month',
  'cancelTask.rateLimit.lastWarning': 'This is your last free cancellation this month. Use it wisely!',
  'cancelTask.limitExceeded.title': 'Monthly cancellation limit reached',
  'cancelTask.limitExceeded.message': 'You\'ve reached your cancellation limit for this month. Frequent cancellations may affect your account standing. Please contact support if you need assistance.',
};
