// Notifications, task detail, and posted tasks translations
export const notifications = {
  // Notifications
  'notifications.title': 'Notifications',
  'notifications.cleanup': 'Clean up',
  'notifications.markAsRead': 'Mark Read',
  'notifications.cleanupConfirm.title': 'Delete all notifications?',
  'notifications.cleanupConfirm.message': 'All notifications will be permanently deleted.',
  'notifications.cleanupConfirm.cancel': 'Cancel',
  'notifications.cleanupConfirm.confirm': 'Delete',
  'notifications.tabAll': 'All',
  'notifications.tabApplications': 'Applications',
  'notifications.tabTasks': 'Tasks',
  'notifications.tabMessages': 'Messages',
  'notifications.empty.title': 'No notifications yet',
  'notifications.empty.message': "You'll be notified when someone applies to your tasks or responds to your applications.",
  'notifications.empty.filterMessage': 'No notifications in this category.',
  'notifications.emptyUnread.title': "You're all caught up!",
  'notifications.emptyUnread.message': 'All notifications have been read.',
  'notifications.viewApplication': 'View Application',
  'notifications.viewMyWork': 'View My Work',
  'notifications.viewTask': 'View Task',
  'notifications.getStarted': 'Get Started',
  'notifications.customerContact': 'Customer Contact Information',
  'notifications.customerMessage': 'Message from customer',

  // Notification Content (titles and messages)
  'notifications.content.welcome.title': 'Welcome to Trudify!',
  'notifications.content.welcome.message': 'Your account has been created successfully. Get started by posting a task or browsing work opportunities!',
  'notifications.content.applicationReceived.title': 'New Application',
  'notifications.content.applicationReceived.message': '{{professionalName}} applied to your task "{{taskTitle}}"',
  'notifications.content.applicationAccepted.title': 'Application Accepted! 🎉',
  'notifications.content.applicationAccepted.message': 'Your application for "{{taskTitle}}" was accepted by {{customerName}}',
  'notifications.content.applicationRejected.title': 'Application Update',
  'notifications.content.applicationRejected.message': 'Your application for "{{taskTitle}}" was not selected this time. Keep applying!',
  'notifications.content.taskCompleted.title': 'Task Completed - Review Needed ⭐',
  'notifications.content.taskCompleted.message': '"{{taskTitle}}" is complete! Please take a moment to review {{professionalName}}\'s work.',
  'notifications.content.professionalWithdrew.title': 'Professional Withdrew',
  'notifications.content.professionalWithdrew.message': '{{professionalName}} has withdrawn from your task "{{taskTitle}}". Your task is now open for new applications.',
  'notifications.content.removedByCustomer.title': 'Customer Removed You from Task',
  'notifications.content.removedByCustomer.message': 'You were removed from task "{{taskTitle}}" by the customer.',
  'notifications.content.taskCancelled.title': 'Task Cancelled',
  'notifications.content.taskCancelled.message': 'The task "{{taskTitle}}" has been cancelled by the client',

  // Telegram notification templates
  'notifications.telegram.viewHere': 'View here',
  'notifications.telegram.welcome': '👋 <b>Welcome to Trudify, {{userName}}!</b>\n\n🎉 Congratulations! Your account has been created successfully.\n\n✅ You\'ll receive instant notifications here for:\n• New applications on your tasks\n• Messages from professionals\n• Task updates and completions\n\nGet started now:\n📝 Post a task or\n💼 Browse work opportunities!',
  'notifications.telegram.applicationReceived': '✅ <b>New Application!</b>\n\n<b>{{professionalName}}</b> has applied to your task:\n"{{taskTitle}}"\n\n{{link}}',
  'notifications.telegram.applicationAccepted': '🎉 <b>Application Accepted!</b>\n\nYour application for "{{taskTitle}}" has been accepted by {{customerName}}!{{customerMessageSection}}\n\n<b>Contact Information:</b>\n{{customerContact}}\n\n{{link}}',
  'notifications.telegram.taskCompleted': '✅ <b>Task Completed - Review Needed!</b>\n\nYour task "<b>{{taskTitle}}</b>" was completed by {{professionalName}}.\n\n⭐ <b>Please leave a review</b> to help others find great professionals.\n\n{{link}}',
  'notifications.telegram.professionalWithdrew': '⚠️ <b>Professional Withdrew</b>\n\n<b>{{professionalName}}</b> has withdrawn from your task:\n"{{taskTitle}}"\n\n📋 Your task is now <b>open again</b> for new applications.\n\n👉 <b>Next Steps:</b>\n• Review your task details\n• Check if budget is competitive\n• Respond to new applications quickly\n\n🔗 View Task: {{link}}',
  'notifications.telegram.removedByCustomer': '⚠️ <b>Customer Removed You from Task</b>\n\nYou were removed from task:\n"<b>{{taskTitle}}</b>"\n\n📋 The task has been <b>reopened</b> for new applications.\n\n👉 <b>Next Steps:</b>\n• Browse other available tasks\n• Apply to tasks that match your skills\n• Focus on building positive client relationships\n\n🔗 Browse Tasks: {{link}}',
  'notifications.telegram.taskCancelled': '❌ <b>Task Cancelled</b>\n\nThe task "{{taskTitle}}" has been cancelled by the client.\n\nYour application and all discussions related to this task have been removed.\n\n👉 <b>Next Steps:</b>\n• Browse other available tasks\n• Apply to tasks that match your skills\n\n🔗 Browse Tasks: {{link}}',
  'notifications.telegram.taskInvitation': '🎯 <b>New Task Invitation!</b>\n\n<b>{{customerName}}</b> has invited you to apply for their task:\n\n📋 <b>{{taskTitle}}</b>\n🏷️ Category: {{taskCategory}}\n\n👉 View and apply here:\n{{link}}',

  // Task Detail
  'taskDetail.backToTasks': 'Back to tasks',
  'taskDetail.requirements': 'Requirements:',
  'taskDetail.keyInformation': 'Key Information',
  'taskDetail.client': 'Task Author',
  'taskDetail.loginForMore': 'Login for more',
  'taskDetail.loginMessage': 'Log in to see full information',
  'taskDetail.completedTasks': 'completed tasks',
  'taskDetail.memberSince': 'Member since',
  'taskDetail.similarTasks': 'Similar Tasks',
  'taskDetail.apply': 'Apply for Task',
  'taskDetail.askQuestion': 'Ask Question',
  'taskDetail.applicationsCount': 'applications',
  'taskDetail.timeAgo': 'ago',
  'taskDetail.today': 'Today',
  'taskDetail.tomorrow': 'Tomorrow',
  'taskDetail.days': 'days',
  'taskDetail.flexible': 'Flexible',
  'taskDetail.asap': 'As soon as possible',
  'taskDetail.negotiable': 'Negotiable',
  'taskDetail.urgency.same_day': 'Urgent - today',
  'taskDetail.urgency.within_week': 'Within a week',
  'taskDetail.urgency.flexible': 'Flexible deadline',
  'taskDetail.urgency.default': 'Unspecified',
  'taskDetail.status': 'Status',
  'taskDetail.statusTypes.vacant': 'Vacant',
  'taskDetail.statusTypes.applied': 'Applied',
  'taskDetail.statusTypes.inProgress': 'In Progress',
  'taskDetail.statusTypes.done': 'Done',
  'taskDetail.statusTypes.archived': 'Archived',
  'taskDetail.appliedTooltip': 'You have applied to this task. The client may accept or reject your application.',
  'taskDetail.inProgressBanner.title': 'Task No Longer Available',
  'taskDetail.inProgressBanner.message': 'This task is currently being managed by a professional and is no longer accepting applications.',
  'taskDetail.published.today': 'published today',
  'taskDetail.published.thisWeek': 'published this week',
  'taskDetail.published.thisMonth': 'published this month',
  'taskDetail.published.someTimeAgo': 'published some time ago',

  'taskDetail.share': 'Share',
  'taskDetail.shareText': 'Check out this task on Trudify',
  'taskDetail.shareSuccess': 'Shared successfully!',
  'taskDetail.linkCopied': 'Link copied to clipboard!',
  'taskDetail.copyError': 'Failed to copy link',
  'taskDetail.editTask': 'Edit Task',
  'taskDetail.cancelTask': 'Cancel Task',
  'taskDetail.confirmCancel': 'Are you sure you want to cancel this task?',
  'taskDetail.cancelSuccess': 'Task cancelled successfully',
  'taskDetail.cancelError': 'Failed to cancel task',
  'taskDetail.cancelDialog.title': 'Cancel This Task?',
  'taskDetail.cancelDialog.warning': 'This action cannot be undone and will:',
  'taskDetail.cancelDialog.consequence1': 'Delete all applications',
  'taskDetail.cancelDialog.consequence1NoApps': 'Remove the task (no applications yet)',
  'taskDetail.cancelDialog.consequence2': 'Remove the task from search results',
  'taskDetail.cancelDialog.consequence3': 'Delete all task data permanently',
  'taskDetail.cancelDialog.confirm': 'Are you sure you want to cancel this task?',
  'taskDetail.cancelDialog.btnCancel': 'Cancel',
  'taskDetail.cancelDialog.btnConfirm': 'Yes, Cancel Task',
  'taskDetail.cancelDialog.processing': 'Cancelling...',
  'taskDetail.activity': 'Task Activity',
  'taskDetail.applications': 'Applications',
  'taskDetail.questions': 'Questions',
  'taskDetail.accept': 'Accept',
  'taskDetail.reject': 'Reject',
  'taskDetail.message': 'Message',
  'taskDetail.reply': 'Reply',
  'taskDetail.yourReply': 'Your reply:',
  'taskDetail.price': 'Price',
  'taskDetail.timeline': 'Timeline',
  'taskDetail.tasks': 'tasks',
  'taskDetail.cancel': 'Cancel',
  'taskDetail.writeReply': 'Write your reply...',
  'taskDetail.sendReply': 'Send Reply',

  // Ask Question Dialog
  'taskDetail.askQuestionDialog.title': 'Ask a Question',
  'taskDetail.askQuestionDialog.placeholder': 'What would you like to know about this task?',
  'taskDetail.askQuestionDialog.submit': 'Post Question',
  'taskDetail.askQuestionDialog.characterCount': '{{current}}/{{max}} characters',
  'taskDetail.askQuestionDialog.minLength': 'Question must be at least {{min}} characters',
  'taskDetail.askQuestionDialog.maxLength': 'Question must be at most {{max}} characters',

  // Questions Section
  'taskDetail.questions.empty.title': 'No questions yet',
  'taskDetail.questions.empty.message': 'Be the first to ask a question about this task!',
  'taskDetail.questions.unanswered': 'Unanswered',
  'taskDetail.questions.answered': 'Answered',
  'taskDetail.questions.loading': 'Loading questions...',

  // Answer Dialog
  'taskDetail.answerDialog.title': 'Answer Question',
  'taskDetail.answerDialog.placeholder': 'Write your answer...',

  // Success/Error Messages
  'taskDetail.questionPosted': 'Your question has been posted successfully!',
  'taskDetail.questionError': 'Failed to post question. Please try again.',
  'taskDetail.answerPosted': 'Your answer has been posted successfully!',
  'taskDetail.answerError': 'Failed to post answer. Please try again.',

  // Not Found Page
  'taskDetail.notFound.title': 'Task Not Found',
  'taskDetail.notFound.description': "The task you're looking for doesn't exist or has been removed.",
  'taskDetail.notFound.browseTasks': 'Browse Tasks',

  // Error Page
  'taskDetail.error.title': 'Something went wrong!',
  'taskDetail.error.description': "We couldn't load this task. This might be a temporary issue.",
  'taskDetail.error.retry': 'Try Again',
  'taskDetail.error.goHome': 'Go to Home',

  // Posted Tasks Page (Customer View)
  'postedTasks.title': 'My Posted Tasks',
  'postedTasks.subtitle': 'Manage tasks you\'ve created',
  'postedTasks.loading': 'Loading your tasks...',
  'postedTasks.createTask': 'Create Task',
  'postedTasks.filter.all': 'All',
  'postedTasks.filter.open': 'Open',
  'postedTasks.filter.inProgress': 'In Progress',
  'postedTasks.filter.awaitingConfirmation': 'Awaiting Confirmation',
  'postedTasks.filter.completed': 'Completed',
  'postedTasks.filter.cancelled': 'Cancelled',
  'postedTasks.applicationsCount': '{{count}} applications',
  'postedTasks.viewApplications': 'View Applications',
  'postedTasks.viewDetails': 'View Details',
  'postedTasks.editTask': 'Edit Task',
  'postedTasks.acceptedProfessional': 'Accepted Professional',
  'postedTasks.completedBy': 'Completed by professional',
  'postedTasks.awaitingYourConfirmation': 'Awaiting Your Confirmation',
  'postedTasks.markedComplete': 'marked this task as complete',
  'postedTasks.markComplete': 'Mark Complete',
  'postedTasks.reportIssue': 'Report Issue',
  'postedTasks.cancelTask': 'Cancel Task',
  'postedTasks.cancelTaskConfirm': 'Are you sure you want to cancel this task? The professional will be notified.',
  'postedTasks.reopenTask': 'Reopen Task',
  'postedTasks.reopenTaskConfirm': 'Reopen this task? You\'ll be able to review and edit the details before posting again.',
  'postedTasks.empty.title': 'Got an idea? Let\'s make it happen! 💡',
  'postedTasks.empty.description': 'Your task board is empty and ready for action. From home repairs to creative projects, professionals are waiting to help.',
  'postedTasks.empty.subtext': 'Post your first task in under 2 minutes. It\'s free, simple, and you\'ll start receiving applications right away!',
  'postedTasks.empty.createButton': 'Create Task',
  'postedTasks.empty.hint': '✨ Tip: The more details you provide, the better applications you\'ll receive',
  'postedTasks.firstApplication.title': 'Great news! You have your first application',
  'postedTasks.firstApplication.message': 'Check the application details and respond to the professional',

  // Cancel Task Dialog
  'cancelTask.title': 'Cancel Task',
  'cancelTask.professional': 'Professional',
  'cancelTask.professionalNotification': 'The professional will be notified about the cancellation',
  'cancelTask.reasonLabel': 'Why are you canceling this task?',
  'cancelTask.reasons.noShow': 'Professional never showed up',
  'cancelTask.reasons.abandoned': 'Professional abandoned the work',
  'cancelTask.reasons.unresponsive': 'Professional is unresponsive',
  'cancelTask.reasons.changedRequirements': 'My requirements changed',
  'cancelTask.reasons.foundAlternative': 'Found another solution',
  'cancelTask.reasons.other': 'Other reason',
  'cancelTask.descriptionLabel': 'Additional details (optional)',
  'cancelTask.descriptionPlaceholder': 'Please provide any additional context...',
  'cancelTask.descriptionHint': 'Help us understand what happened',
  'cancelTask.confirmButton': 'Cancel Task',
  'cancelTask.rateLimit.title': 'You can cancel {{remaining}} more task(s) this month',
  'cancelTask.rateLimit.message': 'To prevent abuse, users can cancel up to {{max}} tasks per month',
  'cancelTask.rateLimit.lastWarning': 'This is your last free cancellation this month. Use it wisely!',
  'cancelTask.limitExceeded.title': 'Monthly cancellation limit reached',
  'cancelTask.limitExceeded.message': 'You\'ve reached your cancellation limit for this month. Frequent cancellations may affect your account standing. Please contact support if you need assistance.',

  // Customer Remove Professional Dialog
  'customerRemove.title': 'Remove Professional from Task',
  'customerRemove.subtitle': 'Removing from: {{taskTitle}}',
  'customerRemove.professional': 'Professional',
  'customerRemove.acceptedOn': 'Accepted',
  'customerRemove.workingFor': 'Working for',
  'customerRemove.professionalNotification': 'The professional will be notified and your task will be reopened for new applications',
  'customerRemove.taskWillReopen': 'Your task will be reopened for new applications',
  'customerRemove.limitWarning.title': 'You can remove {{remaining}} more professional(s) this month',
  'customerRemove.limitWarning.message': 'Customers can remove up to {{max}} professional per month. Frequent removals may indicate poor hiring decisions.',
  'customerRemove.limitExceeded.title': 'Monthly removal limit reached',
  'customerRemove.limitExceeded.message': 'You\'ve reached your removal limit for this month. Please contact support if you have a serious issue.',
  'customerRemove.reasonLabel': 'Why are you removing this professional?',
  'customerRemove.reasons.professional_unresponsive': 'Professional not responding to messages',
  'customerRemove.reasons.professional_no_show': 'Professional missed scheduled appointments',
  'customerRemove.reasons.quality_concerns': 'Work quality not meeting standards',
  'customerRemove.reasons.safety_issues': 'Safety concerns with the work',
  'customerRemove.reasons.timeline_issue': 'Cannot meet my deadline',
  'customerRemove.reasons.scope_disagreement': 'Disagreement about scope or price',
  'customerRemove.reasons.my_circumstances_changed': 'My circumstances have changed',
  'customerRemove.reasons.mutual_agreement': 'Mutual agreement to end assignment',
  'customerRemove.reasons.other': 'Other reason',
  'customerRemove.descriptionLabel': 'Additional details (optional)',
  'customerRemove.descriptionPlaceholder': 'Please explain the situation...',
  'customerRemove.descriptionHint': 'This helps us improve the platform',
  'customerRemove.confirmButton': 'Remove Professional',
  'postedTasks.removeProfessional': 'Remove Professional',
  'postedTasks.removeProfessionalSuccess': 'Professional removed. Task reopened for new applications.',
  'postedTasks.cannotRemove': 'Cannot remove',
  'postedTasks.markCompleteSuccess': 'Task marked as complete successfully!',
  'postedTasks.markCompleteSuccessDescription': 'The professional has been notified.',
  'postedTasks.markCompleteError': 'Failed to mark task as complete',

  // Edit Task Page
  'editTask.title': 'Edit Task',
  'editTask.subtitle': 'Update your task details to attract more professionals',
  'editTask.editingBanner': 'Editing: {{title}}',
  'editTask.editingSubtext': 'Make changes to improve your task',
  'editTask.help': 'Need help? Contact our support team',
  'editTask.freeToEdit': 'Free to edit',
  'editTask.noPayment': 'No payment until work starts',
  'editTask.instantSave': 'Changes saved instantly',
  'editTask.prosWillSee': 'Professionals will see updates',
  'editTask.savingChanges': 'Saving changes...',
  'editTask.saveChanges': 'Save Changes',
  'editTask.cancelEdit': 'Cancel',
  'editTask.successMessage': 'Task updated successfully!',
  'editTask.errorMessage': 'Error updating task. Please try again.',
  'editTask.cachingNotice': 'Note: Changes may take up to 1 hour to appear on the public task page due to performance optimization.',
  'editTask.imageUpload.error': 'Image upload failed',

  // Task Hints System
  'taskHints.noApplications.title': 'No applications yet? Your task has been open for {{days}} days',
  'taskHints.improveTask': 'Improve Task',
  'taskHints.dismiss': 'Dismiss',
  'taskHints.suggestions.increasePrice': 'Try increasing your budget to attract more professionals',
  'taskHints.suggestions.addPhotos': 'Add or update photos to better showcase what needs to be done',
  'taskHints.suggestions.improveDescription': 'Add more details to your description to make it clearer',
  'taskHints.suggestions.adjustDeadline': 'Consider making the deadline more flexible',
  'taskHints.suggestions.updateTask': 'Review and update your task details to make it more appealing',

  // Email Notification Templates
  // 1. Application Received
  'notifications.email.applicationReceived.subject': '{{customer_name}}, you have a new application!',
  'notifications.email.applicationReceived.heading': 'New Application Received!',
  'notifications.email.applicationReceived.message': '{{professional_name}} has applied to your task "{{task_title}}". Check their profile, reviews, and offer details.',
  'notifications.email.applicationReceived.buttonText': 'View Application',
  'notifications.email.applicationReceived.secondaryButtonText': 'View Profile',
  'notifications.email.applicationReceived.infoTitle': 'Application Details:',
  'notifications.email.applicationReceived.footerText': "You're receiving this because you posted a task on Trudify.",

  // 2. Application Accepted
  'notifications.email.applicationAccepted.subject': 'Your application was accepted!',
  'notifications.email.applicationAccepted.heading': 'Congratulations! Application Accepted',
  'notifications.email.applicationAccepted.message': 'Your application for "{{task_title}}" has been accepted by {{customer_name}}!',
  'notifications.email.applicationAccepted.buttonText': 'View Task Details',
  'notifications.email.applicationAccepted.infoTitle': 'Customer Contact Information:',
  'notifications.email.applicationAccepted.secondaryMessage': 'Get started on the task and maintain good communication with the customer.',
  'notifications.email.applicationAccepted.footerText': "You're receiving this because you applied to a task on Trudify.",

  // 3. Application Rejected
  'notifications.email.applicationRejected.subject': 'Application Update for "{{task_title}}"',
  'notifications.email.applicationRejected.heading': 'Application Not Accepted',
  'notifications.email.applicationRejected.message': 'Your application for "{{task_title}}" was not accepted this time. Don\'t worry! Keep applying to other opportunities.',
  'notifications.email.applicationRejected.buttonText': 'Browse Other Tasks',
  'notifications.email.applicationRejected.secondaryMessage': 'Remember: Each application is a learning experience. Review feedback and keep improving!',
  'notifications.email.applicationRejected.footerText': "You're receiving this because you applied to a task on Trudify.",

  // 4. Message Received
  'notifications.email.messageReceived.subject': 'New message from {{sender_name}}',
  'notifications.email.messageReceived.heading': 'You Have a New Message',
  'notifications.email.messageReceived.message': '{{sender_name}} sent you a message about "{{task_title}}"',
  'notifications.email.messageReceived.buttonText': 'View Message',
  'notifications.email.messageReceived.infoTitle': 'Message Preview:',
  'notifications.email.messageReceived.secondaryMessage': 'Respond quickly to maintain good communication and build trust.',
  'notifications.email.messageReceived.footerText': "You're receiving this because you're involved in a task on Trudify.",

  // 5. Task Completed
  'notifications.email.taskCompleted.subject': 'Task completed: "{{task_title}}"',
  'notifications.email.taskCompleted.heading': 'Task Completed Successfully!',
  'notifications.email.taskCompleted.message': 'The task "{{task_title}}" has been marked as complete. Please rate your experience and help build trust in the community.',
  'notifications.email.taskCompleted.buttonText': 'Leave a Review',
  'notifications.email.taskCompleted.secondaryMessage': 'Your review helps other users find great professionals (or customers) and improves the Trudify community.',
  'notifications.email.taskCompleted.footerText': "You're receiving this because you were involved in a task on Trudify.",

  // 6. Payment Received
  'notifications.email.paymentReceived.subject': 'Payment received for "{{task_title}}"',
  'notifications.email.paymentReceived.heading': 'Payment Received!',
  'notifications.email.paymentReceived.message': 'You received {{amount}} BGN for completing "{{task_title}}". Keep up the great work!',
  'notifications.email.paymentReceived.buttonText': 'View Balance',
  'notifications.email.paymentReceived.infoTitle': 'Payment Details:',
  'notifications.email.paymentReceived.secondaryMessage': 'Earnings are available in your profile. Continue providing excellent service to earn more!',
  'notifications.email.paymentReceived.footerText': "You're receiving this because you completed a task on Trudify.",

  // 7. Welcome Email
  'notifications.email.welcome.subject': 'Welcome to Trudify, {{user_name}}!',
  'notifications.email.welcome.heading': 'Welcome to Trudify!',
  'notifications.email.welcome.message': 'Congratulations! Your account has been created successfully.',
  'notifications.email.welcome.buttonText': 'Get Started',
  'notifications.email.welcome.infoTitle': 'What You Can Do on Trudify:',
  'notifications.email.welcome.secondaryMessage': 'Need help? Check out our guides or contact support.',
  'notifications.email.welcome.footerText': "You're receiving this because you created an account on Trudify.",

  // 8. Removed from Task
  'notifications.email.removedFromTask.subject': 'Task update: "{{task_title}}"',
  'notifications.email.removedFromTask.heading': "You've Been Removed from a Task",
  'notifications.email.removedFromTask.message': 'You have been removed from the task "{{task_title}}" by the customer. The task is now open for other professionals to apply.',
  'notifications.email.removedFromTask.buttonText': 'Browse Other Tasks',
  'notifications.email.removedFromTask.secondaryMessage': 'This does not affect your rating unless there are quality or safety concerns. If you have questions, please contact support.',
  'notifications.email.removedFromTask.footerText': "You're receiving this because you were working on a task on Trudify.",

  // 9. Task Invitation
  'notifications.email.taskInvitation.subject': '{{customer_name}} invited you to a task!',
  'notifications.email.taskInvitation.heading': "You've Been Invited to a Task!",
  'notifications.email.taskInvitation.message': '{{customer_name}} has invited you to apply for their task in {{task_category}}.',
  'notifications.email.taskInvitation.buttonText': 'View Task & Apply',
  'notifications.email.taskInvitation.infoTitle': 'Task Details:',
  'notifications.email.taskInvitation.secondaryMessage': 'You were selected based on your skills and reviews. Apply now before the task is filled!',
  'notifications.email.taskInvitation.footerText': "You're receiving this because you were invited to apply for a task on Trudify.",

  // Common Email Elements
  'notifications.email.common.greeting': 'Hi',
  'notifications.email.common.footerRights': 'All rights reserved.',
};
