// Profile page translations - personal info, professional info, statistics, settings
export const profile = {
  'profile.title': 'My Profile',
  'profile.personalInfo': 'Personal Information',
  'profile.professionalInfo': 'Professional Information',
  'profile.verification': 'Verification',
  'profile.reviews': 'Reviews',
  'profile.stats': 'Statistics',

  'profile.form.firstName': 'First Name',
  'profile.form.lastName': 'Last Name',
  'profile.form.email': 'Email',
  'profile.form.phone': 'Phone',
  'profile.form.location': 'Location',
  'profile.form.bio': 'Bio',
  'profile.form.skills': 'Skills',
  'profile.form.experience': 'Years of Experience',
  'profile.form.hourlyRate': 'Hourly Rate (BGN)',
  'profile.form.vatNumber': 'VAT Number',
  'profile.form.businessName': 'Business Name',
  'profile.form.website': 'Website',

  'profile.verification.identity': 'Identity Verified',
  'profile.verification.business': 'Business Verified',
  'profile.verification.phone': 'Phone Verified',
  'profile.verification.email': 'Email Verified',

  // Profile Page
  'profile.completion': 'Profile completion',
  'profile.settings': 'Settings',
  'profile.tabs.customer': 'Customer',
  'profile.tabs.professional': 'Professional',
  'profile.email': 'Email',
  'profile.phone': 'Phone',
  'profile.location': 'Location',
  'profile.memberSince': 'Member since',
  'profile.editPersonalInfo': 'Edit Personal Info',
  'profile.statistics': 'Statistics',
  'profile.verified': 'Verified',
  'profile.completed': 'Completed',
  'profile.active': 'Active',

  // Avatar Upload
  'profile.avatar.changeAvatar': 'Change Avatar',
  'profile.avatar.selectImage': 'Select Image',
  'profile.avatar.remove': 'Remove',
  'profile.avatar.supportedFormats': 'Supported formats: JPG, PNG, WebP (max 5MB)',
  'profile.avatar.invalidFileType': 'Invalid file type. Please select JPG, PNG, or WebP image.',
  'profile.avatar.fileTooLarge': 'File too large. Please select image smaller than 5MB.',
  'profile.avatar.uploadError': 'Failed to upload image. Please try again.',

  // Statistics Modal
  'profile.statistics.title': 'Account Statistics',
  'profile.statistics.description': 'View your performance metrics and activity overview',
  'profile.statistics.memberSince': 'Member Since',

  // Customer Statistics
  'profile.statistics.customer.overview': 'Customer Overview',
  'profile.statistics.customer.performance': 'Performance Metrics',
  'profile.statistics.customer.successRate': 'Success Rate',
  'profile.statistics.customer.responseRate': 'Response Rate',

  // Professional Statistics
  'profile.statistics.professional.business': 'Business Overview',
  'profile.statistics.professional.performance': 'Performance Metrics',
  'profile.statistics.professional.repeatClients': 'Repeat Clients',
  'profile.statistics.professional.monthlyEarnings': 'Monthly Earnings',

  // Customer Profile
  'profile.customer.personalInfo': 'Personal Information',
  'profile.customer.statistics': 'Statistics',
  'profile.customer.tasksPosted': 'Tasks Posted',
  'profile.customer.tasksCompleted': 'Tasks Completed',
  'profile.customer.averageRating': 'Average Rating',
  'profile.customer.totalSpent': 'Total Spent',
  'profile.customer.recentActivity': 'Recent Activity',
  'profile.customer.taskCompleted': 'Task Completed',
  'profile.customer.taskPosted': 'Task Posted',
  'profile.customer.viewAllTasks': 'View All Tasks',
  'profile.customer.notificationPreferences': 'Notification Preferences',
  'profile.customer.smsNotifications': 'SMS Notifications',
  'profile.customer.smsNotificationsDesc': 'Receive important updates via text message',

  // Professional Profile
  'profile.professional.info': 'Professional Information',
  'profile.professional.title': 'Professional Title',
  'profile.professional.description': 'Description',
  'profile.professional.hourlyRate': 'Hourly Rate',
  'profile.professional.availability': 'Availability',
  'profile.professional.skills': 'Skills',
  'profile.professional.statistics': 'Performance Statistics',
  'profile.professional.completedJobs': 'Completed Jobs',
  'profile.professional.totalEarnings': 'Total Earnings',
  'profile.professional.responseTime': 'Response Time',
  'profile.professional.performance': 'Performance Metrics',
  'profile.professional.profileViews': 'Profile Views',
  'profile.professional.completionRate': 'Completion Rate',
  'profile.professional.monthlyGrowth': 'Monthly Growth',
  'profile.professional.recentWork': 'Recent Work',
  'profile.professional.viewPortfolio': 'View Portfolio',
  'profile.professional.setupTitle': 'Set Up Your Professional Profile',
  'profile.professional.setupDescription': 'Complete your professional profile to start receiving job opportunities and connect with clients.',
  'profile.professional.setupProfile': 'Set Up Professional Profile',
  'profile.professional.businessSettings': 'Business Settings',
  'profile.professional.paymentMethod': 'Payment Method',
  'profile.professional.vatNumber': 'VAT Number',
  'profile.professional.serviceArea': 'Service Area',
  'profile.professional.setupFormDescription': 'Fill out your professional information to showcase your skills and experience.',
  'profile.professional.selectCategories': 'Select Categories',
  'profile.professional.serviceCategories': 'Service Categories',
  'profile.professional.verificationTrust': 'Verification & Trust',
  'profile.professional.phoneVerification': 'Phone Verification',
  'profile.professional.phoneVerificationRequired': 'Required for all professionals',
  'profile.professional.verified': 'Verified',
  'profile.professional.verifyPhone': 'Verify Phone',
  'profile.professional.acceptedPaymentMethods': 'Accepted Payment Methods',
  'profile.professional.businessHours': 'Business Hours',
  'profile.professional.businessHoursPlaceholder': 'e.g., Mon-Fri 8:00-18:00, Sat 9:00-14:00',
  'profile.professional.weekdaysLabel': 'Weekdays (Mon-Fri)',
  'profile.professional.weekendLabel': 'Weekend (Sat-Sun)',
  'profile.professional.startTime': 'Start Time',
  'profile.professional.endTime': 'End Time',
  'profile.professional.noPaymentMethods': 'No payment methods selected',
  'profile.professional.portfolioGallery': 'Portfolio Gallery',
  'profile.professional.portfolioDescription': 'Showcase your best work with before/after images',
  'profile.professional.addServiceCategories': 'Add Your Service Categories',
  'profile.professional.categoriesHelp': 'Help customers find you! Select the services you offer to start receiving task requests.',

  // Professional Setup Form
  'profile.professional.form.titlePlaceholder': 'e.g. Full Stack Developer, UX Designer, Marketing Consultant',
  'profile.professional.form.descriptionPlaceholder': 'Describe your professional background, expertise, and what makes you unique...',
  'profile.professional.form.experience': 'Experience Level',
  'profile.professional.form.portfolio': 'Portfolio URL (Optional)',
  'profile.professional.form.portfolioDescription': 'Link to your website, GitHub, or online portfolio',
  'profile.professional.form.selectedSkills': 'Selected Skills',
  'profile.professional.form.searchSkills': 'Search skills...',
  'profile.professional.form.suggestedSkills': 'Popular Skills',
  'profile.professional.form.addCustomSkill': 'Add Custom Skill',
  'profile.professional.form.customSkillPlaceholder': 'Enter skill name',
  'profile.professional.form.moreSkillsAvailable': 'and {{count}} more...',
  'profile.professional.form.skillsLimitNotice': 'We recommend selecting your top 10 skills for the best results.',
  'profile.professional.form.submitting': 'Creating Profile...',
  'profile.professional.form.createProfile': 'Create Professional Profile',

  // Experience Options
  'profile.professional.form.experienceOptions.beginner': '0-1 years',
  'profile.professional.form.experienceOptions.intermediate': '2-5 years',
  'profile.professional.form.experienceOptions.experienced': '5-10 years',
  'profile.professional.form.experienceOptions.expert': '10+ years',

  // Availability Options
  'profile.professional.form.availabilityOptions.available': 'Available',
  'profile.professional.form.availabilityOptions.busy': 'Busy',
  'profile.professional.form.availabilityOptions.unavailable': 'Unavailable',

  // Form Validation
  'profile.professional.form.validation.titleRequired': 'Professional title is required (minimum 3 characters)',
  'profile.professional.form.validation.descriptionRequired': 'Description is required (minimum 20 characters)',
  'profile.professional.form.validation.rateRequired': 'Hourly rate must be greater than 0',
  'profile.professional.form.validation.skillsRequired': 'Please select at least one skill',

  // Settings Modal
  'profile.settings.description': 'Manage your account preferences and privacy settings',

  // Telegram Connection
  'profile.telegramNotifications': 'Telegram Notifications',
  'profile.telegramDescription': 'Connect your Telegram account to receive instant, free notifications',
  'profile.connected': 'Connected',
  'profile.notConnected': 'Not Connected',
  'profile.connectedAs': 'Connected as',
  'profile.benefits': 'Benefits',
  'profile.instantNotifications': 'Instant notifications (no delays)',
  'profile.freeForever': 'Free forever (no SMS costs)',
  'profile.noEmailSpam': 'No email spam',
  'profile.richMessages': 'Rich messages with buttons and links',
  'profile.connectTelegram': 'Connect Telegram',
  'profile.disconnectTelegram': 'Disconnect Telegram',
  'profile.telegramInstructions': 'Telegram will open in a new window. Click the button in the bot message to complete connection.',
  'profile.telegramConnectError': 'Failed to connect Telegram. Please try again.',
  'profile.telegramDisconnectConfirm': 'Are you sure you want to disconnect Telegram? You will no longer receive instant notifications.',
  'profile.telegramDisconnectError': 'Failed to disconnect Telegram. Please try again.',
  'profile.settings.notifications': 'Notifications',
  'profile.settings.emailNotifications': 'Email Notifications',
  'profile.settings.emailNotificationsDesc': 'Receive updates about your tasks and account',
  'profile.settings.taskUpdates': 'Task Updates',
  'profile.settings.taskUpdatesDesc': 'Get notified when tasks have updates',
  'profile.settings.marketingEmails': 'Marketing Emails',
  'profile.settings.marketingEmailsDesc': 'Receive tips and promotional content',
  'profile.settings.pushNotifications': 'Push Notifications',
  'profile.settings.pushNotificationsDesc': 'Receive instant notifications on your device',
  'profile.settings.weeklyDigest': 'Weekly Digest',
  'profile.settings.weeklyDigestDesc': 'Get a weekly summary of your activity and opportunities',
  'profile.settings.privacy': 'Privacy',
  'profile.settings.profileVisibility': 'Profile Visibility',
  'profile.settings.profileVisibilityDesc': 'Make your profile visible to potential clients',
  'profile.settings.showContactInfo': 'Show Contact Info',
  'profile.settings.showContactInfoDesc': 'Display your contact information publicly',
  'profile.settings.interface': 'Interface',
  'profile.settings.darkMode': 'Dark Mode',
  'profile.settings.darkModeDesc': 'Switch to dark theme interface',
  'profile.settings.dangerZone': 'Danger Zone',
  'profile.settings.deleteAccount': 'Delete Account',
  'profile.settings.deleteAccountDesc': 'Permanently delete your account and all data',
  'profile.settings.deleteAccountConfirm': 'Account deletion will be implemented soon',

  // Customer Profile Form
  'profile.form.name': 'Full Name',
  'profile.form.saving': 'Saving...',
  'profile.form.validation.nameRequired': 'Name is required (minimum 2 characters)',
  'profile.form.validation.emailRequired': 'Email is required',
  'profile.form.validation.emailInvalid': 'Please enter a valid email address',
  'profile.form.validation.phoneRequired': 'Phone number is required',
  'profile.form.validation.phoneInvalid': 'Please enter a valid phone number',
  'profile.form.validation.locationRequired': 'Location is required (minimum 3 characters)',
};
