// Professionals page and professional detail translations
export const professionals = {
  'professionals.hero.title': 'Find Trusted Professionals',
  'professionals.hero.subtitle':
    'Browse verified specialists by category and find the perfect match for your needs',
  'professionals.hero.badge': 'Professional Network',
  'professionals.hero.stats.verified.value': 'Verified Professionals',
  'professionals.hero.stats.verified.label': 'Getting more every day',
  'professionals.hero.stats.ratings.value': 'Trusted Quality',
  'professionals.hero.stats.ratings.label': 'Based on true ratings & reviews',
  'professionals.hero.stats.jobs.value': 'Active Network',
  'professionals.hero.stats.jobs.label': 'Getting many jobs done every day',
  'professionals.searchPlaceholder':
    'Search categories... (e.g., repair, cleaning, tutoring)',
  'professionals.search.popular': 'Popular',
  'professionals.allCategories': 'All Categories',
  'professionals.featuredTitle': 'Featured Professionals',
  'professionals.viewProfile': 'View Profile',
  'professionals.rating': 'Rating',
  'professionals.completedJobs': 'Completed Jobs',
  'professionals.card.completedJobs': 'completed jobs',
  'professionals.card.lookingForFirstTask': 'Ready for first task',
  'professionals.card.waitingForReviews': 'Waiting for first reviews',
  'professionals.startingFrom': 'Starting from',
  'professionals.noResults': 'No categories match your search',
  'professionals.categoryResults': 'categories found',
  'professionals.filterBy': 'Filter by',
  'professionals.location': 'Location',
  'professionals.experience': 'Experience',
  'professionals.priceRange': 'Price Range',
  'professionals.availability': 'Availability',
  'professionals.findPerfect': 'Find the Perfect Professional',
  'professionals.discoverTrusted':
    'Discover trusted professionals with proven track records and exceptional reviews',
  'professionals.popularCategories': 'Popular categories',
  'professionals.refineSearch': 'Refine your search results',
  'professionals.professionalsAvailable': 'professionals available',
  'professionals.noProfessionalsFound': 'No Professionals Found',
  'professionals.tryAdjustingFilters': 'Try adjusting your filters or search terms to find more professionals.',
  'professionals.noMatchingResults':
    'No professionals available matching your criteria. Try broadening your search.',
  'professionals.mostActive': 'Most Active',
  'professionals.specialists': 'Specialists',
  'professionals.stars': 'stars',
  'professionals.gender.male': 'Male',
  'professionals.gender.female': 'Female',
  'professionals.filters.category': 'Category',
  'professionals.filters.city': 'City',
  'professionals.filters.location': 'Location',
  'professionals.filters.minimumRating': 'Minimum Rating',
  'professionals.filters.minRating': 'Min Rating',
  'professionals.filters.minJobs': 'Min Jobs',
  'professionals.filters.jobs': 'jobs',
  'professionals.filters.sortBy': 'Sort By',
  'professionals.filters.genderPreference': 'Gender Preference',
  'professionals.filters.activityLevel': 'Activity Level',
  'professionals.filters.all': 'All',
  'professionals.filters.topPerformersOnly': 'Top Performers Only',
  'professionals.filters.locationPlaceholder': 'Sofia, Plovdiv, Varna...',
  'professionals.filters.any': 'Any',
  'professionals.filters.anyShort': 'Any',
  'professionals.typing.plumber': 'plumber in Sofia',
  'professionals.typing.cleaner': 'house cleaning specialist',
  'professionals.typing.electrician': 'certified electrician',
  'professionals.typing.tutor': 'English tutor',
  'professionals.typing.photographer': 'wedding photographer',
  'professionals.typing.handyman': 'handyman services',
  'professionals.recommendedTitle': 'RECOMMENDED PROFESSIONALS',
  'professionals.filters.clear': 'Clear',
  'professionals.filters.clearAll': 'Clear all filters',
  'professionals.filters.fourPlusStars': '4+ stars',
  'professionals.filters.fiveStarsOnly': '5 stars only',
  'professionals.filters.anyRating': 'By Rating',
  'professionals.filters.showProfessionalsWithAnyRating':
    'Show professionals with any rating',
  'professionals.filters.locationPlaceholderDesktop': '📍 Location',
  'professionals.sorting.featuredFirst': 'Top Choice',
  'professionals.sorting.featuredFirstDesc': 'Best professionals',
  'professionals.sorting.highestRating': 'By Rating',
  'professionals.sorting.highestRatingDesc': 'Top rated',
  'professionals.sorting.mostExperience': 'By Experience',
  'professionals.sorting.mostExperienceDesc': 'Most orders',
  'professionals.filters.sortResultsBy': 'Sort Results By',
  'professionals.filters.sortResultsTitle': 'Sort Results',
  'professionals.filters.sortResultsDescription':
    'Choose how to order professionals',
  'professionals.filters.selectMinimumRating': 'Select Minimum Rating',
  'professionals.filters.showingVerifiedFirst':
    'Showing verified top performers first',
  'professionals.filters.proTip': 'Pro Tip',
  'professionals.filters.proTipMessage':
    'Try "{{sortOption}}" for quality-assured professionals with verified credentials',
  'professionals.filters.sortingBy': 'Sorting by {{option}}',
  'professionals.filters.sortingDescFeatured':
    'Showing verified top performers first',
  'professionals.filters.sortingDescRating':
    'Professionals with highest ratings appear first',
  'professionals.filters.sortingDescJobs':
    'Most experienced professionals appear first',
  'professionals.filters.activeFilters': 'Active Filters',
  'professionals.filters.filterApplied': '{{count}} filter applied',
  'professionals.filters.filtersApplied': '{{count}} filters applied',
  'professionals.filters.showProfessionalsWithRating':
    'Show professionals with {{rating}}+ star ratings',
  'professionals.filters.showPerfectRating':
    'Show only professionals with perfect 5-star ratings',

  // Results section
  'professionals.results.showing': 'Showing {{count}} professionals',
  'professionals.results.loading': 'Loading professionals...',
  'professionals.results.noResults.title': 'No professionals found',
  'professionals.results.noResults.description':
    'Try adjusting your filters or search in a different area',
  'professionals.results.noResults.clearFilters': 'Clear Filters',
  'professionals.results.error.title': 'Oops! Something went wrong',
  'professionals.results.error.description': 'Our servers need a coffee break',
  'professionals.results.error.subtext': "Don't worry, we're on it!",
  'professionals.results.error.retry': 'Try Again',
  'professionals.results.mockTitle': 'Mock Professionals (Reference)',
  'professionals.results.mockDescription':
    'Sample data showcasing future features: portfolios, certifications, edge cases',
  'professionals.results.mockBadge1': 'For Development Reference',
  'professionals.results.mockBadge2': 'Not Real Users',
  'professionals.results.featured.title': 'Featured Professionals',
  'professionals.results.featured.description':
    'Check out these top-rated professionals from our network',

  // Pagination
  'professionals.pagination.previous': 'Previous',
  'professionals.pagination.next': 'Next',
  'professionals.pagination.pageOf': 'Page {{current}} of {{total}}',

  'professionalDetail.about': 'About the Professional',
  'professionalDetail.reviews': 'reviews',
  'professionalDetail.online': 'Online',
  'professionalDetail.offline': 'Last seen recently',
  'professionalDetail.verified.phone': 'Phone',
  'professionalDetail.verified.id': 'ID',
  'professionalDetail.stats.completedTasks': 'Tasks',
  'professionalDetail.stats.yearsExperience': 'Years',
  'professionalDetail.stats.yearsExperienceLabel': 'years',
  'professionalDetail.stats.experience': 'Experience',
  'professionalDetail.stats.responseTime': 'Response',
  'professionalDetail.defaultBio': 'Professional specialist with experience in the field.',
  'professionalDetail.actions.inviteToApply': 'Invite to Apply',
  'professionalDetail.actions.contact': 'Contact',
  'professionalDetail.actions.share': 'Share',
  'professionalDetail.contactHours': 'Available',
  'professionalDetail.services.title': 'Services & Pricing',
  'professionalDetail.services.pricingNote.title': 'Pricing Information',
  'professionalDetail.services.pricingNote.description':
    'Final prices are agreed upon individually based on task complexity and requirements.',
  'professionalDetail.portfolio.title': 'My Demos',
  'professionalDetail.portfolio.noWork': 'No demos available yet',
  'professionalDetail.portfolio.before': 'Before',
  'professionalDetail.portfolio.after': 'After',
  'professionalDetail.portfolio.viewMore': 'View all demos',
  'professionalDetail.portfolio.showcase': 'Professional work showcase',
  'professionalDetail.completedTasks.title': 'Completed Tasks',
  'professionalDetail.completedTasks.noTasks': 'No completed tasks yet',
  'professionalDetail.completedTasks.hugePotential': 'This professional has huge potential!',
  'professionalDetail.completedTasks.comingSoon': 'Great work coming soon...',
  'professionalDetail.completedTasks.watchThisSpace': 'Watch this space for amazing completed projects!',
  'professionalDetail.completedTasks.viewTask': 'View Task',
  'professionalDetail.completedTasks.completedOn': 'Completed on',
  'professionalDetail.reviews.title': 'Reviews & Ratings',
  'professionalDetail.reviews.count': 'reviews',
  'professionalDetail.reviews.recentRating': 'Recent rating',
  'professionalDetail.reviews.excellent': 'Excellent',
  'professionalDetail.reviews.noReviews': 'No reviews yet',
  'professionalDetail.reviews.beFirst':
    'Be the first to review this professional',
  'professionalDetail.reviews.showMore': 'Show all reviews',
  'professionalDetail.reviews.allReviews': 'All Reviews',
  'professionalDetail.reviews.avgRating': 'Average Rating',
  'professionalDetail.reviews.more': 'more',
  'professionalDetail.completedTasks.stats.tasksCompleted': 'Tasks Completed',
  'professionalDetail.completedTasks.stats.avgRating': 'Avg Rating',
  'professionalDetail.completedTasks.stats.fiveStarTasks': '5-Star Tasks',
  'professionalDetail.verified': 'Verified',
  'professionals.results.featured.title': 'Featured Professionals',
  'professionals.results.featured.description': 'Check out these top-rated professionals from our network',
  'professionals.results.showing': 'Showing {{count}} professionals',
  'professionals.results.showing_zero': 'Showing 0 professionals',
  'professionals.results.showing_one': 'Showing 1 professional',
  'professionals.results.showing_other': 'Showing {{count}} professionals',
  'professionals.results.loading': 'Loading professionals...',
  'professionals.filters.filtersButton': 'Filters',
  'professionals.filters.active': 'active',
  'professionals.filters.proTipText': 'Use multiple filters to find the perfect professional. You can always reset them!',
  'professionals.filters.showResults': 'Show Results',
  'professionals.filters.reset': 'Reset',
  'professionals.filters.filters': 'Filters',
};
