// Professionals page and professional detail translations
export const professionals = {
  'professionals.hero.title': 'Find Trusted Professionals',
  'professionals.hero.subtitle':
    'Browse verified specialists by category and find the perfect match for your needs',
  'professionals.hero.badge': 'Professional Network',
  'professionals.hero.stats.verified.value': 'Verified Professionals',
  'professionals.hero.stats.verified.label': 'Getting more every day',
  'professionals.hero.stats.ratings.value': 'Trusted Quality',
  'professionals.hero.stats.ratings.label': 'Based on true ratings & reviews',
  'professionals.hero.stats.jobs.value': 'Active Network',
  'professionals.hero.stats.jobs.label': 'Getting many jobs done every day',
  'professionals.searchPlaceholder':
    'Search categories... (e.g., repair, cleaning, tutoring)',
  'professionals.search.popular': 'Popular',
  'professionals.search.categories': 'Service Categories',
  'professionals.allCategories': 'All Categories',
  'professionals.featuredTitle': 'Featured Professionals',
  'professionals.viewProfile': 'View Profile',
  'professionals.suggestTask': 'Suggest a task',
  'professionals.viewProfessionals': 'View Professionals',
  'professionals.rating': 'Rating',
  'professionals.completedJobs': 'Completed Jobs',
  'professionals.card.completedJobs': 'completed jobs',
  'professionals.card.completedJobsShort': 'jobs',
  'professionals.card.lookingForFirstTask': 'Ready for first task',
  'professionals.card.waitingForReviews': 'Waiting for first reviews',
  'professionals.startingFrom': 'Starting from',
  'professionals.noResults': 'No categories match your search',
  'professionals.categoryResults': 'categories found',
  'professionals.filterBy': 'Filter by',
  'professionals.location': 'Location',
  'professionals.experience': 'Experience',
  'professionals.priceRange': 'Price Range',
  'professionals.availability': 'Availability',
  'professionals.findPerfect': 'Find the Perfect Professional',
  'professionals.discoverTrusted':
    'Discover trusted professionals with proven track records and exceptional reviews',
  'professionals.popularCategories': 'Popular categories',
  'professionals.refineSearch': 'Refine your search results',
  'professionals.professionalsAvailable': 'professionals available',
  'professionals.noProfessionalsFound': 'No Professionals Found',
  'professionals.tryAdjustingFilters': 'Try adjusting your filters or search terms to find more professionals.',
  'professionals.noMatchingResults':
    'No professionals available matching your criteria. Try broadening your search.',
  'professionals.mostActive': 'Most Active',
  'professionals.specialists': 'Specialists',
  'professionals.stars': 'stars',
  'professionals.gender.male': 'Male',
  'professionals.gender.female': 'Female',
  'professionals.filters.category': 'Category',
  'professionals.filters.city': 'City',
  'professionals.filters.location': 'Location',
  'professionals.filters.minimumRating': 'Minimum Rating',
  'professionals.filters.minRating': 'Min Rating',
  'professionals.filters.minJobs': 'Min Jobs',
  'professionals.filters.jobs': 'jobs',
  'professionals.filters.sortBy': 'Sort By',
  'professionals.filters.genderPreference': 'Gender Preference',
  'professionals.filters.activityLevel': 'Activity Level',
  'professionals.filters.all': 'All',
  'professionals.filters.topPerformersOnly': 'Top Performers Only',
  'professionals.filters.locationPlaceholder': 'Sofia, Plovdiv, Varna...',
  'professionals.filters.any': 'Any',
  'professionals.filters.anyShort': 'Any',
  'professionals.typing.plumber': 'plumber in Sofia',
  'professionals.typing.cleaner': 'house cleaning specialist',
  'professionals.typing.electrician': 'certified electrician',
  'professionals.typing.tutor': 'English tutor',
  'professionals.typing.photographer': 'wedding photographer',
  'professionals.typing.handyman': 'handyman services',
  'professionals.recommendedTitle': 'RECOMMENDED PROFESSIONALS',
  'professionals.filters.clear': 'Clear',
  'professionals.filters.clearAll': 'Clear all filters',
  'professionals.filters.fourPlusStars': '4+ stars',
  'professionals.filters.fiveStarsOnly': '5 stars only',
  'professionals.filters.anyRating': 'By Rating',
  'professionals.filters.showProfessionalsWithAnyRating':
    'Show professionals with any rating',
  'professionals.filters.locationPlaceholderDesktop': '📍 Location',
  'professionals.sorting.featuredFirst': 'Top Choice',
  'professionals.sorting.featuredFirstDesc': 'Best professionals',
  'professionals.sorting.highestRating': 'By Rating',
  'professionals.sorting.highestRatingDesc': 'Top rated',
  'professionals.sorting.mostExperience': 'By Experience',
  'professionals.sorting.mostExperienceDesc': 'Most orders',
  'professionals.filters.sortResultsBy': 'Sort Results By',
  'professionals.filters.sortResultsTitle': 'Sort Results',
  'professionals.filters.sortResultsDescription':
    'Choose how to order professionals',
  'professionals.filters.selectMinimumRating': 'Select Minimum Rating',
  'professionals.filters.showingVerifiedFirst':
    'Showing verified top performers first',
  'professionals.filters.proTip': 'Pro Tip',
  'professionals.filters.proTipMessage':
    'Try "{{sortOption}}" for quality-assured professionals with verified credentials',
  'professionals.filters.sortingBy': 'Sorting by {{option}}',
  'professionals.filters.sortingDescFeatured':
    'Showing verified top performers first',
  'professionals.filters.sortingDescRating':
    'Professionals with highest ratings appear first',
  'professionals.filters.sortingDescJobs':
    'Most experienced professionals appear first',
  'professionals.filters.activeFilters': 'Active Filters',
  'professionals.filters.filterApplied': '{{count}} filter applied',
  'professionals.filters.filtersApplied': '{{count}} filters applied',
  'professionals.filters.showProfessionalsWithRating':
    'Show professionals with {{rating}}+ star ratings',
  'professionals.filters.showPerfectRating':
    'Show only professionals with perfect 5-star ratings',

  // Results section
  'professionals.results.showing': 'Showing {{count}} professionals',
  'professionals.results.loading': 'Loading professionals...',
  'professionals.results.noResults.title': 'No professionals found',
  'professionals.results.noResults.description':
    'Try adjusting your filters or search in a different area',
  'professionals.results.noResults.clearFilters': 'Clear Filters',
  'professionals.results.error.title': 'Oops! Something went wrong',
  'professionals.results.error.description': 'Our servers need a coffee break',
  'professionals.results.error.subtext': "Don't worry, we're on it!",
  'professionals.results.error.retry': 'Try Again',
  'professionals.results.mockTitle': 'Mock Professionals (Reference)',
  'professionals.results.mockDescription':
    'Sample data showcasing future features: portfolios, certifications, edge cases',
  'professionals.results.mockBadge1': 'For Development Reference',
  'professionals.results.mockBadge2': 'Not Real Users',
  'professionals.results.featured.title': 'Featured Professionals',
  'professionals.results.featured.description':
    'Check out these top-rated professionals from our network',
  'professionals.results.allLoaded': "You've reached the end of the list",
  'professionals.results.loadingMore': 'Loading more professionals...',

  // Pagination
  'professionals.pagination.previous': 'Previous',
  'professionals.pagination.next': 'Next',
  'professionals.pagination.pageOf': 'Page {{current}} of {{total}}',

  'professionalDetail.about': 'About the Professional',
  'professionalDetail.reviews': 'reviews',
  'professionalDetail.online': 'Online',
  'professionalDetail.offline': 'Last seen recently',
  'professionalDetail.verified.phone': 'Phone',
  'professionalDetail.verified.id': 'ID',
  'professionalDetail.stats.completedTasks': 'Tasks',
  'professionalDetail.stats.yearsExperience': 'Years',
  'professionalDetail.stats.yearsExperienceLabel': 'years',
  'professionalDetail.stats.experience': 'Experience',
  'professionalDetail.stats.responseTime': 'Response',
  'professionalDetail.defaultBio': 'Professional specialist with experience in the field.',
  'professionalDetail.actions.suggestMyTask': 'Suggest My Task',
  'professionalDetail.actions.inviteToApply': 'Invite to Apply',
  'professionalDetail.actions.contact': 'Contact',
  'professionalDetail.actions.share': 'Share',
  'professionalDetail.contactHours': 'Available',
  'professionalDetail.services.title': 'Services & Pricing',
  'professionalDetail.services.pricingNote.title': 'Pricing Information',
  'professionalDetail.services.pricingNote.description':
    'Final prices are agreed upon individually based on task complexity and requirements.',
  'professionalDetail.portfolio.title': 'My Demos',
  'professionalDetail.portfolio.noWork': 'No demos available yet',
  'professionalDetail.portfolio.emptyState': "This professional hasn't updated their demos yet. We keep asking them to add it - maybe we'll be lucky enough tomorrow!",
  'professionalDetail.portfolio.emptyStateCTA': 'Check back soon for their amazing work showcase',
  'professionalDetail.portfolio.before': 'Before',
  'professionalDetail.portfolio.after': 'After',
  'professionalDetail.portfolio.viewMore': 'View all demos',
  'professionalDetail.portfolio.showcase': 'Professional work showcase',

  // Gallery (Premium Feature)
  'professionalDetail.gallery.title': 'Work Gallery',
  'professionalDetail.gallery.subtitle': 'Examples of completed work',
  'professionalDetail.gallery.imageView': 'Image View',

  'professionalDetail.completedTasks.title': 'Completed Tasks',
  'professionalDetail.completedTasks.noTasks': 'No completed tasks yet',
  'professionalDetail.completedTasks.hugePotential': 'This professional has huge potential!',
  'professionalDetail.completedTasks.comingSoon': 'Great work coming soon...',
  'professionalDetail.completedTasks.watchThisSpace': 'Watch this space for amazing completed projects!',
  'professionalDetail.completedTasks.emptyState': 'This professional performed tons of tasks but not with us at this point. Please help us enrich this page with your task!',
  'professionalDetail.completedTasks.emptyStateCTA': 'Suggest them a task and be their first client on our platform',
  'professionalDetail.completedTasks.viewTask': 'View Task',
  'professionalDetail.completedTasks.completedOn': 'Completed on',
  'professionalDetail.reviews.title': 'Reviews & Ratings',
  'professionalDetail.reviews.count': 'reviews',
  'professionalDetail.reviews.recentRating': 'Recent rating',
  'professionalDetail.reviews.excellent': 'Excellent',
  'professionalDetail.reviews.noReviews': 'No reviews yet',
  'professionalDetail.reviews.beFirst':
    'Be the first to review this professional',
  'professionalDetail.reviews.emptyState': 'Reviews are coming for this professional. Suggest them a task to rate them also!',
  'professionalDetail.reviews.emptyStateCTA': 'Be the first to work with this professional and leave a review',
  'professionalDetail.reviews.showMore': 'Show all reviews',
  'professionalDetail.reviews.allReviews': 'All Reviews',
  'professionalDetail.reviews.avgRating': 'Average Rating',
  'professionalDetail.reviews.more': 'more',
  'professionalDetail.completedTasks.stats.tasksCompleted': 'Tasks Completed',
  'professionalDetail.completedTasks.stats.avgRating': 'Avg Rating',
  'professionalDetail.completedTasks.stats.fiveStarTasks': '5-Star Tasks',
  'professionalDetail.completedTasks.pendingReview': 'Pending review',
  'professionalDetail.completedTasks.viewAll': 'View all {{count}} tasks',
  'professionalDetail.completedTasks.totalTasks': 'Total Tasks',
  'professionalDetail.completedTasks.averageRatingStars': 'Average rating: {{rating}} stars',
  'professionalDetail.verified': 'Verified',
  'professionalDetail.shareText': 'Check out this professional on Trudify',
  'professionalDetail.shareSuccess': 'Shared successfully!',
  'professionalDetail.linkCopied': 'Link copied to clipboard!',
  'professionalDetail.copyError': 'Failed to copy link',
  'professionals.filters.filtersButton': 'Filters',
  'professionals.filters.active': 'active',
  'professionals.filters.proTipText': 'Use multiple filters to find the perfect professional. You can always reset them!',
  'professionals.filters.showResults': 'Show Results',
  'professionals.filters.reset': 'Reset',
  'professionals.filters.filters': 'Filters',

  // Professional Badges
  'professionals.badge.topProfessional': 'Top Professional',
  'professionals.badge.topProfessional.tooltip': 'Completed {{count}} tasks in the last 30 days',
  'professionals.badge.earlyAdopter': 'Early Adopter',
  'professionals.badge.earlyAdopter.tooltip': 'One of the first professionals in {{category}}',
  'professionals.badge.earlyAdopter.tooltipGeneric': 'One of the first professionals on the platform',

  // Invite Modal
  'inviteModal.title': 'Invite Professional to Task',
  'inviteModal.subtitle': 'Select which task to invite {{name}} to',
  'inviteModal.selectLabel': 'Choose a task',
  'inviteModal.selectPlaceholder': 'Select your task',
  'inviteModal.noTasks': "You don't have any open tasks yet.",
  'inviteModal.createTaskHint': 'Create a task first to invite this professional.',
  'inviteModal.confirmText': 'will receive a notification about this task invitation.',
  'inviteModal.sendInvitation': 'Send Invitation',
  'inviteModal.success': 'Invitation sent!',
  'inviteModal.successDescription': '{{name}} will be notified about your task.',
  'inviteModal.error': 'Failed to send invitation',
  'inviteModal.alreadyInvited': 'Already invited',
  'inviteModal.alreadyInvitedDescription': 'You have already invited {{name}} to this task.',
  'inviteModal.alreadyInvitedProfessional': 'Already invited',
  'inviteModal.alreadyInvitedProfessionalDescription': 'You have already invited {{name}} to your task. They may apply within 24 hours if available.',
  'inviteModal.selfInviteTitle': '🤔 Nice try!',
  'inviteModal.selfInviteDescription': "You can't suggest a task to yourself. But we appreciate the creativity!",
  'inviteModal.createNewTask': 'Create New Task',
  'inviteModal.loadingTasks': 'Loading your tasks...',
  'inviteModal.continue': 'Continue',
};
