// Profile page translations - personal info, professional info, statistics, settings
export const profile = {
  // Auto-save
  'profile.autoSave.saved': 'Changes saved',
  'profile.autoSave.error': 'Failed to save changes',

  // Loading
  'profile.loading': 'Loading your profile...',

  'profile.title': 'My Profile',
  'profile.customerProfileTitle': 'Customer Profile Information',
  'profile.professionalProfileTitle': 'Professional Profile Information',
  'profile.personalInfo': 'Personal Information',
  'profile.professionalInfo': 'Professional Information',
  'profile.verification': 'Verification',
  'profile.reviews': 'Reviews',
  'profile.stats': 'Statistics',

  'profile.form.firstName': 'First Name',
  'profile.form.lastName': 'Last Name',
  'profile.form.email': 'Email',
  'profile.form.phone': 'Phone',
  'profile.form.location': 'Location',
  'profile.form.bio': 'Short intro',
  'profile.form.skills': 'Skills',
  'profile.form.experience': 'Years of Experience',
  'profile.form.hourlyRate': 'Hourly Rate (€)',
  'profile.form.vatNumber': 'VAT Number',
  'profile.form.businessName': 'Business Name',
  'profile.form.website': 'Website',

  'profile.verification.identity': 'Identity Verified',
  'profile.verification.business': 'Business Verified',
  'profile.verification.phone': 'Phone Verified',
  'profile.verification.email': 'Email Verified',

  // Email Verification
  'profile.verifyEmailPrompt': 'Verify your email address',
  'profile.verifyEmailMessage': 'Get important updates about your tasks and applications. A verification email was sent when you signed up.',
  'profile.sendVerificationEmail': 'Send Verification Email',
  'profile.sending': 'Sending...',

  // Profile Page
  'profile.completion': 'Profile completion',
  'profile.settingsTitle': 'Settings',
  'profile.tabs.customer': 'Customer',
  'profile.tabs.professional': 'Professional',
  'profile.switchToCustomer': 'Switch to Customer Profile',
  'profile.switchToProfessional': 'Switch to Professional Profile',
  'profile.emailLabel': 'Email',
  'profile.phone': 'Phone',
  'profile.location': 'Location',
  'profile.selectCity': 'Select your city',
  'profile.memberSince': 'Member since',
  'profile.editPersonalInfo': 'Edit',
  'profile.statistics': 'Statistics',
  'profile.verified': 'Verified',
  'profile.completed': 'Completed',
  'profile.active': 'Active',

  // Avatar Upload
  'profile.avatar.changeAvatar': 'Change Avatar',
  'profile.avatar.selectImage': 'Select Image',
  'profile.avatar.remove': 'Remove',
  'profile.avatar.supportedFormats': 'Supported formats: JPG, PNG, WebP (max 2MB)',
  'profile.avatar.supportedFormatsExtended': 'Supported formats: JPG, PNG, WebP (auto-optimized)',
  'profile.avatar.invalidFileType': 'Invalid file type. Please select JPG, PNG, or WebP image.',
  'profile.avatar.fileTooLarge': 'File too large. Please select image smaller than 2MB.',
  'profile.avatar.fileTooLargeForCompression': 'File too large. Maximum 20MB allowed.',
  'profile.avatar.uploadError': 'Failed to upload image. Please try again.',
  'profile.avatar.deleteError': 'Failed to delete avatar. Please try again.',
  'profile.avatar.compressing': 'Optimizing...',
  'profile.avatar.optimizing': 'Optimizing image',
  'profile.avatar.compressionError': 'Failed to optimize image. Please try again.',
  'profile.avatar.saved': 'saved',

  // Statistics Modal
  'profile.statistics.title': 'Account Statistics',
  'profile.statistics.description': 'View your performance metrics and activity overview',
  'profile.statistics.memberSince': 'Member Since',

  // Customer Statistics
  'profile.statistics.customer.overview': 'Account Overview',
  'profile.statistics.customer.performance': 'Performance Metrics',
  'profile.statistics.customer.successRate': 'Success Rate',
  'profile.statistics.customer.responseRate': 'Response Rate',
  'profile.statistics.customer.noStatsYet': 'Task statistics will appear here as you use the platform.',
  'profile.statistics.customer.tasksPosted': 'Tasks Posted',
  'profile.statistics.customer.applicationsReceived': 'Applications Received',
  'profile.statistics.customer.reviewsGiven': 'Reviews Given',

  // Professional Statistics
  'profile.statistics.professional.business': 'Business Overview',
  'profile.statistics.professional.performance': 'Performance Metrics',
  'profile.statistics.professional.repeatClients': 'Repeat Clients',
  'profile.statistics.professional.monthlyEarnings': 'Monthly Earnings',
  'profile.statistics.professional.activeJobs': 'Active Jobs',
  'profile.statistics.avgResponseTime': 'Avg. Response Time',
  'profile.statistics.responseTime.minutes': '{minutes} min',
  'profile.statistics.responseTime.hour': '1 hour',
  'profile.statistics.responseTime.hours': '{hours} hours',
  'profile.professional.acceptanceRate': 'Acceptance Rate',

  // Quick Actions
  'profile.quickActions.createTask': 'Create Task',

  // Customer Profile
  'profile.customer.personalInfo': 'Personal Information',
  'profile.customer.language': 'Language',
  'profile.customer.preferredContact': 'Notifications',
  'profile.customer.preferredLanguage': 'Preferred Language',
  'profile.customer.preferredContactMethod': 'Where to receive notifications',
  'profile.customer.statistics': 'Statistics',
  'profile.customer.tasksPosted': 'Tasks Posted',
  'profile.customer.tasksCompleted': 'Tasks Completed',
  'profile.customer.averageRating': 'Average Rating',
  'profile.customer.totalSpent': 'Total Spent',
  'profile.customer.recentActivity': 'Recent Activity',
  'profile.customer.taskCompleted': 'Task Completed',
  'profile.customer.taskPosted': 'Task Posted',
  'profile.customer.viewAllTasks': 'View All Tasks',
  'profile.customer.notificationPreferences': 'Notification Preferences',
  'profile.customer.smsNotifications': 'SMS Notifications',
  'profile.customer.smsNotificationsDesc': 'Receive important updates via text message',

  // Professional Profile
  'profile.professional.info': 'Professional Information',
  'profile.professional.identitySection': 'About You',
  'profile.professional.title': 'What you do',
  'profile.professional.bio': 'Short intro',
  'profile.professional.yearsOfExperience': 'Years of Experience',
  'profile.professional.description': 'Description',
  'profile.professional.hourlyRate': 'Hourly Rate',
  'profile.professional.availability': 'Availability',
  'profile.professional.availabilityPreferences': 'Availability & Preferences',
  'profile.professional.status': 'Status',
  'profile.professional.languagesSpoken': 'Languages Spoken',
  'profile.professional.noLanguagesSelected': 'No languages selected',
  'profile.professional.skills': 'Skills',
  'profile.professional.statistics': 'Performance Statistics',
  'profile.professional.completedJobs': 'Completed Jobs',
  'profile.professional.totalEarnings': 'Total Earnings',
  'profile.professional.responseTimeLabel': 'Response Time',
  'profile.professional.performance': 'Performance Metrics',
  'profile.professional.profileViews': 'Profile Views',
  'profile.professional.completionRate': 'Completion Rate',
  'profile.professional.monthlyGrowth': 'Monthly Growth',
  'profile.professional.recentWork': 'Recent Work',
  'profile.professional.viewPortfolio': 'View Portfolio',
  'profile.professional.setupTitle': 'Set Up Your Professional Profile',
  'profile.professional.setupDescription': 'Complete your professional profile to start receiving job opportunities and connect with clients.',
  'profile.professional.setupProfile': 'Set Up Professional Profile',
  'profile.professional.businessSettings': 'Business Settings',
  'profile.professional.paymentMethod': 'Payment Method',
  'profile.professional.vatNumber': 'VAT Number',
  'profile.professional.serviceLocation': 'Service Location',
  'profile.professional.setInPersonalInfo': 'Set in Personal Information section',
  'profile.professional.editInPersonalInfo': 'Edit in Personal Information section',
  'profile.professional.notSet': 'Not set',
  'profile.professional.notVerified': 'Not Verified',
  'profile.professional.titlePlaceholder': 'e.g., Professional Cleaning & Home Services',
  'profile.professional.bioPlaceholder': 'Tell customers about your experience, specializations, and approach...',
  'profile.professional.setupFormDescription': 'Fill out your professional information to showcase your skills and experience.',
  'profile.professional.selectCategories': 'Select Categories',
  'profile.professional.serviceCategories': 'Your categories',
  'profile.serviceCategories.saveCategories': 'Save',
  'profile.serviceCategories.searchPlaceholder': 'Search categories...',
  'profile.serviceCategories.popularCategories': 'Popular Categories',
  'profile.serviceCategories.selected': 'Selected',
  'profile.serviceCategories.clearAll': 'Clear all',
  'profile.professional.verificationTrust': 'Verification & Trust',
  'profile.professional.phoneVerification': 'Phone Verification',
  'profile.professional.phoneVerificationRequired': 'Required for all professionals',
  'profile.professional.verified': 'Verified',
  'profile.professional.verifyPhone': 'Verify Phone',
  'profile.professional.acceptedPaymentMethods': 'Accepted Payment Methods',
  'profile.professional.businessHoursLabel': 'Business Hours',
  'profile.professional.businessHoursPlaceholder': 'e.g., Mon-Fri 8:00-18:00, Sat 9:00-14:00',
  'profile.professional.weekdaysLabel': 'Weekdays (Mon-Fri)',
  'profile.professional.weekendLabel': 'Weekend (Sat-Sun)',
  'profile.professional.startTime': 'Start Time',
  'profile.professional.endTime': 'End Time',
  'profile.professional.noPaymentMethods': 'No payment methods selected',
  'profile.professional.portfolioGallery': 'Portfolio Gallery',
  'profile.professional.portfolioDescription': 'Showcase your best work with before/after images',
  'profile.professional.addServiceCategories': 'Add Your Service Categories',
  'profile.professional.categoriesHelp': 'Help customers find you! Select the services you offer to start receiving task requests.',

  // Auto-suggested categories (based on professional title)
  'profile.professional.suggestedCategories': 'We found matching categories!',
  'profile.professional.suggestedCategoriesHelp': 'Based on your professional title, these categories might be a good fit:',
  'profile.professional.acceptSuggestions': 'Use These Categories',
  'profile.professional.chooseOther': 'Choose Different',
  'profile.professional.categoriesAutoApplied': 'Categories added automatically',
  'profile.professional.categoriesAutoAppliedDescription': 'We matched categories based on your title. You can change them anytime.',
  'profile.professional.categoriesAutoAppliedCheck': 'Did we guess your categories correctly?',
  'profile.professional.looksGood': 'Looks good',

  // Professional Profile Completion
  'profile.professional.incompleteTitle': 'Complete Your Professional Profile',
  'profile.professional.minimumRequired': 'Minimum required',
  'profile.professional.titleField': 'What you do',
  'profile.professional.recommended': 'Recommended',
  'profile.professional.recommendedFields': 'Categories (Services), Location, and Short intro',

  // Professional Listing Banner
  'profile.listing.notListed': 'Your profile is not listed yet',
  'profile.listing.notListedMessage': 'Tell us what you do to appear in our search and receive job opportunities from customers.',
  'profile.listing.incomplete': 'Complete your profile',
  'profile.listing.incompleteMessage': 'Fill in the missing information to improve your visibility and attract more customers.',
  'profile.listing.requirement.title': 'What you do',
  'profile.listing.requirement.bio': 'Short intro',
  'profile.listing.requirement.rate': 'Hourly rate',
  'profile.listing.requirement.skills': 'Your categories',
  'profile.listing.clickToFix': 'Fix',

  // Telegram Connection
  'profile.telegram.clickToConnect': 'Click to connect',

  // Professional Setup Form
  'profile.professional.form.titlePlaceholder': 'e.g. Full Stack Developer, UX Designer, Marketing Consultant',
  'profile.professional.form.descriptionPlaceholder': 'Describe your professional background, expertise, and what makes you unique...',
  'profile.professional.form.experience': 'Experience Level',
  'profile.professional.form.portfolio': 'Portfolio URL (Optional)',
  'profile.professional.form.portfolioDescription': 'Link to your website, GitHub, or online portfolio',
  'profile.professional.form.selectedSkills': 'Selected Skills',
  'profile.professional.form.searchSkills': 'Search skills...',
  'profile.professional.form.suggestedSkills': 'Popular Skills',
  'profile.professional.form.addCustomSkill': 'Add Custom Skill',
  'profile.professional.form.customSkillPlaceholder': 'Enter skill name',
  'profile.professional.form.moreSkillsAvailable': 'and {count} more...',
  'profile.professional.form.skillsLimitNotice': 'We recommend selecting your top 10 skills for the best results.',
  'profile.professional.form.submitting': 'Creating Profile...',
  'profile.professional.form.createProfile': 'Create Professional Profile',

  // Experience Options
  'profile.professional.form.experienceOptions.beginner': '0-1 years',
  'profile.professional.form.experienceOptions.intermediate': '2-5 years',
  'profile.professional.form.experienceOptions.experienced': '5-10 years',
  'profile.professional.form.experienceOptions.expert': '10+ years',

  // Availability Options
  'profile.professional.form.availabilityOptions.available': 'Available',
  'profile.professional.form.availabilityOptions.busy': 'Busy',
  'profile.professional.form.availabilityOptions.unavailable': 'Unavailable',

  // Response Time Options
  'profile.professional.responseTime.1h': 'Within 1 hour',
  'profile.professional.responseTime.2h': 'Within 2 hours',
  'profile.professional.responseTime.4h': 'Within 4 hours',
  'profile.professional.responseTime.24h': 'Within 24 hours',

  // Language Options
  'profile.professional.languages.bg': '🇧🇬 Bulgarian',
  'profile.professional.languages.ru': '🇷🇺 Russian',
  'profile.professional.languages.en': '🇬🇧 English',
  'profile.professional.languages.ua': '🇺🇦 Ukrainian',

  // Payment Method Options
  'profile.professional.paymentMethods.cash': 'Cash',
  'profile.professional.paymentMethods.card': 'Card',
  'profile.professional.paymentMethods.bank_transfer': 'Bank Transfer',
  'profile.professional.paymentMethods.mobile_payment': 'Mobile Payment',

  // Business Hours Labels
  'profile.professional.businessHours.weekdays': 'Mon-Fri',
  'profile.professional.businessHours.weekend': 'Sat-Sun',

  // Form Validation
  'profile.professional.form.validation.titleRequired': 'Professional title is required (minimum 3 characters)',
  'profile.professional.form.validation.descriptionRequired': 'Description is required (minimum 20 characters)',
  'profile.professional.form.validation.rateRequired': 'Hourly rate must be greater than 0',
  'profile.professional.form.validation.skillsRequired': 'Please select at least one skill',

  // Settings Modal
  'profile.settings.description': 'Manage your account preferences and privacy settings',

  // Email Verification Banner
  'profile.email.promptTitle': 'Verify Your Email!',
  'profile.email.promptDescription': 'Verify your email address to receive important notifications about your tasks, applications, and messages.',
  'profile.email.promptDescriptionSecurity': 'Verify your email address for account security and to receive important updates about your tasks and applications.',
  'profile.email.sendVerification': 'Send Email',
  'profile.email.verificationSent': 'Verification email sent! Check your inbox.',
  'profile.email.verificationFailed': 'Failed to send verification email',
  'profile.email.checkInboxTitle': 'Check Your Inbox!',
  'profile.email.checkInboxMessage': 'We sent a verification email to your inbox. Please click the link in the email to verify your address.',
  'profile.email.checkSpam': "Didn't receive it? Check your spam folder or click the button below to resend.",

  // Telegram Connection
  'profile.telegramNotifications': 'Telegram Notifications',
  'profile.telegramDescription': 'Connect your Telegram account to receive instant, free notifications',
  'profile.telegram.promptTitle': 'Get Instant Notifications!',
  'profile.telegram.promptDescription': 'Connect your Telegram account to receive real-time updates about your tasks, applications, and messages.',
  'profile.telegram.connectNow': 'Connect Telegram',
  'profile.telegram.openTelegram': 'Open Telegram to Connect',
  'profile.connected': 'Connected',
  'profile.notConnected': 'Not Connected',
  'profile.connectedAs': 'Connected as',
  'profile.benefits': 'Benefits',
  'profile.instantNotifications': 'Instant notifications (no delays)',
  'profile.freeForever': 'Free forever (no SMS costs)',
  'profile.noEmailSpam': 'No email spam',
  'profile.richMessages': 'Rich messages with buttons and links',
  'profile.connectTelegram': 'Connect Telegram',
  'profile.disconnectTelegram': 'Disconnect Telegram',
  'profile.telegramInstructions': 'Telegram will open in a new window. Click the button in the bot message to complete connection.',
  'profile.telegramConnectError': 'Failed to connect Telegram. Please try again.',
  'profile.telegramDisconnectConfirm': 'Are you sure you want to disconnect Telegram? You will no longer receive instant notifications.',
  'profile.telegramDisconnectError': 'Failed to disconnect Telegram. Please try again.',
  'profile.telegram.disconnectConfirmTitle': 'Disconnect Telegram?',
  'profile.telegram.disconnectConfirmMessage': 'Are you sure you want to stop receiving instant free Telegram notifications?',
  'profile.telegram.disconnectWarning': 'You will lose access to:',
  'profile.telegram.keepTelegram': 'Keep Telegram',
  'profile.telegram.disconnect': 'Disconnect',
  'profile.telegram.steps': 'Follow these steps',
  'profile.telegram.step1': 'Click the button below to open Telegram bot',
  'profile.telegram.step2': 'Click "Start" and copy your Telegram ID',
  'profile.telegram.step3': 'Paste your Telegram ID below',
  'profile.telegram.enterId': 'Enter your Telegram ID',
  'profile.telegram.connect': 'Connect',
  'profile.telegram.invalidIdFormat': 'Please enter a valid Telegram ID (numbers only)',
  'profile.telegram.alreadyConnected': 'This Telegram account is already connected to another Trudify account. Please disconnect it first or use a different Telegram account.',
  'profile.telegram.openBot': 'Open Telegram Bot',
  'profile.telegram.pasteAndConnect': 'Paste ID & Connect',
  'profile.telegram.connecting': 'Connecting...',
  'profile.telegram.autoSaveHint': 'Paste your ID here - it will connect automatically',
  'profile.telegram.clipboardError': 'Clipboard access denied. Please paste the ID manually.',
  'profile.telegram.toast.title': 'Connect Telegram for Instant Notifications',
  'profile.telegram.toast.description': 'Get real-time updates about your tasks, applications, and messages. Free and always on time!',
  'profile.telegram.toast.action': 'Connect Now',
  'profile.settings.notifications': 'Notifications',
  'profile.settings.emailNotifications': 'Email Notifications',
  'profile.settings.emailNotificationsDesc': 'Receive updates about your tasks and account',
  'profile.settings.taskUpdates': 'Task Updates',
  'profile.settings.taskUpdatesDesc': 'Get notified when tasks have updates',
  'profile.settings.marketingEmails': 'Marketing Emails',
  'profile.settings.marketingEmailsDesc': 'Receive tips and promotional content',
  'profile.settings.pushNotifications': 'Push Notifications',
  'profile.settings.pushNotificationsDesc': 'Receive instant notifications on your device',
  'profile.settings.weeklyDigest': 'Weekly Digest',
  'profile.settings.weeklyDigestDesc': 'Get a weekly summary of your activity and opportunities',
  'profile.settings.privacy': 'Privacy',
  'profile.settings.profileVisibility': 'Profile Visibility',
  'profile.settings.profileVisibilityDesc': 'Make your profile visible to potential clients',
  'profile.settings.showContactInfo': 'Show Contact Info',
  'profile.settings.showContactInfoDesc': 'Display your contact information publicly',
  'profile.settings.interface': 'Interface',
  'profile.settings.darkMode': 'Dark Mode',
  'profile.settings.darkModeDesc': 'Switch to dark theme interface',
  'profile.settings.dangerZone': 'Danger Zone',
  'profile.settings.deleteAccount': 'Delete Account',
  'profile.settings.deleteAccountDesc': 'Permanently delete your account and all data',
  'profile.settings.deleteAccountConfirm': 'Account deletion will be implemented soon',

  // Customer Profile Form
  'profile.form.name': 'Full Name',
  'profile.form.saving': 'Saving...',
  'profile.form.validation.nameRequired': 'Name is required (minimum 2 characters)',
  'profile.form.validation.emailRequired': 'Email is required',
  'profile.form.validation.emailInvalid': 'Please enter a valid email address',
  'profile.form.validation.phoneRequired': 'Phone number is required',
  'profile.form.validation.phoneInvalid': 'Enter 8-9 digits (e.g. 88 123 4567)',
  'profile.form.phoneBulgarianOnly': 'Bulgarian phone numbers only',
  'profile.form.validation.locationRequired': 'Location is required (minimum 3 characters)',

  // Gallery (Premium Feature)
  'profile.gallery.title': 'Work Gallery',
  'profile.gallery.description': 'Showcase your best work (max 5 images)',
  'profile.gallery.addImage': 'Add',
  'profile.gallery.captionPlaceholder': 'Caption (optional)',
  'profile.gallery.helperText': 'Click on empty slots to upload images. JPG, PNG, or WEBP (max 5MB each)',
  'profile.gallery.invalidType': 'Invalid file type',
  'profile.gallery.useJpgPngWebp': 'Please use JPG, PNG, or WEBP',
  'profile.gallery.fileTooLarge': 'File too large',
  'profile.gallery.maxSize': 'Maximum 5MB allowed',
  'profile.gallery.compressing': 'Optimizing...',
  'profile.gallery.uploading': 'Uploading...',
  'profile.gallery.smaller': 'smaller',
  'profile.gallery.uploadSuccess': 'Image uploaded',
  'profile.gallery.uploadError': 'Upload failed',
  'profile.gallery.deleteSuccess': 'Image deleted',
  'profile.gallery.deleteError': 'Delete failed',

  // Services & Pricing
  'profile.services.title': 'My prices',
  'profile.services.description': 'List your services with pricing',
  'profile.services.empty': 'No services added yet',
  'profile.services.emptyHint': 'Add your services to let clients know what you offer',
  'profile.services.addService': 'Add Service',
  'profile.services.serviceName': 'Service name',
  'profile.services.serviceNamePlaceholder': 'e.g., Plumbing repair',
  'profile.services.price': 'Price',
  'profile.services.pricePlaceholder': 'e.g., 25 €/hour',
  'profile.services.descriptionLabel': 'Description (optional)',
  'profile.services.descriptionPlaceholder': 'Brief description of this service',
  'profile.services.helperText': 'Add up to {max} services. Changes are saved automatically.',

  // Achievement Banner
  'profile.achievement.title': "You're doing amazing!",
  'profile.achievement.subtitle': 'Thank you for being an outstanding member of our community. Your hard work and dedication make a real difference!',
  'profile.achievement.tasksCompleted': 'tasks',
};
