// Task-related translations - browsing, creating, task cards, task detail
export const tasks = {
  'tasks.title': 'Browse Tasks',
  'tasks.subtitle':
    'Find the perfect task that matches your skills and interests',
  'tasks.searchPlaceholder':
    'Search tasks by keywords, categories, or location...',
  'tasks.filters.title': 'Filters',
  'tasks.filters.category': 'Category',
  'tasks.filters.allCategories': 'All Categories',
  'tasks.filters.location': 'Location',
  'tasks.filters.budget': 'Budget',
  'tasks.filters.budgetMin': 'Min Budget',
  'tasks.filters.budgetMax': 'Max Budget',
  'tasks.filters.deadline': 'Deadline',
  'tasks.filters.status': 'Status',
  'tasks.filters.all': 'All',
  'tasks.filters.open': 'Open',
  'tasks.filters.inProgress': 'In Progress',
  'tasks.filters.completed': 'Completed',
  'tasks.filters.activeFilters': 'Active Filters',
  'tasks.filters.clearAll': 'Clear All',
  'tasks.results': 'results',
  'tasks.sort.newest': 'Newest First',
  'tasks.sort.oldest': 'Oldest First',
  'tasks.sort.budgetHigh': 'Highest Budget',
  'tasks.sort.budgetLow': 'Lowest Budget',
  'tasks.sort.deadline': 'By Deadline',

  'browseTasks.hero.badge': 'Earn Money Now',
  'browseTasks.hero.title1': 'Find Your Next',
  'browseTasks.hero.title2': 'Opportunity',
  'browseTasks.hero.subtitle':
    'Browse verified tasks from real clients. Build your income on your schedule.',
  'browseTasks.search.placeholder':
    'Search tasks by keywords, category or city...',
  'browseTasks.search.popular': 'Popular',
  'browseTasks.search.searchingCategories': 'Searching categories...',
  'browseTasks.search.suggestedCategories': 'Suggested Categories',
  'browseTasks.search.categories': 'Categories',
  'browseTasks.search.cities': 'Cities',
  'browseTasks.filters.title': 'Filtering and sorting',
  'browseTasks.filters.advanced': 'Advanced filters',
  'browseTasks.filters.quick': 'Quick filter',
  'browseTasks.filters.searchPlaceholder':
    'Search for tasks... (e.g., cleaning, repair, delivery)',
  'browseTasks.filters.category': 'Category',
  'browseTasks.filters.allCategories': 'All categories',
  'browseTasks.filters.city': 'City',
  'browseTasks.filters.allCities': 'All cities',
  'browseTasks.filters.cities.sofia': 'Sofia',
  'browseTasks.filters.cities.plovdiv': 'Plovdiv',
  'browseTasks.filters.cities.varna': 'Varna',
  'browseTasks.filters.cities.burgas': 'Burgas',
  'browseTasks.filters.budget': 'Budget',
  'browseTasks.filters.budgetMin': 'Min',
  'browseTasks.filters.budgetMax': 'Max',
  'browseTasks.filters.budgetUpTo': 'Up to 500 BGN',
  'browseTasks.filters.sortBy': 'Sort by',
  'browseTasks.filters.sort.newest': 'Newest',
  'browseTasks.filters.sort.oldest': 'Oldest',
  'browseTasks.filters.sort.highBudget': 'High budget',
  'browseTasks.filters.sort.lowBudget': 'Low budget',
  'browseTasks.filters.filters': 'Filters',
  'browseTasks.filters.active': 'active',
  'browseTasks.filters.reset': 'Reset',
  'browseTasks.filters.showResults': 'Show Results',
  'browseTasks.filters.clear': 'Clear',
  'browseTasks.filters.customRange': 'Custom Range',
  'browseTasks.filters.min': 'Min',
  'browseTasks.filters.max': 'Max',
  'browseTasks.filters.apply': 'Apply',
  'browseTasks.filters.urgency': 'Urgency',
  'browseTasks.filters.urgentSameDay': 'Urgent (Same Day)',
  'browseTasks.filters.thisWeek': 'This Week',
  'browseTasks.filters.flexible': 'Flexible',
  'browseTasks.filters.searchCity': 'Search city...',
  'browseTasks.filters.noCitiesFound': 'No cities found',
  'browseTasks.filters.searchCategory': 'Search categories...',
  'browseTasks.filters.noCategoriesFound': 'No categories found',
  'browseTasks.filters.activeFilters': 'Active filters',
  'browseTasks.filters.clearAll': 'Clear all',
  'browseTasks.sort.newest': 'Newest First',
  'browseTasks.sort.urgent': 'Urgent First',
  'browseTasks.sort.budgetHigh': 'Highest Budget',
  'browseTasks.sort.budgetLow': 'Lowest Budget',
  'browseTasks.sort.deadline': 'Ending Soon',
  'browseTasks.results.shown': 'Shown {{count}} results',
  'browseTasks.results.featured': 'Showing {{count}} popular tasks',
  'browseTasks.results.loading': 'Loading...',
  'browseTasks.results.noTasks.title': 'No tasks found',
  'browseTasks.results.noTasks.description':
    'Try changing the filters or searching by different criteria.',
  'browseTasks.results.noTasks.clearFilters': 'Clear filters',
  'browseTasks.results.suggestedTasks': 'Popular Tasks You Might Like',
  'browseTasks.results.suggestedDescription':
    'Here are some popular tasks from our community',
  'browseTasks.results.featuredTasks': 'Featured Tasks',
  'browseTasks.results.featuredDescription':
    'Check out these popular tasks from our community',
  'browseTasks.results.error.title': 'Oops! Our servers took a coffee break ☕',
  'browseTasks.results.error.description':
    'Looks like our hamsters stopped running on their wheels. Don\'t worry, we\'re giving them espresso shots!',
  'browseTasks.results.error.subtext':
    'This usually fixes itself faster than you can say "cappuccino"',
  'browseTasks.results.error.retry': 'Try Again',
  'browseTasks.pagination.previous': 'Previous',
  'browseTasks.pagination.next': 'Next',
  'browseTasks.search.tags.programming': 'Programming',
  'browseTasks.search.tags.design': 'Design',
  'browseTasks.search.tags.marketing': 'Marketing',
  'browseTasks.search.tags.translation': 'Translation',
  'browseTasks.search.tags.photography': 'Photography',
  'browseTasks.typing.plumber': 'plumber in Sofia',
  'browseTasks.typing.cleaner': 'house cleaning',
  'browseTasks.typing.electrician': 'electrician repair',
  'browseTasks.typing.tutor': 'English tutor',
  'browseTasks.typing.moving': 'moving furniture',
  'browseTasks.typing.gardener': 'garden maintenance',

  'task.budget': 'Budget',
  'task.location': 'Location',
  'task.category': 'Category',
  'task.applications': 'Applications',
  'task.viewDetails': 'View Details',
  'task.apply': 'Apply Now',
  'task.created': 'Created',
  'task.deadline': 'Deadline',

  // Create Task Form
  'createTask.title': 'Post a New Task',
  'createTask.hero.subtitle': 'Describe what you need and let professionals come to you',
  'createTask.hero.freeToPost': 'Free to post',
  'createTask.hero.noPayment': 'No payment until work starts',
  'createTask.hero.avgResponse': 'Average response time: 2 hours',
  'createTask.hero.verifiedPros': 'Verified professionals',
  'createTask.hero.help': 'Need help? Contact our support team',

  // Category Section
  'createTask.category.title': 'What type of service do you need?',
  'createTask.category.subtitle': 'Select the category that best matches your task',
  'createTask.category.selectSubcategory': 'Select a specific service',
  'createTask.category.backToMain': 'Back to main categories',
  'createTask.category.selected': 'Selected Service',
  'createTask.category.categorySelected': 'Selected category. Click the X to change.',
  'createTask.category.tryDifferent': 'Try a different search term',

  // Details Section
  'createTask.details.title': 'Tell us about your task',
  'createTask.details.subtitle': 'Provide clear information to attract the right professionals',
  'createTask.details.titleLabel': 'Task Title',
  'createTask.details.titlePlaceholder': 'What do you need done?',
  'createTask.details.titleHelp': 'Be specific and clear (e.g., "Professional house cleaning for 2-bedroom apartment")',
  'createTask.details.descriptionLabel': 'Description',
  'createTask.details.descriptionPlaceholder': 'Describe your task in detail...',
  'createTask.details.descriptionHelp': 'Include all important details: what needs to be done, any special requirements, tools/materials needed, etc.',
  'createTask.details.requirementsLabel': 'Specific Requirements (Optional)',
  'createTask.details.requirementsPlaceholder': '• Requirement 1\n• Requirement 2\n• Requirement 3',
  'createTask.details.requirementsHelp': 'List any special skills, certifications, or equipment needed (one per line)',

  // Location Section
  'createTask.location.title': 'Where will the task be performed?',
  'createTask.location.subtitle': 'Location helps professionals understand if they can reach you',
  'createTask.location.cityLabel': 'City',
  'createTask.location.cityPlaceholder': 'Select your city',
  'createTask.location.neighborhoodLabel': 'Neighborhood/District',
  'createTask.location.neighborhoodPlaceholder': 'e.g., Лозенец, Витоша, Център',
  'createTask.location.neighborhoodHelp': 'Helps professionals determine if they can reach you',
  'createTask.location.addressLabel': 'Full Address (Optional)',
  'createTask.location.addressPlaceholder': 'Street, building number, entrance, floor, apartment',
  'createTask.location.addressSecurity': 'Address will only be shown to the professional you hire',

  // Budget Section
  'createTask.budget.title': 'What is your budget?',
  'createTask.budget.help': 'Fair budgets get 3x more applications',
  'createTask.budget.typeFixed': 'Fixed Price',
  'createTask.budget.typeRange': 'Price Range',
  'createTask.budget.typeUnclear': "I'm not sure about the budget",
  'createTask.budget.fixedLabel': 'Your Budget',
  'createTask.budget.minLabel': 'Minimum',
  'createTask.budget.maxLabel': 'Maximum',
  'createTask.budget.notSure': "I'm not sure about the budget",

  // Timeline Section
  'createTask.timeline.title': 'When do you need this done?',
  'createTask.timeline.subtitle': 'Let professionals know your timeline',
  'createTask.timeline.urgentTitle': 'Urgent - Same Day',
  'createTask.timeline.urgentDesc': 'I need this done today',
  'createTask.timeline.soonTitle': 'Soon - Within a Week',
  'createTask.timeline.soonDesc': 'I need this done in the next 7 days',
  'createTask.timeline.flexibleTitle': 'Flexible',
  'createTask.timeline.flexibleDesc': "I'm flexible with timing",
  'createTask.timeline.deadlineLabel': 'Specific Deadline (Optional)',
  'createTask.timeline.deadlineHelp': "Leave empty if you don't have a specific deadline",

  // Photos Section
  'createTask.photos.title': 'Add a photo (optional)',
  'createTask.photos.help': 'A photo helps professionals understand your task better',
  'createTask.photos.dragDrop': 'Drag and drop an image here',
  'createTask.photos.orBrowse': 'or click to browse',
  'createTask.photos.takePhoto': 'Take a Photo',
  'createTask.photos.maxSize': '5MB maximum',
  'createTask.photos.formats': 'JPG, PNG, WebP',
  'createTask.photos.uploading': 'Uploading photo...',
  'createTask.photos.fileTooLarge': 'File is too large. Maximum size is 5MB',
  'createTask.photos.invalidType': 'File is not a supported image format',
  'createTask.photos.uploadError': 'Failed to upload photos. Please try again.',
  'createTask.photos.optimizing': 'Optimizing image for faster upload...',
  'createTask.photos.optimized': 'Image optimized successfully',
  'createTask.photos.smaller': 'smaller',

  // Review Section
  'createTask.review.title': 'Review your task',
  'createTask.review.subtitle': 'Make sure everything looks good before posting',
  'createTask.review.submit': 'Post Task',
  'createTask.review.location': 'Location',
  'createTask.review.budget': 'Budget',
  'createTask.review.timeline': 'Timeline',
  'createTask.review.requirements': 'Requirements',
  'createTask.review.photos': 'Photos',
  'createTask.review.noTitle': 'No title yet',
  'createTask.review.noDescription': 'No description yet',
  'createTask.review.noCity': 'No city selected',
  'createTask.review.fillRequired': 'Please fill in all required fields to submit',

  // Errors
  'createTask.errors.categoryRequired': 'Please select a category',
  'createTask.errors.titleTooShort': 'Title must be at least 10 characters',
  'createTask.errors.titleTooLong': 'Title must be less than 200 characters',
  'createTask.errors.descriptionTooShort': 'Description must be at least 30 characters',
  'createTask.errors.descriptionTooLong': 'Description must be less than 2000 characters',
  'createTask.errors.cityRequired': 'City is required',
  'createTask.errors.budgetInvalid': 'Maximum must be greater than minimum',
  'createTask.errors.deadlineInPast': 'Deadline must be today or in the future',

  'createTask.imageUpload.error': 'Image upload failed',

  // Success messages
  'createTask.success': 'Task created successfully!',
  'createTask.successMessage': 'Your task has been posted and is now visible to professionals.',
  'createTask.successWithoutImage': 'Your task has been posted without an image. You can add or change the image by editing the task.',
  'createTask.error': 'Error creating task',
  'createTask.errorMessage': 'Please try again later.',

  'taskCard.apply': 'Apply',
  'taskCard.seeDetails': 'See details',
  'taskCard.anonymous': 'Anonymous',
  'taskCard.budget.from': 'from',
  'taskCard.budget.to': 'up to',
  'taskCard.budget.negotiable': 'Negotiable',
  'taskCard.budget.unclear': 'Budget unclear',
  'taskCard.deadline.flexible': 'Flexible',
  'taskCard.deadline.today': 'Today',
  'taskCard.deadline.tomorrow': 'Tomorrow',
  'taskCard.deadline.days': 'days',
  'taskCard.category.home_repair': 'Home Repairs',
  'taskCard.category.delivery_transport': 'Delivery & Transport',
  'taskCard.category.personal_care': 'Personal Care',
  'taskCard.category.personal_assistant': 'Personal Assistant',
  'taskCard.category.learning_fitness': 'Learning & Fitness',
  'taskCard.category.other': 'Other',
  // Subcategories
  'taskCard.category.courier-services': 'Courier Services',
  'taskCard.category.logistics': 'Logistics',
  'taskCard.category.handyman': 'Handyman',
  'taskCard.category.plumbing': 'Plumbing',
  'taskCard.category.electrical': 'Electrical',
  'taskCard.category.cleaning-services': 'Cleaning',
  'taskCard.category.house-cleaning': 'House Cleaning',
};
